### ISSUE TITLE
Create a prefetch table for windows

### ISSUE THREAD

**Issue by mtmcgrew** [osquery/osquery#2384]
http://www.forensicswiki.org/wiki/Prefetch
http://www.forensicswiki.org/wiki/Windows_Prefetch_File_Format

It would be great to create a table with some of this info http://www.swiftforensics.com/2013/10/windows-prefetch-pf-files.html

filename, file path, last execution time, etc.

**Comment by PoppySeedPlehzr** [comment]
👍 Agreed, This would be hot.

**Comment by MobeenAshraf** [comment]
Hello People,

I am currently working on this table. I  have worked out on this feature request a bit  and would like to know your feedback on  columns that would/should be added  in it.


Following are the columns I'm going to be implementing, let me know if anyone thinks this should be different :

1) Version
2) File Size
3) Executable Name
4) Run Count
5) Last Executed


File also has information on Volume(Name, Date, Number) , Directory Strings, and Resources which are loaded under that file.

**Comment by fmanco** [comment]
Hi @MobeenAshraf really sorry we missed this. Is this something you ended up implementing? If so feel free to submit a PR. I'll leave this open as a `wishlist` issue.

**Comment by directionless** [comment]
I believe this was implemented in #5831

**Comment by theopolis** [comment]
@puffyCid, does the BAM implementation cover this? Sorry if this is a lame question, I am not very familiar with Windows internals.

**Comment by puffyCid** [comment]
@theopolis thats a good question
BAM does not cover prefetch. Both BAM and prefetch can show evidence of execution.
But prefetch also shows a lot more data.
Also BAM exists in the Registry and Prefetch is a file
