### ISSUE TITLE
windows: Anti-Virus application logs virtual table

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#2495]
Our analysts are hoping that we can make use of osquery to parse some Anti-Virus application logs for hits, misses, or just any useful data. This might make a good generic table if we can find a uniform way for the application logs to be parsed, however I'm doubting they'll all be that uniform. We may still be able to extract some similar characteristics for various vendors.

**Comment by directionless** [comment]
I'm not sure osquery can become a generally parser for all application logs. Though, I'd certainly be happy to review/discuss any specific table implementations. 

I'm going to close this as Very Old. Feel free to re-open if you disagree
