### ISSUE TITLE
deployment/documentation: Write up example Chef/Puppet deployment recipes

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#2568]
At Facebook, we use Chef for our internal deployments of osquery. Let's whip up some good example Chef Recipe scripts that should help get people started on deployment of osquery to their organizations. Additionally, a few folks in the slack have made mention that the current [Puppet module](https://github.com/BIAndrews/puppet-osquery) is some what dated. Let's take some time to get this up and running to.

To approach this issue, you'll likely want to roll out a few virtual machines and setup either a Chef or a Puppet server, and then test developing the Chef/Puppet scripts used to install, configure, and maintain osquery on said virtual machines.

Ping @poppyseedplehzr (or thor in the slack) for any details or questions!

**Comment by eth-0** [comment]
+1
