### ISSUE TITLE
windows: Slow queries on process table

### ISSUE THREAD

**Issue by svmastersamurai** [osquery/osquery#2574]
Thanks for getting the Windows version out the door at last! Just wanted to report that querying the process table is pretty slow in the current build compared to native queries via `Powershell` or `WMIC`:

``` shell
PS C:\programdata\osquery> measure-command { & .\osqueryi.exe 'select * from processes;' --json }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 14
Milliseconds      : 544
Ticks             : 145445951
TotalDays         : 0.000168340221064815
TotalHours        : 0.00404016530555556
TotalMinutes      : 0.242409918333333
TotalSeconds      : 14.5445951
TotalMilliseconds : 14544.5951
```

Here is the WInXP naive old-hat way to get the process table:

``` shell
PS C:\programdata\osquery> measure-command { & wmic PROCESS }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 624
Ticks             : 36248542
TotalDays         : 4.19543310185185E-05
TotalHours        : 0.00100690394444444
TotalMinutes      : 0.0604142366666667
TotalSeconds      : 3.6248542
TotalMilliseconds : 3624.8542
```

The slightly better WMI queries are faster

``` shell
PS C:\programdata\osquery> measure-command { Get-WmiObject -Query 'Select * From Win32_Process' }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 103
Ticks             : 1036293
TotalDays         : 1.19941319444444E-06
TotalHours        : 2.87859166666667E-05
TotalMinutes      : 0.001727155
TotalSeconds      : 0.1036293
TotalMilliseconds : 103.6293
```

While the new hotness CIM Queries are slightly quicker

``` shell
PS C:\programdata\osquery> measure-command { Get-CimInstance -Query 'SELECT * From CIM_Process' }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 97
Ticks             : 973313
TotalDays         : 1.12651967592593E-06
TotalHours        : 2.70364722222222E-05
TotalMinutes      : 0.00162218833333333
TotalSeconds      : 0.0973313
TotalMilliseconds : 97.3313
```

**Comment by PoppySeedPlehzr** [comment]
Hey @svmastersamurai !  Thanks for the issue, we're fairly certain the reason for the slow process enumeration is multiple WMI queries. It's currently on my roadmap to port/refactor this functionality, but we just haven't made that happen yet

**Comment by svmastersamurai** [comment]
word, whenever you guys get the chance :)

**Comment by theopolis** [comment]
I don't think we're finished here :) the table implementation is still WMI-based.

**Comment by PoppySeedPlehzr** [comment]
Thanks @theopolis I don't recall what I was thinking when I closed this. I think our roadmap currently is to overhault he processes table to leverage the Windows API to get the process information, which should result in  much faster look up times.

**Comment by cbenning** [comment]
Has anything happened on this front? Any joins we do against this table are quite slow.

**Comment by packetzero** [comment]
@muffins  I thought your non-WMI implementation already landed (https://github.com/osquery/osquery/pull/5293).  I've been using a version of it for a while now, it's good!

**Comment by packetzero** [comment]
@cbenning Tell me about these joins... what is the query?  Are all the columns involved in the joins indexed according to their table spec files?  I remember there still being a bug around joining non-indexed columns will trigger a full table scan for each row to join.

**Comment by cbenning** [comment]
@packetzero I'm just doing anything that filters by PID on the processes table, a simple:

 SELECT 
	*
 FROM processes AS p 
 WHERE p.pid IN (X, Y ,Z);

Takes a couple seconds. When the lists get big it gets nasty.

What version was this improved in?

**Comment by packetzero** [comment]
okay, so that's not a JOIN, and it is filtering on pid, which is an indexed column ... so not the issue I was thinking about.  It sounds like you just need the non-WMI processes implementation of processes table.

**Comment by cbenning** [comment]
@packetzero I am on 3.4.0 (which is the version that this improvment was released). Is there something I need to do in configuration to enable it?

**Comment by packetzero** [comment]
ah... okay, so that version does not have pid filtering if I recall.  So for every item in the IN() list, it will pull entire list of processes and let SQLite do the filtering.  If you are building on your own, there a diff to add that (https://github.com/osql/osql/pull/3/files) .  See the stuff for pidlist.

**Comment by cbenning** [comment]
So I just updated my version and the query is quick. I think I figured 3.4.0 would be new enough. But 4.0.1 is much faster. Thanks

**Comment by Smjert** [comment]
Table re-architected by this commit: https://github.com/osquery/osquery/commit/01ce1ad1cb19737639a2ab4a16b5bf773c9da35d
pid filtering implemented by https://github.com/osquery/osquery/pull/5919
