### ISSUE TITLE
More debugging statements in verbose mode

### ISSUE THREAD

**Issue by yying** [osquery/osquery#2744]
Currently, there are still some `try`/`catch` blocks that ignore raise exceptions. For example: https://github.com/facebook/osquery/blob/master/osquery/config/config.cpp#L387

There should instead transition over to these: https://github.com/facebook/osquery/blob/master/osquery/config/config.cpp#L249

**Comment by vjon** [comment]
What is the preferred location for logging these messages?

In the example you provided, Config::updateSource() opts to return the error message embedded in a Status object. An arguement could be made for logging either inside the function itself immediately prior to the return statement, or having the calling function log the message when it checks for Status::isValid()

Personally, I think it makes more sense for the individual functions to log their own messages before any return values, but so long as it's consistent everywhere (thus avoiding messages being logged multiple times) it would be fine either way.

**Comment by theopolis** [comment]
We have no standard or suggested method. If someone wants to comb the codebase and implement one I'm happy to review. :)
