### ISSUE TITLE
build: Investigate installing cclash on Windows build hosts

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#2770]
Project: https://github.com/inorton/cclash

From the documentation it seems we can integrate this very easily.

**Comment by PoppySeedPlehzr** [comment]
Another project that kept showing up in SO articles was this: https://github.com/frerich/clcache  Might be worth checking out also.

**Comment by theopolis** [comment]
From the notes in `cclash` it seems inspired by `clcache`. I like either, but we already provision a Python 2.7 on build hosts. If `clcache` needs Python 3+ we may be a world of disorganized hurt for Python.
