### ISSUE TITLE
Order of columns when serialized

### ISSUE THREAD

**Issue by iBigQ** [osquery/osquery#2903]
I have an extension code similar to:
```
std::string query = "SELECT name, major FROM os_version";
QueryData results;
auto status_query = queryExternal(query, results);

QueryLogItem item;
item.name = "foo";
item.identifier = "bar";
item.time = osquery::getUnixTime();
item.calendar_time = osquery::getAsciiTime();
item.snapshot_results = results;
std::string json;
serializeQueryLogItemJSON(item, json);
```

The resulting json string is:
```
{
"snapshot":
      [
      {"major":"18","name":"Linux Mint"}
      ],
      "action":"snapshot",
      "name":"foo",
      "hostIdentifier":"bar",
      "calendarTime":"Wed Jan 11 15:34:29 2017 UTC","unixTime":"1484148869"
}
```

As you can see, the requested order was (name, major), but it is the reverse in the json string. I was expecting the json string to be in the same order. Is there anything wrong with my code maybe?
This is critical to me, as I use this string to feed the logger with and expect the result columns to match the request order.

**Comment by theopolis** [comment]
Right, we need a proper JSON implementation to handle the order, see https://github.com/facebook/osquery/issues/2687 for other sort-of-JSON issues we suffer. The only blocker is taking the care to refactor all of the uses of boost-property trees.

**Comment by theopolis** [comment]
We may be able to address this using the new database/query results APIs: https://github.com/facebook/osquery/commit/721dd1ed624b25738c2471dae617d7868df8fb0d

**Comment by directionless** [comment]
I think the json implementation has changed since this was filed. And, I'm not sure it makes sense to guarantee order in what should be unordered structures. I'm closing this. Feel free to reopen if you feel otherwise
