### ISSUE TITLE
Enumerate macOS configuration profiles

### ISSUE THREAD

**Issue by headmin** [osquery/osquery#2990]
I wonder why the table for darwin profiles is not included in default osquery.
would love to see that included.

https://github.com/andrew-d/osquery-profiles

**Comment by groob** [comment]
@andrew-d created this issue a year ago, there's a good discussion with some insight from @pudquick https://github.com/facebook/osquery/issues/1666

The issue with adding a table to osquery directly is that andrew's solution uses exec and there is no proper API for listing profiles on macOS. 
Apple only wants to allow querying this information via MDM. 

I'd argue that having a darwin profiles table is pretty important for mac admins, given that profiles are the primary way  we apply a wide range of settings to macs. But whatever the solution for getting the profiles is going to be, implementing it would be a hack.

**Comment by headmin** [comment]
thanks @groob to link back to the discussion. fully agree with all your concerns here.

**Comment by mike-myers-tob** [comment]
I looked at this again on Friday. There is still no API for enumerating the installed configuration profiles, even though it can be done with Apple's CLI tools `/usr/bin/profiles -C` (or `-L`) and with `system_profiler SPConfigurationProfileDataType`.

As of macOS 11, `/us/bin/profiles` is still leveraging `/System/Library/PrivateFrameworks/ConfigurationProfiles.framework/Versions/A/ConfigurationProfiles`

The extension approach is still the only solution for this under osquery's self-imposed rules.
