### ISSUE TITLE
windows: Yara virtual table support

### ISSUE THREAD

**Issue by stachdude** [osquery/osquery#3027]
Is more of a question than issue - any plans on adding yara to windows build any time soon ?

**Comment by poppyseedplehzr** [comment]
Nothing on the immediate roadmap. Not a whole lot of folks have been asking for it, but I'd say this is something great for an open source developer to take on ;)

**Comment by theopolis** [comment]
@poppyseedplehzr we'd need `yara` available in `choco` right?

**Comment by nigifabio** [comment]
i can take care of it, we are interested too in yara for osquery on windows

**Comment by packetzero** [comment]
I got this working in this [branch](https://github.com/packetzero/osquery/commits/win_yara) . 
 - I haven't tried yara_events yet.
I'm waiting on a [pull request to yara](https://github.com/VirusTotal/yara/pull/975) required to get the library dependencies compiled and linking correctly. When that's ready,  will submit a PR.

**Comment by Smjert** [comment]
The `yara` table has been ported by (#6564), closing.
