### ISSUE TITLE
Completeness of process_open_sockets and listening_ports with Linux containers ?

### ISSUE THREAD

**Issue by stephane-martin** [osquery/osquery#3055]
Hello,

I have a Linux server that only runs a few processes as a host, with all the real stuff happening in containers (Docker and LXC).

The containers have their own namespaced network. Communication with host is classically done with some bridge interfaces and veth.

For example, the host has a "real" internet interface eth0 (176.X.Y.Z) and a bridge interface 'brweb' (10.100.1.1). Inside the "nginx" container there is a namespaced eth0 interface (10.100.1.2), and there an nginx process listens on 10.100.1.2:443. The host eth0 and the container eth0 are linked through a veth.

When i run osqueryi on the host, it looks like `process_open_sockets` and `listen_ports` do not contain information about processes that are run inside the containers. So `listen_ports` does not give anything listening on port 443 and `process_open_sockets` does not show the nginx process. 

Is it the intended behaviour ? How can get network info about the processes run inside containers ?

Tested on Ubuntu Xenial, with kernels 4.4.X, and (sudo) osqueryi 2.3.2.

Thanks !

**Comment by Smjert** [comment]
PR #4024 has implemented this, and testing on latest master (d71420be93a35ad810646110e0e13c679a6521c3) I can confirm that's working, closing.
