### ISSUE TITLE
last - return delta (change) vs. all results

### ISSUE THREAD

**Issue by ghost** [osquery/osquery#3105]
https://osquery.io/docs/tables/#last

Have `last` return the delta/differential vs. the entire results each time

**Comment by Smjert** [comment]
Every non evented table always gathers all the results taken from its data source, it's then the job of the query or the differential engine to give only the delta.
Docs on the differential engine/logs: https://osquery.readthedocs.io/en/latest/deployment/logging/#differential-logs
