### ISSUE TITLE
sudoers implementation does not process #include and #includedir directives

### ISSUE THREAD

**Issue by spasam** [osquery/osquery#3255]
sudoers implementation should iterate through directories and files specified using **#include** and **#includedir** 

Otherwise the contents of the table are misleading and incomplete.

Following text copied from Ubuntu 16.04 sudoers man page:

**Including other files from within sudoers**

It is possible to include other sudoers files from within the sudoers file currently being parsed using the #include and #includedir directives.

This can be used, for example, to keep a site-wide sudoers file in addition to a local, per-machine file.  For the sake of this example the site-wide sudoers file will be /etc/sudoers and the per-machine one will be /etc/sudoers.local.  To include /etc/sudoers.local from within /etc/sudoers we would use the following line in /etc/sudoers:

         #include /etc/sudoers.local

When sudo reaches this line it will suspend processing of the current file (/etc/sudoers) and switch to /etc/sudoers.local.  Upon reaching the end of /etc/sudoers.local, the rest of /etc/sudoers will be processed.  Files that are included may themselves include other files.  A hard limit of 128 nested include files is enforced to prevent include file loops.

If the path to the include file is not fully-qualified (does not begin with a ‘/’, it must be located in the same directory as the sudoers file it was included from.  For example, if /etc/sudoers contains the line:

         #include sudoers.local

the file that will be included is /etc/sudoers.local.

The file name may also include the %h escape, signifying the short form of the host name.  In other words, if the machine's host name is “xerxes”, then

         #include /etc/sudoers.%h

will cause sudo to include the file /etc/sudoers.xerxes.

The #includedir directive can be used to create a sudoers.d directory that the system package manager can drop sudoers file rules into as part of package installation.  For example, given:

         #includedir /etc/sudoers.d

sudo will read each file in /etc/sudoers.d, skipping file names that end in ‘~’ or contain a ‘.’ character to avoid causing problems with package manager or editor temporary/backup files.  Files are parsed in sorted lexical order.  That is, /etc/sudoers.d/01_first will be parsed before /etc/sudoers.d/10_second.  Be aware that because the sorting is lexical, not numeric, /etc/sudoers.d/1_whoops would be loaded after /etc/sudoers.d/10_second.  Using a consistent number of leading zeroes in the file names can be used to avoid such problems.

Note that unlike files included via #include, visudo will not edit the files in a #includedir directory unless one of them contains a syntax error.  It is still possible to run visudo with the -f flag to edit the files directly, but this will not catch the redefinition of an alias that is also present in a different file.

**Comment by Smjert** [comment]
This has been implemented by PR https://github.com/osquery/osquery/pull/5350
