### ISSUE TITLE
One-shot queries on boot

### ISSUE THREAD

**Issue by thedrow** [osquery/osquery#3293]
Currently if a user wants to report something when OSQuery is started he/she needs to send a distributed query after osqueryd enrolls to the server.
It can be useful to add one-shot queries to the schedule that will be executed as soon as the schedule is read and parsed.
This is a good usecase for tables like system information, kernel version or other immutable data that is reported once anyway in snapshot mode.

**Comment by Centurion89** [comment]
+1 this FR. Would be great to add a "run_at_boot" option or something to the configs.

**Comment by theopolis** [comment]
Should the daemon run the one-shot queries whenever the configuration is updated (hash of configuration content changes)? Or the first time the configuration is loaded (when the daemon starts)?

**Comment by Centurion89** [comment]
My preference would be for the latter, but I don't think I have strong opinions about it.

**Comment by thedrow** [comment]
The latter is interesting since it can allow us to deprecate the distributed querying API. If you want a distributed query you can simply add a "one-shot" to the configuration. I'm not sure it's desired though.

**Comment by Centurion89** [comment]
Ah sorry, I sorta misunderstood this request and got it confused with something I previously mentioned. I think there are two distinct asks here:

1) One-shot queries could run whenever osquery detected a config change and would only run a single time
2) Run-at-start queries would run just like other queries, except they would execute as soon as the daemon started up without waiting for $interval

**Comment by arubdesu** [comment]
While some of this sounds like [discovery queries](https://osquery.readthedocs.io/en/stable/deployment/configuration/#discovery-queries), on the Mac we normally handle needs like this via a launchd-driven framework like [outset](https://github.com/chilcote/outset/wiki/FAQ#what-happens-during-boot). It also has on-demand functionality, but this is platform dependent and tied to a specific use case/workflow, where a bunch of things that may not be applicable to this tool are being discussed. Just wanted to chime in with that as a possible framework to decouple it from regular osquery operation.

**Comment by thedrow** [comment]
@arubdesu The problem with discovery queries is that you can't add a condition that is not inside the table(s) you are querying.

**Comment by directionless** [comment]
I'd love to hear more about use cases around oneshot and an osqueryd. 

For myself, I can see how a "run osquery once, with these queries, and put out here" would be interesting. In that mode, you could use it to replace `facter` or similar reporting tools, while keeping their existing idioms. 

But once it moves to a daemon mode, I don't understand how the use case would be.

**Comment by directionless** [comment]
I suspect this is solved by the load decorator queries.
