### ISSUE TITLE
deb_packages is not (or should not be) Linux specific

### ISSUE THREAD

**Issue by guillemj** [osquery/osquery#3323]
Hi!

Just found out about this project (via LWN), and while checking it out noticed the deb_packages "module" which sits under a linux hierarchy. But strictly speaking dpkg is not Linux-specific, it is being used in many POSIX-like OSes, some of which use it as their primary package manager. See the list of porting targets https://wiki.debian.org/Teams/Dpkg/Porting, and of known downstreams https://wiki.debian.org/Teams/Dpkg/Downstream (not all of which use it as their primary package manager though).

Of course the path to the database is hardcoded and will not work on several of those systems, so besides moving it from linux to osix, you should probably change the  dpkg_db_set_dir() call to pass a NULL which will make it use the default or get it from the DPKG_ADMINDIR environment variable if set.

BTW, I'm interested in general in current pain points with the libdpkg API, so if you have any issues, I'd like to know to try to make it easier for external parties to use. :)

**Comment by theopolis** [comment]
Hi @guillemj! Thanks for the notes, you're absolutely correct, we can try to quickly make it work on Darwin too. FreeBSD would be possible but we're being conservative about the dependency set on FreeBSD and preferring to use an explicit-opt-out model so it will take a bit longer.

We do this funky thing where we distribute a 'portable' ELF/Mach-O that has almost all dependencies statically linked so the 'default' package home will usually be invalid with-respect-to the system running osquery (vs. the one building osquery). We can and should be respecting the `DPKG_ADMINDIR` environment variable. So I'll call this a bug too!

**Comment by Smjert** [comment]
Going to close this since the support for passing a different admindir via constraints has been added in https://github.com/osquery/osquery/pull/7549

**Comment by guillemj** [comment]
@Smjert Hi! The main problem from this issue that the support is marked as linux-only when it should instead be posix still remains.

Also the other problem with the admindir still remains too IMO, as it is still hardcoded instead of defaulting to the built-in default from libdpkg. Being able to specify any other admindir is nice, but that does not fix the problem of by default potentially ending up using a different directory than the system default.

So, I'd say this needs to be reopened? :)  (If you prefer I can split these into another issue to make it more manageable?)

**Comment by alessandrogario** [comment]
@guillemj I think there is no real use case right now to make this work on non-Linux platforms. This would also add additional work in maintaining libraries, since we would have to pre-generate and bake the configuration for one additional platform.

For the `DPKG_ADMINDIR` environment variable, I'm not entirely sure right now if it's a good idea to support it within osquery, since we already have a more SQL-friendly approach to it. It would be confusing to have two different settings for it that would potentially specify different folders.
