### ISSUE TITLE
bug: syslog - Received fewer fields than expected in line

### ISSUE THREAD

**Issue by ghost** [osquery/osquery#3327]
**What**

We just started getting errors like the following: `Received fewer fields than expected in line: 95871+00:00","i-82c5b41b","6","authpriv","CRON[17240]:"," pam_unix(cron:session): session opened for user root by (uid=0)"`

Running osquery v2.4.2, utilizing rsyslog + the `syslog` table.

Relevant line provided in the error:

https://github.com/facebook/osquery/blob/master/osquery/events/linux/syslog.cpp#L173

Relevant supporting code: 

https://github.com/facebook/osquery/blob/master/osquery/events/linux/syslog.cpp#L187-L213

**Impact**

Unknown

**Number of impacted machines**

Less than a dozen

**Comment by austinbyers** [comment]
Two more examples:

`Received fewer fields than expected in line: 32a224","6","authpriv","CRON[30680]:"," pam_unix(cron:session): session closed for user root"`

`Received fewer fields than expected in line: rsyslogd: pthread_mutex_lock.c:62: __pthread_mutex_lock: Assertion 'mutex->__data.__owner == 0' failed.`

**Comment by theopolis** [comment]
Those lines seem to be missing the first `"`, here's the expected example format: https://github.com/facebook/osquery/blob/master/osquery/events/linux/tests/syslog_tests.cpp#L33

**Comment by theopolis** [comment]
I wonder if we should be checking `.good()`/`.bad()` and potentially closing/opening the stream. I wonder if the lost character could be recovered? @zwass maybe you have more knowledge of fstream edge cases?

**Comment by roens** [comment]
I too am getting this… by just opening the `osqueryi` shell:
```
$ sudo osqueryi 
Using a virtual database. Need help, type '.help'
osquery> E0406 19:56:05.260185 29211 syslog.cpp:173] Received fewer fields than expected in line: (uid=0)"
```

**Comment by zwass** [comment]
If you `cat` from the pipe that rsyslog is sending the logs into, do they have the appropriate format as specified in https://osquery.readthedocs.io/en/stable/deployment/syslog/#linux-syslog?

**Comment by theopolis** [comment]
We refactored this publisher recently, please let us know if this is still an issue.
