### ISSUE TITLE
Allow more complicated output with --json

### ISSUE THREAD

**Issue by mew1033** [osquery/osquery#3372]
Here's an example query (with a `LIMIT 1` to only see one process):

    SELECT t.iso_8601 AS _time,
           p.name AS process,
           p.pid AS process_id,
           p.cmdline,
           p.cwd,
           p.on_disk,
           p.resident_size AS mem_used,
           p.parent,
           g.groupname,
           g.gid AS group_id,
           u.username AS USER,
           u.uid AS user_id,
           eu.username AS effective_username,
           eg.groupname AS effective_groupname,
           p.path,
           h.md5,
           h.sha1,
           h.sha256,
          (SELECT json_group_array(json_object('fd',pof.fd, 'path',pof.path))
           FROM process_open_files AS pof
           WHERE pof.pid=p.pid
           GROUP BY pof.pid) AS openfiles
    FROM processes AS p
    LEFT JOIN users AS u ON p.uid=u.uid
    LEFT JOIN users AS eu ON p.euid=eu.uid
    LEFT JOIN groups AS g ON p.gid=g.gid
    LEFT JOIN groups AS eg ON p.gid=eg.gid
    LEFT JOIN hash AS h ON p.path=h.path
    LEFT JOIN time AS t
    WHERE parent IS NOT 2
      AND (process NOTNULL
           OR parent NOTNULL) LIMIT 1;

Run this with --json and this is the output I get:

    [
      {
        "USER": "root",
        "_time": "2017-06-01T17:34:43Z",
        "cmdline": "/sbin/init",
        "cwd": "/",
        "effective_groupname": "root",
        "effective_username": "root",
        "group_id": "0",
        "groupname": "root",
        "md5": "177d0701225011e4daca0be3f49eb5d7",
        "mem_used": "940000",
        "on_disk": "1",
        "openfiles": "[{\"fd\":0,\"path\":\"/dev/null\"},{\"fd\":1,\"path\":\"/dev/null\"},{\"fd\":2,\"path\":\"/dev/null\"}]",
        "parent": "0",
        "path": "/sbin/init",
        "process": "init",
        "process_id": "1",
        "sha1": "16338f95b772078cf5b81145d81fa00a5a5d4895",
        "sha256": "903789c5f25b7098f0fa6d0b25f1b97e6823671317cfda8f5ea915de6a04cf87",
        "user_id": "0"
      }
    ]

Makes sense. The "openfiles" column includes a string that is the json representation of all the open files. However, what I actually want is this:

    [
      {
        "USER": "root",
        "_time": "2017-06-01T17:34:43Z",
        "cmdline": "/sbin/init",
        "cwd": "/",
        "effective_groupname": "root",
        "effective_username": "root",
        "group_id": "0",
        "groupname": "root",
        "md5": "177d0701225011e4daca0be3f49eb5d7",
        "mem_used": "940000",
        "on_disk": "1",
        "openfiles": [
          {
            "fd": 0,
            "path": "/dev/null"
          },
          {
            "fd": 1,
            "path": "/dev/null"
          },
          {
            "fd": 2,
            "path": "/dev/null"
          }
        ],
        "parent": "0",
        "path": "/sbin/init",
        "process": "init",
        "process_id": "1",
        "sha1": "16338f95b772078cf5b81145d81fa00a5a5d4895",
        "sha256": "903789c5f25b7098f0fa6d0b25f1b97e6823671317cfda8f5ea915de6a04cf87",
        "user_id": "0"
      }
    ]

I want the "openfiles" object to be a list of other objects. This is quite easy to represent in json, but I have no idea how to represent it in SQL. I suspect it's not possible.

One option I've toyed with is creating a wrapper function that converts specific columns from a json string to actual json (string to python object in python).

**Comment by poppyseedplehzr** [comment]
This might be achievable through a SQL `json` or `pretty` function, similar to what @jedi22 is using [here](https://github.com/facebook/osquery/pull/3320)?  I know that boost property trees allow for one to specify a `pretty=true` option in the `write_json`, maybe we could, in the SQL function, take in the data and re-render it using a ptree that's `pretty=true`?

**Comment by theopolis** [comment]
It seems like the issue is during "print" or "log" we cannot assume the type of a column is `JSON`, we only know `TEXT`.

**Comment by theopolis** [comment]
Related: https://github.com/facebook/osquery/issues/2687

**Comment by directionless** [comment]
I think this is a dup of #2687
