### ISSUE TITLE
Investigate using persistent & immutable data structures

### ISSUE THREAD

**Issue by thedrow** [osquery/osquery#3606]
[Immer](https://sinusoid.es/immer/index.html) is a C++ library that provides persistent and immutable data structures.
QueryResults could benefit from these kind of data structures since we only insert new data and never modify previously inserted data.
Immer does not provide a map data type as of yet but https://github.com/arximboldi/immer/issues/7 is tracking the progress of implementation.
If any of you have ideas where else we can benefit from persistent & immutable data structures I'd love to hear about it.

**Comment by theopolis** [comment]
Folks have suggested this before. Ideally the `QueryData` and `Row` structures become 'smart' and force the table authors to fill in each column. It's possible to meta-program this with the specfiles, but I'd love if we could make something not requiring (number of tables) structures but still enforce compile or runtime-test checks.

**Comment by directionless** [comment]
While I agree with the intent here, I don't think anyone is likely to pick up this work.
