### ISSUE TITLE
Roadmap to C++17

### ISSUE THREAD

**Issue by thedrow** [osquery/osquery#3609]
GCC already [supports everything](https://gcc.gnu.org/projects/cxx-status.html#cxx1z) C++17 has introduced. Clang's [implementation is still partial but nearly complete](https://clang.llvm.org/cxx_status.html#cxx17).
The C++17 standard is not yet finalized so this issue is not very urgent.
At some point, I think we should drop older C++ versions.

We should devise a plan to upgrade our compilers and test osquery that is compiled with `-std=c++1z`.
Contributors should review code and add TODOs where code can be optimized to use the new C++ features.

**Comment by theopolis** [comment]
I'm not sure of the priority, what would you like from C++17 that doesn't exist in boost e.g., string views?

I'd like to start playing nice with OS build systems, meaning introducing a limiting function as the most-current C++ for the least current supported OS build system. Right now we build with a C++14, but can link against C++11 sans maybe newer unique pointer symbols (as an example). We could back down to C++11 but writing in those symbols ourselves.

**Comment by diptanu** [comment]
One of the C++17 features that would be nice to have is if-expressions. 

Sidenote - Clang 5 now has implemented all the C++17 features.

**Comment by thedrow** [comment]
Both Clang and GCC have experimental C++17 support.

**Comment by Smjert** [comment]
We have recently passed to C++17 after merging #6571, closing.
