### ISSUE TITLE
tables: Extend `startup_items` table logic to Linux

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#3627]
Currently this is just a stub table, but it'd be super nice to have the logic extend to pull some generic Linux startup item locations. Either that or let's assess the value of having the table exist in it's current form on linux, which is just a stub table.

**Comment by javuto** [comment]
Let's give this one a try, and get back to osquery development

**Comment by javuto** [comment]
Should I just focus at systemd for this table? It seems to be the common one amongst the linux distributions that we do support via packages.

**Comment by obelisk** [comment]
Confirmed with @javuto that he is actively working on this

**Comment by javuto** [comment]
Do we want to get the contents of the startup items (files in `/etc/init.d`, `/etc/rc.d`...) or just list the files and fit the current table schema?

**Comment by obelisk** [comment]
I don't think we need or want the contents of the file, I would say just fit the current schema.

@muffins

**Comment by muffins** [comment]
Nah no file contents, that'd probably be better suited as a different table, maybe the carves or something?

**Comment by javuto** [comment]
@obelisk the problem of fitting the current schema of `startup_items` is that is too focused on the OSX implementation. For linux it should be `systemd` or `initscripts` instead and having its own schema.

**Comment by mike-myers-tob** [comment]
Completed by #6502 and #6562
