### ISSUE TITLE
tables: extend user_groups table to windows

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#3668]
we have the `user_groups` table on posix, but we need to extend this table to Windows.

**Comment by muffins** [comment]
Note that this might also entail modifying how our users table functions on windows.

**Comment by muffins** [comment]
We have some beautiful templates for this work, if folks are interested drop a line here and I can provide you with some work that's already been started!

**Comment by mike-myers-tob** [comment]
@muffins can I work on this? I am interested in your details on how you want it done.

**Comment by muffins** [comment]
@mike-myers-tob sounds good! I'll shoot you some information over Slack.

**Comment by mike-myers-tob** [comment]
So what we merged in #3855 was a `groups` table for Windows, matching the schema of other platforms. It lists out the groups on the system.

Do we still want a `user_groups` table for Windows (to show the group that every user belongs to)?

**Comment by muffins** [comment]
@mike-myers-tob yeah we'll want to try and match the posix scheme if we can. The need for the `user_groups` table is to act as a bridge between the `groups` table and the `users` table, so you could have something like:
```
osquery> select u.username, g.groupname from users u, user_groups ug, groups g where u.uid = ug.uid and ug.gid = g.gid and u.username = 'thor' limit 10;
+----------+------------------------------+
| username | groupname                    |
+----------+------------------------------+
| thor     |                              |
| thor     | com.apple.sharepoint.group.1 |
| thor     | everyone                     |
| thor     | netaccounts                  |
| thor     | admin                        |
| thor     | _lpadmin                     |
| thor     | _appstore                    |
| thor     | _lpoperator                  |
| thor     | _developer                   |
| thor     | _analyticsusers              |
+----------+------------------------------+
```

**Comment by muffins** [comment]
It _could_ be the case that there's an easier/better way to get this information on windows, and that definitely merits investigation, but the goal here would be the "Single query for all platforms" idea, so if we can it'd be awesome to mimic the posix schemas.

**Comment by Smjert** [comment]
Implemented by https://github.com/osquery/osquery/pull/4217
