### ISSUE TITLE
Add an selinux_events table

### ISSUE THREAD

**Issue by npratley** [osquery/osquery#3740]
When process auditing is enabled on Linux, SELinux events, which are normally logged by auditd to /var/log/audit/audit.log, are lost. It would be great if these events could be handled by osquery and put in an selinux_events table.

**Comment by reSHARMA** [comment]
I would like to contribute on this , can you guide me a bit as this will be my first contribution to osquery

**Comment by theopolis** [comment]
I can provide some pointers and guidance early next week :)

**Comment by reSHARMA** [comment]
Thank you , till then could you suggest me the part of codebase I should emphasis on going through.

**Comment by npratley** [comment]
@reSHARMA thanks for taking a look at this. Here are some comments from @theopolis in Slack that should help.

--------
npratley [12:34 PM] 
Apologies if this has been asked before but if I enable process auditing on linux (Centos), is there any way I can still see SELinux logs which are normally logged by auditd to `/var/log/audit/audit.log`?


theopolis [12:37 PM] 
@npratley that's a great question, unfortunately it's only capturing `user_events`: https://github.com/facebook/osquery/blob/master/osquery/events/linux/audit.cpp#L684 as defined by the event IDs in that range.


[12:38] 
It would be fairly straight forward to add a `selinux_events`: https://github.com/facebook/osquery/blob/master/osquery/events/linux/audit.cpp#L628 just filter those event IDs into a table, hopefully there's some uniformity in the fields such that it could be filtered in a small set of columns


[12:39] 
for example, all `user_events` usually share the fields here: https://github.com/facebook/osquery/blob/master/osquery/tables/events/linux/user_events.cpp#L48

**Comment by reSHARMA** [comment]
@npratley thanks for sharing , they are really very helpful.

**Comment by beddari** [comment]
Did you get anywhere on this? Selinux is pretty much a requirement for me ...

**Comment by npratley** [comment]
@beddari I did not, sorry. Looks as though the audit event handling has moved around a bit, this is now in osquery/osquery/events/linux/auditdnetlink.cpp ?

**Comment by Smjert** [comment]
Implemented by https://github.com/osquery/osquery/pull/4224
