### ISSUE TITLE
macOS: investigate process_file_events subscriber table availability

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#3823]
I'm seeing lots of warnings for `Subscriber table missing: process_file_events` on Darwin deployments with 2.9.0.

**Comment by spasam** [comment]
Schema for this table is also missing in the generated JSON.

**Comment by spasam** [comment]
It is there in 2.7.0 schema and is gone in 2.8.0

**Comment by spasam** [comment]
Could this be related to: https://github.com/facebook/osquery/commit/8dc4268761c8304a3fdab20f26f777b8cb86d3a8

**Comment by spasam** [comment]
Never mind. Looks like moving this table to legacy was intentional.

**Comment by Smjert** [comment]
The table doesn't exist anymore.
