### ISSUE TITLE
tables: PE Header Metadata table

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#3890]
Virtual Table to parse out PE and Rich Header metadata information.

**Comment by muffins** [comment]
Will update the description with more details here shortly, this was mostly to keep track of the request ;)

**Comment by muffins** [comment]
Might also be super neat to convert the compiler type to it's associated string: https://github.com/dishather/richprint/blob/master/comp_id.txt

**Comment by mike-myers-tob** [comment]
Trail of Bits makes an MIT-licensed PE-parsing library, for what it's worth https://github.com/trailofbits/pe-parse
