### ISSUE TITLE
The chrome_extensions table doesn't seem to find extensions in Chromium

### ISSUE THREAD

**Issue by fincham** [osquery/osquery#3912]
Hi all,

On my Debian stretch and Ubuntu xenial machines this plugin returns empty even though Chromium is installed.

I assume it's looking in the wrong place in the filesystem.

**Comment by theopolis** [comment]
How did you install Chromium?

**Comment by fincham** [comment]
Just an "apt install chromium"

**Comment by rmetzler** [comment]
According to https://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions Chromium uses the path  `~/.config/chromium/Default/Extensions`.

The code doesn't check the path https://github.com/facebook/osquery/blob/master/osquery/tables/applications/browser_chrome.cpp#L32

**Comment by rmetzler** [comment]
I didn't was on my Ubuntu machine the time I updated the comment, but came over this problem today. This is a simple workaround, that works for me.

```bash
cd ~/.config
ln -sf ./chromium google-chrome
```

**Comment by fincham** [comment]
Is this likely to be fixed in upstream osquery?

**Comment by isg-sysadmin** [comment]
Thanks, confirmed working properly now.
