### ISSUE TITLE
Add additional OS X malware/adware from EtreCheck

### ISSUE THREAD

**Issue by reedloden** [osquery/osquery#4042]
https://github.com/etresoft/EtreCheck has a pretty long list of OS X malware/adware, and I don't think `osx-attacks.conf` covers it all. Should see what needs to be added.

https://github.com/etresoft/EtreCheck/blob/master/EtreCheck/adware.plist

**Comment by Smjert** [comment]
I'm going to close this since we want to deprecate packs: https://github.com/osquery/osquery/issues/7592
