### ISSUE TITLE
"Recursive" searches on results

### ISSUE THREAD

**Issue by geekscrapy** [osquery/osquery#4069]
Looking for a way to perform recursive searches on results. End result is to have a query which will provide file table results for values in services.path and/or services.module_path columns. We're intending to use OSQuery as a snapshotting tool, but not for continious monitoring. Therefore we need to collect everything we want to in one go, then analyse later.

An example of this is to enumerate all .services and upon each of the services.path results, query the path column with the .file table. Hence the recursion.

For example given the following query:
SELECT file.filename, file.uid, file.gid FROM file INNER JOIN services ON file.path=services.path;

Whilst this provides some output when the services.path is soley a path to a binary, when it contains command arguments or environment variables that row is ignored. For example, this is completly useless with the services.module_path column where most of the values start %systemroot%.

How may I go about doing this internally? Could a table be created in which if JOINed upon it would parse the input, expand the path (if environment variables are used) and allow you to then JOIN with another table, like .file?

**Comment by theopolis** [comment]
Absolutely! You can do all of this with SQLite. If you LEFT JOIN you will not lose results for right hand nulls. If you place the services into a sub query you can replace the variable expansions (very simply use the replace functions). There may be a more elaborate way to replace that handles arbitrary variables too.

**Comment by theopolis** [comment]
As an example:
```sql
select path, type from (
  select replace(path, '%userdir%', '/home/teddy') as directory from (
    select '%userdir%/Mail' as path
  )
) paths, file where file.directory = paths.directory;
```

In this example I am using a mock query in the inner-most subquery: `select '%userdir%/Mail' as path` definitely replace that with the `services` table you mentioned. The next layer does the replacement and renames the column using `as`. Be sure not to have any overlapping column names, but you can definitely bubble-up columns from the inner query to the outer-most by continuing to select them at each level.
