### ISSUE TITLE
"docker_container_processes" Not Showing Anything.

### ISSUE THREAD

**Issue by sanghyunhong** [osquery/osquery#4070]
Hello, 

I have been running OSQuery on my EC2 instances in AWS as well as on my Mac laptop, and I am running at least three containers per host. However, I cannot get anything from the command 'select * from docker_container_processes where id = <container_id>' in the OSQueryi.

Can you look at this issue as soon as possible, since I think it's the critical?

S.

**Comment by spasam** [comment]
Are you running as root or with privileged to connect to the domain socket?

**Comment by sanghyunhong** [comment]
I installed the OSQuery with the command 'brew install osquery' and installed the docker with the installation image from the docker website.

- Doesn't this way provide the root access to the docker daemon or socket?
- How do I run the OSQuery as "root or with privileged to connect to the domain socket"?

**Comment by spasam** [comment]
Are you not seeing results from osquery daemon or are you trying above SQL from osqueryi command line interface? And how are you starting osqueryi? With sudo?

**Comment by spasam** [comment]
@sanghyunhong Can you check if you have this file?

`ls -la /var/run/docker.sock`

**Comment by sanghyunhong** [comment]
@spasam: Yep, I have it
`lrwxr-xr-x`  1 root  daemon  65 Jan 19 15:17 /var/run/docker.sock -> /Users/<laptop-name>/Library/Containers/com.docker.docker/Data/s60`

**Comment by spasam** [comment]
@sanghyunhong Are you on osquery slack channel. May be we can troubleshoot there!

Can you drop the where clause and just search for containers?
```
sudo osqueryi
select * from docker_containers;
```

**Comment by sanghyunhong** [comment]
@spasam: I will be right there on the slack.

**Comment by sanghyunhong** [comment]
@spasam: FYI, here is the output from the command line
`osquery> select * from docker_containers;
+------------------------------------------------------------------+----------------+-----------+------------------------------------------------------------------+------------------------+------------+---------+-----------+
| id                                                               | name           | image     | image_id                                                         | command                | created    | state   | status    |
+------------------------------------------------------------------+----------------+-----------+------------------------------------------------------------------+------------------------+------------+---------+-----------+
| 38795e9b2e54ac8f424c7248384d67a5c2bdea22f318440cc1abb93708f8572b | /my-apache-app | httpd:2.4 | 7239615c06455b6be1df0e5932e196667e15e5415c641c7a7d4a18d0946c876d | httpd-foreground       | 1516394099 | running | Up 2 days |
| 6520929a1cdb310ef7dfeccaec3d3320a200773ffdd497bbc547e6401d334c9a | /webserver     | nginx     | 3f8a4339aadda5897b744682f5f774dc69991a81af8d715d37a616bb4c99edf5 | nginx -g 'daemon off;' | 1516393093 | running | Up 2 days |
+------------------------------------------------------------------+----------------+-----------+------------------------------------------------------------------+------------------------+------------+---------+-----------+`

**Comment by sanghyunhong** [comment]
I check with the osquery version **osqueryi version 3.2.4** and found that the _docker_container_processes_ is working.
