### ISSUE TITLE
make deps fails when attempted on ClearLinux

### ISSUE THREAD

**Issue by FireballDWF** [osquery/osquery#4072]
$ make deps
Traceback (most recent call last):
  File "./tools/get_platform.py", line 210, in <module>
    familyAction()
  File "./tools/get_platform.py", line 182, in familyAction
    family, osType = _platform()
TypeError: 'NoneType' object is not iterable

**Comment by theopolis** [comment]
Hi @FireballDWF! I'd love to help, but I need more information about what's going on. I see that `make deps` is failing, but can you elaborate? What platform / OS are you using, has this ever worked before, etc. Please try to provide as much information as possible.

**Comment by FireballDWF** [comment]
Steps to Reproduce, assuming having docker.

1. sudo docker run -it clearlinux:latest bash
2. swupd update
3. swupd bundle-add network-basic-dev ruby-basic
4. git clone https://github.com/facebook/osquery.git
5. cd osquery
6. make deps

**Comment by theopolis** [comment]
Ah, I'm not very familiar with ClearLinux. This error with the platform detection is most likely the first of several porting errors you'll run into. 

If you're looking to just use osquery, I'd recommend using: https://pkg.osquery.io/linux/osquery-2.11.2_1.linux_x86_64.tar.gz
