### ISSUE TITLE
codename in os_version table returns incorrect information on Windows

### ISSUE THREAD

**Issue by keeleysam** [osquery/osquery#4080]
The codename key in the os_version table returns incorrect information about the product on systems which aren't running a standard client build of Windows 10, instead returning what the info would be if it were running on Windows 10.

For example, on Windows 7 Professional, you get results like this:
```
columns":{
"build":"7601",
"codename":"Windows 10 Pro",
"major":"6",
"minor":"1",
"name":"Microsoft Windows 7 Professional ",
"patch":"",
"platform":"windows",
"platform_like":"windows",
"version":"6.1.7601"
},
```

It also returns nothing on Windows 10 LTSB 2016.

This is due to a mapping of DWORDs to strings here https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/os_version.cpp#L75

Perhaps instead of the mapping there is a way to retrieve this information from Windows itself which would save work in the future from having to maintain it.

**Comment by keeleysam** [comment]
Thinking about this - isn't `name` really going to be basically the same thing with Microsoft at the front?

I think codename should probably be removed from Windows.

**Comment by obelisk** [comment]
@muffins Thoughts?

**Comment by muffins** [comment]
From my limited searching around, we got these codenames from [this doc](https://en.wikipedia.org/wiki/List_of_Microsoft_codenames), which clearly isn't a good way to do this, but I wasn't able to find a good API for pulling a string with the codename. I'm of the opinion that the information isn't hurting being there, and if we can find a better way to dynamically query the data we should just leave it. I'll take a look and see if we can find a better solution.

**Comment by FritzX6** [comment]
This is still affecting users with Windows 7. Any hope to see this addressed?

**Comment by muffins** [comment]
Ah so there's two things I'm noticing here. Windows does provide an exhaustive mapping for the API that we're using [here](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getproductinfo), however I think we have a bug with the table itself. The Minimum major version one can grab is `6`, not `0`, as [we've currently got it](https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/os_version.cpp#L1660).

That being said, I agree with @keeleysam that it would be much better to have this derived, as opposed to maintaining the list. I'll see if I can find a good WMI provider for this, but I'm not super optimistic. The alternative is we just don't populate `codename` on Windows, but I'm less excited about this idea, as there's no good way to "hide" a column for a platform, and migrating this column to be Linux/Macos only seems like an API change that I'm not convinced is _really_ merited. Should have a fix/change here in a bit, just need to spin up a Win7 box.

**Comment by directionless** [comment]
Is https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-osversioninfoexa?redirectedfrom=MSDN what you're looking for?
