### ISSUE TITLE
Problem with initializing database

### ISSUE THREAD

**Issue by hemasalma** [osquery/osquery#4100]
Hello,

We have installed Osquery-2.11 in our lab... we have copied conf file from /usr/share/osquery
and started the service using the following command

service osqueryd start

then when checking with the conf file using the command:
osqueryctl config-check

it is showing the below error:
E0202 20:04:09.015120 15390 init.cpp:591] [Ref #1629] osqueryd initialize failed: Could not initialize database
but, we are able to execute the commands using the conf file and results are seen in the results.log 
and even we checked with sending these data to logstash and it is working fine..

so, can we know why we are getting the error and how to work on to resolve it...

**Comment by muffins** [comment]
@hemasalma typically the database path is `/var/osquery/osquery.db`, but this is commented out by default in the configuration. Can you verify that `/var/osquery` exists and that the user you're running the daemon as can write to that directory? We also [have a Slack](https://osquery-slack.herokuapp.com/) that can possibly get you faster answers :)

**Comment by salmajohnysk** [comment]
Hi,
we have uncommented the path /var/log/osqueru.db  and we are able to see the directory /var/osquery .
if we start the osquery service we are able to push data into osquery.results.log   file based on the conf file information.
But if we check the conf file with below command it is showing error...

osqueryctl config-check

E0202 20:04:09.015120 15390 init.cpp:591] [Ref #1629] osqueryd initialize failed: Could not initialize database.
