### ISSUE TITLE
Log to a plain tcp or udp socket, or http?

### ISSUE THREAD

**Issue by dcosson** [osquery/osquery#4127]
I'm just getting started on osquery and so far I'm really enjoying it. But I'm wondering why there is no built-in logger option to stream the logs to a tcp or udp socket. Given that there is a tls logger, I would expect these to also exist as they seem like basically a simpler version of the same type of use.

My particular scenario is that I already have a fluentd log collector running on all of my servers, and I was hoping to set up osquery to send logs directly to it over a localhost udp or tcp connection. I don't want to set up a hostname and certificates to use tls for this since it's just local traffic. I guess the only way to do it is to log to a file instead and have fluentd tail it, it's just slightly less convenient since now there's extra data lying around and I need to set up logrotate rules and such to manage it.

A fluentd specific log output like docker has included in its core would be even better for my use.

(The syslog format could also work in my use case, but I don't want to have to configure sending it through the built-in syslog handling, and there doesn't seem to be an option to set the syslog port in osquery so that I could use a non-standard port and just have fluentd listen for it.)

I'm wondering if I'm just missing something obvious, and if not I just wanted to open this as a feature request.

**Comment by dcosson** [comment]
Ok, so it looks like osquery writes result logs to be owned by root and not world-readable, and I don't see any way to change it (even when I manually chmod the results.log file it changes it back the next time it flushes logs). So it seems like there's no way to set up another process to tail my osquery result logs if I don't run that process as root.

For such a relatively popular and mature project I'm kind of surprised to have run into so many dead ends here (no streaming to a socket, or local http server, no syslog using a dedicated collector, no tailing a log file). Is there any simple option I'm just missing? The docs [even mention fluentd](https://osquery.readthedocs.io/en/stable/deployment/log-aggregation/#fluentd) so I was expecting this to be pretty straightforward.

If not I may just give up on osqueryd and run my relatively few queries manually with osqueryi on a schedule. I discovered there's already a plugin [that does this on fluentd](https://github.com/niyonmaruz/fluent-plugin-osquery) so maybe I'm not the first person to run into this.

**Comment by obelisk** [comment]
Heyo! Sorry you're having issues getting osqueryd logging set up in a sustainable way.

To answer your first question about the logs owned by root, it's because if osquery is running as root it will collect data perhaps not visible to unprivileged users which is why osquery enforces that.

As for streaming data to a fluentd collector I will unfortunately be less helpful as I haven't used it personally. It would be relatively easy to write a simple logger plugin that can write the logs to a TCP or UDP socket (it could even be written as an extension).

**Comment by obelisk** [comment]
Here is branch I whipped up if you're looking for a starting point on this: https://github.com/obelisk/osquery/tree/simple_tcp

**Comment by dcosson** [comment]
Great, i'll start there. Thanks for the help

**Comment by directionless** [comment]
This appears to have been answered.
