### ISSUE TITLE
osquery appears to ignore files with names that contain multibyte characters over U+00FF on Windows

### ISSUE THREAD

**Issue by tandrew33333** [osquery/osquery#4150]
Running on Windows 10 v1703 x64
STR:
1. Add "ÿ.txt" to your desktop.
2. Add "Ā.txt" to your desktop.
2.  Run .\osqueryi "SELECT * from file where path like 'c:\users\user1\desktop\%';" --json

Expected:
[
{"atime":"1519398540","block_size":"","btime":"0","ctime":"1519398540","device":"2","directory":"c:\\users\\bit9qa\\desktop\\osquery","filename":"ÿ.txt","gid":"0","hard_links":"","inode":"0","mode":"
0666","mtime":"1519398624","path":"c:\\users\\bit9qa\\desktop\\osquery\\Ā.txt","size":"6","symlink":"0","type":"regular","uid":"0"}
{"atime":"1519398540","block_size":"","btime":"0","ctime":"1519398540","device":"2","directory":"c:\\users\\bit9qa\\desktop\\osquery","filename":"ÿ.txt","gid":"0","hard_links":"","inode":"0","mode":"
0666","mtime":"1519398624","path":"c:\\users\\bit9qa\\desktop\\osquery\\ÿ.txt","size":"6","symlink":"0","type":"regular","uid":"0"}
]

Actual:
[
{"atime":"1519398540","block_size":"","btime":"0","ctime":"1519398540","device":"2","directory":"c:\\users\\bit9qa\\desktop\\osquery","filename":"ÿ.txt","gid":"0","hard_links":"","inode":"0","mode":"
0666","mtime":"1519398624","path":"c:\\users\\bit9qa\\desktop\\osquery\\ÿ.txt","size":"6","symlink":"0","type":"regular","uid":"0"}
]

**Comment by muffins** [comment]
Ah yes, this is due to a limitation that we made a decision to use ANSI APIs from the beginning, and have never moved to leveraging windows wide strings. [We have another issue](https://github.com/facebook/osquery/issues/2569) open requesting we make the shift, and in my opinion we should absolutely be using the wide string APIs, however we've never had the time or resources to make this shift.

That being said, there should still be a row returned here for the file even if it can't quite parse the name out correctly. I'll take a look at why we're not getting a row.

**Comment by Smjert** [comment]
```
PS C:\osq\b> .\osquery\RelWithDebInfo\osqueryd -S --json "SELECT * from file where path like \`"C:\osq\%\`";"
[
  {"atime":"1603639977","attributes":"","block_size":"512","btime":"1593005413","ctime":"1603459773","device":"16196206","directory":"C:\\osq\\b","file_id":"0x002000000000e938","file_version":"","filename":".","gid":"513","hard_links":"1","inode":"9007199254800696","mode":"-1","mtime":"1603459773","path":"C:\\osq\\b\\","product_version":"","size":"40960","symlink":"0","type":"directory","uid":"544","volume_serial":"00f7-226e"},
  {"atime":"1603639897","attributes":"A","block_size":"512","btime":"1603639893","ctime":"1603639915","device":"16196206","directory":"C:\\osq","file_id":"0x0005000000024ba2","file_version":"","filename":"ÿ.txt","gid":"513","hard_links":"1","inode":"1407374883703714","mode":"-1","mtime":"1603639893","path":"C:\\osq\\ÿ.txt","product_version":"","size":"0","symlink":"0","type":"regular","uid":"1001","volume_serial":"00f7-226e"},
  {"atime":"1603640100","attributes":"A","block_size":"512","btime":"1603640100","ctime":"1603640101","device":"16196206","directory":"C:\\osq","file_id":"0x0003000000024ba7","file_version":"","filename":"Ā.txt","gid":"513","hard_links":"1","inode":"844424930282407","mode":"-1","mtime":"1603640100","path":"C:\\osq\\Ā.txt","product_version":"","size":"0","symlink":"0","type":"regular","uid":"1001","volume_serial":"00f7-226e"}
```

I would say that this now works thanks to #6338 and #6190.
