### ISSUE TITLE
windows: Update build projects to VS2017

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4151]
VS2017 has been out for a bit now, and it's proving to be substantially faster and more responsive than VS2015. Let's map out what the upgrade path looks like and deploy this.

**Comment by momopranto** [comment]
Let's broaden the scope of this issue to include third party dependencies that need to be rebuilt using 2017 toolchain. We've got the ball rolling with Boost and openssl but we should take a look at the others as well.

**Comment by mike-myers-tob** [comment]
It seems this issue can be closed? We are building using VS2017 today: 
https://osquery.readthedocs.io/en/latest/development/building/#windows-10
