### ISSUE TITLE
Long Sql Statements

### ISSUE THREAD

**Issue by kemalbayar** [osquery/osquery#4157]
on a osquery agent without tls server, I see the exact (long) query in the output (--verbose) but no logging in osquery_results (local file on the client)

When the query to be changed to Select * from windows_events where eventid=1102; no logging problem

There is a problem with long sql statements ?

```
C:\Users\Administrator>\ProgramData\osquery\osqueryd\osqueryd.exe --config_path=\programdata\osquery\osquery.conf --flagfile=\programdata\osquery\osquery.flags
I0226 15:40:33.200104 3804 init.cpp:380] osquery initialized [version=2.11.2]
I0226 15:40:33.262603 3804 system.cpp:344] Found stale process for osqueryd (3864)
I0226 15:40:33.262603 3804 system.cpp:377] Writing osqueryd pid (5020) to \ProgramData\osquery\osqueryd.pidfile
I0226 15:40:33.262603 3804 extensions.cpp:300] Could not autoload extensions: Failed reading: \ProgramData\osquery\extensions.load
I0226 15:40:33.778230 3360 watcher.cpp:549] osqueryd watcher (5020) executing worker (5876)
I0226 15:40:33.809479 896 init.cpp:377] osquery worker initialized [watcher=5020]
I0226 15:40:33.825103 896 rocksdb.cpp:132] Opening RocksDB handle: \ProgramData\osquery\osquery.db
I0226 15:40:33.981364 5860 interface.cpp:338] Extension manager service starting: \.\pipe\osquery.em
I0226 15:40:36.083745 5800 events.cpp:746] Starting event publisher run loop: windows_event_log
I0226 15:40:36.083745 896 main.cpp:106] Not starting the distributed query service: Distributed query service not enabled.
I0226 15:40:39.107058 3368 scheduler.cpp:75] Executing scheduled query system_info: SELECT * FROM windows_events WHERE eventid in ('1100','1101','1102','1104','4608','4609','4624','4625','4634','4657','4660','4663','4670','4688','4689','4698','4699','4700','4701','4702','4719','4720','4722','4723','4723','4724','4724','4725','4726','4727','4728','4729','4730','4731','4732','4733','4734','4735','4737','4738','4739','4767','4740','4741','4742','4743','4744','4745','4746','4747','4748','4749','4750','4751','4752','4753','4754','4755','4756','4757','4758','4759','4760','4761','4762','4763','4764','4800','4801','4817','5024','5025','5140','5142','5143','5144','5145');
```

Details here: This case moved from https://github.com/kolide/fleet/issues/1713

**Comment by obelisk** [comment]
Hmm, this is an interesting issue. We run some very long queries here so it seems unlikely it would be the SQL engine; maybe something to do with windows event logs.

cc @muffins Any idea if there is something in the event code that could cause this?

**Comment by muffins** [comment]
@kemalbayar I updated your question to make things a little more readable, hope you don't mind :)

As for the question itself, there shouldn't be any issue here, so we'll dig into what's going on. I did some quick preliminary tests, and `in` statements the way you're using them definitely should work just fine on the `windows_event_log` table.

**Comment by kemalbayar** [comment]
Now I'm using this query: SELECT * FROM windows_events where eventid=4688 OR eventid=1102 OR eventid=4658;

And  I can see 4658 and 1102 event logs in the osquery_results log file but although 4688 events created (which can be seen in the following picture) related 4688 logs aren't written to osquery_results log file

![image](https://user-images.githubusercontent.com/33925821/36983105-91c2d3b2-20a2-11e8-9835-48c75be4634e.png)

**Comment by muffins** [comment]
In that immediate example, are you’d ure you’re running as Administrator? 4688 is a security channel event, as you’ve pictured, but osquery can’t subscribe to Security channel events without privilege, so in your testing ensure that you’re running the shell as admin.

**Comment by kemalbayar** [comment]
Well, I login the system using Administrator so it is mean I'm running the cmd with admin privilege. Finally, all the events 1102, 4658 and 4688 are included in Security channel. The problem is that some events fetched randomly by osquery

**Comment by kemalbayar** [comment]
just now I did a test.  Select * from windows_events where eventid='1102' OR eventid='4688' ....; all the logs created aren't written to the osquery_results log file but  when I use the command Select * from windows_events where eventid='4688';  I see it in the osquery_results log file.

is this case related to some flags? My flags in osquery.flags file are 

--enroll_secret_path=/programdata/osquery/enroll_secret.txt
--tls_server_certs=/programdata/osquery/server.pem
--tls_hostname=192.168.1.2:8080
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=60
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=3
--windows_event_channels=Windows PowerShell,Security
--events_optimize=true
--config_refresh=30
--config_tls_refresh=30
--config_accelerated_refresh=300
--config_tls_max_attempts=3
--logger_event_type=true
--logger_snapshot_event_type=true
--events_max=70000
--events_expiry=3600

**Comment by kemalbayar** [comment]
@muffins  is there any progress about the case? 

I've tested the queries on a different client running windows server 2012 (previously was server 2016) but result is same.   I'm administrator on the related hosts and I see all the related event id being created in event viewer(4658,1102,4663...) but only some of related event id are dropping into osquery_results log file.


Select * from windows_events where eventid=4658 OR eventid=4663;
Select * from windows_events where eventid in (4658,1102,4663);

**Comment by kemalbayar** [comment]
@obelisk  @muffins 

I also tested a different case related to this issue

I got all the logs with related event ids on Kolide UI using a distributed query.
also no problem when I use the same query in Osqueryi (shell)

When i use the same queries in a pack, the osquery_results log file not contains the related events, although I see the related event ids was generated in event viewer's security channel

it's weird that the same queries not to be an issue when using with distributed query feature

**Comment by muffins** [comment]
@kemalbayar can you give us the details of the scheduled query, as well as config flags you’re using? Are you seeing any warning or info verbosity around events expiring? It could be that you’re overflowing the event limit of 50k. How frequently are you querying windows events?

**Comment by kemalbayar** [comment]
I'm sure this case isn't related events_max flag. if so, I would got the warning like you mentioned. (previously, I got that warning so i know)

as I mentioned before, I see some events immediately in osquery_results just after it's dropped in event viewer. This happening randomly, some event ids are OK but some not


--enroll_secret_path=/programdata/osquery/enroll_secret.txt
--tls_server_certs=/programdata/osquery/server.pem
--tls_hostname=192.168.1.254:8080
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=10
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=3
--windows_event_channels=Windows PowerShell,Security
--events_optimize=true
--config_refresh=10
--config_accelerated_refresh=300
--config_tls_max_attempts=3
--logger_event_type=true
--logger_snapshot_event_type=true
--events_max=70000
--events_expiry=3600

**Comment by kemalbayar** [comment]
@muffins  in addition to above, no problem with the query select * from windows_events;
when the query is this, all the event ids are dropping into the log file, but when the query is either "select * from windows_events where eventid=xxxx OR eventid=xxxxx OR eventid=xxxxxx";  or "select * from windows_events where eventid in (xxxx,xxxx,xxxx,xxxx)";
the problem is happening

**Comment by aCruzQ** [comment]
Hi @kemalbayar.
I'm working with table windows_events and did queries as:

"select * from windows_events where eventid='4720' OR eventid='640'"; 
or 
"select * from windows_events where eventid in ('4720','640')";
and 
sometimes have results on the web, no results in the file results and we run the query using the API; have correct results.  

But if I run the query with the format:
"Select * from windows_events where eventid='4720'; "
or
"Select * from windows_events where eventid in ('4720'); "

The query dropping perfectly result in file, screen and API without problems.

![image](https://user-images.githubusercontent.com/20323736/63432233-16620c00-c421-11e9-8947-85eb572fc110.png)

![image](https://user-images.githubusercontent.com/20323736/63432263-2679eb80-c421-11e9-8298-e25e928332f0.png)

![image](https://user-images.githubusercontent.com/20323736/63496672-9c825f00-c4c2-11e9-929b-1de6d410de87.png)

I think that is a problem of SQLite syntaxis. How I can solve this problem, please?

Thank, for help me.

**Comment by aCruzQ** [comment]
I created a pack with 6 queries:
Name: QueryTest01
SELECT * from windows_events  where (eventid='4720') OR (eventid='624');
Name: QueryTest02
SELECT *  from windows_events where eventid = '4720' or '624';
Name: QueryTest03
SELECT *  from windows_events where (windows_events.eventid= '4720') or (windows_events.eventid='624');
Name: QueryTest04
SELECT *  from windows_events where eventid='4720'; 
Name: QueryTest05
SELECT *  from windows_events WHERE (eventid = '4720') OR (eventid = '624');
Name: QueryTest06
SELECT * from windows_events where eventid LIKE '4720' OR '624';

The queries run to 30 seconds and logging as a diferencial. 

Then I create an account and the results (in the osquery_result file) are different; some queries triggered result with many different windows IDs.
Some queries didn't save results.
The unique query that saves the correct result is the "QueryTest04".

Can you help us with this, please?

Kind regards.

**Comment by aCruzQ** [comment]
Hi, someone can help me with this problem.

Kind regards.

**Comment by Hizees** [comment]
who are you? name, have a question



---Original---

**Comment by theopolis** [comment]
Thanks for pinging the issue folks, this is indeed something that we want to resolve.

Can you please let us know what versions of osquery you are using? I see in the top-post that a 2.x version is used. I’d like to confirm this is still an issue with 4.0.2.

**Comment by Hizees** [comment]
is&nbsp; it&nbsp; &nbsp;just&nbsp;&nbsp;
l&nbsp; don't&nbsp; &nbsp;need&nbsp; it

---Original---

**Comment by Smjert** [comment]
Please test the latest version of osquery (4.5.1), windows_events has been refactored on Windows so please test it and reopen if that issue persist.
