### ISSUE TITLE
Startup Items Discrepancy with Login Items

### ISSUE THREAD

**Issue by jbussing** [osquery/osquery#4174]
Hi,

I am getting a discrepancy between what I observe in the Login Items for a user and what osquery has in the startup_items table. Im also wondering if this could be related to a previous issue (https://github.com/facebook/osquery/issues/3994).

Below is a list of the startup items:
```
$ python -c 'import sys; from Foundation import SFLManager; manager = SFLManager.sharedInstance(); map(lambda x: sys.stdout.write(str(x.bookmark()) + "\n"), manager.loginItems().allItems())'
file:///Applications/Backup%20and%20Sync.app/
file:///Users/XXXXXXX/Library/PreferencePanes/MenuMeters.prefPane/Contents/Resources/MenuMetersApp.app/
file:///Applications/CopyQ.app/
file:///Applications/Spectacle.app/
file:///Applications/AnyDesk.app/
file:///Applications/VMware%20Fusion.app/Contents/Library/VMware%20Fusion%20Start%20Menu.app/
file:///Applications/Keybase.app/
file:///Applications/Spotify.app/
file:///Applications/Dropbox.app/
file:///Applications/iTunes.app/Contents/MacOS/iTunesHelper.app/
file:///Applications/Clipy.app/
```
Below is the osquery result for the same machine's startup_items table:
![screen shot 2018-03-02 at 11 41 21 am](https://user-images.githubusercontent.com/25304987/36920798-bfd17e36-1e16-11e8-81b1-78d2d3ff9b8f.png)

Additionally this issue might also be related to an update that was made to AliasData (10.13)

**Comment by clong** [comment]
@jbussing which version of osquery is this happening with?

**Comment by jbussing** [comment]
The osquery version presenting this issue is 2.11.2

**Comment by groob** [comment]
It's definitely related to the linked issue. 

The core problem is that osquery builds this table by [parsing a plist](https://github.com/theopolis/osquery/blob/dec9bbd1425208754d69c2957cdaacf89a0b601d/osquery/tables/system/darwin/startup_items.cpp#L29-L30) in the preferences folder. 
Generally plists are used on macOS as just caches, and there's no guarantees that the data in some /Preferences/foo.plist is every accurate. 

For example on my 10.13.4 mac the LoginItems plist does not even exist. 

We should move to an API, possibly the one @pudquick documented in #3994

**Comment by rhuddleston** [comment]
https://objective-see.com/blog/blog_0x31.html

On macOS 10.13, Apple decided to change both where and how login items were stored. Instead of the com.apple.loginitems.plist file, login items are now stored in the backgrounditems.btm file, found within ~/Library/Application Support/com.apple.backgroundtaskmanagementagent/

**Comment by rhuddleston** [comment]
see related issue #5564

**Comment by Smjert** [comment]
I'm going to close this; osquery support goes back to 10.15, the issue has changed and is already tracked by the previously mentioned issue.
