### ISSUE TITLE
tables: file table on Windows always returns 0 for uid and gid

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4176]
We leverage `stat` on posix and Windows for obtaining file information. This function on Windows always returns `0` for the uid and gid fields, thus we're not getting ownership values for filesystem queries on Windows. See https://msdn.microsoft.com/en-us/library/14h5k7ff.aspx for more information.

**Comment by kemalbayar** [comment]
for example..:

select * from users;

![image](https://user-images.githubusercontent.com/33925821/37196946-cd20e46e-2389-11e8-9507-e560d42f1ab5.png)

select * from processes;
output of that query contains -1, 0 and 544 as UID and GID

for these reasons, the following query doesn't return any result
select *,username from processes JOIN users USING (uid);

**Comment by Rich5** [comment]
Is there any known work-around for getting file ownership values on Windows?

**Comment by Rich5** [comment]
@muffins if you want I can take a stot at fixing this? I think we'll need to use win32api calls though. Something like shown here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa446629(v=vs.85).aspx

**Comment by muffins** [comment]
@Rich5 that would be amazing, thank you! Lemme know if you get stuck or need this shipped fast and I can bump it in my priorities, but I haven't started, so if you could tackle this that would be awesome.

**Comment by Rich5** [comment]
I'll get something together. This should be fixed so we can eventually get a good FIM extension on Windows.

**Comment by Rich5** [comment]
@muffins so I've made some progress on this, but in the process of standing up a new dev env I can't seem to get the binaries to build again. It appears that the installing visual studio 2015 community now doesn't include the `um\ `folder and the libs needed. The error is below. Are you able to reproduce or did I just mess something up. 

```
LINK : fatal error LNK1181: cannot open input file 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64\wevt
api.lib' [C:\users\dev\sources\repos\osquery\build\windows10\osquery\daemon.vcxproj]


[-] osquery build failed.

```

**Comment by Rich5** [comment]
@muffins I made an initial cut at refactoring the file table for windows. It's functional, but wanted to get your take on it before I submit a PR
https://github.com/Rich5/osquery/tree/windows_file_ops
