### ISSUE TITLE
packages: set stable package to be latest stable tag in GH

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4186]
Grabbing the osquery package from:

https://osquery-packages.s3.amazonaws.com/darwin/osquery.pkg

Will get the _latest_ tag cut for osquery, which is different from the latest _stable_ version of osquery. It was requested that we look into either pointing this link to be the latest stable, or possibly adding another hard coded link, possibly something like https://osquery-packages.s3.amazonaws.com/darwin/osquery-stable.pkg for all platforms.

**Comment by directionless** [comment]
I'm going to close this, on the grounds that it's old, and there's known future work around the build system.
