### ISSUE TITLE
watchdog: worker processes not being killed during high CPU consumption queries

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4191]
In particular, on single core Windows systems we've seen queries take up ~80 to 90% of the CPU for > 10 seconds, and the process not be killed by the watchdog. Will fill in with more details when I can get some good screen shots of reproducing.

**Comment by muffins** [comment]
Bump. I'll get this to the top of my priority list this week or next, we need to sort out what's causing the watcher to not kill the service in high consumption circumstances.

**Comment by theopolis** [comment]
We've refactored a lot of the shutdown and watchdog logic recently. Please reopen if this is still an issue.
