### ISSUE TITLE
configuration of required files for the magic table

### ISSUE THREAD

**Issue by fossam** [osquery/osquery#4193]
As of default package of 2.11.0 for ubuntu, the _magic_ table does not work. osquery is looking for the required files in _/usr/local/osquery/Cellar/libmagic/5.29_101/share/misc/magic.mgc_ which rarely exist by default on end hosts.

The ask here is two fold:
* make it possible to configure the path in compile time (in osquery/tools/provision/formula/libmagic.rb, for example)
* make it possible to have runtime configuration of the path.

The first ask makes it easier to have custom builds for situations where anything resembling the default path is not possible (even symlinks or additional runtime options).

The second ask helps with one-off commands.

**Comment by Smjert** [comment]
Addressed by https://github.com/osquery/osquery/pull/5438
