### ISSUE TITLE
Standalone osqueryi installation unable to query shared folder / folder accessed through full path

### ISSUE THREAD

**Issue by yesoreyeram** [osquery/osquery#4194]
Hi, I am beginner with osquery. I am trying to get filecount from a remote folder (windows to windows) using osqueryi.exe

My query is very simple.

       select count(*) from file where file.path like "\\some-remote-server\remote-folder\%"

But i couldnt get the results back. I do have access to the server and manually able to navigate remote folder. How can i fix the query? Or is this not possible with osquery? 

User has full (R+W) access to the folder. 

![image](https://user-images.githubusercontent.com/153843/37402350-16f51964-2783-11e8-92ab-81b285610d33.png)

**Comment by yesoreyeram** [comment]
One more screenshot to help. In the below case my expected output is 5 ( file count including subdirectories )

![image](https://user-images.githubusercontent.com/153843/37403724-b1af7310-2787-11e8-9186-ea18639294af.png)

**Comment by muffins** [comment]
Interesting, I don't think we had intended for queries against the file table to work against remote systems, so yeah there could be something up with how File Globs work via the Windows APIs. This _might_ not actually be possible for us to get, and I don't believe it's something we intended to be supported. I'll see if I can find a quick and easy solution to this and get back to you.

**Comment by reynas** [comment]
any update on this? Would like to see this being supported as well. Thanks!

**Comment by sk4la** [comment]
I second this FR.

**Comment by directionless** [comment]
I don't think anyone is working on this
