### ISSUE TITLE
osqueryd initialize failed: Could not create file: /var/osquery/osqueryd.pidfile

### ISSUE THREAD

**Issue by r3doubt** [osquery/osquery#4201]
3.1.0 installed via Brew
https://osquery.readthedocs.io/en/stable/installation/install-osx/

> sudo ln -s /var/osquery /usr/local/share/osquery
> sudo mkdir /var/log/osquery
> sudo chown root /usr/local/Cellar/osquery/1.7.3/bin/osqueryd
> sudo cp /var/osquery/osquery.example.conf /var/osquery/osque
> 
Directions are out of date, don't seem correct or to correspond to the pathways for Brew install (3.1.0).  There is no /var/osquery to use for symlink or the .conf.  These are in /Cellar.

Got it working for osqueryi, but osqueryd still failed due to pidfile.

Configuring osqueryd received 

> osqueryd initialize failed: Could not create file: /var/osquery/osqueryd.pidfile

Found https://github.com/marpaia/osquery/commit/5a5ec45bbbfd0943a733bcb409e3535d2ab01b66
and
https://github.com/facebook/osquery/issues/785

There is no warning text appearing when this fails due to the alternate path from Brew installs, /usr/local/Cellar.

Changing the file pathway with osqueryd (--pidfile) or config (--config_path), per ticket 785 suggestion,simply produces the same error (osquery is being run from correct pathway).

I followed https://osquery.readthedocs.io/en/stable/deployment/configuration/  which seems to suggest using --config_path which doesn't work.

> /usr/local/Cellar/osquery/3.1.0/bin/osqueryd --config_path=/usr/local/Cellar/osquery/3.1.0/share/osquery/osquery.conf

> E0318 01:52:28.363977 2834613056 init.cpp:421] osqueryd initialize failed: Could not create file: /var/osquery/osqueryd.pidfile

Tried a mkdir /var/osquery, without resetting --pidfile=path, and this seems to resolve issue.  Warning should maybe be added with instructions to create a /var/osquery, and directions for macOS install should be updated/fixed.

**Comment by r3doubt** [comment]
I guess that should be without resetting --pidfile=path since I used /var/osquery.

**Comment by Smjert** [comment]
I don't think this is relevant anymore, the most recent documentation is https://osquery.readthedocs.io/en/latest/installation/install-macos/
