### ISSUE TITLE
sshd child not present in process_events

### ISSUE THREAD

**Issue by ghost** [osquery/osquery#4220]
I am using the osquery compiled from git, the second sshd process is created when a user starts a new ssh session successfully.
The process with pid 2936 is not a thread but a new forked, childred of 2876.

root      2876  2876  0.0  0.1 107696  7220 ?        Ss   13:48   0:00 sshd: user1 [priv]
user1     2936  2936  0.7  0.0 107696  3544 ?        S    13:48   0:00 sshd: user1@pts/2
 
 
osquery> select path, cmdline, pid from process_events where cmdline like '%ssh%';
+----------------+-------------------------------+--------+
| path            | cmdline                        | pid    |
+----------------+-------------------------------+--------+
| /usr/sbin/sshd | /usr/sbin/sshd -D -R  | 2566 |
| /usr/sbin/sshd | /usr/sbin/sshd -D -R  | 2876 |
| /usr/sbin/sshd | /usr/sbin/sshd -D -R  | 3319 |
+----------------+-------------------------------+--------+

I can't see it in process_events, but it is visible in processes table.

**Comment by clong** [comment]
I'm not a Linux internals expert, but I suspect this could be happening if the child process is being spawned via the fork syscall, rather than execve which is the only process-based syscall that osquery monitors.

**Comment by n0way0ut** [comment]
yes, this seems to be the issue, it is just fork and not fork+execve.
I should find a workaround to monitor sshd. :)

**Comment by clong** [comment]
I think this issue can be closed

**Comment by Smjert** [comment]
This has been implemented by #5701.
