### ISSUE TITLE
Cache the config content persistently unless it is older than N seconds

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery#4223]
## Proposed Solution

Modify the implementation of [`osquery/config/config.cpp`](https://github.com/facebook/osquery/blob/65a85799f5e2fb41c56aa43607f6eb5389cac63d/osquery/config/config.cpp#L431) to persist the config to RocksDB upon successful acquisition and use that config if config acquisition fails in the future. Add a `--config_offline_expiry` flag (name tbd) to control how old of a config should actually be used in the event a host is offline for a really long time.

If implemented, this solution will add this network durability by default to all internal config plugins as well as those provided by extensions that don't already account for this.

## Background

A few of us were talking earlier about some differences in behavior between a few different config plugin implementations and how caching works if the device is offline but network connectivity is required to get the config.

Consider the differences in behaviors given the following plugins:

#### Filesystem Plugin (facebook/osquery)

The filesystem plugin does not require communication with a remote host, so it's our control in this experiment (also because it's the default). The filesystem plugin does not require consistent distribution of the config or network communication for it to work. You give osquery a config and it will execute scheduled queries and log results in a variety of network conditions.

#### TLS Plugin (facebook/osquery)

The TLS plugin does not cache the config in RocksDB, so if a `genConfig` request fails, the existing config will only be cached in memory. Upon process restart, the host will not be able to access the last used config.

#### gRPC Plugin (kolide/launcher)

Thee gRPC plugin in the Kolide Go Extension persists configs to disk and attempts to read them if remote acquisition fails.

**Comment by directionless** [comment]
This was implemented in #4935
