### ISSUE TITLE
Python path hardcoded on "python_packages" table for Linux (and partially macOS)

### ISSUE THREAD

**Issue by mcburrlin** [osquery/osquery#4252]
In the "python_packages" table, "kPythonPath" (Linux platform) is hardcoded to python2.7 path.
https://github.com/facebook/osquery/blob/f6d077cbf7e1f60eef06ccdaf568f25971d178e9/osquery/tables/system/python_packages.cpp#L33-L40

It looks like Darwin & Windows dynamically generate, although the Darwin logic assumes you're using a Python binary located in:

https://github.com/facebook/osquery/blob/f6d077cbf7e1f60eef06ccdaf568f25971d178e9/osquery/tables/system/python_packages.cpp#L42-L44

I think it would make sense to dynamically locate the Python binary or to allow for the ability to select Python based on a given path.

**Comment by lukelima** [comment]
Is this issue still relevant ? Case not, it should be closed by PR #4407

**Comment by Smjert** [comment]
Closing since this has been implemented by #4407
