### ISSUE TITLE
FIM didnt report inotify DELETED file event whenever watched file removed  

### ISSUE THREAD

**Issue by erdarun** [osquery/osquery#4260]
OSQuery FIM existing functionality doesn't catch inotify DELETED file event.

When existing watched file removed from system using 'rm' command, OSQuery only reports ATTRIBUTES_MODIFIED file event it doesn't catch DELETED file event.

I guess since watcher gets deleted OSQuery not able to catch/report DELETED file event.

Please check and revert.

**Comment by muffins** [comment]
@erdarun can you give us more information about your setup? What operating system are you running this on and what version of osquery?

**Comment by erdarun** [comment]
@muffins Running FIM on both RedHat Enterprise Linux Server 6.8, CentOS 7 & macOS Sierra 10.12.6. OSQuery version is "osquery-2.7.0-1.linux.x86_64.rpm"

**Comment by muffins** [comment]
Hey @erdarun, truly sorry for the delay in our response! Would you mind updating to the latest stable version, 2.11.2 and check if you can still reproduce?
