### ISSUE TITLE
vagrant: Windows box fails provisioning due to python thrift issue

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4298]
Currently trying to provision with a vargrant box will fail at installing the python thrift package. This is because there's an issue with installing thrift on python if the word `vagrant` is anywhere in your environment, see [this issue on thrift](https://github.com/apache/thrift/commit/9e0c9272140ea91ea4b3f042d207acbbaa15c093). As this is a known issue with Thrift, and it has been patched *but not released*, let's use this issue as something of a PSA.

The workaround is to create a new user on the vagrant box, and change the environment value of `HOME` to something other than `C:\Users\vagrant`. See the snapshot.

<img width="476" alt="screen shot 2018-04-17 at 5 16 57 pm" src="https://user-images.githubusercontent.com/1328916/38905296-ac1b1254-4264-11e8-90f6-d05d66545573.png">

**Comment by muffins** [comment]
You'll also need to exit your shell env, and in my case I needed a system reboot before this change went into effect. That being said you could likely just run `$env:HOME="C:\Users\myuser"` and it might work.

**Comment by mike-myers-tob** [comment]
Since the issue was in Thrift, and was patched, and we have picked up the patched version of Thrift, I am closing this issue.
