### ISSUE TITLE
Watchdog docs for CPU usage limits are self-contradictory and also disagree with actual behavior

### ISSUE THREAD

**Issue by jkeljo** [osquery/osquery#4300]
Here's one place (from https://osquery.readthedocs.io/en/stable/installation/cli-flags/#daemon-control-flags):

>--watchdog_level=0
>
>Performance limit level (0=normal, 1=restrictive, -1=disabled). The watchdog process uses a "level" to configure performance limits.
>
>The level limits are as follows: Memory: default 200M, restrictive 100M ***CPU: default 25% (for 9 seconds), restrictive 18% (for 9 seconds)***
>

A little further down the same page:

>--watchdog_utilization_limit=0
>
>If this value is >0 then the watchdog level (--watchdog_level) for maximum sustained CPU utilization is overridden. Use this if you would like ***to allow the osqueryd process to use more than 30% of a thread for more than 9 seconds of wall time***. The length of sustained utilization is not independently configurable.
>
>This value is a maximum number of CPU cycles counted as the processes table's user_time and  system_time. The ***default is 90, meaning less 90 seconds of cpu time per 3 seconds of wall time*** is allowed.

There are a few issues here:
1. There are three values quoted for default max CPU usage: 25%, 30%, and 3000% (90 seconds of CPU/3 seconds of wall time)
2. `watchdog-utilization-limit` is described as allowing you to specify using "more than 30% of a thread for more than 9 seconds", but "**more than** 9 seconds" is wrong since (as it says) you can't actually control the length
3. None of these numbers match the code (the code has 9% utilization for 12 seconds by default, 8% utilization for 6 seconds as restrictive, and 100% utilization for 1000 seconds as "disabled", which therefore isn't truly disabled).
4. Also, the docs describe "CPU utilization", but the code checks for user and system time separately.

None of this is hard to fix (I'm happy to do it), but I'd need some guidance as to what the *right* numbers are.

FWIW, here are a couple new (failing) tests, using the 25%/18% and 9 seconds numbers:
https://github.com/jkeljo/osquery/commit/9be507615d9bb3736ffc739397a629bb71f29606

**Comment by directionless** [comment]
I can't find the PR right now, but I think @theopolis recently reworked the watchdog. Is this still an issue?

**Comment by Smjert** [comment]
@directionless Yes, the doc is incorrect:
https://github.com/osquery/osquery/blob/6d57dc8066031b3859a8e1da0627740150d5a24d/osquery/core/watcher.cpp#L82-L95

(Each value in the {} corresponds to the watchdog_level, in order normal, restrictive and off)

**Comment by lucasmrod** [comment]
Hi folks!

Found this old issue while working on https://github.com/osquery/osquery/pull/8070.

To bring this issue up to date wrt more recent changes:

> There are three values quoted for default max CPU usage: 25%, 30%, and 3000% (90 seconds of CPU/3 seconds of wall time)

This is no longer the case.
https://github.com/osquery/osquery/blob/master/docs/wiki/installation/cli-flags.md?plain=1#L89-L91

> watchdog-utilization-limit is described as allowing you to specify using "more than 30% of a thread for more than 9 seconds", but "more than 9 seconds" is wrong since (as it says) you can't actually control the length

Latency limit is currently configurable:
https://github.com/osquery/osquery/blob/2e3495837d4fe4db3554c6ef76494bc86c74c099/osquery/core/watcher.cpp#L77-L78

> None of these numbers match the code (the code has 9% utilization for 12 seconds by default, 8% utilization for 6 seconds as restrictive, and 100% utilization for 1000 seconds as "disabled", which therefore isn't truly disabled).

As far as I can see source code matches the docs now, and https://github.com/osquery/osquery/pull/8070 is fixing some leftover mismatches.

> Also, the docs describe "CPU utilization", but the code checks for user and system time separately.

The code currently uses the sum of system + user:
https://github.com/osquery/osquery/blob/2e3495837d4fe4db3554c6ef76494bc86c74c099/osquery/core/watcher.cpp#L482-L484

AFAICS this issue can be closed.

**Comment by lucasmrod** [comment]
Hi folks! https://github.com/osquery/osquery/pull/8070 has been merged, I believe this issue can be closed.
