### ISSUE TITLE
Add vtable for Security Center (Windows)

### ISSUE THREAD

**Issue by cryps1s** [osquery/osquery#4331]
Third-party security products are required to register themselves within the Windows Security Center (WSC). WSC interfaces directly with the security product to track changes in installation, configuration, and health, and with the Action Center, which notifies users of required actions (e.g. restart the firewall). 

This would be a fantastic vtable to add, as it would allow systems owners to introspect the WSC and identify all installed and registered security products on the system. This has the added advantage of not requiring inspection of installed application lists, and only showing software which has successfully registered with WSC. 

Example of querying WSC providers using WMI: 
```
Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntiVirusProduct
Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntiSpywareProduct 
Get-CimInstance -Namespace root/SecurityCenter2 -ClassName FirewallProduct
```

There are three main enumerations which would be useful to add: 

WSC_SECURITY_PROVIDER 
https://msdn.microsoft.com/en-us/library/bb432509(v=vs.85).aspx

WSC_SECURITY_PRODUCT_STATE 
https://msdn.microsoft.com/en-us/library/jj155490(v=vs.85).aspx

WSC_SECURITY_PROVIDER_HEALTH 
https://msdn.microsoft.com/en-us/library/bb432510(v=vs.85).aspx

Some example scenarios that could be solved with this vtable: 

- Tell me if there are systems without a WSC-registered security product.
- Tell me which systems have a WSC-registered security product disabled or in poor health.
- Tell me if a user has installed more than one security products.
- Tell me if a user has installed more than one firewalls. 

Some example rows and columns output: 

- Product Name | TEXT | Security Product Name
- Registration Type | TEXT | WSC Registration (e.g. Firewall, AntiVirus, AntiSpyware) 
- Binary Path | TEXT | Path to Binary

**Comment by redplait** [comment]
something like patch in attach
function GetSecurityProducts was ripped mostly from ms github sample: https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/WebSecurityCenter/cpp/WscApiSample.cpp
put win_wsc.table to osquery\specs\windows
and win_wsc.cpp somewhere to osquery\tables\system\windows
[win_wsc.zip](https://github.com/facebook/osquery/files/2232603/win_wsc.zip)

**Comment by zwass** [comment]
@redplait is there a reason you did not submit your table as a pull request? Would you be willing for someone else to finish it and submit a pull request?

**Comment by redplait** [comment]
hi
mostly religious
I hate github

пт, 15 февр. 2019 г. в 01:12, Zachary Wasserman <notifications@github.com>:

**Comment by zwass** [comment]
@redplait do you authorize someone to take your proposed patch and merge it into osquery via pull request?

**Comment by redplait** [comment]
Hi
license of osquery is apache 2, so all code/patches in issues also under
bsd-like license
I don`t know why you ask my permission
sure anybody can make this patch
I wrote it bcs I was needed in this functionality

пт, 15 февр. 2019 г. в 05:42, Zachary Wasserman <notifications@github.com>:
