### ISSUE TITLE
osquery Cannot Gather Contextual Information from Protected Process Light (PPL) Processes

### ISSUE THREAD

**Issue by clong** [osquery/osquery#4336]
Looks like osquery is not able to gather information about processes that have the PsProtectedLight protection applied to them.

The following query demonstrates the problem: `osquery> select name, path, cmdline, state, cwd, uid, gid, user_time, system_time, start_time from processes where user_time < 0;`

### What version of `osquery` are you using? What operating system. Be specific.
```
+-----------------+------------+----------+-------------+
| osquery_version | os_version | os_build | os_platform |
+-----------------+------------+----------+-------------+
| 2.11.2          | 10.0.15063 | 15063    | windows     |
+-----------------+------------+----------+-------------+
```

### What did you expect to see?
The actual values for the processes

### What did you see instead?
```
osquery> select name, path, cmdline, state, cwd, uid, gid, user_time, system_time, start_time from processes where user_time < 0;
+---------------------------+------+---------+-------+-----+-----+-----+-----------+-------------+------------+
| name                      | path | cmdline | state | cwd | uid | gid | user_time | system_time | start_time |
+---------------------------+------+---------+-------+-----+-----+-----+-----------+-------------+------------+
| System Idle Process       |      |         |       |     | -1  | -1  | -1        | -1          | -1         |
| System                    |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| smss.exe                  |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| csrss.exe                 |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| wininit.exe               |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| csrss.exe                 |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| services.exe              |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| svchost.exe               |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| MsMpEng.exe               |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| SecurityHealthService.exe |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| MsSense.exe               |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| NisSrv.exe                |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
| svchost.exe               |      |         |       |     | 0   | 0   | -1        | -1          | -1         |
+---------------------------+------+---------+-------+-----+-----+-----+-----------+-------------+------------+
```

**Comment by muffins** [comment]
This is definitely something I'd love to see us support. I think to get there we'll need to raise our own protection run-level to be able to open these handles, so I think inherently we wont be able to get _all_ information about system protected processes considering we A.) Run in user land, and B.) Don't have an EV Code sig, but we could probably do better than we are with some re-writes to the processes table. Not sure when this could actually be landed as I don't have cycles right now, but this is something I definitely want.

**Comment by muffins** [comment]
@clong can you think of any other bits of information we might want to grab but can't currently? I think we've largely addressed this issue with the recent re-architecture of the `processes` table, and I'm wondering if we can't close this issue out or if we need to refine what information specifically we cannot get. Right now it looks like only Protected Processes, not PPL, are out of our grasp:
```
osquery> select pid, name, path, start_time from processes where path = '';
E1020 22:23:26.211391  7184 processes.cpp:312] Failed to lookup path information for process 4
E1020 22:23:26.211391  7184 processes.cpp:332] Failed to get cwd for 4 with 31
E1020 22:23:26.212388  7184 processes.cpp:312] Failed to lookup path information for process 104
E1020 22:23:26.212388  7184 processes.cpp:332] Failed to get cwd for 104 with 31
E1020 22:23:26.219370  7184 processes.cpp:312] Failed to lookup path information for process 2032
E1020 22:23:26.219370  7184 processes.cpp:332] Failed to get cwd for 2032 with 31
+------+--------------------+------+------------+
| pid  | name               | path | start_time |
+------+--------------------+------+------------+
| 0    | [System Process]   |      | -1         |
| 4    | System             |      | 1571465309 |
| 104  | Registry           |      | 1571465304 |
| 2032 | Memory Compression |      | 1571465320 |
+------+--------------------+------+------------+
osquery> select pid, name, path, cmdline from processes where path = '';
E1020 22:23:48.594466  7184 processes.cpp:312] Failed to lookup path information for process 4
E1020 22:23:48.594466  7184 processes.cpp:332] Failed to get cwd for 4 with 31
E1020 22:23:48.594466  7184 processes.cpp:312] Failed to lookup path information for process 104
E1020 22:23:48.595463  7184 processes.cpp:332] Failed to get cwd for 104 with 31
E1020 22:23:48.602445  7184 processes.cpp:312] Failed to lookup path information for process 2032
E1020 22:23:48.602445  7184 processes.cpp:332] Failed to get cwd for 2032 with 31
+------+--------------------+------+---------+
| pid  | name               | path | cmdline |
+------+--------------------+------+---------+
| 0    | [System Process]   |      |         |
| 4    | System             |      |         |
| 104  | Registry           |      |         |
| 2032 | Memory Compression |      |         |
+------+--------------------+------+---------+
```

**Comment by premkumar-r1** [comment]
We are facing a similar issue with mac on OSQuery 4.x, It is not returning any values for cmdline.
Can you confirm, Is processes table restructure is going to fix the issue on mac agent too?
Also, share some inform, why mac osquery agent is not able to collect `cmdline` data?
Is there any timeline this issue will be fixed?
osquery> select pid, name, start_time, cmdline from processes Limit 15;
+-----+----------------+------------+---------+
| pid | name                     | start_time | cmdline |
+-----+----------------+------------+---------+
| 0    | kernel_task           | 1584971117 |         |
| 1     | launchd                | 1584971117 |         |
| 42  | syslogd                 | 1584971127 |         |
| 43  | UserEventAgent   | 1584971127 |         |
| 45  | sh                           | 1584971127 |         |
| 47  | uninstalled             | 1584971127 |         |
| 48  | kextd                     | 1584971127 |         |
| 49  | fseventsd              | 1584971127 |         |
| 51  | jamf                        | 1584971127 |         |
| 52  | vpnagentd             | 1584971127 |         |
| 57  | appleeventsd        | 1584971127 |         |
| 58  | systemstats          | 1584971127 |         |
| 60  | configd                  | 1584971127 |         |
| 62  | ciscod                    | 1584971127 |         |
| 63  | powerd                  | 1584971127 |         |
+-----+----------------+------------+---------+

**Comment by mike-myers-tob** [comment]
> We are facing a similar issue with mac on OSQuery 4.x, It is not returning any values for cmdline.
> Can you confirm, Is processes table restructure is going to fix the issue on mac agent too?
> Also, share some inform, why mac osquery agent is not able to collect `cmdline` data?
> Is there any timeline this issue will be fixed?

I don't think it will be the same change required to get PPL process information on Windows and this missing info on macOS. I'm actually going to open a separate issue for the macOS table's inability to read `cmdline` on some processes.

**Comment by muffins** [comment]
Given that from @mike-myers-tob, I'm under the expectation that we can close this issue out, as I believe _most_ of the problem has been solved, and more generically this issue is pretty old given how far osquery has come. I'm going to close this out, and if folks would like us to dig deeper we can re-open and gather fresh context on the issue. Let us know, thanks!
