### ISSUE TITLE
feature: port WEL processing code to RJ from ptrees

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4357]
The windows event log pipeline still makes use of ptrees. This should be ported over to RJ as this is our preferred JSON representation.

**Comment by directionless** [comment]
The event log stuff was re-written in #6280, and then moved a little in #6575. It's now using `boost/property_tree` Both the xml and the json output. Do you think this request is still reasonable?

**Comment by muffins** [comment]
Probably not, let's go ahead and close this out for now!
