### ISSUE TITLE
windows: CWD column in processes table lists the whole process path and not the actual process current directory

### ISSUE THREAD

**Issue by ExceptionalHandler** [osquery/osquery#4384]
The cwd column in processes table in windows shows the whole process path as current working directory. This is apparently because of use of GetModuleFileName for populating that field. 

Version : 
+-------------------+------------+----------+-------------+
| osquery_version   | os_version | os_build | os_platform |
+-------------------+------------+----------+-------------+
| 3.2.2-4-g3abadc77 | 10.0.16299 | 16299    | windows     |
+-------------------+------------+----------+-------------+
### What have you already tried?
Select * from processes;

### What did you expect to see?
cwd column has the current path of the process (like on linux). 
### What did you see instead?
It has the image path instead
![cwd](https://user-images.githubusercontent.com/11868412/39880506-a31f6bfc-549b-11e8-9bf7-9691fa5d10dc.PNG)

**Comment by FullyArticulate** [comment]
I can confirm this. windows/processes.cpp loads GetModuleFileName{,Ex} to get the root and cwd fields. Instead, it should be reading the PEB string to get the CURDIR. (Using the same method the  getProcessCommandLineLegacy() code does)

**Comment by mike-myers-tob** [comment]
It looks like that PR fixed Windows 10, but that the test fails on Azure Pipelines, so the code may not work on Windows Server 2016 (manifests as a warning, not a failed test). I'll reopen this issue until a test and fix is available that eliminates the test warning.

**Comment by mike-myers-tob** [comment]
The discussion on #6263 explains what I was seeing in the osquery output: certain processes are special and osquery cannot access a PEB for them, so it cannot get certain information/columns. It's not a bug, but we'll track it in #6263 as a nice-to-have enhancement if there's a solution. 

Closing out this one for good this time.
