### ISSUE TITLE
Extension can't open \\.\pipe\osquery.em when running as SYSTEM

### ISSUE THREAD

**Issue by mbernhardt6** [osquery/osquery#4417]
### What version of `osquery` are you using? What operating system. Be specific.
osquery_version: 2.11.2
os_version: 10.0.16299
os_build: 16299
os_platform: windows

### What have you already tried?
We have attempted various iterations of uninstall/reinstall/rebooting/killing process, etc.

### What did you expect to see?
osqueryd.exe to start up, open the osquery.em named pipe and our extension connecting to that named pipe and start reporting data up to our inventory system. When we run osqueryd.exe in an elevated command prompt using the same command the service runs as, this process starts as expected and our extension runs properly.

### What did you see instead?
osqueryd.exe starts, we will observe the osquery.em named pipe open then close several seconds (1-5, usually) later.

We will see the following events in one of the INFO logs. This will typically repeat as long as we let the service run.

I0523 10:10:26.855883  7468 watcher.cpp:591] Created and monitoring extension child (\<PID>): \<extension path>
W0523 10:10:29.972787  7468 watcher.cpp:561] Extension respawning too quickly: \<extension path>

Our extension will report the following error:

E0523 10:10:30.054621    2532 main.go:56] can't connect to extension manager: open \\\\.\pipe\osquery.em: The system cannot find the file specified.

Not sure if it's related but we also see the following lines:

E0523 10:09:21.742242 10140 init.cpp:557] Cannot activate \<plugin> config plugin: Unknown registry plugin: \<plugin>
I0523 10:09:21.755270  8660 interface.cpp:89] Thrift message: TPipeServer ConnectNamedPipe GLE=errno = 995

**Comment by mbernhardt6** [comment]
We have since updated to 3.2.4 and are still experiencing this issue.

osquery_version: 3.2.4
os_version: 10.0.16299
os_build: 16299
os_platform: windows

**Comment by rmulley** [comment]
This issue appears to still exist with osquery `3.3.2`.

**Comment by Smjert** [comment]
Hello @mbernhardt6 @rmulley, I'm sorry for the long wait; does this still happen with the latest stable release?
If, yes, what were the CLI flags/options given to the osqueryd process and extension?

What I tried to test this is:
1. Install osquery through the provided MSI
2. Stop and remove the created service through an elevated Powershell console
```
Stop-Service -Name "osqueryd"
Remove-Service -Name "osqueryd"
```
3. Create a new service which specifies the name of the extension socket and start it
```
New-Service -Name 'osqueryd' -BinaryPathName '"C:\Program Files\osquery\osqueryd\osqueryd.exe" --flagfile="C:\Program Files\osquery\osquery.flags" --logger_path="I:" --logger_plugin=filesystem --extensions_socket="\\.\pipe\osquery.em" --disable_extensions=false'
Start-Service -Name "osqueryd"
```
4. Run the extension
```
<extension> --extensions_socket="\\.\pipe\osquery.em"
```
5. Verify that no error occured while launching the extension, or in the logs under I:\

**Comment by Smjert** [comment]
Since this doesn't seem to be an issue anymore I'll just close it.
Feel free to reopen if this happens again.
