### ISSUE TITLE
Crontable for "at" and "batch" jobs

### ISSUE THREAD

**Issue by jbussing** [osquery/osquery#4420]
OSQuery Version and System Info:
osquery 2.11.2 on MacOS High Sierra 10.13.4

I have a general question about the crontab table. 

From what I can gather in specs/posix/crontab.table and osquery/tables/system/posix/crontab.cpp the following paths are used to create the table.
```
"/var/spool/cron/crontabs/",
"/etc/crontab",
```

I was wondering if there was any consideration or plan to include the paths for "at" and "batch" jobs?

According to the man pages the files for the jobs are clearly defined.
```
FILES
     _ATJOB_DIR            directory containing job files
                           (/usr/lib/cron/jobs/)
     _ATJOB_DIR/_LOCKFILE  job-creation lock file (/usr/lib/cron/jobs/...)
     _ATSPOOL_DIR          directory containing output spool files
                           (/usr/lib/cron/spool/)
     _PERM_PATH/at.allow   allow permission control (/usr/lib/cron/at.allow)
     _PERM_PATH/at.deny    deny permission control (/usr/lib/cron/at.deny)
     /var/run/utmpx        login records
```

Thanks for taking a look!

**Comment by directionless** [comment]
I do not believe anyone is currently thinking about implementing this. It seems reasonable, and I think we'd review a PR. But I'm not sure this issue is helping.
