### ISSUE TITLE
Pack output to json is not valid json

### ISSUE THREAD

**Issue by cheizer** [osquery/osquery#4432]
When running a pack and outputting the results to json the results or the queries is not valid json.

### What version of `osquery`

osquery 3.2.4
using SQLite 3.19.3

### What did you expect to see?

Valid json, with a title for each pack query.

### What did you see instead?

[
{"QUERY RESULT ROW"},
{"QUERY RESULT ROW"},
{"QUERY RESULT ROW"},
]

[
{"QUERY RESULT ROW"}
]

**Comment by fmanco** [comment]
Hi @cheizer could you please provide more details? Most importantly the commands you actually ran. Thanks!

**Comment by cheizer** [comment]
I'm not sure what extra details you need. Here is how I ran the query. 

`osqueryi --config_path=/tmp/mp_inv.conf --pack=foo --json > /tmp/foo.json`

**Comment by fmanco** [comment]
Hi @cheizer this is expected behaviour given the current way that packs work. So I'll mark this as a feature request but we don't have any plans to work on it.

**Comment by jspaleta** [comment]
Hey @fmanco, are you accepting pull requests to fix this?
I'm keen on getting this fixed and I think I can probably get this sorted out.

**Comment by fmanco** [comment]
Hey @jspaleta sure, thanks for looking into this. Just make sure you don't break old behaviour, i.e. put this under a new flag.

**Comment by jspaleta** [comment]
sure thing. I'll fork/branch and hopefully do a PR by the end of the week.

Have an option name you prefer? 
--pack-json  maybe?

I'm thinking of encoding the pack name and the query name into the resulting json output for maximum usability.  

The output is sooooooo close to being parsable it shouldn't be that hard to add a new argument conditional and clean it up.

**Comment by cheizer** [comment]
Awesome, if you can get this working that would save me a bunch of work.

**Comment by fmanco** [comment]
@jspaleta nit but maybe `--pack-single-json` is better. I'm trying to have the least cryptic names as possible.

**Comment by jspaleta** [comment]
hey @fmanco 
i got the new output format up and running in the PR #4624 .
Very thin change needed.  Easy to validate that it works by passing pack output to jq on the commandline

please note, I probably didn't do the last query conditional in the most C++ way, and just went to doing it the C way by running an incrementing counter. None of the more C++ iteration looping patterns using .end() conditionals were compiling for me, couldn't figure out how to avoid type mismatching with the end() patterns.
