### ISSUE TITLE
macOS Mojave Issues

### ISSUE THREAD

**Issue by obelisk** [osquery/osquery#4493]
macOS Mojave is now in beta testing and somethings in osquery do not play nice.

Please leave any bugs you find with Mojave here along with any potential solutions.

- Safari extensions don't work without user approval (@keeleysam)
- ~Wifi_survey segfaults (@groob)~ Fixed with #4499 (3.2.7 cut)
- User Interaction Events don't work without user approval
    - This is interesting because we are listenOnly which should be fine but isn't. 
    - This means that we create a tap but it's not enabled by the OS
- ~Build system doesn't work~
     - ~Brew needs to be updated then our formulae need some patches~

**Comment by groob** [comment]
Filed https://github.com/facebook/osquery/issues/4494

**Comment by groob** [comment]
And #4495

**Comment by obelisk** [comment]
For the wifi issues, it looks like it could be new permissions introduced by Apple. scanForNetworksWithName is now throwing the error: Couldn’t communicate with a helper application.

**Comment by obelisk** [comment]
This is a new feature in Mojave which blocks access to the bssids without a special permission.

**Comment by obelisk** [comment]
So, the solution is two fold, the wifi table will now return bssids conditionally, and if you want them, location services need to be enabled.

**Comment by groob** [comment]
Thanks for fixing the crash @obelisk 
Something interesting I noticed while playing with this data with @clburlison: if you're using the airport utility, the BSSID field is still present. 
```
sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s --xml
```

So, guessing their own tools have the entitlement?

**Comment by thomasareed** [comment]
I'm not sure whether this is fixable or not, but on Mojave 10.14 (18A391), I've been doing some tests with the following query:

`select * from safari_extensions;

I've found the following:

- Executed from osqueryi in the Terminal, I get no results
- If Terminal is given Full Disk Access in System Preferences -> Security & Privacy -> Privacy, the query returns the expected results, showing both Safari extensions I have installed

This is pretty logical. However, there's a problem when trying the same query in osquery.conf through osqueryd launched via the launch daemon.

In this case, I never get the expected output in the logs, no matter what. I have tried adding both osqueryd and launchd to the Full Disk Access list, and no dice.

**Comment by scarlac** [comment]
We're facing the same issue where `.listenOnly` event tap fails to ask for permission (unlike the `.defaultTap` which allows modification of events) and then fails to create the tap.

Has this been reported to Apple, @thomasareed ? Or have you found any potential workaround besides asking user to manually allowing access?

**Comment by obelisk** [comment]
I have reported this Apple but received no response. I will circle back to this eventually but I don't have a timeframe for it.

**Comment by thomasareed** [comment]
I haven't reported to Apple yet, no. I do need to, because I've noticed similar problems with out background services that never trigger a request for access.

**Comment by obelisk** [comment]
AFAIK programs that are not applications (have an Info.plist, etc) cannot trigger requests from the OS. What I reported to Apple is that I though from their WWDC talks that there was no entitlement needed for listenOnly taps. It seems that is incorrect and when I reported it received no response. I assume this means that this is intended behaviour by macOS. :(

**Comment by directionless** [comment]
Do we need to keep this bug open? It sounds like the issues here, are around how osx manages Full Disk Access. I'm not sure if that's something osquery should try to handle, or if we should leave as it. 

Perhaps it should be a doc issue. Or if we wanted to fix it, we might need to ship an app bundle

**Comment by obelisk** [comment]
This can be closed in that the same problem is present in Catalina (even more so).

osquery in Catalina can no longer access a user's downloads folder, Desktop, Document, among other things.

As far as I know, this never causes crashes on osquery, only the inability to access data:
I.e `select * from file where path like '/Users/%/Desktop/%'` will return no rows.

The solution for this is to use the approved MDM framework to grant osquery the Full Disk Access Permission. There is no need to ship an app bundle.
