### ISSUE TITLE
distributed queries executed against ec2_instance_tags table return no results

### ISSUE THREAD

**Issue by patrickod** [osquery/osquery#4519]
### What version of `osquery` are you using? What operating system. Be specific.
You can run this query to get the necessary details: 
```
osquery_version = 3.2.6
     os_version = 2018.03
       os_build = 
    os_platform = amzn
```

### What have you already tried?

- [x] Confirmed that queries against other tables work as distributed queries
- [x] Confirmed that the query works as a scheduled query read from a local configuration
- [x] Confirmed that the query works with `osqueryi`

### What did you expect to see?

I expected the following query to return results
```SQL
SELECT * FROM ec2_instance_tags
``` 

### What did you see instead?

While running osqueryd with `--tls_dump` and `--verbose` to monitor the execution of the distributed query the following error messages are seen repeatedly
```
{
  "hostIdentifier": "EC2A7B36-0686-08D7-3DFB-74D3CCEDA8A0",
  "calendarTime": "Fri Jun  8 19:00:42 2018 UTC",
  "unixTime": "1528484442",
  "severity": "2",
  "filename": "aws_util.cpp",
  "line": "178",
  "message": "Exception making HTTP request to URL (https://ec2.us-east-1.amazonaws.com): std::exception",
  "version": "3.2.6"
}
```

**Comment by spasam** [comment]
e.what() is coming back with std::exception 😕

**Comment by patrickod** [comment]
Bumping with some debug output from reproducing today.

```
I0912 20:45:21.943050 1418604 aws_util.cpp:355] EC2 instance ID: i-xxxxxxxxxxxxxxxxx. Region: us-east-1
E0912 20:45:21.954223 1418604 aws_util.cpp:178] Exception making HTTP request to URL (https://ec2.us-east-1.amazonaws.com): std::exception
```
The client is able to ascertain it's region and ec2 instance ID by successfully querying the local metadata service, but later fails to make the `DescribeTags` request used to populate the table.

**Comment by patrickod** [comment]
Tried with the latest `3.3.0` release just to gather more information, and the log output is thankfully a bit more helpful than before:
```
I0913 18:33:14.008628 212615 ec2_instance_tags.cpp:53] Error getting EC2 instance tags: Unable to connect to endpoint
```

**Comment by theopolis** [comment]
Please let us know if this is still and issue with the 4.4.0+ releases.
