### ISSUE TITLE
Logging directories missing after MacOS upgrade

### ISSUE THREAD

**Issue by daguy666** [osquery/osquery#4520]
### What version of `osquery` are you using? What operating system. Be specific.

osquery_version = 2.11.2
os_version = 10.14
os_build = 18A293u
os_platform = darwin

I have tested this, and had the same result when upgrading from the following OS.

- 10.11.x --> 10.12.x
- 10.11.x --> 10.13.x
- 10.11.x --> 10.14 (beta) 
- 10.12.x --> 10.13.x
- 10.12.x --> 10.14 (beta)
---

### What is happening?
When you upgrade your operating system from one version of MacOS to another you lose the anything in `/var/log/` that is not originally put there by MacOS. Osquery requires the logging directory to run, so being its not there, the process just quits.  

### What have you already tried?
I have tried deploying a bash script to my fleet to check that the directory exists, if not, then it create it. This works, but I was hoping to find something a little more permanent, especially since the new OS is coming out end of summer.  
https://gist.github.com/daguy666/3f2318c037289246a1fe3c29287ed0ea

### What did you expect to see?
I was expecting to see following directory after upgrading. `/var/log/osquery`

### What did you see instead?
I saw no log directory, and osquery was not running.

I realize this isn't technically a problem with osquery and more of a feature of Apple's MacOS. But this situation is disabling some of security measures when people upgrade their OS. Would it be possible to change the log directory to a different path so upgrading operating systems wouldn't disable the process? I don't know for sure if this directory is safe either, but what if the path was switched to `/Library/Logs/`

**Comment by directionless** [comment]
I suspect this is long fixed. At least, I think we'd hear a lot more about it if it was a regular issue
