### ISSUE TITLE
Access is denied when this module runs `net start osqueryd` on Windows

### ISSUE THREAD

**Issue by jl98800** [osquery/osquery#4600]
### What have you already tried?
Could be one of 3 things:
1. Owner can't write to a directory to start osqueryd
2. Local Service isn't configured to start the service
3. Puppet runs as local Administrator and can't start the service - which is should be able to do

      Set 'C:\ProgramData\osquery - added SYSTEM, Local Service, local Administrator and Administrators group to the ownership of the files/dirs below - this didn't fix it
      $config_user  = 'SYSTEM' - changed to Administrator - this didn't fix it

Allowed System, local service, administrator to run net.exe

### What did you see instead?
Doesn't matter which user, service, system is configured to own the files/dirs in C:\ProgramData\osquery to start the service.  `net start osqueryd` fails immediately.

I'm using a default Windows 2012 R2 image - which should be the same as osquery was tested with before released.  We haven't made modifications to the osquery module.  It does everything correctly - except start the service - which might be the most critical part.

**Comment by jl98800** [comment]
Found the osquery module - when it does a chocolatey install of osquery - creates C:\ProgramData\osquery\osqueryd - which has now access to anyone - including Admin.  I had to pull down the acl module from Puppet Forge to correct that - and still get an error "System error 1067 has occurred."  Should a specific user besides Administrator be the one who starts the service?

I had two questions:

1. Why would osquery install in C:\ProgramData and not C:\Program Files?
2. Why is the osqueryd directory locked down so tight?  `net start osqueryd` lives in that directory and nobody can reach it.

Thanks

**Comment by jl98800** [comment]
Update:

Found that the group CREATOR OWNER gets applied to C:\ProgramData\osquery\osqueryd which is inherited from it's parent directory.  I modified the osquery module to NOT inherit (set to false) that group from osquery to osqueryd and THEN the service will start successfully.   

          inherit_parent_permissions => false,
Seemed to do the trick.

**Comment by Smjert** [comment]
Closing this since a quick test on a Windows 10 shows that it works.
Also the folder where osquery is installed has changed and the permission too slightly.
