### ISSUE TITLE
Unknown command line flags:'logger_kafka_brokers' 'logger_kafka_topic'

### ISSUE THREAD

**Issue by nishantgaonkar** [osquery/osquery#4616]
Osquery version 3.4.6
Using kafka logging flags gives a unknown command error in the cmd. Osqueryd -h does not list kafka related flags. Tried changing the logger_plugin to kafka_producer but it didn't work. 
![cap1](https://user-images.githubusercontent.com/35428611/41707239-4856f646-755b-11e8-9b9b-065fa0372738.PNG)
![capture](https://user-images.githubusercontent.com/35428611/41707467-c64d9280-755b-11e8-8e46-61c87345f61a.PNG)

**Comment by theopolis** [comment]
Kafka is not available on Windows and FreeBSD in osquery right now: https://github.com/facebook/osquery/blob/master/osquery/logger/CMakeLists.txt#L54

**Comment by mike-myers-tob** [comment]
Tracking this over on #5678
