### ISSUE TITLE
possible mem-leak in windows events

### ISSUE THREAD

**Issue by redplait** [osquery/osquery#4649]
after 3 week running of service osqueryd.exe it consuming about 150mb of memory
so I made full dump within process explorer (size of file is 236mb) and next run RogueKillerPE to extract strings
it seems that lots of them from windows events:
grep -i eventdata strs | wc -l
1376
grep windows_event strs | wc -l
2733
and also presents lots of blocks like this:
`
Offset: 10269267 - ws_event_log.windows_events.60.25500780
Offset: 10269314 - 0000011221:1530046820,0000011222:15300468203
Offset: 10269369 - 0000011223:1530047241,0000011224:15300472412
Offset: 10269425 - 0000011225:1530047660,0000011226:15300476601
Offset: 10269482 - 0000011227:1530048081,0000011228:15300480813
Offset: 10269537 - 0000011229:1530048500,0000011230:15300485002
Offset: 10269593 - 0000011231:1530048921,0000011232:15300489213
Offset: 10269648 - 0000011233:15300490572
Offset: 10269682 - 0000011234:1530049340,0000011235:15300493403
Offset: 10269737 - 0000011236:1530049785,0000011237:15300497852
Offset: 10269793 - 0000011238:1530049827,0000011239:1530049827,0000011240:15300498273
Offset: 10269870 - 0000011241:1530050180,0000011242:15300501802
Offset: 10269926 - 0000011243:1530050600,0000011244:15300506002
Offset: 10269982 - 0000011245:1530051020,0000011246:15300510203
Offset: 10270037 - 0000011247:1530051440,0000011248:15300514402
Offset: 10270093 - 0000011249:1530051860,0000011250:15300518602
Offset: 10270149 - 0000011251:1530052280,0000011252:1530052280
`

**Comment by muffins** [comment]
Oooo, thank you for filing. I'll jump on this asap, unless you happen to find it and wanna patch yerself :)

We should also work to find a good way to plug in a CI test for leak analysis. I have a few Python integration test diffs on the way, but haven't had time to prioritize them. That being said, I'll add another integration test for the Windows Event log pipe. Thanks!

**Comment by redplait** [comment]
well, I still cannot find reason of mem-leak
but next most leaked objects have size 0xb0 and looks like:
offset 0x10 - ptr to string "Services"
offset 0x48 - ptr to string "Console"
offset 0x90 - ptr to some memory with size 0x10 and "tmp" as 3 first bytes
offset 0x98 - ptr to machine name
can you identify this structure ?

**Comment by theopolis** [comment]
The windows eventing features have been redesigned recently. Please let us know if this is still an issue.
