### ISSUE TITLE
memory leak in genLoggedInUsers

### ISSUE THREAD

**Issue by redplait** [osquery/osquery#4655]
I analyzed memory dump in windbg with !heap -l and then wrote simple perl script to calculate stat of sizes leaked blocks
results are:
A0 **80659**
4D0 **80596

**
20 54034
10 53737
B0 26862
3D0 2984
as you can see we have two leaders with the same count of leaked blocks. this is WTSINFOA (size 0x90) and WTSCLIENTA (size 0x4b0). lets see why they was leaked
msdn say that after calling of WTSQuerySessionInformationA (https://docs.microsoft.com/ru-ru/windows/desktop/api/wtsapi32/nf-wtsapi32-wtsquerysessioninformationa)

"To free the returned buffer, call the WTSFreeMemory function"

and in code osquery\tables\system\windows\logged_in_users.cpp WTSFreeMemoryEx was called
the patch in attach
[1.txt](https://github.com/facebook/osquery/files/2145738/1.txt)

**Comment by muffins** [comment]
@redplait nice find, that patch looks good. Any desire to throw it up as a PR?
