### ISSUE TITLE
Q: is it posible in osquery, to select from augeas and specify the lens ?

### ISSUE THREAD

**Issue by mboldi-uptycs** [osquery/osquery#4659]
I have 8 files in Linux that there is no lens.  audit.rules, /etc/motd ....  others

So I altered the simplelines.aug file to pull in the /etc/audit/audit.files ... but I would prefer a "hint" syntax so I would not have to alter this file ( or create a new file ) to handle this file ( and others   ).

something like

select * from augeas.simplelines where path = '/etc/audit/audit.files'
or
select * from augeas ( using simplelines ) where path = '/etc/audit/audit.files'

This way I have more flexibility 

Is it true that the path MUST be in the   ->  let filter = incl ..... 
section of a lens ?   There is no way to pull in a random file ? 

I see that there is an environment variable where you can override the location of all lenses like so
 --augeas_lenses=/usr/share/osquery/lenses
That is not an option for me.  I was also thinking ( as a temporary measure ) creating and installing a few new lens files, basically copies of simplelines.

### What version of `osquery` are you using? What operating system. Be specific.
You can run this query to get the necessary details: 
```
osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'
```

**Comment by theopolis** [comment]
Could you use your configuration management tools to install these lenses into `/usr/share/osquery/lenses`?

**Comment by mboldi-uptycs** [comment]
I think we will need to .. as far as I can tell, one must mention a path to
the file you want to parse .. There is no osquery option like  select *
from augeas ( using simplelines.aug) where path = '/some/random/file'

I'd like to see a way of parsing any file. Albeit a simple parsing ..
eventually one might any (random) file ..  and if simplelines is good
enough .. a syntax like
select * from augeas.simplelines where path = '/whatever......'  would be
cool ..

I am trying to fulfill the CIS controls for security concerns ... and there
are many files not currently covered ..  and most controls are simple greps
..  simplelines is great ..  but my concern is that eventually files like
-->  /etc/audit/audit.rules
will have a lens created, then in my install routine, there will be
redundancy in   lens files ...  YIKES !!

**Comment by directionless** [comment]
When I refactored Augeas a bit ago, I noticed that augeas itself isn't designed to work this way. It has lenses, and it loads _all_ files matching all lenses. I opted to use that, and not re-load augeas for each query.
