### ISSUE TITLE
argparse documentation for `persist` arg in test_http_server.py inaccurate

### ISSUE THREAD

**Issue by zbuc** [osquery/osquery#4674]
Looks like the documentation for the `persist` argument isn't correct (copied from `tls` arg):

https://github.com/facebook/osquery/blob/5fa1ebad132f436f47c9e9c5a40c0d0dff88c343/tools/tests/test_http_server.py#L409

**Comment by muffins** [comment]
Ah nice, good catch!

**Comment by pramos** [comment]
I believe this issue should be closed as it was fixed in #5095
