### ISSUE TITLE
deploy: msi repair option causes application file size increased

### ISSUE THREAD

**Issue by Apptestingrd** [osquery/osquery#4700]
application file size increase about 10 MB on Add\Remove control panel after each repair process. (after standalone installation) by clicking repair option by right clicking the msi file.. through GP using msiexec.exe with a repair parameter (/f...) as a Startup script

is it expected behaviour that the repair option causes the application size increased?

**Comment by fmanco** [comment]
@Apptestingrd please provide more information and try to adhere to template provided. What osquery version and OS version are you running? What are you trying to achieve? What exact command are you running? etc.

**Comment by Apptestingrd** [comment]
I tried with 3.2.4 (downloaded from osquery.io web site) and 3.2.6 (i've taken built using powershell script provided by osquery) I think it is valid for all versions. the issue is related to repair... 
Repair option might be preferred for some reasons...
as i mentioned above, (1)right click the application and click repair or (2) in deployment phase,repair through Active Directory / Group policy as a Startup script using the command msiexec.exe with a repairing parameter /f... (from Computer Configuration - policies -windows settings-Scripts - Startup)
in both cases, the situation happens

**Comment by muffins** [comment]
There's a couple of issues with the MSI, not only does the repair option increase the file size, but uninstall leaves behind residual artifacts (this was actually intended, but sounds like some folks might not want that ^.^). Let's use this issue to enumerate any problems the MSI deployment has so we can scope out what all needs doing. /CC @johnnyramos

**Comment by Rich5** [comment]
As a follow-up from Slack: Some things we noticed is when updating osquery on Windows the MSI makes things difficult; especially in fleet deployment scenarios. I get the point of leaving the DB and it's a good idea for upgrades, but we observed that the DB permissions caused the osquery service to not start after upgrading sometimes. Best guess is because the the DB can't be accessed. The second thing we noticed is that if you just run the MSI to upgrade there will be multiple instances of osquery in the add/remove programs list. We sort of handle this with extra scripts right now but it's cumbersome.

**Comment by Apptestingrd** [comment]
we got rid of some deployment problems (multiple instance of installed osquery, file size increase...) by modifying the msi file ... 
we extracted the msi file and added InstallScope="perMachine" to wxs file and regenerated the msi file... we used dark.exe candle.exe, light.exe for this purpose)

but repairing is still an issue. Thanks

**Comment by Smjert** [comment]
I think the DB permissions issues has been solved with the new MSI generation which installs under `Program Files` and gives access to the `Administrators` group.
I've also tested the repair option via MSI file (I've also deleted osqueryi.exe to check that it would restore it); everything seems in order, every deleted file is restored and the size reported on the Windows 10 Apps&features doesn't change/is correct.

Closing this, but feel free to reopen if you experience this with the latest version.
