### ISSUE TITLE
chocolatey: bad osqueryd acl on windows server 2008/2012

### ISSUE THREAD

**Issue by keeleysam** [osquery/osquery#4729]
### What version of `osquery` are you using? What operating system. Be specific.
3.2.9, Windows Server 2012 R2

### What have you already tried?
Install osquery 2.9.1 or later on Windows Server 2008 R2 or Windows Server 2012 R2 via Chocolatey, then attempt to install service.

### What did you expect to see?
Service installable and able to start.
osqueryd able to be launched manually

### What did you see instead?

When installing, you'll see the message:
```Attempted to perform an unauthorized operation.
Access to the path 'C:\ProgramData\osquery\osqueryd' is denied.
```
The ACLs on the folder end up with nobody having access:
<img width="743" alt="screenshot 2018-07-18 16 46 35" src="https://user-images.githubusercontent.com/2081075/42916192-cb148f36-8ab8-11e8-8de7-61767b90b35e.png">

### Notes
- Upgrades have the same issue
- This appears related to changes in c494bc56ae45e4a92d6fc089c6c00588a916b848
- This is not an issue on Windows 10 or Windows Server 2016
- Reproducible on vanilla installs, nothing other than Chocolatey installed.
- osquery 2.9.0 installs fine

**Comment by polylogyx** [comment]
Ran into this issue yesterday. If it helps, adding my observations.

Installation tool: MSI

Operating System: Windows Server 2008 R2

1) When upgrading from a previous installed osquery (2.9.0) to later one (3.2.6), hit the issue of osqueryd service not getting started
2) When tried on a clean system (with no previous osquery), it worked fine.

**Comment by mike-myers-tob** [comment]
This might have been fixed with
https://github.com/osquery/osquery/pull/7166
or 
https://github.com/osquery/osquery/pull/7182
or
https://github.com/osquery/osquery/pull/5790 and the path has moved away from `ProgramData`

Closing this issue but feel free to re-open it if it was never fixed
