### ISSUE TITLE
Osquery doesn't distinguish between installed and removed packages.

### ISSUE THREAD

**Issue by nuritizra** [osquery/osquery#4740]
Hi,

I'm using Osquery to query the table deb_packages - the installed DEB package database.
I'm using Osquery version 2.9.0.
Operating System - Linux.
It apears that Osquery doesn't distinguish between installed and removed packages when querying the deb_packages table.
Only after purging the packages, we don't see them packages in the result of the query.

The  details:

```*@guc3-*:~$ sudo osqueryd -S --line 'SELECT * from deb_packages WHERE name="libdw1" LIMIT 1;'```

```
*@guc3-*:~$  sudo apt-get install libdw1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libdw1
0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 0 B/173 kB of archives.
After this operation, 697 kB of additional disk space will be used.
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
Selecting previously unselected package libdw1:amd64.
(Reading database ... 85587 files and directories currently installed.)
Preparing to unpack .../libdw1_0.158-0ubuntu5.3_amd64.deb ...
Unpacking libdw1:amd64 (0.158-0ubuntu5.3) ...
Setting up libdw1:amd64 (0.158-0ubuntu5.3) ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
```

```
*@guc3-*:~$ sudo osqueryd -S --line 'SELECT * from deb_packages WHERE name="libdw1" LIMIT 1;'
    name = libdw1
 version = 0.158-0ubuntu5.3
  source = elfutils
    size = 681
    arch = amd64
revision = 0ubuntu5.3

```
```
*@guc3-*:~$ sudo apt-get remove libdw1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libdw1
0 upgraded, 0 newly installed, 1 to remove and 47 not upgraded.
After this operation, 697 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 85622 files and directories currently installed.)
Removing libdw1:amd64 (0.158-0ubuntu5.3) ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
```

```
*@guc3-*:~$ sudo osqueryd -S --line 'SELECT * from deb_packages WHERE name="libdw1" LIMIT 1;'
    name = libdw1
 version = 0.158-0ubuntu5.3
  source = elfutils
    size = 681
    arch = amd64
revision = 0ubuntu5.3
```
### What did you expect to see?
I expected to see empty results.

```
*@guc3-*:~$ sudo apt-get purge libdw1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libdw1*
0 upgraded, 0 newly installed, 1 to remove and 47 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
(Reading database ... 85586 files and directories currently installed.)
Removing libdw1:amd64 (0.158-0ubuntu5.3) ...
Purging configuration files for libdw1:amd64 (0.158-0ubuntu5.3) ...
```

```*@guc3-*:~$ sudo osqueryd -S --line 'SELECT * from deb_packages WHERE name="libdw1" LIMIT 1;'```

<!--
### What version of `osquery` are you using? What operating system. Be specific.
You can run this query to get the necessary details: 
```
osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'
```

### What did you see instead?
--!>

**Comment by theopolis** [comment]
Seems to work as expected on Ubuntu 16.04 without needing to `purge`, interesting.

**Comment by rnhsp** [comment]
I'm on the same team as @nuritizra. The system we're seeing this on is running Ubuntu 14.04 (LTS), which is supported by Canonical for another 8 months.

```bash
$ sudo osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'
osquery_version = 2.9.0
     os_version = 14.04, Trusty Tahr
       os_build =
    os_platform = ubuntu
```

**Comment by rnhsp** [comment]
@theopolis: Is this considered a bug and is Ubuntu 14.04 a version osquery supports? The documentation for this table speaks about installed packages, so the observed behavior is both unexpected and unfortunate as it gives us wrong information without an apparent way of adjusting our query to fix it.

**Comment by dgriffin831** [comment]
@theopolis I don't know how this worked for you in 16.04. Anything you can add about your testing scenario that may have produced a different result?

I tested the scenario in Ubuntu 16.04 and 18.04.1 just now using both Osquery 2.11.2 and Osquery 3.3.0 and had the issue in all cases. I remove a package without purge and it becomes "rc" status but still shows in the results.

IMO, adding a "status" column with status code (ii, rc, etc) would be a very helpful improvement.

**Comment by rnhsp** [comment]
+1 for status column! Ideally breaking the letters apart into their respective representation – desired package state, current package state, (error state) – see https://askubuntu.com/a/18807.
