### ISSUE TITLE
can't install osquery.man manifest

### ISSUE THREAD

**Issue by gnomefish** [osquery/osquery#4773]
### What version of `osquery` are you using? What operating system. Be specific.

3.2.6 on windows

### What have you already tried?

wevtutil im C:\ProgramData\osquery\osquery.man

PS C:\ProgramData\osquery> .\manage-osqueryd.ps1 -installWelManifest

### What did you expect to see?

Manifest to be successfully installed

### What did you see instead?

Result with WEVUTIL:
C:\ProgramData\osquery\osquery.man(0): Error 0x800c0006: At column=0, The system cannot locate the object specified.

Failed to load xml document C:\ProgramData\osquery\osquery.man. Incorrect function.

Result with PS:
[-] Failed to find the osquery Event Log manifest file! (C:\ProgramData\osquery\osquery.man)

**Comment by Smjert** [comment]
I don't believe this is an issue anymore since we restored the WEL plugin in https://github.com/osquery/osquery/pull/6164
