### ISSUE TITLE
Add instance metadata table(s) for Microsoft Azure Cloud

### ISSUE THREAD

**Issue by praksinha** [osquery/osquery#4782]
Currently we have '**ec2_instance_metadata**' and '**ec2_instance_tags**' table for AWS EC2 instances.
It would be great if we can similar table for **Microsoft Azure cloud**. 

Few important columns that table might have are:
- Subscription ID
- Resource Group
- Region
- Availability Zone
- Image Id
- Image Name (or VHD name)
- Instance Type
- Instance ID or VM ID
- MAC
- hostname
- Private IP
- ssh_key (if any)
- Instance Tags (Can be moved to separate table altogether like we have ec2_instance_tags)

Above are few suggestions for columns that can be '**azure_vm_metadata**' table and or '**azure_vm_tags**' table.

**Comment by Smjert** [comment]
Implemented in https://github.com/osquery/osquery/pull/5434
