### ISSUE TITLE
License not included in Debian packages / metadata is possibly inaccurate

### ISSUE THREAD

**Issue by jordemort** [osquery/osquery#4786]
### What version of `osquery` are you using? What operating system. Be specific.

3.2.6-1.linux on Debian jessie

```
osquery_version = 3.2.6
     os_version = 8 (jessie)
       os_build = 
    os_platform = debian
```

### What have you already tried?

By convention, Debian packages install their licenses in `/usr/share/doc/<package name>/copyright`; I have tooling that depends on this to determine the licenses of the packages we are distributing.

I tried finding the license for osquery in `/usr/share/doc/osquery/copyright`

### What did you expect to see?

I expected to find the license for the `osquery` package in that location

### What did you see instead?

That file does not exist.

The `osquery` deb does include a `License: BSD` line in its control file. That's not a standard control header though, Debian doesn't use it (although it's preserved and parsable) - it's also not entirely sufficient, since it doesn't contain any information about the copyright holder. It also seems like it might be inaccurate, since https://github.com/facebook/osquery/blob/master/LICENSE appears to be an Apache license to me.

**Comment by Smjert** [comment]
This is now also tracked here: https://github.com/osquery/osquery/issues/5769
