### ISSUE TITLE
`system_info` incorrectly reporting `cpu_physical_cores` column

### ISSUE THREAD

**Issue by allanliu** [osquery/osquery#4811]
Currently the `system_info` table reports[ `cpu_physical_cores` incorrectly as the same value as what the system has for `cpu_logical_cores`.](https://github.com/facebook/osquery/blob/master/osquery/tables/system/linux/system_info.cpp#L43-L47)

I'd like to take on this bug soon.  However, there are a few approaches we can take for this and  I wanted to see what the general feelings are about each of them:
1. Parse `/proc/cpuinfo`  and calculate the physical cores as the comment says.
2. Calculate the cores from walking `sys` (for linux)
3. Utilize [hwloc](https://www.open-mpi.org/projects/hwloc/).  Source is [here](https://github.com/open-mpi/ompi).

The 3rd option is the most interesting in that `hwloc` provides a C API that is both cross-platform, and allows us to trivially retrieve information regarding CPU topology including CPU sockets, cores, threads, cache info, NUMA info, etc.  Many, if not most, of which is not currently exposed by osquery.  However, after playing with the library a bit on `xenial` and `trusty`, even when just reading data, `strace` revealed `sched_setaffinity` syscalls.  It does look as if those calls are made just to test the capability of the process since CPU binding is part of the API (looked thru the source some, but haven't found the smoking gun proving this yet, but wanted get some feedback from the community going first before proceeding down this path further).  However, they are still calls that can mutate the state of the calling process and in general we're not as interested in bringing in new 3rd party dependencies into the core, especially given that this particular table is pretty core to the system and cannot and should not be build bypass-able.  On the contrary, utilizing this library does opens the door to an easy, clean, cross-platform way of exposing CPU topography.  Thoughts?

Example from strace output on `trusty`:
```
sched_getaffinity(0, 8, {ffffffffffffffff}) = 8
sched_getaffinity(0, 8, {ffffffffffffffff}) = 8
sched_setaffinity(0, 8, {1})            = 0
sched_setaffinity(0, 8, {2})            = 0
sched_setaffinity(0, 8, {4})            = 0
sched_setaffinity(0, 8, {8})            = 0
sched_setaffinity(0, 8, {10})           = 0
sched_setaffinity(0, 8, {20})           = 0
sched_setaffinity(0, 8, {40})           = 0
sched_setaffinity(0, 8, {80})           = 0
sched_setaffinity(0, 8, {100})          = 0
sched_setaffinity(0, 8, {200})          = 0
sched_setaffinity(0, 8, {400})          = 0
sched_setaffinity(0, 8, {800})          = 0
sched_setaffinity(0, 8, {1000})         = 0
sched_setaffinity(0, 8, {2000})         = 0
sched_setaffinity(0, 8, {4000})         = 0
sched_setaffinity(0, 8, {8000})         = 0
sched_setaffinity(0, 8, {10000})        = 0
sched_setaffinity(0, 8, {20000})        = 0
sched_setaffinity(0, 8, {40000})        = 0
sched_setaffinity(0, 8, {80000})        = 0
sched_setaffinity(0, 8, {100000})       = 0
sched_setaffinity(0, 8, {200000})       = 0
sched_setaffinity(0, 8, {400000})       = 0
sched_setaffinity(0, 8, {800000})       = 0
sched_setaffinity(0, 8, {1000000})      = 0
sched_setaffinity(0, 8, {2000000})      = 0
sched_setaffinity(0, 8, {4000000})      = 0
sched_setaffinity(0, 8, {8000000})      = 0
sched_setaffinity(0, 8, {10000000})     = 0
sched_setaffinity(0, 8, {20000000})     = 0
sched_setaffinity(0, 8, {40000000})     = 0
sched_setaffinity(0, 8, {80000000})     = 0
sched_setaffinity(0, 8, {100000000})    = 0
sched_setaffinity(0, 8, {200000000})    = 0
sched_setaffinity(0, 8, {400000000})    = 0
sched_setaffinity(0, 8, {800000000})    = 0
sched_setaffinity(0, 8, {1000000000})   = 0
sched_setaffinity(0, 8, {2000000000})   = 0
sched_setaffinity(0, 8, {4000000000})   = 0
sched_setaffinity(0, 8, {8000000000})   = 0
sched_setaffinity(0, 8, {10000000000})  = 0
sched_setaffinity(0, 8, {20000000000})  = 0
sched_setaffinity(0, 8, {40000000000})  = 0
sched_setaffinity(0, 8, {80000000000})  = 0
sched_setaffinity(0, 8, {100000000000}) = 0
sched_setaffinity(0, 8, {200000000000}) = 0
sched_setaffinity(0, 8, {400000000000}) = 0
sched_setaffinity(0, 8, {800000000000}) = 0
sched_setaffinity(0, 8, {1000000000000}) = 0
sched_setaffinity(0, 8, {2000000000000}) = 0
sched_setaffinity(0, 8, {4000000000000}) = 0
sched_setaffinity(0, 8, {8000000000000}) = 0
sched_setaffinity(0, 8, {10000000000000}) = 0
sched_setaffinity(0, 8, {20000000000000}) = 0
sched_setaffinity(0, 8, {40000000000000}) = 0
sched_setaffinity(0, 8, {80000000000000}) = 0
sched_setaffinity(0, 8, {100000000000000}) = 0
sched_setaffinity(0, 8, {200000000000000}) = 0
sched_setaffinity(0, 8, {400000000000000}) = 0
sched_setaffinity(0, 8, {800000000000000}) = 0
sched_setaffinity(0, 8, {1000000000000000}) = 0
sched_setaffinity(0, 8, {2000000000000000}) = 0
sched_setaffinity(0, 8, {4000000000000000}) = 0
sched_setaffinity(0, 8, {8000000000000000}) = 0
sched_setaffinity(0, 8, {ffffffffffffffff}) = 0
```

**Comment by uptycs-nishant** [comment]
https://www.boost.org/doc/libs/1_58_0/doc/html/thread/thread_management.html
----------------------------------------------------------
@allanliu , hardware_concurrency Vs physical_concurrency

## Static member function hardware_concurrency()
###unsigned hardware_concurrency() noexecpt;

Returns:
The number of hardware threads available on the current system (e.g. number of CPUs or cores or hyperthreading units), or 0 if this information is not available.

Throws:
Nothing

## Static member function physical_concurrency()
### unsigned physical_concurrency() noexecpt;

Returns:
The number of physical cores available on the current system. In contrast to hardware_concurrency() it does not return the number of virtual cores, but it counts only physical cores.

Throws:

**Comment by allanliu** [comment]
@uptycs-nishant That's a good suggestion.  I was unaware of those boost API's.  I definitely think that's the way to go for this particular bug fix :)

However, there's a good change we will need additional cpu topology information at some point in the future, but that's probably best suited as a separate, and optional table, which would change the scope of this dependency.  Regardless, that would be a different discussion all together.

**Comment by allanliu** [comment]
[PR](https://github.com/facebook/osquery/pull/4848) up.
