### ISSUE TITLE
Installing osquery on Windows 7

### ISSUE THREAD

**Issue by balahmadi-Ox** [osquery/osquery#4854]
I am trying to install osquery though Chocolatey on Windows 7. Although installing with 'administrative privileges - I get an error 'Attempted to perform an unauthorized operation' , 'Access to the path is denied' C:\ProgramData\osquery\osqueryd. 
I attempted to change the permission of the osquery folder and was able to finally install the osquery service but then it won't run and I get error 1067.

**Comment by muffins** [comment]
Going to close this out as I believe it _may_ be irrelevant with recent changes to _where_ we are installing osquery, as well as the numerous components of our deployment scripts that have changed. If you're still having issues with installing osquery through Chocolatey on Windows 7 please re-open!
