### ISSUE TITLE
Create tests for the table `chrome_extensions`

### ISSUE THREAD

**Issue by akindyakov** [osquery/osquery#4926]
## Create tests for the table `chrome_extensions`

  - Create header file for the table implementation, if one is not exists.
  - In test, query the table and check if retrieved columns (name and types) match the columns from table spec.
  - If there is any guarantee to number of rows (e.g. only 1 record in every query result, more than 3 records or something else) check it.
  - Test the implementation details of the table, if it possible.

Table spec: `specs/chrome_extensions.table`

Source files:

  - `applications/browser_chrome.cpp`

Table generating function: `genChromeExtensions()`

Labels: `good-first-issue` `build/test`

**Comment by mike-myers-tob** [comment]
Thanks again Rachel.
