### ISSUE TITLE
deps: Update Windows SDK to latest version

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#4973]
Seems like our current provisioning script is referencing an outdated version of the Windows SDK. We need to update to ensure the provisioning is running smoothly.

**Comment by defensivedepth** [comment]
Confirmed this issue on a fresh W10 install & provision attempt.

I think the only thing that needs to change is the choco package name -

 `'windows-sdk-10'` ([Package Info](https://chocolatey.org/packages/windows-sdk-10)) or `'windows-sdk-10.1'` ([Package Info](https://chocolatey.org/packages/windows-sdk-10.1)):

https://github.com/facebook/osquery/blob/master/tools/provision.ps1#L462

**Comment by muffins** [comment]
I think we've addressed this issue with recent build system changes. I'm going to close this issue out, if folks are still having issues with legacy Win SDK versions please re-open
