### ISSUE TITLE
Create tests for the table `account_policy_data`

### ISSUE THREAD

**Issue by akindyakov** [osquery/osquery#5018]
## Create tests for the table `account_policy_data`

  - Create header file for the table implementation, if one is not exists.
  - In test, query the table and check if retrieved columns (name and types) match the columns from table spec.
  - If there is any guarantee to number of rows (e.g. only 1 record in every query result, more than 3 records or something else) check it.
  - Test the implementation details of the table, if it possible.

Table spec: `specs/darwin/account_policy_data.table`

Source files:

  - `osquery/tables/system/darwin/account_policy_data.mm`

Table generating function: `genAccountPolicyData()`

**Comment by 0xmilkmix** [comment]
working on this one. Just hitting a limits on `tryTo<double>` to create a test to validate that `failed_login_timestamp` >= `creation_time`.
As discussion on slack, looks like the solution would be to provide a `tryTo<double>` in `tryto.h`. If that's ok, I can provide such a PR
