### ISSUE TITLE
Create tests for the table `apps`

### ISSUE THREAD

**Issue by akindyakov** [osquery/osquery#5020]
## Create tests for the table `apps`

  - Create header file for the table implementation, if one is not exists.
  - In test, query the table and check if retrieved columns (name and types) match the columns from table spec.
  - If there is any guarantee to number of rows (e.g. only 1 record in every query result, more than 3 records or something else) check it.
  - Test the implementation details of the table, if it possible.

Table spec: `specs/darwin/apps.table`

Source files:

  - `osquery/tables/system/darwin/apps.mm`

Table generating function: `genApps()`

**Comment by nasehim7** [comment]
Hey! what kind of assertions can there be for the "apps" table?
One trivial assertion could be - the size of the table would be atleast one i.e. atleast a row will exist.
Moreover, if not this, just checking the retrieved columns with the columns from the table spec should suffice, I think.
