### ISSUE TITLE
Create tests for the table `startup_items`

### ISSUE THREAD

**Issue by akindyakov** [osquery/osquery#5058]
## Create tests for the table `startup_items`

  - Create header file for the table implementation, if one is not exists.
  - In test, query the table and check if retrieved columns (name and types) match the columns from table spec.
  - If there is any guarantee to number of rows (e.g. only 1 record in every query result, more than 3 records or something else) check it.
  - Test the implementation details of the table, if it possible.

Table spec: `specs/macwin/startup_items.table`

Source files:

  - `osquery/tables/system/darwin/startup_items.cpp`
  - `osquery/tables/system/windows/startup_items.cpp`

Table generating function: `genStartupItems()`

**Comment by muffins** [comment]
Looks like this has been completed.
