### ISSUE TITLE
Create tests for the table `cpuid`

### ISSUE THREAD

**Issue by akindyakov** [osquery/osquery#5060]
## Create tests for the table `cpuid`

  - Create header file for the table implementation, if one is not exists.
  - In test, query the table and check if retrieved columns (name and types) match the columns from table spec.
  - If there is any guarantee to number of rows (e.g. only 1 record in every query result, more than 3 records or something else) check it.
  - Test the implementation details of the table, if it possible.

Table spec: `specs/cpuid.table`

Source files:

  - `osquery/tables/system/cpuid.cpp`

Table generating function: `genCPUID()`

**Comment by aalon2** [comment]
hi, I like to take this one if no one already working on it. it's my first task here so I'll appreciate some guide here - is there an example of tests for table that already working?

**Comment by muffins** [comment]
@aalon2 did you ever have a chance to ship the tests for this? We'd love to help you out if you need, let us know if you've made any progress!
