### ISSUE TITLE
Create tests for the table `curl_certificate`

### ISSUE THREAD

**Issue by akindyakov** [osquery/osquery#5061]
## Create tests for the table `curl_certificate`

  - Create header file for the table implementation, if one is not exists.
  - In test, query the table and check if retrieved columns (name and types) match the columns from table spec.
  - If there is any guarantee to number of rows (e.g. only 1 record in every query result, more than 3 records or something else) check it.
  - Test the implementation details of the table, if it possible.

Table spec: `specs/curl_certificate.table`

Source files:

  - `osquery/tables/networking/curl_certificate.cpp`

Table generating function: `genTLSCertificate()`

**Comment by saketepe** [comment]
Hi, can I work on this?
