### ISSUE TITLE
deps: sanitizer builds link against libstdc++

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5074]
The clang sanitizer libraries are compiled when `clang-rt` is built. At this point the only C++ available is GCC's. This means the sanitizer libraries are not portable. Trying to run `make libfuzz` shows this, you are most likely to run into linking issues when you try.

To fix this we should use a "stage1" and "stage2" build in the formula, where the runtime + sanitizers are built, then libc++, then build the sanitizers again and tweak the CMake options to use the locally built c++.

**Comment by Smjert** [comment]
This has been solved with the `osquery-toolchain`.
