### ISSUE TITLE
deps: Several issues when building dependencies from source

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5075]
There are a few problems with building dependencies from source on Linux.

The command `make build_deps` fails:
- [ ] bzip needs a mirror (showing bad-hash due to downloading a 200-as-404-page): https://jenkins.osquery.io/job/osqueryMasterDependenciesLinux/425/TargetSystem=aws-ubuntu-16.04/console
- [ ] cmake should build it's gzip/bzip/curl locally

**Comment by mike-myers-tob** [comment]
Was this all fixed with https://github.com/osquery/osquery/pull/5706 ?
