### ISSUE TITLE
Store Host UUID on a file

### ISSUE THREAD

**Issue by fmanco** [osquery/osquery#5101]
# Task

Start storing the host UUID on a file instead of the Database.

Background: osquery sources the host UUID preferably from the hardware and resorts to generating an UUID only when this fails. This process has two problems:

* The concept of host shouldn't necessarily be tied to the hardware where osquery is running but rather to the filesystem osquery is running on.
* osqueryi cannot read from the DB while osqueryd is running. When the hardware does not provide a valid UUID osqueryi will present a different UUID every time it starts.

A quick solution for this problem is to start writing the UUID to a file as oppose to the DB.

Implementation:

1. Create a new [DB migration](https://github.com/facebook/osquery/blob/6ff326213963fe3cec1ad893ec3e61fb79339a4a/osquery/database/database.cpp#L562-L626) to retrieve the value from the DB, write it to the file and delete it from DB (if the UUID already exists).
2. Change [getHostUUID()](https://github.com/facebook/osquery/blob/ce0592b4644923aa2239e07c0a6d5396a3133fe8/osquery/core/system.cpp#L237-L246) to fetch/store this information in a file.
3. Create tests

Note: UUID file path should be set using a flag.

**Comment by directionless** [comment]
I don't think this is going to happen. And truth be told, I'm not sure it's desirable. See comments in #7509
