### ISSUE TITLE
TLS module logger error

### ISSUE THREAD

**Issue by redragon68** [osquery/osquery#5102]
# Bug report

### What operating system and version are you using?

 version = CentOS Linux release 7.5.1804 (Core)
   build = 
platform = rhel

### What version of osquery are you using?

version = 3.2.6

### What steps did you take to reproduce the issue?

Configure osqueryd to post via the tls module to a remote system (custom or demo server)

### What did you expect to see?

Valid ssl communication to the remote system

### What did you see instead?

SSL SHORT_READ_ERROR: http_client closing socket

### Additional information

1) If osqueryd is posting to localhost there is not an issue.
2) if osqueryd is posting to a remote host then you receive the error
3) If you enable --verbose then the error goes away and osqueryd posts successfully to the tls endpoing
4) This has been tested on ubuntu 14.04 package of osquery as well
5) All packages were installed from repositories listed on osquery.io website, no custom builds
6) The issue only presents itself on the logger call, not on the enroll or config calls

**Comment by nicholastripp** [comment]
We're seeing this on our clients across several platforms.

**Comment by anfasci** [comment]
I am also facing this issue in newer version

**Comment by theopolis** [comment]
There has been a lot of work to improve osquery over the last few years. Please open a new issue if you are still facing a related problem.
