### ISSUE TITLE
Certificate table shows serial number incorrectly.

### ISSUE THREAD

**Issue by scudette** [osquery/osquery#5104]
# Bug report

The certificates table shows the serial number reversed (wrong endianess). This is because the serial number is actually a big int and it is encoded in little endian form. The code simply hex encodes the encoded form:

```
    std::string serial;
    boost::algorithm::hex(
        std::string(certContext->pCertInfo->SerialNumber.pbData,
                    certContext->pCertInfo->SerialNumber.pbData +
                        certContext->pCertInfo->SerialNumber.cbData),
        back_inserter(serial));
    r["serial"] = serial;
```

Which is incorrect since it needs to also deal with byte endianess. The overall result is that the serial number it shows is backwards from the one, say, windows certmgr shows.

![image](https://user-images.githubusercontent.com/3856546/44616646-d6f8f200-a896-11e8-9e48-487533419d4d.png)

### What operating system and version are you using?

Windows

### What version of osquery are you using?

3.2.4

**Comment by mike-myers-tob** [comment]
I just confirmed that this is still an issue even after the overhaul of the `certificates` table in osquery `4.0`.
