### ISSUE TITLE
Silence part or all: "Symlink loop detected possibly involving: ..."

### ISSUE THREAD

**Issue by juju4** [osquery/osquery#5161]
# Feature request

above message appears when using fim but is creating a lot of noise for paths where it is part of upstream distribution
ex: /lib/firmware, /etc/alternative/jre*, /usr/lib/jvm/jre*, /var/lib/docker/btrfs/subvolumes, /usr/lib/x86_64-linux-gnu/perl/, /usr/lib/gcc/x86_64-linux-gnu/7/

Thanks

### What new feature do you want?

We should have a way to suppress those warnings either globally, either for above paths.

### How is this new feature useful?

Avoid useless logs that take storage space, processing time and analyst time to review.

### How can this be implemented?

following part of the code should have a toogle option or an equivalent of fim exclude_paths.

https://github.com/facebook/osquery/blob/5f9552fa0ecface0fa056f7b934f661b70295fa1/osquery/filesystem/filesystem.cpp#L289

**Comment by guliashvili** [comment]
Thanks for the feature request. I don't think there is anything stopping us from removing this warning. Feel free to open PR and we can discuss with others if anyone has any use for that.

**Comment by theopolis** [comment]
This has been implemented.

**Comment by juju4** [comment]
Thanks for https://github.com/osquery/osquery/pull/6545 !
