### ISSUE TITLE
system processes start_time in processes table (Windows) is -1

### ISSUE THREAD

**Issue by Omer-N** [osquery/osquery#5168]
# Bug report

### What operating system and version are you using?
```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.17134 | 17134 | windows  |
+------------+-------+----------+
```

### What version of osquery are you using?
```
+---------+
| version |
+---------+
| 3.2.6   |
+---------+
```

### What steps did you take to reproduce the issue?
When querying processes table on Windows machines, I encounter a lot of missing start times (Instead of the real start time I receive -1).
It's especially occurs for system's processes and high privileged processes, and also the uid and gid of these processes are 0.
I think that it's a permissions issue because it's correlated with this code (`processes.cpp`):
```
if (GetLastError() == ERROR_ACCESS_DENIED) {
		uid = 0;
		gid = 0;
	}
```

**Suggestion for solution:**
I tried to search for the causes in the source files and I see that in `processes.cpp` there's a privilege issue and when the access is denied for `OpenProcess` the start_time is -1.
Even when I'm running osquery as administrator I got this issue,
therefore I think that it's because there should be a call to `AdjustTokenPrivileges` to request the privilege `SE_SYSTEM_PROFILE_NAME` (and also maybe `SE_DEBUG_NAME`). 

### What did you expect to see?
```
osquery> select pid, start_time from processes where start_time = -1 limit 5;
+-----+------------+
| pid | start_time |
+-----+------------+
+-----+------------+
```

### What did you see instead?
```
osquery> select pid, start_time from processes where start_time = -1 limit 5;
+-----+------------+
| pid | start_time |
+-----+------------+
| 0   | -1         |
| 4   | -1         |
| 72  | -1         |
| 128 | -1         |
| 588 | -1         |
+-----+------------+
```

**Comment by guliashvili** [comment]
Thanks for reporting the issue and the investigation. In general -1 is reported when for some reason osquery could not extract the column entry. Will update you if we find any solution to this problem.

**Comment by Omer-N** [comment]
@Rich5 
Hey, I'm using osqueryd as a service.
But as you mentioned, when trying to use osqueryi.exe I get the following results:
```
osquery> select count(*) from processes where start_time = -1;
+----------+
| count(*) |
+----------+
| 170      |
+----------+
```
And when running as a service or with `osqueryi.exe` via `psexec` with system permissions I get:
```
osquery> select count(*) from processes where start_time = -1;
+----------+
| count(*) |
+----------+
| 13       |
+----------+
```

The processes with the access denied problem (even when running as system or service) are the OS processes like: `System`, `services.exe`, `Registry` and etc..

**Comment by Rich5** [comment]
Those look like protected processes. Wonder if it's related to #4336

**Comment by Omer-N** [comment]
@Rich5 
Yes, It's really part of it.
Take a look on the following code:
```
if (pid == currentPid) {
		hProcess = GetCurrentProcess();
	}
	else {
		hProcess =
			OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, false, pid);
	}

	if (GetLastError() == ERROR_ACCESS_DENIED) {
		uid = 0;
		gid = 0;
	}
```
When you don't have permissions `hProcess` will be null.
Then few lines below we have these lines:
```
auto procRet =
		GetProcessTimes(hProcess, &createTime, &exitTime, &kernelTime, &userTime);
	if (procRet == FALSE) {
		r["user_time"] = BIGINT(-1);
		r["system_time"] = BIGINT(-1);
		r["start_time"] = BIGINT(-1);
	}
	else {
		// Windows stores proc times in 100 nanosecond ticks
		ULARGE_INTEGER utime;
		utime.HighPart = userTime.dwHighDateTime;
		utime.LowPart = userTime.dwLowDateTime;
		r["user_time"] = BIGINT(utime.QuadPart / 10000);
		utime.HighPart = kernelTime.dwHighDateTime;
		utime.LowPart = kernelTime.dwLowDateTime;
		r["system_time"] = BIGINT(utime.QuadPart / 10000);
		r["start_time"] = BIGINT(osquery::filetimeToUnixtime(createTime));
	}
```

Then it'll be False for sure because you're sending null, and therefore it'll put -1 in all these fields because of the missing permissions.
You can find it at `processes.cpp` at the method `genProcess`

**Comment by Rich5** [comment]
If adding SE_SYSTEM_PROFILE_NAME works then that's a nice solution to getting info for protected processes

**Comment by muffins** [comment]
I think we've largely closed this issue out with recent re-architecting of the `processes` table. Checking it now running as Administrator the only process I don't get the start time is for the `[System Process]`, which is somewhat to be expected as I'm not sure we can get much meta-information on this process. I'm going to close this out for now, but please feel free to re-open if you think we need to dig deeper, otherwise I'd say consider upgrading. If there's any other information we're not getting, perhaps let's open up a new issue to track against new versions of osquery?

```
osquery> select pid, name, path, start_time from processes where start_time = -1;
E1020 22:20:58.585969  7184 processes.cpp:312] Failed to lookup path information for process 4
E1020 22:20:58.586944  7184 processes.cpp:332] Failed to get cwd for 4 with 31
E1020 22:20:58.587939  7184 processes.cpp:312] Failed to lookup path information for process 104
E1020 22:20:58.588935  7184 processes.cpp:332] Failed to get cwd for 104 with 31
E1020 22:20:58.594919  7184 processes.cpp:312] Failed to lookup path information for process 2032
E1020 22:20:58.594919  7184 processes.cpp:332] Failed to get cwd for 2032 with 31
+-----+------------------+------+------------+
| pid | name             | path | start_time |
+-----+------------------+------+------------+
| 0   | [System Process] |      | -1         |
+-----+------------------+------+------------+
```
