### ISSUE TITLE
"--verbose" flag overrides the "--logger_min_status" flag

### ISSUE THREAD

**Issue by clong** [osquery/osquery#5212]
# Bug report
Possibly related to #4608 ?

### What operating system and version are you using?
Centos7 and MacOS 13.6

### What version of osquery are you using?
2.11.2 and 3.3.0

### What steps did you take to reproduce the issue?
1. Run osquery with the filesystem logger plugin and the `--logger_min_status=1` flag set. 
2. Observe that no .INFO log file is generated
3. Run osquery with both the `--logger_min_status=1`  and `--verbose` flag set.
4. Observe that a .INFO log file is created and the `--logger_min_status=1` flag is now ignored

### What did you expect to see?
I would expect the `--logger_min_status` flag to take precedent, or at least a notification from the daemon informing me that the verbose flag will override the `--logger_min_status` flag.

### What did you see instead?
The presence of the `--verbose` flag has the same behavior of not having the `--logger_min_status` flag present.

**Comment by guliashvili** [comment]
#5090  fixes

**Comment by clong** [comment]
Just updating this issue to clarify that the PR referenced above was never merged, therefore this bug is still alive and well.

**Comment by theopolis** [comment]
This is a clunky design but it's sort of working as intended. :/
