### ISSUE TITLE
`disk_encryption` schema on Mac with T2 chip incorrectly reports encryption status

### ISSUE THREAD

**Issue by rmcvey** [osquery/osquery#5223]
# Bug report

We are seeing issues on Mac machines with the new T2 chip reporting that the disk is encrypted when FileVault hasn't been enabled.

<img width="1284" alt="security___privacy_and_1__osqueryd" src="https://user-images.githubusercontent.com/307161/45568666-153c5e00-b812-11e8-896c-a813775cd966.png">

### What operating system and version are you using?

**Controller Information:**

  Model Name:	Apple T2 chip
  Firmware Version:	15P6805

```
osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 10.13.6
   build = 17G2307
platform = darwin
```

### What version of osquery are you using?

Issue is present on 3.2.6 and 3.3.0

```
osqueryi --line "SELECT version from osquery_info;"
version = 3.3.0
```

### What steps did you take to reproduce the issue?

- Find a newer Mac laptop with T2 chip (System Report > Controller)
- Do not enable encryption via FileVault
- Run: 

```
osquery> select name, encrypted, encryption_status from disk_encryption;
+--------------+-----------+-------------------+
| name         | encrypted | encryption_status |
+--------------+-----------+-------------------+
| /dev/disk0   | 0         | undefined         |
| /dev/disk0s1 | 0         | undefined         |
| /dev/disk0s2 | 0         | undefined         |
| /dev/disk1   | 0         | undefined         |
| /dev/disk1s1 | 1         | encrypted         |
| /dev/disk1s2 | 0         | not encrypted     |
| /dev/disk1s3 | 0         | not encrypted     |
| /dev/disk1s4 | 1         | encrypted         |
| /dev/disk2   | 0         | undefined         |
| /dev/disk2s1 | 0         | undefined         |
+--------------+-----------+-------------------+
```

- Verify that FDE is not enabled

```
$ fdesetup status
FileVault is Off.
```

### What did you expect to see?

Encryption status = 0

### What did you see instead?

Encryption status = 1

**Comment by obelisk** [comment]
This seems like a bug resulting from our use of private functions to determine this status and that there is a new case that needs to be handled.

@mkareta Do you have an idea or plans to look into this? If not, assign it to me and I'll look at it when I have time.

**Comment by ideologysec** [comment]
Per the T2 security whitepaper, even when FileVault is disabled, the T2 chip is AES DMA encrypting and decrypting the storage on the device using the unique hardware key. The only way to access data on a non-FileVault2-enabled T2 mac is via Target Disk Mode.

I realize it's a bit philosophical; it sounds like osquery's underlying behavior should change from "is disk encryptIon enabled" to "is FileVault2 turned on" at least on macOS.

**Comment by seren** [comment]
FYI, this might be resolved by with vronin's suggestion: https://github.com/osquery/osquery/issues/3709#issuecomment-366407843

**Comment by directionless** [comment]
Fixed by 6823
