### ISSUE TITLE
SQLite DBs with Journal Mode WAL are incompatible with ATC parser

### ISSUE THREAD

**Issue by FritzX6** [osquery/osquery#5225]
# Bug report
When attempting to build ATC configuration blocks for several SQLite databases I continued to encounter `Error Code 14` at time of query. An example of the output can be seen below:

```
osquery> select * from cloud_sync_google_drive;
I0913 14:44:39.450301 2340193152 virtual_sqlite_table.cpp:97] Could not prepare database at path: "/Users/fritz/Library/Application Support/Google/Drive/user_default/sync_config.db"
W0913 14:44:39.450348 2340193152 auto_constructed_tables.cpp:37] Error Code: 14 Could not generate data: Could not prepare database
```

Some tables worked without any difficulty while others would produce this error. I was able to determine that the key difference between these tables was the **Journal Mode**. 

SQLite databases like the LSQuarantineEventsV2 (_System Download History_) which worked with the ATC parser had a Journal Mode of `Delete`. Whereas, the sync_config.db used by Google Drive to store configuration details had a Journal Mode of `WAL`.

### What operating system and version are you using?

```
 version = 10.13.6
   build = 17G65
platform = darwin
```
### What version of osquery are you using?

```
version = 3.3.0
```
### What steps did you take to reproduce the issue?
I attempted to build an osquery configuration file with an `"auto_table_construction"` block that would parse the Google Drive Sync configuration database located at:

```
Users/%/Library/Application Support/Google/Drive/user_default/sync_config.db
```

An example configuration block is here:
```
{
    "auto_table_construction" : {
        "cloud_sync_google_drive" : {
            "query" : "SELECT (SELECT data_value from data where entry_key = 'user_email') AS user_email, (SELECT data_value from data where entry_key = 'local_sync_root_path') AS local_sync_root_path",
            "path" : "/Users/%/Library/Application Support/Google/Drive/user_default/sync_config.db",
            "columns" : ["user_email", "local_sync_root_path"]
        }
    }
}
```
I then queried that table in osqueryi using the following:

```
osquery> select * from cloud_sync_google_drive;
```

### What did you expect to see?
I expected to see output in the format that I declared with my configuration block, which would have resembled something like:
```
osquery> select * from cloud_sync_google_drive;
+-----------------+----------------------------+
| username        | local_sync_root_path       |
+-----------------+----------------------------+
| fritz@kolide.co | /Users/fritz/Google Drive  |
+-----------------+----------------------------+
```
I was able to receive the expected output by making a local copy of my sync_config.db and changing the Journal Mode from `WAL` to `Delete`. Which allowed osquery to parse and prepare the DB and successfully query it.

### What did you see instead?
Instead I saw:
```
I0913 14:44:39.450301 2340193152 virtual_sqlite_table.cpp:97] Could not prepare database at path: "/Users/fritz/Library/Application Support/Google/Drive/user_default/sync_config.db"
W0913 14:44:39.450348 2340193152 auto_constructed_tables.cpp:37] Error Code: 14 Could not generate data: Could not prepare database
```

### Proposed solution
Modify the ATC function to accommodate SQLite db's with other Journal Modes (including WAL)

Determining the Journal Type of a SQLite database can be done via the terminal using the following command.

```
sqlite3 ~/Library/Application\ Support/Google/Drive/user_default/sync_config.db "PRAGMA journal_mode;" 
```

Or via a GUI (DB Browser for SQLite):
![image](https://user-images.githubusercontent.com/931724/45572842-80009000-b838-11e8-9c66-a1b6c3ea1a14.png)

**Comment by directionless** [comment]
I was curious about this so I went digging at some docs. From https://www.sqlite.org/wal.html:

 > ~It is not possible to open read-only WAL databases. The opening process must have write privileges for "-shm" wal-index shared memory file associated with the database, if that file exists, or else write access on the directory containing the database file if the "-shm" file does not exist.~ Beginning with version 3.22.0 (2018-01-22), a read-only WAL-mode database file can be opened if the -shm and -wal files already exists or those files can be created or the database is immutable.

Looks like osquery is on 3.19.3. So possible just bumping the dependency is enough here.

**Comment by FritzX6** [comment]
I've since followed up with @obelisk but posting here for posterity.

@directionless I went down that rabbit-hole of SQLite version dependency last week and came up empty-handed. Building osqueryi with the latest version of SQLite 3.25 did not solve the problem.

```
osquery> select * from cloud_sync_google_drive;
I0919 17:40:50.433495 2930557824 virtual_sqlite_table.cpp:97] Could not prepare database at path: "/Users/fritz-imac/Library/Application Support/Google/Drive/user_default/sync_config.db"
W0919 17:40:50.433514 2930557824 auto_constructed_tables.cpp:37] Error Code: 14 Could not generate data: Could not prepare database
osquery> .version
osquery 3.3.0
using SQLite 3.25.1
```

**Comment by piax93** [comment]
I opened https://github.com/osquery/osquery/pull/5633 to address this issue

**Comment by directionless** [comment]
https://github.com/osquery/osquery/pull/5633 merged
