### ISSUE TITLE
Error building external extension

### ISSUE THREAD

**Issue by javierpr71** [osquery/osquery#5240]
# Bug report

I have created an extension which includes #include <boost/asio/ssl.hpp> 
When I build on Windows all works fine but in Linux the linking process emits some errors like these:

/usr/local/osquery/bin/ld.lld: error: undefined symbol: SSL_library_init
>>> referenced by openssl_init.ipp:40 (/usr/local/osquery/include/boost/asio/ssl/detail/impl/openssl_init.ipp:40)
>>>               /home/javier/Projects/labs/osquery/osquery/build/bionic/cache/llvmcache-3184CB02F0A177C07DD314E33EC0470F90FB5EC6:(boost::asio::ssl::detail::openssl_init_base::do_init::do_init())

/usr/local/osquery/bin/ld.lld: error: undefined symbol: SSL_load_error_strings
>>> referenced by openssl_init.ipp:41 (/usr/local/osquery/include/boost/asio/ssl/detail/impl/openssl_init.ipp:41)
>>>               /home/javier/Projects/labs/osquery/osquery/build/bionic/cache/llvmcache-3184CB02F0A177C07DD314E33EC0470F90FB5EC6:(boost::asio::ssl::detail::openssl_init_base::do_init::do_init())

/usr/local/osquery/bin/ld.lld: error: undefined symbol: SSL_COMP_free_compression_methods
>>> referenced by openssl_init.ipp:84 (/usr/local/osquery/include/boost/asio/ssl/detail/impl/openssl_init.ipp:84)
>>>               /home/javier/Projects/labs/osquery/osquery/build/bionic/cache/llvmcache-3184CB02F0A177C07DD314E33EC0470F90FB5EC6:(boost::asio::ssl::detail::openssl_init_base::do_init::~do_init())

.......
### What operating system and version are you using?
+-----------------------------+-------+----------+
| version                     | build | platform |
+-----------------------------+-------+----------+
| 18.04.1 LTS (Bionic Beaver) |       | ubuntu   |
+-----------------------------+-------+----------+

### What version of osquery are you using?
3.3.0
### What steps did you take to reproduce the issue?
Create an exterbal extension with #include<boost/asio/ssl.hpp> on Ubuntu

**Comment by mike-myers-tob** [comment]
The build system, including specifically the OpenSSL and Boost dependencies, has been overhauled since this issue was opened. We believe we have fixed the behavior with Boost not specifying the OpenSSL dependency, so I'm closing this issue.

Feel free to reopen this issue if you see that it is still a problem.
