### ISSUE TITLE
Feature Request: CPU Usage Metrics

### ISSUE THREAD

**Issue by ion-storm** [osquery/osquery#5241]
### What new feature do you want?

CPU Usage metrics

### How is this new feature useful?

Query Agents for CPU Usage

### How can this be implemented?

Get-WmiObject win32_processor | select LoadPercentage  |fl

**Comment by samillee** [comment]
Just a question.
When is the 
Adding cpu_utilization query for cpu_info #5307
feature to be added to the new release?

**Comment by valayDave** [comment]
Is there a way to do this for Linux ?

**Comment by jabdr** [comment]
Afaik, the only half way reliable way on linux is to periodically scan /proc/stat, calculate the differences during every period and then return the percent.

This could probably be implemented with the pub sub framework in osquery.

**Comment by directionless** [comment]
I'm going to close this as stale. While #5307 does provide a windows implementation, I don't think there's a implementation for linux or macOS that would work
