### ISSUE TITLE
audit-allow-* flags are misleading 

### ISSUE THREAD

**Issue by h0c0b** [osquery/osquery#5275]
### What operating system and version are you using?

` version = 16.04.5 LTS (Xenial Xerus)
   build = 
platform = ubuntu
`

### What version of osquery are you using?
`version = 3.3.0
`
### What steps did you take to reproduce the issue?
Wanted to enable socket and process monitoring as well as file integrity checks. Did osqueryi --help and got the following flags: 
--audit_allow_config                     Allow the audit publisher to change auditing configuration
--audit_allow_fim_events             Allow the audit publisher to install file event monitoring rules
--audit_allow_process_events     Allow the audit publisher to install process event monitoring rules
--audit_allow_selinux_events       Allow the audit publisher to process audit events
--audit_allow_sockets                   Allow the audit publisher to install socket-related rules
--audit_allow_user_events            Allow the audit publisher to install user events-related rules
--audit_force_reconfigure              Configure the audit subsystem from scratch
--audit_force_unconfigure              Always uninstall all rules, regardless of whether they were already installed or not
--audit_persist                                Attempt to retain control of audit

### What did you expect to see?
My assumption was that if socket and process auditing requires enabling of certain flags, FIM also does require similar behavior

### What did you see instead?
It appeared that audit_allow_fim_events flag enables quite a different functionality that has no relation to the FIM process described [here](https://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/). That's very misleading.

**Comment by obelisk** [comment]
I agree it is confusing. If I recall there are events and guarantees you get from the audit versions of FIM vs the inode version and they were developed basically independently. The inode one is what most people need because it has the smallest system impact.

We should clarify this though, you're right it can be misleading.

**Comment by h0c0b** [comment]
@obelisk Thank you for acknowledging this situation as an issue! In my particular case enabling both version has led to tremendous CPU consumption, lags, log overflows and actually absence of any FIM information in the DB. Looks like enabling both mechanisms breaks event subscribers functionality.

**Comment by Smjert** [comment]
Closing this issue since the page on readthedocs has been improved since then and mentions Audit, inotify etc.
