### ISSUE TITLE
Cannot install when skipping tests

### ISSUE THREAD

**Issue by iBigQ** [osquery/osquery#5280]
# Bug report

### What operating system and version are you using?

Linux

### What version of osquery are you using?

Latest master

### What steps did you take to reproduce the issue?

SKIP_TESTS=True make && sudo make install

### What did you expect to see?

Install osquery without building tests

### What did you see instead?

Errors on ```make install```:

```
-- Build files have been written to: /path/to/osquery/build/sylvia
Install the project...
-- Install configuration: "RELEASE"
CMake Error at third-party/googletest/googlemock/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/path/to/osquery/build/sylvia/third-party/googletest/googlemock/libgmock.a".
Call Stack (most recent call first):
  third-party/googletest/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)
```

The install within googletest seems to be triggered although building osquery with ```SKIP_TESTS```.  However, this lib has not been build at all in that case?

**Comment by directionless** [comment]
The build system has been reworked, as have third-party dependancies. I'm going to close this.
