### ISSUE TITLE
select query fails on prometheus_metrics 

### ISSUE THREAD

**Issue by adv16** [osquery/osquery#5286]
# Bug report

### What operating system and version are you using?

MacOS High Sierra 10.13.6

### What version of osquery are you using?

3.3.0

### What steps did you take to reproduce the issue?

Run the command - 
select * from prometheus_metrics;

### What did you expect to see?

Data from the prometheus_metrics table

### What did you see instead?

W1108 17:04:31.143815 2921268096 prometheus_metrics.cpp:91] Configuration for prometheus_targets is missing field: urls

**Comment by orlovds** [comment]
This bug is still present, osqueryd version 5.13.1 on linux.

**Comment by orlovds** [comment]
Where should this url be specified???

**Comment by Smjert** [comment]
Hello @orlovds, I think I might've been quick on testing this, but there's documentation here: https://osquery.readthedocs.io/en/latest/deployment/configuration/#prometheus

You can see that the table is meant to provide prometheus metrics that are exposed by somethings else, so you need to provide the url to get that data from in the osquery config.

**Comment by Smjert** [comment]
I'm going to close this, since this is a misconfiguration. Feel free to open a new bug if you think you have configured correctly but are unable to get metrics, or hit us on [Slack](https://join.slack.com/t/osquery/shared_invite/zt-1wi6cdgf7-zR2wt7FZ0ClHj6tEym6KFQ).
