### ISSUE TITLE
Build fails when OSQUERY_BUILD_SHARED=True is enabled

### ISSUE THREAD

**Issue by cwsteinbach** [osquery/osquery#5291]
# Bug report

### What operating system and version are you using?
platform = darwin
version = 10.13.5
build = 17F77

### What version of osquery are you using?
version = 3.3.1-1-g5188ce52

### What steps did you take to reproduce the issue?
Starting with a fresh checkout of the Osquery repo I ran the following commands:

```
export OSQUERY_BUILD_SHARE=True
make depsclean
make distclean
rm -rf build
make deps
make -j4
```
### What did you expect to see?
I expected the build to generate osquery shared libraries and then exit.

### What did you see instead?
The last `make` command generates the following error messages:
```
...
-- Found library /usr/lib/liblzma.dylib
-- Found library /usr/lib/libbz2.dylib
CMake Error at osquery/CMakeLists.txt:296 (target_link_libraries):
  Cannot specify link libraries for target "libosquery_shared" which is not
  built by this project.


-- Configuring incomplete, errors occurred!
See also "/Users/csteinba/Work/repos/github/osquery2/build/darwin10.13/CMakeFiles/CMakeOutput.log".
See also "/Users/csteinba/Work/repos/github/osquery2/build/darwin10.13/CMakeFiles/CMakeError.log".
make: *** [all] Error 1
```

**Comment by cwsteinbach** [comment]
This bug affects all platforms. The proximate cause are the the following lines `osquery/CMakelists.txt`:

```
# Create the dynamic libosquery.
if(DEFINED ENV{OSQUERY_BUILD_SHARED})
  add_library(a_shared SHARED main/lib.cpp ${OSQUERY_OBJECTS})
  target_link_libraries(libosquery_shared PRIVATE ${OSQUERY_LIBS})
  set_target_properties(libosquery_shared PROPERTIES COMPILE_FLAGS "${OSQUERY_LIBRARY_FLAGS}")
  set_target_properties(libosquery_shared PROPERTIES OUTPUT_NAME osquery)
endif()
```
Note that the `add_library()` call references `a_shared` when it should reference `libosquery_shared`. However, after making this change I encounter other problems.

**Comment by theopolis** [comment]
Hi, I am closing this because the build system and documentation have changed drastically. Feel free to reopen if there are still issues.
