### ISSUE TITLE
osqueryd not stopping with service when using tls

### ISSUE THREAD

**Issue by avcarrillo** [osquery/osquery#5300]
# Bug report
Stopping the osqueryd service, does not end all osqueryd tasks, when using a fleet manager like Kolide with tls. The second osqueryd.exe task does not stop when the service manager shows it as having been stopped.

Because of this issue, I am unable to restart the service without first stopping it, then using the task manager to close the orphan daemon, then start it again. 
 
Similar issue to #2851, however I can reproduce. 

During normal operations:
```bash
c:\ProgramData\osquery>sc query osqueryd

SERVICE_NAME: osqueryd
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
![image](https://user-images.githubusercontent.com/5413275/48663354-ea55cc80-ea43-11e8-9b1a-e318f38d57bc.png)

![image](https://user-images.githubusercontent.com/5413275/48663269-a44c3900-ea42-11e8-94a1-a59fc6509686.png)

After stopping the service:
```bash
c:\ProgramData\osquery>sc query osqueryd

SERVICE_NAME: osqueryd
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
![image](https://user-images.githubusercontent.com/5413275/48663340-ab277b80-ea43-11e8-98c5-e34fa5e74fbb.png)

![image](https://user-images.githubusercontent.com/5413275/48663349-c3979600-ea43-11e8-98f9-181d8c9ce45e.png)

**Note:**
This is only an issue with the service. If I run the same command the service is using from the command line, the second task closes when I exit the console

### What operating system and version are you using?

version = 10.0.16299
build = 16299
platform = windows

### What version of osquery are you using?
version = 3.3.1

Same issue with version 3.3.0

### What steps did you take to reproduce the issue?
Without tls configurations in the flag file, everything works as expected. I am able to start/stop the service and the daemon exists. When adding tls options below, the issue appears

```bash
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10
--tls_hostname=myserver:8412
--tls_server_certs=c:\ProgramData\osquery\certs\mycert.crt
```
### What did you expect to see?
Both osqueryd.exe tasks should close when the service is stopped or restarted

### What did you see instead?
One osqueryd.exe task continues to run

**Comment by packetzero** [comment]
I have also seen this on windows.

**Comment by avcarrillo** [comment]
While trying to determine the cause I found if any of the following flags are set, the issue appears
--config_refresh
--config_tls_refresh
--disable_distributed=false

**Comment by avcarrillo** [comment]
Issue persists after upgrading to OsQuery 3.3.2

**Comment by packetzero** [comment]
This is probably related to https://github.com/facebook/osquery/issues/5494 .  Essentially, buffered logger uses the database to cache results and status.  The database is sync'ed for every db write and delete!!

**Comment by packetzero** [comment]
@avcarrillo The reason the agent doesn't exit is because a thread is not exiting. Override the teardown method to make sure the forwarder thread exits.  Like the one I added to kinesis:
```
void KinesisLoggerPlugin::tearDown() {
  forwarder_->interrupt();
}
```

**Comment by avcarrillo** [comment]
@packetzero 

I'm not using the KinesisLoggerPlugin or AWS. Will this override still fix the problem?

**Comment by packetzero** [comment]
You are using tls logger, which uses buffered logger just like KinesisLoggerPlugin does.

**Comment by Smjert** [comment]
Is this still a problem with the latest version?

**Comment by avcarrillo** [comment]
I'm no longer experiencing this issue on the current release
