### ISSUE TITLE
Log a message when osqueryd service is stopped (Potential Defense Evassion Technique)

### ISSUE THREAD

**Issue by michaelhidalgo** [osquery/osquery#5313]
# Feature request

### What new feature do you want?

As per ATT&CK framework technique [https://attack.mitre.org/techniques/T1089/](https://attack.mitre.org/techniques/T1089/), threat actors tend to disable security tools. Therefore, having a way to log when the osqueryd services is stopped would be good. 

That way, blue teams can take a look when this is happening and perform further research on a given workstation.

### How is this new feature useful?

When it comes to threat hunting, the faster and earlier you find suspicious activities within a given workstation, the less impact for the organization.
It's well known that adversaries will disable security tool in order to avoid detection on the network. Therefore if we could log when osquery has stopped (I guess there are probably more than one way that could trigger this behavior, i.e manually pausing the service or an unexpected error?) it would help to potentially identify suspicious activity.

**Comment by directionless** [comment]
I think osquery emits both startup and shutdown messages, and I'd expect the init system to log things.
