### ISSUE TITLE
Query to logged_in_users table resulting in incorrect comparison on certain strings.

### ISSUE THREAD

**Issue by zvxr-tech** [osquery/osquery#5320]
# Bug report

### What operating system and version are you using?

```
 version = CentOS release 6.6 (Final)
   build =
platform = rhel    
```

### What version of osquery are you using?

```
version = 3.3.0
```

### What steps did you take to reproduce the issue?

See attached image:
![osquery_bug_screen_redacted](https://user-images.githubusercontent.com/1869940/49898131-60680c00-fe15-11e8-9285-914d7625b9e9.png)

### What did you expect to see?

Given, 

```
osquery> select * from logged_in_users where type = "user";
```
the query should match on the rows of table `logged_in_users` where `type = "user"`.

### What did you see instead?

The query matched on rows of table  `logged_in_users` where `type = "runlevel"` instead.

**Comment by srozb** [comment]
same here on Ubuntu 16.04

```
osquery> select distinct user,host,tty from logged_in_users where type = "user";
+----------+------------------+-----+
| user     | host             | tty |
+----------+------------------+-----+
| runlevel | 4.4.0-62-generic | ~   |
+----------+------------------+-----+
```
```
osquery> select * from logged_in_users;
+-----------+----------+-------+------------------+------------+--------+
| type      | user     | tty   | host             | time       | pid    |
+-----------+----------+-------+------------------+------------+--------+
| boot_time | reboot   | ~     | 4.4.0-62-generic | 1536668105 | 0      |
| runlevel  | runlevel | ~     | 4.4.0-62-generic | 1536668108 | 53     |
| login     | LOGIN    | tty1  |                  | 1536668534 | 2823   |
```
It's starting to show the correct results as soon as I execute query `select * from last;` as the first one...

**Comment by Smjert** [comment]
This is not a bug, but a quirk of sqlite.
Since the value `"user"` matches the column name, the query doesn't work as expected and single quotes should be used.

**Comment by directionless** [comment]
I've used this trick to handle column changes across versions. But it's pretty grotty :)

**Comment by Smjert** [comment]
> I've used this trick to handle column changes across versions. But it's pretty grotty :)

I should've also added that this is documented:
https://sqlite.org/lang_keywords.html
and
https://www.sqlite.org/faq.html#q24
