### ISSUE TITLE
Win Dev Setup - Post doxygen v1.8.11 install steps fail - unable to resolve ftp.stack.nl

### ISSUE THREAD

**Issue by rlefever** [osquery/osquery#5329]
doxygen v1.8.11
doxygen package files install completed. Performing other installation steps.
Attempt to get headers for http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.windows.x64.bin.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.windows.x64.bin.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved: 'ftp.stack.nl'"
Downloading doxygen 64 bit
  from 'http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.windows.x64.bin.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.windows.x64.bin.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved: 'ftp.stack.nl'"
The install of doxygen was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\doxygen\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - doxygen (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\doxygen\tools\chocolateyinstall.ps1'.
 See log for details.

I will upload Chocolatey logs if desired.

**Comment by redplait** [comment]
you can download doxygen installer here: http://www.doxygen.nl/files/doxygen-1.8.14-setup.exe
and just comment out "doxygen.1.8.11", in provision.ps1

**Comment by theopolis** [comment]
Hi, I am closing this because the build system and documentation have changed drastically. Feel free to reopen if there are still issues.
