### ISSUE TITLE
Cannot Open / Cannot Delete osquery.db

### ISSUE THREAD

**Issue by zveroboy152** [osquery/osquery#5337]
# Bug report
Cannot Open / Cannot Delete osquery.db

### What operating system and version are you using?
Windows 10 1709

### What version of osquery are you using?
3.3.1

### What steps did you take to reproduce the issue?
Installed via MSI, then ran osqueryd.
Then, trying to reinstall osquery:
Uninstalling osquery via control panel, then deleting osquery file in programdata. Cannot Delete osquery.db

### What did you expect to see?
Database opening, or uninstalling and being able to delete osquery.db

### What did you see instead?
Cannot Open / Cannot Delete osquery.db

E0107 15:03:36.724936  3660 init.cpp:627] [Ref #1629] osqueryd initialize failed: Could not initialize database

**Comment by groob** [comment]
This is an issue with osquery 3.3.0, but was fixed with 3.3.1.

**Comment by fmanco** [comment]
@groob thanks for the input. According to the bug this is `3.3.1` @zveroboy152 can you confirm? @groob do you have more details or another issue for this?

**Comment by groob** [comment]
https://github.com/facebook/osquery/pull/5229 this was the fix.

**Comment by vector-sec** [comment]
I had a similar issue downgrading from 3.3.2 to 3.2.6 and thought I fixed it by using the powershell here: https://github.com/facebook/osquery/issues/3842#issuecomment-337743344

But every time I start v3.2.6 osqueryd it just recreates the same unaccessible osquery.db

**Comment by clong** [comment]
I believe the permissions are set this way on purpose so that only SYSTEM can delete it. Here's what works for me:

1. Right click on osquery.db > Properties
2. Click the security tab
3. Click "Advanced"
4. Click the "change" link to change ownership
5. Type your username into the box 
6. Check the "Replace owner on subcontainers and objects" box
7. Click OK

You should be able to delete the folder now.

**Comment by Smjert** [comment]
This doesn't seem to be an issue anymore, the osquery installation has been moved to `Program Files` and the Administrators group has access to the folder, so when deleting it asks for admin access and if you're with an Administrator user you can delete it, no change of permissions needed.
