### ISSUE TITLE
Processes schema description (cpu_type, cpu_subtype) is incorrect

### ISSUE THREAD

**Issue by init99** [osquery/osquery#5404]
The description for cpu_type and cpu_subtype in the processes table schema https://github.com/facebook/osquery/blob/master/specs/processes.table#L43 is incorrect, and I'm not 100% sure how it should read.

**Comment by woodruffw** [comment]
Yeah, those descriptions are definitely incorrect. `cpu_type` and `cpu_subtype` come from `proc_pidinfo` and presumably correspond to the executing processes' Mach-O CPU type and subtype (e.g. `CPU_TYPE_X86_64` and `CPU_SUBTYPE_X86_64_ALL`).

**Comment by directionless** [comment]
Fixed in #6596
