### ISSUE TITLE
Possible bug in events_optimize can cause events to stop logging

### ISSUE THREAD

**Issue by clong** [osquery/osquery#5420]
# Bug report

## Overview

It appears that it's possible for the database to permanently remain in a partially migrated state where some of the records are correctly updated from `audit` -> `auditeventpublisher`, but not 100% of them. This leaves the database in an unusable state for events and causes the same problems outlined in #4615 . A simple fix for this would be allowing users to manually re-force a database migration job to run. Presumably when the migration tool runs, it assumes if it had previously run that the migration was successful, but that may not always be the case. 

More info here: https://osquery.slack.com/archives/C08V7KTJB/p1549400625412800

```
OS Versions: Centos 6 and 7
Osquery Version: osquery v3.3.2
```

### What steps did you take to reproduce the issue?
The same steps outlined here: https://github.com/facebook/osquery/issues/4615

Additionally, I used the RocksDB's `sst_dump` tool to check for the presence of records with `audit` instead of `auditeventpublisher` and only discovered them on hosts where process_events were not properly working, leading me to believe the migration must not have finished

```
for sst in /var/osquery/osquery.db/*.sst; 
  do ./sst_dump --file="$sst" --command=scan | grep process_events | grep -v auditeventpublisher; 
done
```

### What did you expect to see?
Zero `data.audit` and `records.audit` events. There should only be `data.auditeventpublisher` and `records.auditeventpublisher` events in the database post-migration.

### What did you see instead?
Dozens of `'data.audit.process_events` on hosts where the process_events table was malfunctioning

**Comment by fmanco** [comment]
This indeed looks like the migration did not finish, but the weird part is that writing the new version on the DB is the last step of the process, so if the migration was interrupted for some reason the new version should not have been written to the DB and therefore the migration should have run again once oqsueryd restarts.

**Comment by clong** [comment]
I tried re-migrating by setting the `results_version` key to zero using ldb:
```
./ldb --db=/var/osquery/osquery.db put results_version 0
```

This reran the migration:
```
# osqueryd --flagfile=/etc/osquery/osquery.flags --verbose
I0206 18:33:51.651440  9256 init.cpp:416] osquery initialized [version=3.3.2]
I0206 18:33:51.671424  9256 system.cpp:370] Found stale process for osqueryd (11983)
I0206 18:33:51.671486  9256 system.cpp:402] Writing osqueryd pid (9256) to /var/run/osqueryd.pidfile
I0206 18:33:51.671730  9256 extensions.cpp:343] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0206 18:33:51.672466  9257 watcher.cpp:583] osqueryd watcher (9256) executing worker (9258)
I0206 18:33:51.679919  9258 init.cpp:413] osquery worker initialized [watcher=9256]
I0206 18:33:51.680178  9258 rocksdb.cpp:134] Opening RocksDB handle: /var/osquery/osquery.db
I0206 18:33:51.694066  9258 database.cpp:563] Checking database version for migration
I0206 18:33:51.694151  9258 database.cpp:587] Performing migration: 0 -> 1
I0206 18:33:51.736801  9258 database.cpp:619] Migration 0 -> 1 successfully completed!
I0206 18:33:51.736855  9258 database.cpp:587] Performing migration: 1 -> 2
I0206 18:33:51.842855  9258 database.cpp:619] Migration 1 -> 2 successfully completed!
```

LDB shows zero entries with `\.audit\.` keys:
```
./ldb --db=/var/osquery/osquery.db --column_family=queries scan | grep '\.audit\.' | wc -l
0
```

However `sst_dump` shows hundreds. I'm not sure if that matters or how to proceed at this point, but process_events are still not working on this host.

```
# for sst in /var/osquery/osquery.db/*.sst; 
  do echo "$sst: "; ./sst_dump --file="$sst" --command=scan | grep -E 'data\.audit\.process_events|records\.audit\.process_events' | wc -l ;  
done
/var/osquery/osquery.db/1110891.sst:
2
/var/osquery/osquery.db/1141525.sst:
635
/var/osquery/osquery.db/1141530.sst:
0
/var/osquery/osquery.db/1141531.sst:
0
/var/osquery/osquery.db/1141537.sst:
0
/var/osquery/osquery.db/1141538.sst:
0
/var/osquery/osquery.db/1141547.sst:
0
/var/osquery/osquery.db/1141548.sst:
0
/var/osquery/osquery.db/1141557.sst:
0
/var/osquery/osquery.db/1141558.sst:
0
/var/osquery/osquery.db/1141559.sst:
0
/var/osquery/osquery.db/984958.sst:
633
```

**Comment by clong** [comment]
DBs have been provided to @fmanco for additional debugging

**Comment by clong** [comment]
Any luck here? I'm trying to learn the basics of RocksDB, but I don't fully understand why these entries appear in the SST files but I can't seem to find them when scanning the DB with LDB. Maybe someone from the RocksDB team on FB would be able to help provide insight?

**Comment by fmanco** [comment]
@clong I still didn't manage to get anywhere with this...

**Comment by clong** [comment]
I spent a few more hours trying to isolate the bug yesterday and tried the following:
* Looking at DBs on broken vs. working hosts. Some of the hosts that are broken don't actually have any `audit` events in their SSTs, so that may be a red herring. However, NONE of the working hosts I looked at have any `audit` events in them.
* I tried using LDB's `repair` functionality and restarting osquery to no avail
* Swapping out the DB for a new one fixes the problem 100% of the time
* Changing the process/socket events query string (i.e. changing which fields get selected) does not help. I thought this might force some sort of database change, but no luck.

Short of adding extremely verbose logging around the osquery DB code or getting support from folks on the RocksDB team, I think the only path forward for us here will be to nuke all of our production databases and start again from scratch.

**Comment by fmanco** [comment]
I think I've tracked this down to the `events_optimize` option (which is enabled by default). I'm not sure yet what the problem is, but for the time being, as a workaround, disabling this option will make events start flowing again immediately.

**Comment by clong** [comment]
+1 for the workaround. I just deployed it to our staging environment and events started flowing from "broken" hosts immediately. 

Can we keep this issue open to eventually find what the root cause of the bug is with events_optimize?

**Comment by uptycs-nishant** [comment]
@clong, @fmanco 
>  Changing the process/socket events query string (i.e. changing which fields get selected) does not help. I thought this might force some sort of database change, but no luck.

Instead of changing the query itself change query name (e.g. process_events -> process_events2) then test with --events_optimize=true(default setting).  I believe you will start getting your results.

I dont have DB to analyze but I believe due to following condition -

optimize_eid.process_events - eid.auditeventpublisher.process_events = BIG POSITIVE NUMBER is causing events not to be logged it may be due to database not migrated or  eid.auditeventpublisher.process_events overflowed (which is unlikely since it is a 64 bit number)

Can you dump the output of ?

ldb --db=post/osquery.db/  scan --column_family=queries| grep '^eid'
ldb --db=post/osquery.db/  scan --column_family=queries| grep '^optimize'

**Comment by clong** [comment]
I'm going to close this out as upgrading from v2 -> v3 is probably a major edge case these days. Disabling events_optimize put the CPU usage of osquery through the roof, so that's not an ideal workaround. The only solution here is to recreate the database.
