### ISSUE TITLE
The unixTime field value is no longer wrapped in double quotes

### ISSUE THREAD

**Issue by clong** [osquery/osquery#5433]
# Bug report

### What operating system and version are you using?

CentOS 6 and 7 & Ubuntu

### What version of osquery are you using?
v3.3.2 

### What steps did you take to reproduce the issue?
Looked at logs from hosts running osquery v2.10.0 and compared them to hosts running v3.3.2

### What did you expect to see?
Sample JSON of 2.10.0:
```
{<snip>"unixTime":"1550011254",</snip>}
```
Notice the timestamp is wrapped in double quotes

### What did you see instead?
Sample JSON of 3.3.2:
```
{<snip>"unixTime":1550011005,</snip>}
```
The timestamp is no longer wrapped.

This is an issue because many people use regex to specify the extraction of the timestamp in tools like Logstash or Splunk. I see two possible paths forward:

1. This was an intended change or is irreversible due to the JSON library being used.
2. This was an accident and should never have changed and will be changed back in a newer version of osquery.

In the meantime, a regex specifying option characters can be used to workaround this inconsistency.

**Comment by SAlexandru** [comment]
hello, 
Thank for flagging this!
Can you please provide some more details on replicating? What table did you query or what events are you looking at?

Thanks!

**Comment by clong** [comment]
I believe this is happening with all events regardless of the table, and this is from the resulting logs being sent to syslog. These specific events were from the `osquery_info` table.

**Comment by SAlexandru** [comment]
@clong I've checked this on experimental and the output is as expected (i.e the timestamp will be printed as a string). Can you please confirm that?  
For now, I guess the workaround should suffice to fix this inconsistency and when we merge experimental this should be fixed.

**Comment by directionless** [comment]
This is pretty old, is it still current? And does it related to `--logger_numerics`

**Comment by clong** [comment]
I don't think this is an issue anymore￼

**Comment by directionless** [comment]
Great. I'll close this. We can always reopen
