### ISSUE TITLE
file_events join users?

### ISSUE THREAD

**Issue by juju4** [osquery/osquery#5463]
# Bug report

### What operating system and version are you using?

```
# osqueryi --line "SELECT version, build, platform FROM os_version;"
I0223 14:20:32.612037 11981 database.cpp:563] Checking database version for migration
I0223 14:20:32.612126 11981 database.cpp:587] Performing migration: 0 -> 1
I0223 14:20:32.612154 11981 database.cpp:619] Migration 0 -> 1 successfully completed!
I0223 14:20:32.612175 11981 database.cpp:587] Performing migration: 1 -> 2
I0223 14:20:32.612200 11981 database.cpp:619] Migration 1 -> 2 successfully completed!
I0223 14:20:32.663285 11981 events.cpp:745] Subscriber expiration is too low: hardware_events
 version = 16.04.6 LTS (Xenial Xerus)
   build = 
platform = ubuntu
```
Also tested on centos7

### What version of osquery are you using?

```
# osqueryi --line "SELECT version from osquery_info;"
version = 3.3.2
```

### What steps did you take to reproduce the issue?

configure osquery with fim enabled (inotify-based, not auditd) and query `select file_events.* from users join file_events using (uid);`

### What did you expect to see?

fim log with full username.
Maybe a join constraint on events table

### What did you see instead?

usual fim log with just uid/gid

**Comment by Smjert** [comment]
@juju4 a bit late of an answer, but this isn't a bug, the query you used only selects columns that comes from the `file_events` table, which will not include the ones from `users`, like `username`.
You need to select all columns `*`, or if in addition to the `file_events` columns you are only interested in the username, then the select part can be `file_events.*, username`.
