### ISSUE TITLE
'shadow' table incorrectly shows empty password 

### ISSUE THREAD

**Issue by shashial** [osquery/osquery#5465]
# Bug report

### What operating system and version are you using?

 version = 18.04.2 LTS (Bionic Beaver)
   build = 
platform = ubuntu

### What version of osquery are you using?

version = 3.3.2

### What steps did you take to reproduce the issue?

so here we have `!` for password 
`root@test:~# cat /etc/passwd | grep root`
`root:x:0:0:root:/root:/bin/bash`
`root@test:~# cat /etc/shadow | grep root`
`root:!:17945:0:99999:7:::`

delete the password
`root@test:~# passwd -d root`
`passwd: password expiry information changed.`

and it's empty now
`root@test:~# cat /etc/passwd | grep root`
`root:x:0:0:root:/root:/bin/bash`
`root@test:~# cat /etc/shadow | grep root`
`root::17945:0:99999:7:::`

### What did you expect to see?

`select * from shadow where username='root';`
+-----------------+----------+-------------+-----+-------+---------+----------+--------+------+----------+
| password_status | hash_alg | last_change | min | max   | warning | inactive | expire | flag | username |
+-----------------+----------+-------------+-----+-------+---------+----------+--------+------+----------+
| **empty**          |          | 17945       | 0   | 99999 | 7       | -1       | -1     |      | root     |
+-----------------+----------+-------------+-----+-------+---------+----------+--------+------+----------+

### What did you see instead?
`select * from shadow where username='root';`
+-----------------+----------+-------------+-----+-------+---------+----------+--------+------+----------+
| password_status | hash_alg | last_change | min | max   | warning | inactive | expire | flag | username |
+-----------------+----------+-------------+-----+-------+---------+----------+--------+------+----------+
| **active**          |          | 17945       | 0   | 99999 | 7       | -1       | -1     |      | root     |
+-----------------+----------+-------------+-----+-------+---------+----------+--------+------+----------+

https://github.com/facebook/osquery/blob/c7355b19aa49494a5bfba6f3cce37ab14a8a6570/osquery/tables/system/linux/shadow.cpp#L50

**Comment by guliashvili** [comment]
Thanks for reporting the issue.
How exactly do you start osquery?

**Comment by shashial** [comment]
`sudo osqueryi`
