### ISSUE TITLE
Killing spec files

### ISSUE THREAD

**Issue by fmanco** [osquery/osquery#5502]
# Blueprint

So far we have been using Jinja2 based code generation to generate the code for each of the table's classes. This classes contain the table schema and a `generate()` method which proxies a call to a static generation function defined in the spec. Event tables have some additional code to subscribe and handle events. This is a proposal to remove code generation completely.

## Why

One of the goals of the new ev2 framework is to be able to create smart tables, namely tables that correlate data from different event sources, or that use different generation mechanisms depending on the runtime configuration of osquery. The current code generation mechanism assumes all tables are equal with just a couple of types and therefore makes implementing smart tables much harder.

There are a few other downsides to the current implementation:

* It is impossible to set proper dependencies for each table.
  * Having proper dependencies would allow to make the build much more configurable in an easy way.
* Requires data generation functions to be static.
  * All data these generation functions need to keep between invocations (e.g. for caching) will need to be static as well.
* Does not expose table metadata to the application.
  * Wouldn't it be nice to be able to read a table description directly from `osqueryi`?
* It requires python and a couple of third-party libraries.

## Removing specs

There are a few things specs provide we will need to replace:

1. Table metadata. This includes table and column descriptions and usage examples.

To address this point I'll extend the `TablePlugin` class to contain table metadata. This data will then be available to be queried in runtime.

2. Automatic generation of native and foreign tables amalgamations.

Table amalgamations are evil, they prevent us from having proper per-table dependencies and easily configuring the build. They also don't offer any advantage and therefore I'll remove amalgamations.

* Native amalgamation

This is just a concatenation of all code for native tables. No special handling is needed to replace them, just include the individual table code in the build.

* Foreign amalgamation

The foreign amalgamation exposes a `registerForeignTables()` function which, in runtime, will decide whether to register foreign tables. The intent of this feature is to provide osquery with table schemas for all platforms, however this is hard to implement due to extended schemas which make tables different across platform and makes this feature partially broken. It is also not widely used, so I will remove it.

3. Generation of the schema.

Since we'll have all the metadata in osquery I'll add a `--schema` option which will generate the schema similar to our current script.

4. Per-platform implementation of generation method and extended schemas.

Each table will have a common implementation (where the schema is defined for instance) and a per-platform implementation (if necessary). The generate function will go into the per-platform implementation file and the right file will be compiled for each platform. Schemas might go either in the common part or per-platform will decide later, but the idea is the same. Finally if an implementation needs per-platform specific members we can use a mechanism like [Pimpl](https://en.cppreference.com/w/cpp/language/pimpl).

## Execution plan

1. Extend `TablePlugin` to support table metadata
2. Update the code generation script to include table metadata and per-platform implementation files when necessary (these will still call static functions to generate data)
4. Generate all code once update BUCK files and commit
5. Long term start moving generation functions to the class implementation

**Comment by theopolis** [comment]
Yes, this is amazing!

**Comment by packetzero** [comment]
Would be a great time to :
-Register class instances rather than functions.
-Add new generate() support to report one row at a time. Will allow us to get progress feedback to use to avoid watchdog kill (can add sleeps to throttle as needed). As well as avoid storing all rows at once before passing to sqlite3.

**Comment by directionless** [comment]
While this would be amazing, I doubt anyone is working on it
