### ISSUE TITLE
fix queries and docs for tightened constraints

### ISSUE THREAD

**Issue by packetzero** [osquery/osquery#5503]
# Bug report

#5422 adds tighter constraints.  This issue is to update packs and docs.  This will mean users will likely need to make changes to their queries.  We need  good documentation explaining this.

### What operating system and version are you using?

All

### What version of osquery are you using?

experimental or any custom build containing PR5422

### What steps did you take to reproduce the issue?

Run agent.

### What did you expect to see?

same query behavior as before

### What did you see instead?

some queries are failing with 'constraint failed' message.

Things to look for:
- you may need to fix ordering and qualifiers on JOIN to be LEFT JOIN
- no more using multiple LIKE constraints on a required column, only multiple Equals or IN().  So you have to get creative with IN(select like or like)

**Example 1: packs/hardware-monitoring.conf**
This will fail, and needs **LEFT JOIN** on hash.
```
select file.path, uid, gid, mode, 0 as atime, mtime, ctime, md5, sha1, sha256 
from (select * from file where path like '/System/Library/CoreServices/%.efi' union select * from file where path like '/System/Library/LaunchDaemons/com.apple%efi%') file
join hash using (path);
```

**Example 2: packs/osx-attacks.conf**
This will fail since an INDEX has multiple LIKE constraints.
```
select * from file where
       path LIKE '/Users/%/Library/.kernel_%' OR
       path LIKE '/Users/%/Library/kernel_service';
```
Workaround:
```
SELECT * FROM file
WHERE path IN (
       SELECT path FROM file WHERE path LIKE '/Users/%/Library/iMovie/%'
       UNION
       SELECT path FROM file WHERE path LIKE '/Users/%/Library/kernel_service'
)
```

**Comment by guliashvili** [comment]
Hi,

I try to replicate problem on my machine.

I do 
```
select file.path, uid, gid, mode, 0 as atime, mtime, ctime, md5, sha1, sha256 
from (select * from file where path like '/System/Library/CoreServices/%.efi' union select * from file where path like '/System/Library/LaunchDaemons/com.apple%efi%') file
join hash using (path);
```

But I get some data. What am I doing wrong?

**Comment by packetzero** [comment]
I am using #5422 backported to 3.3.1 , and I think there's a different sqlite version in experimental.  Perhaps the newer sqlite is smarter at joins?

**Comment by directionless** [comment]
Testing, I can't replicate this on the current head. I'm using
```
select path from file where
  path like '/Users/%/Library/Google/%.plist' OR 
  path LIKE '/Users/%/Library/Google/%/%.plist';
```

But, I'd love to get tests for this

**Comment by verntx** [comment]
#5422 is reworked by #6038. I back-ported the xBestIndex logic from #6038 to our 3.3.1 fork. The example queries noted in this ticket no longer fail.
