### ISSUE TITLE
Does it support UNIX? such as HP-UX or AIX

### ISSUE THREAD

**Issue by j4ckzh0u** [osquery/osquery#5507]
# Question
I have some unix machine ， such as HP-UX or AIX.
I want to install osquery on my unix system .
I don't find the packages of release for unix.
so, i wait to know if it support unix.

**Comment by directionless** [comment]
osquery does not build or distributed packages on those platforms.

It may compile, and we would probably accept patches that added support for those. (If they were clean, and in keeping with the general code standards)
