### ISSUE TITLE
Disabling the "processes" table prevents osqueryd from starting

### ISSUE THREAD

**Issue by isg-sysadmin** [osquery/osquery#5512]
# Bug report

### What operating system and version are you using?

```
version = 16.04.6 LTS (Xenial Xerus)
   build = 
platform = ubuntu
```

### What version of osquery are you using?

`version = 3.3.2`

### What steps did you take to reproduce the issue?

Include `--disable_tables=processes` in `/etc/osquery/osquery.flags` then stop `osqueryd` and start it from cold.

### What did you expect to see?

Normal `osqueryd` startup.

### What did you see instead?

`osqueryd` starts then dies:

```
Mar 13 09:34:28 test osqueryd: osqueryd started [version=3.3.2]
Mar 13 09:34:28 test osqueryd[621]: E0313 09:34:28.511849   621 init.cpp:457] osqueryd initialize failed: Error querying processes: no such table: processes
Mar 13 09:34:28 test systemd[1]: osqueryd.service: Main process exited, code=exited, status=1/FAILURE
```

We'd like to be able to disable the `processes` table without having it break `osqueryd`.

**Comment by mike-myers-tob** [comment]
I tested osqueryd 4.0.2 on Ubuntu 16.04 and reproduced this issue with the following steps.

```bash
mmyers@ubuntu:~$ cat /etc/osquery/osquery.flags
--disable_tables=processes

mmyers@ubuntu:~$ cat /etc/osquery/osquery.conf
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10
  },
  "schedule": {
    "get_three_processes": {
      "query": "SELECT pid,name FROM processes limit 3;",
      "interval": 10
    }
  }
}

mmyers@ubuntu:~$ sudo osqueryctl status
● osqueryd.service - The osquery Daemon
   Loaded: loaded (/usr/lib/systemd/system/osqueryd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

mmyers@ubuntu:~$ sudo osqueryctl start

mmyers@ubuntu:~$ sudo osqueryctl status
● osqueryd.service - The osquery Daemon
   Loaded: loaded (/usr/lib/systemd/system/osqueryd.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Fri 2019-09-20 13:29:45 PDT; 24s ago
  Process: 4043 ExecStart=/usr/bin/osqueryd --flagfile $FLAG_FILE --config_path $CONFIG_FILE (code=exited, status=1/FAILURE)
  Process: 4041 ExecStartPre=/bin/sh -c if [ -f $LOCAL_PIDFILE ]; then mv $LOCAL_PIDFILE $PIDFILE; fi (code=exited, status=0/SUCCESS)
  Process: 4039 ExecStartPre=/bin/sh -c if [ ! -f $FLAG_FILE ]; then touch $FLAG_FILE; fi (code=exited, status=0/SUCCESS)
 Main PID: 4043 (code=exited, status=1/FAILURE)

Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Unit entered failed state.
Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Failed with result 'exit-code'.
Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Service hold-off time over, scheduling restart.
Sep 20 13:29:45 ubuntu systemd[1]: Stopped The osquery Daemon.
Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Start request repeated too quickly.
Sep 20 13:29:45 ubuntu systemd[1]: Failed to start The osquery Daemon.
Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Unit entered failed state.
Sep 20 13:29:45 ubuntu systemd[1]: osqueryd.service: Failed with result 'start-limit-hit'.
```

If you use the flag file to disable another table, _e.g._ `time`, it doesn't cause `osqueryd` to abort.

Also, interestingly, if you set the `disables_table` option from within the conf file, things work as they should.

**Comment by alessandrogario** [comment]
The watchdog makes use of the `processes` table to determine process state:
``` cpp
QueryData WatcherRunner::getProcessRow(pid_t pid) const {
  // On Windows, pid_t = DWORD, which is unsigned. However invalidity
  // of processes is denoted by a pid_t of -1. We check for this
  // by comparing the max value of DWORD, or ULONG_MAX, and then casting
  // our query back to an int value, as ULONG_MAX causes boost exceptions
  // as it's out of the range of an int.
  int p = pid;
#ifdef WIN32
  p = (pid == ULONG_MAX) ? -1 : pid;
#endif
  return SQL::selectFrom(
      {"parent", "user_time", "system_time", "resident_size"},
      "processes",
      "pid",
      EQUALS,
      INTEGER(p));
}
```

Link: https://github.com/osquery/osquery/blob/c7355b19aa49494a5bfba6f3cce37ab14a8a6570/osquery/core/watcher.cpp#L467

**Comment by theopolis** [comment]
Should we add a whitelist to prevent some tables from being disabled?

Using tables within osquery core code does happen, as some tables are nice OS agnostic abstractions around common data.

**Comment by packetzero** [comment]
I would prefer that we start to formalize a platform API that is used instead of tables. At the high level it’s a wrapper around functions that are already in place. Preferably without Row passing.  As we saw here, calling tables from core or other tables is always a bit of a surprise.

**Comment by theopolis** [comment]
I support deprecating the internal use of the table abstraction. If we refactor table generation code into classes (an API) it would make this fairly easy to migrate.

**Comment by directionless** [comment]
I am not sure this issue needs to stay open. Today, osquery uses various tables for internal purposes. If someone is motivated to open an blueprint for how that might change, we can talk about it. But I don't think it's going to change without an excited volunteer.
