### ISSUE TITLE
Implement "--enable_tables_only" feature in addition to "--disable_tables"

### ISSUE THREAD

**Issue by fincham** [osquery/osquery#5513]
# Feature request

### What new feature do you want?

Currently `osqueryd` implements a `--disable_tables` option. This is a bit of a footgun if you only want a specific subset of tables explicitly enabled, as it means for every new release the user has to check for any new tables and add them to the `disable_tables` list.

Ideally an option similar to OpenSSH's `restrict` feature that disables all current and new tables that are not explicitly permitted would be great.

As osquery has grown tables like `curl_http` and so on, the ability to make sure new (and potentially security sensitive) tables are disabled-by-default in some installs would make a big difference to osquery's security.

### How is this new feature useful?

Prevents accidental security exposure when new tables are added that may be undesirable. Saves having to maintain a giant disable list in `osquery.flags`.

### How can this be implemented?

Extending the existing `--disable_tables` code shouldn't be too difficult.

**Comment by directionless** [comment]
Fixed in #6150
