### ISSUE TITLE
osquery json data format error when including Chinese character.

### ISSUE THREAD

**Issue by zubryan** [osquery/osquery#5533]
# Bug report
osquery json data format error when including Chinese character.
Is there a solution to it?

### What operating system and version are you using?
```
[
  {"build":"7601","platform":"windows","version":"6.1.7601"}
]
```

### What version of osquery are you using?
```
osqueryd.exe: {"version":"3.3.1"}
```

### What steps did you take to reproduce the issue?
```
select * from processes;
```

### What did you see?
![windows_bug](https://user-images.githubusercontent.com/129747/54470123-9da9b480-47dd-11e9-9bbb-c9e446ef45b2.jpg)

**Comment by directionless** [comment]
Slack discussion thinks this is related to #5288

**Comment by zubryan** [comment]
Seems like it's related to #520. Probably it's a bug from boost.

**Comment by zubryan** [comment]
@directionless where is the Slack channel?

**Comment by directionless** [comment]
@zubryan See https://osquery.io/

There's also a nascent stackoverflow tag https://stackoverflow.com/questions/tagged/osquery

**Comment by zubryan** [comment]
Cool, thanks a lot.

**Comment by directionless** [comment]
I think this got fixed with some work on the utf8 support a bit ago. Please holler if there is still an issue
