### ISSUE TITLE
Visual Stuido 2017 Community install fails from  make-win64-dev-env.bat

### ISSUE THREAD

**Issue by sofakingdead** [osquery/osquery#5534]
# Bug report

### What operating system and version are you using?
Windows 10 64 bit

### What version of osquery are you using?
3.3.3
<!--
You can run the line bellow. Paste the result within a code block.
Error is before OSQuery install during build phase for packaging

### What steps did you take to reproduce the issue?
Tried on another PC running  make-win64-dev-env.bat
### What did you expect to see?
Chocolatey package for Visual Studio 2017 community to succeed in make-win64-dev-env.bat
### What did you see instead?
Package install failed exit code 1

Suspect this is due to the exceed timeout not being long enough. I can install the package from chocolatey on it's own but it is quite slow.

**Comment by muffins** [comment]
Can you be more specific about what's breaking? running `tools/make-win64-dev-env.bat` on experimental is broken and you'll need to reference the `BUILD.md` on the experimental branch for instructions on building, however running it with `3.3.3` checked out _should_ still work alright.

**Comment by theopolis** [comment]
I am closing this because the build system and documentation have changed drastically.
