### ISSUE TITLE
docs/wiki/development/building.md needs to be updated to reflect instructions at ./osquery/BUILD.md 

### ISSUE THREAD

**Issue by ssikdar1** [osquery/osquery#5549]
# Bug report

Was following the instructions to build osquery found here:

https://osquery.readthedocs.io/en/latest/development/building/

```
$ git clone https://github.com/facebook/osquery.git
$ cd osquery
$ # ./tools/provision/darwin.sh # installs Xcode-Tools
$ make deps
$ make
```

running `make deps` gives this error:
```
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Looking here:

https://github.com/facebook/osquery/blob/c7355b19aa49494a5bfba6f3cce37ab14a8a6570/tools/provision.sh#L295

looks like it is trying to install requirements.txt after pip but looking in the pulled git repo:

```
$ find . -name requirements.txt
$ 
```

File seems to be missing or the line in the script should be removed?

### What operating system and version are you using?

MacOS Mojave 
Version 10.14  

### What version of osquery are you using?
N/A? since this is in the building stage?

**Comment by Cvetomird91** [comment]
I recently started getting into the project as yourself. I got support from http://osquery.slack.com . The project is now being built with Buck Build. Can you please refer to BUILD.md?

**Comment by ssikdar1** [comment]
@Cvetomird91 Looks like buck build instructions are working!

I guess the docs here need to be updated then: https://github.com/facebook/osquery/blob/experimental/docs/wiki/development/building.md

I can change the title of the bug. 

If I have time, I'll try can try and get a PR in.

**Comment by Smjert** [comment]
Closing since the build system is back to CMake and the building page is updated: https://osquery.readthedocs.io/en/latest/development/building/
