### ISSUE TITLE
osqueryd: E0510 15:42:25.561630 18290 pci_devices.cpp:264] Unexpected error attempting to read pci.ids at path: /usr/share/misc/pci.ids

### ISSUE THREAD

**Issue by juju4** [osquery/osquery#5569]
# Bug report

every hour, osquery report above error.

Matching code is
https://github.com/facebook/osquery/blob/c7355b19aa49494a5bfba6f3cce37ab14a8a6570/osquery/tables/system/linux/pci_devices.cpp#L36

it seems this file path only exists on Debian/Ubuntu
https://packages.debian.org/search?searchon=contents&keywords=pci.ids

https://centos.pkgs.org/7/centos-x86_64/hwdata-0.252-9.1.el7.x86_64.rpm.html
Confirmed on Fedora release 29 (Twenty Nine)
```
$ find /usr/ -iname pci.ids 2>/dev/null
/usr/share/hwdata/pci.ids
```

Workarounds
- downgrade to 3.2.6-1
- copy/symlink above file
- touch file (maybe side impact)

### What operating system and version are you using?

```
CentOS Linux release 7.6.1810 (Core)
```

### What version of osquery are you using?

osquery-3.3.2-1.linux.x86_64

### What did you expect to see?

No error. Not happening with osquery-3.2.6-1.linux.x86_64

### What did you see instead?

Above error.

**Comment by Smjert** [comment]
This has been fixed in PR https://github.com/osquery/osquery/pull/6297, closing.
