### ISSUE TITLE
Add package installed date time to rpm_packages table

### ISSUE THREAD

**Issue by RamrajSekar** [osquery/osquery#5570]
# Feature request

### What new feature do you want?

Kindly add a column to display the installation date/time of each rpm package.

### How is this new feature useful?

It'll be helpful for reporting or identifying the issue with latest package installed

### How can this be implemented?

The "rpm -qa --last" command shows the date/time of the each package installation from which you can fetch the date and add it to the table.

**Comment by directionless** [comment]
Fixed in #6113
