### ISSUE TITLE
Allow Docs in EPUB and PDF

### ISSUE THREAD

**Issue by tmnc** [osquery/osquery#5573]
# Feature request

### What new feature do you want?
Allow the docs at readthedocs to be converted and downloaded as EPUB and PDF.  Other docs on that site allow saving as PDF or EPUB (or even HTML).

### How is this new feature useful?

If necessary, this allows one to save the documentation offline, to an e-reader. For example, have done this with GRR, saved as EPUB, then used Calibre to reconvert to allow use with Play books, etc.

### How can this be implemented?
I believe this can be done with tagging and a workflow during the build.

**Comment by directionless** [comment]
I don't see an easy way to do this. readthedocs only supports downloads for Sphinx based projects, while we use mkdocs.
