### ISSUE TITLE
osquey crashed caused by a copy constructor

### ISSUE THREAD

**Issue by xujw89** [osquery/osquery#5578]
# Bug report

program crash

### What operating system and version are you using?

win10 x64

compile in vs2017 for a win32 version osquery

### What version of osquery are you using?

3.3.2
The latest version has changed the code, but I didn't try.

### What steps did you take to reproduce the issue?

After compile, Run the osqueryd, then it crashed. The problem caused by a copy constructor

![image](https://user-images.githubusercontent.com/11781413/58949739-b6fc4480-87bf-11e9-9d21-3e42314d799b.png)
![image](https://user-images.githubusercontent.com/11781413/58949847-02165780-87c0-11e9-80ca-1199a3a1ec17.png)

![image](https://user-images.githubusercontent.com/11781413/58949902-207c5300-87c0-11e9-87de-535c59aa459a.png)

The alternate change may like a deep constructor：
![image](https://user-images.githubusercontent.com/11781413/58949961-40137b80-87c0-11e9-80d5-6dce7e1c2632.png)

### What did you see instead?

wish helpful, thanks for your works

**Comment by Smjert** [comment]
This issue has been solved in commit https://github.com/osquery/osquery/commit/6ade85a5f32a036b4c79fda7919d9979d9554210.
