### ISSUE TITLE
make-win64-binaries.bat and make_windows_package.ps1 scripts not working

### ISSUE THREAD

**Issue by agentsofshield** [osquery/osquery#5586]
### What operating system and version are you using?
I cloned the repo of v3.3.3 using git and ran the scripts - `make-win64-env-dev.bat` and `make-win64-binaries.bat` on win10 VM and win7

```+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.17763 | 17763 | windows  |
+------------+-------+----------+

+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 6.1.7601 | 7601 | windows  |
+------------+-------+----------+
```
### What version of osquery are you using?
v3.3.3

### What steps did you take to reproduce the issue?
Running `make-win64-dev-env.bat` returned a few errors about the doxygen, nuget and PSScriptAnalyzer which stopped showing after a few times running the script and running it under a VS Dev command prompt.
Afterwards I tried to run the `make-win64-binaries.bat` which resulted in 2 different errors depending on if the script was run under CMD or VS Dev command prompt.
Also after seeing that the script cant find the vs build tools I installed them manually through chocolatey and tried again.

### What did you expect to see?
I expected to see the script running smoothly, creating the binaries allowing me to create a custom MSI.

### What did you see instead?
Running under CMD:
```
CMake Error: The source directory "C:/Users/Administrator/Desktop/osquery" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: osquery.sln

[-] osquery build failed.
```

Running under VS Dev command prompt:
```
[-] Failed to find vs build tools. Re-run tools\make-win64-dev-env.bat
```
After running make_windows_package.ps1:
` [-] Did not find Release binaries, check build script output.`

**Comment by Smjert** [comment]
These scripts were needed for the old master (pre experimental merge), to setup the environment and retrieve some of the dependencies needed to build.

The process right now changed and it's tracked in the BUILD.md; also the majority of dependencies are downloaded by CMake or Buck, so there's not much left to install.

All in all I think we could eventually provide some "one click" scripts to install what's not automatically installed already, but, if I may, I'm not sure this is worth to wait for and delay the 4.0.0 release?

**Comment by Smjert** [comment]
I would say that basically any script present, beyond the ones that we either use in the CI or that has been somewhat updated (like the one to make MSI packages) is deprecated, too much has changed since the old master.

**Comment by muffins** [comment]
I think for this issue we might be able to close this out. The best instructions for building osquery are currently in the [building guide](https://osquery.readthedocs.io/en/latest/development/building/) which is pretty solid. As for packaging up binaries for distribution, the [make_windows_package.ps1](https://github.com/osquery/osquery/blob/master/tools/deployment/make_windows_package.ps1) script has been pretty solid for me over the last two releases we just did, so I'd recommend sticking to those. Do we have any other reason to leave this open? I'm going to close out, but I'd say feel free to re-open if folks think there's other items we should use this issue to track, otherwise lets cut new issues to track additional work.
