### ISSUE TITLE
Add support for continuous builds/releases

### ISSUE THREAD

**Issue by groob** [osquery/osquery#5589]
I would like to propose that we add continuous builds to osquery. 
My ideal user experience would be to have a `stable`, `beta` and `nightly` release, where `beta` and `stable` are tagged on a schedule, and `nightly` is built every day. 

There's a lot of questions of what this would look like on the infra side. Are non stable releases signed?

**Comment by directionless** [comment]
If we have appropriate signing infrastructure, I'd sign the nightlies. But, that's a big if. It may require credential delegation.  Or a different key.

**Comment by mike-myers-tob** [comment]
I request we move this to the 5.1 milestone, I think we have progressed a lot towards this, but it shouldn't block 5.0. If anyone agrees they can move it to the 5.1.

**Comment by mike-myers-tob** [comment]
I'm going to stop kicking this down the road for now. As we've discussed, monthly releases is what we're going to attempt now.

**Comment by directionless** [comment]
Honestly, I think we're close to nightlies. But I don't see value in keeping this ticket.

**Comment by Smjert** [comment]
> Honestly, I think we're close to nightlies. But I don't see value in keeping this ticket.

Yeah for future readers, we have scheduled builds every 6 hours that build `unsigned` packages. Also every PR merged will get a build on the master branch too, together with again the artifacts.

Just go https://github.com/osquery/osquery/actions, the scheduled builds are currently named as the workflow, so `build_x86` and `build_aarch64`; click on their name which is a link, and in the page that opens, scroll to the bottom, and you'll see all the various artifacts.
