### ISSUE TITLE
Failing tests in osquery 4.x

### ISSUE THREAD

**Issue by alessandrogario** [osquery/osquery#5608]
Badges will be added with a PR, but the CI system has already been setup and can be seen here: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=308

Some tests are failing, and should either be fixed or skipped. An issue can be opened for each failing test that has been disabled, to make it easier to track them.

**Comment by Smjert** [comment]
Opened #5634 for the test that has been disabled.
