### ISSUE TITLE
Provide a custom toolchain for osquery 4.x

### ISSUE THREAD

**Issue by alessandrogario** [osquery/osquery#5609]
The old version of osquery has always been built with a custom toolchain. The new release has however dropped support for it, and it would be nice to provide a replacement. This would greatly help in adding support for reproducible builds.

@theopolis has been working on a toolchain that could be integrated in the project. It can also be expanded later on, and use it to build the external dependencies.

**Comment by theopolis** [comment]
It looks like this toolchain also needs a generally-compatible version of linux-headers.

**Comment by directionless** [comment]
Discussion in today's office hours is that:

* We should ship the toolchain, even without updating all the third party libs for centos6 support
* We believe this is similar to the status quo, it is not a step back
* This probably needs some doc updates, and some binaries checked in
* The work of checking each third party lib can be done ad-hoc, post release.
* Future work for automating this better with CI or autoconf automation in https://github.com/osquery/osquery/issues/5743

**Comment by theopolis** [comment]
Steps towards landing the toolchain:

- [ ] The `osquery/osquery-toolchain` final issues and documentation need to be resolved.
- [ ] A release of `osquery/osquery-toolchain` should be tagged and a tarball of the pre-built toolchain uploaded as an asset.
- [ ] The `osquery/osquery` Azure pipeline should be edited to introduce a new configuration that downloads and uses the toolchain.

**Comment by directionless** [comment]
I added `osquery/osquery-toolchain` to easyCLA
