### ISSUE TITLE
Current dependencies compiled without -fPIC and CMake build is non-PIE

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5611]
It looks like there are some regressions here. 

We should not cut a release unless the resulting binaries can be compiled with `-fPIE` and `-fPIC`. This might mean recompiling the dependencies.

**Comment by alessandrogario** [comment]
The correct setting is present inside the CMake code:

`cmake/utilities.cmake`
```
  set_target_properties(global_settings PROPERTIES
    INTERFACE_POSITION_INDEPENDENT_CODE ON
  )
```

**Comment by alessandrogario** [comment]
In case we do have to rebuild the deps, I was wondering if the London team (cc @fmanco) could assist us with some instructions. Doesn't have to be too formal; a quick how-to on Slack is fine, then we can capture it inside a readme in the repo.

**Comment by Smjert** [comment]
Just want to mention that this is going to be dealt with https://github.com/osquery/osquery/pull/5706
