### ISSUE TITLE
CPack: Name release artifacts by to os/arch 

### ISSUE THREAD

**Issue by groob** [osquery/osquery#5624]
I downloaded the 4.0.0 pre-release, which has the following artifacts:

<img width="780" alt="Screen Shot 2019-07-03 at 10 08 31 AM" src="https://user-images.githubusercontent.com/1526945/60598378-9a313d80-9d7a-11e9-9222-0e82e262bd2e.png">

I'd like to propose that we provide more granular, architecture specific release assets:
For example:
`osquery-4.0.0.darwin-amd64.pkg` or `osquery.4.0.0.windows-386.msi`

**Comment by alessandrogario** [comment]
I'm in favor of the change! I think that the reason there is no architecture in the file name is because x64 is the only supported platform right now

**Comment by directionless** [comment]
Hrm. I see value in having things sanely sorted, though I think common packaging norms put the version last. I think this is fine. (though I'd rather use a seperator that's easy to pull out. hyphen probably). `osquery-version-platform-arch`

**Comment by Smjert** [comment]
I think this should be fixed by https://github.com/osquery/osquery/pull/5822/files and https://github.com/osquery/osquery/pull/5770/files?
