### ISSUE TITLE
Unable to remove osquery from hosts

### ISSUE THREAD

**Issue by agentsofshield** [osquery/osquery#5643]
### What operating system and version are you using?
Windows 10
Windows 7

### What version of osquery are you using?
Osquery v3.4.0

### What steps did you take to reproduce the issue?
I used the script provided to create a custom MSI file `make_windows_package.ps1` and installed osquery on my hosts.
Then I tried to uninstall using the uninstall string and the MSI itself (msi /uninstall). Also ran Microsoft Install and Uninstall Diagnostic Tool.

### What did you expect to see?
Osquery showing up in the appwiz and being able to uninstall it.

### What did you see instead?
Osquery did not show as an installed program in appwiz after running the MSI, although the service is installed and process is running regularly. When trying to use the MSI to uninstall I saw the following message :
`
This patch package could not be opened. Verify that the patch package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer patch package
`
When trying to use the uninstall string I see this message:
`This action is only valid for products that are currently installed`

**Comment by directionless** [comment]
I think much of the packaging has been reworked since this was filed. I'm going to close this. Please comment if this is still an issue with the provided packages.
