### ISSUE TITLE
Windows service isn't migrated to updated Program Files location

### ISSUE THREAD

**Issue by keeleysam** [osquery/osquery#5644]
# Bug report

### What operating system and version are you using?

Windows 10 1903

### What version of osquery are you using?

3.4.0, migrating from 3.3.2

### What steps did you take to reproduce the issue?

1. Install osquery 3.3.2 via chocolatey
2. Install the service with osqueryd.exe --install, it will install properly
3. Upgrade osquery to 3.4.0 via chocolatey
4. The service will still be pointing at the old ProgramData location instead of being updated.  Using osqueryd.exe --install will error out as the service already exists with old details.

### What did you expect to see?
If the service exists already, it should be updated to the new location.

### What did you see instead?
Service points at old location

**Comment by keeleysam** [comment]
tagging @muffins who pointed to https://github.com/osquery/osquery/blob/master/tools/deployment/chocolatey/tools/chocolateyinstall.ps1#L16-L25 which needs a bit more logic

**Comment by muffins** [comment]
I'll get this cleaned up, I was under the impression I had already updated this logic but that appears to have not been the case.

**Comment by muffins** [comment]
@keeleysam https://github.com/muffins/osquery/tree/win-svc-path-update-priv-esc should fix this, at least the service path is updated correctly, however it's having "safe" permission errors again and I haven't been able to sort it out. If you're just looking for the correct service path logic update that's got it. If you're alright with the Deny Write ACL, that will launch osquery up just fine also, it's just trying to apply "sane, safe" ACL permissions on the binary is failing somehow...

**Comment by mike-myers-tob** [comment]
@muffins do the permissions I documented in https://github.com/osquery/osquery/pull/5741 help with the debugging of the ACL for this?

**Comment by muffins** [comment]
@mike-myers-tob nah this was an issue with just getting the service installed path updated when installing a new version. #5790 handles this but only if you do version pinning, I still don't have a fix for if one uses `choco upgrade`, but I'm closing this out as I typically recommend one does `choco install --version` explicitly. Feel free to re-open if we need more effort here.
