### ISSUE TITLE
Build failing on macOS 10.14.5

### ISSUE THREAD

**Issue by Tchinmai7** [osquery/osquery#5651]
# Bug report

### What operating system and version are you using?
macOS 10.14.5

### What version of osquery are you using?
latest master

### What steps did you take to reproduce the issue?
1. Clone the repo   -  git clone https://github.com/osquery/osquery.git -b master src
2. Create a build directory  - mkdir build && cd build
3. Configure cmake - cmake ../src
4. Run the build - cmake --build . -j 4

### What did you expect to see?
A built osquery binary 

### What did you see instead?

build failing with the following error - Seeing the same with buck builds as well. Noticed the error first on the 3.4.0 branch, upgraded to master, ran into it again.

```
[ 60%] Building CXX object osquery/filesystem/CMakeFiles/osquery_filesystem.dir/filesystem.cpp.o
[ 60%] Building CXX object osquery/filesystem/CMakeFiles/osquery_filesystem.dir/posix/fileops.cpp.o
/Users/tsekar/sources/osquery-4.0/src/osquery/filesystem/posix/fileops.cpp:292:10: error: call to implicitly-deleted default constructor of 'glob_t'
  glob_t data;
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/glob.h:60:9: note: default constructor of '' is implicitly deleted because variant field 'gl_errblk' is an ObjC pointer
                int (^gl_errblk)(const char *, int);
                      ^
1 error generated.
make[2]: *** [osquery/filesystem/CMakeFiles/osquery_filesystem.dir/posix/fileops.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [osquery/filesystem/CMakeFiles/osquery_filesystem.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 60%] Linking CXX static library libosquery_remote_httpclient.a
[ 60%] Built target osquery_remote_httpclient
make: *** [all] Error 2
```

**Comment by Smjert** [comment]
Thanks for the report!
Out of curiosity, what `xcodebuild -version` outputs?

**Comment by Tchinmai7** [comment]
@Smjert  I don't have the Xcode installed, just have the command line tools. The command `xcodebuild -version` throws an error.


`
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
`

**Comment by Smjert** [comment]
I see, maybe then `clang --version` makes more sense.

I'm trying to understand what's different in the macOS installation from the CI one.

**Comment by Tchinmai7** [comment]
output of `clang --version`
`
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
`

**Comment by Smjert** [comment]
That seems a beta version of the Command Line Tools for Xcode 11.

We currently support up to the latest stable, which is the one for Xcode 10.2.1.

**Comment by Tchinmai7** [comment]
It builds fine with the command line tools for Xcode 10.2.1. Can you please add a note to the build instructions about the versions of xcode to use ? `xcode-select` installs the 11.0 version now.

**Comment by Smjert** [comment]
> It builds fine with the command line tools for Xcode 10.2.1. Can you please add a note to the build instructions about the versions of xcode to use ? `xcode-select` installs the 11.0 version now.

That seems quite strange though, I've even reinstalled a macOS 10.14.5 VM from scratch and used `xcode-select --install` and I get the CLI for 10.2.1, not 11.

That been said we'll add the note for the version.
