### ISSUE TITLE
Return all SQL query errors, not just the first one found

### ISSUE THREAD

**Issue by AndrewDK** [osquery/osquery#5655]
# Feature request

### What new feature do you want?

It would be helpful if a query that contained multiple (missing column) errors could return all the errors at once. Right now, only the first error is returned.

For example, observe the following iterations of a query with several invalid columns specified:

```
osquery> select pid, datetime, script_block_count, script_block_id from listening_ports;
Error: no such column: datetime
osquery> select pid, script_block_count, script_block_id from listening_ports;
Error: no such column: script_block_count
osquery> select pid, script_block_id from listening_ports;
Error: no such column: script_block_id
```

### How is this new feature useful?

More useful or complete error information makes osquery more accessible and easy to use, and minimizes round trips on crafting queries.

### How can this be implemented?

Keep checking the other columns ;) I understand that for a syntax error, it may not make sense to continue parsing a query, but for a content error, like a missing column, it seems practical.

**Comment by directionless** [comment]
I assume this is how sqlite works
