### ISSUE TITLE
Performance issue around joins

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5656]
Building on HEAD, I'm seeing some performance issues. 

My test query is:
`SELECT users.uid,chrome_extensions.version FROM users CROSS JOIN chrome_extensions USING (uid) WHERE identifier='aomjjhallfgjeglblehebfpbcfeobpgk'` This is running as root

As I understand it, the users table is somewhat expensive on osx. And I think that the `CROSS JOIN ... USING`  is the recommended way to pass that along. (@zwass ?)

But, comparing osquery 3.3.2 to 4.x.x gets very different results. On 3.3.2, that runs in about .3s. On head, it takes 30s, and has many more library calls. I added some VLOG statements to try to tell how many times `genUser` and `genChromeBasedExtensions` are called:

|    |  genUser | genChromeBasedExtensions |   |
| -- | ---------- | ------------ | -- |
| CROSS JOIN |  many | many | (The calls appear interleaved) |
| JOIN              | 1 | 1 |
| remove index=True, CROSS JOIN | many | many | (The calls appear interleaved) |
| remove index=True, JOIN | many | many | (The calls appear interleaved) |

Zach has been wondering if [index=True](https://github.com/osquery/osquery/blob/master/specs/users.table#L4) mattered. It appears not.

**Comment by directionless** [comment]
Given how data can change, it feels wrong to re-call an external API inside a JOIN, but I don't know much about how the query planner tracks this stuff.

**Comment by directionless** [comment]
@packetzero -- Zach thought you might be working on something related here

**Comment by directionless** [comment]
Hrm.  From https://github.com/osquery/osquery/pull/5368

> Important to note I had to remove the optimization on both the user and group tables that just called getpwnam if the query specified the uid or gid since the struct returned doesn't contain the IsHidden attribute. I'm not sure if or how much this will affect performance since I wasn't able to get the profiling to work with the new version (very likely I'm just doing it incorrectly).

**Comment by directionless** [comment]
Some testing...

If I special handle the constraints when UID is set (https://github.com/osquery/osquery/compare/master...directionless:seph/genuserbyuserid)  I see that genUsers is called a lot. But at least it's fast. This is mitigating, but still feels wrong. not to mention it omits the `is_hidden` field

But, if I try to tell sqlite that there is no index, and that we should cache the whole table, it's still called many times, and the query still takes 30s (https://github.com/osquery/osquery/compare/master...directionless:seph/queryplan)

**Comment by terracatta** [comment]
Just wanted to add my two cents here regarding the perf regression as a result of merging https://github.com/osquery/osquery/pull/5368.

Good performance on the user's table for JOIN use-cases is paramount. It's likely the most joined table in normal Osquery usage. I propose this `is_hidden` column be removed from the table before it lands in a stable release since it dramatically decreases the performance of the table for minimal information gain.

If this information is valuable, a new table can be constructed that can be joined against users or groups. Perhaps a `hidden_users` and `hidden_groups` table that enumerate the GIDs and UIDs of users with that flag.

**Comment by directionless** [comment]
Conclusion in office hours is to:
1. Revert https://github.com/osquery/osquery/pull/5368 (release blocking)
2. Investigate caching and query planning seperately
