### ISSUE TITLE
async readFile fails on Windows when getting ERROR_IO_INCOMPLETE

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#5661]
# Bug report

### What operating system and version are you using?

Windows 10
Windows Server 2016

### What version of osquery are you using?

3.3.2.
The code has not been changed in experimental, so this is most likely still an issue.

### What steps did you take to reproduce the issue?

The issue cannot be reproduced every time because it probably depends on hardware speed (CPU vs Disk speed) and also if the file read has been cached somewhere.

One way is to run ConfigTests.test_pack_noninline, after a system reboot.

### What did you expect to see?

The test not failing

### What did you see instead?

The test failing

In order, what's happening:
1. The test calls the following readFile overload, without specifying the `blocking` argument:
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L173-L192
while trying to read the test_noninline_packs.conf.
2. Worth to noting that if `blocking` is not specified, its default value is `false`. This means that the call is async, and has a blocksize set.
The called readFile function has the real implementation, and doesn't check the `blocking` argument, but it uses to configure the file handle:
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L98
which then sets the mode to PF_NONBLOCK and initializes PlatformFile with it:
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L79-L80
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L84
and sets the Windows PlatformFile `is_nonblock_` variable to true:
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/windows/fileops.cpp#L587-L589
3. The logic of readFile contains both the blocking and non-blocking implementation, but the `blocking` variable is not checked to decide which one to use:
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L134
Given that the call came in with `blocking` to false but the `block_size` set, readFile takes the blocking path but with a handle that's configured for non-blocking usage.

4. On Windows this causes the specific implementation of the PlatformFile `read` function to use GetOverlappedResult which can sometimes return an ERROR_IO_INCOMPLETE when the ReadFile request hasn't completed yet.
The `read` implementation exits with a return value of -1 when this happens, and so the readFile function exits early:
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L141-L142
https://github.com/osquery/osquery/blob/22d51ddc20d9c8a5787c88d037253777a7de209a/osquery/filesystem/filesystem.cpp#L153

There are also cases where the non-blocking path is called when the blocking one was configured in the handle.

This could also be a problem on Linux.

**Comment by Smjert** [comment]
I was working on this, since I originally reported it on osql.
I think there are several issues hidden here.
In general it seems to me that readFile it's trying to do too many things, maybe it should be at least split for the two cases (blocking and non-blocking) so that's clearer.
It also seems to support a particular case where it forces the read to be blocking if the device it reads from doesn't report a size (I presume a pipe?); this might need a clear statement.

Moreover, to create a test to force a ERROR_IO_INCOMPLETE error I had to resort to some hacks, patching the IAT (a Windows specific hack) to call my custom implementation of GetOverlappedResult.
It would be better to think on introducing seams between these API layers, to be able to mock the system API calls.

**Comment by mike-myers-tob** [comment]
Fixed in #6368 but we may revisit the use of this API in a refactor.
