### ISSUE TITLE
remove ' (deleted)' suffix from path in process_open_files, etc.

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#5663]
# Feature request

Originally reported by @packetzero on the osql project.

### What new feature do you want?

on linux, **process_open_files** and **process_memory_map** tables will read from /proc/$pid/maps.
The underlying file paths may contain a ' (deleted)' suffix.
Since queries are likely to use paths against other tables like hash or yara, this suffixed path format causes issues. I suggest we filter out the suffix and indicate the deleted information in a separate column. In fact, we probably already record this in the on_disk column.

### How can this be implemented?

There is already code in the processes.cpp file to check for ' (deleted)' suffix, but in some situations, it's kept. I think the main thing here is for the community to come to an agreement on what the right behavior is.

Relevant: https://stackoverflow.com/questions/50244427/what-deleted-means-in-proc-pid-maps

**Comment by directionless** [comment]
I think I lean towards removing it, and noting that in a column.

While I generally prefer presenting information as given, this seems like it would be much improved by a column instead of a suffix.

**Comment by directionless** [comment]
As far as I can tell, we _do_ remove the deleted suffix. Code looks okay, testing confirms it's removal, and discussion in #1607 says we're removing it. Please re-open if you have a test case.
