### ISSUE TITLE
Investigate adding ec2 tables to Windows and macOS

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5664]
Right now the ec2_* tables are not built on Windows or MacOS due to schema configuration. I would like to disable building and linking these tables, and disable linking the ec2 static library.

This issue tracks discussion and investigation for re-enabling this and changing the schema to support these tables. This would require a significant need for having these tables available. It might makes sense to enable on Windows in the future.

**Comment by mike-myers-tob** [comment]
The Windows part is done as of https://github.com/osquery/osquery/pull/6756

Since this issue was opened, AWS now actually offers [macOS EC2 instances](https://aws.amazon.com/about-aws/whats-new/2020/11/announcing-amazon-ec2-mac-instances-for-macos/).

**Comment by mike-myers-tob** [comment]
The macOS part is now also done as of #6817
