### ISSUE TITLE
Bug: Init Falsely Reports Extension Manager Start Failure

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#5679]
# Bug report

### What operating system and version are you using?

OS: Windows 10 Enterprise RS3 x64 (10.0.16299)

### What version of osquery are you using?

Shell version: 3.3.2

### What steps did you take to reproduce the issue?
Using TrailOfBits extension 1.2 (https://github.com/osql/extensions)
Extension listed in extensions.load file, which is set to autoload via CLI flag.

Invocation:
> osqueryi.exe --json --verbose --disable_extensions=false --extensions_autoload=extensions.load --extensions_require=C:\osquery_extension_testing\ToB.ext.exe "SELECT * FROM HostBlacklist"

### What did you expect to see?

No errors.

### What did you see instead?

When invoking osqueryi (shell) with the following command line, the attached stderr and stdout are produced:

[stderr.txt](https://github.com/osquery/osquery/files/3454275/stderr.txt)
[stdout.txt](https://github.com/osquery/osquery/files/3454276/stdout.txt)

The logging (see stderr.txt) shows that the extensions (trailofbits_osquery_extensions) are successfully loaded and registered, but the osqueryi's initialization function claims that extension load failed.  This is clearly wrong, since expected query results were returned and extension tables were successfully registered.

This is problematic for our use-case due to osqueryi not setting a return code in some(all?) common error cases (e.g., bad table name, syntax error, etc.); we rely on 1) filtering out info/warning logs and 2) the stderr pipe being clear in order to confirm that a query was successful.

**Update: New Issue didn't take me to the template-selection screen.  Updating with bug-template format.**

**Comment by Smjert** [comment]
Thanks for this report!

Just to be clear, when using `--verbose` it's expected that additional output appears in stderr; that's a debugging option.

I see two bugs here, or a bug and a feature request:
1. Extension manager (incorrectly?) reporting a failure
2. osqueryi not setting (some?) errors in the exit code

Would it be possible to report the second one on a different issue?
Thanks!

**Comment by tferguson7337** [comment]
> Just to be clear, when using --verbose it's expected that additional output appears in stderr; that's a debugging option.

Yep!  --verbose was intended to provide more detailed logging for this ticket; the error message comes through regardless.  I will file a separate bug for osqueryi not returning an error code.

**Comment by tferguson7337** [comment]
One thing to note that I've learned about the --extensions_require flag:
The flag seems to key off of an extension group name that is set via makefile, rather than the filename of the extension.  This makes our use-case non-viable: without access to the makefile for w/e arbitrary extension we want to run, we can't use this flag as-is.  It seems this flag should accept extension path(s) to support this use-case.

For instance, Trail of Bits defines their extension group name (in https://github.com/trailofbits/osquery-extensions/blob/master/CMakeLists.txt#L23) to "trailofbits_osquery_extensions".  W/o knowing ahead of time the contents of the make-file, we hit this issue.

**Comment by theopolis** [comment]
> It seems this flag should accept extension path(s) to support this use-case.

One oversight in designing the extensions API is not providing this context information in the handshake. So the osquery core does not know about the path. I can thing of creative ways to work around this but they'd require code changes to osquery.

**Comment by Smjert** [comment]
@tferguson7337 It's also possible to retrieve those values through a query to the meta table `osquery_extensions`:

```
osquery> select * from osquery_extensions;
+-------+--------------------------------+--------------------+-------------+-------------------------+-----------+
| uuid  | name                           | version            | sdk_version | path                    | type      |
+-------+--------------------------------+--------------------+-------------+-------------------------+-----------+
| 0     | core                           | 4.0.2-21-g52171f56 | 0.0.0       | \\.\pipe\shell.em       | core      |
| 25511 | trailofbits_osquery_extensions | 1.2                | 0.0.0       | \\.\pipe\shell.em.25511 | extension |
+-------+--------------------------------+--------------------+-------------+-------------------------+-----------+
```

**Comment by tferguson7337** [comment]
Thanks for the suggestion @Smjert.  Unfortunately, our use-case is purely programmatic, so we cannot rely on the shell running as an interactive process.  Our program runs queries directly via command-line (through WinAPI CreateProcess), which causes osqueryi to run the query, return results, and exit immediately.

Due to this constraint of needing to run queries directly via command-line (non-interactive), we can't rely on `select * from osquery_extensions;`.  In this scenario, the query is ran before the extension is loaded, so we don't get the internal name (only result is for the "core").

**Comment by Smjert** [comment]
> Thanks for the suggestion @Smjert. Unfortunately, our use-case is purely programmatic, so we cannot rely on the shell running as an interactive process.

That makes sense, I was assuming that somewhere there was some manual process to list which extensions have to be autoloaded, and there one could also retrieve the ID.
Obviously UX here is not the best and in fact, it would make sense to open a feature request to add what you're asking here.
