### ISSUE TITLE
OSQuery third-party boost failed due to error C2039 under /permissive- + MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [osquery/osquery#5682]
OSQuery failed due to error C2039 when built on MSVC under /permissive- mode. Could you please have a look at this issue? Thanks a lot! 

I reported a source issue to Boost/beast team too: https://github.com/boostorg/beast/issues/1673

**Repro steps:**

1. git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2. open a VS 2017 x64 command prompt and browse to D:\OSQuery
3. cd src
4. tools\make-win64-dev-env.bat
5. mkdir build\windows10 && pushd build\windows10
6. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\..
7. cmake --build . --target osqueryd --config Release -- /maxcpucount

Build log: [log_build.log](https://github.com/osquery/osquery/files/3459918/log_build.log)

**Failures:**

D:\OSQuery\src\build\windows10\third-party\boost\boost\1.66.0\include\boost/beast/http/impl/file_body_win32.ipp(499): error C2039: 'write_some': is not a member of 'boost::beast::http::detail' [D:\OSQuery\src\build\windows10\osquery\remote\osquery_remote_httpclient.vcxproj]
  D:\OSQuery\src\build\windows10\third-party\boost\boost\1.66.0\include\boost/beast/http/impl/file_body_win32.ipp(278): note: see declaration of 'boost::beast::http::detail'
  D:\OSQuery\src\build\windows10\third-party\boost\boost\1.66.0\include\boost/beast/http/impl/file_body_win32.ipp(499): note: This diagnostic occurred in the compiler generated function 'size_t boost::beast::http::write_some(boost::asio::basic_stream_socket<Protocol> &,boost::beast::http::serializer<isRequest,boost::beast::http::basic_file_body<boost::beast::file>,Fields> &,boost::beast::error_code &)'
D:\OSQuery\src\build\windows10\third-party\boost\boost\1.66.0\include\boost/beast/http/impl/file_body_win32.ipp(507): error C2039: 'write_some': is not a member of 'boost::beast::http::detail' [D:\OSQuery\src\build\windows10\osquery\remote\osquery_remote_httpclient.vcxproj]
  D:\OSQuery\src\build\windows10\third-party\boost\boost\1.66.0\include\boost/beast/http/impl/file_body_win32.ipp(278): note: see declaration of 'boost::beast::http::detail'
  D:\OSQuery\src\build\windows10\third-party\boost\boost\1.66.0\include\boost/beast/http/impl/file_body_win32.ipp(507): note: This diagnostic occurred in the compiler generated function 'size_t boost::beast::http::write_some(boost::asio::basic_stream_socket<Protocol> &,boost::beast::http::serializer<isRequest,boost::beast::http::basic_file_body<boost::beast::file>,Fields> &,boost::beast::error_code &)'

**Comment by Smjert** [comment]
Hi, this seems to be an upstream issue more than an osquery one, we cannot do much in this case.

I've also seen that rapidjson has an issue similar to this when building with `/permissive-`

Maybe newer versions won't have these issues, but we cannot change them now, we are working to have dependencies always buildable by source to also simplify using newer versions, but this is not ready yet.

**Comment by QuellaZhang** [comment]
Thanks for your reply. We could not patch for this issue due to the build mechanism. Do you have any workaround for this? Or is it possible to disable third-party libraries?

**Comment by Smjert** [comment]
Third party libraries are dependencies for building osquery, without them it cannot build.
Those libraries right now are downloaded as pre-built from Facebook S3 bucket, we don't have a way to build them from source to patch them for now.

However, after they have been downloaded in the build folder, under the third-party folder, the headers could be patched.
Though depending on what `/permissive-` marks as problems, most likely patching them in the headers would result in something that doesn't build.
To have them downloaded but to avoid the build to start, you can try to build the `prepare_for_ide` target, and then patch them.

I don't have a specific workaround to solve this, because the supported flags for now are the standard ones that `msbuild` enables.
Is it possible for you to avoid enabling that flag?

**Comment by QuellaZhang** [comment]
Thank you @Smjert . We discussed and decided to disable OSQuery under /permissive mode. But I will continue to track this issue, I will give it a try if there are any updates.
