### ISSUE TITLE
Update build docs for the new build processes

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5688]
We should update the docs readthedocs use for the new build processes.

**Comment by mike-myers-tob** [comment]
https://github.com/osquery/osquery/pull/5708 should address this. Requesting this issue be closed.

**Comment by directionless** [comment]
Maybe. I don't think we have docs for the third party changes that are in flight, but #5708 does cover the current master.

**Comment by mike-myers-tob** [comment]
For what it's worth, I checked out the `thirdparty-submodules` branch and built it using the current instructions on macOS 10.14, Windows 10, and Ubuntu Linux 18.04.

I think I can add a couple of pre-requisites troubleshooting tips to the Windows 10 instructions.

And the Linux instructions should apparently include `sudo apt-get install flex bison`. I'll start another PR for these small fixes.

**Comment by directionless** [comment]
Let's call this issue good enough, and close it.

We may need another set of docs about the dependency finding behaviors.
