### ISSUE TITLE
Unloading osquery with `launchctl bootout` prints an error on macOS Catalina

### ISSUE THREAD

**Issue by weswhet** [osquery/osquery#5698]
#4803 Bug report

When attempting to `bootout` the osquery daemon on Catalina you receive the following error.

```
Boot-out failed: 36: Operation now in progress
```

Interestingly enough the Daemon does successfully stop. 

 Yes I'm aware the Catalina is a prerelease but wanted to make sure this was on the projects radar :). 

### What operating system and version are you using?
```
+---------+---------+----------+
| version | build   | platform |
+---------+---------+----------+
| 10.15   | 19A526h | darwin   |
+---------+---------+----------+
```
### What version of osquery are you using?
```
+---------+
| version |
+---------+
| 3.3.2   |
+---------+
```
### What steps did you take to reproduce the issue?

Install osquery on the latest developer preview of macOS Catalina (19A526h)

Make sure the service is running as intended.

Run the following
```
sudo launchctl bootout system/com.facebook.osquery
```

### What did you expect to see?
The osquery service should stop successful without error. 

### What did you see instead?

The reported error.

**Comment by weswhet** [comment]
cc @groob 

To add some more detail this action does not happen for all services on macOS. This could be a new behavior on Catalina if the service does not successfully handle the bootout request from launchd.

**Comment by groob** [comment]
Does this only happen with Catalina?
I'll try to reproduce with my test device. Thanks for reporting it!

**Comment by weswhet** [comment]
Yup only Catalina. Works as intended on 10.13 and 10.14.

**Comment by weswhet** [comment]
@groob did you get a chance to try and look/reproduce this?

**Comment by groob** [comment]
Not yet. Thanks for the reminder, I'll follow up.

**Comment by lashomb** [comment]
This is still an issue on macOS 10.15.2 running the latest osquery.

**Comment by mike-myers-tob** [comment]
Confirmed that this message does still print out when taking the following steps with macOS 10.15.6 and osquery 4.5.0.

```shell
# start osquery, this way or by invoking launchctl load
sudo osqueryctl start
# confirm that it is running
sudo launchctl print system/com.facebook.osqueryd
# stop it with the bootout subcommand
sudo launchctl bootout system/com.facebook.osqueryd
```

The output of that last command:
```Boot-out failed: 36: Operation now in progress```

You can confirm that although you get this messaged, it didn't fail, it just didn't wait for the unload. By the time it has printed this, the daemon is already unloaded.

But, this is the exact same behavior seen if you bootout the VMware LaunchDaemon, for example:

```sudo launchctl bootout system/com.vmware.launchd.tools```

And, anecdotally, this is the same if you bootout Symantec's SEP LaunchDaemon.

I see it as a new quirk of LaunchD and not a change in osquery, nor is it a problem per se. You can unload with ```sudo osqueryctl stop``` or ```sudo launchctl unload /Library/LaunchDaemons/com.facebook.osqueryd``` and you get only the ```Operation now in progress``` part of the output. I guess ```unload``` is now a "legacy" subcommand as described in the `man` page for `launchd`. As of macOS 10.11, so maybe out script and docs should be updated to use the "correct" (current) commands.

I recommend closing this issue as a Won't Fix.

**Comment by weswhet** [comment]
from my additional testing, it appears that the above `Boot-out failed: 36: Operation now in progress` only happens when there is an active PID for the `launchd` service. At first, I was unsure if this was osquery not handling a `SIGTERM` well but that doesn't appear to be the case.

Happy to close as this is definitely a macOS bug.
