### ISSUE TITLE
Crash due to heap initialization/allocation race

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#5700]
# Bug report

### What operating system and version are you using?
Windows 10 - any version, but most common on 19H1

### What version of osquery are you using?

osqueryi shell 3.3.2

### What steps did you take to reproduce the issue?

Run:  `osqueryi.exe --json --logger_min_status 2 "SELECT * FROM users"`

### What did you expect to see?

Results and no crash

### What did you see instead?

osqueryi crashing due to race condition around heap allocation and initialization.

Attaching stack of crashing thread and initialization thread.  Init thread has not yet reached its heap-init step when crashing thread calls malloc (via new)

[osquery_crash_stacks.txt](https://github.com/osquery/osquery/files/3493918/osquery_crash_stacks.txt)

**Comment by theopolis** [comment]
@tferguson7337, is this only crashing when you try to use the `users` table?

Are the other CLI flags required to reproduce? `--json` and `--logger_min_status 2`?

**Comment by muffins** [comment]
> osqueryi shell 3.3.2

Do you know if this is crashing on the latest version? I'll take a look at reproing here in a bit.

**Comment by muffins** [comment]
@tferguson7337 can you provide more information for this issue? At the moment I'm not able to repro, building off of master (4.0.1 tag) selecting from the users table is fine:

```
C:\Users\Nick\work\repos\osquery [master ≡]> .\build\windows10\osquery\Release\osqueryi.exe --json --logger_min_status 2 "SELECT * FROM users"
[
  {"description":"Built-in account for administering the computer/domain","directory":"C:\\Users\\Administrator","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"500","uid_signed":"500","username":"Administrator","uuid":"S-1-5-21-3535526762-2088972459-3486670382-500"},
  {"description":"A user account managed by the system.","directory":"","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"503","uid_signed":"503","username":"DefaultAccount","uuid":"S-1-5-21-3535526762-2088972459-3486670382-503"},
  {"description":"Built-in account for guest access to the computer/domain","directory":"","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"501","uid_signed":"501","username":"Guest","uuid":"S-1-5-21-3535526762-2088972459-3486670382-501"},
  {"description":"Built-in account for homegroup access to the computer","directory":"","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"1003","uid_signed":"1003","username":"HomeGroupUser$","uuid":"S-1-5-21-3535526762-2088972459-3486670382-1003"},
  {"description":"","directory":"C:\\Users\\muffins","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"1008","uid_signed":"1008","username":"muffins","uuid":"S-1-5-21-3535526762-2088972459-3486670382-1008"},
  {"description":"","directory":"C:\\Users\\Nick","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"1001","uid_signed":"1001","username":"Nick","uuid":"S-1-5-21-3535526762-2088972459-3486670382-1001"},
  {"description":"A user account managed and used by the system for Windows Defender Application Guard scenarios.","directory":"","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"504","uid_signed":"504","username":"WDAGUtilityAccount","uuid":"S-1-5-21-3535526762-2088972459-3486670382-504"},
  {"description":"","directory":"C:\\Users\\???","gid":"513","gid_signed":"513","shell":"C:\\Windows\\System32\\cmd.exe","type":"local","uid":"1009","uid_signed":"1009","username":"πü»πéïπü¿","uuid":"S-1-5-21-3535526762-2088972459-3486670382-1009"},
  {"description":"","directory":"%systemroot%\\system32\\config\\systemprofile","gid":"18","gid_signed":"18","shell":"C:\\Windows\\system32\\cmd.exe","type":"special","uid":"18","uid_signed":"18","username":"SYSTEM","uuid":"S-1-5-18"},
  {"description":"","directory":"%systemroot%\\ServiceProfiles\\LocalService","gid":"19","gid_signed":"19","shell":"C:\\Windows\\system32\\cmd.exe","type":"special","uid":"19","uid_signed":"19","username":"LOCAL SERVICE","uuid":"S-1-5-19"},
  {"description":"","directory":"%systemroot%\\ServiceProfiles\\NetworkService","gid":"20","gid_signed":"20","shell":"C:\\Windows\\system32\\cmd.exe","type":"special","uid":"20","uid_signed":"20","username":"NETWORK SERVICE","uuid":"S-1-5-20"}
]
```

**Comment by muffins** [comment]
@tferguson7337 any updates? We'd love to help triage this issue, however we'd like to keep the issues we track cleaned up. If we don't receive a response in the next couple of weeks we'll close this issue out, but please feel free to re-open if you have any additional details you can provide!

**Comment by mike-myers-tob** [comment]
Assuming the original explanation for the bug, I don't understand how it happens. Shouldn't the C++ runtime initialize a heap for the process before calling the `main()` entry point, let alone before osquery starts spawning new threads?

**Comment by tferguson7337** [comment]
Apologies for the radio silence - lost sight of this one.  No updates on this and we haven't seen it for some time now.  I think this can be closed.

> I don't understand how it happens. Shouldn't the C++ runtime initialize a heap for the process before calling the main() entry point, let alone before osquery starts spawning new threads?

I don't get it either, don't understand how this occurred.
