### ISSUE TITLE
sqlite susceptible to trojan data

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5702]
sqlite is in the news with a vulnerability. An attacker can craft a malicious sqlite DB, which can cause unexpected behavior. https://research.checkpoint.com/select-code_execution-from-using-sqlite/

Several places in osquery read sqlite data. 

Does this give a user a route to privilege escalation? It's not yet clear what mitigations we can do.

**Comment by theopolis** [comment]
The mitigations would be to remove the build-time options here: https://github.com/osquery/third-party-sqlite/blob/2ca13814d05e8408b445b1938aaf6c675e5a510f/CMakeLists.txt#L21
