### ISSUE TITLE
Enable compiler warnings flags and/or linters

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5724]
While filling out https://bestpractices.coreinfrastructure.org/ it requests that we should:

> The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language.  
> 
> The project MUST address warnings
>
> It is SUGGESTED that projects be maximally strict with warnings in the software produced by the project, where practical.  

I'm not sure if we do those

**Comment by alessandrogario** [comment]
Several warnings have been enabled; they are going to be moved after the third-party-submodules branch is merged, but right now they can be found here: https://github.com/osquery/osquery/blob/81e12f718cf2a7652131a608baeedb62185dee6a/cmake/utilities.cmake#L211

Concerning linting and code quality tests, we once had cppcheck support but was lost during the experimental refactor.

**Comment by theopolis** [comment]
This is complete.
