### ISSUE TITLE
Making Linux information cgroup aware using libresrouce

### ISSUE THREAD

**Issue by rahuyada** [osquery/osquery#5725]
The information provided by OSquery for Linux OS is not cgroup aware for some resources.  For example currently memory related information is gathered by reading /proc/meminfo in procfs. But procfs is not cgroup aware. If a process is running in a virtualized environment (for example running in a container) then the information provided by procfs will reflect statistics for whole system, not the virtualized environment.

We can use libresource to get such information. libresource is a library to get system resource information in and it is cgroup aware.
https://github.com/lxc/libresource
If the query process is running in a containerized environment libresource will provide container aware information, else it will provide information directly from procfs which will be system wide information.

**Comment by directionless** [comment]
It looks that library hasn't been updated in some time, and we're looking at doing this in different ways.
