### ISSUE TITLE
Restore Windows Event Logging support

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#5735]
It seems that the Windows Event Logging support has been lost in the passage.

The relevant commits implementing it or changing code related to it: 
e859276739b48447d937b2eb810630f2b9a7e548
2c8813a1506b73d5a58593da0db7429f69fbc999
214302bdeb38fbdb606774ae9165dd633b908604

We have to maybe update something of those files and also reintroduce windows_resources.rc in the build.

**Comment by theopolis** [comment]
@packetzero, you had mentioned in Slack that WEL is working in 4.0.1?

**Comment by alessandrogario** [comment]
The publisher is still working fine, but the WEL logger plugin is no longer usable due to the missing resource script in the executable (attempting to register it without it will likely cause an error).

**Comment by muffins** [comment]
I'm flying a bit blind on difficulty, but I think this would make a really good Hacktoberfest bug fix for someone to land. This issue would be good for someone a bit comfortable with Windows debugging chops, but I believe the fix will ultimately relate to our packaging and deployment scripts for the osquery Windows installation. Hit up @alessandrogario or myself for help on how to get started!

**Comment by akefallonitis** [comment]
Is there any update ? Its been troubling to have osqeury without being able to collect the logs.

Thanks in advanced
