### ISSUE TITLE
Windows video_info table returns the date in an unexpected format

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5746]
While looking at some data, I noticed that `select driver_date from video_info` returns a date in the format of `20171017018000.000000-000`. This was somewhat unexpected. I expected seconds since the epoch. 

I'm not sure what correct is, but I think we should try to be consistent.

If I'm looking at the right part of the windows docs, https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-videocontroller says it's a `datetime` object.

**Comment by muffins** [comment]
It looks like this might also be a problem with the `os_version` table, I'll give a crack at this as I think the fix isn't too bad.

**Comment by muffins** [comment]
This should be addressed with #5901
