### ISSUE TITLE
/var/log/syslog contains INFO logs after osquery install

### ISSUE THREAD

**Issue by biocyberman** [osquery/osquery#5749]
# Bug report

### What operating system and version are you using?

sudo osqueryi --line "SELECT version, build, platform FROM os_version;"
I0904 23:58:31.266387 84402 database.cpp:563] Checking database version for migration
I0904 23:58:31.266444 84402 database.cpp:587] Performing migration: 0 -> 1
I0904 23:58:31.266461 84402 database.cpp:619] Migration 0 -> 1 successfully completed!
I0904 23:58:31.266470 84402 database.cpp:587] Performing migration: 1 -> 2
I0904 23:58:31.266482 84402 database.cpp:619] Migration 1 -> 2 successfully completed!
I0904 23:58:31.287463 84402 options.cpp:103] Verbose logging enabled by config option
I0904 23:58:31.287572 84402 killswitch.cpp:60] osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0904 23:58:31.288553 84402 events.cpp:1116] Error registering subscriber: process_file_events: Subscriber disabled via configuration
I0904 23:58:31.297232 84402 events.cpp:745] Subscriber expiration is too low: hardware_events
 version = 16.04.6 LTS (Xenial Xerus)
   build =
platform = ubuntu
### What version of osquery are you using?

sudo osqueryi --line "SELECT version from osquery_info;"
I0904 23:59:08.897140 84937 database.cpp:563] Checking database version for migration
I0904 23:59:08.897197 84937 database.cpp:587] Performing migration: 0 -> 1
I0904 23:59:08.897214 84937 database.cpp:619] Migration 0 -> 1 successfully completed!
I0904 23:59:08.897223 84937 database.cpp:587] Performing migration: 1 -> 2
I0904 23:59:08.897235 84937 database.cpp:619] Migration 1 -> 2 successfully completed!
I0904 23:59:08.918025 84937 options.cpp:103] Verbose logging enabled by config option
I0904 23:59:08.918138 84937 killswitch.cpp:60] osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0904 23:59:08.918272 84937 events.cpp:1116] Error registering subscriber: process_file_events: Subscriber disabled via configuration
I0904 23:59:08.926852 84937 events.cpp:745] Subscriber expiration is too low: hardware_events
version = 3.3.2
### What steps did you take to reproduce the issue?
Install and run osquery
### What did you expect to see?
Without the errors
### What did you see instead?
/var/log/syslog is flooded with tons of lines like this: 
Sep  4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818204  2142 virtual_table.cpp:729] Error casting inode () to BIGINT
Sep  4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818256  2142 virtual_table.cpp:729] Error casting uid () to BIGINT
Sep  4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818279  2142 virtual_table.cpp:729] Error casting gid () to BIGINT
Sep  4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818303  2142 virtual_table.cpp:729] Error casting size () to BIGINT

**Comment by theopolis** [comment]
Hi @biocyberman, the logs you mention:
```
Sep 4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818204 2142 virtual_table.cpp:729] Error casting inode () to BIGINT
Sep 4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818256 2142 virtual_table.cpp:729] Error casting uid () to BIGINT
Sep 4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818279 2142 virtual_table.cpp:729] Error casting gid () to BIGINT
Sep 4 06:26:04 server1 osqueryd[1459]: I0904 06:26:04.818303 2142 virtual_table.cpp:729] Error casting size () to BIGINT
```

Are informational. You're right that it's not ideal to have these messages in syslog. Do you mind sharing your osquery configuration. Perhaps the logging is too verbose.

**Comment by biocyberman** [comment]
@theopolis This is the configuration:

```
cat /etc/osquery/osquery.conf
{
  // https://osquery.readthedocs.io/en/stable/deployment/configuration/
  // Configure the daemon below:
  "options": {
    // Select the osquery config plugin.
    "config_plugin": "filesystem",

    // Select the osquery logging plugin.
    "logger_plugin": "filesystem",

    // The log directory stores info, warning, and errors.
    // If the daemon uses the 'filesystem' logging retriever then the log_dir
    // will also contain the query results.
    "logger_path": "/var/log/osquery",

    // Set 'disable_logging' to true to prevent writing any info, warning, error
    // logs. If a logging plugin is selected it will still write query results.
    "disable_logging": "false",

    // Splay the scheduled interval for queries.
    // This is very helpful to prevent system performance impact when scheduling
    // large numbers of queries that run a smaller or similar intervals.
    "schedule_splay_percent": "10",

    // Write the pid of the osqueryd process to a pidfile/mutex.
    "pidfile": "/var/osquery/osquery.pidfile",

    // Clear events from the osquery backing store after a number of seconds.
    "events_expiry": "3600",

    // A filesystem path for disk-based backing storage used for events and
    // query results differentials. See also 'use_in_memory_database'.
    "database_path": "/var/osquery/osquery.db",

    // Comma-delimited list of table names to be disabled.
    // This allows osquery to be launched without certain tables.
    "disable_tables": "",

    // Enable debug or verbose debug output when logging.
    "verbose": "true",

    // Maximum file read size
    "read_max": 100000,

    // Maximum number of events per type to buffer
    "events_max": 100000,

    // Enable the schedule monitor
    "enable_monitor": true,

    // Field used to identify the host running osquery (hostname, uuid)
    "host_identifier": "hostname"
  },

  // Define a schedule of queries:
  "schedule": {
    // This is a simple example query that outputs basic system information.
    "system_info": {
      // The exact query to run.
      "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
      // The interval in seconds to run this query, not an exact interval.
      "interval": 3600
    },
    "file_events": {
      "query": "SELECT * from file_events;",
      "removed": false,
      "interval": 60
    }
  },

  // Decorators are normal queries that append data to every query.
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },

  // Add default osquery packs or install your own.
  //
  // There are several 'default' packs installed with 'make install' or via
  // packages and/or Homebrew.
  //
  // Linux:        /usr/share/osquery/packs
  // OS X:         /var/osquery/packs
  // Homebrew:     /usr/local/share/osquery/packs
  // make install: {PREFIX}/share/osquery/packs
  //
  "packs": {
    "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
    "incident-response": "/usr/share/osquery/packs/incident-response.conf",
    "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
    "osx-attacks": "/usr/share/osquery/packs/osx-attacks.conf",
    "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
    "hardware-monitoring": "/usr/share/osquery/packs/hardware-monitoring.conf"
  },

  // httpw://osquery.readthedocs.io/en/stable/deployment/configuration/#file-paths
  "file_paths": {
    "homes": [
      "/root/.ssh/%%",
      "/home/%/.ssh/%%"
    ],
    "etc": [
      "/etc/%%"
    ],
    "tmp": [
      "/tmp/%%"
    ]
  }
  // https://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/
  // Enabling this setting will disable file hashing.
  // "file_accesses": ["homes", "etc", "tmp"]
}
```

**Comment by theopolis** [comment]
Thanks for posting, can you remove the option for verbose logging (the line verbose=true), and see if that helps?

**Comment by biocyberman** [comment]
It reduced some logging, but still there are many lines like the following, which caused service denial due to lack of disk space :(

`Sep  6 18:38:52 server1 osqueryd[114274]: W0906 18:38:52.225931 52136 filesystem.cpp:113] Cannot read file that exceeds size limit: /run/atop/atop.acct`

**Comment by theopolis** [comment]
That is a legitimate warning, a query is reading a file that exceeds the max expected size.

You can update that max size in the configuration using the “read_max” option: https://osquery.readthedocs.io/en/latest/installation/cli-flags/

**Comment by biocyberman** [comment]
@theopolis I added `--max_read=52428800` (50MB) to `/etc/osquery/osquery.flags`, restarted the service. However, osquery still emits many of these lines: 

`Sep 10 12:58:57 server1 osqueryd[51068]: W0910 12:58:57.641641 51102 filesystem.cpp:113] Cannot read file that exceeds size limit: /run/atop/atop.acct`

And size of atop.acct:

```
sudo ls -lah /run/atop/atop.acct
-rw------- 1 root root 12M Sep 10 12:59 /run/atop/atop.acct
```
So, osquery doesn't seem to use the flag.

**Comment by muffins** [comment]
@biocyberman looks like the flag is wrong, it should be `--read_max=52428800`. You can see an exhaustive list of all osquery configuration flags by checking out the `osquery_flags` virtual table within the shell. Let us know if that helps?
