### ISSUE TITLE
Deprecation of ASL logging, and asl table

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#5760]
# Blueprint

This issue was opened by @groob originally on the osql fork:

> ASL logging is deprecating on macOS, which keeps the osquery builds from moving to a newer darwin SDK.
>
> Suggestion: move the asl table out of core into an extension. Move to the 10.14 SDK

ASL logging was deprecated a while back in favor of Unified Logging, but Apple never gave us an API for _reading_, only for _writing_. For reading, we were limited to invoking the `log` command-line process or the Console.app GUI. Trail of Bits created an osquery table for reading the Unified Log this way, as an extension https://github.com/trailofbits/osquery-extensions/tree/master/darwin_unified_log

I think the path forward should open soon, if we implement an osquery table for macOS Unified Logging that uses the `OSLogStore::getEntries()` API (new in the 10.15 SDK), As @keeleysam suggested:

> it should be replaced with something that calls 
> https://developer.apple.com/documentation/logging/oslogstore/3204125-getentries which is new in 10.15

Related: #2487 where the issue was acknowledged but resolved by suppressing the deprecation warnings and staying on the old SDK.

**Comment by mike-myers-tob** [comment]
As of macOS 10.15 and around the end of 2019, there's now a reading API for the Unified Log https://developer.apple.com/documentation/oslog

https://developer.apple.com/documentation/oslog/oslogstore/3366102-local
> To read the system log, the caller must be run by an admin account and have the com.apple.logging.local-store entitlement.

https://twitter.com/macshome/status/1197242131942924295/photo/1

**Comment by thealanberman** [comment]
Is there any work/progress on leveraging the new API?

**Comment by mike-myers-tob** [comment]
Nobody is yet working on implementing this, but it would be a welcomed contribution if someone wants to.

**Comment by directionless** [comment]
Closed by #7598
