### ISSUE TITLE
Consider reintroducing fuzz test cases

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#5766]
# Blueprint

This is also related to the "dynamic analysis" criteria for the CII badge (osquery/foundation#17),  sanitizers on the debug builds (osquery/osquery#5628), and something similar on Windows (osquery/osquery#5734).

It looks like there used to be a `make fuzz` build target, was it removed in the refactor? Did it invoke [`./tools/analysis/fuzz.py`](https://github.com/osquery/osquery/blob/master/tools/analysis/fuzz.py)?

There are some open questions still, as to how best to incorporate fuzz test cases, and for which components.

Notes from a previous discussion:
- modify the system state (fuzz the source data that acts as input to an osquery table)
- you could fuzz the filetypes that osquery reads/parses directly, such as .plist files, . `cron`, `authorized_keys`, `launchd`, `chrome_extensions`, etc. Most system state, however, is accessed via a system API.
- the osqueryd process usually runs as root so it is a possible privesc vector
- the query interface itself is not of interest for fuzzing, because access is limited to whoever controls the server, or the osquery config file. Both of those already ought to be access-limited to a small group of privileged users.
- likewise osquery doesn't accept any incoming network connections
- the Thrift API socket is also access controlled (although questions have been raised about that on Windows where it's a named pipe)

**Comment by theopolis** [comment]
In this past I found value from fuzz testing the JSON parsing to assure correctness, less so to mitigation security risk. There was security-related value in hardening JSON parsing because several user-control datums could have caused corruption and potentially privesc as mentioned above.

**Comment by theopolis** [comment]
This is being tracked in #5905.
