### ISSUE TITLE
Refactor and restore TLS tests

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#5768]
# Task

TODO: refactor and restore TLS tests on Windows.

The `TLSConfigTests` on Windows were disabled, and have not since been re-enabled, as mentioned in https://github.com/osquery/osquery/pull/5629

- [ ] [osquery/config/plugins/tests/tls_config_tests.cpp](https://github.com/osquery/osquery/blob/master/tests/unit/config/plugins/tls_config_tests.cpp)
- [ ] [osquery/remote/transports/tests/tls_transports_tests.cpp](https://github.com/osquery/osquery/blob/master/osquery/remote/transports/tests/tls_transports_tests.cpp)

**Comment by Smjert** [comment]
I would like to specify that there are single testcases disabled in some of the tests we are currently running that have to be restored.
Basically, all the ones based on TLSServerRunner, which actually uses https://github.com/osquery/osquery/blob/master/tools/tests/test_http_server.py in the background.
That script as mentioned in this PR https://github.com/osquery/osquery/pull/5836, still has to be updated.

Moreover, we have some of the tests (like https://github.com/osquery/osquery/blob/master/plugins/logger/tests/tls_logger_tests.cpp) which currently try to start that server, even if it will clearly fail, but the test pass.
So we might also want to improve the reliability of the test results from this tests.
