### ISSUE TITLE
Osquery debian package failing GPG signature

### ISSUE THREAD

**Issue by shivamdixit** [osquery/osquery#5792]
# Bug report

### What operating system and version are you using?
Debian GNU/Linux 8 (jessie)

### What version of osquery are you using?

version 3.3.2

### What steps did you take to reproduce the issue?

Run `apt-get update` on the host with `https://pkg.osquery.io/deb` in the source lists, it fails with: 

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://pkg.osquery.io deb Release: The following signatures were invalid: BADSIG 97A80C63C9D8B80B osquery (osquery) <osquery@fb.com>

W: Failed to fetch https://pkg.osquery.io/deb/dists/deb/Release
```

I have validated client side configurations, for example, cleaning the cache, fetching the latest key (sudo apt-key...), etc. 

### More Details

On debugging, it turns out that the osquery pkg servers with the `Release` file from `11 Sep 2019` have the correct signatures, however, servers with `Release` file from `10 Jan 2019` have bad signatures. 

Some of the servers that have correct signature: `99.84.216.42, 99.84.216.20`. Some of the servers with bad signature : `13.35.125.126, 13.35.125.116, 13.224.2.123`. I have manually downloaded the Release files from the repo and validated the signatures with `gpgv`, it fails for the release from `10 Jan 2019`.

```
$ diff --suppress-common-lines -y <(curl -sS4k --resolve 'pkg.osquery.io:443:13.224.2.123' https://pkg.osquery.io/deb/dists/deb/Release.gpg) <(curl -sS4k --resolve 'pkg.osquery.io:443:99.84.216.42' https://pkg.osquery.io/deb/dists/deb/Release.gpg)

$ diff --suppress-common-lines -y <(curl -sS4k --resolve 'pkg.osquery.io:443:13.224.2.123' https://pkg.osquery.io/deb/dists/deb/Release) <(curl -sS4k --resolve 'pkg.osquery.io:443:99.84.216.42' https://pkg.osquery.io/deb/dists/deb/Release)
Date: Thu, 10 Jan 2019 03:05:59 UTC                  |    Date: Wed, 11 Sep 2019 04:25:30 UTC
 491a958811651eed05585e85aa702c23 36908 main/binary-amd64/Pac |     2452adc2c24e445c08d4f0958fe40dc9 38309 main/binary-amd64/Pac
 6c2d50d6e978ebf16e5a5dcc6f65f6ac 10408 main/binary-amd64/Pac |     5079ce74b5b88c730d3e48ad43a613ad 10835 main/binary-amd64/Pac
 675260682e6acfb4d5389993d03a7449 175 main/binary-amd64/Relea |     7c325b7d04c476fc70fd545758c5e69b 175 main/binary-amd64/Relea
 e0f28caf3e0b4fc8a1e85aac33d039c62bfce716 36908 main/binary-a |     ddfd2fb01d0c0b9e3e710af5559cb8b9eb3b10a9 38309 main/binary-a
 26b2bd2a828dd453b1f6f131818210d8fa6eb125 10408 main/binary-a |     f1b2903099b0e206c86ce3f12dc35650e94ae840 10835 main/binary-a
 6086e89b16d9cd39557c4fcca0852357142340f0 175 main/binary-amd |     d375b832b7b7bdfecadf46be55289f14ee77fc7e 175 main/binary-amd
 bc33c1fdae08b2719113e0bc8c7cad002d94b9429993a2dd231b1a75a568 |     c14d8d95a98f3a1b17ef4ef3f076eef4d2603c96e5e9ed23f5571d311917
 5e4bcd04bcb069f8ac6243e056a0454074ffb0badac3ad88e835dbf465ef |     5fda4e0497bc2a784a9f076057d494125b492ad3e4b7a0a43a3b3c57de8b
 26fe08c04437caae5627b171ebf1051bf0b3d0c1a5a80053e44144679cc1 |     7a73fbab8d4f1d3637eae5411dba86d50a8b8c4bb0d8cde56f9c500e1755
 e0f24150e20792f38d46f9d267ec8dab61df0807d6544d770345ad923a9e |     5a3ba8e2a66c7b6d523cae98595e6248bf050e0416c13207cf42520c9375
 dc1bcce8f3fc6b5a9b86b363f20b90ed1492cdb5c6d932bda42c7bac04fa |     57e760548f8b49afcafc6cb9e923bd8bf9243691098a69573442a6afe4b9
 1ab11dcacbef3bc9293262f139742a583e1cc862434c418db740a964e5a0 |     d226bb420f935711d890177619c4cce777431e6a59ffaafdfb2d521e7b0d
```

**Comment by ricbartm** [comment]
Same here 🤚 a workaround that seems to works has been using this repo config:
```
deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/deb deb main
```

So we hit the origin S3 bucket instead of CloudFront distribution. Problem looks to disappear ever it might be slower.

Got that domain from https://github.com/osquery/osquery/issues/4144

**Comment by rbreckenridge** [comment]
It seems like something got resolved yesterday afternoon, after a full day of failed deployments it's working again...

**Comment by theopolis** [comment]
This is the first time we've updated the repos, which are backed by S3, after placing CloudFront as our TLS terminator. Before there was a small Apache reverse proxy. That small host was purposefully DoSed a few times back forcing us to migrate.

I will explore more of the CloudFront origin cache options to see if I can fix this issue.
