### ISSUE TITLE
[Windows][4.0.1] manage-osqueryd.ps1 installed service missing quotes

### ISSUE THREAD

**Issue by mike2523** [osquery/osquery#5798]
# Bug report

### What operating system and version are you using?

Windows 10 1809

### What version of osquery are you using?
4.0.1

### What steps did you take to reproduce the issue?
`"C:\Program Files\osquery\osqueryd\osqueryd.exe" --install`
### What did you expect to see?
service path to executable:

`"C:\Program Files\osquery\osqueryd\osqueryd.exe" --flagfile="C:\Program Files\osquery\osquery.flags"`
### What did you see instead?
`C:\Program Files\osquery\osqueryd\osqueryd.exe --flagfile=\Program Files\osquery\osquery.flags`

**Comment by muffins** [comment]
This should be addressed with #5824
