### ISSUE TITLE
Extend Support for Google Chrome Extensions to support Brave and Chromium 

### ISSUE THREAD

**Issue by terracatta** [osquery/osquery#5800]
Brave (https://brave.com/) is becoming an increasingly popular alternative to Google Chrome. It is based on Chrominium and can run the majority of extensions in the Chrome store.

Since we are seeing a notable increase in the amount of users running this browser, it would be nice to expand the the `chrome_extensions` table to additionally look at extensions installed on Brave and possibly the default paths for a vanilla Chromium installation.

On my Mac, Brave extensions are stored in `~/Library/Application\ Support/BraveSoftware/Brave-Browser/%/Extensions`.  (Where % is my profile name, in this case it is "Default")

In theory all that would need to be done is to modify https://github.com/osquery/osquery/blob/master/osquery/tables/applications/browser_chrome.cpp#L21 (and the method it calls) to accept a list of paths and include the default installation locations for both Brave and Chromium.

**Comment by muffins** [comment]
This would make a _great_ Hacktoberfest challenge for someone looking for a good project to take on!

**Comment by mike-myers-tob** [comment]
Thanks Rachel!
