### ISSUE TITLE
Potential race condition in osquery shell when also loading extensions

### ISSUE THREAD

**Issue by chrisbroome** [osquery/osquery#5812]
# Bug report

I’ve noticed an odd behavior when running osquery as a shell process and having extensions loaded. Running

```
osqueryd.exe --S --verbose "SELECT * FROM os_version"
```

with anything in the `extensions.load` file (I used the open source trail_of_bits extensions for example), it will execute the query and exit the shell (as expected) the majority of the time. But, if an extension happens to register before the query results come back, the shell process just hangs and you have to CTRL+C (usually twice) to get out of it.

I’m running a build from source on Windows 10 with the latest master branch, but I’m not sure how long the issue has actually been in the codebase

### What operating system and version are you using?

```
 version = 10.0.17763
   build = 17763
platform = windows
```

### What version of osquery are you using?
```
version = 4.0.2-2-g65aca42e
```

### What steps did you take to reproduce the issue?
1) Make sure that there is at least 1 extension in the `extensions.load` file. I used https://github.com/trailofbits/osquery-extensions but any well-behaved extension should work to reproduce the issue.
2) Stop the `osqueryd` service (if it is installed as a service)
3) From the command line, run the following query:
```
osqueryd.exe --S --verbose "SELECT version FROM osquery_info;"
```
4) If the extension does not register before the query results come back, then the process terminates normally (so go back to step 3). However, if the extension does register, then after query results are returned, the process just hangs and multiple `CTRL+C` key presses are required to terminate it.

### What did you expect to see?
I would expect the process to terminate normally regardless of whether or not extensions are registered.

### What did you see instead?
In the case when extensions register before query results are returned, the process just hangs and multiple `CTRL+C` key presses are needed to terminate the process.

**Comment by theopolis** [comment]
Interesting, @chrisbroome, I did a lot of work to refactor the shutdown logic. Do you mind checking if 4.4.0 still has this issue?

**Comment by chrisbroome** [comment]
I haven't been able to reproduce this with 4.4.0. I'll close the issue.
