### ISSUE TITLE
Update website to mention 4.0.2 release

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#5813]
# Task

1. https://osquery.io/downloads  update this page to point to 4.0.2
2. https://osquery.io/blog/official-news add a short blurb to announce 4.0.2
3. Add "update the website" to the checklist for "how to cut a release" if we have such a list

**Comment by zwass** [comment]
1. Has already been completed by @theopolis (https://github.com/osquery/osquery-site/pull/150).
2. I just submitted a PR for this (https://github.com/osquery/osquery-site/pull/152).
3. Let's open a separate issue for a release checklist? Unless someone else is aware of this existing?

**Comment by theopolis** [comment]
> Let's open a separate issue for a release checklist? Unless someone else is aware of this existing?

One option is to use an issue template. When you go to make a new release, open an issue using that template and work through the checkboxes.
