### ISSUE TITLE
Restart of osquery service leaves running osqueryd process 

### ISSUE THREAD

**Issue by itamarshpak** [osquery/osquery#5833]
# Bug report
Hey, On Windows Servers, Restarting Osquery Service doesn't kill all process of osqueryd.exe.
when the service manager stop the service, there is still orphand process of osqueryd.exe (so it does not really stop). I had to stop service, kill the process manually and start the service again. 
On linux servers all work as expected.

**Comment by theopolis** [comment]
@itamarshpak, is this with version 4.0.2?

**Comment by mike-myers-tob** [comment]
Is it the watchdog process that remains running, or is perhaps re-launching osqueryd?

It might be worth testing with the watchdog disabled:
https://osquery.readthedocs.io/en/latest/installation/cli-flags/#daemon-control-flags

**Comment by itamarshpak** [comment]
Version 3.2.2, ops, didnt see the new version, is it fixed in 4.0.2?

**Comment by muffins** [comment]
@itamarshpak yeah this was a known issue some time ago, it has been resolved in 4.0.2. Please update and feel free to re-open this issue if the problem persists!
