### ISSUE TITLE
osqueryi returns zero error code (success) when command line query fails

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#5853]
# Bug report

### What operating system and version are you using?

Windows 10 x64 RS3 (Build 1703, 16299.1392)

### What version of osquery are you using?

osqueryi 3.3.2 (shell only)

### What steps did you take to reproduce the issue?

`>.\osqueryi.exe --json "SELECT * FROM bogus_table;"`

### What did you expect to see?

>cmd\> .\osqueryi.exe --json "SELECT * FROM bogus_table;"
I1001 14:45:41.871394 14256 database.cpp:563] Checking database version for migration
I1001 14:45:41.874397 14256 database.cpp:587] Performing migration: 0 -> 1
I1001 14:45:41.875396 14256 database.cpp:619] Migration 0 -> 1 successfully completed!
I1001 14:45:41.875396 14256 database.cpp:587] Performing migration: 1 -> 2
I1001 14:45:41.876397 14256 database.cpp:619] Migration 1 -> 2 successfully completed!
[
]
Error: no such table: bogus_table

>cmd\> echo %errorlevel%
[NOT 0]

### What did you see instead?

Zero return code, which indicates success.

This same behavior applies to running queries programmatically, where GetExitCodeProcess(...) (windows API) against a finished osqueryi process will return 0.  This presents an issue for being able to determine if a query run in this manner was successful.  The only way to determine failure is to inspect stderr and either
1) Parse stderr contents
    - Undesirable, as osquery logging can/will change from build-to-build.
2) Treat any stderr content as failure

Given that we need to treat the presence of any stderr data as an error, we need to filter out warning level logs (via --logger_min_(status|stderr)=2).  For our use-case, info logging can be filtered out, but warning logs may be useful to collect (even if we still choose to treat the query as successful).

osqueryi should be returning a non-zero error code to indicate query failure (e.g., non-existent table, non-existent column, etc.).

**Comment by Zabari** [comment]
I'm thinking of tackling this issue, does anyone have a hint on where to start looking?

**Comment by directionless** [comment]
I can confirm this bug on osx, with v4. And also that it does _not_ exist in sqlite.

```shell
$ osqueryd -S  "SELECT * FROM bogus_table;"; echo $?
Error: no such table: bogus_table
0
$ osqueryd -S  "xselect 1;"; echo $?
Error: near "xselect": syntax error
0

$ sqlite3 /dev/null   "SELECT * FROM bogus_table;" ; echo $?
Error: no such table: bogus_table
1
$ sqlite3 /dev/null   "xselect 1;" ; echo $?
Error: near "xselect": syntax error
1
```

**Comment by zwass** [comment]
@Zabari https://github.com/osquery/osquery/blob/13290ed7ac4f3ce00ab07fd0389f892801752292/osquery/main/main.cpp would be a good place to start.
