### ISSUE TITLE
git submodule failure  -- "fatal: reference is not a tree"

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5862]
# Bug report

Sometimes, when trying to build on a new machine, git submodules throws up a fatal error.

The simplest test case, can be seen with:

```shell
cd /tmp
git clone https://github.com/osquery/osquery
cd osquery
git submodule update --init --depth=1 libraries/cmake/source/augeas/src
```

When this fails, you will see an error like:
```
fatal: reference is not a tree: 3775c2bf53fef5f694fcf25308cee1dfe00600c4
Unable to checkout '3775c2bf53fef5f694fcf25308cee1dfe00600c4' in submodule path 'libraries/cmake/source/augeas/src'
```

## Observations

| where | git version | result |
| -------------- | -----------| ----- |
| docker gcr.io/oss-fuzz-base/base-builder | 2.7.4 | fail |
| docker ubuntu:16.04 | 2.7.4 | fail |
| docker ubuntu:18.04 | 2.17.1 | success |
| macOS | 2.17.2 | success |
| macOS | 2.21.0 | success |
| macOS | 2.23.0 | success |

## Theory

I strongly suspect this is because cloning with `depth=1` doesn't get much for history, and commit 3775c2bf53fef5f694fcf25308cee1dfe00600c4 is quite old. It's about 2 years, and 151 commits back. 

Certainly, this behavior matches what I expect from general git use. On a current git, I can reproduce this by:
```shell
$ git clone --depth 1 git@github.com:hercules-team/augeas.git
$ cd augeas
$ git checkout 3775c2bf53fef5f694fcf25308cee1dfe00600c4
fatal: reference is not a tree: 3775c2bf53fef5f694fcf25308cee1dfe00600c4

# works if I pull the tag refs
$ git fetch -t
$ git checkout 3775c2bf53fef5f694fcf25308cee1dfe00600c4
Note: switching to '3775c2bf53fef5f694fcf25308cee1dfe00600c4'.
```

https://github.com/boostorg/boost/issues/245 seems to be much the same issue. That ticket suggests that anything prior to 2.8 is more broken. There's also a comments that ["because Github doesn't allow direct SHA fetch"](https://github.com/boostorg/boost/issues/245#issuecomment-470716527). That github comment sounds like it's references the same things https://github.com/git/git/commit/18a74a092bff41f1ffe10bd2463d3eed9a04435d is:
> This is likely to fail when the upstream repositories
submodules are cloned from a repository that is not prepared to
serve histories that ends at a commit that is not at the tip of a
branch, and we know the world is not yet ready.

My takeaway here, is that we might be fine if:
* We can assume a newer git
* _Maybe_ if we use newer versions

And if those don't help, we're probably going to need to think harder

**Comment by directionless** [comment]
I spent a couple minutes staring at the git traces (as created with `GIT_CURL_VERBOSE=1 GIT_TRACE=2`) the working case does a bunch of `git rev-list` and some additional fetches before trying to checkout. 

Ultimately, they both do a `git checkout -f -q 3775c2bf53fef5f694fcf25308cee1dfe00600c4` which I think supports my theory above.

**Comment by theopolis** [comment]
I tried bisecting `git` and seeing where our assumption about shallow clones pointing to GitHub tag references fails, and it is https://github.com/git/git/commit/34066f06614d6dbc1955c92ba0c3a17dbfeb0077#diff-7891df559f581cdcc9168363e0f932a1

**Comment by directionless** [comment]
## Conclusion

Huge effort from a bunch of us, I'm going to try to summarize:
* As @theopolis found, this is an intentional change by the git team
* Anything newer than git 2.18 will not behave as we previously required
* At least, when using the first version of the protocol
* Luckily, we can specify protocol v2
* But not for gitlab
* https://public-inbox.org/git/20191013064314.GA28018@sigill.intra.peff.net/  is the result of a mailing list thread

So, @zwass updated the cmake tools to add the protocol specifier, and to not shallow clone the gitlab repos.

If we find performance impacts from the non-shallow clones, we'll have to investigate options. Perhaps mirroring to github.

Fixed By: https://github.com/osquery/osquery/pull/5897

**Comment by zwass** [comment]
Small correction ^ It's git versions newer than **2.22** that cause the problem.

**Comment by directionless** [comment]
Updated, thanks!
