### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by kouzhudong** [osquery/osquery#5877]
# Bug report

301>D:\code\git\osquery\osquery\tables\sleuthkit\sleuthkit.cpp(15,10): fatal error C1083: 无法打开包括文件: “tsk/libtsk.h”: No such file or directory
301>已完成生成项目“osquery_tables_sleuthkit_sleuthkittable.vcxproj”的操作 - 失败。
321>D:\code\git\osquery\osquery\tables\lldpd\lldp_neighbors.cpp(18,10): fatal error C1083: 无法打开包括文件: “lldp-const.h”: No such file or directory

**Comment by muffins** [comment]
@kouzhudong can you provide more details? I'm currently able to successfully build for Windows off of master, not hitting these issues. Have you tried removing your CMake build directory and re-generating the solution, then rebuilding?

**Comment by muffins** [comment]
I'm going to close this out, as builds on master are working currently for both cmake and buck. Feel free to open if you have more questions!
