### ISSUE TITLE
Missing deserialization support for `QueryLogItem`

### ISSUE THREAD

**Issue by kumarak** [osquery/osquery#5878]
# Feature request

The deserialization functions (`deserializeQueryLogItemJSON`, `deserializeQueryLogItem`) for the `QuearyLogItem` are lost in the refactoring. It was helpful for the extension developer to look into the snapshot queries and log them. 
 
With missing deserialization support, the extension will have to deserialize the string of their own after the usage of osquery serialization API's (`serializeQueryLogItemJSON`, `serializeQueryLogItem`).

**Comment by directionless** [comment]
In office hours 2019-10-15 this was discussed. It was concluded that we do not think this should be in core, and removing them is correct. Extensions should implement what they need.
