### ISSUE TITLE
Revisit http_client and the changes in #5606 to check IPv6 compatibility

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5883]
There might have been regressions in IPv6 compatibility with #5606. The good news is that newer beast/boost APIs should restore this so we should avoid a revert.

I suspect some of our previous tests that may have detected this are also disabled.

Additionally, I added some questions to the merged PR about inconsistencies in dispatching an `async_wait`.

**Comment by uptycs-nishant** [comment]
@theopolis , I believe #5606 does not do anything to break IPv6 compatibility. If it is broken, it was broken already.

**Comment by theopolis** [comment]
I'm just leaving a note for myself to investigate. I brought the changes over to an internal repo where the tests run on IPv6-only hosts and it started to fail tests that we're working before. I was able to get it working after a lot of trial and error. This issue is also a reminder for me to bring those changes back to GitHub.

**Comment by uptycs-nishant** [comment]
let me know if I may assist you in anyway?
