### ISSUE TITLE
Apple Notarization

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5894]
This is a reminder to myself to dump notes about apple notarization in here.

Relates to: #5689 

cc: @sharvilshah @groob @alessandrogario

**Comment by directionless** [comment]
Notarization is part of apple's current security thing. It's an asynchronous malware scanning process.

The basic workflow is that at _build_ and _package_ time the developer submits the thing to apple for scanning. Apple then passes judgement. If a thing passes, the developer _may_ download a ticket (certificate) indicating it's passed, and staple this ticket to the thing. 

At runtime, for things that have a quarantine bit set (set by things like web browsers, but not command line tools), gatekeeper will check whether it's notarized. If the ticket is stapled, this is an offline check. If there is no ticket stapled, gatekeeper will reach out to apple's servers to verify

-----

You may need a different codesign options. I'm playing with:
```
codesign --force -s "${CODESIGN_IDENTITY}" -v --options runtime --timestamp ./build/darwin/launcher
```

To see what the state of a thing is (for basically any kind of thing):
```
spctl -a -vvv -t install </path/to/file>
```

To submit:
```
xcrun altool --username seph@directionless.org --password @env:N_PASS --asc-provider X98UFR7HA3 --output-format xml --notarize-app ~/Downloads/launcher_0.10.3.zip
```

To Check the status:
```
xcrun altool --username seph@directionless.org --password @env:N_PASS --asc-provider X98UFR7HA3 --output-format xml --notarization-info 1ebba2e2-5b86-49f5-a74d-602a75dc30d2
```

**Comment by gavinelder** [comment]
Small comment I see https://github.com/osquery/osquery/pull/6467 looks to query using the EndpointSecurity framework this would require the osquery foundation to apply separately for the [Endpoint Security Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_endpoint-security_client)  and pass some additional build arg's to apply it to the pkg.

**Comment by directionless** [comment]
The codesign repo does this
