### ISSUE TITLE
Improve reliability of the deb_packages test

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#5917]
https://github.com/osquery/osquery/blob/master/tests/integration/tables/deb_packages.cpp

The test, among other things, controls for the presence of `linux-base`, `linux-firmware`, `linux-generic` packages, but in some cases either they are not present, or they have a different name.

For instance in a Docker container none of those are present, in fact a workaround we use right now for our CI is to install those three as empty/fake packages.

On Ubuntu `linux-generic` is not the only provider of a kernel image, one could also install `linux-generic-hwe`; the test would fail when doing so.

**Comment by Hizees** [comment]
NO! NO! NO!------------------ 原始邮件 ------------------
发件人: "JGbooks"<notifications@github.com>
发送时间: 2019年10月21日(星期一) 晚上10:42
收件人: "osquery/osquery"<osquery@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [osquery/osquery] Improve reliability of the deb_packages test(#5917)



The test, among other things, controls for the presence of linux-base, linux-firmware, linux-generic packages, but in some cases either they are not present, or they have a different name.
 
For instance in a Docker container none of those are present, in fact a workaround we use right now for our CI is to install those three as empty/fake packages.
 On Ubuntu linux-generic is not the only provider of a kernel image, one could also install linux-generic-hwe and the test would fail.
 
&mdash;

**Comment by howar6hill** [comment]
@Smjert Should the absence of linux-base, linux-firmware, linux-generic packages be allowed? If so, I will work on this issue.
