### ISSUE TITLE
Configurable Audit backlog limit setting on Linux

### ISSUE THREAD

**Issue by alessandrogario** [osquery/osquery#5921]
The Audit backlog limit on Linux is currently hardcoded:

https://github.com/osquery/osquery/blob/444b2cc017218d2ac4c25ab1e431be809e744821/osquery/events/linux/auditdnetlink.cpp#L308

A command line option could be implemented to make this configurable

**Comment by r-a303931** [comment]
Do you mind if I take a look at this?

**Comment by directionless** [comment]
@r-a303931 By all means!

**Comment by ikoniaris** [comment]
@r-a303931 https://github.com/osquery/osquery/issues/5930 is a related one.

**Comment by jagij** [comment]
Looks like this one is already fixed by #5953.

Current code:
https://github.com/osquery/osquery/blob/c799afbf91a6269fb3c058ceb614817f8bc5277a/osquery/events/linux/auditdnetlink.cpp#L336
