### ISSUE TITLE
virtual tables : log warning when table does not implement an advertised index

### ISSUE THREAD

**Issue by packetzero** [osquery/osquery#5922]
# Feature request

### What new feature do you want?

Currently it's possible for a table to advertise an INDEX column without implementing it in code.  If possible, let's log a WARNING message when detected.

### How is this new feature useful?

It will help us catch situations where JOIN or IN() will result in table scans for every constraint value.

### How can this be implemented?

in osquery/sql/virtual_table.cpp , if index constraints are passed to generate() and operators are all EQUALS, the number of rows should be 0 or 1.

**Comment by packetzero** [comment]
relates to https://github.com/osquery/osquery/issues/5675

**Comment by theopolis** [comment]
Be careful, there are quite a few tables that could never do this, but you still want the `JOIN/IN` functionality. A potential balance might be in `--verbose` mode only.

**Comment by packetzero** [comment]
augeas is one such table.
