### ISSUE TITLE
Add Ubuntu 18.04 to the deb repository

### ISSUE THREAD

**Issue by alessandrogario** [osquery/osquery#5925]

**Comment by theopolis** [comment]
Not sure what this means? You can add the general APT repo to a Ubuntu 18.04 machine. See the instructions here: https://osquery.io/downloads/official/4.0.2

For easy reference:
```
export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $OSQUERY_KEY
sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
sudo apt-get update
sudo apt-get install osquery
```

**Comment by alessandrogario** [comment]
I opened the issue in respose to a user claiming the packages didn't show up on bionic; good to know it actually works!
