### ISSUE TITLE
Configurable audit backlog wait time setting on Linux 

### ISSUE THREAD

**Issue by ikoniaris** [osquery/osquery#5930]
# Feature request

### What new feature do you want?

The ability to configure the audit_backlog_wait_time value. 

References:
[1] http://man7.org/linux/man-pages/man3/audit_set_backlog_wait_time.3.html
[2] https://github.com/torvalds/linux/blob/master/kernel/audit.c#L121-L122

Currently the value is hardcoded to 1 in the code: https://github.com/osquery/osquery/blob/master/osquery/events/linux/auditdnetlink.cpp#L307
`  audit_set_backlog_wait_time(audit_netlink_handle_, 1); `

This has been discussed by @theopolis in https://github.com/osquery/osquery/issues/3148

### How is this new feature useful?

Based on a couple of online﻿ discussions﻿ it seems like for specific kernel versions setting this value to a number will lead to the kernel blocking the thread that invoked the syscall if the audit consumer (osquery) can't keep up and the backlog is reached. Setting the parameter to 0 ensures nothing gets blocked in the kernel. Bear in mind that this is not supported in all kernels so its effectiveness can vary. 

References:
[1] https://github.com/elastic/go-libaudit/issues/34
[2] https://github.com/elastic/beats/issues/7157

**Caveat**: this could be specific to the Beats product by Elastic, and osquery could work OK with a value of 1.  But, auditd itself sets it to 0 on a my Ubuntu 18.04 LTS that I've just tested it. 

### How can this be implemented?

Change the backlog wait time from 1 to 0, or even better keep a default and then expose this value as parameter that can be set via the CLI and a configuration option so that users can pick their own. Should be implemented similar to #5921.

**Comment by ikoniaris** [comment]
This could be split into two issues; 1) change the parameter from 1 to 0 following auditd's example and/or based on the issue linked from the Elastic, 2) parameterize this value regardless of its default value

**Comment by theopolis** [comment]
I can split the issues out!
