### ISSUE TITLE
atom_packages table does not produce results after running the query once

### ISSUE THREAD

**Issue by terracatta** [osquery/osquery#5933]
# Bug report

### What operating system and version are you using?

macOS 

version = 10.15
   build = 19A602
platform = darwin

### What version of osquery are you using?

version = 4.0.2
### What steps did you take to reproduce the issue?

1. Ensure you have Atom.app installed with some packages
1. Open osqueryi 
1. Execute the query `select * from atom_packages;` (note the number of results)
1. Execute the query `select * from atom_packages;` again.

### What did you expect to see?

I expect to see the same number of results as the first invocation.

### What did you see instead?

No results.

### Other notes

Restarting the osquery process results in the behavior being reset. Running a distributed query on osqueryd results in only the first query returning results until osqueryd is restarted.

Running osqueryi in verbose mode did not produce any actionable logs.

**Comment by theopolis** [comment]
The bug is because `endpwent` is not called. It looks like this table should make use of the users-enumeration utilities since it is parsing content per-user.
