### ISSUE TITLE
Find a ccache replacement for windows

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5967]
The windows builds have gotten very slow. This is because we're rebuilding the AWS EC2 sdk each time. This requires a lot of ram, and as the CI machines are small it's a fairly slow process.

In office hours on 2019-10-29, we discussed how this problem only manifests on windows, because there is no ccache. There's some interest in finding a ccache equivalent for msbuild

Cc: @alessandrogario @Smjert @muffins 

Relates to: #5968

**Comment by directionless** [comment]
Forgive me for sending y'all the obvious internet link, but have you seen https://github.com/frerich/clcache

**Comment by Smjert** [comment]
> Forgive me for sending y'all the obvious internet link, but have you seen https://github.com/frerich/clcache

I've seen it, though I didn't try it. My only concern is how production ready really is vs something that's more for smaller scoped projects, non-security involved projects or individual devs.
When adding a layer that caches objects I'm always a bit worried of bugs from it, which retrieves an object that work/link but it's not the correct one.

I know we are not at the level of Chromium, but this is relevant https://github.com/frerich/clcache/issues/347

**Comment by mike-myers-tob** [comment]
Fixed in https://github.com/osquery/osquery/pull/6231
