### ISSUE TITLE
Blueprint: Implementing generic container support

### ISSUE THREAD

**Issue by alessandrogario** [osquery/osquery#5975]
## Description
This blueprint is about improving container introspection within osquery for non-evented tables.

In my opinion, the ideal solution should:

1. Cover as many tables as possible, using a common query syntax.
2. Maximize code re-use, without re-implementing existing functionality we already have when accessing the host.
3. Keep complexity low: avoid different code paths when accessing a container vs the host

Most of the information we are interested in are fully available by accessing the filesystem, but there are some problems:
1. Accessing container storage is hard; some storage engines (such as overlayfs) are easy to work with, but others (such as devicemapper) are completely opaque
2. Data is fragmented, usually on multiple layers
3. Some resources, such as /proc, are not accessible
4. It's not easy to update the tables to make them work with container storage

## Proposed solution

1. Implement a common constraint to reference containers
2. Integrate the new constraint to compatible tables
3. When a query hits a table and the constraint is set, join the container's mount namespace
4. Run the table code

This mechanism would allow tables to work out of the box within the context of the specified container. Since we also get access to /proc, we can cover many usages.

Here are some of the tables that could easily benefit from such feature:

1. apt_sources
2. authorized_keys
3. curl_certificate
4. deb_packages
5. rpm_packages
6. npm_packages
7. python_packages
8. file
9. hash
10. os_version
11. processes
12. shell_history
13. process_open_files
14. more!

## Implementation details

Since it is not possible to join a mount namespace if there are multiple threads running, our only choice is to fork. The child process would then join the container's namespace and run the table code. If no container needs to be referenced, the table code can be run directly.

Once the fork happens, the environment (i.e. process state) in which the table code is run is unknown; it is then best to move all the code referenced by tables inside a completely isolated library (which can live inside the same repository). Migration doesn't have to happen all at once; I would suggest to port one table at a time. The most important goal for this library is to avoid using and depending on global state.

From the child process, it is no longer possible to directly access the osquery code base; this is also valid for things like logging. It would be best to implement a communication channel that can support both results and logging information in case error messages need to be logged.

**Comment by packetzero** [comment]
When you say `Since it is not possible to join a mount namespace if there are multiple threads running, our only choice is to fork`.  The scheduler is single threaded, which means that only a single query is in progress at a given time.

**Comment by alessandrogario** [comment]
> When you say `Since it is not possible to join a mount namespace if there are multiple threads running, our only choice is to fork`. The scheduler is single threaded, which means that only a single query is in progress at a given time.

It is not a synchronization issue, but a limit imposed by the kernel; it is not possible to use the setns syscall with the parameters we need (mount namespace) unless we have exactly one thread inside the calling process. Depending on the kernel version, even threads that have been terminated but have not been joined will prevent this operation.

**Comment by directionless** [comment]
I think this has merged, so I'm closing this. Feel free to reopen if needed
