### ISSUE TITLE
cannot build via cmake on Windows with a space in username

### ISSUE THREAD

**Issue by keeleysam** [osquery/osquery#5986]
# Bug report

osquery cannot be built with the supported workflow via cmake on Windows if you've gone through the setup assistant and created a user like a normal person.  this probably isn't an issue on computers which are AD bound and don't have spaces in usernames, and isn't an issue for users who only provide one name at the setup assistant.

i think this was an issue before the build system got redone too, but probably in separate places.

### What operating system and version are you using?

windows 10 1903 64 bit

### What version of osquery are you using?

4.1.0

### What steps did you take to reproduce the issue?

- install windows 10
- create a user during the setup assistant with a space in it, like your real name.  use that user for the rest of it.
- install dependencies as required
- build with `cmake --build . --config RelWithDebInfo -j10` as documented

### What did you expect to see?
osquery builds

### What did you see instead?
it errors out on at least one formula, the openssl one.   example from error:
```
cl : Command line warning D9024: unrecognized source file type 'Keeley/osquery/build/libs/fb/zlib/zlib/1.2.11/include', object file assumed [C:\Users\Samuel Keeley\osquery\build\openssl\openssl.vcxproj]
cl : Command line warning D9027: source file 'Keeley/osquery/build/libs/fb/zlib/zlib/1.2.11/include' ignored [C:\Users\Samuel Keeley\osquery\build\openssl\openssl.vcxproj]
  c_zlib.c
```

**Comment by mike-myers-tob** [comment]
Steps to reproduce (on Windows 10, user that can build osquery successfully):
1. Created a new admin user with a space in the name
2. Logged in as that user, reinstalled Python 3 dependency so the new user would have it
3. Deleted osquery/build folder and recreated it
4. In an admin Powershell, `cd build`
5. `cmake -G "Visual Studio 16 2019" -A x64 -T v141 ..`
6. `cmake --build . --config RelWithDebInfo -j10`

Everything built successfully. I think the changes to the CMake files, including to the OpenSSL formula in particular, might have fixed this issue.

**Comment by mike-myers-tob** [comment]
Closing as fixed, but reopen if needed. Thanks
