### ISSUE TITLE
osquery v4 breaks compatibility with older macOS

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5993]
I don't know if this is intentional, or accidental, but the v4 osquery builds break runtime compatibility with older OSes. It seems to require High Sierra or newer.

On an older machine, we get:
```
MacBook-Pro:osquery casper$ ./osqueryd-4.0.2 --pidfile /tmp/o.pid --database_path=/tmp/o.db
dyld: lazy symbol binding failed: Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/casper/Downloads/osquery/./osqueryd-4.0.2 (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Users/casper/Downloads/osquery/./osqueryd-4.0.2 (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

From a test El Capitan machine:

<img width="1312" alt="Screen Shot 2019-11-04 at 2 57 23 PM" src="https://user-images.githubusercontent.com/179542/68153676-f1efd900-ff13-11e9-9f17-9450e7d98ad5.png">

**Comment by alessandrogario** [comment]
Assuming this is related to the selected SDK version, you are completely right. We have changed this without notice.

Here's a snippet from the 3.3.x build system:

```
  if(DEFINED ENV{OSX_VERSION_MIN})
    set(OSX_VERSION_MIN "$ENV{OSX_VERSION_MIN}")
  elseif(DEFINED ENV{OSX_VERSION_NATIVE})
    set(OSX_VERSION_MIN "${OSQUERY_BUILD_DISTRO}")
  else()
    set(OSX_VERSION_MIN "10.11")
  endif()

  add_compile_options(
    -mmacosx-version-min=${OSX_VERSION_MIN}
  )
```

I remember many people complaining that 10.11 was too old; what's the minimum version we should use in your opinion?

**Comment by directionless** [comment]
Tough call. I'd like to say we should only support the recent releases. But, I think we'd do better to try to support more things. We do this for linux, after all.

Do we know if there's a downside to adding that back? If nothing breaks, we should probably just do it.

My fear is that we're going to be fighting apple here

**Comment by Smjert** [comment]
Well the difference with Linux though is that there's a bit less that's actually downgraded.
You can still use the latest libraries, they just need to be compiled with an older glibc.

To select and older deployment target one can set `CMAKE_OSX_DEPLOYMENT_TARGET=<osx version>`.

**Comment by Smjert** [comment]
There's also another reason: the pre-built libraries have been compiled targeting 10.14, so until we move to everything being compiled from source, I don't think we can properly support older versions.

**Comment by directionless** [comment]
I tried running a build (on my mojave) machine using:
```
mkdir build-old
cd build-old
export CMAKE_OSX_DEPLOYMENT_TARGET=10.11
cmake ../
make -j8
```

It took a long time to compile the aws sdk. The resulting binary has the same error.

**Comment by directionless** [comment]
I don't really understand the tradeoffs about what version of the mac SDK we use. I expect there are users stuck on old OSes. But, we also will someday want the new SDK.

**Comment by Smjert** [comment]
> I tried running a build (on my mojave) machine using:
> 
> ```
> mkdir build-old
> cd build-old
> export CMAKE_OSX_DEPLOYMENT_TARGET=10.11
> cmake ../
> make -j8
> ```
> 
> It took a long time to compile the aws sdk. The resulting binary has the same error.

That is a CMake variable, you have to pass it with `-D` when configuring with CMake.
But again, I don't think it will work properly anyway due to the pre-built libraries.

**Comment by theopolis** [comment]
We haven’t shipped the release packages yet so if there’s a CMake-configure fix we can apply that for 4.1.0. I’d like to see safe-defaults in code so we could fix in master (if possible) and plan to publish a 4.1.1.

**Comment by theopolis** [comment]
This was built with `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.11`, does it work for you @directionless?
[osquery-4.1.0.pkg.zip](https://github.com/osquery/osquery/files/3807180/osquery-4.1.0.pkg.zip)

**Comment by directionless** [comment]
I can't test till I'm back in the office tomorrow -- I don't have anything old enough at my house.

**Comment by directionless** [comment]
I'm back in the office, where I have an El Capitan machine. 

Your attached build works on it. As did my build using `cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 ../ && make -j8`

I'm not sure if there's a downside to using this. I've pushed it out to my test hosts
