### ISSUE TITLE
Syslog - Could not open output pipe - Permission denied

### ISSUE THREAD

**Issue by hackdefendr** [osquery/osquery#5994]
# Bug report

### What operating system and version are you using?

  Red Hat Enterprise Linux Server release 7.7 (Maipo)

### What version of osquery are you using?

  4.0.2

### What steps did you take to reproduce the issue?

1. Using the provided documentation, I configured osquery to pipe through syslog
2. Pipe path configured as /tmp/syslog_pipe
3. Restart OSQuery and Rsyslog
4. Pipe file is created

  pr--rw----. 1 root root      0 Nov  4 14:57 syslog_pipe

5. Error in Rsyslog:

  rsyslogd[21830]: Could not open output pipe '/tmp/syslog_pipe':: Permission denied [v8.24.0-41.el7_7.2 try http://www.rsyslog.com/e/2039 ]

### What did you expect to see?

I expected to see Rsyslog start up normally and for OSQuery to pipe events through the created syslog_pipe.

### What did you see instead?

See error above in number 5.

**Comment by directionless** [comment]
What piece of documentation are you following?

Are you trying to query syslog from inside osquery, or are you trying to output osquery results to syslog?

**Comment by hackdefendr** [comment]
I was following this: https://osquery.readthedocs.io/en/latest/deployment/syslog/

I am trying to output osquery to syslog with the --enable-syslog flag set.

Basically it appears that there is a bug in how the syslog pipe is created.  It doesn't allow rsyslog to read/write. I tried manually changing permissions and ownership on the pipe and that doesn't work.

**Comment by directionless** [comment]
The doc you link, and the `--enable-syslog` flag are about _consuming_ syslog. Having osquery ingest events sent to it via syslog. The documentation is a bit thin on permissions, but it depends a lot on the exact setup. It says:
> Permissions for the pipe must at least allow rsyslogd to read/write, and osquery to read. For security, it is advised that the least possible privileges are enabled to allow this.

And the rest is left to the reader

----

But, you're saying you want osquery to _output_ to syslog. That would go through the logging system, discussed in https://osquery.readthedocs.io/en/latest/deployment/logging/ I believe you would want `--logger_plugin syslog`

**Comment by hackdefendr** [comment]
Maybe you are correct...Here is what we are trying to do.

Collect all logging, system info and command line included, and centralize those logs to be sent to our SIEM.  Right now this project is only for our linux systems, but if we can get this to work we may extend to our Windows workstations.

I was told that OSQuery was the way to go.

BTW selinux was the culprit.  Once I disabled that, rsyslog was able to talk to the syslog pipe.  But now that I have that working I see I may have approached this from the wrong direction.

**Comment by directionless** [comment]
osquery can be one component of that, yes. Though how all the pieces fit together can be a bit convoluted.

A common pattern is to have syslog forward to an SIEM. And then osquery either forward to syslog, or directly to the SIEM ingest. 

You may find https://blog.securelyinsecure.com/post/osquery-splunk-and-beyond/ interesting.

It does not sound like there's an osquery bug here, so I'm going to close this

**Comment by theopolis** [comment]
Feel free to bring discussion about your deployment / questions to Slack!
