### ISSUE TITLE
duplicated logs in osqueryd.results.log

### ISSUE THREAD

**Issue by thuhak** [osquery/osquery#5999]
# Bug report

### What operating system and version are you using?

 version = CentOS Linux release 7.6.1810 (Core)
   build =
platform = rhel

### What version of osquery are you using?

version = 4.0.2

### What steps did you take to reproduce the issue?

config.file
```
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10
  },

  "schedule": {
    "login": {
      "query": "SELECT username, time, CASE WHEN host='' THEN 'local' ELSE `host`  END  as host FROM last WHERE type=7;",
      "interval": 10,
      "remove": false
    }
  }
}
```

```bash
systemctl start osqueryd
```

### What did you expect to see?

one login message should be saved in log file just once. 

### What did you see instead?

```bash
grep '{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"}' osqueryd.results.log
```

```
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:43:50 2019 UTC","unixTime":1572939830,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:51:32 2019 UTC","unixTime":1572940292,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:52:27 2019 UTC","unixTime":1572940347,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:53:15 2019 UTC","unixTime":1572940395,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:55:03 2019 UTC","unixTime":1572940503,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:00:09 2019 UTC","unixTime":1572940809,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:05:06 2019 UTC","unixTime":1572941106,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:10:03 2019 UTC","unixTime":1572941403,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:15:10 2019 UTC","unixTime":1572941710,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:20:07 2019 UTC","unixTime":1572942007,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:25:04 2019 UTC","unixTime":1572942304,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:30:10 2019 UTC","unixTime":1572942610,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:35:07 2019 UTC","unixTime":1572942907,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:40:04 2019 UTC","unixTime":1572943204,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:45:10 2019 UTC","unixTime":1572943510,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:50:07 2019 UTC","unixTime":1572943807,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:55:04 2019 UTC","unixTime":1572944104,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:00:10 2019 UTC","unixTime":1572944410,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:05:07 2019 UTC","unixTime":1572944707,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:10:04 2019 UTC","unixTime":1572945004,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:15:10 2019 UTC","unixTime":1572945310,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:20:07 2019 UTC","unixTime":1572945607,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:25:04 2019 UTC","unixTime":1572945904,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:30:10 2019 UTC","unixTime":1572946210,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:35:07 2019 UTC","unixTime":1572946507,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:40:04 2019 UTC","unixTime":1572946804,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
{"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:45:10 2019 UTC","unixTime":1572947110,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
```

**Comment by theopolis** [comment]
Interesting, I tested locally and `osqueryd` is working as expected. Notice in your logs that you are seeing a new event between 5 minute periods, `Tue Nov  5 09:40:04 2019 UTC` and `Tue Nov  5 09:45:10 2019 UTC`. Since you are not logging the 'removed' events you are possibility missing that you have logged out-then-in during that period. The table will still notice this but due to your configuration it will only logged the 'added' events.

**Comment by lhtest429** [comment]
we suffer the same problem
is that the "epoch" reset to "0" or "counter" reset to "0"?

**Comment by lhtest429** [comment]
> # Bug report
> ### What operating system and version are you using?
> version = CentOS Linux release 7.6.1810 (Core)
> build =
> platform = rhel
> 
> ### What version of osquery are you using?
> version = 4.0.2
> 
> ### What steps did you take to reproduce the issue?
> config.file
> 
> ```
> {
>   "options": {
>     "host_identifier": "hostname",
>     "schedule_splay_percent": 10
>   },
> 
>   "schedule": {
>     "login": {
>       "query": "SELECT username, time, CASE WHEN host='' THEN 'local' ELSE `host`  END  as host FROM last WHERE type=7;",
>       "interval": 10,
>       "remove": false
>     }
>   }
> }
> ```
> 
> ```shell
> systemctl start osqueryd
> ```
> 
> ### What did you expect to see?
> one login message should be saved in log file just once.
> 
> ### What did you see instead?
> ```shell
> grep '{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"}' osqueryd.results.log
> ```
> 
> ```
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:43:50 2019 UTC","unixTime":1572939830,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:51:32 2019 UTC","unixTime":1572940292,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:52:27 2019 UTC","unixTime":1572940347,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:53:15 2019 UTC","unixTime":1572940395,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:55:03 2019 UTC","unixTime":1572940503,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:00:09 2019 UTC","unixTime":1572940809,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:05:06 2019 UTC","unixTime":1572941106,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:10:03 2019 UTC","unixTime":1572941403,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:15:10 2019 UTC","unixTime":1572941710,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:20:07 2019 UTC","unixTime":1572942007,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:25:04 2019 UTC","unixTime":1572942304,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:30:10 2019 UTC","unixTime":1572942610,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:35:07 2019 UTC","unixTime":1572942907,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:40:04 2019 UTC","unixTime":1572943204,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:45:10 2019 UTC","unixTime":1572943510,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:50:07 2019 UTC","unixTime":1572943807,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:55:04 2019 UTC","unixTime":1572944104,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:00:10 2019 UTC","unixTime":1572944410,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:05:07 2019 UTC","unixTime":1572944707,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:10:04 2019 UTC","unixTime":1572945004,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:15:10 2019 UTC","unixTime":1572945310,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:20:07 2019 UTC","unixTime":1572945607,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:25:04 2019 UTC","unixTime":1572945904,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:30:10 2019 UTC","unixTime":1572946210,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:35:07 2019 UTC","unixTime":1572946507,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:40:04 2019 UTC","unixTime":1572946804,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:45:10 2019 UTC","unixTime":1572947110,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> ```

你怎么解决的？我也发现这个问题了?
how you solve the problem?

**Comment by theopolis** [comment]
@lhtest429, did you read my comment here: https://github.com/osquery/osquery/issues/5999#issuecomment-549838838

Are you sure this does not apply to your setup?

**Comment by lhtest429** [comment]
@theopolis ，actually i use this query:
> {
           "query": "select authorized_keys.key,users.username from users join authorized_keys using (uid);",
           "interval": 60,
           "removed": false
}

osquery.flag:


>  --config_refresh=300
 --config_accelerated_refresh=120
 --host_identifier=uuid
 --disable_events=false
--disable_audit=false
--audit_allow_process_events=true
--audit_allow_sockets=true
--audit_allow_config=true

i never modify the authorized_keys, but it still generate the log in osquery.result.log.(list all the users authorized_keys). Just like using the "snapshot" mode.

![image](https://user-images.githubusercontent.com/12692169/83001030-be0a0b80-a03d-11ea-8ae7-9724a2818c49.png)

i found "count" always be 0.

To be compared, i try on another machine. Suprised!!!, it works well. The "count" is rising normally.

I do not know the reason. Another machine is still be wrong.

**Comment by theopolis** [comment]
Are there any status logs indicating a problem reading the RocksDB database?

Here is an example where I am deliberately setting the database to an incorrect path:
```
$ osqueryd --database_path /dev/null --verbose
I0531 23:06:31.775507 146173376 rocksdb.cpp:125] Opening RocksDB handle: /dev/null
I0531 23:06:31.775830 146173376 rocksdb.cpp:142] Rocksdb open failed (5:0) IO error: `/dev/null' exists but is not a directory
I0531 23:06:31.775840 146173376 rocksdb.cpp:150] Opening RocksDB failed: Continuing with read-only support
I0531 23:06:31.775856 146173376 database.cpp:568] Checking database version for migration
I0531 23:06:31.776253 146173376 database.cpp:592] Performing migration: 0 -> 1
E0531 23:06:31.776355 146173376 init.cpp:415] Failed to upgrade database
```

If you see anything similar, then osquery might fail to record the initial state of your queries.

**Comment by thuhak** [comment]
> > # Bug report
> > ### What operating system and version are you using?
> > version = CentOS Linux release 7.6.1810 (Core)
> > build =
> > platform = rhel
> > ### What version of osquery are you using?
> > version = 4.0.2
> > ### What steps did you take to reproduce the issue?
> > config.file
> > ```
> > {
> >   "options": {
> >     "host_identifier": "hostname",
> >     "schedule_splay_percent": 10
> >   },
> > 
> >   "schedule": {
> >     "login": {
> >       "query": "SELECT username, time, CASE WHEN host='' THEN 'local' ELSE `host`  END  as host FROM last WHERE type=7;",
> >       "interval": 10,
> >       "remove": false
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > ```shell
> > systemctl start osqueryd
> > ```
> > 
> > 
> > ### What did you expect to see?
> > one login message should be saved in log file just once.
> > ### What did you see instead?
> > ```shell
> > grep '{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"}' osqueryd.results.log
> > ```
> > 
> > 
> > ```
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:43:50 2019 UTC","unixTime":1572939830,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:51:32 2019 UTC","unixTime":1572940292,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:52:27 2019 UTC","unixTime":1572940347,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:53:15 2019 UTC","unixTime":1572940395,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 07:55:03 2019 UTC","unixTime":1572940503,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:00:09 2019 UTC","unixTime":1572940809,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:05:06 2019 UTC","unixTime":1572941106,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:10:03 2019 UTC","unixTime":1572941403,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:15:10 2019 UTC","unixTime":1572941710,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:20:07 2019 UTC","unixTime":1572942007,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:25:04 2019 UTC","unixTime":1572942304,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:30:10 2019 UTC","unixTime":1572942610,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:35:07 2019 UTC","unixTime":1572942907,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:40:04 2019 UTC","unixTime":1572943204,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:45:10 2019 UTC","unixTime":1572943510,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:50:07 2019 UTC","unixTime":1572943807,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 08:55:04 2019 UTC","unixTime":1572944104,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:00:10 2019 UTC","unixTime":1572944410,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:05:07 2019 UTC","unixTime":1572944707,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:10:04 2019 UTC","unixTime":1572945004,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:15:10 2019 UTC","unixTime":1572945310,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:20:07 2019 UTC","unixTime":1572945607,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:25:04 2019 UTC","unixTime":1572945904,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:30:10 2019 UTC","unixTime":1572946210,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:35:07 2019 UTC","unixTime":1572946507,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:40:04 2019 UTC","unixTime":1572946804,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > {"name":"login","hostIdentifier":"t-awsbj-salt-m01","calendarTime":"Tue Nov  5 09:45:10 2019 UTC","unixTime":1572947110,"epoch":0,"counter":0,"logNumericsAsNumbers":false,"columns":{"host":"10.110.34.87","time":"1550624855","username":"timmy.zhao"},"action":"added"}
> > ```
> 
> 你怎么解决的？我也发现这个问题了?
> how you solve the problem?

我换了其他解决方案，绕过了这个问题。
I had changed the solution to avoid this issue.
