### ISSUE TITLE
osqueryi incorrect-query user experience warnings are missing

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6001]
# Bug report

The nice-to-have, "you did not include a correct WHERE clause" warnings are missing from the shell. I should investigate why they are gone and if this is intentional. IIRC these were a feature request from several people and they were helpful in debugging unexpected behavior.

### What operating system and version are you using?

macOS, but all should be effected.

### What version of osquery are you using?

4.0.2 (breakage is between 3.x and 4.x)

### What steps did you take to reproduce the issue?

```
osquery> select * from hash;
```

### What did you expect to see?

```
osquery> select * from hash;
W1105 08:57:25.626163 205204928 virtual_table.cpp:991] Table hash was queried without a required column in the WHERE clause
W1105 08:57:25.626194 205204928 virtual_table.cpp:1002] Please see the table documentation: https://osquery.io/schema/#hash
```

### What did you see instead?

```
osquery> select * from hash;
Error: no query solution
```

**Comment by Smjert** [comment]
I noticed this too when preparing example queries for a spec/table that was missing them.
I also noticed another thing, which suggests that `required` works a bit strangely.
With the extended_attributes table (macOS), we have 2 `required` columns, `path` and `directory`.
In theory only one of those is required to have the table work; if I put nothing, it gives "Error: no query solution".
If I put `path` and point it to a folder like `/usr`, it correctly retrieves the extended attributes and shows that the directory (parent) is `/`.
Though if I put `directory` and point to `/`, no results return. Maybe it's a bug in the table, but still..

I was talking about this with @packetzero on Slack, he mentioned that some of those errors may change depending on the sqlite version.
I don't know if he had time to look deeper into why the warning that we mention in the docs is missing (but present in code).

**Comment by directionless** [comment]
Interestingly, the other `LOG(WARNING)` I can emit, does work correctly:

```
dover:x seph$ ./osqueryd-3.3.2 -S "select * from mdfind where query = 'nope'"
I1105 13:22:51.203725 155022784 database.cpp:563] Checking database version for migration
I1105 13:22:51.204025 155022784 database.cpp:587] Performing migration: 0 -> 1
I1105 13:22:51.204047 155022784 database.cpp:619] Migration 0 -> 1 successfully completed!
I1105 13:22:51.204052 155022784 database.cpp:587] Performing migration: 1 -> 2
I1105 13:22:51.204061 155022784 database.cpp:619] Migration 1 -> 2 successfully completed!
W1105 13:22:51.227705 155022784 mdfind.mm:64] nope is invalid

dover:x seph$ ./osqueryd-4.0.2 -S "select * from mdfind where query = 'nope'"
W1105 13:22:57.454342 474367424 mdfind.mm:63] nope is invalid
```

**Comment by directionless** [comment]
[`virtual_table.cpp`](https://github.com/osquery/osquery/blob/08e0b9078b23e564d5f7585bc1797f4344d058b7/osquery/sql/virtual_table.cpp#L939-L941) emits that warning. It _also_ emits a wanring if it's an events table, but events are disabled. 

The events disabled warning works:
```
dover:x seph$ ./osqueryd-4.0.2 -S "select * from process_events"
W1105 13:26:32.810897 264861120 virtual_table.cpp:930] Table process_events is event-based but events are disabled
W1105 13:26:32.810935 264861120 virtual_table.cpp:937] Please see the table documentation: https://osquery.io/schema/#process_events
```

So I suspect `required_satisfied`   is misset

**Comment by directionless** [comment]
Very oddly, I'm seeing something similar in extensions. Still debugging

**Comment by theopolis** [comment]
I cannot find a way to fix this, and by 'fix' I mean display a warning that references the table without required a required column constraint.

I believe the issue is because `xBestIndex` returns a correct `SQLITE_CONSTRAINT` when these requirements are not present. I do not recommend adding a warning in `xBestIndex` because it may be called several times during the planning. And this is not an issue of repeated warning messages, but rather SQLite may attempt a plan without the constraint and one with, and so the warning would be a false positive. 

I tried using `setTableErrorMessage` naively and that error is not propagating to where we check for query errors, the only available error is `no query solution`.

**Comment by theopolis** [comment]
See #6038 for the fix.
