### ISSUE TITLE
Cannot build on Centos 7.7

### ISSUE THREAD

**Issue by jayeye** [osquery/osquery#6013]
# Bug report

### What operating system and version are you using?

Centos 7.7, on AWS, the latest AMI that matches "CentOS*Linux*7*x86_64*HVM*EBS*ENA*1901_01*"

`
$ sudo osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = CentOS Linux release 7.7.1908 (Core)
   build =
platform = rhel
`
### What version of osquery are you using?
4.0.2. Installed the RPM from     `https://pkg.osquery.io/rpm/osquery-4.0.2-1.linux.x86_64.rpm`, and it has the correct checksum.

`
$ sudo osqueryi --line "SELECT version from osquery_info;"
version = 4.0.2
`
### What steps did you take to reproduce the issue?
On an updated Centos 7.7 machine, followed the exact instructions from `https://osquery.readthedocs.io/en/latest/development/building/` (building for Linux). The build fails at `cmake -DOSQUERY_TOOLCHAIN_SYSROOT=/usr/local/osquery-toolchain ..`
### What did you expect to see?
I expected it to build!
### What did you see instead?
```
$ cmake -DOSQUERY_TOOLCHAIN_SYSROOT=/usr/local/osquery-toolchain ..
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/local/osquery-toolchain/usr/bin/clang
-- Check for working C compiler: /usr/local/osquery-toolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/osquery-toolchain/usr/bin/clang++
-- Check for working CXX compiler: /usr/local/osquery-toolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Not found: ccache. Install it and put it into the PATH if you want to speed up partial builds.
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- osquery version: 4.1.0-11-g3c3c7a7
-- Build type: RelWithDebInfo
-- Shared libraries: OFF
-- Found Python2: /usr/bin/python2.7 (found version "2.7.5") found components:  Interpreter 
-- Found Python3: /usr/bin/python3.6 (found version "3.6.8") found components:  Interpreter 
-- Importing: facebook/markupsafe
-- Importing: facebook/jinja2
-- Importing: source/augeas
You need to run this command from the toplevel of the working tree.
CMake Error at libraries/cmake/source/modules/utils.cmake:52 (message):
  Failed to update the following git submodule:
  "/home/centos/osquery/libraries/cmake/source/augeas/src"
Call Stack (most recent call first):
  libraries/cmake/source/modules/utils.cmake:134 (initializeGitSubmodule)
  libraries/cmake/source/modules/Findaugeas.cmake:10 (importSourceSubmodule)
  CMakeLists.txt:147 (find_package)
  CMakeLists.txt:68 (importLibraries)
  CMakeLists.txt:187 (main)
-- Configuring incomplete, errors occurred!
See also "/home/centos/osquery/build/CMakeFiles/CMakeOutput.log".
```

[CMakeOutput.log](https://github.com/osquery/osquery/files/3817885/CMakeOutput.log)

Same error both at master:
`
$ git rev-parse HEAD
3c3c7a7d2951a093287f3f784198ac5b7487a415
`
and at tag 4.0.2
`
$ git rev-parse HEAD
4f9f63a667105ad6e998de5119fc1a1c09834eb8
`

**Comment by Smjert** [comment]
Thanks for you report!
Unfortunately the git version shipped by CentOS 7 is too old for the way we clone submodules (using shallow clones).
This is mentioned in the `Building with CMake` section.

It might make sense though to fallback on doing full clones and at the same time suggest of installing a newer version.

**Comment by Smjert** [comment]
Another important detail, specifically for the 4.0.2 version, is that using a git version higher than 2.22 will fail again.
I know for a fact that the version 2.17.1, which Ubuntu 18.04 uses, works correctly, I suggest to install that. But in general anything between 2.14 and 2.21 should work.

There's a workaround for git version higher than 2.22, but it might not fully work in the state 4.0.2 was in.
More info: Issue https://github.com/osquery/osquery/issues/5862, and relative PR that fixes the issue https://github.com/osquery/osquery/pull/5897

**Comment by jayeye** [comment]
Of all the things to check it did not occur to me to check the version of git.  Indeed, building and installing 2.17.1 allowed the build process to finish successfully.

**Comment by Smjert** [comment]
> Of all the things to check it did not occur to me to check the version of git. Indeed, building and installing 2.17.1 allowed the build process to finish successfully. Shall I close the issue?

Glad that it worked!
I'll close it and open an issue about having a fallback for git :).
