### ISSUE TITLE
Have submodule cloning work even when git < 2.14

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6015]
The project currently needs a git version that's 2.14 or higher to properly do shallow clones with submodules.
We do have that requirement written in the documentation, but not checked into the CMake code.

While it would be preferable to update the git version, falling back on doing full clones when the version is < 2.14 it's viable too and gives a smoother experience.
It's important though to leave a warning that mentions this and suggests updating to something newer.

Relevant code:
https://github.com/osquery/osquery/blob/11ae5a21b0f4a0142d73970d363aabcb05fafbc7/libraries/cmake/source/modules/utils.cmake#L28-L32

**Comment by Zabari** [comment]
Ah I would like to try and tackle this issue if that's alright.

**Comment by Smjert** [comment]
> Ah I would like to try and tackle this issue if that's alright.

Definitely! Thank you!
