### ISSUE TITLE
Curl table not returning results as expected

### ISSUE THREAD

**Issue by FritzX6** [osquery/osquery#6034]
The curl table seems to exhibit inconsistent behavior across different URL's. I am not sure of the cause but the URL I am attempting to reach is not located behind an authentication requirement.

# Bug report

### What operating system and version are you using?

```
+---------+--------+----------+
| version | build  | platform |
+---------+--------+----------+
| 10.15   | 19A602 | darwin   |
+---------+--------+----------+
```
### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 4.0.2   |
+---------+
```

Also checked: 
```
+---------+
| version |
+---------+
| 3.3.0   |
+---------+
```
### What steps did you take to reproduce the issue?
Attempted to use curl table to return json from Atom.io: https://atom.io/api/packages/file-icons

```SELECT * FROM curl where url = "https://atom.io/api/packages/file-icons"```

### What did you expect to see?
Results similar to when I run:
```SELECT * FROM curl where url = "https://www.google.com"```

### What did you see instead?

I see an error code:
```
osquery> SELECT * from curl where url = "https://atom.io/api/packages/file-icons";
W1111 15:50:43.593782 213499200 curl.cpp:80] tlsv1 alert internal error
+-----------------------------------------+--------+------------+---------------+-----------------+-------+--------+
| url                                     | method | user_agent | response_code | round_trip_time | bytes | result |
+-----------------------------------------+--------+------------+---------------+-----------------+-------+--------+
| https://atom.io/api/packages/file-icons | GET    | osquery    |               |                 |       |        |
+-----------------------------------------+--------+------------+---------------+-----------------+-------+--------+
```

**Comment by FritzX6** [comment]
```
➜  ~ openssl version
OpenSSL 1.0.2o  27 Mar 2018
```

```
➜  ~ openssl s_client -connect atom.io:443
CONNECTED(00000003)
4712857068:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:802:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 307 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1573760346
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by theopolis** [comment]
The issue (perhaps a bug) with the `curl` table is it allows non-TLS connections. Because of this osquery does not apply the "TLS defaults" to the HTTP client. No osquery-specific TLS version requirements / certificate bundle location / SNI configuration. 

A potential fix is detecting the presence of "https://" as the prefix and applying the basic checks.

Another potential bug with the `curl` table is the missing usage of `--proxy_hostname`, would you expect these requests to use the configured proxy or not?

**Comment by terracatta** [comment]
> Another potential bug with the curl table is the missing usage of --proxy_hostname, would you expect these requests to use the configured proxy or not?

One use-case we have for the curl table at Kolide is to curl for an internally accessible URl (provided by a customer) as a way to determine if a device is currently "on-corp". In this case, we would want to use the configured proxy when available. So my preference is use the proxy by default and an opt-out flag would be a nice-to-have for cases where that causes a problem.

**Comment by theopolis** [comment]
> One use-case we have for the curl table at Kolide is to curl for an internally accessible URl (provided by a customer) as a way to determine if a device is currently "on-corp". In this case, we would want to use the configured proxy when available.

Wouldn't you want to skip using the proxy for local (corporate) resources? The osquery HTTP client is not smart enough to make this determination so it would be always use the proxy or not (currently).

**Comment by terracatta** [comment]
> Wouldn't you want to skip using the proxy for local (corporate) resources? The osquery HTTP client is not smart enough to make this determination so it would be always use the proxy or not (currently).

No, at least in the big companies I've worked for the proxies are traditionally configured to exclude internal resources and sometimes add access to resources not previously available.

**Comment by theopolis** [comment]
Ok, please help by testing and reviewing the change I proposed.
