### ISSUE TITLE
In a config file, using decorators causes disabled_tables to be ignored

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6041]
# Bug report

Debugging something on slack, it seems like using `decorators` can cause the options block to be ignored.

```
$ cat /tmp/osq.conf 
{
  "decorators":{"load":["SELECT uuid AS host_uuid FROM system_info;" ]},
  "options": { "disable_tables": "kernel_info" }
}

$ osqueryd -S -config_path  /tmp/osq.conf  'select version from kernel_info;'
+---------+
| version |
+---------+
| 18.7.0  |
+---------+



$ cat /tmp/osq.conf 
{
  //"decorators":{"load":["SELECT uuid AS host_uuid FROM system_info;" ]},
  "options": { "disable_tables": "kernel_info" }
}

$ osqueryd -S -config_path  /tmp/osq.conf  'select version from kernel_info;'
Error: no such table: kernel_info
```

### What operating system and version are you using?

```
 version = 10.14.6
   build = 18G1012
platform = darwin
```

### What version of osquery are you using?

```
version = 4.0.2
```

**Comment by directionless** [comment]
Continuing to dig, it seems specific to the `load` part there. If I have no load queries, the disable work. But if I have even `"decorators":{"load":["SELECT 1;"]}` the options are ignored.

Perhaps also notable is that the load decorator isn't on the output there

**Comment by theopolis** [comment]
Hehe, this is because the `decorators` parser is loaded before the `options` parser ;)
