### ISSUE TITLE
CentOS 8 / RHEL 8 rpm package

### ISSUE THREAD

**Issue by furlongm** [osquery/osquery#6042]
# Feature request

### What new feature do you want?

RPM package for CentOS 8 / RHEL 8

### How is this new feature useful?

Currently packages are only available for CentOS 6/7 / RHEL 6/7

### How can this be implemented?

Building a package for CentOS 8 and uploading to https://s3.amazonaws.com/osquery-packages/centos8/$basearch/

**Comment by theopolis** [comment]
Hi @furlongm, the osquery RPM packages should work on every Linux distro that supports RPM installs. The same is true for the `yum` repos we host: https://osquery.io/downloads/official/4.0.2

You may be using old yum/RPM packages, take a look at the downloads page and try them out on CentOS 8. If there's an issue, please re-open!

**Comment by furlongm** [comment]
Hi,

The rpms work, but adding a generic yum repo with the $releasever yum variable for Centos 6/7 and 8 is not possible without the centos8 url.

i.e. the below repo file works for CentOS 6 and 7, but not 8.

```
[osquery repo]
name=name=osquery CentOS $releasever RPM repository - $basearch
baseurl=https://s3.amazonaws.com/osquery-packages/centos$releasever/$basearch/
enabled=1
gpgkey = file:///etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY
gpgcheck=1
```

Would it be possible to just add a CentOS 8 repo with the same rpms published in the CentOS 6 and CentOS 7 repos? If it's possible to add a link to the CentOS 7 repo, that would also work.

**Comment by furlongm** [comment]
I'm have no permission to re-open this issue btw!

**Comment by theopolis** [comment]
Why not just create a repo file like:
```
[osquery repo]
name=name=osquery RPM repository - $basearch
baseurl=https://pkg.osquery.io/rpm/$basearch/
enabled=1
gpgkey = file:///etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY
gpgcheck=1
```

Then use this on any Linux with `yum` installed.

**Comment by furlongm** [comment]
That works, thanks!
