### ISSUE TITLE
Explore porting boost::regex to std::regex

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6061]
There are some bugs with `boost::regex` that do not exist with `std::regex`. Is is possible to port https://github.com/osquery/osquery/pull/5444?

I mostly want to move away from `boost::algorithm::split_regex`, but it doesn't make sense to have multiple regex implementations (boost+std).

Relates to: #5443 #5444

**Comment by theopolis** [comment]
//cc @directionless who first encountered the hang-bug.

**Comment by directionless** [comment]
I based `regex_match` on boost, since it's what regex_split used. I don't know any reason we can't move them to `std::regex`. I think that would be a great idea

The hang bug is #5443

**Comment by theopolis** [comment]
Ah yes, thanks for linking the previous issue.

It’s not clear to me that the regex grammar for boost and std are the same, thus I am not sure how easy this fix is (may not be a good first issue).

**Comment by directionless** [comment]
There are reasonable test cases running, and they can be expanded.

But my inclination is that if we need to change regex engines, and some extended syntax changes, so be it.

**Comment by scoders-tob** [comment]
Instead of switching regex engines, an alternative is to use `boost::sregex_token_iterator` does not seem to suffer from the #5443 bug. Is that acceptable?

**Comment by directionless** [comment]
While I expect moving to `boost::sregex_token_iterator` would solve the issue, but the non-responsiveness of the boost developers doesn't really make me feel good about it. If `std::regex` works, my bias is to use that.

**Comment by scoders-tob** [comment]
Cool, `std::regex` also works. 
I can take this issue up then and replace both `regex_split` and `regex_match` StringExtensions to fix bug #5443 to begin with.
I'll follow it up with an overall replacement of `boost::regex` with `std::regex` eventually.
Does that work?

**Comment by directionless** [comment]
Seems reasonable to me. I think `regex_split` and `regex_match` are both small and easy places to get traction.

**Comment by scoders-tob** [comment]
Do we want to replace `boost::xpressive::regex_search` as well or only `boost::regex_search`?

**Comment by theopolis** [comment]
It feels low priority but ideal to move as much to `std::regex` as possible. I am not sure if we can set a goal to stop linking `boost_regex` as other dependencies may require it?

**Comment by scoders-tob** [comment]
Ok, I'll try and convert all occurrences to `std::regex`. Then  we can take try not linking `boost_regex` and see if/what fails.
