### ISSUE TITLE
Log events and system events are inconsistent

### ISSUE THREAD

**Issue by bubaiwantong** [osquery/osquery#6070]
dear：
    i run date command, display system time show below:
[root@localhost osquery]# date
Thu Nov 21 10:19:17 CST 2019
    
    but event time display shwo below:
{"name":"system_profile","hostIdentifier":"localhost.localdomain","calendarTime":"**Thu Nov 21 00:31:35 2019** UTC","unixTime":1574296295,"epoch":0,"counter":61,"logNumericsAsNumbers":false,"decorations":{"host_uuid":"564DBF01-FAEE-BBC1-FA74-3F967DBEC914","username":"root"},"columns":{"average_memory":"8000","blacklisted":"0","executions":"65","interval":"3600","last_executed":"1574292993","name":"shell_history","output_size":"","query":"select uid,command,history_file from shell_history;","system_time":"50","user_time":"250","wall_time":"0"},"action":"added"}

What's the problem, please

**Comment by muffins** [comment]
Looks like it's the Timezone difference. osquery generically uses UTC for it's timestamps, which you've got highlighted there:
```
Thu Nov 21 00:31:35 2019 UTC
```
Whereas your `date` command is returning your results in CST. Going to close this out but please feel free to re-open if you've got more questions :)
