### ISSUE TITLE
table schema support issue.

### ISSUE THREAD

**Issue by SimpleSummer** [osquery/osquery#6072]
# Bug report

### What operating system and version are you using?

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64

### What version of osquery are you using?

version = 4.0.2

### What steps did you take to reproduce the issue?
1.In this [page](https://osquery.io/schema/4.0.2), I know atom_packages can be supported by windows platform.
2. When I enter .tables, I failed to find the atom_packages table.
### What did you expect to see?
I expect to verify the page.

**Comment by theopolis** [comment]
It looks like it is only being included for `linux` and `macos`.

```
./specs/CMakeLists.txt:69:    "atom_packages.table:linux,macos"
```

**Comment by sevickson** [comment]
Does this mean the website needs to be changed or atom_packages should be included with the Windows build also?
