### ISSUE TITLE
cpack: Package naming nitpicks (corrections)

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6074]
Right now CPack is generating debug packages for debian with the filename: `$NAME_$VERSION.$ARCH-dbgsym.ddeb`. 

```
$ dpkg-deb --info ./osquery_4.1.1_1.linux.amd64-dbgsym.ddeb 
 new Debian package, version 2.0.
 size 36992810 bytes: control archive=440 bytes.
     335 bytes,    13 lines      control              
     202 bytes,     1 lines      md5sums              
 Architecture: amd64
 Auto-Built-Package: debug-symbols
 Build-Ids: 66d121dbdf319825fe3b1b7af11c5620584ddac0
 Depends: osquery (= 4.1.1-1.linux)
 Description: debug symbols for osquery
 Maintainer: osquery@osquery.io
 Package: osquery-dbgsym
 Package-Type: ddeb
 Priority: optional
 Section: debug
 Version: 4.1.1-1.linux
 Installed-Size: 133771
 ```

The package `Name:` is set to `osquery-dbgsym` and that should be reflected in the filename. According to https://wiki.debian.org/AutomaticDebugPackages the correct format is: `osquery-dbgsym_4.1.1-1.linux_amd64.deb`.

For the generator reference: https://cmake.org/cmake/help/v3.13/cpack_gen/deb.html

**Comment by theopolis** [comment]
Additionally the `tar.gz` generated should be: `osquery-4.1.1_1.linux_x86_64.tar.gz`.

**Comment by theopolis** [comment]
Additionally the debug `rpm` generated should be: `osquery-debuginfo-4.1.1-1.linux.x86_64.rpm`

**Comment by directionless** [comment]
Is this still an issue?

**Comment by theopolis** [comment]
Yes but I do not think we have a resolution besides doing the rename manually.
