### ISSUE TITLE
osquery build broken with Python 3.5

### ISSUE THREAD

**Issue by tomrittervg** [osquery/osquery#6079]
# Bug report

### What operating system and version are you using?

Ubuntu xenial

### What version of osquery are you using?

https://github.com/osquery/osquery/commit/93ceef7e5f1c7e17be63e4d7a58c641bc8031474

### What steps did you take to reproduce the issue?

Try configuring and building osquery.  It fails because xenial's python3 is only 3.5

### What did you expect to see?

It to build. (At least one configuration did before this patch landed, I don't know if there were reasons to avoid 3.5 that wren't mentioned in #6057 though)

### What did you see instead?

> Step #4: CMake Error at cmake/utilities.cmake:111 (message):
> Step #4:   Could not find a suitable Python 3 version.  Please install a version >=
> Step #4:   3.6 but < 3.8

**Comment by directionless** [comment]
Relates to: https://github.com/osquery/osquery/pull/6057

Also worth noting that in #6057 someone asked for 3.8 support
