### ISSUE TITLE
xml parsing in the windows_events table

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6083]
The `windows_events`'s `data` column is currently doing some hand tweaked value coercion. 

In office hours todays we talked about how this would benefit from moving to rapidXML.

There was also a slack suggestion to make a flag to support outputing in other formats. json, base64, etc. This would probably fit in other columns, I'm generally against config flags

**Comment by verntx** [comment]
The boost.PropertyTree XML parser is already built on rapidXML:
https://www.boost.org/doc/libs/1_71_0/doc/html/property_tree/parsers.html#property_tree.parsers.xml_parser
