### ISSUE TITLE
Remove com.facebook files and references

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6094]
Placeholder:
* https://github.com/osquery/osquery/pull/6093
* https://github.com/osquery/osquery/blob/master/tools/deployment/productbuild.sh
* https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osquery.rb

**Comment by Smjert** [comment]
The only thing missing here is to eventually updating the Homebrew cask. So this is not a blocker for the release anymore.

**Comment by mike-myers-tob** [comment]
It's not a blocker, I'll move it from the 5.0 release milestone

**Comment by directionless** [comment]
Well, sorta? I think we've removed all the facebook references from inside our repo. But the homebrew update will need to change them.

**Comment by Smjert** [comment]
@directionless Isn't this a step that happens **after** the release (because it needs the sha)? So it can't be blocking it.

**Comment by directionless** [comment]
Yes. And it's not even a repo we pay much attention to.

**Comment by mike-myers-tob** [comment]
- [ ] Homebrew cask (make a PR to [Homebrew Cask](https://github.com/homebrew/homebrew-cask) once 5.0 is "release/stable")
- [ ] Linux and Windows signing keys are still `fb.com` (this won't happen on 5.0.x)

**Comment by mike-myers-tob** [comment]
I think we're all done here? Can this be closed?

**Comment by directionless** [comment]
Yeah, I think we can close this
