### ISSUE TITLE
mdfind table no longer works in osquery 4.1.1

### ISSUE THREAD

**Issue by FritzX6** [osquery/osquery#6099]
# Bug report

### What operating system and version are you using?
macOS 10.15.1 (Catalina)
macOS 10.14.6 (Mojave)

### What version of osquery are you using?
**osquery 4.0.1** 
_(confirmed works)_

**osquery 4.1.1**
_broken_

### What steps did you take to reproduce the issue?
Launch osqueryi terminal session and run a valid mdfind query:

### What did you expect to see?
```SQL
osquery> .version
osquery 4.0.1
using SQLite 3.26.0
osquery> select COUNT(*) from mdfind, file USING(path) where query = "kMDItemFSName == '*.sketch'";
+----------+
| COUNT(*) |
+----------+
| 999      |
+----------+
```
### What did you see instead?
```SQL
osquery> .version
osquery 4.1.1
using SQLite 3.29.0
osquery> select COUNT(*) from mdfind, file USING(path) where query = "kMDItemFSName == '*.sketch'";
+----------+
| COUNT(*) |
+----------+
| 0        |
+----------+
osquery> 
```

**Comment by terracatta** [comment]
Just to add to this, osqueryi 4.1.1 reports no additional information (warnings/errors) when running under the verbose settings that would offer a clue as to why this table is not producing results.

**Comment by theopolis** [comment]
Indeed, it looks like the `mdfind` spec is incorrect:
```
table_name("mdfind")
description("Run searches against the spotlight database.")
schema([
    Column("path", TEXT, "Path of the file returned from spotlight"),
    Column("query", TEXT, "The query that was run to find the file"),
])
implementation("mdfind@genMdfindResults")
fuzz_paths([])
examples([
	"select count(*) from mdfind where query = 'kMDItemTextContent == \"osquery\"';"
	"select * from mdfind where query = 'kMDItemDisplayName == \"rook.stl\"';",
	"select * from mdfind where query in ('kMDItemDisplayName == \"rook.stl\"', 'kMDItemDisplayName == \"video.mp4\"')"
])
```

The `query` column should be marked as a required column. This sometimes worked before but with >4.0.2 these values are more strict.

I am guessing the attempt to fix all of the specs missed this one.
