### ISSUE TITLE
extension: return Status in TablePlugin::call() get lost

### ISSUE THREAD

**Issue by Agile86** [osquery/osquery#6107]
While using extension, osquery::Status returned from `TablePlugin::call()` method get lost.
See [VirtualTable.cpp:1006](https://github.com/osquery/osquery/blob/master/osquery/sql/virtual_table.cpp#L1006).
From extension POV this is looking like:

`  osquery::Status ExampleTable::call(const osquery::PluginRequest& request,
                       osquery::PluginResponse& response) override`
`
{
      return Status(33, "SOME ERROR");
}
`

> osquery> select * from example;
osquery>

After patch:

>osquery> select * from example;
Error: SOME ERROR
osquery>

Here is [patch](https://textuploader.com/1opg9).

**Comment by theopolis** [comment]
Thanks for proposing the patch @Agile86, I do think we should implement this. Are you able to open a GitHub pull request with the change?
