### ISSUE TITLE
Windows MSI no longer includes cert bundle

### ISSUE THREAD

**Issue by zwass** [osquery/osquery#6109]
# Bug report

### What operating system and version are you using?
Windows (any)

### What version of osquery are you using?
4.1.1

### What steps did you take to reproduce the issue?
Install MSI

### What did you expect to see?
`\Program Files\osquery\certs\` contains a cert bundle.

### What did you see instead?
The directory is empty.

I think this is because the default path the build script looks for the bundle does not contain certs (at least in the latest chocolatey openssl package): https://github.com/osquery/osquery/blob/master/tools/deployment/make_windows_package.ps1#L667

Maybe the script can be configured to use the bundle in the repo? https://github.com/osquery/osquery/blob/master/tools/deployment/certs.pem

**Comment by theopolis** [comment]
Ah, @muffins, is it possible to use CPack (as the code exists today) for the next release? If not then is it possible to fix the Windows/MSI/CPack problems before the next release?

**Comment by muffins** [comment]
Thanks for getting that fixed up @zwass! I appreciate it!
