### ISSUE TITLE
windows_event_log logger plugin not working

### ISSUE THREAD

**Issue by akefallonitis** [osquery/osquery#6117]
Hi,

 windows_event_log logger plugin is not working in a Windows 10 1909 built.

 After fresh installation of 4.02 msi and following the steps:
https://osquery.readthedocs.io/en/stable/installation/install-windows/#enabling-windows-event-log-support
osquery event log stream is created in the event viewer but osquery reports no output and no error.

flags config

--config_plugin=filesystem
--config_path=C:\Program Files\osquery\osquery.conf
--enable_monitor
--events_expiry=300
--logger_plugin=windows_event_log
--logger_event_type=false
--logger_snapshot_event_type=false
--database_path=C:\Program Files\osquery\osquery.db
--pidfile=C:\Program Files\osquery\osquery.pidfile
--disable_tables=windows_events
--verbose

**Comment by akefallonitis** [comment]
![image](https://user-images.githubusercontent.com/24274227/70640180-3a519380-1c44-11ea-8ee2-e7aa6b2082d2.png)

**Comment by akefallonitis** [comment]
So basically wanna log the query results and snapshots along with osquery errors etc in windows event logs to push them in WEC

**Comment by Smjert** [comment]
@akefallonitis, thanks for the report!
I'm sorry but this is currently not available, the problem is tracked by https://github.com/osquery/osquery/issues/5735.

I'll have a look at it.

Curiosity, haven't you received a similar error when installing the manifest?
```
**** Warning: Publisher {f7740e18-3259-434f-9759-976319968900} is installed on
the system. Only new values would be added. If you want to update previous
settings, uninstall the manifest first.

**** Warning: The resource file for publisher Facebook does not contain the metadata resource.
Make sure to link the .bin file generated by the Message Compiler into the
specified binary.

resourceFileName: C:\Program Files\osquery\osqueryd\osqueryd.exe

**** Warning: Publisher Facebook resources could not be found or are not accessible
to the EventLog service account (NT SERVICE\EventLog).
```

**Comment by akefallonitis** [comment]
Hi @Smjert  yes the error exist when trying the wevtutil command. But when trying the powershell .\manage-osqueryd.ps1 -installWelManifest there was no error so i assumed that it should work.
