### ISSUE TITLE
Fix ntfsAclPermission.test_sanity throwing bad_alloc

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6123]
https://dev.azure.com/trailofbits/osquery/_build/results?buildId=1847
```
67: [----------] 1 test from ntfsAclPermissions
67: [ RUN      ] ntfsAclPermissions.test_sanity
67: unknown file: error: C++ exception with description "bad allocation" thrown in the test body.
67: [  FAILED  ] ntfsAclPermissions.test_sanity (16 ms)
67: [----------] 1 test from ntfsAclPermissions (16 ms total)
```

The test failed when compiling commit https://github.com/osquery/osquery/commit/a73ffad3bfb3592070091f6ae8211fb9c6894adb
It only reproduced once for now.

**Comment by theopolis** [comment]
I am trying to guess what could go wrong and this code could be improved:
```cpp
std::string trusteeToStr(const TRUSTEE& trustee) {
  // Max username length for Windows
  const unsigned long maxBuffSize = 256;
  unsigned long sizeOut = maxBuffSize;
  char name[maxBuffSize];
  char domain[maxBuffSize];
  SID_NAME_USE accountType;

  switch (trustee.TrusteeForm) {
  case TRUSTEE_IS_SID: {
    // get the name from the SID
    PSID psid = trustee.ptstrName;
    auto r = LookupAccountSid(
        nullptr, psid, name, &sizeOut, domain, &sizeOut, &accountType);
    if (r == FALSE) {
      VLOG(1) << "LookupAccountSid error: " << GetLastError();
      return "";
    } else {
      return name;
    }
  }
  [...]
}
```

I make this assumption because in other places I see `LookupAccountSid` used first to calculate `sizeOut` and allocate a buffer, then a second call to fill in the buffer.

I do doubt this slightly since this is a c++ exception and I am not sure if `LookupAccountSid` is written in c++, nor do I know if Windows APIs throw c++ exceptions.

**Comment by theopolis** [comment]
I do think that change is not responsible for the error but surfaced the underlying bug.

**Comment by theopolis** [comment]
It also looks like this function is leaking memory by not calling `LocalFree` (based on reading https://docs.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-getexplicitentriesfromacla).

**Comment by Smjert** [comment]
Good find!
Something that throws me off though is that the test does `select * from ntfs_acl_permissions`, but this query doesn't make sense for the table implementation, because it should require a path, which doesn't (in fact the table spec is missing the `required` option).
At the same time though the table logic is doing:
https://github.com/osquery/osquery/blob/3f632aaea2873b21ebd0b238a58e33a552486e9c/osquery/tables/system/windows/ntfs_acl_permissions.cpp#L131-L132

So if you don't pass a `path` constraint, my expectation is that the table code will do nothing... but then why it's throwing a bad_alloc?

**Comment by theopolis** [comment]
> Something that throws me off though is that the test does `select * from ntfs_acl_permissions`

It may have done that for a short amount of time, but there is a `path` and my guess is this is what is causing the exceptions to show up now. See the code (with blame turned on) https://github.com/osquery/osquery/blame/master/tests/integration/tables/ntfs_acl_permissions.cpp#L34

**Comment by Smjert** [comment]
> > Something that throws me off though is that the test does `select * from ntfs_acl_permissions`
> 
> It may have done that for a short amount of time, but there is a `path` and my guess is this is what is causing the exceptions to show up now. See the code (with blame turned on) https://github.com/osquery/osquery/blame/master/tests/integration/tables/ntfs_acl_permissions.cpp#L34

Doh, maybe looking at the latest master would be a good thing.
