### ISSUE TITLE
Missing header (`config.hpp`) from the boost package

### ISSUE THREAD

**Issue by kumarak** [osquery/osquery#6134]
# Bug report
Tried building osquery-extension which uses boost process library on macOS. It fails due to missing file `boost/winapi/config.hpp`. The file is not included on the non-windows platform. 

```
In file included from .../osquery_workspace/osquery/libraries/cmake/source/boost/src/libs/process/include/boost/process.hpp:27:
.../osquery_workspace/osquery/libraries/cmake/source/boost/src/libs/process/include/boost/process/cmd.hpp:14:10: fatal error: 
   'boost/winapi/config.hpp' file not found
#include <boost/winapi/config.hpp>
     ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
### What operating system and version are you using?
MacOS 10.15

### What version of osquery are you using?
master

**Comment by theopolis** [comment]
Thanks for the report, do you mind including more information about how you are building the extension? What commands are you running?

I’d like to reproduce the error but I need step-by-step guidance.

**Comment by Smjert** [comment]
Looking at the boost headers it indeed seems that Boost unconditionally depends on that header:
https://github.com/boostorg/process/blob/0a554c92b589428d21e6e263350a1c0c866331ac/include/boost/process/cmd.hpp#L14

While our CMake skips the library if it's not Windows:
https://github.com/osquery/osquery/blob/551d548b478f416bbfadaa0a0450c05873d2a9f6/libraries/cmake/source/boost/CMakeLists.txt#L275-L280

**Comment by kumarak** [comment]
@Smjert, Thanks for adding the details. 

I tried building `darwin_unified_log` from `trailofbits/osquery-extensions`. It includes process library header `boost/process.hpp`.  The process header internally depends on `boost/winapi/config.hpp` without checking for the platform type. 

The osquery CMake interface ignores the `winapi` directory for the non-windows platforms.  
https://github.com/osquery/osquery/blob/551d548b478f416bbfadaa0a0450c05873d2a9f6/libraries/cmake/source/boost/CMakeLists.txt#L275-L280

Anyone using the process library is likely to run into the issue because of the missing include directory.
