### ISSUE TITLE
Windows:  No executable details due to missing resource file

### ISSUE THREAD

**Issue by joshdhart** [osquery/osquery#6137]
# Bug report

### What operating system and version are you using?
Windows 10

### What version of osquery are you using?

4.1.1

### What steps did you take to reproduce the issue?

1. Install or extract binaries from the MSI
2. Right click osqueryi.exe or osqueryd.exe and  press "properties"
3. Navigate to the "details" tab
4. No description, no version, no company, etc. 

### What did you expect to see?

All the windows resource  information populated just like in version 3.X of the product. 

### What did you see instead?

Nothing

**Comment by Smjert** [comment]
Hi! thanks for your report, this issue is tracked by https://github.com/osquery/osquery/issues/5735
and related to https://github.com/osquery/osquery/issues/6117
