### ISSUE TITLE
example_extension did not built 

### ISSUE THREAD

**Issue by htmlgod** [osquery/osquery#6146]
# Bug report

### What operating system and version are you using?

```
 version = 10.15.1
   build = 19B88
platform = darwin
```

### What version of osquery are you using?

```
version = 4.1.2
```

### What steps did you take to reproduce the issue?
Cloned source files from osquery : master, tried to build osquery from source
### What did you expect to see?
example_extension.ext in build folder
### What did you see instead?
Osqueryi and osqueryd had built correctly, last time i didnt get that result, so i tried to find osquery_extension.ext but didnt find it

**Comment by Smjert** [comment]
@htmlgod Thanks for your report, this is a known issue.
@scoders-tob have worked to restore them and the respective Python tests (https://github.com/osquery/osquery/pull/5836/commits/d17641a174647fee899953fee804f0ade484b879), but there's still some work to do on the Python tests framework, so we have to deal with that first and then repropose the PR.

Meanwhile, if you just need to build it, you could try with that commit.

**Comment by htmlgod** [comment]
Thx, i ll try this
