### ISSUE TITLE
OSQUERY stops working after Windows Updates (Win Server 2016 and Windows 10)

### ISSUE THREAD

**Issue by juaromu** [osquery/osquery#6148]
I've noticed that every time a windows update is executed, patches are installed and system reboots OSQUERY agent stops working. I'm using Fleet and affected hosts are shown as disconnected after the upgrade and only workaround I've found is to reinstall the package.

Please find details below as per template.
Thanks!

### What operating system and version are you using?

version = 3.3.2

### What steps did you take to reproduce the issue?

Automatic Windows Update (Windows Server 2016 and Windows 10)

### What did you expect to see?

OSQUERY working after updates instaleld and system reboot

### What did you see instead?

Host shown as disconencted in Fleet Manager. OSQUERY stopped working/Fleet managr not getting query results.

Workaround: Reinstall OSQUERY from .msi package

**Comment by juaromu** [comment]
### What operating system and version are you using?



version = 3.3.2

### What steps did you take to reproduce the issue?

Automatic Windows Update (Windows Server 2016 and Windows 10)

### What did you expect to see?

OSQUERY working after updates instaleld and system reboot

### What did you see instead?

Host shown as disconencted in Fleet Manager. OSQUERY stopped working/Fleet managr not getting query results.

Workaround: Reinstall OSQUERY from .msi package

**Comment by juaromu** [comment]
### What operating system and version are you using?

 version = 10.0.14393
   build = 14393
platform = windows

### What version of osquery are you using?

version = 3.3.2

**Comment by muffins** [comment]
Hey @juaromu , thanks for reporting. That’s a pretty old version of osquery, any chance you could test an upgrade to the latest version of 4.1.2 and see if the problem persists? I ask as there’s a considerable amount of changes that I’ve taken place since 3.3.2

**Comment by juaromu** [comment]
Hi @muffins 
Thx for your response. I've installed 4.1.1 in another machine (Win10), applied latest Windows update and after restart came back up fine, shown as online in Fleet and sending query results.
Thx for ur help :-)
