### ISSUE TITLE
Create `ec2_instance_metadata` table on Windows

### ISSUE THREAD

**Issue by luisffc** [osquery/osquery#6149]
# Feature request

### What new feature do you want?

It would be great to have `ec2_instance_metadata` table available also on Windows

### How is this new feature useful?

It would make easier writing platform-agnostic queries with osquery

### How can this be implemented?

No idea, but noticed `azure_instance_metadata` is currently available for all platforms

**Comment by Smjert** [comment]
Closing since this has been implemented.
