### ISSUE TITLE
Group perms on extensions socket to access as unpriv. user

### ISSUE THREAD

**Issue by ake-persson** [osquery/osquery#6172]
# Feature request

### What new feature do you want?

I want to be able to access the extension socket as an unprivileged user.

This means the OS package needs to create a group "osquery" and set the ownership of the socket to this group. It also needs to set the permissions to 770 to allow a member of that group to read/write to the socket.

### How is this new feature useful?

I'm currently the maintainer of a package [osquery-api](https://github.com/mickep76/osquery-api) that exposes osquery as a REST API and it's preferable to run this as an unprivileged user for security. Currently I work around this issue by creating a dir. for the socket and set 2770 so it inherits the perms. This obv. works but it requires me to replace/ modify the systemd file for osquery so that it starts with umask 0002. This is undesirable and it would be nicer if this was included per default in osquery.

This is also useful in cases where you want to accees the socket from your own user. This is a pattern Docker uses for it's socket so I would say it's a reasonable improvement.

### How can this be implemented?

The OS package needs to add a group "osquery" on creation of the extensions socket it needs to assign this group ownership of the socket and set the perms to 770 for the socket.

**Comment by theopolis** [comment]
I think it's a nice feature to use `osquery` as non-root. But we do not want to expose access to the socket as an unprivileged user as the information osquery provides is sensitive.

The approach is reasonable but I think this is something we should put into the documentation for now, unless someone wants to take initiative to build it into packaging.

@mickep76 is this something you can help us with?

**Comment by DivyaUppu** [comment]
Are there any plans on building this feature?

**Comment by ake-persson** [comment]
I think `not`.
