### ISSUE TITLE
WmiRequest explicit constructor's second parameter should be std::wstring and not BSTR

### ISSUE THREAD

**Issue by farfella** [osquery/osquery#6173]
# Bug report

### What operating system and version are you using?
N/A

### What version of osquery are you using?
master branch

### What steps did you take to reproduce the issue?
Looking at PR https://github.com/osquery/osquery/pull/5246

### What did you expect to see?
The second argument to this explicit constructor should be an std::wstring instead of BSTR.

### What did you see instead?
BSTR is a special structure for strings in windows, and needs to be allocated with SysAllocString and freed with SysFreeString. Casting a std::wstring to BSTR is incorrect and will lead to unexpected errors. Better approach would be to construct a BSTR from the wstring parameter, and free it after use.

**Comment by theopolis** [comment]
I see several instances of the pattern `(BSTR)L"WQL"` in the code base. How are these working given the data structure expectation for a `BSTR`?

**Comment by farfella** [comment]
> I see several instances of the pattern `(BSTR)L"WQL"` in the code base. How are these working given the data structure expectation for a `BSTR`?

Passing in wchar_t strings to methods/functions that explicitly request BSTRs results in undefined behavior. These are different data-types.

Here is one reference: https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/allocating-and-releasing-memory-for-a-bstr?view=vs-2019
