### ISSUE TITLE
osquery can't start

### ISSUE THREAD

**Issue by topsekadmin** [osquery/osquery#6177]
hello:
     when i use command osqueryctl start, show below:
     /usr/bin/osqueryctl: line 18: 14374 Segmentation fault      (core dumped) $EXEC --config_path=$REAL_CONFIG_PATH --config_check

     i use kolide fleet, when i use command add client, server can't display
   sudo /usr/bin/osqueryd \
  --enroll_secret_path=/var/osquery/enroll_secret \
  --tls_server_certs=/var/osquery/server.pem \
  --tls_hostname=192.168.30.123:8080 \
  --host_identifier=uuid \
  --enroll_tls_endpoint=/api/v1/osquery/enroll \
  --config_plugin=tls \
  --config_tls_endpoint=/api/v1/osquery/config \
  --config_refresh=10 \
  --disable_distributed=false \
  --distributed_plugin=tls \
  --distributed_interval=3 \
  --distributed_tls_max_attempts=3 \
  --distributed_tls_read_endpoint=/api/v1/osquery/distributed/read \
  --distributed_tls_write_endpoint=/api/v1/osquery/distributed/write \
  --logger_plugin=tls \
  --logger_tls_endpoint=/api/v1/osquery/log \
  --logger_tls_period=10 &

<img width="1261" alt="WX20200116-143603@2x" src="https://user-images.githubusercontent.com/59950798/72499700-8a3bff80-386d-11ea-89a0-b611785aaf1c.png">

please help me check it ,thank you

**Comment by Smjert** [comment]
@topsekadmin Hi!
Which osquery version are you using?
On what platform/version?

**Comment by topsekadmin** [comment]
> @topsekadmin Hi!
> Which osquery version are you using?
> On what platform/version?

osquery version is 4.1.2
os version is CentOS Linux release 7.6.1810 (Core)

**Comment by topsekadmin** [comment]
Hi ALL:

osquery version is 4.1.2
os version is CentOS Linux release 7.6.1810 (Core)

 

 

发件人: Stefano Bonicatti <notifications@github.com>
答复: osquery/osquery <reply@reply.github.com>
日期: 2020年1月16日 星期四 下午11:02
收件人: osquery/osquery <osquery@noreply.github.com>
抄送: topsekadmin <wsj@topsek.com>, Mention <mention@noreply.github.com>
主题: Re: [osquery/osquery] osquery can't start (#6177)

 

@topsekadmin Hi!
Which osquery version are you using?
On what platform/version?

**Comment by topsekadmin** [comment]
close
