### ISSUE TITLE
Linux centos7, centos6, precise, trusty, and xenial apt/yum repos 404 (intentional)

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6181]
(this issue is a heads up!)

The 4.1.2 packages are now available in our `yum` and `apt` repositories. Please find the install instructions at https://osquery.io/downloads/official/4.1.2 as well as direct downloads for the packages. They should install on almost all Linux platforms supporting either RPM or DEB packages. 

In the past we copy-pasted packages to repos named, trusty, precise, centos6, etc, those duplicate repos are removed, if you still use these please move to the generic repos.

All distros using RPMs:
```
curl -L https://pkg.osquery.io/rpm/GPG | sudo tee /etc/pki/rpm-gpg/RPM-GPG-KEY-osquery
sudo yum-config-manager --add-repo https://pkg.osquery.io/rpm/osquery-s3-rpm.repo
sudo yum-config-manager --enable osquery-s3-rpm
sudo yum install osquery
```

All distros using DEBs:
```
export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
sudo apt-get update
sudo apt-get install osquery
```

**Comment by juju4** [comment]
Thanks @theopolis 
It also seems debug package is missing in repo (debian/ubuntu)

```
The following packages have unmet dependencies:
 osquery-dbg : Depends: osquery (= 4.0.2-1.linux) but 4.1.2-1.linux is to be installed

```

**Comment by theopolis** [comment]
Ah! Sorry about that, I will investigate and publish instructions (or fix). I think CMake produces osquery-dbgsym.

**Comment by juju4** [comment]
no problem.
package name may have changed.
I use osquery-debuginfo on redhat and osquery-dbg on debian/ubuntu

**Comment by Iwant2learn** [comment]
Hello, it seems there is some issue with ubuntu keyserver

I am getting following error on 
 # /usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys
1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

Executing: /tmp/apt-key-gpghome.C5M7jtcX1J/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

gpg: keyserver receive failed: No keyserver available. Any advise ?


Thanks in advance !

**Comment by theopolis** [comment]
@Iwant2learn, let me update the instruction here, can you try:

```
export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
```

**Comment by Iwant2learn** [comment]
Hi,

it still fails - 

export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY


Executing: /tmp/apt-key-gpghome.VDDIVJ8tAb/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
gpg: keyserver receive failed: No keyserver available


I tried searching this key on keyserver.ubuntu.com and got not found ( not sure if that is the right way to verify )

**Comment by theopolis** [comment]
Can you try some of the recommendations here: https://unix.stackexchange.com/questions/361642/keyserver-receive-failed-on-every-keyserver-available

We have not changed the key so I’m unsure why this would be an osquery-specific issue. Nevertheless I will have time to test and repo later today.

**Comment by theopolis** [comment]
> Nevertheless I will have time to test and repo later today.

I tested this on a fresh install of Debian 8.

```
vagrant@debian-8:~$ export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
vagrant@debian-8:~$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.2vt0egYMnH --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
gpg: requesting key C9D8B80B from hkp server keyserver.ubuntu.com
gpg: key C9D8B80B: public key "osquery (osquery) <osquery@fb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

The specific error:

```
gpg: keyserver receive failed: No keyserver available
```

May indicate an issue with outgoing proxy configuration.
