### ISSUE TITLE
Revisit osquery/filesystem/windows/fileops.cpp function normalizeDirPath

### ISSUE THREAD

**Issue by farfella** [osquery/osquery#6204]
The function `normalizeDirPath` makes an assumption in a comment `// NTFS is case insensitive, to normalize, make everything uppercase` and then follows to perform a `::CharUpperW` call on the path.

This is not true since NTFS is actually case-sensitive, and the end-user may have it turned on, for example, when they enable the Windows Subsystem for Linux (WSL) or POSIX/Interix.

So, we ought to check and only "normalize" if case-sensitivity isn't turned on.

**Comment by theopolis** [comment]
Hi folks, are either of you planning to work on this?

**Comment by farfella** [comment]
Yup. Going to fix the catalog/certificate issue first. This issue is probably lowest priority.
