### ISSUE TITLE
Exceeds size limit- Osquery_result

### ISSUE THREAD

**Issue by iadityac** [osquery/osquery#6205]
W0127 12:13:55.939991  1392 filesystem.cpp:113] Cannot read file that exceeds size limit: /tmp/osquery_status

getting Error ..

**Comment by Smjert** [comment]
Hello @iadityac that's more of a warning that an error, though if you're trying to read that file, you have to keep in mind that osquery has a read size limit for performance reasons, which is by default at 50MB.
If you check on our wiki at this page https://osquery.readthedocs.io/en/latest/installation/cli-flags/#daemon-runtime-control-flags, we have a `--read_max` flags that can increase that limit.

**Comment by iadityac** [comment]
@Smjert Thanks for help.
