### ISSUE TITLE
Broken Thrift API link in documentation

### ISSUE THREAD

**Issue by yves-dolce** [osquery/osquery#6210]
# Task
.
The Thrift API https://github.com/osquery/osquery/blob/master/osquery.thrift link on https://osquery.readthedocs.io/en/stable/development/osquery-sdk/#thrift-api takes you to a github 404. This need to be updated.

**Comment by jackdcasey** [comment]
I'd be happy to make this change! I've been looking for something smaller to start contributing to the project 😁

I've submitted a pr, with these changes applied.
