### ISSUE TITLE
etc_hosts doesn't do any validation

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6213]
# Bug report

I noticed the `etc_hosts` table doesn't do any validation on the data it finds. I can't decide if this is a bug or not. What do y'all think?

```
$ tail -3 /etc/hosts
hello osquery peeps
localhost notit
hello
```

```
osquery> select * from etc_hosts;
+-----------------+----------------------------+
| address         | hostnames                  |
+-----------------+----------------------------+
| hello           | osquery peeps              |
| localhost       | notit                      |
| hello           |                            |
+-----------------+----------------------------+
```

osquery> SELECT version, build, platform FROM os_version;
+---------+---------+----------+
| version | build   | platform |
+---------+---------+----------+
| 10.14.6 | 18G2022 | darwin   |
+---------+---------+----------+
osquery> SELECT version from osquery_info;
+---------+
| version |
+---------+
| 4.1.1   |
+---------+

**Comment by muffins** [comment]
Any thoughts/suggestions that you've got @directionless? I think from my perspective... I'm not sure it's worth it for us to be in the business of validating the style/type of data on a host, as this might be difficult _generically_ to do. That being said we might be able to do some simple regex matching to at least make weak guarantees on the data format?

**Comment by directionless** [comment]
On one hand, I'm leery of trying to build rich data verification. Somewhat, I think we should report on what's there.

But, in other places we do some light verification to avoid shipping mostly empty data. (I don't have an example at hand, but there are lots of places we don't push the row if expected columns are blank)

My gut sense is that it would be reasonable to skip the row if either `address` or `hostnames` is blank. I'm not sure it's worth pulling in ip address verification. But I want to hear what others think too.

**Comment by zwass** [comment]
Line 3 looks like an error, while the other two are valid syntax (http://man7.org/linux/man-pages/man5/hosts.5.html). I'd say we should leave it as-is: Folks would actually have the opportunity to spot erroneous lines vs. no visibility at all.

**Comment by directionless** [comment]
AFAIK none of those are valid. To the extent I can find format info, it should be `IP_address`. Neither `hello` nor `localhost` are ip addresses.

I'm good leaving it as is. Or bringing in some kind of skip if null behavior
