### ISSUE TITLE
SSL doesn't work with "kafka_producer" logger plugin

### ISSUE THREAD

**Issue by dfolias** [osquery/osquery#6221]
# Bug report

### What operating system and version are you using?
The bug occurred in the following operating systems and possibly affect all linux distributions:
```
+----------+--------------------------------------+
| platform | version                              |
+----------+--------------------------------------+
| rhel     | CentOS Linux release 7.7.1908 (Core) |
+----------+--------------------------------------+
| rhel     | CentOS Linux release 8.0.1905 (Core) |
+----------+--------------------------------------+
| debian   | 8 (jessie)                           |
+----------+--------------------------------------+
| debian   | 9 (stretch)                          |
+----------+--------------------------------------+
| debian   | 10 (buster)                          |
+----------+--------------------------------------+
| ubuntu   | 14.04.5 LTS, Trusty Tahr             |
+----------+--------------------------------------+
| ubuntu   | 16.04.6 LTS (Xenial Xerus)           |
+----------+--------------------------------------+
| ubuntu   | 18.04.3 LTS (Bionic Beaver)          |
+----------+--------------------------------------+
```

### What version of osquery are you using?
The bug occurred in versions:
```
+---------+
| version |
+---------+
| 4.0.1   |
+---------+
| 4.0.2   |
+---------+
| 4.1.1   |
+---------+
| 4.1.2   |
+---------+
```
The latest version that the bug does **not** occure is:
```
+---------+
| version |
+---------+
| 3.2.3   |
+---------+
```

### What steps did you take to reproduce the issue?
Configuring the "kafka_producer" in "logger_plugins" option and using SSL as protocol in "logger_kafka_brokers" causes the issue to appear.
Here is an example configuration on Ubuntu bionic:
```
$ osqueryi --line "SELECT version from os_version;"
version = 18.04.3 LTS (Bionic Beaver)

$ cat /etc/osquery/osquery.flags               
--config_plugin=filesystem
--tls_server_certs=/etc/ssl/certs/ca-certificates.crt

$ jq '.options.logger_plugin' /etc/osquery/osquery.conf
"kafka_producer,filesystem"

$ jq '.options.logger_kafka_brokers' /etc/osquery/osquery.conf.d/logger_kafka.conf 
"ssl://broker01.example.com:9093,ssl://broker02.example.com:9093,ssl://broker03.example.com:9093"
```

### What did you expect to see?
The expected behaviour would be to receive no error regarding the "kafka_producer" related configuration and finally be able to ingest osquery logs in the Kafka cluster. 
The same configuration had been working flawlessly until version 3.2.3 .
### What did you see instead?
An error appeared in the daemon log regarding the `ssl` prefix on the brokers' FQDNs.
```
# journalctl -xe -u osqueryd.service -o verbose --output-fields=MESSAGE |grep kafka
    MESSAGE=E0131 13:49:24.010207  5349 kafka_producer.cpp:91] Could not set Kafka configuration key 'security.protocol': Invalid value "ssl" for configuration property "security.protocol"
```
And also, it was the only error, when debugging with `--verbose`
```
# /usr/bin/osqueryd --ephemeral --database_path /tmp/osquery.db --verbose 2>&1 |grep ^E
E0131 14:50:40.963933 20148 kafka_producer.cpp:91] Could not set Kafka configuration key 'security.protocol': Invalid value "ssl" for configuration property "security.protocol"
```
As a result osquery logs were not ingested in the target Kafka cluster.

**Comment by Smjert** [comment]
Hi @dfolias, I think I know what's happening, the support for SSL is been inadvertently dropped between those versions.
I'm in the process of updating OpenSSL to the latest version and I can look into fix this since I already to work on having kafka build from source on macOS.

**Comment by dfolias** [comment]
Hello @Smjert , thanks for looking into it.

**Comment by ostrowr** [comment]
@Smjert thanks! This is just me reminding myself that I can update https://github.com/osquery/osquery/pull/5526 once your openssl upgrade lands.

**Comment by Smjert** [comment]
@dfolias I've opened a PR with a fix as mentioned in the issue, it would be great if you were able to test it to see if the SSL authentication now works!
Thanks!

**Comment by dfolias** [comment]
@Smjert I 'll proceed with testing and give feedback

**Comment by dfolias** [comment]
@Smjert I built osquery from your [branch](https://github.com/trailofbits/osquery/tree/stefano/build/openssl-1.1.1d) and obtained the binary with version:
`osqueryd version 4.0.1-290-gfd715939`
Using this binary, I performed successful tests with the exact same configuration as reported here and NO errors appeared in the daemon log.
Finally I verified that osquery logs were successfuly ingested in the target Kafka cluster.
Thanks a lot for fixing this, looking forward to see it merged in a verified release.

**Comment by Smjert** [comment]
> @Smjert I built osquery from your [branch](https://github.com/trailofbits/osquery/tree/stefano/build/openssl-1.1.1d) and obtained the binary with version:
> `osqueryd version 4.0.1-290-gfd715939`
> Using this binary, I performed successful tests with the exact same configuration as reported here and NO errors appeared in the daemon log.
> Finally I verified that osquery logs were successfuly ingested in the target Kafka cluster.
> Thanks a lot for fixing this, looking forward to see it merged in a verified release.

Thanks for taking the time to test it!
