### ISSUE TITLE
Create package using RPM fails

### ISSUE THREAD

**Issue by hackdefendr** [osquery/osquery#6230]
# Bug report

### What operating system and version are you using?
Redhat 7

### What version of osquery are you using?
Trying to build 4.1.2

### What steps did you take to reproduce the issue?
Followed the build guide including packaging from here: https://osquery.readthedocs.io/en/latest/development/building/

### What did you expect to see?
The build completes successfully, but crashes during packaging. I expected to see a successful build with a properly constructed RPM.

### What did you see instead?
```
Run CPack packaging tool...
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: osquery
CPack: - Install project: osquery
CPack: Create package
CMake Warning (dev) at /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:135 (message):
  CPackRPM:Warning: Path /etc/init.d/osqueryd is not on one of the
  relocatable paths! Package will be partially relocatable.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:1001 (cpack_rpm_prepare_relocation_paths)
  /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:1870 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:135 (message):
  CPackRPM:Warning: Path /etc/sysconfig/osqueryd is not on one of the
  relocatable paths! Package will be partially relocatable.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:1001 (cpack_rpm_prepare_relocation_paths)
  /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:1870 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CPackRPM:Debug: Using CPACK_RPM_ROOTDIR=/root/osquery/build/_CPack_Packages/Linux/RPM
CMake Error at /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:611 (message):
  CPackRPM: source dir path '/root/osquery' is shorter than debuginfo sources
  dir path '/usr/src/debug/osquery/src_0'! Source dir path must be longer
  than debuginfo sources dir path.  Set CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX
  variable to a shorter value or make source dir path longer.  Required for
  debuginfo packaging.  See documentation of CPACK_RPM_DEBUGINFO_PACKAGE
  variable for details.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:1376 (cpack_rpm_debugsymbol_check)
  /usr/local/share/cmake-3.14/Modules/Internal/CPack/CPackRPM.cmake:1870 (cpack_rpm_generate_package)


CPack Error: Error while execution CPackRPM.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: osquery
gmake: *** [package] Error 1
```

I'm usually pretty good with picking apart error messages, but this one has me stumped.  Do I need to create the RPM BUILD source folders and set CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX to something?

Thanks in advance.

**Comment by brucedlg** [comment]
The CPackRPM has a weird requirement that the src path (in your case /root/ocquery) must be longer than CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX (in your case, /usr/src/debug/osquery/src_0).

The easiest workaround is to checkout your code into a different location, with longer path, e.g. /root/ocquery-package/ocquery. Just make sure it's longer than /usr/src/debug/osquery/src_0

**Comment by Smjert** [comment]
Hello @brucedlg, @hackdefendr: CPackRPM needs paths longer than /usr/src/debug/osquery/src_0, because it has to edit, post-build, the binary to put the expected install path of the sources, so that they'll be automatically found by a debugger.

If you don't want to clone again the source code in a different place, another way that works is to create that longer path somewhere and then put a symlink back to the source folder.
Then when configuring the project with CMake, you point that longer path instead of the original source folder.

**Comment by theopolis** [comment]
Also checkout how our Azure CI handles this: https://github.com/osquery/osquery/blob/master/azure-pipelines.yml#L31
