### ISSUE TITLE
yum repo rpm is missing from documented url

### ISSUE THREAD

**Issue by cove** [osquery/osquery#6233]
# Bug report

### What operating system and version are you using?

CentOS7.7

### What version of osquery are you using?

1.4.6

### What steps did you take to reproduce the issue?
Following the  install steps here:
https://osquery.readthedocs.io/en/1.4.6/installation/install-linux/

```
$ sudo rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
$ sudo yum install osquery
```
### What did you expect to see?

An RPM download and install for the osquery yum repo.

### What did you see instead?

```
$ sudo rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
Retrieving https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm - transfer failed
```

**Comment by theopolis** [comment]
Hi @cove, please take a look at the latest documentation: https://osquery.readthedocs.io/en/latest/installation/install-linux/

The 1.4.6 version is very old and not supported anymore.

Also take a look here for the new repos: https://github.com/osquery/osquery/issues/6181

**Comment by cove** [comment]
Ah thanks!
