### ISSUE TITLE
Referencing aliases in subselects not supported? 

### ISSUE THREAD

**Issue by quest2nest** [osquery/osquery#6241]
I was trying to get a list of directory sizes in my home directory (Linux) using the following query:

```SQL
SELECT
  path || '%%' AS dirpath,

  (SELECT SUM(size)
   FROM file
   WHERE path LIKE dirpath
     AND type = 'regular')

FROM file

WHERE path LIKE '/home/teddy/%'
  AND type = 'directory';
```
... and got the following error:

```Error: no such column: dirpath```

Am I doing something wrong or it's a bug in osquery?

**Comment by theopolis** [comment]
Correct, the subquery is evaluated first. I think you'll need recursion to implement directory size listing, unless you are OK ignoring sizes of subdirs.

You can write the non-recursive version like:

```sql
select sum(size), directory
from file
where directory in (
  select path 
  from file 
  where directory = '/home/teddy/%' and type = 'directory'
)
group by directory;
```

**Comment by zwass** [comment]
You may want to try using a `WITH` clause (see https://sqlite.org/lang_with.html and https://dactiv.llc/blog/process-tree-with-osquery/ for an example of using this with osquery).
