### ISSUE TITLE
ssdeep hash failing returns -1 and prints to stderr

### ISSUE THREAD

**Issue by eoinmiller-r7** [osquery/osquery#6242]
# Bug report

If hashing of a file fails for md5/sha1/sha256, no messages are sent to stderr and the value returned for them is an empty string. However for ssdeep type hashing, if it fails it will print a message to stderr and also return a "-1". The behavior is inconsistent.

Relevant code:
https://github.com/osquery/osquery/blob/master/osquery/tables/system/hash.cpp#L194-L201

### What operating system and version are you using?

OSX 10.14 (Mojave), but also seen with Ubuntu 18.04, Windows 10, etc

### What version of osquery are you using?

4.1.2

### What steps did you take to reproduce the issue?

users-Mac:~ user$ sudo osqueryi 'SELECT * FROM hash WHERE path = "/private/var/db/dslocal/nodes/Default/sqlindex"' --json

### What did you expect to see?

```
[
{"directory":"/private/var/db/dslocal/nodes/Default","md5":"","path":"/private/var/db/dslocal/nodes/Default/sqlindex","sha1":"","sha256":"","ssdeep":""}
]
```
### What did you see instead?

```
W0212 16:33:37.699832 448591296 hash.cpp:195] ssdeep failed: /private/var/db/dslocal/nodes/Default/sqlindex
[
{"directory":"/private/var/db/dslocal/nodes/Default","md5":"","path":"/private/var/db/dslocal/nodes/Default/sqlindex","sha1":"","sha256":"","ssdeep":"-1"}
]
```

**Comment by directionless** [comment]
This looks like it was fixed in #6209
