### ISSUE TITLE
Move nupkg to cpack

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6248]
Right now the nupkg build uses legacy powershell scripts, we should try using cpack for it. 

Does it just work?

**Comment by muffins** [comment]
The choco package has been submitted to chocolatey, I've done quite a bit of testing and it's looking good, so once #6262 lands we should no longer require the deployment script for windows.

**Comment by theopolis** [comment]
@muffins is this complete?

**Comment by muffins** [comment]
@theopolis yup! Thanks for the ping, closing out.
