### ISSUE TITLE
chrome_extensions returns duplicate results

### ISSUE THREAD

**Issue by thepaulbenoit** [osquery/osquery#6276]
# Bug report

### What operating system and version are you using?
Windows 10  
version 10.0.18363

### What version of osquery are you using?
This issue exists in osquery 4.1.2 and 4.2.0.  
4.0.2 does not have the issue.

### What steps did you take to reproduce the issue?
Run `SELECT * FROM chrome_extensions;`  
For easier debugging, limit by a single extension identifier like `select * from chrome_extensions where identifier='nmmhkkegccagdldgiimedpiccmgmieda';`

### What did you expect to see?
A single unique result row per unique chrome extension.

### What did you see instead?
Three identical result rows per chrome extension.

**Comment by directionless** [comment]
Confirmed! I think I found it. PR incoming
