### ISSUE TITLE
Portable osquery

### ISSUE THREAD

**Issue by anki-code** [osquery/osquery#6298]
Hello!

I think about adding osquery to [xxh project](https://github.com/xxh/xxh) which allows you to bring your shell wherever you go through the ssh.

Is there a way to run osquery in portable mode? (static binary, AppImage)

For example the AppImage works good and could be build:
* [Using AppImage template on Open Build Service](https://build.opensuse.org/package/show/home:rfparedes:branches:OBS:AppImage:Templates:SLE:12-SP4/AppImageTemplate)
* [Using PEP 571 recommended manulinux2010 on Travis CI](https://github.com/niess/linuxdeploy-plugin-python/tree/master/.travis)

Thanks!

**Comment by alessandrogario** [comment]
Hello @anki-code!

The osquery project is built using [a custom, LLVM-based toolchain](https://github.com/osquery/osquery-toolchain) that already creates a 99% static binary (we can't fully static glibc due to its limitations) that can run pretty much [on any recent distribution](https://github.com/osquery/osquery/blob/master/cmake/packaging.cmake#L321).

**Comment by anki-code** [comment]
Great! Many thanks! I've added osquery entrypoint: https://github.com/xxh/xxh-shell-osquery

It works like a charm:
```
> xxhp i xxh-shell-osquery
> xxh myhost +s xxh-shell-osquery
osquery>
osquery> select * from os_version;
+--------+-----------------------------+-------+-------+-------+-------+----------+---------------+----------+
| name   | version                     | major | minor | patch | build | platform | platform_like | codename |
+--------+-----------------------------+-------+-------+-------+-------+----------+---------------+----------+
| Ubuntu | 18.04.4 LTS (Bionic Beaver) | 18    | 4     | 0     |       | ubuntu   | debian        | bionic   |
+--------+-----------------------------+-------+-------+-------+-------+----------+---------------+----------+

```
