### ISSUE TITLE
How to add hostname to prompt?

### ISSUE THREAD

**Issue by anki-code** [osquery/osquery#6299]
Hi!
Is there a way to add hostname to prompt?
```
hostname@osquery>
```
Instead of just `osquery> `

Thanks!

**Comment by theopolis** [comment]
I am not away of a way to do this now. This would have to be a new feature, it sounds neat and useful, I am happy to support and review code.

**Comment by directionless** [comment]
I'm going to close this issue, it's been answered. If someone adds it, we'll happily review the PR
