### ISSUE TITLE
Build MSI Powershell - make_windows_package.ps1

### ISSUE THREAD

**Issue by FFFreak** [osquery/osquery#6309]
Release 4.2.0 / built following: https://osquery.readthedocs.io/en/stable/development/building/
I had 3 defects that prevented an MSI being created in
**FILE:** tools\deployment\make_windows_package.ps1

** #1 **
foreach ($c in $(Get-ChildItem $certsPath)) {
  $wix += "`n<File Id='cert_$cnt' Name='$c' Source='$certsPath\$c'/>`n"
  $cnt += 1

ISSUE: $c would be the whole path of the PEM file that it detects in windows
$c == $certsPath leaving an invalid character error in candle as the path has "\" characters and is the NAME $c.
NAME: C:\osquery\tools\deployment\..\..\tools\deployment\certs.pem
SOURCE; C:\osquery\tools\deployment\..\..\tools\deployment\certs.pem\C:\osquery\tools\deployment\..\..\tools\deployment\certs.pem

** #2 **
ISSUE: On windows 10 pro, Candle would fail with a FIPS error, so had to add the -fips argument to $candleargs
New code:
 $candleArgs = @(
    "-fips",
    "$outputPath\osquery.wxs"
  )

** #3 **
if ($BuildPath -eq '') {
    # Check the default CMake build location
    $BuildPath = Join-Path "$PSScriptRoot\..\..\..\" 'build\osquery\RelWithDebInfo'

ISSUES: 2 of them - (1) 3 backs go beyond c:\ and does a powershell error. (2) assumes you did Release with Debug info.  Why the creator didn't just re-use $osqRoot I do not know. Works with the snippet below just fine.
    $BuildPath = Join-Path $osqRoot 'build\osquery\RelWithDebInfo'

**Comment by FFFreak** [comment]
For the first defect named above i just did:
$cnt = 0
if ($certsPath -eq "C:\osquery\tools\deployment\..\..\tools\deployment\certs.pem") {
  $wix += "`n<File Id='cert_0' Name='certs.pem' Source='C:\osquery\tools\deployment\certs.pem'/>`n"
} else {
  foreach ($c in $(Get-ChildItem $certsPath)) {
    $wix += "`n<File Id='cert_$cnt' Name='$c' Source='$certsPath\$c'/>`n"
    $cnt += 1
  }
}

**Comment by directionless** [comment]
I'm pretty sure the powershell script is deprecated, things are moving into `cpack`. 

@PoppySeedPlehzr ?

**Comment by FFFreak** [comment]
If it i would love to know, testing cmake now
Starting in build directory ->
cmake -DPACKAGING_SYSTEM=MSI ..
cmake --build . --target package

**Comment by FFFreak** [comment]
Attempt 2 - type must be WIX it said.

**Comment by Smjert** [comment]
> If it i would love to know, testing cmake now
> Starting in build directory ->
> cmake -DPACKAGING_SYSTEM=MSI ..
> cmake --build . --target package

By default the packaging system generates an MSI, so you don't need to specify it.
Also keep in mind that the name is `WIX`, not `MSI`.

**Comment by FFFreak** [comment]
OK, I appreciate the insight, I missed the windows part under the snippet the first time i read the custom package section.
https://osquery.readthedocs.io/en/stable/development/building/#custom-packages
Is there a way to not build it twice for Binaries vs MSI?

**Comment by FFFreak** [comment]
Lastly, is there further documentation on this process, where to put cert / flag file prior to build (I assume)?
As with the MSI PowerShell I did those as command line switches.

**Comment by directionless** [comment]
Take a look at https://github.com/osquery/osquery/pull/6262

**Comment by Smjert** [comment]
So, probably the section we have, "Custom packages" it's a bit of a misnomer right now.
CPack creates the packages for the official release, so everything is setup and layed out for that.
If you need to customize the process, you have to have a look at https://github.com/osquery/osquery/blob/master/cmake/packaging.cmake and change that or set through `-D` variables https://cmake.org/cmake/help/v3.15/variable/CPACK_INSTALL_SCRIPT.html, and provide a custom script to modify the layout before packaging begins.

```
Is there a way to not build it twice for Binaries vs MSI?
```

The project will always be built once; if you do `cmake --build . --config <config> --target package`, if there's something to build it will be built and then it will create the package you've selected.
The binaries used to create the package are in the build folder.

**Comment by FFFreak** [comment]
Thank you for my first 2 days of touching this process, I feel I have learned alot. documenting the above for my person notes - so i think either way if the powershell is deprecated this issue is solved, or cancelled, or whatever status you recommend that is not "open"

**Comment by FFFreak** [comment]
last note i cannot use the solution you posted since chocolaty is part of my issue to many heterogeneous systems... why I went MSI

**Comment by FFFreak** [comment]
For reference after my 3 changes above I was using - next run ill try cpack
.\make_windows_package.ps1 -InstallType MSI -FlagFilePath "C:\osquery\build\msi\osquery.flags" -Extras @("C:\osquery\build\msi\osquery.key","C:\osquery\build\msi\kfleetCERT_Reversed.cer")

**Comment by muffins** [comment]
@FFFreak yeah that powershell script is being deprecated, as you've discovered and so thoroughly noted, there's _loads_ of issues with that flow and it needs quite a bit of manual work. As @directionless noted #6262 brings in the new functionality, but I haven't had an opportunity to get it shipped - will try and get this fixed up tonight and tomorrow for landing. That being said, I still need to get some documentation for how this process works, but this should be quick work, as largely you just need to specify the packaging type `NuGet` when running `cmake` to generate the targets and you should be good to go. Sorry for the delays in my responses and the clunky packaging system, we'll hopefully have things working well soon! :)
