### ISSUE TITLE
osquery-4.2.0.msi: Default install directory is 'D:\Program Files\osquery' ?

### ISSUE THREAD

**Issue by robschi** [osquery/osquery#6314]
```
version = 10.0.14393
   build = 14393
platform = windows
```
`version = 4.2.0`

If you have a "D:\" drive and execute `msiexec.exe /i <path>\osquery-4.2.0.msi /qb /norestart`, osquery is installed afterwards under 'D:\Program Files\osquery' and NOT ''C:\Program Files\osquery''

As workaround you can set the ROOTDRIVE in the msiexec.exe command:
`msiexec.exe /i <path>\osquery-4.2.0.msi /qb /norestart ROOTDRIVE=%SystemDrive%\`

I think it would be best if you use the environment variable "%ProgramFiles%" to select the parent install folder.

**Comment by Smjert** [comment]
Same issue: https://github.com/osquery/osquery/issues/6342
