### ISSUE TITLE
OpenDirectory error with macOS query

### ISSUE THREAD

**Issue by nyanshak** [osquery/osquery#6320]
# Bug report

### What operating system and version are you using?

macOS 10.15

### What version of osquery are you using?

4.2.0

### What steps did you take to reproduce the issue?

Run osqueryd with this query enabled with `--verbose`:

```
I0303 10:49:29.274178 192253952 scheduler.cpp:96] Executing scheduled query pack_somepack_audit-process-events: select h.md5, p.path, p.cmdline, p.cwd, p.gid, p.egid, p.uid, p.euid, p.pid, p.parent, p.time, u.username, eu.username as e_username, g.groupname, eg.groupname as e_groupname from
hash as h, process_events as p, users as u, groups as g join users as eu on p.euid=eu.uid join groups as eg on p.egid=eg.gid where h.path = p.path and u.uid = p.uid and g.gid = p.gid and p.cmdline NOT LIKE "%docker-credentials%" group by h.md5;

```

### What did you expect to see?

no error

### What did you see instead?

```
I0303 10:49:29.317302 192253952 user_groups.mm:56] Error with OpenDirectory results: An invalid attribute type was provided.
```

> Stefano Bonicatti:trailofbits:  10:40
> @nyanshak, it's a system library error which seems to suggest that we are querying
> OpenDirectory with a wrong attribute for a specific node?
> Would need to debug that to know more..

**Comment by directionless** [comment]
Is that SQL truncated?

**Comment by directionless** [comment]
Testing this a bit, on  a 10.14 machine, with a current master build, there is a simple reproduction case in:
```
dover:build seph$ ./osquery/osqueryi  --verbose 'select * from groups where gid=0;'
I0409 00:15:05.901494 195483072 init.cpp:343] osquery initialized [version=4.2.0-63-g702a6e049]
I0409 00:15:05.901886 195483072 extensions.cpp:383] Could not autoload extensions: Failed reading: /var/osquery/extensions.load
I0409 00:15:05.902082 195483072 init.cpp:567] An error occured during extension manager startup: Extensions disabled
I0409 00:15:05.902112 195483072 auto_constructed_tables.cpp:96] Removing stale ATC entries
I0409 00:15:05.902396 195483072 init.cpp:605] Error reading config: config file does not exist: /var/osquery/osquery.conf
I0409 00:15:05.934108 195483072 user_groups.mm:56] Error with OpenDirectory results: An invalid attribute type was provided.
+-----+------------+-----------+-----------+
| gid | gid_signed | groupname | is_hidden |
+-----+------------+-----------+-----------+
| 0   | 0          | wheel     | 0         |
+-----+------------+-----------+-----------+
```

**Comment by theopolis** [comment]
@directionless, @nyanshak, sorry if I am missing something obvious but is the core issue that there is a warning/error displayed? I want to make sure there is not a known data integrity issue (for example has someone confirmed there is missing or incorrect data returned)?

**Comment by nyanshak** [comment]
I'm not sure if there are any data integrity issues, I think it's primarily a warning / possible improper collection of OpenDirectory results.
