### ISSUE TITLE
Idea: InSpec Table

### ISSUE THREAD

**Issue by gdemarcsek** [osquery/osquery#6321]
# Feature request

### What new feature do you want?

I am only wondering if it would make sense to create a Chef InSpec (https://www.inspec.io/) table to be able to ask about compliance to InSpec profiles. Osquery is great for asking questions and detecting changes in the answers, but it doesn't check if the answers are "OK" according to your policy. That's all right, you can do that elsewhere, but there is already a solution for that on the endpoints too, that might be used by some folks and could be useful to integrate.

I am not very experienced with osquery, so please be advised - this is just a vague idea, I'm just interested to learn if it makes any sense at all. So I imagine a table called `inspec` that could support running InSpec profiles:

```
table_name("inspec")
description("Track Chef InSpec checks")
schema([
    Column("profile_path", TEXT, "Path of InSpec profile", index=True),
    Column("control_status", TEXT, "Status of check"),
    Column("control_description", TEXT, "Description of check"),
    Column("control_message", TEXT, "Additional error message from control check"),
    Column("profile_id", TEXT, "ID of profile"),
    Column("profile_description", TEXT, "Profile description")
])
examples([
  "SELECT * FROM inspec WHERE profile_path = '/etc/inspec/profiles'",
])
```

### How is this new feature useful?

It could help improve osquery capabilities for continous compliance and security configuration auditing by allowing to integrate it with an existing solution.

### How can this be implemented?

On a `SELECT * FROM inspec WHERE profile_path = '/etc/inspec/profiles'`, I suppose osquery could do the equivalent of:

```
inspec exec /etc/inspec/profiles --reporter=json | jq .
```

And populate the table based on the results. Of course, there are some concerns, it might contradict current design decisions - running inspec synchronously might take considerable time depending on the profile size, etc.

**Comment by directionless** [comment]
Hi @gdemarcsek thank you for taking the time to write up the suggestion!

I'm familiar with `inspec`, and I can see the value. However, I think it's a great fit for core osquery. In addition to being slow, I think it would also involve shelling out, and historically inspec has not been an easy or standalone tool.

However, this may be the kind of thing that a site could implement. One method, would be to write an osquery extension that does this. Another method might be to setup inspec to run from cron, and to dump the files somewhere osquery can read. Of course, this option elides a lot of complexity, as osquery doesn't not support reading most file format.
