### ISSUE TITLE
chrome_extensions table contains duplicate rows

### ISSUE THREAD

**Issue by nickcollier** [osquery/osquery#6326]
# Bug report

### What operating system and version are you using?

```
 version = 10.0.18362
   build = 18362
platform = windows
```

### What version of osquery are you using?

`version = 4.2.0`

### What steps did you take to reproduce the issue?
`osqueryi "SELECT name, version, path FROM chrome_extensions ORDER BY path;"`

### What did you expect to see?
A single entry for each installed chrome extension

### What did you see instead?
Three entries for each installed chrome extension.

**Comment by directionless** [comment]
Can you share a snippet of the duplicate data?

**Comment by nickcollier** [comment]
+---------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------+
    | name                      | version      | path                                                                                                                                       |
    +---------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------+
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\                     |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\                     |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\                     |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\                     |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\                     |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\                     |
    | Google Drive              | 14.1         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.1_0\                     |
    | Google Drive              | 14.1         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.1_0\                     |
    | Google Drive              | 14.1         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.1_0\                     |
    | Passwordstate             | 8.9.3.5      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\appojfilknpkghkebigcdkmopdfcjhim\8.9.3.5_0\                  |
    | Passwordstate             | 8.9.3.5      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\appojfilknpkghkebigcdkmopdfcjhim\8.9.3.5_0\                  |
    | Passwordstate             | 8.9.3.5      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\appojfilknpkghkebigcdkmopdfcjhim\8.9.3.5_0\                  |
    | JSON Formatter            | 0.6.0        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\bcjindcccaagfpapjjmafapmmgkkhgoa\0.6.0_0\                    |
    | JSON Formatter            | 0.6.0        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\bcjindcccaagfpapjjmafapmmgkkhgoa\0.6.0_0\                    |
    | JSON Formatter            | 0.6.0        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\bcjindcccaagfpapjjmafapmmgkkhgoa\0.6.0_0\                    |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\                    |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\                    |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\                    |
    | Wildfire                  | 1.3.10       | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\djhgeeodemlfdpmcccdekfalbhllcoim\1.3.10_0\                   |
    | Wildfire                  | 1.3.10       | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\djhgeeodemlfdpmcccdekfalbhllcoim\1.3.10_0\                   |
    | Wildfire                  | 1.3.10       | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\djhgeeodemlfdpmcccdekfalbhllcoim\1.3.10_0\                   |
    | Adobe Acrobat             | 15.1.2.0     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.2.0_0\                 |
    | Adobe Acrobat             | 15.1.2.0     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.2.0_0\                 |
    | Adobe Acrobat             | 15.1.2.0     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.2.0_0\                 |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                      |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                      |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                      |
    | Google Docs Offline       | 1.11.0       | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.11.0_0\                   |
    | Google Docs Offline       | 1.11.0       | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.11.0_0\                   |
    | Google Docs Offline       | 1.11.0       | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.11.0_0\                   |
    | OneNote Web Clipper       | 3.8.1        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\gojbdfnpnhogfdgjbigejoaolejmgdhk\3.8.1_0\                    |
    | OneNote Web Clipper       | 3.8.1        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\gojbdfnpnhogfdgjbigejoaolejmgdhk\3.8.1_0\                    |
    | OneNote Web Clipper       | 3.8.1        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\gojbdfnpnhogfdgjbigejoaolejmgdhk\3.8.1_0\                    |
    | Chrome Web Store Payments | 1.0.0.5      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.5_0\                  |
    | Chrome Web Store Payments | 1.0.0.5      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.5_0\                  |
    | Chrome Web Store Payments | 1.0.0.5      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.5_0\                  |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                      |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                      |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                      |
    | Chrome Media Router       | 8320.407.0.1 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\8320.407.0.1_0\             |
    | Chrome Media Router       | 8320.407.0.1 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\8320.407.0.1_0\             |
    | Chrome Media Router       | 8320.407.0.1 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Default\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\8320.407.0.1_0\             |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\                   |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\                   |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\                   |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\                   |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\                   |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\                   |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_0\                   |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_0\                   |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_0\                   |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\                  |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\                  |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\                  |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_0\               |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_0\               |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_0\               |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                    |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                    |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                    |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_2\                    |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_2\                    |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_2\                    |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\                |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\                |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\                |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                    |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                    |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                    |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\           |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\           |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\Profile 2\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\           |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\               |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\               |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\               |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\               |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\               |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_0\               |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_0\               |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_0\               |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_0\               |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\              |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\              |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\              |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_0\           |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_0\           |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_0\           |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_0\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_0\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_0\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_1\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_1\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_1\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_2\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_2\                |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_2\                |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\            |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\            |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\            |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\                |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\       |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\       |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileBackup\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\       |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\         |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\         |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\         |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_1\         |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_1\         |
    | Docs                      | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\aohghmighlieiainnegkcijnfilokake\0.10_1\         |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_1\         |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_1\         |
    | Google Drive              | 14.2         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\apdfllckaahabafndbhieahigkjlhalf\14.2_1\         |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\        |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\        |
    | YouTube                   | 4.2.8        | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\blpcfgokakmgnkcojhhkbfbldkacnbeo\4.2.8_0\        |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_1\     |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_1\     |
    | Adobe Acrobat             | 15.1.1.2     | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\efaidnbmnnnibpcajpcglclefindmkaj\15.1.1.2_1\     |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\          |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\          |
    | Sheets                    | 1.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\felcaaldnbdncclmgdcncolpebgiejap\1.2_0\          |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_0\          |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_0\          |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_0\          |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_1\          |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_1\          |
    | Google Docs Offline       | 1.7          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\ghbmnnjooekpmoecnnnilnnbdlolhkhi\1.7_1\          |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\      |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\      |
    | Chrome Web Store Payments | 1.0.0.4      | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\nmmhkkegccagdldgiimedpiccmgmieda\1.0.0.4_0\      |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\          |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\          |
    | Gmail                     | 8.2          | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\pjkljhegncpnkpknbcohdijeoejaedia\8.2_0\          |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\ |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\ |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomiBackup\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\ |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomi\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\               |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomi\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\               |
    | Slides                    | 0.10         | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomi\Extensions\aapocclcgogkmnckokdopfmhonfmgoek\0.10_0\               |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomi\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\       |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomi\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\       |
    | Chrome Media Router       | 7619.603.0.2 | C:\Users\nickcollier\AppData\Local\Google\Chrome\User Data\ProfileEloomi\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\7619.603.0.2_0\       |
    +---------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by nickcollier** [comment]
I've just retested this with 4.3.0 and it seems to be fixed

**Comment by directionless** [comment]
Great! I suspect those are different profiles. Fixed by https://github.com/osquery/osquery/pull/6277
