### ISSUE TITLE
osquery not reporting process `cmdline` properly in macos and linux

### ISSUE THREAD

**Issue by prateeknischal** [osquery/osquery#6330]
# Bug report

### What operating system and version are you using?

```
$ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 10.14.6
   build = 18G3020
platform = darwin
```
```
$ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 16.04.3 LTS (Xenial Xerus)
   build =
platform = ubuntu
```
### What version of osquery are you using?

* MacOS
```
$ osqueryi --line "SELECT version from osquery_info;"
version = 4.2.0
```
* Linux
```
$ osqueryi --line "SELECT version from osquery_info;"
version = 4.1.2
```

### What steps did you take to reproduce the issue?
Run a dummy process, eg: `python3 -m http.server` to create a process id `42071` in macos and `15791` in linux in this specific case.

And then query the following:
```
select pid, name, cmdline, uid, elapsed_time from processes where name like "%python%";
```

### What did you expect to see?

```
+-------+---------+------------------------+------+--------------+
| pid   | name    | cmdline                | uid  | elapsed_time |
+-------+---------+------------------------+------+--------------+
| 15791 | python3 | python3 -m http.server | 1002 |              |
+-------+---------+------------------------+------+--------------+
```
### What did you see instead?
I was not able to get the cmdline and the elapsed time in macos, it was all around the place.
```
osquery> select pid, name, cmdline, uid, elapsed_time from processes where name like "%python%";
+-------+--------+---------+-----+--------------+
| pid   | name   | cmdline | uid | elapsed_time |
+-------+--------+---------+-----+--------------+
| 42071 | Python |         | 502 | 521          |
+-------+--------+---------+-----+--------------+
osquery> select pid, name, cmdline, uid, elapsed_time from processes where name like "%python%";
+-------+--------+---------+-----+--------------+
| pid   | name   | cmdline | uid | elapsed_time |
+-------+--------+---------+-----+--------------+
| 42071 | Python |         | 502 | 0            |
+-------+--------+---------+-----+--------------+
osquery> select pid, name, cmdline, uid, elapsed_time from processes where name like "%python%";
+-------+--------+---------+-----+---------------------+
| pid   | name   | cmdline | uid | elapsed_time        |
+-------+--------+---------+-----+---------------------+
| 42071 | Python |         | 502 | 7306086829599451492 |
+-------+--------+---------+-----+---------------------+
```
Linux was able to get the `cmdline` but not the elapsed time.
```
$ osqueryi "select pid, name, cmdline, uid, elapsed_time from processes where name like \"%python%\";"
+-------+---------+------------------------+------+--------------+
| pid   | name    | cmdline                | uid  | elapsed_time |
+-------+---------+------------------------+------+--------------+
| 15791 | python3 | python3 -m http.server | 1002 |              |
+-------+---------+------------------------+------+--------------+
```
with no error on macos and the following error in linux
```
I0325 14:51:24.857920 16390 dynamic_table_row.cpp:123] Error casting elapsed_time () to BIGINT
```

**Comment by premkumar-r1** [comment]
We are facing a similar issue with mac on OSQuery 4.x, It is not returning any values for cmdline.
I see an issue where windows agent is not able to grasp date from PPL.
Also, share some inform, why mac osquery agent is not able to collect `cmdline` data?
Is there any timeline this issue will be fixed?

osquery> select pid, name, start_time, cmdline from processes Limit 15;
+-----+----------------+------------+---------+
| pid | name                     | start_time | cmdline |
+-----+----------------+------------+---------+
| 0    | kernel_task           | 1584971117 |         |
| 1     | launchd                | 1584971117 |         |
| 42  | syslogd                 | 1584971127 |         |
| 43  | UserEventAgent   | 1584971127 |         |
| 45  | sh                           | 1584971127 |         |
| 47  | uninstalled             | 1584971127 |         |
| 48  | kextd                     | 1584971127 |         |
| 49  | fseventsd              | 1584971127 |         |
| 51  | jamf                        | 1584971127 |         |
| 52  | vpnagentd             | 1584971127 |         |
| 57  | appleeventsd        | 1584971127 |         |
| 58  | systemstats          | 1584971127 |         |
| 60  | configd                  | 1584971127 |         |
| 62  | ciscod                    | 1584971127 |         |
| 63  | powerd                  | 1584971127 |         |
+-----+----------------+------------+---------+

**Comment by directionless** [comment]
In general, please don't open an issue for multiple bugs.

Looking at `elapsed_time` I'm not sure that it exists for non-windows platforms. I think I only see the implementation in the windows `processess.cpp`

---

Looking at `cmdline` I agree there was a behavior change. 

It appears to have been refactored in https://github.com/osquery/osquery/commit/f7ec202778fd513ca86e0f35cdd4c323dbe36101

I'm not really sure how https://github.com/osquery/osquery/blob/4.2.0/osquery/tables/system/darwin/processes.cpp#L318-L359 is supposed to work. It looks a bit off to me.

**Comment by theopolis** [comment]
Good find
