### ISSUE TITLE
Improve table description: account_policy_data

### ISSUE THREAD

**Issue by JLsushmaumesh** [osquery/osquery#6345]
# Bug report
Document : https://osquery.io/schema/4.2.0
Table : account_policy_data
Column : failed_login_count 
Existing Description :  The description for the above column specifies "The number of times the user failed to login with the correct password. Resets after a correct password is entered"

Expected Description  : The number of times the user failed to login with the **incorrect** password. Resets after a correct password is entered

Search engine : Google Chrome:

**Comment by Smjert** [comment]
Hi @JLsushmaumesh! I'm not a native english speaker, though "The number of times the user failed to login with the correct password" should mean, written in another way, "The number of times the user failed to use the correct password to login".

That been said, if you want to propose a change for this, modify that sentence is simple, the source code for that description is here: https://github.com/osquery/osquery/blob/46a46da0519de76d10128b3c05984eb5d775cccd/specs/darwin/account_policy_data.table#L6

**Comment by JLsushmaumesh** [comment]
Hi Stefano Bonicatti,

Request you to add the description as updated by you and the extension of the description as below.

Expected : "The number of times the user failed to use the correct password to login. Count resets after a correct password is entered."

Thanks,
Sushma
