### ISSUE TITLE
Did not find libosquery.so ?

### ISSUE THREAD

**Issue by VikasBhumca2006** [osquery/osquery#6348]
# Question : Did not find libosquery.so ?

I have compiled complete osquery as per given instruction.
osqueryi and osquerd were also generated but shared objects were not generated.

Thanks
Vikas

**Comment by Smjert** [comment]
Hi! @VikasBhumca2006, after osquery 3.3.2 the build system totally changed and we do not create a libosquery.so anymore, everything is built statically into the osqueryd binary (except from some system libraries that cannot be linked statically).
I'm not sure which version of build instructions you're looking at but if you're using the master branch you should look at https://osquery.readthedocs.io/en/latest/development/building/

Is there a specific need with having that separated library?

**Comment by theopolis** [comment]
I'm going to close out this issue due to the most likely cause being an older build. If there's more discussion needed please feel free to reopen.

**Comment by AE1020** [comment]
I was going to try something involving chopping out the shell.cpp and main.cpp and writing a different front-end. My interest was piqued by wording saying that there was a SDK with an API, which would make it easier...which I saw in the documentation. By the way, I noticed that the link to `osquery/include/osquery` seems to be broken at the top of the page:

https://osquery.readthedocs.io/en/stable/development/osquery-sdk/

It links to `https://github.com/osquery/osquery/tree/master/include/osquery` when presumably it means `https://github.com/osquery/osquery/tree/master/osquery/include/osquery`.

I found this issue by searching for "libosquery", where you seem to suggest that you only build the executables. So the SDK is intended for plugins only, not alternatives to osqueryd/osqueryi?

I'm okay going with my initial idea to destructively-edit the CMake files to do my experiment. But a non-destructive edit that just offered an optional build target that let you make a static library of "everything but the interface" would be a nice option to have...if that is something which is not-too-hard to make a "blueprint" for.

**Comment by theopolis** [comment]
Good find on the documentation, I'll try to fix that shortly.

> So the SDK is intended for plugins only, not alternatives to osqueryd/osqueryi?

Correct.

> But a non-destructive edit that just offered an optional build target that let you make a static library of "everything but the interface" would be a nice option to have

That sounds cool, I wonder if the `./externals` tooling and subsequent `make externals` could support this use case right now.
