### ISSUE TITLE
OpenSSL 1.1.1d formula error in osquery 4.2.0+

### ISSUE THREAD

**Issue by QuellaZhang** [osquery/osquery#6357]
Hello,

OSQuery latest version c22ab5c404374e5fb7dabbc118d163acf72c1c02 failed to download openssl lib, I could not find openssl-1.1.1d.tar.gz  in https://www.openssl.org/source/, the download path should be updated.

**error:**
CUSTOMBUILD : error : downloading 'https://www.openssl.org/source/openssl-1.1.1d.tar.gz' failed [F:\gitP\facebook\osquery\build\openssl\openssl.vcxproj]
         CUSTOMBUILD : The requested URL returned error : 404 Not Found [F:\gitP\facebook\osquery\build\openssl\openssl.vcxproj]
         CUSTOMBUILD : error : downloading 'https://www.openssl.org/source/openssl-1.1.1d.tar.gz' failed [F:\gitP\facebook\osquery\build\openssl\openssl.vcxproj]
         CUSTOMBUILD : The requested URL returned error : 404 Not Found [F:\gitP\facebook\osquery\build\openssl\openssl.vcxproj]
         CUSTOMBUILD : error : downloading 'https://www.openssl.org/source/openssl-1.1.1d.tar.gz' failed [F:\gitP\facebook\osquery\build\openssl\openssl.vcxproj]
         CUSTOMBUILD : The requested URL returned error : 404 Not Found [F:\gitP\facebook\osquery\build\openssl\openssl.vcxproj]

**Comment by alessandrogario** [comment]
Hello @QuellaZhang 

The tarball has been moved into the 'old' subfolder, as you can see here: https://www.openssl.org/source/old/1.1.1/openssl-1.1.1d.tar.gz

The OpenSSL formula is being updated by @Smjert so that it will automatically try both the `source` and the `source/old` folders.

There is however an additional issue preventing OpenSSL 1.1.1x from working correctly, so as a temporary fix it is best to revert commit c22ab5c

**Comment by QuellaZhang** [comment]
Thanks for the update. OSQuery still failed to build when I revert back to commit 3486bf3, I see the same download error in build/formula_logs/openssl.txt. I also hit this error in other old commit.

**error info:**
23>CustomBuild:
     Running formula: openssl (F:/gitP/facebook/osquery/build/formula_logs/openssl.txt)
23>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [F:\gitP\facebook\osquery\build\openssl_formula_runner.vcxproj]
**openssl.txt**: [openssl.txt](https://github.com/osquery/osquery/files/4425665/openssl.txt)
Retry after 60 seconds (attempt #5) ...
  -- Using src='https://www.openssl.org/source/openssl-1.1.1d.tar.gz'
  CMake Error at openssl-stamp/download-openssl.cmake:159 (message):
    Each download failed!

**Comment by theopolis** [comment]
Hi @QuellaZhang, sorry for the trouble. Can you try building from master again, the problem should be fixed.

**Comment by QuellaZhang** [comment]
Thanks @theopolis , verified this issue has been fixed, closed this issue.
