### ISSUE TITLE
osquery v4.2.0 doesn't work with TLS Server through a proxy but osquery v4.0.2 worked

### ISSUE THREAD

**Issue by macEar** [osquery/osquery#6382]
# Bug report

### What version of osquery are you using?

```
select osquery.version from osquery_info osquery;
```
hostname | version
-- | --
*** | 4.2.0

### What steps did you take to reproduce the issue?

We had osquery v4.0.2 installed on all the servers (mostly Linux) some time ago. Some of them worked as follows:

osquery ---> stunnel -----> Kolide Fleet

OR

osquery ----> nginx ------> Kolide Fleet

Everything worked fine, as we expected it to work.

Then new version of osquery was released (v4.2.0), we started to upgrade osquery everywhere and noticed that abovementioned flowchart was broken, and osquery complained:

```W0331 16:44:05.693001  9886 tls_enroll.cpp:76] Failed enrollment request to https://<proxy-ip>:8412/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...```

We've checked the certificate and enrollment key, they are correct.

`stunnel` configuration (stunnelsrv.conf):

```
[osqueryd]
accept = x.x.x.x:8412
connect = y.y.y.y:8412
```

Also noticed the alike behavior for nginx proxy although we almost don't use it. When I tried to set nginx as a proxy, osquery showed up for several minutes in Kolide Fleet, and then displayed as turned off but actually it was running. Osquery accessing the Kolide server through the `nginx` was installed on Windows, and osquery accessing the Kolide server through `stunnel` was installed on a Linux server.

nginx configuration:

```
server {
    listen 80;
    server_name AAAA;
    return 301 https://$host$request_uri;
}

server {
    error_log /var/log/nginx/kolide_error.log warn;

    server_name AAAA;
    
    listen 443 ssl;
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;

    location / {
      proxy_pass https://KOLIDE-FLEET:8412/;
      proxy_set_header Host $host:$proxy_port;
      proxy_set_header X_FORWARDED_PROTO https;
    }
}

```

### What did you expect to see?

Osquery v4.2.0 works fine with TLS server (Kolide Fleet in out case) through Proxy (stunnel in our case)

### What did you see instead?

Osquery didn't work through a proxy and log the following:

```
W0331 16:44:05.693001  9886 tls_enroll.cpp:76] Failed enrollment request to https://<proxy-ip>:8412/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
```

**Comment by theopolis** [comment]
This is most likely what changed: https://github.com/osquery/osquery/pull/6197 prior to this bug fix osquery was not checking the CN/SAN in certificates.

I believe you are TLS terminating in `stunnel` and `nginx` so the certificate they present must be valid for the hostname osquery intends to connect to, `AAAA`.

Based on "`https://<proxy-ip>:8412`" I am guessing there is a difference between what osquery knows it is connecting to vs. the CN/SAN present in the certificate.

**Comment by macEar** [comment]
@theopolis thanks for your reply!

In our **osquery.flags** we have:

```
--tls_server_certs=/etc/osquery/server.pem
--tls_hostname=<proxy-ip>:8412
```

* In `server.pem` the FQDN of our Kolide Fleet server is set as CN/SAN, but the `tls_hostname` parameter is different from that. Therefore to solve the problem, we have to specify the FQDN corresponding to CN/SAN in the server.pem, right?

* Or otherwise we can issue server certificate for our proxy and place it as osquery tls_server_cert, and tls_hostname in this case remains to be proxy-ip. On the proxy we have to decrypt osquery traffic and re-encrypt it with the Kolide Fleet server certificate (`server.pem` specified above). Will it work so?

Are there any other solutions  to this issue? Do we need to change something with the enrollment secret? If I get it right, we don't
