### ISSUE TITLE
Adding disable_events to the config files slows down osquery's exit

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6383]
While investigating #6329, I noticed that osquery is sometimes oddly slow to exit. I'm not sure it it represents a deeper issue, or what. Mostly reported for the paper trail.

Running off a master build:
```
dover:build seph$ ./osquery/osqueryi  'select version from osquery_info'
+---------------------+
| version             |
+---------------------+
| 4.2.0-63-g702a6e049 |
+---------------------+
```

Some baseline... On my machine, with my usual load. Running osquery  with a single select one takes 0.25s:
```
dover:build seph$ time ./osquery/osqueryi  'select 1' > /dev/null 

real	0m0.257s
user	0m0.039s
sys	0m0.011s
dover:build seph$ time ./osquery/osqueryi  --ephemeral 'select 1' > /dev/null 

real	0m0.256s
user	0m0.040s
sys	0m0.009s
dover:build seph$ time ./osquery/osqueryi  --ephemeral --disable_events=false 'select 1' > /dev/null 

real	0m0.259s
user	0m0.044s
sys	0m0.011s
```

An empty config file, still 0.25s

```
dover:build seph$ cat /tmp/osq-empty.conf
{   
    "options": {
    }
}

dover:build seph$ time ./osquery/osqueryi  --ephemeral --config_path=/tmp/osq-empty.conf 'select 1'  > /dev/null 

real	0m0.268s
user	0m0.040s
sys	0m0.011s
```

But... if I add a `disable_events=false` option, which is the default, suddenly it takes twice as long?
```
dover:build seph$ cat /tmp/osq-events.conf 
{   
    "options": {
        "disable_events": "false"
    }
}

dover:build seph$ time ./osquery/osqueryi --config_path /tmp/osq-events.conf --ephemeral  'select 1' > /dev/null 

real	0m0.466s
user	0m0.044s
sys	0m0.016s
```
(You can't see it, but the slowness is _after_ the data is printed).

Curiously, if the config file is `disable_events=true`, there is no slowdown.

I've only tested a handful of options. Not sure here.

**Comment by theopolis** [comment]
Events are disabled in the Shell by default. Enabling them adds startup and tear down cost (and time).

**Comment by theopolis** [comment]
There is logic that tries to predict how you are using the shell and disable multiple features: https://github.com/osquery/osquery/blob/master/osquery/main/main.cpp#L120

However, these can be overridden by the config.

**Comment by directionless** [comment]
Ah, that makes sense. Thanks for going over the automated guessing. 

I was, embarrassingly, also turned around by the double negative.
