### ISSUE TITLE
Query list of deb/rpm packages from containers

### ISSUE THREAD

**Issue by thedrow** [osquery/osquery#6388]
# Blueprint

Currently we only allow users to query the list of deb or rpm packages from the root filesystem.
This is an issue if you have multiple containers on the system which shouldn't run instances of OSQuery on their own.

We can create a hidden `root_path` column to allow users to set the root path from.
Afterwards, we can use it to create specialized tables for Docker containers, LXC containers or any other sysroot path we have on the system.

**Comment by Smjert** [comment]
Hi @thedrow, I think what you're referring to has been done in the following PRs https://github.com/osquery/osquery/pull/6209 and https://github.com/osquery/osquery/pull/6218, soon to be merged (though probably after the 4.3.0 release).

There is also a blueprint here: https://github.com/osquery/osquery/issues/5975

**Comment by thedrow** [comment]
Oh, I was thinking about something simpler.
Since you don't really need to enter a namespace to query packages you can simply introduce a hidden column for the sysroot and use that.
Whatever works is fine by me though.

**Comment by directionless** [comment]
https://github.com/osquery/osquery/pull/6414 merged. Which provides access via the pid. I'm closing this. Feel free to comment if you think it needs something additional.
