### ISSUE TITLE
How to Convert Chrome Browser History Sqlite Timestamps with Osquery

### ISSUE THREAD

**Issue by dbuehler77** [osquery/osquery#6390]
As I understand, the Chrome browser uses the WebKit time format for timestamps within the browser history database. WebKit time is expressed as milliseconds since January, 1601.

I've found numerous articles that seemingly have the answer to my question, but none have worked so far. The common answer is to use the formula below to convert from WebKit to a human-readable, localtime:

`SELECT datetime((time/1000000)-11644473600, 'unixepoch', 'localtime') AS time FROM table;`

Sources: https://linuxsleuthing.blogspot.com/2011/06/decoding-google-chrome-timestamps-in.html What is the format of Chrome's timestamps?

I'm trying to convert the timestamps while gathering the data through Osquery, using the configuration below.

`"chrome_browser_history" : {
            "query" : "SELECT urls.id id, urls.url url, urls.title title, urls.visit_count visit_count, urls.typed_count typed_count, urls.last_visit_time last_visit_time, urls.hidden hidden, visits.visit_time visit_time, visits.from_visit from_visit, visits.visit_duration visit_duration, visits.transition transition, visit_source.source source FROM urls JOIN visits ON urls.id = visits.url LEFT JOIN visit_source ON visits.id = visit_source.id",
            "path" : "/Users/%/Library/Application Support/Google/Chrome/%/History",
            "columns" : ["path", "id", "url", "title", "visit_count", "typed_count", "last_visit_time", "hidden", "visit_time", "visit_duration", "source"],
            "platform" : "darwin"
        },
        "chrome_login_keychain" : {
            "query" : "SELECT origin_url, action_url, username_value, password_element FROM logins",
            "path" : "/Users/%/Library/Application Support/Google/Chrome/Default/Login Data",
            "columns" : ["origin_url", "action_url", "username_value", "password_element"],
            "platform" : "darwin"
        }
    },

    "schedule": {
        "chrome_history": {
        "query": "select distinct url,datetime((last_visit_time/1000000)-11644473600, 'unixepoch', 'localtime') AS time from chrome_browser_history where url like '%nhl.com%';",
        "interval": 10
        }
    }`
 

The resulting events have timestamps from the year 1600:

`"time":"1600-12-31 18:46:16"`

If I change the config to pull the raw timestamp with no conversion, I get stamps such as the following:

`"last_visit_time":"1793021894"`

From what I've read about WebKit time, it is expressed in 17-digit numbers, which clearly is not what I'm seeing. So I'm not sure if this is an Osquery, Chrome, or query issue at this point. All help and insight appreciated!

**Comment by Smjert** [comment]
Hi @dbuehler77, welcome!

I'm sorry but that table is not something that comes with the official upstream release, so you will have to check with the provider of that table.
