### ISSUE TITLE
Unknown CMake command "add_osquery_library".

### ISSUE THREAD

**Issue by gbedoya** [osquery/osquery#6394]
Hi, I'm using the following documentation to build osquery 4.3.0
https://osquery.readthedocs.io/en/latest/development/building/

However, when using the osquery toolchain I encounter the following error ...
```
cmake -DCMAKE_BUILD_TYPE=Release -DOSQUERY_TOOLCHAIN_SYSROOT=/usr/local/osquery-toolchain .. -Wno-dev
CMake Error at process/CMakeLists.txt:25 (add_osquery_library):
  Unknown CMake command "add_osquery_library".
Call Stack (most recent call first):
  process/CMakeLists.txt:8 (generateOsqueryProcess)
  process/CMakeLists.txt:51 (osqueryProcessMain)


-- Configuring incomplete, errors occurred!
See also "/[...]/osquery/osquery/build/CMakeFiles/CMakeOutput.log".
```

Further, I noticed that Azure Pipelines leverages
```usr/bin/docker pull trailofbits/osquery:ubuntu-18.04-toolchain-v8```

How can I build the toolchain for Debian Buster and fix `add_osquery_library` cmake error? Thanks.

**Comment by Smjert** [comment]
Hello @gbedoya, that's odd, I've recently built the 4.3.0 package on a new VM with Ubuntu 18.04, but this shouldn't matter; that function is defined by our CMake code, so it should've been picked up anyway.

If you haven't already, could you please try to delete all the build folder contents and retry?
If you already started from scratch: please delete again and this time append `--trace-expand 2>&1 cmake.log` to the configure command, then please upload that file here; thanks!

**Comment by gbedoya** [comment]
@Smjert I've attached cmake.log and I'm trying to build on Debian Buster.

[cmake.log](https://github.com/osquery/osquery/files/4482178/cmake.log)

Last commits in git ...
```
commit a9b5df4984d6884f6cb4966d25afa7355da22396
[...]
commit e5f9a8dd7a8ba8a69a3ab4f93b6842efa4788c33
Author: Stefano Bonicatti <stefano.bonicatti@gmail.com>
Date:   Tue Apr 14 16:53:39 2020 +0200
    release: updating changelog for 4.3.0 release (#6387)
```

Note: `/build` deleted and re-created

**Comment by Smjert** [comment]
@gbedoya The issue seems that the cmake call is not using the root CMakeLists.txt and you have a build folder inside the internal osquery source folder.

The layout the wiki guides you to should be
```
osquery
  - build
  - cmake
  - docs
  - external
  - libraries 
  - osquery
  [...]
```

Instead you have:
```
osquery
  - cmake
  - docs
  - external
  - libraries 
  - osquery
     - build
```

The build folder has to be inside the root folder (or even outside it), and you should be targeting the root folder.

**Comment by gbedoya** [comment]
New build is incredibly fast compared to 3.x. Thanks.
