### ISSUE TITLE
Third party libraries to be ported to build from source

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6400]
This is the list of third party libraries we still need to port so that they build from source on the respective platforms:

- [x] linenoise-ng on macOS, Windows
- [x] lldpd on macOS
- [x] popt on macOS
- [x] sleuthkit on macOS
- [x] smartmontools on macOS
- [x] ssdeep-cpp on macOS

**Comment by theopolis** [comment]
What about the python modules?

**Comment by Smjert** [comment]
> What about the python modules?

Initially I wanted to install them from the system, but indeed they are used to generate the tables from the specs; I don't envision a different version resulting in major changes in the output, but still.

Looking at what they should do, we could even just write a simply python script ourselves that does what the jinja2 module does, because it seems pretty simple.
The less dependencies the better no?

Also, I think eventually we want to drop generation entirely.

**Comment by mike-myers-tob** [comment]
Linking to the PRs:

https://github.com/osquery/osquery/pull/6464
https://github.com/osquery/osquery/pull/6465
