### ISSUE TITLE
Windows authenticode table does not show built-in Windows files as signed

### ISSUE THREAD

**Issue by sroache** [osquery/osquery#6401]
# Bug report

### What operating system and version are you using?

```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.18941 | 18941 | windows  |
+------------+-------+----------+
```
and
```
+----------+-------+----------+
| version  | build | platform |
+----------+-------+----------+
| 6.1.7601 | 7601  | windows  |
+----------+-------+----------+
```

### What version of osquery are you using?

4.2.0

### What steps did you take to reproduce the issue?
Tried to get the authenticode results for built-in Windows tool i.e notepad.exe
```
SELECT * FROM authenticode WHERE path='C:\Windows\System32\notepad.exe';
```
### What did you expect to see?
Expected to see that the executable was signed by Microsoft in the same way that sigcheck (from sysinternals) shows:
![image](https://user-images.githubusercontent.com/48997543/79574036-7647aa00-80b7-11ea-840d-57e6db927863.png)

### What did you see instead?
![image](https://user-images.githubusercontent.com/48997543/79573804-16e99a00-80b7-11ea-9f2f-0e790bfbe4a2.png)

This behaviour has been discussed here: https://blog.didierstevens.com/2008/01/11/the-case-of-the-missing-digital-signatures-tab/ and is a result of the signature for the hash of the file is stored in a security catalog on the machine.

**Comment by farfella** [comment]
@theopolis I can work on updating osquery after the unicode PR is in, unless someone else wants to work on it. Basically, 1) involves checking cat files for the file hash, 2) updating the table to convey the location of authenticode.

**Comment by clong** [comment]
Just came across this same issue today, this would be such an amazing capability to add to the authenticode table if someone has the knowledge to accomplish it

**Comment by farfella** [comment]
:) I'll work on it in about two weeks, unless someone else wants to jump in.
