### ISSUE TITLE
Warning: DEFAULT entry missing in drive database file(s)  

### ISSUE THREAD

**Issue by maomj2008** [osquery/osquery#6421]
# Bug report

### What version of osquery are you using?
4.2.0

### What steps did you take to reproduce the issue?
osquery>
Warning: DEFAULT entry missing in drive database file(s)
  Configuration setting "activation/vdo_pool_autoextend_threshold" unknown.
  Configuration setting "global/event_activation" unknown.
  Configuration setting "devices/scan_lvs" unknown.
### What did you expect to see?
all disk data list and result write to log files,but not created result logs
### What did you see instead?
Warning: DEFAULT entry missing in drive database file(s)
  Configuration setting "activation/vdo_pool_autoextend_threshold" unknown.
  Configuration setting "global/event_activation" unknown.
  Configuration setting "devices/scan_lvs" unknown.

**Comment by theopolis** [comment]
I'm not familiar with these errors, are you using any osquery extensions? Any ideas on how we can reproduce these?

**Comment by theopolis** [comment]
Hi, I am closing this out due to inactivity. Let us know if there is still an issue, and if so please provide specific details about how we can reproduce the issue.
