### ISSUE TITLE
PID from processes not correct after JOIN

### ISSUE THREAD

**Issue by sevickson** [osquery/osquery#6427]
# Bug report

### What operating system and version are you using?
``` 
version = 10.0.18363
build = 18363
platform = windows 
```

### What version of osquery are you using?
``` version = 4.3.0 ```

### What steps did you take to reproduce the issue?
Ran following JOIN in osqueryi.
``` SELECT p.parent,p.pid,p.name,o.pid,o.state FROM process_open_sockets o INNER JOIN processes p ON o.pid = p.parent WHERE p.name LIKE 'firefox.exe' AND p.parent <> p.pid; ```

### What did you expect to see?
Expected a difference between parent and PID columns.
Checked it with.
```select pid,name,parent from processes where name='firefox.exe' and parent <> pid;```
```
+--------+-------+-------------+
| parent | pid   | name        |
+--------+-------+-------------+
| 18996  | 19016 | firefox.exe |
| 19016  | 18796 | firefox.exe |
| 19016  | 20068 | firefox.exe |
| 19016  | 18184 | firefox.exe |
| 19016  | 23496 | firefox.exe |
| 19016  | 17608 | firefox.exe |
| 19016  | 13980 | firefox.exe |
| 19016  | 22632 | firefox.exe |
| 19016  | 16880 | firefox.exe |
| 19016  | 20028 | firefox.exe |
+--------+-------+-------------+
```
Expected to see above PID numbers.
### What did you see instead?
All results had the same parent and PID.
```
+--------+-------+-------------+-------+-------------+
| parent | pid   | name        | pid   | state       |
+--------+-------+-------------+-------+-------------+
| 19016  | 19016 | firefox.exe | 19016 | ESTABLISHED |
| 19016  | 19016 | firefox.exe | 19016 | ESTABLISHED |
| 19016  | 19016 | firefox.exe | 19016 | ESTABLISHED |
| 19016  | 19016 | firefox.exe | 19016 | ESTABLISHED |
| 19016  | 19016 | firefox.exe | 19016 | ESTABLISHED |
| 19016  | 19016 | firefox.exe | 19016 | ESTABLISHED |
```

**Comment by theopolis** [comment]
I think the issue is the column name collision in your first query. Try aliasing, for example `p.pid as pid1` and `o.pid as pid2`.

**Comment by mike-myers-tob** [comment]
> I think the issue is the column name collision in your first query. Try aliasing, for example `p.pid as pid1` and `o.pid as pid2`.

@sevickson it has been 20 days without a response, so I will close this issue. If Teddy's suggestion did not resolve your issue, comment and we can reopen it.

**Comment by siikamiika** [comment]
I ran into this as well and I think it's a bit confusing for someone who expects it to work just like sqlite:

```sql
sqlite> create table test1 (id INTEGER, value TEXT);
sqlite> create table test2 (id INTEGER, value TEXT);
sqlite> insert into test1 (id, value) values (1, 'a'), (2, 'b');
sqlite> insert into test2 (id, value) values (2, 'a'), (3, 'b');
sqlite> select t1.id, t2.id, t1.value, t2.value from test1 t1 join test2 t2 on t1.value = t2.value;
1|2|a|a
2|3|b|b
```

though I can confirm that aliasing makes it work in osquery too.

From the docs:
> The osquery SQL language is a superset of SQLite's. Please read SQL as understood by SQLite for reference. This is a great starting place if coming from MySQL, PostgreSQL, or MSSQL.
