### ISSUE TITLE
File name exceeds the OS max path limit

### ISSUE THREAD

**Issue by QuellaZhang** [osquery/osquery#6439]
Hi all,

We building OSQuery latest version 34c8ac3 on MSVC, it failed due to file name exceeds the OS max path limit, we put source code under "F:\gitP\facebook\osquery", can you help look?

build log: [osquery_build.log](https://github.com/osquery/osquery/files/4621394/osquery_build.log)

error:
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(325,5): error MSB3491: Could not write lines to file "x64\Release\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h\osquery_.482695D9.tlog\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h.lastbuildstate". Path: x64\Release\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h\osquery_.482695D9.tlog\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h.lastbuildstate exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [F:\gitP\facebook\osquery\build\osquery\worker\ipc\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h.vcxproj]

**Comment by Smjert** [comment]
Hello @QuellaZhang, although we have some long targets name here and there, this is a really an issue of msbuild/Windows.
It creates deep paths that easily fill the very limited max path of 260 chars.
The quick solution is to just move the build folder higher up the hierarchy.

We will try to shorten those paths but then long term solution is msbuild actually support long path names; it appears that it was done, but there are still issues:https://github.com/microsoft/msbuild/issues/5331

**Comment by QuellaZhang** [comment]
Thanks @Smjert , I shortened the file names as a workaround, and now OSQuery is built successfully.

**Comment by theopolis** [comment]
For posterity, if anyone else hits this issue I tend to build at `C:\build`, this is where I run `CMake` the osquery sourcecode is elsewhere.
