### ISSUE TITLE
Screenlock issue while using osqueryctl.

### ISSUE THREAD

**Issue by nawang87** [osquery/osquery#6451]
# Bug report

### What operating system and version are you using?
 version = 10.15.4
   build = 19E287
platform = darwin

### What version of osquery are you using?

version = 4.3.0

### What steps did you take to reproduce the issue?
Below screen lock query was scheduled to run using osqueryctl start command.

		"schedule": {
		"screenlock_info": {
		"query": "SELECT * FROM screenlock;",
		"interval": "60"
		}

### What did you expect to see?
When running osqueryd --verbose it runs smoothly.

I0518 22:06:01.281826 48214016 scheduler.cpp:96] Executing scheduled query screenlock_info: select * from screenlock;
I0518 22:06:01.337699 48214016 scheduler.cpp:159] Found results for query: screenlock_info

### What did you see instead?
But when executed as daemon it is showing below error.
osquery.INFO log

I0519 09:19:09.690701 166711296 scheduler.cpp:96] Executing scheduled query screenlock_info: select * from screenlock;
I0519 09:19:09.742617 166711296 screenlock.mm:62] MKBDeviceGetGracePeriod did not return an NSDictionary

**Comment by theopolis** [comment]
@terracatta, and ideas?

**Comment by directionless** [comment]
As mentioned in #6243

> I want to point out a functional limitation of this table. The API I am using is only capable of returning results when a user is signed in via the GUI. This table will not produce any rows in a situation where launchctl is running the device outside of the logged in user's context.

Are you running into that?

(Despite those limitations, we find this table quite valuable)
