### ISSUE TITLE
osqueryi segfaults when querying package_bom

### ISSUE THREAD

**Issue by williamtheaker** [osquery/osquery#6455]
# Bug report

### What operating system and version are you using?

macOS 10.15.4 19E287

### What version of osquery are you using?

4.3.0

### What steps did you take to reproduce the issue?

```
osqueryi --line "select * from package_bom where path == '/private/var/db/receipts/com.facebook.osquery.bom';"
Thrift: Wed May 20 10:16:43 2020 TSocket::open() connect() <Host:  Port: 0>Connection refused
zsh: segmentation fault  osqueryi --line 
```

Using `where path LIKE` doesn't segfault.

**Comment by gbedoya** [comment]
Here's additional info. However, it looks like optimizations need to be disabled.
```
(lldb) process launch
Process 81444 launched: '/.../software/osquery/build/osquery/osqueryd' (x86_64)
osqueryd was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 81444 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001003ede6b osqueryd`osquery::tables::BOM::getVariable(this=0x00007ffeefbfe460, offset=0x00007ffeefbfe458) const at packages.mm:141:36 [opt]
   138 	    return nullptr;
   139 	  }
   140
-> 141 	  *offset += sizeof(BOMVar) + var->length;
   142 	  return var;
   143 	}
   144
(lldb) frame variable --no-args
(const osquery::tables::BOMVar *) var = 0x6d6f420701000000
```

**Comment by theopolis** [comment]
This is reproducible, can someone please investigate a fix.

**Comment by zwass** [comment]
Does anyone know whether this table ever worked? If so, when?

It looks like the parsing of the BOM file is going wrong, and the best documentation of the format I could find was in https://github.com/facebook/xcbuild/blob/master/Libraries/libbom/Headers/bom/bom_format.h, which seems to be what the osquery code is adapted from.

**Comment by theopolis** [comment]
It did, but I see the bug and I also had that question.
