### ISSUE TITLE
Provide `tools` with osquery package

### ISSUE THREAD

**Issue by zachzeid** [osquery/osquery#6481]
# Feature request
Provide `tools` directory as a part of the osquery package

### What new feature do you want?

I want to be able to run profile.py and other useful tools provided by osquery as a part of the osquery package
### How is this new feature useful?
It is useful as it removed an added step in getting tools to test instances, git runners either through manual intervention or scripting for automation.

**Comment by directionless** [comment]
I don't think these tools are very polished, or suitable for distribution. I'm against shipping them in the packages. I think it's easy enough to download them from github.

If there's enough interest, I think it might be reasonable to improve profiling, or add something to osquery itself. But I'm not sure there's solid interest.

I think there's also a fundamental issue where the profiler can only guess at likely cpu and memory consumption. Much depends on your fleet specifics. Things like the `shard` parameter, or create test groups of hosts is going to be a more real-world way to handle this.
