### ISSUE TITLE
proxy_hostname doesn't work with ec2_instance_tags

### ISSUE THREAD

**Issue by kit837** [osquery/osquery#6499]
# Bug report

### What operating system and version are you using?

```
$ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 8 (jessie)
   build =
platform = debian
```

### What version of osquery are you using?

```
$ osqueryi --line "SELECT version from osquery_info";
version = 4.3.0
```
### What steps did you take to reproduce the issue?

- Do not set any AWS_* environment variables
- Provide a `--proxy_hostname` option to osquery
- Query the `ec2_instance_tags` table

```
$ osqueryi 'select * from ec2_instance_tags' --line --proxy_hostname=my-cool-web-proxy
E0611 20:29:57.642669 24350 aws_util.cpp:200] Exception making HTTP request to URL (http://169.254.169.254/latest/meta-data/iam/security-credentials): Forbidden6
E0611 20:29:57.646518 24350 aws_util.cpp:200] Exception making HTTP request to URL (http://169.254.169.254/latest/meta-data/iam/security-credentials): Forbidden6
E0611 20:29:59.653091 24350 aws_util.cpp:200] Exception making HTTP request to URL (http://169.254.169.254/latest/meta-data/iam/security-credentials): Forbidden!o
E0611 20:30:03.664094 24350 aws_util.cpp:200] Exception making HTTP request to URL (http://169.254.169.254/latest/meta-data/iam/security-credentials): Forbidden6
E0611 20:30:11.674067 24350 aws_util.cpp:200] Exception making HTTP request to URL (http://169.254.169.254/latest/meta-data/iam/security-credentials): Forbidden6
```

### What did you expect to see?

I expect that osquery does not use `proxy_hostname` to access the link local address 169.254.169.254.

The `ec2_instance_metadata` table appears to work when used with a proxy:
```
$ osqueryi 'select * from ec2_instance_metadata' --line --proxy_hostname=my-cool-web-proxy
      instance_id = i-deadbeef
```

The `ec2_instance_tags` table works when I do not specify a proxy, or when I manually specify AWS credentials in the environment.
```
$ osqueryi 'select * from ec2_instance_tags' --line # works as expected
instance_id = i-deadbeef
        key = CoolKey
      value = Banana
```

### What did you see instead?

osquery attempted to use my proxy server to access the link local address 169.254.169.254 and failed.

**Comment by theopolis** [comment]
Hi @kit837, I did some testing and it appears that instance tags are not available from the local metadata service. They are retrieved by connecting to and querying EC2.

Perhaps I am mistaken? But it looks like we need a full remote web client for this table.

**Comment by kit837** [comment]
Hi @theopolis, the tags themselves are retrieved using the EC2 API. Here the local metadata service is used to get the [instance profile IAM credentials](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials).

If you specify the credentials through some other method (e.g. environment variables) the metadata endpoint will not be used.

**Comment by theopolis** [comment]
Thanks, I think I understand this better now. This might not be easily solvable based on how the HTTP client works. We’d have to move the local authority check into the core client logic. I’ll experiment today or tomorrow.
