### ISSUE TITLE
Azure tables are missing

### ISSUE THREAD

**Issue by sroache** [osquery/osquery#6501]
# Bug report

### What operating system and version are you using?

Seen on different platforms

### What version of osquery are you using?

4.3.0

### What steps did you take to reproduce the issue?

Attempting to query azure_instance_metadata or azure_instance_tags

### What did you expect to see?

I expected for the tables to be available as per: https://osquery.io/schema/4.3.0/#azure_instance_metadata

### What did you see instead?
 
I saw table not found errors.
![image](https://user-images.githubusercontent.com/48997543/84669306-9f03e880-af1c-11ea-8347-e04aef824d2e.png)

**Comment by theopolis** [comment]
Good find!
