### ISSUE TITLE
multiple root users on ubuntu 20.04

### ISSUE THREAD

**Issue by zpravaiz** [osquery/osquery#6503]
I am running 4.3 on Ubuntu 20.04. When I use "select * from users" I see two root accounts with UID 0 and one with shell /bin/bash one  /bin/sh. I check my /etc/passwd it has only one root user. Same behavior I notice on 2 of my Linux box. Anyone can shed some light?
Thanks

**Comment by theopolis** [comment]
This is what I see on 18.04:

```
osquery> select * from users where uid = 0;
+-----+-----+------------+------------+----------+-------------+-----------+-----------+------+
| uid | gid | uid_signed | gid_signed | username | description | directory | shell     | uuid |
+-----+-----+------------+------------+----------+-------------+-----------+-----------+------+
| 0   | 0   | 0          | 0          | root     | root        | /root     | /bin/bash |      |
+-----+-----+------------+------------+----------+-------------+-----------+-----------+------+
osquery> select * from os_version;
+--------+-----------------------------+-------+-------+-------+-------+----------+---------------+----------+--------+
| name   | version                     | major | minor | patch | build | platform | platform_like | codename | arch   |
+--------+-----------------------------+-------+-------+-------+-------+----------+---------------+----------+--------+
| Ubuntu | 18.04.4 LTS (Bionic Beaver) | 18    | 4     | 0     |       | ubuntu   | debian        | bionic   | x86_64 |
+--------+-----------------------------+-------+-------+-------+-------+----------+---------------+----------+--------+
osquery> 
```

**Comment by zpravaiz** [comment]
Hi

if I add where clause then I get one row only as you got. But if you see
another screenshot when I grep I do get 2 rows. This is on ubuntu 20.04  I
have tested on Kali Linux it looks fine there.

Thanks for responding.

**Comment by theopolis** [comment]
Hi @zpravaiz, do you mind posting the screenshots you are referencing to the GitHub issue: https://github.com/osquery/osquery/issues/6503.

**Comment by zpravaiz** [comment]
![Screen Shot 2020-06-18 at 8 48 06 AM](https://user-images.githubusercontent.com/16450618/85938376-f1320a00-b91d-11ea-87a6-b8dbfc569b5a.png)
![Screen Shot 2020-06-18 at 8 47 36 AM](https://user-images.githubusercontent.com/16450618/85938378-f2fbcd80-b91d-11ea-8244-6111e2ff2ec2.png)
![Screen Shot 2020-06-18 at 8 46 26 AM](https://user-images.githubusercontent.com/16450618/85938379-f3946400-b91d-11ea-8db2-edd948544a1a.png)

Sorry, somehow I forget to upload the screenshots.

Thanks

**Comment by theopolis** [comment]
It looks like osquery is working as intended here. If you run the command `getent passwd` it should list the same data.

The reason there are two UID `0` and `65534` is because this OS has both `passwd` and `systemd` NSS sources configured. Based on my understanding the final two rows are default `DynamicUser`s created by systemd.

A good follow up here is to label each user in osquery's output with the NSS source. However I am not sure what APIs exist to discover this information, aka I am not sure if this is possible. I do not see a way for us to "hide" these dynamic users either.
