### ISSUE TITLE
Feature: implement macos_security baseline profiles

### ISSUE THREAD

**Issue by hazcod** [osquery/osquery#6504]
# Feature request
The https://github.com/usnistgov/macos_security project is created to output several baseline security profiles or macos.

### What new feature do you want?
Implement these profiles as osquery ruleset.

### How is this new feature useful?
A lot of security detections.

**Comment by directionless** [comment]
This seems like it would be a great project. But I think also something better to fitting inside [macos_security](https://github.com/usnistgov/macos_security). I see that they already have some `check` fields, implementing those in osquery feels pretty natural. Or perhaps something standalone, akin to https://github.com/teoseller/osquery-attck
