### ISSUE TITLE
osquery_sdk_pluginsdk compiles /MD on Windows

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#6509]
# Bug report

### What operating system and version are you using?

osquery> SELECT version, build, platform FROM os_version;
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.17763 | 17763 | windows  |
+------------+-------+----------+

### What steps did you take to reproduce the issue?
Clone osquery on windows

Powershell:
C:\git\osquery> mkdir build; cd build
C:\git\osquery\build> cmake -G "Visual Studio 16 2019" -A x64 -T v141 .. -DOSQUERY_BUILD_TESTS=ON

### What did you expect to see?
osquery_sdk-pluginsdk building with /MT

### What did you see instead?
osquery_sdk-pluginsdk building with /MD

### Description
I am unsure if this a bug or by design, osquery sdk (https://github.com/osquery/osquery/blob/master/osquery/sdk/CMakeLists.txt#L20) is generated without "osquery_cxx_settings" and ends up building as /MD. Is this intentional? 

![image](https://user-images.githubusercontent.com/48999626/85026175-44fb6100-b170-11ea-9d5b-8f16b0986bc2.png)

**Comment by theopolis** [comment]
@Smjert, just to confirm, this looks like an oversight.

**Comment by Smjert** [comment]
@theopolis definitely seems so, @Breakwell good find!
