### ISSUE TITLE
table cache not considering columns used

### ISSUE THREAD

**Issue by amalone-scwx** [osquery/osquery#6510]
# Bug report

I was looking at the table cache code in `osquery/core/tables.cpp` and noticed that it does not check whether the query has all the columns requested.  In reality, the query cache is only useful for full table scans with all the columns requested.  Virtual table implementations can optimize and only fetch and return the columns requested.  Consider the following two queries, where the first one executes, and the second one uses the cache.  The second  query ends up acting on cmdline fields that are empty, since the processes table (on windows) checks `if (context.isColumnUsed("cmdline")) ` before fetching that information:

- `SELECT pid, name, path FROM processes`
- `SELECT * FROM processes WHERE cmdline LIKE '%baddie%'`

relevant code:

![image](https://user-images.githubusercontent.com/58046369/85076482-d32e1200-b185-11ea-9902-a9135b02ba2c.png)

**Comment by directionless** [comment]
This was fixed by #6513, right?
