### ISSUE TITLE
[Parrot OS] listening_ports is not returning some results 

### ISSUE THREAD

**Issue by anelshaer** [osquery/osquery#6514]
# Bug report

### What operating system and version are you using?
Parrot 4.9

### What version of osquery are you using?

4.3.0

### What steps did you take to reproduce the issue?
`SELECT l.port, l.address, p.name, u.username FROM listening_ports l JOIN processes p USING(pid) JOIN users u WHERE p.uid = u.uid AND l.port!=0;`

`select pid,name,cmdline from processes p where p.name="ncat";`

### What did you expect to see?
i should see ncat listening on that port. 
### What did you see instead?
i did not see netcat at all, and also tested that with nc and did not see it as well.

not sure, should I start thinking that osquery is missing something or Parrot is backdooring and hiding netcat ports/sockets from osquery 🤔 

![image](https://user-images.githubusercontent.com/4087461/85234036-092ff800-b40b-11ea-95a8-549425a9f657.png)

![image](https://user-images.githubusercontent.com/4087461/85234210-25806480-b40c-11ea-9b0e-82663b92d2e1.png)
![image](https://user-images.githubusercontent.com/4087461/85234286-9162cd00-b40c-11ea-923a-22a90c6da97c.png)

**Comment by theopolis** [comment]
Try to simplify your query, first start by looking at:

```sql
select * from listening_ports where port != 0;
```

If you do not see the `12345` port/pid then make sure `osqueryi` is running as root.

Then try to combine the `listening_ports` with `processes`, check that the `ncat` process shows up in `processes`. And finally make sure it is not chaning/dropping privileges such that the `uid` is no longer `0`.

**Comment by anelshaer** [comment]
Thanks for replying, i actaully did that simple query before submission and here below you can see the listening ports cant get that ncat socket although the processes can see it . 

in first picture everything running with `root `user. 
in the second picture,  `osquery `is `root`, and the `ncat `is normal user. 


![image](https://user-images.githubusercontent.com/4087461/85923328-5805e380-b88a-11ea-89e1-cc95d1e912ae.png)

![image](https://user-images.githubusercontent.com/4087461/85923375-b337d600-b88a-11ea-85ba-8ea33910a425.png)

**Comment by Smjert** [comment]
@anelshaer Could you try to give this command `sudo ls -l /proc/<nc pid>/fd` and paste here its output?

**Comment by anelshaer** [comment]
![image](https://user-images.githubusercontent.com/4087461/85924571-86d48780-b893-11ea-9caf-2cccf0dbabfc.png)

**Comment by Smjert** [comment]
So the socket is visible there; @anelshaer another thing you could try is to do `osqueryi --verbose`, do the same query and look at the log output, there might be some message that tells us what's going wrong.

Also, I had a quick look at the Parrot download page; I'm not familiar with the distro and the possible differences between the setups, which one did you specifically installed?
Netinstall? Home? Security?

**Comment by anelshaer** [comment]
i have the Parrot Security **Parrot Security MATE ISO**

running in verbose mode with the same query:
![image](https://user-images.githubusercontent.com/4087461/85931762-0d568c80-b8c7-11ea-9423-c1f8c7030d77.png)


log files have nothing really interesting because this is osqueryi I guess.

```
Log file created at: 2020/06/21 18:04:08
Running on machine: parrot
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0621 18:04:08.250730  2111 events.cpp:863] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
I0621 18:04:08.251320  2111 events.cpp:863] Event publisher not enabled: syslog: Publisher disabled via configurati
on
Log file created at: 2020/06/21 18:04:08
Running on machine: parrot
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0621 18:04:08.250730  2111 events.cpp:863] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
I0621 18:04:08.251320  2111 events.cpp:863] Event publisher not enabled: syslog: Publisher disabled via configuration
~
```

**Comment by Smjert** [comment]
@anelshaer Thanks, I was looking for the stdout of osqueryi.
So it's not even having any query error... interesting.

I'm not sure what's happening without trying directly. I'll try to have a look at it tomorrow!

**Comment by Smjert** [comment]
@anelshaer Something I always failed to see from the screenshots was that you were actually also connected to netcat, that's the problem; listening_ports only lists ports that are still listening, not just open.

You can also see that the port is not in listening mode via `ss -lpn | grep 12345`.

**Comment by anelshaer** [comment]
you are totally right, did not know that listening_ports only for the listening, not the current established.

So to get the current established I use `process_open_socket`, right? 
another unrelated question, how to get the services running on Linux system like  `systemctl status <some.service>` ?

thanks a lot for your efforts, appreciate it.

**Comment by Smjert** [comment]
@anelshaer Yes you should use `process_open_socket`.

It's not currently possible to obtain a list of services or their status from systemd; we have made a PR (that needs to be updated though), which would add support for that here: https://github.com/osquery/osquery/pull/4019.

For other available tables I suggest to have a look at: https://osquery.io/schema/4.3.0

Also for any other question of this kind, which are not related to a possible bug, I would suggest to [join our Slack](https://osquery-slack.herokuapp.com/) and ask there first.
