### ISSUE TITLE
Support Apple Silicon (Apple's new Platform)

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6517]
At WWDC 2020, apple announced their new cpu platform. I think we're still learning about what it means, but meanwhile, here are some links...

## Manual Process

A snippet from https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

> Determine Whether Your Binary Is Universal
To users, a universal binary looks no different than a binary built for a single architecture. When you build a universal binary, Xcode compiles your source files twice—once for each architecture. After linking the binaries for each architecture, Xcode then merges the architecture-specific binaries into a single executable file using the lipo tool. If you build the source files yourself, you must call lipo as part of your build scripts to merge your architecture-specific binaries into a single universal binary.
>
> To see the architectures present in a built executable file, run the lipo or file command-line tools. When running either tool, specify the path to the actual executable file, not to any intermediate directories such as the app bundle. For example, the executable file of a macOS app is in the Contents/MacOS/ directory of its bundle. When running the lipo tool, include the -archs parameter to see the architectures. The following example shows how to use lipo to view the list of architectures for the Mail app in macOS, and the results when Mail is a universal binary.
> ```
> % lipo -archs /System/Applications/Mail.app/Contents/MacOS/Mail
> x86_64 arm64
> ```

**Comment by directionless** [comment]
As an FYI I was able to build osquery, using the documented build process, on a beta Big Sur machine running on intel hardware.

**Comment by keeleysam** [comment]
osquery 4.4.0 seems to run just fine via Rosetta 2 on my Developer Transition kit.  osquery isn't currently able to build for the arm64 platform though, whether from Intel or the DTK.

For experimentation with universal binaries before arm64 builds properly, it is possible to have a universal binary with both `x86_64` and `x86_64h` in one.

**Comment by arubdesu** [comment]
Am I not finding a linked issue for a pretty central issue that `cpu_type`/`cpu_brand` detections fails on 4.6 in the system_info table at present on the shipping M1's? Subset of relevant current output on an ARM Air:
```sh
       cpu_type = i486
       cpu_subtype = Intel 80486
       cpu_brand = VirtualApple @ 2.50GHz
```
There's also a significant number of new items tracked in System Information/`system_profiler` e.g. references to `Reduced Security` being a SPiBridgeDataType Secure Boot value e.g. when enrolled in DEP, and GUI inconsistencies where SPSecureElementDataType has (besides the pre-existing Apple Pay info) a Controller Information section. These may never be accessible via public API's, but it adds a dimension to the current SIP detections, which seem to be reporting accurately.

**Comment by rtibdewal** [comment]
Hello there, 

Is there a plan to support osquery on Apple Silicon? Would it be possible to share possible timelines, even Beta would be nice.

Thanks
Rahul

**Comment by jprichards** [comment]
Hi, we're also looking to support M1 Macs with osquery. Any update on if this will be supported in the coming future would be great.

**Comment by directionless** [comment]
At present, osquery runs under rosetta2. I don't think we've had any issues with that. I'm not sure anyone is actively working on native builds right now.

**Comment by craig65535** [comment]
@directionless Here is an example of an issue running under Rosetta - http://github.com/osquery/osquery/issues/6784

**Comment by rtibdewal** [comment]
Under release notes for 4.5.0, we have support for arm64 on linux in Beta. https://github.com/osquery/osquery/releases
So I was hoping support would soon come for M1 as well.

**Comment by JodhwaniMadhur** [comment]
Ok,So I am trying to build OSquery on Mac Pro 2020 with apple M1 chip and I am facing this problem,can anyone here please explain me as to what I should be doing. I have to use it immediately for my project so it would be of great help if anyone could help.

```
**CMake Error at cmake/globals.cmake:37 (message):
  Unsupported architecture arm64
Call Stack (most recent call first):
  CMakeLists.txt:24 (include)**
```

**Comment by JodhwaniMadhur** [comment]
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### This is the error in the log file

**Comment by theopolis** [comment]
What commands are you running to try to build osquery? Can you describe the steps you've taken in detail?

**Comment by directionless** [comment]
I do not think osquery currently builds on Apple's M1 platform.

**Comment by JodhwaniMadhur** [comment]
I am trying to build it as it is in given on the official site documentation and cmake gives an error as I have mentioned above.
Like I first installed brew,cmake then these commands
 "xcode-select --install
brew install ccache git git-lfs cmake python clang-format flex bison

# Optional: install python tests prerequisites
pip3 install --user setuptools pexpect==3.3 psutil timeout_decorator six thrift==0.11.0 osquery"

The command that gives me error is this one => "cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 .."

**Comment by JodhwaniMadhur** [comment]
any more details required?

**Comment by Smjert** [comment]
As @directionless was saying, osquery doesn't build natively on M1 yet, and it's not only a matter to correct a few compiler flags, but all the third party libraries have to be configured (once and the result stored) under that specific platform/architecture.
It's not exactly a quick process (especially the first time), and I'm not sure if all libraries properly support it.
