### ISSUE TITLE
cpack: PACKAGING_SYSTEM=RPM on Ubuntu creates RPM-DEFAULT.rpm

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6526]
Heads up, on a default Ubuntu 18.04:

```
cmake -DPACKAGING_SYSTEM=RPM ..
make package
```

Creates `RPM-DEFAULT.rpm` and `osquery-debuginfo-4.4.0-1.x86_64.rpm`.

**Comment by Smjert** [comment]
That's weird! I just tried on mine and it works correctly.

Although I've found something that could be the reason, I'll open a PR.
