### ISSUE TITLE
CLI_FLAG should not behave like FLAG

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6533]
Currently CLI_FLAG flags behave like FLAG, while instead it shouldn't be possible to add them within the "options" key in a configuration.
We want to correct this behavior and block CLI_FLAG flags improper usage.
It's also probably worth to check if all FLAG and CLI_FLAG are marked properly.

More information about the behavior: https://osquery.readthedocs.io/en/latest/installation/cli-flags/
Previous attempted PR, with relevant discussion: https://github.com/osquery/osquery/pull/5882

**Comment by theopolis** [comment]
> We want to correct this behavior and block CLI_FLAG flags improper usage.

I would recommend a WARN log followed by simply not setting the value.

**Comment by theopolis** [comment]
Here is an instance where someone is trying to set CLI-only flags via a configuration: https://github.com/osquery/osquery/issues/5381

**Comment by Smjert** [comment]
We have decided to first have a release that will warn users about this change (5.3.0), and later actually skip setting the value.

**Comment by Smjert** [comment]
NOTE: There will be other flags which currently are FLAG but should be changed to CLI_FLAG; for example one of them is `disable_audit`.
I still have to generate the full list.
