### ISSUE TITLE
Should the watchdog monitor private bytes (total_size) on Windows?

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#6537]
# Bug report

Investigating #6536 noticed something interesting with the watchdog. With the osquery process set to background priority (https://github.com/osquery/osquery/blob/master/osquery/process/windows/process_ops.cpp#L221) the memory behaves differently. This means you see an increase in private bytes (total_size in the processes table) rather than the working set (resident_size in the processes table). 

The watchdog currently only monitors for resident_size: https://github.com/osquery/osquery/blob/master/osquery/core/watcher.cpp#L468

This means with the leak in #6536 osquery ends using large amounts of memory without the watchdog kicking in as it is only monitoring working set.

Should the watchdog also be have an option to monitor private bytes?

### What operating system and version are you using?

```
osquery> SELECT version, build, platform FROM os_version;
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.17763 | 17763 | windows  |
+------------+-------+----------+
```

### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 4.2.0   |
+---------+
```

### What steps did you take to reproduce the issue?

I have a small test program to demonstrate the issue

```
#include <iostream>

#include <windows.h>
#include <sddl.h>

#include <vector>

std::string psidToString(PSID sid) {
    LPSTR sidOut = nullptr;
    auto ret = ConvertSidToStringSidA(sid, &sidOut);
    if (ret == 0) {
        return std::string("");
    }
    return std::string(sidOut);
}

PSID GetUserSid(std::wstring user)
{
    // Call LookupAccountNameW() once to retrieve the necessary buffer sizes for
// the SID (in bytes) and the domain name (in TCHARS):
    DWORD sidBufferSize = 0;
    DWORD domainNameSize = 0;
    auto eSidType = SidTypeUnknown;
    auto ret = LookupAccountNameW(nullptr,
        user.c_str(),
        nullptr,
        &sidBufferSize,
        nullptr,
        &domainNameSize,
        &eSidType);

    if (ret == 0 && GetLastError() != ERROR_INSUFFICIENT_BUFFER) {
        std::cout << "Failed to lookup account name "
            << GetLastError();
        return nullptr;
    }

    // Allocate buffers for the (binary data) SID and (wide string) domain name:
    auto sidBuffer = std::make_unique<BYTE[]>(sidBufferSize);
    std::vector<wchar_t> domainName(domainNameSize);

    // Call LookupAccountNameW() a second time to actually obtain the SID for the
    // given account name:
    ret = LookupAccountNameW(nullptr,
        user.c_str(),
        sidBuffer.get(),
        &sidBufferSize,
        domainName.data(),
        &domainNameSize,
        &eSidType);

    return static_cast<PSID>(sidBuffer.get());
}

int main()
{
    BOOL ret = SetPriorityClass(GetCurrentProcess(), PROCESS_MODE_BACKGROUND_BEGIN);
    if (ret != TRUE)
    {
        std::cout << "Failed to set background priority";
        return 1;
    }
    PSID sid = GetUserSid(L"administrator");
    while (true)
    {
        for (int i = 0; i < 100; i++)
        {
            psidToString(sid).c_str();
        }
        Sleep(1 * 10);
    }
}
```
The program is quickly leaking but with background priority set.

If I leave the program running for a few minutes you can see the issue in process explorer:
![image](https://user-images.githubusercontent.com/48999626/86273568-6294e580-bbc8-11ea-807c-689d0ca0ef43.png)

If you disable background mode the working set and private bytes balloon close to parallel.

To investigate the different behaviors further I tested setting background mode:

```
#include <iostream>

#include <windows.h>

void PrintWSFlags(DWORD flags)
{
    std::cout << "Flags:\n";
    if (flags & QUOTA_LIMITS_HARDWS_MIN_DISABLE)
    {
        std::cout << "QUOTA_LIMITS_HARDWS_MIN_DISABLE" << "\n";
    }
    if (flags & QUOTA_LIMITS_HARDWS_MIN_ENABLE)
    {
        std::cout << "QUOTA_LIMITS_HARDWS_MIN_ENABLE" << "\n";
    }
    if (flags & QUOTA_LIMITS_HARDWS_MAX_DISABLE)
    {
        std::cout << "QUOTA_LIMITS_HARDWS_MAX_DISABLE" << "\n";
    }
    if (flags & QUOTA_LIMITS_HARDWS_MAX_ENABLE)
    {
        std::cout << "QUOTA_LIMITS_HARDWS_MAX_ENABLE" << "\n";
    }
}

int main()
{
    SIZE_T minWorkingSetSize;
    SIZE_T maxWorkingSetSize;
    DWORD flags;

    GetProcessWorkingSetSizeEx(GetCurrentProcess(), &minWorkingSetSize, &maxWorkingSetSize, &flags);

    std::cout << "Working set normally\n";
    PrintWSFlags(flags);
    std::cout << "Working set minimum: " << minWorkingSetSize << "\n";
    std::cout << "Working set maximum: " << maxWorkingSetSize << "\n\n";

    BOOL ret = SetPriorityClass(GetCurrentProcess(), PROCESS_MODE_BACKGROUND_BEGIN);
    if (ret != TRUE)
    {
        std::cout << "Failed to set background priority";
        return 1;
    }

    GetProcessWorkingSetSizeEx(GetCurrentProcess(), &minWorkingSetSize, &maxWorkingSetSize, &flags);

    std::cout << "Working set background\n";
    PrintWSFlags(flags);
    std::cout << "Working set minimum: " << minWorkingSetSize << "\n";
    std::cout << "Working set maximum: " << maxWorkingSetSize;
}
```
Output:

```
Working set normally
Flags:
QUOTA_LIMITS_HARDWS_MIN_DISABLE
QUOTA_LIMITS_HARDWS_MAX_DISABLE
Working set minimum: 204800
Working set maximum: 1413120

Working set background
Flags:
QUOTA_LIMITS_HARDWS_MIN_DISABLE
QUOTA_LIMITS_HARDWS_MAX_ENABLE
Working set minimum: 204800
Working set maximum: 33554432
```

Before Background priority QUOTA_LIMITS_HARDWS_MAX_DISABLE is set. This means the process can exceed it's maximum working set if the memory is available. QUOTA_LIMITS_HARDWS_MAX_ENABLE is set when Background priority is set. This now means the working set limit cannot be exceeded.

**Comment by Breakwell** [comment]
Looking at it here I think there's 3 potential fixes for this:

- Do no set background priority
- Increase the working set limit to exceed the watchdog limit
- Monitor private bytes and the working set

**Comment by theopolis** [comment]
Good find, I think we want to go with the third option "Monitor private bytes and the working set" but I am not very familiar with Windows so I will defer to others.

**Comment by Smjert** [comment]
I'm closing this since it should be solved in https://github.com/osquery/osquery/pull/7157.
We should eventually consider a similar thing for the other platforms too. Also, we might have to revisit the watchdog limits because this might cause the daemon to be terminated earlier than usual.
