### ISSUE TITLE
chassis_info table in Windows returns incorrect ChassisTypes value

### ISSUE THREAD

**Issue by jjerger** [osquery/osquery#6538]
I'm adding this in here in case others notice it before I get a chance to properly fix it (so it can be followed or if someone else fixes it before I get to it). I'm probably dealing with an overflow and an incorrect datatype cast based on what Ive been seeing in testing.

I plan to address this myself when I can. Extra cycles to work on osquery have been hard to find lately though, so it may take a while.

This issue does not break the table or any other osquery functionality. Just noting that the value is not correct.

# Bug report
### What operating system and version are you using?
N/A

### What steps did you take to reproduce the issue?
Select ChassisTypes from chassis_info on Windows

### What did you expect to see?
Proper value as shown by the equivalent wmi query

### What did you see instead?
Looks like an overflow results in an incorrect value

**Comment by jjerger** [comment]
Ref: https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/chassis_info.cpp#L40

WMI returns this as an array of integers, even though there is only one value. Simply casting it as an integer did not seem to work the way I hoped.

**Comment by jjerger** [comment]
It doesn't look like WmiResultItem actually has a method for this.

That specific field is an array that for most machines will return a single value as an array of strings, however I think I heard it actually _is_ possible to have multiple values in this array such as the case of a Surface Pro where the GPU resides in the detachable keyboard. Trying to find an example of one to confirm.

I'm not sure how I want to go about making a method for this, since I've never edited wmi.cpp or seen other tables have this come up yet. Any input from the owners here? @theopolis maybe?

**Comment by directionless** [comment]
If it's an array, then it spoils return multiple rows, yes?

**Comment by jjerger** [comment]
Do you mean that it should return multiple rows?

I think it would only return multiple rows in the case of something detachable like a Surface Pro. On a standalone desktop that I'm doing some of the building on for example, I see an array as the type however there is only a single element. I expect this is the case for the vast majority of desktops and laptops.

**Comment by farfella** [comment]
Looking at wmi.cpp, wondering if there was a reason we're using `VARIANT` and parsing things ourselves vs using `_variant_t`, which would have simplified this code a lot.

**Comment by farfella** [comment]
This should be resolved in master.
