### ISSUE TITLE
Poor performance querying user table on Windows

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#6540]
# Bug report

The users table will always generate a row for every user using NetEnumUser: https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/users.cpp#L124 This can be expensive if the machine has a large number of local accounts or is a domain controller.

The table should be improved to optimize any queries joining to the user table. If a SID constraint is used the user information could be looked up individually (e.g. using LookupAccountSid). The SID column could also be marked as INDEXED to ensure the planner calls the table with this constraint whenever possible.

### What operating system and version are you using?

Windows Server 2012 R2 Standard 

### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 4.2.0   |
+---------+
```

### What steps did you take to reproduce the issue?

The user table can be easily joined to get more information from a SID an example of this being:

```
select registry.name, users.username 
from registry 
left join users 
ON registry.name=users.uuid
where registry.path like 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\%' 
AND registry.name like 'S-%';
```
 If ran with ```--planner``` you can see each call to the user table with the SID constraint. This will call NetEnumUser each time.

**Comment by Smjert** [comment]
This is the same issue as observed here: https://github.com/osquery/osquery/issues/6411

**Comment by directionless** [comment]
Closing as a dup of #6411
