### ISSUE TITLE
cosine_similarity field is empty in powershell_events output

### ISSUE THREAD

**Issue by himypoly** [osquery/osquery#6542]
# Bug report

### What operating system and version are you using?
```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.17763 | 17763 | windows  |
+------------+-------+----------+

```

### What version of osquery are you using?
```
 +---------+
| version |
+---------+
 | 4.3.0   |
+---------+
```

### What steps did you take to reproduce the issue?
1. Install osquery (https://osquery.io/downloads/official/4.3.0) . 
2. Enable Windows Powershell script block logging 
3. Subscribe to the channel with --windows_event_channels=Microsoft-Windows-PowerShell/Operational
4. Ensure default osquery.conf file has "feature_vectors" field.
5. In osquery.flags, ensure --config_path=C:\Program Files\osquery\osquery.conf
4. From command prompt, Run "C:\Program Files\osquery>osqueryd\osqueryd.exe -S --flagfile osquery.flags --verbose"
5. Run some powershell scripts
6. Run query "select * from powershell_events;"

### What did you expect to see?
'cosine_similarity' column should not be empty
 
### What did you see instead?
1. 'cosine_similarity' column is empty. 
2. Logs on CLI: powershell_events.cpp:120] Invalid character frequency map found, skipping computation

Further, on debugging across osquery versions, it was observed that this issue is not there is osquery version 3.2.6. It occurs osquery version 3.3.0 onwards. Further analysis of code revealed that kCharFreqVectorLen is now 256. It was 255 in version 3.2.6. But in default osquery.conf, "feature_vectors" elements are 255 only. Adding one more entry to the vector resolves the issue. Example config can be modified to have 256 elements in "feature_vectors". 
Some obfuscation scripts for cosine_similarity can be referred from here: https://github.com/danielbohannon/Revoke-Obfuscation/tree/master/Demo

**Comment by theopolis** [comment]
I believe this is fixed with #6280.
