### ISSUE TITLE
Curl table does not permit the inclusion of custom headers

### ISSUE THREAD

**Issue by FritzX6** [osquery/osquery#6574]
# Feature request

### What new feature do you want?
Add new column `header` to `curl` table.

### How is this new feature useful?
This column would permit the passing of custom headers which would enable the curl table to return the responses from endpoints which require a specific header. An example of which is Google's GCP metadata server: 
https://cloud.google.com/compute/docs/storing-retrieving-metadata

---
**Screenshot of required header documentation:**
![image](https://user-images.githubusercontent.com/931724/89057952-76994780-d32c-11ea-9ee9-41f287822e49.png)

### How can this be implemented?
I do not know the manner in which this would be added.

**Comment by directionless** [comment]
I think we should have a google instance metadata table (or possible a generic cloud metadata table)

I'm much less sure about adding headers to curl. It has security implications we'd need to think through. (Oh look, someone wrote a blog post https://www.tenchisecurity.com/blog/abusing-the-osquery-curl-table-for-pivoting-into-cloud-environments)

**Comment by theopolis** [comment]
I agree, we should create a table specific for this.

**Comment by directionless** [comment]
For future search purposes, the header in question is `Metadata-Flavour: Google`

**Comment by pratiklotia** [comment]
Was a new table format ever created for this? Is there an issue tracking this? gcp_instance_metadata

**Comment by mwarkentin** [comment]
I opened https://github.com/osquery/osquery/issues/7924 for a dedicated table.

**Comment by mwarkentin** [comment]
2 years later, there is still not a dedicated table, so some workaround to support setting this basic header in the `curl` table would be much appreciated.

**Comment by directionless** [comment]
> 2 years later, there is still not a dedicated table, so some workaround to support setting this basic header in the `curl` table would be much appreciated.

Osquery operates on a volunteer basis. Is adding a dedicated table something you're interested in doing?
