### ISSUE TITLE
OSQuery failed due to error C2428 under /std:c++latest +MSVC

### ISSUE THREAD

**Issue by xiaoxiao-Xu** [osquery/osquery#6583]
Hi all,

Issue description:
We tried to build OSQuery using VS2019 on Windows Server 2016. OSQuery failed to build due to error C2428: '++': not allowed on operand of type 'bool'. It can be reproduced on release branch latest commit 1c5ed8a. Could you please help take a look at this? Thanks in advance!

[build.log](https://github.com/osquery/osquery/files/5040530/build.log)

**Repro steps:**
1. git clone --recursive https://github.com/facebook/osquery F:\gitP\facebook\osquery
2. open a VS 2019 x64 command prompt and browse to F:\gitP\facebook\osquery
3. set PATH=C:\Python\Python27\;%PATH%
4. set PATH=C:\Python\Python27\Scripts;%PATH%
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..
6. cmake --build . --target osqueryd --config Release --verbose -- /maxcpucount

**Actual result:**
185>F:\gitP\facebook\osquery\osquery\tables\events\windows\powershell_events.cpp(177,26): error C2428: '++': not allowed on operand of type 'bool' [F:\gitP\facebook\osquery\build\osquery\tables\events\osquery_tables_events_eventstable.vcxproj]
185>F:\gitP\facebook\osquery\osquery\tables\events\windows\powershell_events.cpp(186,26): error C2428: '++': not allowed on operand of type 'bool' [F:\gitP\facebook\osquery\build\osquery\tables\events\osquery_tables_events_eventstable.vcxproj]

**Comment by Smjert** [comment]
@xiaoxiao-Xu thanks for the heads up!
@alessandrogario has prepared a PR to fix this.

A note about how you're getting the source code and how you're building: please follow the instructions for Windows in this page https://osquery.readthedocs.io/en/latest/development/building/.
Mainly, do not clone recursively, some submodules contained in osquery, which are Linux or macOS only, attempt to create files with names not supported by Windows; just clone osquery and then when configuring, CMake will handle the clone of only the needed submodules.
Also, Python 2 is not supported anymore and we don't use it in osquery, you should have Python 3 available.
