### ISSUE TITLE
Build errors after include refactoring

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6591]
Since the include refactoring (#6557) I've started seeing build errors when run with `make -j8`. These errors do not crop up when running single threaded, and they self fix if make is rerun. Which implies they're probably a missing dependency somewhere. 

A couple that I noticed:

```
[ 28%] Building CXX object libs/src/rocksdb/CMakeFiles/thirdparty_rocksdb.dir/src/env/io_posix.cc.o
[ 28%] Linking CXX static library libthirdparty_rocksdb.a
[ 28%] Built target thirdparty_rocksdb
make: *** [all] Error 2
```

---

```
[  9%] Building C object libs/src/lzma/CMakeFiles/thirdparty_lzma.dir/src/src/liblzma/common/filter_flags_decoder.c.o
[  9%] Building CXX object libs/src/boost/CMakeFiles/thirdparty_boost_filesystem.dir/src/libs/filesystem/src/codecvt_error_category.cpp.o
In file included from /tmp/osquery/libraries/cmake/source/boost/src/libs/serialization/src/basic_text_iprimitive.cpp:20:
In file included from /tmp/osquery/libraries/cmake/source/boost/src/libs/serialization/include/boost/archive/impl/basic_text_iprimitive.ipp:25:
/tmp/osquery/libraries/cmake/source/boost/src/libs/serialization/include/boost/archive/iterators/remove_whitespace.hpp:21:10: fatal error: 'boost/iterator/iterator_adaptor.hpp' file not found
#include <boost/iterator/iterator_adaptor.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

----

```
[ 13%] Linking C static library libthirdparty_libxml2.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libthirdparty_libxml2.a(xzlib.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libthirdparty_libxml2.a(xzlib.c.o) has no symbols
[ 13%] Built target thirdparty_libxml2
make: *** [all] Error 2
```

**Comment by theopolis** [comment]
@directionless I have not encountered these, do they still happen for you?

**Comment by mike-myers-tob** [comment]
I always run `cmake` with `-j 8` on macOS and haven't seen this.

**Comment by Smjert** [comment]
The first and the last errors do not show enough of the log to know what was happening unfortunately, because when compiling with multiple jobs the actual error can be often printed quite earlier then when the `make: *** [all] Error 2` line is printed.

For the second one, it's strange since `thirdparty_boost_serialization` is depending on `thirdparty_boost_iterator` so it should find  those headers.
If it's happening again, I would check again which library is requesting those headers (can be seen from the path), and if those headers exists (maybe a bad clone?).

**Comment by directionless** [comment]
I haven't seen these since I filed this, but I usually run with `make -j4`. Testing a `make -j8` again and it seems to be okay. So either it was a weird one off error on my machine, or whatever it was got fixed.

no one else has hit this, i'm closing
