### ISSUE TITLE
Community ID saddr cannot be parsed as IP issue

### ISSUE THREAD

**Issue by dragonxtek** [osquery/osquery#6594]
# Bug report

I'm using Ubuntu 18.10 and I installed osquery 4.4.0 from repositories

I execute:

`osqueryi --line "SELECT pid, processes.path, cmdline, md5 FROM processes JOIN process_open_sockets USING (pid) JOIN hash USING (path) WHERE community_id_v1(local_address,remote_address,local_port,remote_port,protocol) = '1:l7a9beh8+bQe2MRtUW92OFmMMsM=';" `

and I got the following output:

> W0813 14:28:59.940619 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.940625 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.940630 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.949479 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.949497 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.961104 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.961124 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.961133 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.961141 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.961148 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.961155 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP
W0813 14:28:59.318506 18652 sqlite_hashing.cpp:225] Community ID saddr cannot be parsed as IP

Why Community ID saddr cannot be parsed as IP?
I seen this same example in [https://dactiv.llc/blog/correlate-osquery-network-connections/](https://dactiv.llc/blog/correlate-osquery-network-connections/) and it should be work.

**Comment by theopolis** [comment]
@zwass, any insight?

**Comment by zwass** [comment]
I think this would be caused by the `local_address` or `remote_address` columns of the `process_open_sockets` table being empty (which seems to be a common case). The query should probably be modified to something like

```sql
SELECT pid, processes.path, cmdline, md5 FROM processes JOIN process_open_sockets USING (pid) JOIN hash USING (path) WHERE local_address AND remote_address AND community_id_v1(local_address,remote_address,local_port,remote_port,protocol) = '1:l7a9beh8+bQe2MRtUW92OFmMMsM=';
```

**Comment by theopolis** [comment]
Let us know if there's still a problem.
