### ISSUE TITLE
hello I modified the osquery side. After the conf file cannot be in the/var/log/osquery/osquery_result.log See the log log is this why?

### ISSUE THREAD

**Issue by linsihao7788** [osquery/osquery#6624]
![16](https://user-images.githubusercontent.com/46431972/91700675-d6dc0d00-eba8-11ea-9d92-2d6bdae4f7e5.jpg)

**Comment by alessandrogario** [comment]
Hello @linsihao7788 

I noticed you also posted this question on Slack; we usually handle help/support requests there instead of opening an issue. Let's continue on the chat!
