### ISSUE TITLE
Inconsistent number of results in windows_eventlog for Security channel

### ISSUE THREAD

**Issue by clong** [osquery/osquery#6650]
# Bug report

The "security" channel for the `windows_eventlog` table shows inconsistent numbers of events when constraints are added to the query

### What operating system and version are you using?

```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.19041 | 19041 | windows  |
+------------+-------+----------+
```

### What version of osquery are you using?

```
+---------------------------+
| version                   |
+---------------------------+
| 4.4.0-48-gc7e37c2a0-dirty |
+---------------------------+
```

### What steps did you take to reproduce the issue?

Look at the number of events with `4624` as the eventid in both screenshots:

![image](https://user-images.githubusercontent.com/5092699/93263133-2fd7a380-f75a-11ea-94b2-98ead4691846.png)

### What did you expect to see?

The number of 4624 events in both queries should match

### What did you see instead?

The queries show an inconsistent number of 4624 events exist in the 'Security' event channel. This is repeatable with other event codes as well.

**Comment by mike-myers-tob** [comment]
I'm adding the triage label because we need to know if this still happens in the 4.5.0 pre-release after @kumarak 's recent work.

**Comment by kumarak** [comment]
This could be possible if `EvtNext` fails with invalid array bound (`RPC_S_INVALID_BOUND`) on reading a batch of large event log records.  @clong, Can you enable `--verbose` mode and check if it logs the error code 1734?

**Comment by clong** [comment]
Ah, my bad, I should have been running this with the verbose flag while I was testing. it is indeed throwing a 1734:

```
osquery> select count(*) from windows_eventlog where channel='Security';
I0917 18:16:13.913231  8920 windows_eventlog.cpp:148] EvtNext failed with error 1734
+----------+
| count(*) |
+----------+
| 1480     |
+----------+
```

**Comment by kumarak** [comment]
@clong, I raised a PR to fix the invalid array bound error (#6660). There is still a slight difference in the number of events if they are too large. This is because the EvtQuery is getting a different count. It could possibly be due to the different xpath lookup.

**Comment by Smjert** [comment]
@kumarak @clong Is this issue still present/relevant?

**Comment by wizzard0** [comment]
@Smjert At first glance, does not reproduce with Win10 Pro v20H2 and osquery v4.6.0.2. No error 1734 logged in verbose mode either. But it's up to @clong to reproduce ofc.

**Comment by tokcum** [comment]
Hi,

looking through open issues related to windows_eventlog, I came across this one.

I also tried to reproduce this with osquery 5.2.2 and Microsoft Windows Server 2016. As @clong I also selected events from Security channel and reviewed the results for events whose numbers went into 10k+.

I can not reproduce this issue.

@clong: I suggest closing this issue.

**Comment by Smjert** [comment]
Since the author hasn't answered in a while already, I'm closing this issue.
@tokcum thanks for the additional tests and confirmation!
