### ISSUE TITLE
Evaluate replacing RocksDB with Pebble

### ISSUE THREAD

**Issue by reedloden** [osquery/osquery#6651]
# Feature request

### What new feature do you want?

Evaluate replacing RocksDB with Pebble

> Pebble is a LevelDB/RocksDB inspired key-value store focused on performance and internal usage by CockroachDB. Pebble inherits the RocksDB file formats and a few extensions such as range deletion tombstones, table-level bloom filters, and updates to the MANIFEST format.

Basically, RocksDB implemented in Go (versus C). As such, it may be easier to use/manage/debug for osquery, which is written in Go. This is an unproven/untested statement, so just filing this as a pure evaluation request.

### How is this new feature useful?

* https://www.cockroachlabs.com/blog/pebble-rocksdb-kv-store/
* https://news.ycombinator.com/item?id=24484320
* https://github.com/cockroachdb/pebble

### How can this be implemented?

(super high-level)
1. Confirm features of RocksDB used by osquery have been implemented in Pebble
2. Replace some pieces of RocksDB with Pebble and run performance tests 
3. Replace remaining pieces with Pebble

**Comment by theopolis** [comment]
This would be awesome (a lightweight version of RocksDB), but osquery is written in C++ not go so I don’t think this works for us.

**Comment by stg18** [comment]
it's nice

**Comment by reedloden** [comment]
Sigh. My brain is just not working this week. Duh. I think I have been
writing too much Go lately for other projects. Hah.
