### ISSUE TITLE
Event publisher not enabled: ntfs_event_publisher: NTFS event publisher disabled via configuration (windows)

### ISSUE THREAD

**Issue by chouchouzzj** [osquery/osquery#6672]
hi ,I am  new to osquery, and I installed osquery-4.4.0.msi on my windows 7 professional.
I updated my osquery.conf and make a packes file named fim.conf, followed the article: [https://blog.trailofbits.com/2020/03/16/real-time-file-monitoring-on-windows-with-osquery/]
here is the osquery.flags

```
--disable_events=false
--usn_journal_reader_debug=true
--ntfs_event_publisher_debug=true
```

but it doesn't work. 

And then ,I run the osqueryi.exe to find out the reason.
the command line is like:

```
"c:\Program Files\osquery\osqueryi.exe" -S --config_path="C:\Program Files\osquery\osquery.conf" --disable_events=false --usn_journal_reader_debug=true --ntfs_event_publisher_debug=true --verbose
```

but the response is like 

```
I0925 10:09:33.218725  5000 events.cpp:785] Starting event publisher run loop: WindowsEventLogPublisher
I0925 10:09:33.218725  5000 events.cpp:805] Event publisher WindowsEventLogPublisher run loop terminated for reason: Publisher disabled by configuration
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> select * from ntfs_journal_events;
osquery>
```

and here is the osquery.INFO.*******[datetime]

```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0925 10:07:28.948907  5516 events.cpp:866] Event publisher not enabled: ntfs_event_publisher: NTFS event publisher disabled via configuration
```

so,how can I config the osquery.conf and the osquery.flags for real time file monitoring.

I would really appreciate it if someone has an answer as to why this happens!!
Thanks!

**Comment by theopolis** [comment]
Hi, you should not need to enable those debug flags. But you do need to configure paths for osquery to monitor.

Take a look at the configuration examples here: https://osquery.readthedocs.io/en/latest/deployment/file-integrity-monitoring/

**Comment by knightian** [comment]
> https://osquery.readthedocs.io/en/latest/deployment/file-integrity-monitoring/

This link looks like it's discussing Linux and macOS not Windows.

But can I surmise that you are suggesting that we need to set up paths to the windows event logs for monitoring?

**Comment by chouchouzzj** [comment]
> Hi, you should not need to enable those debug flags. But you do need to configure paths for osquery to monitor.
> 
> Take a look at the configuration examples here: https://osquery.readthedocs.io/en/latest/deployment/file-integrity-monitoring/

Thank you for answering. 
But of course I have configured paths metioned in the link.

**Comment by chouchouzzj** [comment]
> > https://osquery.readthedocs.io/en/latest/deployment/file-integrity-monitoring/
> 
> This link looks like it's discussing Linux and macOS not Windows. "File integrity monitoring (FIM) is available for Linux and macOS using inotify and FSEvents." In fact it would seem given by that sentence that it is not available for windows at all?
> 
> But can I surmise that you are suggesting that we need to set up paths to the windows event logs for monitoring? However the link you have supplied suggests that is not correct for windows. How do we turn on events for windows event logs I cannot find this information anywhere.

Thank you for answering.
Here is the blog that I followed. 
https://blog.trailofbits.com/2020/03/16/real-time-file-monitoring-on-windows-with-osquery/

And the osquery give the windows_event named [ntfs_journal_events](https://osquery.io/schema/4.2.0#ntfs_journal_events)
So, I believe that it should work on windows.
Maybe win10,or higher version.

**Comment by chouchouzzj** [comment]
> hi ,I am new to osquery, and I installed osquery-4.4.0.msi on my windows 7 professional.
> I updated my osquery.conf and make a packes file named fim.conf, followed the article: [https://blog.trailofbits.com/2020/03/16/real-time-file-monitoring-on-windows-with-osquery/]
> here is the osquery.flags
> 
> ```
> --disable_events=false
> --usn_journal_reader_debug=true
> --ntfs_event_publisher_debug=true
> ```
> 
> but it doesn't work.
> 
> And then ,I run the osqueryi.exe to find out the reason.
> the command line is like:
> 
> ```
> "c:\Program Files\osquery\osqueryi.exe" -S --config_path="C:\Program Files\osquery\osquery.conf" --disable_events=false --usn_journal_reader_debug=true --ntfs_event_publisher_debug=true --verbose
> ```
> 
> but the response is like
> 
> ```
> I0925 10:09:33.218725  5000 events.cpp:785] Starting event publisher run loop: WindowsEventLogPublisher
> I0925 10:09:33.218725  5000 events.cpp:805] Event publisher WindowsEventLogPublisher run loop terminated for reason: Publisher disabled by configuration
> Using a �[1mvirtual database�[0m. Need help, type '.help'
> osquery> select * from ntfs_journal_events;
> osquery>
> ```
> 
> and here is the osquery.INFO.*******[datetime]
> 
> ```
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> I0925 10:07:28.948907  5516 events.cpp:866] Event publisher not enabled: ntfs_event_publisher: NTFS event publisher disabled via configuration
> ```
> 
> so,how can I config the osquery.conf and the osquery.flags for real time file monitoring.
> 
> I would really appreciate it if someone has an answer as to why this happens!!
> Thanks!



Finally..The command has been found:

osqueryi.exe -S --config_path="C:\Program Files\osquery\osquery.conf" --disable_events=false  --enable_windows_events_publisher=true --enable_windows_events_subscriber=true --enable_ntfs_event_publisher=true --verbose


using the command to List osquery's features and their status:
.features

and you'll find out the answer.
