### ISSUE TITLE
404 error when downloading centos osquery packages

### ISSUE THREAD

**Issue by newdjangodev** [osquery/osquery#6682]
# Bug report

### What operating system and version are you using
Centos

return 404 error (sudo rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm)

**Comment by directionless** [comment]
Looks like a dup of https://github.com/osquery/osquery/issues/6181

**Comment by theopolis** [comment]
Yes, this 404 is intentional, we still support CentOS7 but we do not provide CentOS7-specific repos. Please use the generic yum repo for all distributions that support yum and rpm.

**Comment by sys-jmohn** [comment]
Hello, apologies if this is a low level question. When you say generic yum repo you mean just use **sudo yum install osquery**? Is there any way to still set up the generic yum repo to an internal repo sync? I realise that there are no RHEL repos but when running the yum install it still calls back to the osquery-s3-rpm.repo. Thank you
