### ISSUE TITLE
Programs Table Fails to Handle Unicode Characters (JP)

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#6737]
# Bug report

### What operating system and version are you using?

Windows 10, x64, 1903 (19H1)

os_version Output:
 version = 10.0.18362
   build = 18362
platform = windows

### What version of osquery are you using?

Tested using the osqueryi shell for (almost) all Windows release versions (2.11.2 --> 4.5.1).

### What steps did you take to reproduce the issue?

1. Install Japanese language pack.
2. Install osquery under a directory that contains Japanese characters (I used "オン スクリーン表示").
3. Run ``osqueryi --json "SELECT * FROM programs WHERE name = `'osquery';"``

### What did you expect to see?

"install_source" field content that displays correct Japanese characters.
```
[
    {
        "identifying_number": "{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}",
        "install_date": "20201028",
        "install_location": "C:\\Program Files\\osquery\\",
        "install_source": "C:\\Users\\<user>\\Desktop\\オン スクリーン表示\\",
        "language": "1033",
        "name": "osquery",
        "publisher": "osquery",
        "uninstall_string": "MsiExec.exe /X{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}",
        "version": "4.5.1"
    }
]
```

### What did you see instead?

2.11.2 --> 4.2.0:
Very close to being correct.  These versions will insert a backslash between the last two JP characters (e.g., ``オン スクリーン表\示``), which appears to invalidate the JSON. I believe the JSON is invalid due to the install_source string containing an invalid escape sequence ``\示``.
Several validators I have tried have failed to parse:
- JSONLint.com
- https://jsonformatter.curiousconcept.com/ (**)
- Notepad++ Plugin: JSON Viewer (https://github.com/kapilratnani/JSON-Viewer)

(**) JsonFormatter actually attempts to fix it for you by escaping the ``\``, making it ``オン スクリーン表\\示``, which is not a valid path.

JSON output (note the ``\`` between the last two JP characters):
```
[
    {
        "identifying_number": "{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}",
        "install_date": "20201028",
        "install_location": "C:\\Program Files\\osquery\\",
        "install_source": "C:\\Users\\<user>\\Desktop\\オン スクリーン表\示\\",
        "language": "1033",
        "name": "osquery",
        "publisher": "osquery",
        "uninstall_string": "MsiExec.exe /X{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}",
        "version": "4.5.1"
    }
]
```

4.3.0 --> 4.5.1
Though the JSON is valid, the output is completely incorrect - ``オン スクリーン表示`` becomes ``繧ｪ繝ｳ 繧ｹ繧ｯ繝ｪ繝ｼ繝ｳ陦ｨ遉ｺ``.  Admittedly, I don't know Japanese, however running it through Google translate doesn't yield anything that seems coherent.

JSON output:
```
[
    {
        "identifying_number": "{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}",
        "install_date": "20201028",
        "install_location": "C:\\Program Files\\osquery\\",
        "install_source": "C:\\Users\\<user>\\Desktop\\繧ｪ繝ｳ 繧ｹ繧ｯ繝ｪ繝ｼ繝ｳ陦ｨ遉ｺ\\",
        "language": "1033",
        "name": "osquery",
        "publisher": "osquery",
        "uninstall_string": "MsiExec.exe /X{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}",
        "version": "4.5.1"
    }
]
```

Seems like something is amiss with the registry UTF string conversions.

**Comment by tferguson7337** [comment]
With respect to added backslash in the 2.11.2 --> 4.2.0 output, I tried the query again using --list and --line: the backslash was not inserted in either output:
```
name|version|install_location|install_source|language|publisher|uninstall_string|install_date|identifying_number
osquery|4.5.1|C:\Program Files\osquery\|C:\Users\<user>\Desktop\オン スクリーン表示\|1033|osquery|MsiExec.exe /X{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}|20201028|{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}
```
```
              name = osquery
           version = 4.5.1
  install_location = C:\Program Files\osquery\
    install_source = C:\Users\<user>\Desktop\オン スクリーン表示\
          language = 1033
         publisher = osquery
  uninstall_string = MsiExec.exe /X{CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}
      install_date = 20201028
identifying_number = {CF9213D5-FE2A-41A3-8AFD-81266D5EAE53}
```

Not sure how relevant this is given that this is old behavior now, but thought it might be worth noting.

**Comment by directionless** [comment]
@farfella Seems like something you'd be interested in?

**Comment by farfella** [comment]
Yup-- I'll take a look at it this weekend. Feel free to send windows issues my way.

**Comment by farfella** [comment]
Hey @tferguson7337, trying to reproduce this issue.

When you mention 

> 3. Run `` osqueryi --json "SELECT * FROM programs WHERE name = `'osquery';" ``

which program did you run this command in? That is, in a Command Prompt, PowerShell, the new windows terminal (https://github.com/microsoft/terminal), etc?

**Comment by tferguson7337** [comment]
Hello @farfella,

Apologies for the incomplete repro steps.  Ran the command in PowerShell using a font that supports the Unicode characters (SimSun-ExtB).  Command Prompt doesn't do well with Unicode, in my experience.

Additionally, the back-tick in the query I posted shouldn't be there - that's a typo.

PowerShell invocation:
``.\osqueryi.exe --json "SELECT * FROM programs WHERE name = 'osquery';"``

**Comment by tferguson7337** [comment]
You may also need to set PowerShell's $OutputEncoding to something other than the default (non-ASCII).  I believe on the VM I tested this I used $OutputEncoding = [Console]::Encoding, which set it to use the Japanese codepage.

**Comment by farfella** [comment]
Thanks @tferguson7337!

I understand the issue you are encountering. The code page the system is using is region/locale-specific vs UTF-8. One way to change the code page to UTF-8 is to run `CHCP 65001` in the shell prior to invoking `osqueryi`.

Another way to set this globally is, on the systems in which you are running osquery `v4.5.1`:
1. Run `intl.cpl` (This will open the `Region` control panel item).
2. Click on the `Administrative` tab
3. Click `Change system locale...`
4. Check `Beta: Use Unicode UTF-8 for worldwide language support`

Note the "Beta" tag on this feature; this may have side-effects with other programs, which are assuming single-byte character sets (for example, [here](https://support.dataaccess.com/Forums/showthread.php?64797-Recent-Microsoft-Changes-to-Windows-10-May-Impact-Functionality-and-or-Data-Integrity)). So, in these cases, `CHCP 65001` prior to running `osqueryi --json` will yield the expected output.

If you could please try this let me know the outcome, would appreciate it. :)
Thanks!

**Comment by tferguson7337** [comment]
I'll be able to test this on the JP VM come Monday.  Thank you @farfella

**Comment by tferguson7337** [comment]
It seems like that does the trick; didn't even need to opt-in for the locale UTF-8 beta.  Additionally, we normally obtain the query output programmatically via providing our own pipes for stdout/stderr reading.  I forgot to test this scenario, which also works (and should be unaffected by terminal codepage anyway).

There doesn't appear to be any issue here.

Thank you for your help, and apologies for wasting your time!
