### ISSUE TITLE
Deadlock registering two extensions at the same time

### ISSUE THREAD

**Issue by nickcollier** [osquery/osquery#6744]
# Bug report

### What operating system and version are you using?

      version = 10.0.19042
         build = 19042
    platform = windows

### What version of osquery are you using?

    version = 4.5.1

### What steps did you take to reproduce the issue?

1. Launch osquery
2. Launch two extensions at the same time

### What did you expect to see?

Both extensions reigster and table plugins are available to query

### What did you see instead?

Neither extension reigstered. Two threads deadlocked

    # Child-SP          RetAddr           Call Site
    00 0000005a`657feae8 00007ffc`29ec1e93 ntdll!NtWaitForSingleObject+0x14
    01 0000005a`657feaf0 00007ff6`6fe5dc79 KERNELBASE!WaitForSingleObjectEx+0x93
    02 (Inline Function) --------`-------- osqueryd!boost::shared_mutex::lock_shared+0x79 [c:\workspace\cmakex64\libraries\boost\include\boost\thread\win32\shared_mutex.hpp @ 183]
    03 0000005a`657feb90 00007ff6`70521edd osqueryd!boost::shared_lock<boost::shared_mutex>::lock+0xc9 [c:\workspace\cmakex64\libraries\boost\include\boost\thread\lock_types.hpp @ 645]
    04 (Inline Function) --------`-------- osqueryd!boost::shared_lock<boost::shared_mutex>::{ctor}+0x1e [c:\workspace\cmakex64\libraries\boost\include\boost\thread\lock_types.hpp @ 520]
    05 0000005a`657fed20 00007ff6`70521e77 osqueryd!osquery::RegistryInterface::exists_+0x3d [c:\workspace\osquery\registry\registry_interface.cpp @ 354]
    06 0000005a`657fed60 00007ff6`705285bd osqueryd!osquery::RegistryInterface::exists+0x57 [c:\workspace\osquery\registry\registry_interface.cpp @ 309]
    07 0000005a`657fedb0 00007ff6`70526f03 osqueryd!osquery::RegistryFactory::exists+0x5d [c:\workspace\osquery\registry\registry_factory.cpp @ 239]
    08 0000005a`657fee00 00007ff6`706e69ee osqueryd!osquery::RegistryFactory::addBroadcast+0x1e3 [c:\workspace\osquery\registry\registry_factory.cpp @ 80]
    09 0000005a`657ff020 00007ff6`6fe88e7d osqueryd!osquery::ExtensionManagerInterface::registerExtension+0x28e [c:\workspace\osquery\extensions\interface.cpp @ 112]
    0a 0000005a`657ff1f0 00007ff6`70096fa9 osqueryd!osquery::ExtensionManagerHandler::registerExtension+0x40d [c:\workspace\osquery\extensions\impl_thrift.cpp @ 245]
    0b 0000005a`657ff390 00007ff6`700954f9 osqueryd!osquery::extensions::ExtensionManagerProcessor::process_registerExtension+0x249 [c:\workspace\osquery\extensions\thrift\gen\extensionmanager.cpp @ 1801]
    0c 0000005a`657ff6b0 00007ff6`6fe87253 osqueryd!osquery::extensions::ExtensionManagerProcessor::dispatchCall+0xc9 [c:\workspace\osquery\extensions\thrift\gen\extensionmanager.cpp @ 1666]
    0d 0000005a`657ff700 00007ff6`700afd6a osqueryd!apache::thrift::TDispatchProcessor::process+0x143 [c:\workspace\cmakex64\libraries\thrift\include\thrift\tdispatchprocessor.h @ 121]
    0e 0000005a`657ff7c0 00007ff6`700a5be7 osqueryd!apache::thrift::server::TConnectedClient::run+0x16a [c:\forjenkins\basefolder\thrift\lib\cpp\src\thrift\server\tconnectedclient.cpp @ 62]
    0f 0000005a`657ff900 00007ff6`700a3911 osqueryd!apache::thrift::server::TThreadedServer::TConnectedClientRunner::run+0x17 [c:\forjenkins\basefolder\thrift\lib\cpp\src\thrift\server\tthreadedserver.cpp @ 148]
    10 0000005a`657ff930 00007ff6`700a3226 osqueryd!apache::thrift::concurrency::StdThread::threadMain+0x71 [c:\forjenkins\basefolder\thrift\lib\cpp\src\thrift\concurrency\stdthreadfactory.cpp @ 130]
    11 (Inline Function) --------`-------- osqueryd!std::_Invoker_functor::_Call+0x20 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\type_traits @ 16707566]
    12 (Inline Function) --------`-------- osqueryd!std::invoke+0x20 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\type_traits @ 16707566]
    13 (Inline Function) --------`-------- osqueryd!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> >,std::default_delete<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> > > > >::_Execute+0x20 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 238]
    14 (Inline Function) --------`-------- osqueryd!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> >,std::default_delete<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> > > > >::_Run+0x6a [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 245]
    15 0000005a`657ff990 00007ff6`700a3159 osqueryd!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> >,std::default_delete<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> > > > >::_Go+0x86 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 230]
    16 0000005a`657ff9e0 00007ff6`709b1e10 osqueryd!std::_Pad::_Call_func+0x9 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 209]
    17 (Inline Function) --------`-------- osqueryd!invoke_thread_procedure+0xd [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 91]
    18 0000005a`657ffa10 00007ffc`2c117c24 osqueryd!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50 [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 115]
    19 0000005a`657ffa40 00007ffc`2c3ecea1 kernel32!BaseThreadInitThunk+0x14
    1a 0000005a`657ffa70 00000000`00000000 ntdll!RtlUserThreadStart+0x21

    # Child-SP          RetAddr           Call Site
    00 0000005a`659fe8f8 00007ffc`29ed2ae7 ntdll!NtWaitForMultipleObjects+0x14
    01 0000005a`659fe900 00007ff6`70520bb8 KERNELBASE!WaitForMultipleObjectsEx+0x107
    02 (Inline Function) --------`-------- osqueryd!boost::shared_mutex::lock+0x78 [c:\workspace\cmakex64\libraries\boost\include\boost\thread\win32\shared_mutex.hpp @ 455]
    03 (Inline Function) --------`-------- osqueryd!boost::unique_lock<boost::shared_mutex>::lock+0x8c [c:\workspace\cmakex64\libraries\boost\include\boost\thread\lock_types.hpp @ 346]
    04 (Inline Function) --------`-------- osqueryd!boost::unique_lock<boost::shared_mutex>::{ctor}+0x98 [c:\workspace\cmakex64\libraries\boost\include\boost\thread\lock_types.hpp @ 124]
    05 0000005a`659fec00 00007ff6`7052727e osqueryd!osquery::RegistryInterface::addExternal+0x118 [c:\workspace\osquery\registry\registry_interface.cpp @ 260]
    06 0000005a`659fee40 00007ff6`706e69ee osqueryd!osquery::RegistryFactory::addBroadcast+0x55e [c:\workspace\osquery\registry\registry_factory.cpp @ 99]
    07 0000005a`659ff060 00007ff6`6fe88e7d osqueryd!osquery::ExtensionManagerInterface::registerExtension+0x28e [c:\workspace\osquery\extensions\interface.cpp @ 112]
    08 0000005a`659ff230 00007ff6`70096fa9 osqueryd!osquery::ExtensionManagerHandler::registerExtension+0x40d [c:\workspace\osquery\extensions\impl_thrift.cpp @ 245]
    09 0000005a`659ff3d0 00007ff6`700954f9 osqueryd!osquery::extensions::ExtensionManagerProcessor::process_registerExtension+0x249 [c:\workspace\osquery\extensions\thrift\gen\extensionmanager.cpp @ 1801]
    0a 0000005a`659ff6f0 00007ff6`6fe87253 osqueryd!osquery::extensions::ExtensionManagerProcessor::dispatchCall+0xc9 [c:\workspace\osquery\extensions\thrift\gen\extensionmanager.cpp @ 1666]
    0b 0000005a`659ff740 00007ff6`700afd6a osqueryd!apache::thrift::TDispatchProcessor::process+0x143 [c:\workspace\cmakex64\libraries\thrift\include\thrift\tdispatchprocessor.h @ 121]
    0c 0000005a`659ff800 00007ff6`700a5be7 osqueryd!apache::thrift::server::TConnectedClient::run+0x16a [c:\forjenkins\basefolder\thrift\lib\cpp\src\thrift\server\tconnectedclient.cpp @ 62]
    0d 0000005a`659ff940 00007ff6`700a3911 osqueryd!apache::thrift::server::TThreadedServer::TConnectedClientRunner::run+0x17 [c:\forjenkins\basefolder\thrift\lib\cpp\src\thrift\server\tthreadedserver.cpp @ 148]
    0e 0000005a`659ff970 00007ff6`700a3226 osqueryd!apache::thrift::concurrency::StdThread::threadMain+0x71 [c:\forjenkins\basefolder\thrift\lib\cpp\src\thrift\concurrency\stdthreadfactory.cpp @ 130]
    0f (Inline Function) --------`-------- osqueryd!std::_Invoker_functor::_Call+0x20 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\type_traits @ 16707566]
    10 (Inline Function) --------`-------- osqueryd!std::invoke+0x20 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\type_traits @ 16707566]
    11 (Inline Function) --------`-------- osqueryd!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> >,std::default_delete<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> > > > >::_Execute+0x20 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 238]
    12 (Inline Function) --------`-------- osqueryd!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> >,std::default_delete<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> > > > >::_Run+0x6a [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 245]
    13 0000005a`659ff9d0 00007ff6`700a3159 osqueryd!std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> >,std::default_delete<std::tuple<void (__cdecl*)(std::shared_ptr<apache::thrift::concurrency::StdThread>),std::shared_ptr<apache::thrift::concurrency::StdThread> > > > >::_Go+0x86 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 230]
    14 0000005a`659ffa20 00007ff6`709b1e10 osqueryd!std::_Pad::_Call_func+0x9 [c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread @ 209]
    15 (Inline Function) --------`-------- osqueryd!invoke_thread_procedure+0xd [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 91]
    16 0000005a`659ffa50 00007ffc`2c117c24 osqueryd!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50 [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 115]
    17 0000005a`659ffa80 00007ffc`2c3ecea1 kernel32!BaseThreadInitThunk+0x14
    18 0000005a`659ffab0 00000000`00000000 ntdll!RtlUserThreadStart+0x21

The first thread has already locked the mutex in question for read and is then in another function that is trying to request a read lock again.

However between these two read lock attempts the second thread has requested a write lock we will block all future read lock requests but cannot be granted until all existing read locks release causing the deadlock.

**Comment by mike-myers-tob** [comment]
Apparently fixed in #6745
