### ISSUE TITLE
osquery-4.5.1-1.linux.x86_64.rpm breaks dependency resolution when installed on fresh system

### ISSUE THREAD

**Issue by alexbozhenko** [osquery/osquery#6755]
When osquery is included to the list of packages to be installed on fresh system instillation(in kickstart) it fails because '/bin/sh' dependency can not be satisfied.

### What operating system and version are you using?
Centos7 

### What version of osquery are you using?
Trying to use 4.5.1.-1

### What steps did you take to reproduce the issue?

```
# wget https://pkg.osquery.io/rpm/osquery-4.5.1-1.linux.x86_64.rpm
# rpmdb --initdb --root /reproducer
# yum --config /etc/yum.conf --installroot=/reproducer install  osquery-4.5.1-1.linux.x86_64.rpm
...
Error: transaction check vs depsolve:
/bin/sh is needed by osquery-4.5.1-1.x86_64
...
```
This is caused by specification of /bin/sh as pretrans script:
```
# rpm -qp --scripts osquery-4.5.1-1.linux.x86_64.rpm | grep -A4 program
pretrans program: /bin/sh
preinstall program: /bin/sh
postinstall scriptlet (using /bin/sh):

#!/bin/sh
# Copyright (c) 2014-present, The osquery authors
--
preuninstall program: /bin/sh
postuninstall program: /bin/sh
posttrans program: /bin/sh

```
Previous version did not have this problem, because there were no pretrans script dependency specified:
```
# rpm -qp --scripts osquery-4.0.2-1.linux.x86_64.rpm 
#
```

According to this:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#pretrans
pretrans must not use sh.

But in this specific case looks like there is no actual pretrans script is used, so pretrans program should not be scpecified in the rpm?

**Comment by Smjert** [comment]
Seems to be an issue of CPack in CMake 3.18.x: https://gitlab.kitware.com/cmake/cmake/-/issues/21345

We might have to recreate the package using an older CMake version to workaround this issue.

**Comment by alexbozhenko** [comment]
@Smjert, thanks for finding cmake bug!

In the mean time, I was able to workaround the issue using the following [rpmrebuild](https://sourceforge.net/projects/rpmrebuild/) command:
`rpmrebuild --edit-whole --package osquery-4.5.1-1.linux.x86_64.rpm`

It will open spec file in editor. Just remove this line:
`%pretrans -p /bin/sh`
and resulting rebuilt rpm won't have extra /bin/sh dependency.

**Comment by directionless** [comment]
It sounds like we fixed this by pinning cmake below the bug. We should also add a version check, but this is not a release blocker.

**Comment by Smjert** [comment]
> It sounds like we fixed this by pinning cmake below the bug. We should also add a version check, but this is not a release blocker.

I can take care of this.
