### ISSUE TITLE
Improve the event control flags documentation

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#6763]
# Feature request

### What new feature do you want?

- There are some undocumented flags that control event publishers. They should be documented on the wiki.
- The other flags that control event-related behavior could be explained better.

### How is this new feature useful?

It would help users correctly set up osquery for evented data collection.

### How can this be implemented?

E.g., on Windows the following flags control events, but not all of them are documented:

```Powershell
PS C:\Projects\osquery-tob\build> .\osquery\RelWithDebInfo\osqueryi.exe --help | findstr -i Event
    --disable_events                                 Disable osquery publish/subscribe system
    --enable_ntfs_event_publisher                    Enables the NTFS event publisher
    --enable_powershell_events_subscriber            Enables Powershell events
    --enable_windows_events_publisher                Enables the Windows events publisher
    --enable_windows_events_subscriber               Enables Windows Event Log events
    --events_expiry VALUE                            Timeout to expire event subscriber results
    --events_max VALUE                               Maximum number of events per type to buffer
    --events_optimize                                Optimize subscriber select queries (scheduler only)
    --logger_event_type                              Log scheduled results as events
    --logger_snapshot_event_type                     Log scheduled snapshot results as events
    --windows_event_channels VALUE                   Comma-separated list of Windows event log channels
```

Documentation edits to https://osquery.readthedocs.io/en/latest/installation/cli-flags/#events-control-flags

**Comment by directionless** [comment]
I'm a little leery of trying to keep wiki docs manually in sync with the osquery flags. Do you think there's a better way?

**Comment by mike-myers-tob** [comment]
> I'm a little leery of trying to keep wiki docs manually in sync with the osquery flags. Do you think there's a better way?

We could keep the doc a little more general so that it is not redundant and out of sync with the --help command. But what the docs ought to explain is that the user should expect to have to explicitly enable both publisher and subscriber in some cases (and not others), etc. Help them not get stuck.
