### ISSUE TITLE
macOS `crashes` table misses crash reports in macOS12+

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6776]
Not sure if this is a question or a bug...

I'm debugging some rosetta 2 stuff, and system logs show me a crash is captured. Cool. But it's not in the osquery `crashes` table.

We appears to look at a couple of enumerated directories -- https://github.com/osquery/osquery/blob/29f4694df214bc3bd4e7210873e05bb19374888b/osquery/tables/system/darwin/crashes.cpp#L35-L40

But poking around this machine, I see my crash in `/Library/Logs/DiagnosticReportsForNewHardware` I don't know if this directory is specific to the dev kit, or more general. I also see crashes in `/Library/Logs/CrashReporter` which don't appear to be mobile. So we might want to revisit this list.

@sharvilshah you're a friendly mac expert... Do you happen to know what directories matter? (If not, no worries)

**Comment by AllPurposeBen** [comment]
I also don't see all the crashes I'd like to, specifically those in userland, `~/Library/Logs/DiagnosticReports/`. I don't _think_ that folder should be TCC protected but even if it is, I don't have a problem granting any needed parts of osquery full disk access.

**Comment by arubdesu** [comment]
Looks like the work that was done in #7215 needs to be applied to these as well, I have .ips files from FRESH crashes e.g. in `$USER/Library/Logs/DiagnosticReports/Python-2022-11-14-095200.ips`
It appears that the system is purging these regularly, so it's even more critical to collect them as they're occurring, I see files being created daily in `/Library/Logs/DiagnosticReports/Retired/` but only going back ~4 days 
@directionless can we please remove the macOS Big Sur label and modify the title of this issue accordingly? @mike-myers-tob mind taking a look at this as well?
Or should I just spin up a new bug report? As of Ventura I'm seeing 0 crashes in the table on darwin, whereas there's ~10 .ips files that ripgrep is allowed to look for across my filesystem (with or without FullDiskAccess being granted to terminal):
```
sudo rg -g '*.ips' --files /System/Volumes/Data/ 2> /dev/null | wc -l
```

**Comment by arubdesu** [comment]
Taking a stab at the new paths to enumerate (while I'm still working on a canonical reference for the paths post-.ips migration on macOS) I'm seeing 
```
/Library/Logs/DiagnosticReports/%.ips
/Library/Logs/DiagnosticReports/Retired/%.ips
$USER/Library/Logs/DiagnosticReports/%.ips
$USER/Library/Logs/DiagnosticReports/Retired/%.ips
```

**Comment by mike-myers-tob** [comment]
I see osquery is just looking for `.crash` files to parse.

https://github.com/osquery/osquery/blob/29f4694df214bc3bd4e7210873e05bb19374888b/osquery/tables/system/darwin/crashes.cpp#L163-L170

I did update the `kernel_panics` table before, because the kernel panic file format had changed both in macOS updates and in the split to Apple Silicon. But I avoided trying to parse the `.ips` file format. It still parses `.panic` files in that table:

https://github.com/osquery/osquery/blob/d8330d915869281a366eb8f48c42a3a7a14e418f/osquery/tables/system/darwin/kernel_panics.cpp#L166-L170

So before getting started on `crashes`, let's check whether the changes are in x86 and ARM, just ARM, or what. Maybe it's not needed to parse `.ips` files here either.

**Comment by mike-myers-tob** [comment]
> Taking a stab at the new paths to enumerate (while I'm still working on a canonical reference for the paths post-.ips migration on macOS) I'm seeing
> 
> ```
> /Library/Logs/DiagnosticReports/%.ips
> /Library/Logs/DiagnosticReports/Retired/%.ips
> $USER/Library/Logs/DiagnosticReports/%.ips
> $USER/Library/Logs/DiagnosticReports/Retired/%.ips
> ```

Confirmed that these are the crash report locations for macOS 13 Ventura on Intel at least.

Steps to (re)produce for a `User` process crash:

1. find the PID of a process you can safely abort
2. `kill -3 <pid>` and wait a few seconds, check `~/Library/Logs/DiagnosticReports/` and find a new `.ips` file.

If a `System` process fails the crash report becomes an `.ips` file in the `/Library/Logs/DiagnosticReports/` directory. Both kinds will be listed in Console.app under `Crash Reports`. You can also, from Console, double-click to open the report and then click the `Reveal` button to jump to where it exists in Finder.

The `Retired` subdirectory appears to be where reports go after some initial processing step, maybe they are reported to Apple and then moved here for expiration/deletion. That's just my guess.

**Comment by mike-myers-tob** [comment]
> But poking around this machine, I see my crash in `/Library/Logs/DiagnosticReportsForNewHardware` I don't know if this directory is specific to the dev kit, or more general. I also see crashes in `/Library/Logs/CrashReporter` which don't appear to be mobile. So we might want to revisit this list.

Yea I bet `DiagnosticReportsForNewHardware` was a devkit thing that was changed before release. Though I'm curious if you can share how to make something produce in the `CrashReporter` directory. On two different Intel macOS Ventura systems at least, this directory doesn't exist.

**Comment by mike-myers-tob** [comment]
[macOS 11 Intel crash report.crash.txt](https://github.com/osquery/osquery/files/10023877/macOS.11.Intel.crash.report.crash.txt)
[macOS 13 Intel crash report ips.txt](https://github.com/osquery/osquery/files/10023878/macOS.13.Intel.crash.report.ips.txt)
[macOS 13 ARM crash report.ips.txt](https://github.com/osquery/osquery/files/10023879/macOS.13.ARM.crash.report.ips.txt)
[macOS 12 ARM crash report.ips.txt](https://github.com/osquery/osquery/files/10023880/macOS.12.ARM.crash.report.ips.txt)

From regression testing it appears that the shift from the unstructured log format (with `.crash` file extension) changed to the JSON-like format (with `.ips` file extension) with macOS 12. We'll have to give osquery the ability to check for both kinds of files.

Other than checking the `Retired` subdirectories I don't _think_ there's any other new paths to check.
