### ISSUE TITLE
authorized_keys table not retrieving records from non-root users

### ISSUE THREAD

**Issue by rmspeers** [osquery/osquery#6777]
# Bug report

### What operating system and version are you using?

ubuntu 18.04.4 LTS

### What version of osquery are you using?

4.5.1 (installed via Kolide Launcher)

NOTE: running it as root:
```
root      7495  1.1  0.6 817600 26100 ?        Sl   01:02   0:00 /usr/local/XXX/bin/osqueryd-updates/ZZZZZZZZ/osqueryd --logger_plugin=kolide_grpc --distributed_plugin=kolide_grpc --disable_distributed=false --distributed_interval=5 --pack_delimiter=: --host_identifier=uuid --force=true --disable_watchdog --utc --config_refresh=300 --config_accelerated_refresh=30 --pidfile=/var/XXX/YYY/osquery.pid --database_path=/var/XXX/YYY/osquery.db --extensions_socket=/var/XXX/YYY/osquery.sock --extensions_autoload=/var/XXX/YYY/osquery.autoload --extensions_timeout=10 --config_plugin=kolide_grpc
```

### What steps did you take to reproduce the issue?

- created /root/.ssh/authorized_keys with an authorized key entry
- created /home/admin/.ssh/authorized_keys with the same authorized key entry
- ensured both files were chowned/group'ed to their user/group, and were set as u+rw only on chmod.
- queried the host with `SELECT * from authorized_keys` and also `SELECT users.username, ak.uid, ak.algorithm, ak.key_file, ak.key FROM authorized_keys AS ak JOIN users ON ak.uid = users.uid;`
- tried also without the root file, just with the admin file, to make sure things weren't being deduplicated or anything.

### What did you expect to see?

- when both files present: two authorized keys entries, one from the root file, one from the admin file.
- when only the admin file present: one authorized keys entry, for the admin file

### What did you see instead?

- result for when the authorized key entry was at /root/.ssh/authorized_keys
- no result for when the authorized key entry was at /home/admin/.ssh/authorized_keys

**Comment by directionless** [comment]
I would expect this to need the `uid` passed in. Does it work if you join it against the users table?

**Comment by qwerty1q2w** [comment]
@directionless thanks:) 
SELECT * FROM users CROSS JOIN authorized_keys USING (uid);
