### ISSUE TITLE
Apple Silicon/M1 shows incorrect cpu_type & cpu_subtype

### ISSUE THREAD

**Issue by dgaffield** [osquery/osquery#6784]
# Bug report

### What operating system and version are you using?

macOS Big Sur on M1

```
osquery> SELECT version, build, platform FROM os_version;
+---------+-------+----------+
| version | build | platform |
+---------+-------+----------+
| 10.16   | 20B29 | darwin   |
+---------+-------+----------+
```

### What version of osquery are you using?

```
osquery> SELECT version from osquery_info;
+---------+
| version |
+---------+
| 4.5.1   |
+---------+
```

### What steps did you take to reproduce the issue?

Run the following query:

`select cpu_type, cpu_subtype from system_info;`

### What did you expect to see?

```
osquery> select cpu_type, cpu_subtype from system_info;
+----------+-------------+
| cpu_type | cpu_subtype |
+----------+-------------+
| arm64    | ?           |
+----------+-------------+
```

Unsure about expected value for cpu_subtype as of this writing.

### What did you see instead?

```
osquery> select cpu_type, cpu_subtype from system_info;
+----------+-------------+
| cpu_type | cpu_subtype |
+----------+-------------+
| i486     | Intel 80486 |
+----------+-------------+
```

**Comment by alessandrogario** [comment]
Hello @dgaffield,

thanks for the bug report! I believe it is normal for these fields to report those values when osquery is running through Rosetta. Once we have native support for the new architecture, we should no longer have this issue

**Comment by directionless** [comment]
In some ways, that is correct -- it's displaying what rosetta is emulating as.

**Comment by directionless** [comment]
I'm going to close this. This works as designed, and will change when we ship a native m1 binary. While we don't have an issue for that, we aren't going to forget

**Comment by dgaffield** [comment]
Thanks @directionless!  Is there a timeline when native m1 support will be available?

**Comment by directionless** [comment]
> Thanks @directionless! Is there a timeline when native m1 support will be available?

We do not have a formal timeline.
