### ISSUE TITLE
Outdated sqlite in  osqueryd.exe

### ISSUE THREAD

**Issue by great944** [osquery/osquery#6797]
Please update SQLite to latest, current version is showing critical vulnerabilities with Black Duck binary analysis. Thank you!

**Comment by crazysurjeet** [comment]
@alessandrogario Can the SQLite package in osqueryd.exe be updated to latest in the upcoming release 4.6.0?

Thanks.

**Comment by great944** [comment]
Thank you for closing this issue.

**Comment by crazysurjeet** [comment]
Thank you @alessandrogario for addressing this issue & Thank you @great944 for raising this issue.
