### ISSUE TITLE
Windows: establish secure ACLs on the Thrift pipe

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#6798]
# Bug report

It has been brought to my attention (semi-publicly, a couple of times, which is why I'm making a GitHub issue for it here) that the Thrift (named pipe `\Device\NamedPipe\osquery.em`) on Windows is created by osquery in such a way that any user can access it, rather than just Administrator.

### What operating system and version are you using?

Windows (affected versions TBD, probably all)

### What version of osquery are you using?

4.5

### What steps did you take to reproduce the issue?

`osqueryi.exe --disable_extensions=false --extensions_socket="\\.\pipe\osquery.em"`

Then, find the handle using SysInternals Process Explorer's "Find Handles or DLLs" and searching for "osquery.em" or selecting `osqueryd.exe` in the process list and viewing the handles and DLLs pane, then checking the security properties on the handle `Device\NamedPipe\osquery.em`.

Alternatively, use SysInternals `accesschk`:

```
accesschk \pipe\shell.em

Accesschk v6.13 - Reports effective permissions for securable objects
Copyright ⌐ 2006-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

\\.\Pipe\shell.em
  RW Everyone
  RW BUILTIN\Administrators
```

### What did you expect to see?

NamedPipe should not be accessible by unprivileged users.

### What did you see instead?

![image](https://user-images.githubusercontent.com/30631532/101552371-9a6a3b00-3967-11eb-84f4-7a59ea0e8356.png)

**Comment by mike-myers-tob** [comment]
Solution, as pointed out in the osquery Slack, is probably to leverage a new feature of Thrift `TPipeServer` class that allows the caller to specify the security descriptor of the Named Pipe object in the class constructor. https://github.com/apache/thrift/pull/2083

https://github.com/apache/thrift/commit/36bf0a491e900f09b894b54dbe037262acec73e5

This would require building against a version of Thrift newer than their most recent [release](https://github.com/apache/thrift/releases), 0.13.0.

And making changes in `impl_thrift.cpp`

**Comment by theopolis** [comment]
That's a great solution!

Off the top of my head I think we have more than one option. 1. We can pin our submodule to that exact commit. 2. We can pin to 0.13 and use our CMake patch tooling to apply the specific commits needed to add the description functionality. We can keep these as patch files in our repo (follow the precedent of some of our other libraries).

The downside to 1 is less support as it is not an official release and there might be bugs; as well as we'll lose the shallow clone ability (which saves initial build and CI time).

The potential downside to 2 is that the patches might not apply cleanly making this approach untenable.

Other options or ideas?

**Comment by theopolis** [comment]
I tried to handle some of the heavy lifting by bringing thrift to version 0.13.0 here: https://github.com/osquery/osquery/pull/6822. I expect to spend some more time on that PR.

**Comment by mike-myers-tob** [comment]
> I tried to handle some of the heavy lifting by bringing thrift to version 0.13.0 here: #6822. I expect to spend some more time on that PR.

Thanks! I can use this to try to make the changes in impl_thrift.cpp.
