### ISSUE TITLE
Battery table misreports on apple silicon m1 machines

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6800]
osquery 4.5.1 on an m1 13" MacBook Pro, Big Sur `20B29`

As compared to an x86 macbook (also running Big Sur) the battery table is notable different:
1. The `health` column reports "check battery" this should report "healthy". (other os tools report it that way)
2. `max_capacity` now reports `100` instead of something like `5552` (this might be an intentional platform change)

**Comment by mike-myers-tob** [comment]
Note that this has to be tested on a laptop with a battery, our CI system or our M1 Mac Mini (no battery) will return 0 rows on this. Tagging @sharvilshah in case he can build our M1 branch and see if it works when built natively.

**Comment by directionless** [comment]
Testing this with an m1 build, this bug is still present.

**Comment by MScottBlake** [comment]
I can also confirm that this bug is still present in the current release, 5.2.2.

**Comment by roperzh** [comment]
I'm not sure this is exclusive of M1 machines, the query below was written on a MacBook Pro 2019, Intel Core i9, note the `health` value:

```
osquery> select * from battery;
          manufacturer = DSY
      manufacture_date =
                 model = bq20z451
         serial_number = <redacted>
           cycle_count = 607
                health = Check Battery
             condition =
                 state = AC Power
              charging = 0
               charged = 1
     designed_capacity = 7336
          max_capacity = 5179
      current_capacity = 5179
     percent_remaining = 100
              amperage = -35
               voltage = 12467
   minutes_until_empty = 0
minutes_to_full_charge = 0
```

my osquery version is 5.2.2

**Comment by sharvilshah** [comment]
> I'm not sure this is exclusive of M1 machines, the query below was written on a MacBook Pro 2019, Intel Core i9, note the `health` value:
> 
> ```
> osquery> select * from battery;
>           manufacturer = DSY
>       manufacture_date =
>                  model = bq20z451
>          serial_number = <redacted>
>            cycle_count = 607
>                 health = Check Battery
>              condition =
>                  state = AC Power
>               charging = 0
>                charged = 1
>      designed_capacity = 7336
>           max_capacity = 5179
>       current_capacity = 5179
>      percent_remaining = 100
>               amperage = -35
>                voltage = 12467
>    minutes_until_empty = 0
> minutes_to_full_charge = 0
> ```
> 
> my osquery version is 5.2.2

@roperzh Can you post the `Power` details from the `System Information` app from that machine? I am wondering if that is an actual case of battery not being normal on that intel macbook...

**Comment by stephanmiehe** [comment]
I came here to report the `Check Battery` health result and found this issue. Based on https://github.com/osquery/osquery/blob/master/specs/darwin/battery.table#L9 `Check Battery` doesn't seem to be a documented state. If this value is indeed expected, could https://github.com/osquery/osquery/blob/master/specs/darwin/battery.table#L9 be updated to reflect the correct meaning of this state?
