### ISSUE TITLE
Remove VACUUM INTO and ATTACH DATABASE as potential security risk

### ISSUE THREAD

**Issue by nmeocisco** [osquery/osquery#6807]
# Feature request

### What new feature do you want?

It would be good to remove the VACUUM INTO and ATTACH DATABASE features of SQLite as they are potential security risks in certain environments.

### How is this new feature useful?

The removal of VACUUM INTO would prevent files from being written to the file system. It cannot overwrite existing files as far as I can tell, but it can still write a SQLite file to somewhere that some other software might automatically pick it up from or at a minimum it can be used to fill up disk space.

The removal of ATTACH DATABASE would prevent arbitrary reading of other users SQLite databases when osquery is used in remote environments.

### How can this be implemented?

Build SQLite without the VACUUM INTO and ATTACH DATABASE features, or offer an option to disable them.

**Comment by directionless** [comment]
Thanks for the report! This had been reported to us a few days prior. It is assigned as https://github.com/osquery/osquery/security/advisories/GHSA-4g56-2482-x7q8 and has been patched in https://github.com/osquery/osquery/commit/c3f9a3dae22d43ed3b4f6a403cbf89da4cba7c3c

It will be part of the 4.6.0 release.
