### ISSUE TITLE
Allowlist TABLE_INFO pragma

### ISSUE THREAD

**Issue by dannykopping** [osquery/osquery#6813]
# Feature request

### What new feature do you want?

As per https://github.com/osquery/osquery/pull/6812, I require the [`TABLE_INFO`](https://www.sqlite.org/pragma.html#pragma_table_info) pragma command to be available.

### How is this new feature useful?

It is used to retrieve a table's columns via SQL; this is not possible through any other means in SQL (to my knowledge)

**Comment by directionless** [comment]
I think we want:
* `table_info`
* `table_xinfo`

None of the other jump out at me.

**Comment by theopolis** [comment]
If you really wanted to do this now:
```sql
WITH columns(name, type, str) AS (
    select '', '', substr(sql, 0, length(sql)) || ',' from sqlite_temp_master where name = "yum_sources"
    UNION ALL SELECT
    substr(substr(str, instr(str, '`')+1), 0, instr(substr(str, instr(str, '`')+1), '`')),
    substr(
      substr(str, instr(str, '`')+1),
      instr(substr(str, instr(str, '`')+1), '`')+2,
      instr(substr(str, instr(str, '`')+1), ',')-instr(substr(str, instr(str, '`')+1), '`')-2
    ),
    substr(str, instr(str, ',')+1)
    FROM columns WHERE str!=''
) SELECT name, type FROM columns WHERE name!='';
```

Not 100% tested, sort of quickly hacked that together, @FritzX6 is much better at this hehe

**Comment by dannykopping** [comment]
That's pretty epic

**Comment by directionless** [comment]
Oh! You found `sqlite_temp_master` amazing! I found `sqlite_master` but it didn't have the info, and I saw nothing in the docs about `sqlite_temp_master`. Beautiful. That's looks exactly like the `.schema` output.
