### ISSUE TITLE
UID column empty in chrome_extension_content_scripts on Windows

### ISSUE THREAD

**Issue by sevickson** [osquery/osquery#6830]
### What operating system and version are you using?
version = 10.0.19041
platform = windows

### What version of osquery are you using?
version = 4.5.1

### What steps did you take to reproduce the issue?
`SELECT uid,identifier FROM chrome_extension_content_scripts;`

### What did you expect to see?
I expected to see the uid column populated as this is a column that can be used to JOIN according to this warning:
```
W1221 12:36:06.372776 28564 virtual_table.cpp:962] The chrome_extension_content_scripts table returns data based on the current user by default, consider JOINing against the users table
W1221 12:36:06.372776 28564 virtual_table.cpp:977] Please see the table documentation: https://osquery.io/schema/#chrome_extension_content_scripts
```

### What did you see instead?
All uid fields empty.
````
+-----+----------------------------------+
| uid | identifier                       |
+-----+----------------------------------+
|     | <chrome_id> |

**Comment by mike-myers-tob** [comment]
Confirmed on osquery 4.6.

Possible workaround: get `uid` from the `chrome_extensions` table in a `JOIN`:

```
osquery> select chrome_extensions.uid, identifier,name from chrome_extension_content_scripts JOIN chrome_extensions using (identifier);
+------+----------------------------------+----------------------+
| uid  | identifier                       | name                 |
+------+----------------------------------+----------------------+
| 1002 | cmedhionkhpnakcndndgjdbohmhepckk | Adblock for Youtube™ |
| 1002 | cmedhionkhpnakcndndgjdbohmhepckk | Adblock for Youtube™ |
+------+----------------------------------+----------------------+
```

Note: I also confirmed that PR #6780 (as it stands now) does not change this column behavior in `chrome_extension_content_scripts`. @alessandrogario do you know how these two tables are intended to be used with regard to `uid`?
