### ISSUE TITLE
How to convert time into localtime and get user login/logout times

### ISSUE THREAD

**Issue by bhuvaneswari01** [osquery/osquery#6841]
How to write the query to convert time into local time in osquery?
how to write the query to get users login and logout times in osquery?

**Comment by Smjert** [comment]
Welcome @bhuvaneswari01!
If you have a unix epoch timestamp, you can convert it in this way: `select datetime(<timestamp>, 'unixepoch', 'localtime');`.
For instance, I'm in GMT+1, some minutes ago I saved the timestamp `1608713897`; if I do:
```
select datetime(1608713897, 'unixepoch');
+-----------------------------------+
| datetime(1608713897, 'unixepoch') |
+-----------------------------------+
| 2020-12-23 08:58:17               |
+-----------------------------------+
```
I get a date in UTC time, otherwise if I do:
```
select datetime(1608713897, 'unixepoch', 'localtime');
+------------------------------------------------+
| datetime(1608713897, 'unixepoch', 'localtime') |
+------------------------------------------------+
| 2020-12-23 09:58:17                            |
+------------------------------------------------+
```
I get my localtime, which is correct.

You can do the same starting from a datetime format:
```
select datetime('2020-12-23T08:58:17Z', 'localtime');
+-----------------------------------------------+
| datetime('2020-12-23T08:58:17Z', 'localtime') |
+-----------------------------------------------+
| 2020-12-23 9:58:17                            |
+-----------------------------------------------+


For the login/logout times, you can query the `last` table.

For other questions, I would suggest joining our channel on [Slack](https://slack.osquery.io/), and ask there.

**Comment by bhuvaneswari01** [comment]
thanks for the reply.

I want to change it to permantely . Beacuse when i am using logon_session table . still it is showing the "logon time as logon_time = 1607917834".  Please help.

**Comment by bhuvaneswari01** [comment]
For login/logout times, i have checked with last table.. But in windows platform , it is saying "No last table" in osquery"".
![image](https://user-images.githubusercontent.com/50693425/102985496-43529180-4535-11eb-8cfc-04db1c9670c9.png)
[](url)
[last table.docx](https://github.com/osquery/osquery/files/5734544/last.table.docx)
