### ISSUE TITLE
how to get login/logout time in osquery

### ISSUE THREAD

**Issue by bhuvaneswari01** [osquery/osquery#6843]
i want to know login/logout time details for all users who has logged into the machine on particular day. 

I tried with "last" table.. But it doesn't work and getting error as " no such table : last". .

Please let me know is there any alternative tables or commands to get the login/logout time by using the osquery.

Note: I
[last table.docx](https://github.com/osquery/osquery/files/5734647/last.table.docx)
n Windows Last table is not availble as per osquery schem documentation(https://osquery.io/schema/4.6.0/#last)

**Comment by Smjert** [comment]
I'm not sure this is currently available on Windows; there's a previous issue tracking this: https://github.com/osquery/osquery/issues/5556

**Comment by bhuvaneswari01** [comment]
Is the osquery is based on server side application? Can we integrate this with logstash?

**Comment by Smjert** [comment]
> Is the osquery is based on server side application? Can we integrate this with logstash?

I highly recommend joining our Slack: https://slack.osquery.io/, it's better suited for answering multiple questions like this.
We normally use the issue tracker for bugs/feature requests. I would use the issue tracker as a last restort if you weren't able to get any answer on Slack.
Thanks!

**Comment by bhuvaneswari01** [comment]
I am not able to access the Slack. 

Error: This site can’t be reachedCheck if there is a typo in slack.osquery.io.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Smjert** [comment]
> I am not able to access the Slack.
> 
> Error: This site can’t be reachedCheck if there is a typo in slack.osquery.io.
> If spelling is correct, try running Windows Network Diagnostics.
> DNS_PROBE_FINISHED_NXDOMAIN

Sorry! My bad, I took the wrong link, please try: https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw

**Comment by Smjert** [comment]
Closing the issue, since the original question has been answered, and the user joined the Slack channel.
