### ISSUE TITLE
login logout time data

### ISSUE THREAD

**Issue by bhuvaneswari01** [osquery/osquery#6857]
Hi 

I have seen the blow code in osquery issues link (https://github.com/osquery/osquery/issues/5556). Please let us know where to add the code to get login and logout times.
[osquery issue.docx](https://github.com/osquery/osquery/files/5745994/osquery.issue.docx)

auto logon_time = longIntToUnixtime(session_data->LogonTime);
auto logoff_time = longIntToUnixtime(session_data->LogffTime);
r["logon_time"] = BIGINT(logon_time) // This is what it should be substituted with
r["logoff_time"] = BIGINT(logoff_time);
r["duration"] BIGINT(logoff_time - logon_time);

**Comment by bhuvaneswari01** [comment]
please update on this.

**Comment by directionless** [comment]
duplicate
