### ISSUE TITLE
Logstash integration

### ISSUE THREAD

**Issue by bhuvaneswari01** [osquery/osquery#6862]
i want integrate the ELK stack with Osquery.. For that i have followed the Osquery documentation(https://osquery.readthedocs.io/en/stable/deployment/log-aggregation/#logstash). Even after completing the configuration i didn't get the fileds in kibana. Please let me know how to get and confirm Whether this logstash interation will support in Windows Platform. Since i am using the Windows platform?

**Comment by directionless** [comment]
This does not sound like an osquery bug. This sounds like a log stash question. I'd love to see what the result is.
