### ISSUE TITLE
shell_history table shows 0 as value for "time" column 

### ISSUE THREAD

**Issue by Kirtar22** [osquery/osquery#6864]
# Bug report

### What operating system and version are you using?
**Operating System :** 

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"

### What version of osquery are you using?
osquery> .version
osquery 4.5.1
using SQLite 3.31.1

### What steps did you take to reproduce the issue?
ran the query again 
### What did you expect to see?
While running the query "select * from shell_history", I get the data as expected except the column "time" where I get 0 in all raws.  I expected to see the timestamp when the command was run. 

select * from shell_history;

+-----+------+-------------------------------------------------------------------------+---------------------+
| uid | time | command                                                                 | history_file        |
+-----+------+-------------------------------------------------------------------------+---------------------+
| 0   | 0    | cd /var/log/                                                            | /root/.bash_history |
| 0   | 0    | ls -l                                                                   | /root/.bash_history |
| 0   | 0    | tail auth.log                                                           | /root/.bash_history |
| 0   | 0    | date                                                                    | /root/.bash_history |
| 0   | 0    | cd /                                                                    | /root/.bash_history |
| 0   | 0    | ls -l                                                                   | /root/.bash_history |
| 0   | 0    | cd /home/                                                               | /root/.bash_history |
| 0   | 0    | ls -l                                                                   | /root/.bash_history |
| 0   | 0    | cd /var/log/                                                            | /root/.bash_history |
| 0   | 0    | ls -l                                                                   | /root/.bash_history |
| 0   | 0    | tail syslog                                                             | /root/.bash_history |
| 0   | 0    | cd ..                                                                   | /root/.bash_history |
| 0   | 0    | cd /etc/                                                                | /root/.bash_history |
| 0   | 0    | ls -l                                                                   | /root/.bash_history |
| 0   | 0    | apt list --installed                                                    | /root/.bash_history |

### What did you see instead?
I see all 0 in column time as shown in the output above.

**Comment by Smjert** [comment]
Have you checked the content of `/root/.bash_history`, does it contain a timestamp?

My `.bash_history` doesn't have any timestamp, and my `.zhistory` too for some initial commands.
For bash this seems to be because the env var `HISTTIMEFORMAT` has not been set for that user, so timestamps do not get saved by bash.
For zsh I believe it's the `extendedhistory` option.

**Comment by Kirtar22** [comment]
@Smjert - yeah, I did understand that there is no timestamp in `/root/.bash_history` file. I was wondering if I am missing something as why there is a timestamp column in the table as there is no timestamp in the file.  I was completely obliviated about `HISTTIMEFORMAT` !! I get the point. I believe that is the reason why it is not getting recorded. Thanks for quick update.
