### ISSUE TITLE
Always log the scheduled query before it is run

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#6923]
# Feature request

Always log the scheduled query before it is run

### What new feature do you want?

At the moment with verbose logging enabled we will get a log line when each scheduled query is run:

```
I0126 05:11:26.115936 12540 scheduler.cpp:102] Executing scheduled query Test: SELECT * FROM processes;
```

This is really useful for tracking down run away queries. However this can only be done with ```--verbose``` set so can only really be used after the fact. 

Could we configure osquery to always log the name of the scheduled query running?
```
I0126 05:11:26.115936 12540 scheduler.cpp:102] Executing scheduled query Test
```

### How is this new feature useful?

Now when tracking down queries it's easy to see which queries have been run without additional configuration.

### How can this be implemented?

Change [scheduler launchQuery function](https://github.com/osquery/osquery/blob/master/osquery/dispatcher/scheduler.cpp#L103) to log the query name at info level e.g:
```
  LOG(INFO)  << "Executing scheduled query " << name;
  VLOG(1) << query.query;
```

If this deemed to be too noisy would get put the feature behind a flag. 
```
if(FLAGS_log_scheduled_query) 
     LOG(INFO)  << "Executing scheduled query " << name;
VLOG(1) << "Executing scheduled query " << name << ": " << query.query;
```
I am happy to raise a PR if we this is something we think we should add.

**Comment by theopolis** [comment]
We originally had the full query logging as an INFO log and folks thought it was too noisy. We could meet in the middle and restore just the name of they query being logged. My preference would be something like `if (!verbose) { log_name } else { log_name_and_query }`, where in either case we only log a single line.
