### ISSUE TITLE
All values in table osquery_schedule are 0

### ISSUE THREAD

**Issue by MichaelHBE** [osquery/osquery#6935]
Hello

I have a question regarding the table osquery_schedule. I would like to use the information in this table to monitor the queries and their performance. Unfortunately the values are all zero 0 (please see the attached csv osquery_schedule.log with the table content). This is the same for all systems in our company.

System: RedHad 8 (we also have RedHat 7 and Windows Server with the same behavior)
Kernel: 4.18.0
OsQuery version: 4.0.2 (on Windows we have 4.5.something and we are planning to move to 4.6.0)

If helpful, I can also upload the flagfile file. In the past we had some issues with few queries and had to tweak the watchdog settings in a not favorable way. I was hoping to use the osquery_schedule table to troubleshoot these issues and then use the watchdog again in a sensible way.

I am rather new to OsQuery, so I kindly ask you to be gentle :-) I am also fully aware that the queries might be rather unorthodox. But they fit into our new cybersecurity infrastructure. During the OsQuery conference two weeks ago I learned about eBPF tables and we will look into those tables very soon. I hope with this we can radically change the configuration and improve the overall usage.

In advance thank you very much for your understanding and your support.

Kind Regards
Michael

[osquery_schedule.log](https://github.com/osquery/osquery/files/5909379/osquery_schedule.log)

**Comment by directionless** [comment]
How did you generate that csv file?

**Comment by MichaelHBE** [comment]
I've performed the following command "osqueryi --flagfile /appl/osquery/etc/osquery.flags --csv "SELECT * from osquery_schedule;" > ~/osquery_schedule.csv"

**Comment by directionless** [comment]
Ah! I was wondering if it was `osqueryi`... Despite seeming like a database, for the most part osquery is a daemon that acts like an api translation layer. Which is to day that a running `osqueryd` and a invocation of `osqueryi` do not share context.

The `osquery_schedule` data is coming out of memory -- and for an `osqueryi` invocation, there have been no scheduled runs.

To query that from `osqueryd`, you'd need either a TLS server, extension, or to have that as a scheduled query outputting results.

**Comment by MichaelHBE** [comment]
Hello

Thank you very much for your answer. I know added the query to the pack and ran it with osqueryd. Out of 3 cases in 2 cases all values were empty :-(


Time | name | query | interval | executions | last_executed | denylisted | wall_time | user_time | system_time | average_memory
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Feb 11, 2021 @ 19:34:19.000 | pack_xy-cybersec-extra_osquery_schedule | SELECT * FROM osquery_schedule; | 21'600 | 0 | 0 | 0 | 0 | 0 | 0 | 0
Feb 11, 2021 @ 13:58:39.000 | pack_xy-cybersec_windows_security_products_snapshot | SELECT type, name, state,   state_timestamp, remediation_path, signatures_up_to_date FROM   windows_security_products; | 86'400 | 0 | 0 | 0 | 0 | 0 | 0 | 0
Feb 11, 2021 @ 13:58:39.000 | system_info | SELECT hostname, cpu_brand,   physical_memory FROM system_info; | 60 | 96 | 1'613'051'866 | 0 | 203 | 94 | 341 | 207'129


Unfortunately I cannot add the CSV as attachment to this message. I hope you can see the result above.
