### ISSUE TITLE
local_timezone value in time table is incorrect on Windows

### ISSUE THREAD

**Issue by clong** [osquery/osquery#6948]
# Bug report

### What operating system and version are you using?

```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.19042 | 19042 | windows  |
+------------+-------+----------+
```

### What version of osquery are you using?

4.6.0.2

### What steps did you take to reproduce the issue?

`SELECT * FROM time;`

### What did you expect to see?

local_timezone should show PST (or UTC-8)

### What did you see instead?

UTC
![Screen Shot 2021-02-12 at 1 30 39 PM](https://user-images.githubusercontent.com/5092699/107825625-48171300-6d38-11eb-96fa-4ea5c0d5488e.png)

**Comment by Smjert** [comment]
Does the flag `--utc=no` fixes the issue?

**Comment by clong** [comment]
Nope, seeing the same results with that flag

**Comment by manurautela** [comment]
strftime(...) api in **times** table seems to always return empty on my windows machine as well with or without utc flag.

[https://github.com/osquery/osquery/blob/77361f15f9f298cd0a47ea824b73c42a81981902/osquery/tables/utility/time.cpp#L54]

Using the code from std library to fetch the same details seem to work.

```diff
   char local_timezone[5] = {0};
   strftime(local_timezone, sizeof(local_timezone), "%Z", &local);
+  // This turns out to be empty with strftime, then we default to UTC
+  std::cout<< "osquery local_timezone: " << local_timezone << std::endl;
+
+#if  1
+  using sc = std::chrono::system_clock;
+  auto  tm = sc::to_time_t(sc::now());
+  std::stringstream local_tz;
+  std::stringstream local_tz_offset;
+
+  local_tz << std::put_time(std::localtime(&tm), "%Z");
+  local_tz_offset << std::put_time(std::localtime(&tm), "%z");
+  std::cout << "correct local timezone: " << local_tz.str() << " offset: " << local_tz_offset.str() << std::endl;
+#endif
```
![image](https://user-images.githubusercontent.com/1333906/109383928-bac6e780-790f-11eb-9839-611c4038f36f.png)

Also if  we the **TZ** environment variable we seem to get the time as set in that.
[https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tzset?view=msvc-160](url)

![image](https://user-images.githubusercontent.com/1333906/109384035-4476b500-7910-11eb-8af8-23c353365593.png)

**Comment by theopolis** [comment]
It looks like we've root caused this, is anyone able to submit a PR to fix?
