### ISSUE TITLE
pkg.osquery.io apt repository now failing due to gnutls_handshake errors

### ISSUE THREAD

**Issue by wfarr** [osquery/osquery#6967]
# Bug report

I wasn't sure the best place to report this since it doesn't cleanly fall under the core osquery nor the normal osquery-site. Apologies if this isn't the best spot.

### What operating system and version are you using?

```
 version = 14.04.6 LTS, Trusty Tahr
   build =
platform = ubuntu
```

### What version of osquery are you using?

Not relevant to the bug report.

### What steps did you take to reproduce the issue?

```
export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
apt-get update
```

### What did you expect to see?

A successful apt-get update.

### What did you see instead?

```
Err https://pkg.osquery.io deb/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
```

This only started occurring within the past 24 hours or so, which suggests a recent load balancer configuration change.

At the time of this writing, SSL Labs shows the following cipher suites as supported:

<img width="1048" alt="Screen Shot 2021-02-25 at 9 28 19 AM" src="https://user-images.githubusercontent.com/203/109167494-ce295580-774b-11eb-8107-28182483d65c.png">

Verifying with `gnutls-cli` shows that none of these are supported on the version of gnutls on Trusty:

```
apt-get update
apt-get install gnutls-bin
gnutls-cli -l | egrep 'TLS_AES_128_GCM_SHA256|TLS_AES_256_GCM_SHA384|TLS_CHACHA20_POLY1305_SHA256|TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256|TLS_ECDHE_RSA_WITH_AES_256_GCM_
SHA384|TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256|TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256|TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384|TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA|TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA'
```

And for reference the full set of cipher suites it does support:

```
root@2fc007a34533:/# gnutls-cli --version
gnutls-cli (GnuTLS) 2.12.23
Packaged by Debian (2.12.23-12ubuntu2)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Nikos Mavrogiannopoulos.
root@2fc007a34533:/# gnutls-cli -l
Cipher suites:
TLS_ANON_DH_ARCFOUR_MD5                           	0x00, 0x18	SSL3.0
TLS_ANON_DH_3DES_EDE_CBC_SHA1                     	0x00, 0x1b	SSL3.0
TLS_ANON_DH_AES_128_CBC_SHA1                      	0x00, 0x34	SSL3.0
TLS_ANON_DH_AES_256_CBC_SHA1                      	0x00, 0x3a	SSL3.0
TLS_ANON_DH_CAMELLIA_128_CBC_SHA1                 	0x00, 0x46	TLS1.0
TLS_ANON_DH_CAMELLIA_256_CBC_SHA1                 	0x00, 0x89	TLS1.0
TLS_ANON_DH_AES_128_CBC_SHA256                    	0x00, 0x6c	TLS1.2
TLS_ANON_DH_AES_256_CBC_SHA256                    	0x00, 0x6d	TLS1.2
TLS_PSK_SHA_ARCFOUR_SHA1                          	0x00, 0x8a	TLS1.0
TLS_PSK_SHA_3DES_EDE_CBC_SHA1                     	0x00, 0x8b	TLS1.0
TLS_PSK_SHA_AES_128_CBC_SHA1                      	0x00, 0x8c	TLS1.0
TLS_PSK_SHA_AES_256_CBC_SHA1                      	0x00, 0x8d	TLS1.0
TLS_DHE_PSK_SHA_ARCFOUR_SHA1                      	0x00, 0x8e	TLS1.0
TLS_DHE_PSK_SHA_3DES_EDE_CBC_SHA1                 	0x00, 0x8f	TLS1.0
TLS_DHE_PSK_SHA_AES_128_CBC_SHA1                  	0x00, 0x90	TLS1.0
TLS_DHE_PSK_SHA_AES_256_CBC_SHA1                  	0x00, 0x91	TLS1.0
TLS_SRP_SHA_3DES_EDE_CBC_SHA1                     	0xc0, 0x1a	TLS1.0
TLS_SRP_SHA_AES_128_CBC_SHA1                      	0xc0, 0x1d	TLS1.0
TLS_SRP_SHA_AES_256_CBC_SHA1                      	0xc0, 0x20	TLS1.0
TLS_SRP_SHA_DSS_3DES_EDE_CBC_SHA1                 	0xc0, 0x1c	TLS1.0
TLS_SRP_SHA_RSA_3DES_EDE_CBC_SHA1                 	0xc0, 0x1b	TLS1.0
TLS_SRP_SHA_DSS_AES_128_CBC_SHA1                  	0xc0, 0x1f	TLS1.0
TLS_SRP_SHA_RSA_AES_128_CBC_SHA1                  	0xc0, 0x1e	TLS1.0
TLS_SRP_SHA_DSS_AES_256_CBC_SHA1                  	0xc0, 0x22	TLS1.0
TLS_SRP_SHA_RSA_AES_256_CBC_SHA1                  	0xc0, 0x21	TLS1.0
TLS_DHE_DSS_ARCFOUR_SHA1                          	0x00, 0x66	TLS1.0
TLS_DHE_DSS_3DES_EDE_CBC_SHA1                     	0x00, 0x13	SSL3.0
TLS_DHE_DSS_AES_128_CBC_SHA1                      	0x00, 0x32	SSL3.0
TLS_DHE_DSS_AES_256_CBC_SHA1                      	0x00, 0x38	SSL3.0
TLS_DHE_DSS_CAMELLIA_128_CBC_SHA1                 	0x00, 0x44	TLS1.0
TLS_DHE_DSS_CAMELLIA_256_CBC_SHA1                 	0x00, 0x87	TLS1.0
TLS_DHE_DSS_AES_128_CBC_SHA256                    	0x00, 0x40	TLS1.2
TLS_DHE_DSS_AES_256_CBC_SHA256                    	0x00, 0x6a	TLS1.2
TLS_DHE_RSA_3DES_EDE_CBC_SHA1                     	0x00, 0x16	SSL3.0
TLS_DHE_RSA_AES_128_CBC_SHA1                      	0x00, 0x33	SSL3.0
TLS_DHE_RSA_AES_256_CBC_SHA1                      	0x00, 0x39	SSL3.0
TLS_DHE_RSA_CAMELLIA_128_CBC_SHA1                 	0x00, 0x45	TLS1.0
TLS_DHE_RSA_CAMELLIA_256_CBC_SHA1                 	0x00, 0x88	TLS1.0
TLS_DHE_RSA_AES_128_CBC_SHA256                    	0x00, 0x67	TLS1.2
TLS_DHE_RSA_AES_256_CBC_SHA256                    	0x00, 0x6b	TLS1.2
TLS_RSA_NULL_MD5                                  	0x00, 0x01	SSL3.0
TLS_RSA_NULL_SHA1                                 	0x00, 0x02	SSL3.0
TLS_RSA_NULL_SHA256                               	0x00, 0x3b	TLS1.2
TLS_RSA_EXPORT_ARCFOUR_40_MD5                     	0x00, 0x03	SSL3.0
TLS_RSA_ARCFOUR_SHA1                              	0x00, 0x05	SSL3.0
TLS_RSA_ARCFOUR_MD5                               	0x00, 0x04	SSL3.0
TLS_RSA_3DES_EDE_CBC_SHA1                         	0x00, 0x0a	SSL3.0
TLS_RSA_AES_128_CBC_SHA1                          	0x00, 0x2f	SSL3.0
TLS_RSA_AES_256_CBC_SHA1                          	0x00, 0x35	SSL3.0
TLS_RSA_CAMELLIA_128_CBC_SHA1                     	0x00, 0x41	TLS1.0
TLS_RSA_CAMELLIA_256_CBC_SHA1                     	0x00, 0x84	TLS1.0
TLS_RSA_AES_128_CBC_SHA256                        	0x00, 0x3c	TLS1.2
TLS_RSA_AES_256_CBC_SHA256                        	0x00, 0x3d	TLS1.2
Certificate types: CTYPE-X.509, CTYPE-OPENPGP
Protocols: VERS-SSL3.0, VERS-TLS1.0, VERS-TLS1.1, VERS-TLS1.2
Ciphers: AES-256-CBC, AES-128-CBC, 3DES-CBC, DES-CBC, ARCFOUR-128, ARCFOUR-40, RC2-40, CAMELLIA-256-CBC, CAMELLIA-128-CBC, NULL
MACs: SHA1, MD5, SHA256, SHA384, SHA512, MD2, RIPEMD160, MAC-NULL
Key exchange algorithms: ANON-DH, RSA, RSA-EXPORT, DHE-RSA, DHE-DSS, SRP-DSS, SRP-RSA, SRP, PSK, DHE-PSK
Compression: COMP-DEFLATE, COMP-NULL
Public Key Systems: RSA, DSA
PK-signatures: SIGN-RSA-SHA1, SIGN-RSA-SHA224, SIGN-RSA-SHA256, SIGN-RSA-SHA384, SIGN-RSA-SHA512, SIGN-RSA-RMD160, SIGN-DSA-SHA1, SIGN-DSA-SHA224, SIGN-DSA-SHA256, SIGN-RSA-MD5, SIGN-RSA-MD2
```

We're currently operating Ubuntu Trusty under Canonical's [ESM program](https://ubuntu.com/security/esm), and it's unlikely that any newer version of gnutls and associated libraries will be backported pending a major security issue. We'd kindly ask the cipher suites to be adjusted to support users still on this version of Ubuntu.

As a work-around in the mean time, we've had to start using the `pkg.osquery.io` repository over vanilla HTTP, which we hope to be a temporary fix as there [have been well known issues with using apt over HTTP](https://lists.debian.org/debian-security-announce/2019/msg00010.html) in the past that HTTPS mitigates.

**Comment by ryanbrainard** [comment]
When this happened before (https://github.com/osquery/osquery/issues/6653), switching to the backing S3 bucket `https://osquery-packages.s3.amazonaws.com/deb` worked around the issue. I just tried this again and it worked:

```
$ echo "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/deb deb main" | sudo tee /etc/apt/sources.list.d/osquery.list
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
$ sudo apt-get update
$ sudo apt-get install osquery
```

(@wfarr, fancy seeing you here!👋 )

**Comment by theopolis** [comment]
Heads up @directionless

**Comment by directionless** [comment]
> When this happened before (#6653), switching to the backing S3 bucket `https://osquery-packages.s3.amazonaws.com/deb` worked around the issue. I just tried this again and it worked:

Please don't swap to the bucket. I expect to wholly disable that at some point.

This is probably because I recently swapped CDN providers. I'll move back to the original one and see if I can replicate it

**Comment by directionless** [comment]
Thank you so much for the detailed bug report, it really helps me diagnose what's happening.

The new CDN (Fastly) defaults to using TLS 1.3 only. Trusty looks to be old enough that it doesn't have full TLS 1.3 support. I'm still investigating options here.

As a different work around, you could swap the transport to using `http`. The underlying contents are signed after all.

**Comment by wfarr** [comment]
Thanks for the rapid response here.

> As a different work around, you could swap the transport to using `http`. The underlying contents are signed after all.

While this makes for an acceptable temporary work-around, repo/package signatures aren't the only problem. Examples [like this one](https://lists.debian.org/debian-security-announce/2019/msg00010.html) demonstrate that MITM attacks that inject malicious content into the HTTP response can be used as well.

Is there any way we could enable TLS 1.2 with a cipher like [`TLS_RSA_AES_256_CBC_SHA256`](https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_CBC_SHA256/)? They would be flagged as "weak" by SSL Labs but are relatively better off than a some of the other TLS 1.2 ciphers that are supported by Trusty.

**Comment by directionless** [comment]
I'm chatting with Fasty support about enabling ciphers, yes.

Of course, one of the underlying issues is that Trusty is quite old, and I'd thought EoL. Though maybe theres still some options in extended support? Do you have a sense of when it would be reasonable to drop support for these older ciphers?

**Comment by wfarr** [comment]
Canonical's paid ESM support for Trusty ends on April 1, 2022. We're in the process of migrating away, but it is a significant undertaking.

**Comment by directionless** [comment]
Yeah.... I can sympathize. I was involved in a similar migration project off Precise, with a similar past-eol timeframe.

**Comment by theopolis** [comment]
For posterity, CloudFront had a checkbox to support the legacy ciphers. Fingers crossed Fastly has this option.

**Comment by directionless** [comment]
Hi @wfarr (and watchers). This should be fixed. It appears to work from a docker test host. I'm closing this, but feel free to comment or reopen if you have issues. (or want to confirm it, or want to chat)

Thank you again for the detailed report. 

For reference, fixing this required Fastly to enable the option for tls 1.2, since they're trying to desupport it. Once enabled it was a checkbox.

**Comment by wfarr** [comment]
I can confirm from our production hosts that it is indeed working for us once more. Thank you again!
