### ISSUE TITLE
Failed to apply thrift/src patch when cmake on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [osquery/osquery#6969]
step:
git clone https://github.com/osquery/osquery.git osquery
cd osquery\build
cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..

F:\facebook\osquery\build>cmake -version
cmake version 3.19.6

error:
-- Importing: source/thrift
error: patch failed: lib/cpp/src/thrift/transport/TPipeServer.cpp:28
error: lib/cpp/src/thrift/transport/TPipeServer.cpp: patch does not apply
error: patch failed: lib/cpp/src/thrift/transport/TPipeServer.h:88
error: lib/cpp/src/thrift/transport/TPipeServer.h: patch does not apply
CMake Error at libraries/cmake/source/modules/utils.cmake:91 (message):
  Failed to patch the following git submodule:
  "F:/gitP/facebook/osquery/libraries/cmake/source/thrift/src"
Call Stack (most recent call first):
  libraries/cmake/source/modules/utils.cmake:165 (patchSubmoduleSourceCode)
  libraries/cmake/source/modules/Findthrift.cmake:10 (importSourceSubmodule)
  CMakeLists.txt:182 (find_package)
  CMakeLists.txt:89 (importLibraries)
  CMakeLists.txt:229 (main)

**Comment by theopolis** [comment]
Are you using an older build folder? Can you try a new/clean build folder?

**Comment by Smjert** [comment]
Hello @QuellaZhang, with the steps you followed you would end up configuring the project inside the source folder itself, this is not correct.
Please take a look at https://osquery.readthedocs.io/en/latest/development/building/ and at the `Step 2: Download and build source on Windows` step: you need to create an additional folder for the build folder, either inside the source folder itself as the wiki guides you through, or as a separate folder wherever you want.
Then from there you would configure and build.

**Comment by QuellaZhang** [comment]
Thanks for your reminder, cmake will not update the submodules, so I manually update it, solved.
I apply the patch manually to verify whether it is a patch issue. :)
Closed.
