### ISSUE TITLE
Repeatable intermittent crash on some CentOS Linux hosts

### ISSUE THREAD

**Issue by WinMordekaiser** [osquery/osquery#6977]
# Bug report

### What operating system and version are you using?
CentOS release 6.2 (Final) rhel

### What version of osquery are you using?
4.4.0

### What steps did you take to reproduce the issue?
Start osquery and wait...

### What did you expect to see?
Osquery running normally.

### What did you see instead?
I have installed osquery on 1000+ server. And  10%  server coredump error at almost same time.  

### How I solved it?
I find there is  a  mistake in `osquery/tables/system/linux/process_open_pipes.cpp::parseInode`.
Here is my code that can run normally.
```
int parseInode(const std::string& pipe_str) {
  std::smatch match;
  if (std::regex_search(pipe_str, match, std::regex("\\d+"))) {
    try {
      return std::stoi(match[0]);
    }catch(...){
      return 0;
    }
  } else {
    return 0;
  }
}
```

I don't know the reason why osquery coredump. And is there any better way to solve it?

**Comment by mike-myers-tob** [comment]
Ok, so `std::regex_search` can return something that causes `std::stoi` to throw an exception? We should find other instances of this in the codebase?

**Comment by directionless** [comment]
An additional note here, is that this is  bug report for 4.4.0. And we think newer releases should have general try/catch blocks that would have caught this.
