### ISSUE TITLE
Leak using ConvertStringSidToSid  in Windows users table

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#6979]
I originally reported https://github.com/osquery/osquery/issues/6560 for a leak around this [sid](https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/users.cpp#L107). Looks like the LocalFree was removed in this change: https://github.com/osquery/osquery/pull/6782

Should we consider putting the Windows user SID code in some kind of RAAI class?

**Comment by theopolis** [comment]
Heads up @mike-myers-tob

**Comment by mike-myers-tob** [comment]
Ah! Those two PRs were around the same time, and maybe I didn't pick up the change correctly. I'll open another quick PR to fix this.

> Should we consider putting the Windows user SID code in some kind of RAAI class?

It's a good idea, but I'd have to ask someone else, right now I can't make the time to refactor the Windows code
