### ISSUE TITLE
Duplicate re-enrollments

### ISSUE THREAD

**Issue by zwass** [osquery/osquery#6993]
# Bug report

### What operating system and version are you using?
macos 11.1

### What version of osquery are you using?

4.6.0

### What steps did you take to reproduce the issue?

1. Run a TLS server (Fleet) connected osqueryd.
2. Invalidate the node key for the osqueryd client.

### What did you expect to see?

The client re-enrolls.

### What did you see instead?

The client sends 2 re-enrollment requests. This makes it difficult for a server to determine if multiple hosts are sharing the same identifiers or the same host is just sending duplicate requests. The issue is compounded by that fact that even if the first enrollment request succeeds, if the second request fails osqueryd will clear the new valid node key from the first request.

See these logs:

```
I0308 11:31:09.492324 90537984 tls.cpp:254] TLS/HTTPS POST request to URI: https://localhost:8080/api/v1/osquery/distributed/read
{"node_key":"ZV6vm3X96MhH0tMpBpW14lyq5kCEjP36"}
I0308 11:31:09.499801 88391680 tls.cpp:254] TLS/HTTPS POST request to URI: https://localhost:8080/api/v1/osquery/log
{"data":[{"hostIdentifier":"f2e359b1-0e7a-4030-90e5-17592cbd7fa4","calendarTime":"Mon Mar  8 19:30:59 2021 UTC","unixTime":"1615231859","severity":"0","filename":"tls.cpp","line":"254","message":"TLS/HTTPS POST request to URI: https://localhost:8080/api/v1/osquery/distributed/read","version":"4.6.0","decorations":{"host_uuid":"9AB68B8B-CF55-5DDD-8B4C-BF589E6A3586","hostname":"zachs-macbook-pro.local"}},{"hostIdentifier":"f2e359b1-0e7a-4030-90e5-17592cbd7fa4","calendarTime":"Mon Mar  8 19:30:59 2021 UTC","unixTime":"1615231859","severity":"0","filename":"tls.cpp","line":"254","message":"TLS/HTTPS POST request to URI: https://localhost:8080/api/v1/osquery/log","version":"4.6.0","decorations":{"host_uuid":"9AB68B8B-CF55-5DDD-8B4C-BF589E6A3586","hostname":"zachs-macbook-pro.local"}}],"log_type":"status","node_key":"ZV6vm3X96MhH0tMpBpW14lyq5kCEjP36"}
{
  "error": "authentication error: invalid node key: ZV6vm3X96MhH0tMpBpW14lyq5kCEjP36",
  "node_invalid": true
}

{
  "error": "authentication error: invalid node key: ZV6vm3X96MhH0tMpBpW14lyq5kCEjP36",
  "node_invalid": true
}

I0308 11:31:09.521951 88391680 buffered.cpp:90] Error sending status to logger: Request failed: Invalid node key: authentication error: invalid node key: ZV6vm3X96MhH0tMpBpW14lyq5kCEjP36
I0308 11:31:10.503829 87855104 config.cpp:1205] Refreshing configuration state
I0308 11:31:10.503998 87855104 tls_enroll.cpp:70] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8080/api/v1/osquery/enroll
I0308 11:31:10.516428 90537984 tls_enroll.cpp:70] TLSEnrollPlugin requesting a node enroll key from: https://localhost:8080/api/v1/osquery/enroll
```

**Comment by zwass** [comment]
This seems to only happen sometimes, depending on the timing of the various remote plugin threads.

**Comment by theopolis** [comment]
Hey @zwass, is this something you are investigating and plan to fix if possible?

**Comment by zwass** [comment]
I can have a look on Monday and see if I understand what the issue is. Not sure I will have the time to investigate if it's not relatively simple. Maybe there just needs to be a mutex on the enrollment code?

@theopolis do you know if the distributed query functionality runs in a separate thread from logging? That could potentially explain the behavior.

So far I've just modified the defaults in Fleet to work around this (as you can see in the linked PR above).
