### ISSUE TITLE
Invalid SQL generated for creating virtual tables with primary keys

### ISSUE THREAD

**Issue by uptycs-rmack** [osquery/osquery#7000]
If you enable sqlite logging, at osqueryi startup you'll see a bunch of spew similar to

near "WITHOUT": syntax error in "CREATE VIRTUAL TABLE temp.temperature_sensors USING temperature_sensors(`key` TEXT, `name` TEXT, `celsius` DOUBLE, `fahrenheit` DOUBLE, PRIMARY KEY (`key`)) WITHOUT ROWID"

The issue is that you can't put WITHOUT ROWID on a CREATE VIRTUAL TABLE statement but current code is doing that for any tables with a primary key specified.

I *think* the fix would be to change the call to columnDefinition() inside attachVirtualTables() to pass "is_extension = true". This would suppress the WITHOUT ROWID inside the std::string columnDefinition(const TableColumns& columns, bool is_extension) function.

A couple reasons I'm not putting up a PR yet:

1. I'm not sure if this matters. Apparently those tables still work even if the virtual table creation fails.
2. I'm hesitant to change is_extention to true because it might cause other changes now or later that we don't want.

Anyone familiar with this code want to advise on whether this is an appropriate fix? "Works for me" but I'm not confident.

**Comment by theopolis** [comment]
I will have to look into the code but I don't think `is_extension` should be set for tables that do not originate from extensions.

Another option might be to allow the `columnDefinition` API to take a parameter to skip emitting the `WITHOUT ROWID`.

But I also want to look into the incompatibility when using a `PRIMARY` key. I think the result within SQLite is that a table with an explicit primary key does not need the auto-generated `rowid` column and thus the `WITHOUT ROWID` qualifier is superfluous.

**Comment by theopolis** [comment]
Yeah, we definitely don't want to touch this without knowing exactly what effect we are creating. The `WITHOUT ROWID` was introduced to fix a bug where `xBestIndex` would incorrectly optimize away constraints. 

Imagine a complex query that SELECTs from `file` multiple times, the first time with `path = /dev/null` and the second with `path = /dev/tty`. When a `rowid` column is used (automatically added when `WITHOUT ROWID` is missing) then the `rowid` for both of these is `0` and SQLite internally can ditch the second result as an optimization technique.

You may be able to observe this behavior with a table like `package_install_history`, which does include a `rowid` column added by SQLite. Try selecting from this table twice and within a complex query and check if the actual table implementation is called twice.

Thus we remove rowid usage for any table that changes its behavior based on the query constraints.

**Comment by theopolis** [comment]
I realize that the documentation says rowids are not used for virtual tables: https://www.sqlite.org/rowidtable.html and I believe this is true because the data for virtual tables is not stored in a B-Tree or anywhere within SQLite internals. However, I think rowids are used in other parts of SQLite (for example the constraints optimization mentioned above).

**Comment by uptycs-rmack** [comment]
At the moment the CREATE VIRTUAL TABLE statement is simply failing though
because the parser doesn't recognize the WITHOUT ROW ID for the CREATE
VIRTUAL TABLE statement. It's no in the grammar. So I'm not entirely sure
how this is breaking things, but I have a hard time imagining how removing
WITHOUT ROW ID for the VIRTUAL TABLE case could make things worse.

**Comment by Smjert** [comment]
Also I may be wrong, but our tables might not need to be created at all because they are eponymous virtual tables (https://sqlite.org/vtab.html), because our xCreate function is the same as xConnect.

**Comment by Smjert** [comment]
I also remembered that a while back I reported this: https://github.com/osquery/osquery/issues/5714, which is related.
