### ISSUE TITLE
Update Thrift submodule to its new 0.14.1 release

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7008]
# Feature request

### What new feature do you want?

Update our Thrift dependency to 0.14, released 8 days ago https://github.com/apache/thrift/releases/tag/v0.14.1

### How is this new feature useful?

We can discontinue the use of our patches to Thrift 0.13.

Simplifies our codebase a little, gets any other new features of Thrift. 

Might improve Thrift reliability generally. See their list of fixed bugs https://github.com/apache/thrift/blob/master/CHANGES.md#c-glib

### How can this be implemented?

Update our Thrift submodule to this commit: https://github.com/apache/thrift/commit/f6fa1794539e68ac294038ac388d6bde40a6c237

**Comment by theopolis** [comment]
@mike-myers-tob is this something you are working on?

**Comment by mike-myers-tob** [comment]
No, and there's no driving need really, it's just something to do eventually.
