### ISSUE TITLE
Transactions no longer work

### ISSUE THREAD

**Issue by nmeocisco** [osquery/osquery#7013]
# Bug report

It appears that transaction statements such as BEGIN and ROLLBACK will no longer work. Doing a little digging it looks like this problem was introduced in osquery 4.6.0 with this change: https://github.com/osquery/osquery/commit/c3f9a3dae22d43ed3b4f6a403cbf89da4cba7c3c#diff-1da890eb014e479fd227a8b434d9b7dbe458984ef8ee2e4b35c6823ec7042b94

It looks like SQLITE_TRANSACTION needs to be added to that list which would make sense to have if other statements such as INSERT, UPDATE, and DELETE are allowed.

### What operating system and version are you using?

WIndows/Linux/MacOS

### What version of osquery are you using?

4.7.0

### What steps did you take to reproduce the issue?

1. Run osqueryi on the command line.
2. Type "BEGIN;" and press ENTER;

### What did you expect to see?

No error is returned and following queries will operate within the context of a transaction.

### What did you see instead?
```
E0318 12:59:10.311563 45195 sqlite_util.cpp:295] Authorizer denied action 22 BEGIN null null null
Error: not authorized
```

**Comment by directionless** [comment]
I'd love to hear more about how you use transactions! As osquery is primarily a readonly view of the underlying APIs, I don't think I've heard much about transaction usage

**Comment by nmeocisco** [comment]
Well in our case we create temporary tables for which data from multiple other queries are consolidated into and used for a final report. Once the contents of those temporary tables are retrieved after all the other queries have been executed, we perform a ROLLBACK to clean up and remove those temporary tables so subsequent runs can be performed without worrying about previous data. Without transactions things get a bit messier as manual cleanup would be required for various scenarios.

**Comment by directionless** [comment]
Thanks so much for describing your use case! I really enjoy hearing about how people use osquery.
