### ISSUE TITLE
leak in logged_in_users table around WTSEnumerateSessionsExW

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#7019]
# Bug report

I was analyzing a dump and noticed a high number of allocations around ```WTSEnumerateSessionsExW```. This seems to indicate a leak in the ```logged_in_users``` table. Looking a bit closer the call to [```WTSEnumerateSessionsExW```](https://github.com/osquery/osquery/blob/89ef888b6a83fc0e1ca03392b3fc93fbda5ca56a/osquery/tables/system/windows/logged_in_users.cpp#L49) is freed [here](https://github.com/osquery/osquery/blob/89ef888b6a83fc0e1ca03392b3fc93fbda5ca56a/osquery/tables/system/windows/logged_in_users.cpp#L153
). However the [docs ](https://docs.microsoft.com/en-us/windows/win32/api/wtsapi32/nf-wtsapi32-wtsenumeratesessionsexw) say:

>To free the returned buffer, call the WTSFreeMemoryEx function and set the WTSClassType parameter to WTSTypeSessionInfoLevel1

Are we actually freeing the whole structure?

**Comment by directionless** [comment]
Fixed by #7039
