### ISSUE TITLE
Osquery client sending many duplicate packets via TLS plugins to Fleet resulting in massive bandwidth usage

### ISSUE THREAD

**Issue by dachin11** [osquery/osquery#7021]
# Bug report

### What operating system and version are you using?
Operating System | 10
-- | --
OS Version | Professional x64 Edition Build 19042.867

and
`Mac OS X 10.15.7`

`c:\Program Files\osquery>osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 10.0.19042
   build = 19042
platform = windows`

`$ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 10.15.7
   build = 19H524
platform = darwin`

### What version of osquery are you using?

`c:\Program Files\osquery>osqueryi --line "SELECT version from osquery_info;"
version = 4.7.0`

`C02SGJ1PG8WP:cintel-importer gdasbach$ osqueryi --line "SELECT version from osquery_info;"
version = 4.4.0`

### What steps did you take to reproduce the issue?
Installed the client, connected to Fleet, scheduled a few simple queries

### What did you expect to see?
Expected to see typical traffic patters between clients and Fleet that match the amount of data we are receiving in Fleet log files (status and results) and in Splunk (Fleet ingests its logs to our Splunk infra).

### What did you see instead?
Out of ~4000 clients, we are seeing maybe 50 - 100 that are sending massive amounts of data to Fleet for no apparent reason - in the GB per hour range, yet the size of corresponding events in logs and in Splunk is orders of magnitude less.  Often when we observe this (but not always), we see no data from a client in status or results logs, though it's still transmitting data.  Here is section of pcap we did on a windows client that shows osquery sending each packet 5 - 7 times to Fleet, causing Fleet to reply 5 - 7 times.

![pcap](https://user-images.githubusercontent.com/65193620/112370263-64dd2980-8c9a-11eb-92e2-39fccc5d0fff.png)

Re-installing the client seems to temporarily resolve the issue on Mac, but not Windows.

General architecture looks like this:
![Screen Shot 2021-03-24 at 3 20 22 PM](https://user-images.githubusercontent.com/65193620/112391059-8814d280-8cb4-11eb-86c5-184320c6533b.png)

**Comment by mike-myers-tob** [comment]
> scheduled a few simple queries

Are any of those queries hitting evented tables (tables that gather events)? If so, can you say which tables are being queried?

**Comment by dachin11** [comment]
@mike-myers-tob, thanks for responding so quickly.  To answer your question, no.  Our only queries are very simple things like
`SELECT * FROM osquery_info`
`SELECT * FROM osquery_schedule`
`SELECT * FROM osquery_schedule WHERE denylisted='1';`
`SELECT path, label, program_arguments, inetd_compatibility, root_directory
FROM launchd`

Even though we have about 4000 hosts deployed and registered to Fleet, we are definitely still in the very beginning of our usage of scheduled queries and packs.

One other update that I've corrected in the original description - re-installing the client seems to only temporarily fix Macs, not Windows clients.

**Comment by dachin11** [comment]
Updated with high-level architecture

**Comment by mike-myers-tob** [comment]
> re-installing the client

So perhaps this resets the local database / backing store (RocksDB database), which somehow resolves the problem (if only temporarily). I don't have a working theory yet but, maybe that makes me think maybe the agent is sending the same cached query results repeatedly for some reason. Maybe it's failing to expire the data, maybe something else. Maybe Fleet is throwing away the redundant results logged from the agent, but I don't know that side as well.

When those clients are acting up, is there anything unusual about their rocksdb files? Size, or filesystem permissions or anything? Does the file grow indefinitely larger?

> Our only queries are very simple things

Ok next question, what interval are they scheduled for? It shouldn't matter, if it is only storing differential results in the local DB, but, maybe it is storing more than it should.

**Comment by dachin11** [comment]
> When those clients are acting up, is there anything unusual about their rocksdb files? Size, or filesystem permissions or anything? Does the file grow indefinitely larger?

Good thought.  I'll start checking on that.

> Ok next question, what interval are they scheduled for? It shouldn't matter, if it is only storing differential results in the local DB, but, maybe it is storing more than it should.

Our queries are either one per day or once per hour.

**Comment by directionless** [comment]
Do you know what's it's sending? I'd assume it's sending logs of some kind. There are couple of places I know the windows tables can get noisy

**Comment by dachin11** [comment]
@directionless, well that's really the crux of the issue - what is all the data the clients are sending, and what's happening to it?  As noted above, when we see this problem we can observe massive bandwidth usage from clients across our FWs / VPNs, but we do not see corresponding data in Fleet logs or in Splunk.  For example, we may see a host send 2 - 3 GB of data to our Fleet IPs over an hour, but only see a handful of entries in the status and results logs, which are then sent to Splunk.  The size of these events in Splunk total up to bytes of data, not gigabytes, and even totaling up the size of all active Fleet logs falls short of the amount of data being transmitted by a single host!

The first thing we tried was running the clients in debug mode.  Our samples show what appears to me to be normal actions - registration, client check-ins for distributed queries (on the distributed_interval), label queries and pack executions which are very simple and execute _at most_, once per hour.  Nothing to explain the extreme bandwidth usage.

After not finding anything definitive in debug, we started running pcaps.  A partial screenshot of the first pcap we ran on a Windows client is attached above.  It sparked this git issue as it was basically all duplicate packets being sent from the client.  I'm waiting on our CIT team to run more pcaps on 'problem' Windows clients.  Subsequent pcaps that have been run on Macs experiencing the issue show chunks of valid traffic followed by chunks of duplicate packets, then it repeats.  I think it's worth noting that pcaps on clients that aren't experiencing the issue don't show the duplicate packets and retransmissions.

**Comment by directionless** [comment]
I believe you can use the (undocumented) `-tls_dump` flag to osquery to see exactly what it's doing. Alternately, you might be able to configure an additional file system logger. 

Otherwise I'm not sure if instrumenting the server side is possible.

**Comment by dachin11** [comment]
@directionless - yes, using -tls_dump while running the client in debug mode is how we observed what the clients are doing - which isn't that much.

`sudo osqueryd --flagfile /etc/osquery/osquery.flags --ephemeral --disable_database --disable_logging --verbose -tls_dump`
It was also suggested to me that the --ephemeral flag shouldn't be used when debugging as that bypasses the local db, but I haven't yet figured out how to get it working with a temp db.

For example, over the last 24 hours we had one user send 37.2 GB of data through 2.3k connections to our VPN/FW destined to Fleet.  However, I have no data for that host in Fleet logs or Splunk and I can go back 7 days.  However, the fact that I can run debug on it and see data going back and forth shows that connectivity exists.

As I've typed this, I may have stumbled on the issue, or at least part of it.  Investigating the client above got me thinking - where is that data going?  Well, it seems that for this host, and several I've checked that are experiencing the extreme bandwidth issue, are able to successfully connect to `/api/v1/osquery/distributed/read`, but every call they make to `/api/v1/osquery/log` turns out to be a 400 in the Fleet nginx logs.  This explains why most of these nodes have very large rocks.db files and why we have no data for them in our Fleet status / results logs or Splunk.

Now the question becomes - why are they getting 400s when trying to log?  All of these systems are configured the same way per OS (i.e. all Windows the same, all Mac the same).  IIRC, 400s are usually some kind of request syntax issue.  I don't pretend to know how the tls_logger_plugin posts data to Fleet, but could there be a data issue of some kind in the local rocks.db that's causing the request to barf?  That would explain why starting with a fresh rocks.db works and why our debugging shows data being sent to Fleet OK as the --ephemeral flag is bypassing the DB.

**Comment by dachin11** [comment]
Hmm, just found this on https://osquery.readthedocs.io/en/latest/installation/cli-flags/

```
--logger_tls_endpoint=

The tls endpoint path, e.g.: /api/v1/logger when using the tls logger plugin. See the other tls_ related CLI flags.
```

Ours is set to
`--logger_tls_endpoint=/api/v1/osquery/log`

/log is working for us mostly....could it be it's newer or older than /logger?

**Comment by directionless** [comment]
Nice sleuthing! I suspect this is a fleet question. Perhaps 400 is signaling unauthorized or something.

osquery is using `/api/v1/logger` as an example. That is an arbitrary path. You'd need to match whatever your fleet server is configured with.

**Comment by dachin11** [comment]
Got it, thanks.  I've confirmed we have Fleet configured to log to` /api/v1/log`, which we'd have to have to be using since we get some logs.  :)

I'm going to ping this into the Fleet Slack channel and see if anyone has ideas.

**Comment by dachin11** [comment]
Can anyone confirm if osquery will continue to try to send logs to Fleet forever (so long as it has data queued locally) if it's not getting a 200 response? 

In the docs I see max attempts for config
`--config_tls_max_attempts=3`

and max attempts for distributed
`--distributed_tls_max_attempts=3`

But I don't see anything that seems to control how long clients will retry to send to Fleet.  If that doesn't exist, then it supports our theory that our clients are retrying over and over and over.

**Comment by Smjert** [comment]
> Can anyone confirm if osquery will continue to try to send logs to Fleet forever (so long as it has data queued locally) if it's not getting a 200 response?
> 
> In the docs I see max attempts for config
> `--config_tls_max_attempts=3`
> 
> and max attempts for distributed
> `--distributed_tls_max_attempts=3`
> 
> But I don't see anything that seems to control how long clients will retry to send to Fleet. If that doesn't exist, then it supports our theory that our clients are retrying over and over and over.

Conceptually all those will try indefinitely to either retrieve or send data, the difference is the delays they use and when.

For instance the tls config plugin, if the `--config_refresh > 0`, will try to retrieve the config from the remote (Fleet) up to `--config_tls_max_attempts` times, with an increasing delay of `attempt * attempt * 1s`, with `attempt = 1` initially.
These attempts are all considered inside the same request/refresh. If the refresh was successful, then it will wait `config_refresh` seconds and do another one, otherwise if it failed, it will wait `config_accelerated_refresh` seconds (default 300, 5 minutes) before doing another refresh.

Now for the log sending, there isn't a longer delay when it fails to send, moreover it does a single attempt to send the logs. So if it fails or succeeds to send them the next flush will happen anyway after `logger_tls_period` seconds which by default is 4 seconds.

**Comment by Smjert** [comment]
To add further information: the logs are sent in batches of `logger_tls_max_lines` (default `1024`) lines, every `logger_tls_period` (default 4) seconds as previously described, with a line of a max size of `logger_tls_max_linesize` (default 1MiB) bytes, and up to `buffered_log_max` lines (default 1 million) are kept in the database before having it starting to purge the older ones.

**Comment by dachin11** [comment]
Thanks @Smjert.

I still think the key issue here is why some of our clients continually get 400s from nginx/Fleet when trying to post their results, while many are able to send the data just fine.

I enabled debug logging on one of our Fleet servers and then watched specific client IPs.  It looks like each time a client successfully hits: `/api/v1/osquery/distributed/read` to check in, there are 3 lines logged to `/var/log/messages`:

`2021-03-29T21:41:23.756513+00:00 REDACTED fleet[8392]: {"component":"service","err":null,"ip_addr":"127.0.0.1:54380","level":"debug","method":"AuthenticateHost","took":"7.485037ms","ts":"2021-03-29T21:41:23.756398719Z","x_for_ip_addr":"x.x.x.x"}
2021-03-29T21:41:23.756770+00:00 REDACTED: {"component":"service","err":null,"ip_addr":"127.0.0.1:54380","level":"debug","method":"AuthenticateHost","took":"7.485037ms","ts":"2021-03-29T21:41:23.756398719Z","x_for_ip_addr":"x.x.x.x"}
2021-03-29T21:41:23.759726+00:00 REDACTED fleet[8392]: {"component":"service","err":null,"ip_addr":"127.0.0.1:54380","level":"debug","method":"GetDistributedQueries","took":"3.203875ms","ts":"2021-03-29T21:41:23.759653637Z","x_for_ip_addr":"x.x.x.x"}
2021-03-29T21:41:23.759901+00:00 REDACTED: {"component":"service","err":null,"ip_addr":"127.0.0.1:54380","level":"debug","method":"GetDistributedQueries","took":"3.203875ms","ts":"2021-03-29T21:41:23.759653637Z","x_for_ip_addr":"x.x.x.x"}`

However, as I watch the 400s come in before and after the 200s from the read endpoint, there are no corresponding entries in /var/log/messages for that client IP.  This leads me to believe that the 400s are coming from nginx and not Fleet.

**Comment by directionless** [comment]
FWIW I would expect osquery to _read_ query requests from `/api/v1/osquery/distributed/read`, but to send logs to a different URL. Possible `distributed/write` or possibly `logs`

**Comment by dachin11** [comment]
> FWIW I would expect osquery to _read_ query requests from `/api/v1/osquery/distributed/read`, but to send logs to a different URL. Possible `distributed/write` or possibly `logs`

Yes, we have `/api/v1/osquery/log` configured as --logger_tls_endpoint.

I do also see a distributed write setting
`--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write`

According to the docs the write endpoint is for distributed queries 

> The URI path which will be used, in conjunction with --tls_hostname, to create the remote URI for submitting the results of distributed queries when using the tls distributed plugin.

So it looks like there's osquery uses a different endpoint to submit results back to Fleet for distributed queries vs queries scheduled via packs.

**Comment by mike-myers-tob** [comment]
Supposedly, when nginx returns `400 (Bad Request)` it will log the reason into error log, at "info" level. If it's possible to log messages at "info" level, it would be interesting to know the reason there. There's a few other things that can be hidden by an HTTP 400 (malformed request syntax, size too large, invalid request message framing, or deceptive request routing).

**Comment by dachin11** [comment]
Yes, thanks @mike-myers-tob.  We are currently not getting any logs in our nginx error logs, so we are investigating that with urgency.

**Comment by dachin11** [comment]
Oh, thanks @Smjert for that update.  So then that would mean that the reason network utilization came back down to more typical levels was because the DBs all shrank to very small in size and osquery was no longer trying to send all of the old info.

**Comment by dachin11** [comment]
Just thought I'd share another update on this.  I was finally able to capture data in nginx error logs that corresponds to a 400 response to` /api/v1/osquery/log`.  As @mike-myers-tob points out, the 400s show up in the error logs at the `info` level.  In our case, our nginx config didn't specify a log level, so it defaulted to `error`.

Unfortunately, what I've captured doesn't necessarily support the theory that we were hitting the nginx's `client_max_body_size` limit, which we discussed a but during osquery office hours (someone in the meeting gave me a reference nginx config for Fleet where that setting was increased to 300M).  Additionally, it seems that the setting defaults to a relatively low # (1 MiB) and according to [nginx.org](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size), nginx would generate a 413 (Request Entry Too Large) error in this case. 

Our change to `info` logging was a bit later in the day and coupled with the fact that we are now getting _A LOT_ less 400s (down from 43% of requests to under 5%), I was only able to get one hit.  Here's what I see:

**The 400**
> { "timestamp": "2021-04-01T00:52:01+00:00","uri": "/api/v1/osquery/log","query_string": "","server_protocol": "HTTP/1.1","request_method": "POST","status": "400","body_bytes_sent": "0","http_user_agent": "osquery/4.4.0","gzip_ratio": "","http_x_forwarded_for": "","ssl_protocol": "TLSv1.2","ssl_cipher": "ECDHE-RSA-AES128-GCM-SHA256","realip_remote_addr": "x.x.29.7","upstream_cache_status": "","upstream_response_time": "","upstream_response_length": "","upstream_addr": "","request_time": "1.163" }

**The log entry in nginx error log**
> 2021/04/01 00:52:01 [info] 22156#22156: *156405 client prematurely closed connection, client: x.x.29.7, server: fleet-corp.nonprod.ppops.net, request: "POST /api/v1/osquery/log HTTP/1.1", host: "REDACTED"

Considering that our Fleet servers are only accessible to our laptops when users are on VPN, it's quite possible that someone actually closed their VPN or otherwise signed off for the day in mid POST.  It does seem very unlikely that the mass 400s were were receiving were all people disconnecting from VPN...but maybe network congestion was causing enough intermittent connectivity / packet loss issues that the client would eventually give up and close the connection.

I'll continue to look into errors tomorrow when we have more people connected to VPN and hopefully I'll have more errors to work with.

**Comment by directionless** [comment]
> > 2021/04/01 00:52:01 [info] 22156#22156: *156405 client prematurely closed connection, client: x.x.29.7, server: fleet-corp.nonprod.ppops.net, request: "POST /api/v1/osquery/log HTTP/1.1", host: "REDACTED"
> 
> Considering that our Fleet servers are only accessible to our laptops when users are on VPN, it's quite possible that someone actually closed their VPN or otherwise signed off for the day in mid POST. It does seem very unlikely that the mass 400s were were receiving were all people disconnecting from VPN...but maybe network congestion was causing enough intermittent connectivity / packet loss issues that the client would eventually give up and close the connection?

I think you've found a likely cause -- not people closing their laptops, but general network congestion / flakiness. It would be entirely unsurprising for a VPN to randomly drop large file transfers. And with the prior `logger_tls_max_lines` you're going see that cascading. 

I suspect your solution of lowering `logger_tls_max_lines` to have reliable transmit is an ideal solution. 

I'm going to close this -- I'm not sure there's to change on the osquery side. Feel free to keep commenting, or advocate for re-opening.

**Comment by dachin11** [comment]
Thanks @directionless, no issues with this being closed.  We are close - now looking at _client_body_buffer_size_ to keep nginx from buffering large client POSTs to disk since I noticed that our remaining 400s all seem to be proceeded by a warning that the `client request body is buffered to a temporary file`.

**Comment by dachin11** [comment]
Quick update for anyone following along / interested.

Turns out the the thing that helped us the most here (after short-circuiting everything by temporarily reducing `buffered_log_max`) was setting`logger_tls_compress` as true for our osquery clients (via Fleet).  Almost immediately after setting that our traffic patterns smoothed and our http 400 errors reduced to .1% or less, and things have been looking good for the last 1.5 weeks.  We've even kicked `buffered_log_max` back up to 200,000.

Considering http 400 errors are the result of _invalid client requests_, I'm still not sure how enabling compression fixed them.  Compressing the traffic would seem to indicate something about the request was too large, but considering that if a client message body size exceeded config limits, the http response code would be a 413.  Furthermore, enabling support for `large_client_header_buffers` and setting `ignore_invalid_headers` to 'ON', did not resolve anything.  It's still a bit of a mystery, but we are good for now.
