### ISSUE TITLE
libc++abi.dylib uncaught exceptions on osquery 4.5+

### ISSUE THREAD

**Issue by sophiesaunders** [osquery/osquery#7031]
# Bug report

### What operating system and version are you using?

```
 version = 10.12.6
   build = 16G29
platform = darwin
```

### What version of osquery are you using?

`version = 4.5.0`

### What steps did you take to reproduce the issue? What did you expect to see, what did you see instead? 

There are a handful of tables that trigger libc++abi.dylib exceptions unexpectedly. This doesn't happen with 4.4, but I can reproduce on my machine with 4.5, 4.6, and 4.7 osquery versions. 

Example 1:
```
mymac:~ myuser$ osqueryi --json "SELECT * FROM xprotect_reports"
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found
Abort trap: 6
```

Example 2:
```
mymac:~ myuser$ osqueryi --json "SELECT * FROM certificates"
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found
Abort trap: 6
```

The following osquery tables, when queried, all produce the same error:
```
account_policy_data
keychain_acls
keychain_items
launchd
sandboxes
startup_items
```

I don't know if something is wrong with my setup or if I'm using osquery incorrectly, please let me know if you think this isn't an osquery bug. I've also attached the osquery crash reports from /Library/Logs/DiagnosticReports in the zip file below:

[Archive.zip](https://github.com/osquery/osquery/files/6238876/Archive.zip)

**Comment by sharvilshah** [comment]
Hey @ssophie1 

Took a quick and cursory look at the attached crash log -- 

```
Process:               osqueryi [2451]
Path:                  /private/tmp/*/osqueryi
Identifier:            osqueryi
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        cpython [960]
Responsible:           osqueryi [2451]
User ID:               0

Date/Time:             2021-03-31 12:35:23.343 -0400
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        B8ACC950-A0E7-F10E-3DDD-6A8FF7D35D5E


Time Awake Since Boot: 73000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

External Modification Warnings:
Process used task_for_pid().
```

It seems that `osqueryi` is run under debugger/disassembler? Is this the case? 
The parent process seems to be `cpython` and it also shows an `external modification warning: process used task_for_pid()`

Is this executable built from source? Or is it from a `.pkg` installer?

**Comment by ssophie1** [comment]
Hi @sharvilshah,

I seem to get the same results with both types of setups -- here are the two ways I've been running queries and seeing the results above:

1. Use the osquery built from source, contained in another application. This is tested with an automated Python script, which is why you're seeing the parent process cpython.
2. Download the osquery .pkg (I tried 4.5, 4.6, and 4.7) from Github and run queries directly on the endpoint using this binary.

I get the exact same error output with method 2, but it doesn't generate a crash file.

**Comment by mike-myers-tob** [comment]
Doesn't happen on my macOS 10.12.6 VM with the release version of osquery 4.7:

```
tests-Mac:~ test$ osqueryi --version
osqueryi version 4.7.0
tests-Mac:~ test$ system_profiler SPSoftwareDataType
Software:
 
    System Software Overview:
 
      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: test’s Mac
      User Name: test (test)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 10 minutes
 
tests-Mac:~ test$ osqueryi --json "SELECT * from xprotect_reports"
[
 
]
tests-Mac:~ test$ osqueryi --json "SELECT * from startup_items"
[
 
]
tests-Mac:~ test$ osqueryi --json "SELECT * from sandboxes"
...
(valid output)
```

**Comment by mike-myers-tob** [comment]
- Is there any osquery config file on the system, prior to testing? (check `/private/var/osquery/`)
- Could there be Unicode characters in the paths on the system, or the contents of the files it is checking? 
- Can you run osquery with the `--verbose` flag?
- Can you build with debug symbols so the stack trace will show up in the crash log?

**Comment by theopolis** [comment]
@ssophie1, I can see how this bug might occur in those tables you mentioned. However, in versions 4.5.1 and greater we added https://github.com/osquery/osquery/pull/6689 to handle these broad exceptions.

I am curious if you can run:

```
osqueryi --version
```

And check that the version is something more recent that 4.5.1.

**Comment by ssophie1** [comment]
@theopolis @mike-myers-tob I will work on getting the stack trace later this week. 

There are no osquery config files on the system prior to install, but they do exist post-install (from a pkg). Is that expected? 

Here is the verbose output of the `certificates` command:

```
macos10126:~ mymac$ which osqueryi
/usr/local/bin/osqueryi
macos10126:~ mymac$ osqueryi --version
osqueryi version 4.7.0
macos10126:~ mymac$ osqueryi --verbose --json "SELECT * FROM xprotect_reports"
I0420 17:27:52.122555 3666363328 init.cpp:342] osquery initialized [version=4.7.0]
I0420 17:27:52.122715 3666363328 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: /var/osquery/extensions.load
I0420 17:27:52.123482 3666363328 init.cpp:553] An error occurred during extension manager startup: Extensions disabled
I0420 17:27:52.123518 3666363328 auto_constructed_tables.cpp:97] Removing stale ATC entries
I0420 17:27:52.127010 3666363328 init.cpp:591] Error reading config: config file does not exist: /var/osquery/osquery.conf
E0420 17:27:52.270445 3666363328 virtual_table.cpp:1006] Exception while executing table xprotect_reports: map::at:  key not found
[

]
Error: map::at:  key not found
I0420 17:27:52.271041 3666363328 dispatcher.cpp:149] Thread: 0x7fffda8843c0 requesting a stop
I0420 17:27:52.271054 3666363328 dispatcher.cpp:122] Thread: 0x7fffda8843c0 requesting a join
I0420 17:27:52.271057 3666363328 dispatcher.cpp:144] Services and threads have been cleared
```

And the contents of `/private/var/osquery` immediately after installing osquery:

```
macos10126:~ mymac$ ls /private/var/osquery
certs				lenses
com.facebook.osqueryd.conf	osquery.example.conf
com.facebook.osqueryd.plist	packs
```

If you aren't seeing this on the same OS with the same osquery version, it seems like user error, but if you could point me in the right direction I would appreciate it.

**Comment by Smjert** [comment]
I suspect this issue is the same as the one fixed here: https://github.com/osquery/osquery/pull/7705

The `xprotect_reports` table attempts to access a user home directory by directly accessing the `directory` column in the results of the query to the user table.
Some users don't have a home directory and so the row in the results might not contain the `directory` column, causing an invalid access.

The `certificates` table seems to have automatically inherited the fix, because it was using the `getHomeDirectories` API already.

**Comment by Smjert** [comment]
I'm going to close this issue since no one else has reported it again after the fix.
Feel free to open a new issue if this becomes a problem again.
