### ISSUE TITLE
Update RockDB with the current host UUID when osqueryd start

### ISSUE THREAD

**Issue by asterisk800** [osquery/osquery#7038]
# Feature request
When VMs are created from an image that has osquery already installed on it, the RocksDB of the provisioned VMs ends up having the host UUID of the VM that was used to create the VM image.

### What new feature do you want?
When the osqueryd daemon starts, having a step to update its host UUID will guaranty the VMs have the correct host UUID all the time. 

Here is an example issue:  https://github.com/fleetdm/fleet/issues/577

### How is this new feature useful?

Having this feature will prevent VMs provisioned from an image that has osquery installed from having identical host UUID in RocksDB. 

### How can this be implemented?

I believe adding a step to update the host UUID in the startDaemon will be able to address this issue.

**Comment by theopolis** [comment]
We could introduce a new value for `--host_identifier`. If you are using `--host_identifier=uuid`, we could introduce a `--host_identifier=uuid_mutable` and if this is used osquery always inspects the actual UUID. If the UUID cannot be retrieved from hardware (or the emulated hardware) then an ephemeral UUID will be selected.

**Comment by directionless** [comment]
To be honest, I'm not sure what I think. Adding mutability here feels like a can of worms. Especially with TLS server enrollments. 

My normal advice would be to make the VM images _without_ an osquery DB and let it be created on startup. Does that pattern work here?

**Comment by np5** [comment]
There are already multiple steps (delete ssh host keys, delete machine ID, remove logs, tmp files, …) that have to be done when preparing images. Why not delete the osquery DB folder too?

**Comment by directionless** [comment]
I'm going to close this. Feel free to speak up if you think otherwise.
