### ISSUE TITLE
Exception at gentable.py when building osquery with homemade table

### ISSUE THREAD

**Issue by Royabra** [osquery/osquery#7041]
Hey all,

I'm trying to create a new table for osquery and i keep having the same exception when building (table name is thread_memory_map and is only on windows for now).

The table itself retrieves the [memory basic information](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-memory_basic_information) struct for each thread in memory, which would allow detection of injected threads in memory.

 Here is the exception i get:
![build_fail](https://user-images.githubusercontent.com/78696440/113513527-deb2c400-9572-11eb-9c97-d8e51b55413b.PNG)
I followed the guide to [building](https://osquery.readthedocs.io/en/stable/development/building/) and [creating new tables](https://osquery.readthedocs.io/en/stable/development/creating-tables/)
Here are my source files
[build-failing.zip](https://github.com/osquery/osquery/files/6254858/build-failing.zip)

Did anyone encounter this problem before or knows how to fix it?

**Comment by Smjert** [comment]
Hello @Royabra, the gentable.py script is the one that generates the tables C++ code starting from the specs files (.table); if you check the Traceback you can see that the error is on `examples([` and is an IndentationError, which means that there is a space/tab where there shouldn't be one (most likely at the start) on that line in you spec file.

**Comment by Royabra** [comment]
Hey @Smjert, thank you for the answer, however I keep having the same problem even after trying your fix, care to take a look at my specs file? 
It is in the zip file I uploaded in the issue
The actual line in the specs file for the my .TABLE is 279

**Comment by Smjert** [comment]
> Hey @Smjert, thank you for the answer, however I keep having the same problem even after trying your fix, care to take a look at my specs file?
> 
> It is in the zip file I uploaded in the issue
> The actual line in the specs file for my .TABLE is 279
> (Rest of the specs file wasn't changed and cloned straight from the osquery repository)

I checked, it's because the whole examples block is indented, you need to remove one indent so that the `examples([` and closing `])` have no prefix spaces and the queries have 4 spaces indent.
Also the description of the table must end with a period.

**Comment by Royabra** [comment]
Hey @Smjert, it's working now, thank you for your time and patience.
