### ISSUE TITLE
Windows_events not being logged

### ISSUE THREAD

**Issue by Jimjazzz** [osquery/osquery#7045]
# Bug report

### What operating system and version are you using?

Windows Server 2019 VM
Windows 10.0.19041

### What version of osquery are you using?
4.7.0

### What steps did you take to reproduce the issue?
Configure a pack to gather windows events, in my case, the pack runs every 60 seconds and runs three queries:
```
    SELECT *, "events_windows." || lower(source) || "." || eventid as __devoSubTag FROM windows_events WHERE source IN ('Application', 'Setup', 'Security', 'System');
    SELECT *, "events_windows.powershell" || "." || eventid as __devoSubTag FROM windows_events WHERE source IN ('Microsoft-Windows-PowerShell/Operational', 'Microsoft-Windows-PowerShell/Admin');
    SELECT *, "events_windows.other_sources" || "." || eventid as __devoSubTag FROM windows_events WHERE source Not IN ('Application', 'Setup', 'Security', 'System', 'Microsoft-Windows-PowerShell/Operational', 'Microsoft-Windows-PowerShell/Admin');
```
Relevant configuration flags:

```
--disable_events=false
--enable_windows_events_subscriber=true
--enable_windows_events_publisher=true
--enable_powershell_events_subscriber=true


events_expiry: 1
events_max: 500000
windows_event_channels: System,Application,Setup,Security,Microsoft-Windows-PowerShell/Operational,ForwardedEvents

```

Procedure:

1. Generate some events (i.e SSH to the windows VM) 
2. Check in the event viewer that the event has been created in the Event Viewer (i.e: when loggin via SSH, i get a 4624 event)
3. Allow some time to the pack to be executed.

### What did you expect to see?
Windows events are queried and logged. 

I tipically use a TLS endpoint but as it was not working, changed the logger to filesystem. It did not change the behavior.

### What did you see instead?
Almost all the events are not logged.

### Other info
After starting osquery i seem to be getting events in the first iterations of the pack. Then it stops and no events are logged. Sometimes i get very few events, but i was not able to identify any pattern or why it would happen only sometimes. Most part of the time, i do not get any event.

The same setup was working properly with osquery 4.6.0.

**Comment by manurautela** [comment]
I tried to see if events are being pushed or not via **windows_events** with a local setup  via filesystem logger (without tls).

```
{
    "packs" : {
        "test_windows_events" : {
            "queries": {
                "windows_events_packs" : {
                    "query" : "select * from windows_events",
                        "interval": 15,
                        "description": "windows_events"
                }
            }
        }
    }
}
```

This is the relevant config  I used for events and logging.

```
# Windows events
--enable_windows_events_publisher=true
--enable_windows_events_subscriber=true
--windows_event_channels=Security,System,Application,Setup,Microsoft-Windows-PowerShell/Operational,Microsoft-Windows-Sysmon/Operational
--enable_powershell_events_subscriber=true

--logger_plugin=filesystem

--schedule_default_interval=15
--pack_refresh_interval=15

```

Running it locally in daemon mode and checking **osqueryd.results.log**. I do notice events getting pushed as in when launching programs, that should generate in their respective channels. The pack refresh interval I had set very low as 15 seconds to speed up.

Tried with one of the queries syntax in the query pack and that seems to work similarly.

```
{
    "packs" : {
        "test_windows_events" : {
            "queries": {
                "windows_events_packs" : {
                    "query" : "SELECT *, 'events_windows.powershell' || '.' || eventid as __devoSubTag FROM windows_events WHERE source IN ('Microsoft-Windows-PowerShell/Operational', 'Microsoft-Windows-PowerShell/Admin');",
                    "interval": 15,
                    "description": "windows_events"
                }

            }
        }
    }
}
```


Here is the output from the log.

```
tail -f log\osqueryd.results.log
{"name":"pack_test_windows_events_windows_events_packs","hostIdentifier":"test","calendarTime":"Wed
Apr  7 07:05:31 2021
UTC","unixTime":1617779131,"epoch":0,"counter":0,"numerics":false,"columns":{"__devoSubTag":"events_windows.powershell.40961","computer_name":"test","data":"{\"EventData\":\"\"}","datetime":"2021-04-07T07:05:23.0538070Z","eventid":"40961","keywords":"0x0","level":"4","provider_guid":"{a0c1853b-5c40-4b15-8766-3cf1c58f985a}","provider_name":"Microsoft-Windows-PowerShell","source":"Microsoft-Windows-PowerShell/Operational","task":"4","time":"1617779127"},"action":"added"}
{"name":"pack_test_windows_events_windows_events_packs","hostIdentifier":"test","calendarTime":"Wed
Apr  7 07:05:46 2021
UTC","unixTime":1617779146,"epoch":0,"counter":0,"numerics":false,"columns":{"__devoSubTag":"events_windows.powershell.53504","computer_name":"test","data":"{\"EventData\":{\"param1\":\"1892\",\"param2\":\"DefaultAppDomain\"}}","datetime":"2021-04-07T07:05:23.2361172Z","eventid":"53504","keywords":"0x0","level":"4","provider_guid":"{a0c1853b-5c40-4b15-8766-3cf1c58f985a}","provider_name":"Microsoft-Windows-PowerShell","source":"Microsoft-Windows-PowerShell/Operational","task":"111","time":"1617779132"},"action":"added"}
<snip...>
```

**Comment by Jimjazzz** [comment]
[logs.zip](https://github.com/osquery/osquery/files/6279286/logs.zip)

![application](https://user-images.githubusercontent.com/73331488/114042444-bafac100-9885-11eb-8209-f0bb767ad446.JPG)

![security](https://user-images.githubusercontent.com/73331488/114042649-e67dab80-9885-11eb-8a47-2ac34af6f5da.JPG)

Attaching logs and output files, also the screenshot of Application and Security events in the windows box. Despite having plenty of events going on, only one was returned. In the verbose log i can see the pack has been executed many times, but in osqueryd results i only have 1 result.

If somebody knows any way to debug this i'd like to give it a try.

**Comment by Jimjazzz** [comment]
Doing some more tests, it seems that setting the flag event_optimize to false solves the issue. I am going to do some more robust testing to confirm, but i am assuming this should not be the expected behavior?

**Comment by theopolis** [comment]
This shouldn't but I think I see the bug in the code.

**Comment by manurautela** [comment]
Not really sure, but even with or without events_optimize set. I seem to be receiving the events. Not hitting these issues on my side.

**Comment by theopolis** [comment]
Here is the code I am looking at: https://github.com/osquery/osquery/blob/master/osquery/events/eventsubscriberplugin.cpp#L234

My hypothesis is the optimization logic is being applied to the time between configuration updates, and instead it should be dynamically calculating the max delta between scheduled queries targeting subscribers. 

This bug would show up if you have multiple scheduled queries using the same `*_events` table. I'll try to come up with a test case later tonight. I want to see if there's missing coverage for the existing test: https://github.com/osquery/osquery/blob/master/osquery/events/tests/eventsubscriberplugin.cpp#L62

**Comment by theopolis** [comment]
^ I tested my hypothesis and I've change my mind, I don't see a bug with `--events_optimize`. And thus my observation is in line with @manurautela's. I am still looking for possible issues.

**Comment by Jimjazzz** [comment]
Adding some more info as talked in slack:

- I have started a osquery instance with a single pack, with the same 3 queries in the description, the pack is scheduled to run every 60 seconds.
- The osqeury instance started at 17:50:05
- Created several test events using `eventcreate /t ERROR /id 335 /l Application /d "TEST EVENTx"` at: 17:51:40, 17:51:43, 17:51:46, 17:51:48, 17:51:50, 17:51:53 
- Events are visible in Windows Event Viewer (attached screenshot)
- osqueryd.results.log is empty at 17:53:00
- Created several test events at 17:53:55, 17:53:57, 17:54:00, 17:54:02
- osqueryd.results.log is empty at 17:58:00
- Some other security events came in at 17:58:30 and 18:05:53 and are visible in event viewer
- osqueryd.results.log is empty at 18:08:00
- stopped osquery

In this case, no events were logged at all, osqueryd.results.log was created but it is always empty.

Verbose log:
[osqueryd.INFO.20210412-175005.zip](https://github.com/osquery/osquery/files/6298195/osqueryd.INFO.20210412-175005.zip)

Application events:
![image](https://user-images.githubusercontent.com/73331488/114426711-a0448700-9bba-11eb-8d7b-0b6a41b33e4c.png)

Security events:
![image](https://user-images.githubusercontent.com/73331488/114426822-bce0bf00-9bba-11eb-9f21-020b9ce0ed11.png)

**Comment by theopolis** [comment]
This should be fixed with https://github.com/osquery/osquery/pull/7055

**Comment by theopolis** [comment]
Thanks again for reporting and helping debug this!
