### ISSUE TITLE
Create a Security Assurance guide for osquery

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7047]
# Task

Create a Security Assurance guide for osquery. This will increment us a bit closer to the Silver badge for the CII. we can keep it in our top-level SECURITY.md file.

Ref.:

- https://github.com/osquery/foundation/issues/17
- https://bestpractices.coreinfrastructure.org/en/projects/3125

Example, although more detail than I expect us to need in our first attempt: https://github.com/coreinfrastructure/best-practices-badge/blob/main/doc/security.md

**Comment by directionless** [comment]
Looking at other examples...

curl:
* https://curl.se/libcurl/security.html
* https://curl.se/dev/secprocess.html

commonmark:
* https://commonmark.thephpleague.com/1.5/security/

thanos (a prometheus storage backend)
* https://thanos.io/security/ (This is a 404)
