### ISSUE TITLE
[Virtual Tables] Failed to read rpm packages from SUSE Linux.

### ISSUE THREAD

**Issue by VENKAT64** [osquery/osquery#7065]
Hello Team, 

"rpm_package" and "rpm_package_files" tables are returns with empty in SUSE 12/15.
Please help me, why rpm query is failing in SUSE Linux.

Appreciate for the swift responses.

**Comment by theopolis** [comment]
Can you please fill out the entire bug report issue template? It is difficult to help if we do not know basic information about your environment, for example what version of osquery are you using?

**Comment by theopolis** [comment]
Thanks!

Is there anything interesting reporting when you try:

```
sudo osqueryi --verbose -A rpm_packages
```

Do you mind pasting me any status messages outputed?

**Comment by theopolis** [comment]
I tested with OpenSUSE 12 and found that the table is working.

```
osquery> select * from os_version;
+------+---------+-------+-------+-------+-------+----------+---------------+----------+--------+
| name | version | major | minor | patch | build | platform | platform_like | codename | arch   |
+------+---------+-------+-------+-------+-------+----------+---------------+----------+--------+
| SLES | 12-SP3  | 12    | 3     | 0     |       | sles     |               |          | x86_64 |
+------+---------+-------+-------+-------+-------+----------+---------------+----------+--------+
osquery> select count(1) from rpm_packages;
+----------+
| count(1) |
+----------+
| 620      |
+----------+
```

**Comment by VENKAT64** [comment]
> select count(1) from rpm_packages;

Thanks for sharing the clear and detailed Information.

Got the rpm_packages query results on running osquery with Administrator privileges and no issue observed in OpenSUSE 12 now.
but the problem still exists in OpenSUSE 15 and requested information shared below, please refer 

![image](https://user-images.githubusercontent.com/32767883/115356337-2e32fa00-a1d9-11eb-8a75-83fc4820736e.png)

![image](https://user-images.githubusercontent.com/32767883/115356796-a1d50700-a1d9-11eb-9658-7f4a753543b3.png)

"**sudo ./osqueryi --verbose -A rpm_packages**" command output for both SUSE 12 and 15 attached as text doc's.

SUSE12 Output:
      [rpmPackages-SUSE12.txt](https://github.com/osquery/osquery/files/6341535/rpmPackages-SUSE12.txt)

SUSE15 Output:
      [rpmPackages-SUSE15.txt](https://github.com/osquery/osquery/files/6341536/rpmPackages-SUSE15.txt)

**Comment by theopolis** [comment]
I am still unable to reproduce the error:

```
vagrant@opensuse15:~> ./osqueryd  -S
Using a virtual database. Need help, type '.help'
osquery> select * from os_version;
+---------------+---------+-------+-------+-------+-------+---------------+---------------+----------+--------+
| name          | version | major | minor | patch | build | platform      | platform_like | codename | arch   |
+---------------+---------+-------+-------+-------+-------+---------------+---------------+----------+--------+
| openSUSE Leap | 15.2    | 15    | 2     | 0     |       | opensuse-leap | suse opensuse |          | x86_64 |
+---------------+---------+-------+-------+-------+-------+---------------+---------------+----------+--------+
osquery> select count(1) from rpm_packages;
+----------+
| count(1) |
+----------+
| 580      |
+----------+
osquery> 
```

**Comment by theopolis** [comment]
Let me know if this is still an issue and we can work more on reproducing it.
