### ISSUE TITLE
chrome_extensions not reporting identifier for unreferenced extensions

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7093]
# Bug report

Since the `chrome_extensions` refactor in https://github.com/osquery/osquery/pull/6780 the the table has stopped returning the `identifier` for unreferenced extensions.

I think this is because the identifier is pulled from the profile config, and not from the extension itself. But I think this represents a bug. @alessandrogario thoughts?

### What operating system and version are you using?

macOS
Google Chrome

### What steps did you take to reproduce the issue?

```
dover:k2 seph$ osqueryd -S "select identifier, state, referenced, path from chrome_extensions where path like '%ghbmnnjooekpmoecnnnilnnbdlolhkhi%'"
+----------------------------------+-------+------------+-----------------------------------------------------------------------------------------------------------------------+
| identifier                       | state | referenced | path                                                                                                                  |
+----------------------------------+-------+------------+-----------------------------------------------------------------------------------------------------------------------+
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Default/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0    |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 1/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
|                                  |       | 0          | /Users/seph/Library/Application Support/Google/Chrome/Profile 10/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.13.0_0 |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 10/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.14.0_0 |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 2/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_11 |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 3/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 4/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 5/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 8/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.21.0_0  |
| ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 9/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.9_0     |
+----------------------------------+-------+------------+-----------------------------------------------------------------------------------------------------------------------+
```

**Comment by alessandrogario** [comment]
> # Bug report
> Since the `chrome_extensions` refactor in #6780 the the table has stopped returning the `identifier` for unreferenced extensions.
> 
> I think this is because the identifier is pulled from the profile config, and not from the extension itself. But I think this represents a bug. @alessandrogario thoughts?
> 
> ### What operating system and version are you using?
> macOS
> Google Chrome
> 
> ### What steps did you take to reproduce the issue?
> ```
> dover:k2 seph$ osqueryd -S "select identifier, state, referenced, path from chrome_extensions where path like '%ghbmnnjooekpmoecnnnilnnbdlolhkhi%'"
> +----------------------------------+-------+------------+-----------------------------------------------------------------------------------------------------------------------+
> | identifier                       | state | referenced | path                                                                                                                  |
> +----------------------------------+-------+------------+-----------------------------------------------------------------------------------------------------------------------+
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Default/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0    |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 1/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
> |                                  |       | 0          | /Users/seph/Library/Application Support/Google/Chrome/Profile 10/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.13.0_0 |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 10/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.14.0_0 |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 2/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_11 |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 3/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 4/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 5/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.28.0_0  |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 8/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.21.0_0  |
> | ghbmnnjooekpmoecnnnilnnbdlolhkhi | 1     | 1          | /Users/seph/Library/Application Support/Google/Chrome/Profile 9/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.9_0     |
> +----------------------------------+-------+------------+-----------------------------------------------------------------------------------------------------------------------+
> ```

The `identifier` column is left empty on purpose in the case the extension is not registered. The `Manifest.json` file used by extensions do not have a field we can use to determine this information.

The `Preferences` (or `Secure Preferences`) file is the only place where the identifier can be extracted correctly. Extensions are often located within a path that happens to match `identifier/version` but that is not always the case (i.e.: system-wide extensions, custom extensions installed by the user) so this assumption is no longer applied to the results. I believe this was just a side-effect of how extensions were (wrongly) enumerated pre-refactor.

**Comment by directionless** [comment]
I'm not sure I understand yet... So prior to #6780, osquery extracted the `identifier` from the path. But, you believe that to be incorrect -- there are examples where the path does not contain the `identifier`.

If this is correct, it was probably a breaking change and we should have noted it better in the changelog. Ah well. We should also update https://github.com/osquery/osquery/blob/d2be385d71f401c85872f00d479df8f499164c5a/specs/chrome_extensions.table#L9

I also think we're in a bit of a weird place... The only stable identifier for chrome extensions (for malware, or really any analysis) comes from that identifier. So we're now reporting a potentially malicious artifact on disk, with no way to cross check it.

What does it mean for an extension to not be referenced? Is it just dead code? Will chrome ever reference it, and make it live?

**Comment by directionless** [comment]
Ah ha. We _can_ calculate the identifier from the manifest.json

* https://stackoverflow.com/questions/16993486/how-to-programmatically-calculate-chrome-extension-id
* https://github.com/Constellation/crxmake
* http://web.archive.org/web/20120606044635/http://supercollider.dk/2010/01/calculating-chrome-extension-id-from-your-private-key-233

**Comment by arubdesu** [comment]
I'm noticing this in things like differential queries, glad it's already being tracked, I misinterpreted this as mid-upgrade or something. It would be backflips for me to filter out e.g. the bevy of extensions Google ships with Chrome AND ALSO filter out the path containing the identifier or something, or fly closer to the sun by excluding nulls and potentially getting burned by sideloaded stuffs (we allow developer mode, as I'm assuming a lot of shops do).
