### ISSUE TITLE
osqueryd crashes occasionally

### ISSUE THREAD

**Issue by alameenshah** [osquery/osquery#7098]
# Bug report

### What operating system and version are you using?
macOS 11.3.1 (20E241)

### osqueryi --line "SELECT version, build, platform from os_version;"
version = 11.3
build = 20E232
platform = darwin

### What version of osquery are you using?
4.7.0

### What steps did you take to reproduce the issue?
1. Create a custom osquery extension. In my case the extension has a table, config and logger plugins.
2. Launch osqueryd from the custom extension process. This is the command I use for launching - 
`/usr/local/bin/osqueryd --extensions_socket="/private/var/tmp/osquery/cst_ext_osquery.em" --extensions_require=cst_ext_osquery --extensions_timeout=60 --extensions_interval=10 --pidfile="/private/var/tmp/osquery/osquery.pidfile" --database_path="/private/var/tmp/osquery/db" --config_plugin=cst_ext_config --config_refresh=30 --config_check=false --logger_plugin=cst_ext_logger --logger_path="/private/var/tmp/osquery" --disable_watchdog=true --disable_distributed=true --disable_events=true --disable_audit=true --allow_unsafe --D`
3. Keep the custom osquery extension running for a day or more.

### What did you expect to see?
osqueryd keeps running.

### What did you see instead?
osqueryd crashes.

[osqueryd_2021-05-06-142346_tests-MacBook-Pro.txt](https://github.com/osquery/osquery/files/6455572/osqueryd_2021-05-06-142346_tests-MacBook-Pro.txt)

[osqueryd_2021-05-05-164047_tests-MacBook-Pro.txt](https://github.com/osquery/osquery/files/6455573/osqueryd_2021-05-05-164047_tests-MacBook-Pro.txt)

**Comment by theopolis** [comment]
It looks like the `osqueryd` that is crashing is located at `/Library/Application Support/VMware/*/osqueryd`. This is crashing because it is hitting and uncaught exception. I can fix this specific instance but the newer osquery versions > 4.5 should not have this issue.

Can you let me know the version installed at:

```
/Library/Application Support/VMware/*/osqueryd --version
```

**Comment by alameenshah** [comment]
> It looks like the `osqueryd` that is crashing is located at `/Library/Application Support/VMware/*/osqueryd`. This is crashing because it is hitting and uncaught exception. I can fix this specific instance but the newer osquery versions > 4.5 should not have this issue.
> 
> Can you let me know the version installed at:
> 
> ```
> /Library/Application Support/VMware/*/osqueryd --version
> ```

ok... I'll update you with the version info soon.

**Comment by alameenshah** [comment]
Update - I was using the old osquery version - 

`/Library/Application Support/VMware/*/osqueryd --version =>
osqueryd version 4.4.0-44-gc6370989-dirty`. 

Have updated it to 4.8. Will let you know if the issue is reproducible with the new version.

**Comment by theopolis** [comment]
Thanks for verifying. Please re-open this issue if you are able to reproduce the crash.
