### ISSUE TITLE
A submodule with GPL licensing

### ISSUE THREAD

**Issue by alameenshah** [osquery/osquery#7101]
The submodule _smartmontools_ used in Osquery is GPL licensed - https://github.com/osquery/third-party-smartmontools.

Wouldn't this be an issue for proprietary software distributions that include osqueryd? Is this intentional or is there an alternate option?

**Comment by theopolis** [comment]
The smartmontools library is licensed GPL 2.0+ thus it is compatible with osquery's license of Apache 2.0 or GPL 2.0. Please see our https://github.com/osquery/osquery/blob/master/LICENSE file.

Is your question about how you may use osquery based on osquery's license?

**Comment by alameenshah** [comment]
> The smartmontools library is licensed GPL 2.0+ thus it is compatible with osquery's license of Apache 2.0 or GPL 2.0. Please see our https://github.com/osquery/osquery/blob/master/LICENSE file.
> 
> Is your question about how you may use osquery based on osquery's license?

Because of the GPL 2 in smartmontools - I was wondering if it would still be legal to include osqueryd in a commercial closed-source software distribution.

**Comment by theopolis** [comment]
I would recommend discussing it with an open source lawyer if you're in this situation of distributing osquery within a product. I think that's the best way to get the most accurate answer.

osquery is built to be used as a binary and distributing it that way works well both from a technical perspective and legal. If a product bundles and distributes osquery as-is then it should reference osquery's GitHub as a method for users of the product to obtain the source and build instructions. If the product makes changes to osquery then those patches/sources need to be distributed along with the product, this is a requirement for either of osquery's licenses, as well as multiple third party libraries used by osquery. Those sources also need the custom build instructions.

In rare cases, if a product instead changes osquery's build to link to it statically/dynamically or create a derivative work, then that product would be required to be distributed with a GPL 2.0+ or compatible license.

Also, keep in mind that osquery uses many dependencies and several of they are licensed as GPL 2.0+.

**Comment by alameenshah** [comment]
Makes sense - Thank you for the detailed response!
