### ISSUE TITLE
Homebrew package list empty on Apple Silicon

### ISSUE THREAD

**Issue by jkish2** [osquery/osquery#7108]
# Bug report

### What operating system and version are you using?

macOS Big Sur 11.3.1 (Apple Silicon)

### What version of osquery are you using?

osquery 4.7.0

### What steps did you take to reproduce the issue?

`SELECT * FROM homebrew_packages;`

### What did you expect to see?

A list of installed homebrew packages.

### What did you see instead?

An empty list.

I suspect this is because the install location of homebrew has changed for systems running Apple Silicon.

**Intel**
`/usr/local/bin/brew`

**Apple Silicon**
`/opt/homebrew/bin/brew`

--

**Source Link**:
https://github.com/osquery/osquery/blob/master/osquery/tables/system/darwin/homebrew_packages.cpp

**Comment by directionless** [comment]
This looks like a bug, as the original poster reports.

I also notice that `genHomebrewPackages` does not take any constraints, so there is no way to point this to a different install directory. I think, ideally, osquery should (a) accept a hidden column specifying where homebrew is installed (b) look in both the default `/opt/homebrew` and `/usr/local` locations.
