### ISSUE TITLE
Update the YARA docs to explain recent functionality changes

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7110]
The YARA docs at https://osquery.readthedocs.io/en/stable/deployment/yara are quite out of date.

1. They reference `pattern` which has long since been replaced by `LIKE` on path
2. They're missing `sigrule`
3. They're missing `sigurl`

**Comment by nmeocisco** [comment]
I just noticed that the `yara` table is available on Windows, but the documentation says it is only for MacOS and Linux.

**Comment by directionless** [comment]
> I just noticed that the `yara` table is available on Windows, but the documentation says it is only for MacOS and Linux.
> https://osquery.io/schema/4.8.0/#yara

This was fixed in a recent change to the website generation tools. The 4.9.0 release should reflect that
