### ISSUE TITLE
osquery can register duplicate extension uuids

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#7118]
# Bug report

I've seen a few times when using the ```--extensions_require``` flag that osquery manages to register two extensions with the same uuid. I can see in the osquery output: 

```
I0521 12:33:57.419342  3556 interface.cpp:120] Registering extension (123, 16920, version=3.3.0.241, sdk=)
I0521 12:33:57.419342  7392 interface.cpp:120] Registering extension (abc, 16920, version=2.2.0.10, sdk=)
```

We can see in[ interface.cpp](https://github.com/osquery/osquery/blob/880f367f8616d85dfef4448a47f310097314d7e6/osquery/extensions/interface.cpp#L110) that there is no lock around assigning an extension uuid and as result there is potential for a collision.

As we've already had to move the read/write mutexes around to prevent deadlocks (https://github.com/osquery/osquery/issues/6744). The easiest solution (without a larger refactor of the extensions logic) would be to create a thread safe class that would generate the uuids.

### What version of osquery are you using?
```
osquery.exe --line "SELECT version from osquery_info;"
version = 4.7.0
```

**Comment by theopolis** [comment]
Thanks for the report @Breakwell, is this something you are working on a fix for?

**Comment by Breakwell** [comment]
@theopolis I have raised a PR
