### ISSUE TITLE
how can I compile osquery for Red Hat on ppc64le

### ISSUE THREAD

**Issue by milind69** [osquery/osquery#7122]
How can I compile or get rpm for Red Hat ppc64le architecture

### How is this new feature useful?
Red Hat on ppc64le is becoming popular os due to high memory support, apps such as SAP using it now. 

### How can this be implemented?

Provide rpm or build instructions or support to build issues 
I can try build it , but facing some issues building osquery toolchain
If you can help debug i can try build

**Comment by theopolis** [comment]
You will need to start with rebuilding the osquery-toolchain with this architecture support, so resolving your issue here is the first step: https://github.com/osquery/osquery-toolchain/issues/24.

I am not aware of any plans to enable this support. If there is considerable requests for the feature we can try to advocate for it.

**Comment by milind69** [comment]
Hi @theopolis 
I think i was able to compile the toolchain , and now i am trying to compile osquery but I get error below ,i had modified TARGET_PROCESSOR=ppc64le in global option for cmake ,but looks like it can not find ppc64le directory structure 

I would appreciate any guidelines

dciunix@cmcbvpdc9lpr50 build]$ cmake -DOSQUERY_TOOLCHAIN_SYSROOT=/home/u347729/opt/osquery-toolchain/final/sysroot/ ..
-- Not found: ccache. Install it and put it into the PATH if you want to speed up partial builds.
-- osquery version: 4.8.0-32-g3607f9d9-dirty
-- Found clang-format: /home/u347729/opt/osquery-toolchain/final/sysroot/usr/bin/clang-format
-- Build type: RelWithDebInfo
-- Shared libraries: OFF
-- Importing: source/augeas
-- Importing: source/augeas/gnulib
-- Importing: source/boost
-- Importing: source/bzip2
-- Importing: source/gflags
-- Importing: source/glog
-- Importing: source/googletest
-- Importing: source/libarchive
-- Importing: source/libaudit
-- Importing: source/libcryptsetup
-- Importing: source/libdevmapper
-- Importing: source/libelfin
-- Importing: source/libgcrypt
-- Importing: source/libgpg-error
-- Importing: source/libiptables
-- Importing: source/libmagic
-- Importing: source/librdkafka
-- Importing: source/librpm
-- Importing: source/libudev
-- Importing: source/libxml2
-- Importing: source/linenoise-ng
-- Importing: source/lldpd
-- Importing: source/lzma
-- Importing: source/popt
-- Importing: source/rapidjson
-- Importing: source/rocksdb
-- Importing: source/sleuthkit
-- Importing: source/smartmontools
-- Importing: source/sqlite
-- Disabling the SQLite R*Tree module
-- Disabling the SQLite FTS extensions
-- Importing: source/ssdeep-cpp
-- Importing: source/thrift
-- Importing: source/util-linux
-- Importing: source/yara
-- Importing: source/zlib
-- Importing: source/zstd
-- Importing formula: formula/openssl
-- Importing: source/icu
-- Importing: source/expat
-- Importing: source/dbus
-- Importing: source/libcap
-- cppcheck: Enabled with /usr/bin/cppcheck
-- Configuring done
CMake Error at libraries/cmake/source/libgcrypt/CMakeLists.txt:12 (add_library):
  Cannot find source file:

    /home/dciunix/toolchain/osquery/libraries/cmake/source/libgcrypt/generated/ppc64le/mpi/mpih-lshift.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  libraries/cmake/source/libgcrypt/CMakeLists.txt:247 (libgcryptMain)


CMake Error at libraries/cmake/source/libgcrypt/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: thirdparty_libgcrypt
Call Stack (most recent call first):
  libraries/cmake/source/libgcrypt/CMakeLists.txt:247 (libgcryptMain)


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by theopolis** [comment]
Nice progress. The next step is equally challenging. You'll have to configure a subset of dependencies for this new architecture and setup the right config structure within `./libraries/cmake/source/DEPENDENCY_NAME`. 

You can infer this scope of the work required here:

```
~/git/osquery/libraries/cmake/source(branch:master*)0 » ag TARGET_PROCESSOR
smartmontools/CMakeLists.txt
78:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux"
82:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos"

librdkafka/CMakeLists.txt
141:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux/dummy"
145:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos/dummy"
192:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux/dummy"
196:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos/dummy"

libdpkg/CMakeLists.txt
96:    "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}"

libgcrypt/CMakeLists.txt
10:  set(generated_root "${CMAKE_CURRENT_SOURCE_DIR}/generated/${TARGET_PROCESSOR}")
123:  if(TARGET_PROCESSOR STREQUAL "aarch64")
147:  if(TARGET_PROCESSOR STREQUAL "aarch64")
197:      COMMAND ${CMAKE_C_COMPILER} -fno-integrated-as -DHAVE_CONFIG_H -O2 -g -DNDEBUG -fPIC -std=gnu11 -o "${asm_object}" -c "${asm_source}" "-I${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}"
231:    "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}"

libgpg-error/CMakeLists.txt
37:    "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}"
38:    "${CMAKE_CURRENT_SOURCE_DIR}/generated/${TARGET_PROCESSOR}"
43:    "${CMAKE_CURRENT_SOURCE_DIR}/generated/${TARGET_PROCESSOR}"

aws-sdk-cpp/CMakeLists.txt
120:  if(DEFINED PLATFORM_POSIX AND TARGET_PROCESSOR STREQUAL "x86_64")
126:  elseif(DEFINED PLATFORM_POSIX AND TARGET_PROCESSOR STREQUAL "aarch64")

boost/CMakeLists.txt
752:  if(DEFINED PLATFORM_LINUX AND TARGET_PROCESSOR STREQUAL "x86_64")
758:  elseif(DEFINED PLATFORM_LINUX AND TARGET_PROCESSOR STREQUAL "aarch64")

lzma/CMakeLists.txt
116:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux"
120:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos"

libaudit/CMakeLists.txt
32:    "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}"

lldpd/CMakeLists.txt
69:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux/libevent"
72:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux/libevent"
76:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos/libevent"
79:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos/libevent"
154:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/linux/liblldpd"
158:      "${CMAKE_CURRENT_SOURCE_DIR}/config/${TARGET_PROCESSOR}/macos/liblldpd"
```

Each of these dependencies may need to be configured:
- smartmontools
- librdkafka
- libdpkg
- libgcrypt
- libgpg-error
- aws-sdk-cpp (this has instruction set specific files)
- boost (this needs specific files to be compiled per-arch)
- lzma
- libaudit
- lldpd

There should be a README in each of these directories that outlines what you need to do, for example `libraries/cmake/source/lldpd/README.md`. Please use a CentOS 6 install when you follow these instructions, ignore the note about Ubuntu 14.04.

**Comment by milind69** [comment]
Hi @theopolis
i am missing something here .. i am trying to compile it on ppc64le host and not cross-compiling on x86_64 hosts ( i want to see if i can do it) 
it looks like it is not finding ppc64le/<files> for these tools and hence it is failing. I see that there are directories for aarch64 and x86_64 in github repo under libraries/cmake/source/<tool>/generated/.. so i copied x86_64 to ppc64le assuming it will work 
it made some progress but now fails

**Comment by milind69** [comment]
[ 17%] Building C object libs/src/lzma/CMakeFiles/thirdparty_lzma.dir/src/src/liblzma/lz/lz_encoder.c.o
cd /home/dciunix/toolchain/osquery/build/libs/src/lzma && /home/u347729/opt/osquery-toolchain/final/sysroot/usr/bin/clang --sysroot=/home/u347729/opt/osquery-toolchain/final/sysroot -DHAVE_CONFIG_H -DLZMADEC -DLZMA_API_STATIC -DNDEBUG -DTUKLIB_GETTEXT=0 -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/lib -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/common -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/check -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/common -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/delta -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/lz -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/lzma -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/rangecoder -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/simple -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/api -I/home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/config/ppc64le/linux  -O2 -g -DNDEBUG -fPIC   -Qunused-arguments -Wno-shadow-field -Wall -Wextra -Wno-unused-local-typedef -Wno-deprecated-register -Wno-unknown-warning-option -Wstrict-aliasing -Wno-missing-field-initializers -Wchar-subscripts -Wpointer-arith -Wformat -Wformat-security -Werror=format-security -Wuseless-cast -Wno-zero-length-array -Wno-unused-parameter -Wno-gnu-case-range -fpermissive -fstack-protector-all -fdata-sections -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -fno-limit-debug-info -pipe -pedantic -pthread -Oz -Wno-c99-extensions -g0 -Wno-everything -Wno-all -Wno-error -o CMakeFiles/thirdparty_lzma.dir/src/src/liblzma/lz/lz_encoder.c.o   -c /home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/lz/lz_encoder.c
In file included from /home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/lz/lz_encoder.c:23:
In file included from /home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/common/memcmplen.h:19:
In file included from /home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/immintrin.h:15:
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/ppc_wrappers/mmintrin.h:31:2: error: "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
#error                                                                         \
 ^
In file included from /home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/lz/lz_encoder.c:23:
In file included from /home/dciunix/toolchain/osquery/libraries/cmake/source/lzma/src/src/liblzma/common/memcmplen.h:19:
In file included from /home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/immintrin.h:15:
In file included from /home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/ppc_wrappers/mmintrin.h:40:
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:55:19: error: unknown type name 'vector'
static __inline__ vector bool char __ATTRS_o_ai
                  ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:56:10: error: unknown type name 'vector'
vec_perm(vector bool char __a, vector bool char __b, vector unsigned char __c);
         ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:56:32: error: unknown type name 'vector'
vec_perm(vector bool char __a, vector bool char __b, vector unsigned char __c);
                               ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:66:19: error: unknown type name 'vector'
static __inline__ vector bool short __ATTRS_o_ai vec_perm(
                  ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:67:5: error: unknown type name 'vector'
    vector bool short __a, vector bool short __b, vector unsigned char __c);
    ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:67:28: error: unknown type name 'vector'
    vector bool short __a, vector bool short __b, vector unsigned char __c);
                           ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:80:19: error: unknown type name 'vector'
static __inline__ vector bool int __ATTRS_o_ai
                  ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:81:10: error: unknown type name 'vector'
vec_perm(vector bool int __a, vector bool int __b, vector unsigned char __c);
         ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:81:31: error: unknown type name 'vector'
vec_perm(vector bool int __a, vector bool int __b, vector unsigned char __c);
                              ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:96:19: error: unknown type name 'vector'
static __inline__ vector bool long long __ATTRS_o_ai
                  ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:97:10: error: unknown type name 'vector'
vec_perm(vector bool long long __a, vector bool long long __b,
         ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:97:37: error: unknown type name 'vector'
vec_perm(vector bool long long __a, vector bool long long __b,
                                    ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:203:9: error: unknown type name 'vector'
vec_add(vector bool char __a, vector signed char __b) {
        ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:208:33: error: unknown type name 'vector'
vec_add(vector signed char __a, vector bool char __b) {
                                ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:218:9: error: unknown type name 'vector'
vec_add(vector bool char __a, vector unsigned char __b) {
        ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:223:35: error: unknown type name 'vector'
vec_add(vector unsigned char __a, vector bool char __b) {
                                  ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:232:53: error: unknown type name 'vector'
static __inline__ vector short __ATTRS_o_ai vec_add(vector bool short __a,
                                                    ^
/home/u347729/opt/osquery-toolchain/final/sysroot/usr/lib/clang/11.0.0/include/altivec.h:238:53: error: unknown type name 'vector'
                                                    vector bool short __b) {
                                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
gmake[2]: *** [libs/src/lzma/CMakeFiles/thirdparty_lzma.dir/build.make:772: libs/src/lzma/CMakeFiles/thirdparty_lzma.dir/src/src/liblzma/lz/lz_encoder.c.o] Error 1
gmake[2]: Leaving directory '/home/dciunix/toolchain/osquery/build'
gmake[1]: *** [CMakeFiles/Makefile2:5387: libs/src/lzma/CMakeFiles/thirdparty_lzma.dir/all] Error 2
gmake[1]: Leaving directory '/home/dciunix/toolchain/osquery/build'
gmake: *** [Makefile:150: all] Error 2

**Comment by theopolis** [comment]
> so i copied x86_64 to ppc64le assuming it will work it made some progress but now fails

Do not do this. :) The reason there is an `x86_64` folder is because there is code and configuration that expects to only work on `x86_64`.

Instead of that, you will need to follow the README directions for each of the dependency libraries I listed above. For example for `lzma` the README is here: https://github.com/osquery/osquery/blob/master/libraries/cmake/source/lzma/README.md run those commands in the `./libraries/cmake/source/lzma/src` directory. The final directions in each of those README files should describe how to build the `ARCH`-specific folders.

**Comment by helix-loop** [comment]
@theopolis You suggested using a CentOS 6 to do the configurations. I am not able to find this (old) version of CentOS for ppc64le. Is there another distribution / version which is not EOL one could use for this?

@milind69 In https://github.com/osquery/osquery/issues/7122#issuecomment-854813695 you mentioned that you were able to build the toolchain. Could you provide your distribution / version used for development and your `crosstool-ng-config-ppc64le` config? (https://github.com/osquery/osquery-toolchain/issues/24)
