### ISSUE TITLE
Notification -- breaking changes to osquery's installation paths

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7146]
Hi folks! This issue is meant to serve as a notification/discussion of an impending breaking change.

With the upcoming osquery 5.0.0 release, the default install location will change from `/usr/local` to `/opt/osquery`. Additionally the macOS package will install osquery using a very minimal app bundle. `osqueryd` will be much the same -- it is not sensitive to it's location, and can freely be moved. 

The change to `/opt/osquery` is meant to reduce likelihood of directory collisions with existing tools.

The minimal app bundle is required to support the macOS Endpoint Security framework.

**Comment by theopolis** [comment]
Should this install path change apply to both macOS and Linux?

**Comment by directionless** [comment]
> Should this install path change apply to both macOS and Linux?

Theory wise -- yes, it should. 

As i understand it, opt is preferred for vendor packages. 

(Can't speak to the code)

**Comment by theopolis** [comment]
My proposal is on macOS we add `/etc/paths.d/osquery` to include `/opt/osquery/bin` and on Linux we can include two symlinks for `osqueryd` and `osqueryi` and install them into `/usr/local/bin`. 

Then we move the actual install of osquery over to `/opt/osquery` on both.

**Comment by erikng** [comment]
Any chance this path is going to change from now until 5.0?

**Comment by directionless** [comment]
> Any chance this path is going to change from now until 5.0?

I'm not sure I understand. 4.9 uses the old path and the old Apple account for signing. 5.0 changes both of them. 

We are not currently planning on a 4.10 release.

**Comment by erikng** [comment]
Great. That's what I needed to know :) My company has discovered an issue with our deployment due to a 3rd party tool, so we will be temporarily forking osquery and moving to the new paths. I just didn't want to find out the hard way in a month or two that the path changes again.

**Comment by directionless** [comment]
> Great. That's what I needed to know :) My company has discovered an issue with our deployment due to a 3rd party tool, so we will be temporarily forking osquery and moving to the new paths. I just didn't want to find out the hard way in a month or two that the path changes again.

Until we release 5.0, these oaths may change. Gotta build and test a few times before we're confident on what the final result will be. 

I'm sure it'll be in /opt/osquery, and I'm sure there'll be an app bundle. But beyond that I think it may change a bit.

**Comment by erikng** [comment]
Fair enough. We will move to `/opt/osquery` and worst case we move again. Thanks for the fast responses.

**Comment by mike-myers-tob** [comment]
@directionless I have seen you give the heads up in other Slacks and such. It has been mentioned in office hours and we have notified our own clients. Anything more that needs to be done for this issue?

**Comment by directionless** [comment]
> @directionless I have seen you give the heads up in other Slacks and such. It has been mentioned in office hours and we have notified our own clients. Anything more that needs to be done for this issue?

This issue is primarily a placeholder to refer people to. We can close it when 5.0 merges. There are other issues with actionable work

**Comment by directionless** [comment]
5.0.1 is stable.

I created some issues in the autopkg repos I could find.
