### ISSUE TITLE
osquery_schedule's `output_size`

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7147]
Long long ago, the `osquery_schedule` table had a `output_size` column. This was removed in 80351aff7d411d2c008055d0547d45dbf1cf0302, citing comments in https://github.com/osquery/osquery/commit/37ffdf8a4899fd515f9db15c00643b1d299367f1#r213278358. I think the general gist of those comments is that the size was calculated pre-serialization, so may not be accurate. 

I frequently find myself trying to debug what queries are generating a lot of data, and this column seems like it would help. Even with the errors introduced in serialization, I think having a rough comparison between scheduled queries would help.

And if we think we should leave it out, we should update the spec. https://github.com/osquery/osquery/blob/d2be385d71f401c85872f00d479df8f499164c5a/specs/utility/osquery_schedule.table#L13

**Comment by zwass** [comment]
Looks like this has been resolved with #7436?
