### ISSUE TITLE
Add table to read text file content

### ISSUE THREAD

**Issue by nickcollier** [osquery/osquery#7164]
# Feature request

### What new feature do you want?

Provide a table that reads the contents of a text file.
The table would require a manditory constraint to specify the file path.
A row should be returned for each line in the file and have the following columns: `path, line_no, text`
The table should be disabled by default and require explictly opting in via configuration.
The table should have a maximum supported line length and file size that can be handled (these options could be made configurable if desired)

### How is this new feature useful?

To look for specific strings in certain log files:

    SELECT text FROM text_file WHERE path = 'C:\ProgramData\SomeVendor\SomeApp\Log.txt' AND text LIKE '% an error occured %'

To check configuration values:

    SELECT SPLIT(text, '=', 1) FROM text_file WHERE path = 'C:\ProgramData\SomeVendor\SomeApp\Config.txt' AND text LIKE 'SomeSetting=%'

    SELECT JSON_EXTRACT(data, '$.SomeSetting') FROM ( SELECT GROUP_CONCAT(text) AS data FROM text_file WHERE path =  'C:\ProgramData\SomeVendor\SomeApp\Config.json' )

**Comment by directionless** [comment]
This functionality is the file carver. 

Can you say more about your intended use case?

**Comment by nickcollier** [comment]
I would like to have the contents of the file available as rows within the query - unless I'm missing something the file carver table can only issue a command to collect the file but doesn't seem to provide the contents as a row.

A common workflow is to send a query out to all osquery instances to check for something (a new vulenarablity, an unwanted installed program, etc.) and then each instance that reports back a row would need further investigation.

I would like to be able to use this workflow for file content based checks, which means the querys themselves need access to the content to determine if a detection/check occured instead of just sending the file. e.g.

    SELECT text FROM text_file WHERE path = 'C:\ProgramData\SomeVendor\SomeApp\Log.txt' AND text LIKE '% an error occured %'

Additionally exposing the file content as row data means it can be combined with other tables, for example you could

- read in one file that contains a list of other paths, then join on to the file/hash table to enrich this data.
- read a URL from a configuration file and then join on to the curl table to check the response status is 200 OK
- read a python projects requirements.txt file and then join the python_packages table to check if they have all been installed

**Comment by directionless** [comment]
There are a couple of reasons I don't think we're likely to see this in core.

Generally speaking, osquery tries to balance some amount of user privacy, vs broad utility. We've tried to avoid arbitrary file reads, they feel too far on the wrong side. File carving exists, because it's useful, it pre-dates that stance, and it can be disabled on the endpoint. 

And, I think there's likely to be some performance issues. File carving has chunking, I think for performance related reasons. 

> I would like to have the contents of the file available as rows within the query - unless I'm missing something the file carver table can only issue a command to collect the file but doesn't seem to provide the contents as a row.

Correct.

> I would like to be able to use this workflow for file content based checks, which means the queries themselves need access to the content to determine if a detection/check occurred instead of just sending the file. e.g.

While not directly in core, there are some paths that might help.

1. The augeas table can parse a number of things. osquery ships a number of lenses, and if you're rolling your own packages you can always include which ones make sense
2. Various third party extensions have implemented various file parsers. 
3. Depending on the specific need, it might be a reasonable table in core.

**Comment by nickcollier** [comment]
I have suggested that this table be disabled by default in the original description which would hopefully address the privacy concerns in the same way they are file carver and will be for mdfind (if #5662 gets implemented).

Sadly the augeas table is not currently available on Windows or it would address some of the configurable based use cases I have for this table.

Several tables that exist today read specific files (etc_hosts, ssh_configs, known_hosts), but you could get exactly the same rows returned using slightly more complicated SQL and the proposed text_file table. I believe there will always be new files cropping up where there would be a desire to read it as a table like these, however with a generic text_files table you would be able to query it straight away without requiring a new table

**Comment by directionless** [comment]
I can see how that would be handy. Nevertheless, I don't think this is something that will land in core.

I'm happy to chat about extension development, or other means to this end, or even the feasibility of compiling augeas on windows.

**Comment by duthils** [comment]
This extension offers a `file_lines` table: https://github.com/macadmins/osquery-extension
