### ISSUE TITLE
Add browser history parsing support

### ISSUE THREAD

**Issue by puffyCid** [osquery/osquery#7177]
# Blueprint

Currently osquery has pretty good visibility into a variety of data on systems. It can view processes, files, logs, artifacts of execution, artifacts of interaction, scan with yara, get applications installed, acquire files, and much more.  
However, one major visibility/forensic gap osquery has is parsing browser history.  
Adding browser history support to osquery could help an analyst answer a variety of questions on a system such as:
* Did an attacker download malware using the browser?
* Did a compromised account view any internal company websites such as internal sharepoint sites, source code, sensitive dbs, phi, etc?
* It may help an analyst determine if there is a possible insider threat (when combined with other data points)?
* It may help provide context if an attacker exfiled data (or accessed) to popular exfil/cloud storage sites like dropbox, mega, onedrive, etc. Or if an attacker browsed to or uploaded data to file transfer sites?

Adding browser history support for the major browsers: Firefox, chrome, and IE/Edge would help give osquery some visibility into the above actions (and possibly other stuff) and could provide an analyst additional leads when using osquery as a forensic/investigative tool.  

A quick mockup (more data and details could be added), the table could return something like:
```
+------------+----------+--------------------------------------+----------+-----------+
| time       | browser  | full url                             | user     |domain     |
+------------+----------+--------------------------------------+----------+-----------+
| 1000000000 | firefox  | google.com/?search=mimikatz+download | bob      | google.com|
+------------+----------+--------------------------------------+----------+-----------+
```
Im curious if other osquery users also want this visibility or if other users have comments/thoughts on this visibility and functionality?

**Comment by directionless** [comment]
I'm uncomfortable with this as a core table. Users tend to view browser history as very sensitive. Curious where other people land 

One alternate approach is to use ATC tables. This should work for anything that had a SQLite db.

I know chrome used to, can't remember if it still does. I think some browsers started moving to an encrypted structure on disk.

**Comment by puffyCid** [comment]
Some users may consider browser history to be sensitive, but when using osquery as a forensic/investigative tool an analyst should be able to a get full picture of a system and collect as much relevant data as possible in order to be able to do a full investigation.  
An analyst may be trying to answer the question "Did an attacker (or compromised account) access or view any data?" and without visibility into browser activity/history the analyst would likely only have an incomplete answer.  

ATC is interesting, but i think that adds additional overhead for an osquery analyst? They would need to research the browser sqlite format, create the json layout, and deploy it to every single endpoint. Adding it to core i think makes it alot easier for an osquery analyst?  
In addition, safari and IE/Edge (older versions) dont use sqlite files. Safari uses plists and IE/Edge uses the ESE format, and I dont think ATC would work for those browsers?

Thats interesting about browsers encrypting data/moving to an encrypted structure on disk, ive not seen that before. Thats kind of cool, do u have any references/blogs or examples of that? I would be interested in learning more.

**Comment by theopolis** [comment]
Right, let's keep browser history out of osquery core.

**Comment by puffyCid** [comment]
> Right, let's keep browser history out of osquery core.
Even if it could provide valuable data to an analyst?  Im a little curious why it wouldnt belong in core? Osquery can be used for performing forensics and parsing browser history is a normal part of forensic investigations.  
Some users/organizations may think browser history is sensitive and other users/organizations may be ok with collecting it. Wouldnt it be better to have the choice and let the user/organization decide?

**Comment by theopolis** [comment]
Check out the previous notes/discussion here: https://github.com/osquery/osquery/issues/1691

**Comment by puffyCid** [comment]
> Check out the previous notes/discussion here: #1691

I saw the discussion at #1691 but that discussion is ~6 years old :).   I also looked at #22.  
It doesnt really provide any other reason for not adding browser history support other than possible privacy concerns (some organizations may or may not consider browser history a privacy concern).  
But wouldnt that concern be user/organization specific? One organization could choose not to use the table or have specific policies for its use. Other organizations may have policies in place that allow browser history to be collected whenever necessary.  

As i mentioned previously, that browser history could be important in analysis when trying to determine if an attacker accessed internal data (or stole data).

**Comment by puffyCid** [comment]
Just curious if this feature is something that would be accepted into core if a PR was created that added this functionality. I wouldnt mind working on/adding this feature sometime in the future. But if there is absolute 0% chance the PR would be accepted, then i wont bother.  

IMO it would be a great addition from a forensic perspective (as mentioned above). So even there is small chance it could be accepted i would gladly work on it. Can also continue to discuss the idea here or in slack if thats better.

Again if there there is absolute 0% chance the PR/feature would be accepted, feel to close this issue.

**Comment by zwass** [comment]
Perhaps this is a discussion best taken to Office Hours (coming up at 13:00 EST on Tuesday)?

I am also inclined against browser history tables in osquery, but it may be productive to discuss where the privacy/utility line is drawn for this project.

**Comment by puffyCid** [comment]
> Perhaps this is a discussion best taken to Office Hours (coming up at 13:00 EST on Tuesday)?
> 
> I am also inclined against browser history tables in osquery, but it may be productive to discuss where the privacy/utility line is drawn for this project.

I would like to discuss/advocate for this feature during officehours.  But i have conflicts when officehours are held, otherwise i would like to join them. If the hackmd notes are posted/enabled early (ex: monday) i can type out my thoughts on that.  If not thats fine.

**Comment by SophosRapidResponse** [comment]
I manage an IR team and while I realize adding browser history as a core table would suddenly give us easy and widespread access to potentially sensitive data, the fact is we often need that data for the investigation, so instead we have to manually collect it using other tools. OSQuery supporting or not supporting a type of data doesn't change what I am going to collect, it just determines if it going to help or hinder the investigation. My vote is to include it as a core table.

I do have a query that can get Chrome history, you need to supply the username, it then gets the Chrome History file, dumps it to hex and then uses GREP and to get the URLs out of it, this only provides you the websites that were visited not the time of when they were, so it is just a quick check to see if there is something interesting before you go and pull the full history via other means. Only got it working with Chrome, haven't been able to figure out a way for the others yet. [https://github.com/SophosRapidResponse/OSQuery/blob/main/Browsing_History/Browsing_History.01.0%20-%20Chrome%20sites%20visited.txt]

**Comment by directionless** [comment]
> I do have a query that can get Chrome history, you need to supply the username, it then gets the Chrome History file, dumps it to hex and then uses GREP and to get the URLs out of it

I'm not sure what this query is designed to run against. I think that's using tables that are not in osquery's distribution. As your readme there says:

> Many of these queries benefit from the additional Sophos tables added to OSQuery, while others will work with 3rd party products using the standard OSQuery tables.

The current standing of the TSC is that extensions (or ATC configuration) is a viable way to get this data. And your Sophos example seems to support the idea that extensions are a viable route.

**Comment by SophosRapidResponse** [comment]
> > I do have a query that can get Chrome history, you need to supply the username, it then gets the Chrome History file, dumps it to hex and then uses GREP and to get the URLs out of it
> 
> I'm not sure what this query is designed to run against. I think that's using tables that are not in osquery's distribution. As your readme there says:
> 
> > Many of these queries benefit from the additional Sophos tables added to OSQuery, while others will work with 3rd party products using the standard OSQuery tables.
> 
> The current standing of the TSC is that extensions (or ATC configuration) is a viable way to get this data. And your Sophos example seems to support the idea that extensions are a viable route.

Hey, yes this works with the Sophos EDR product, I didn't realize it didn't work with the default OSQuery, sorry for any confusion.
