### ISSUE TITLE
OSQuery return empty status log

### ISSUE THREAD

**Issue by YingFengOu** [osquery/osquery#7180]
# Bug report

### What operating system and version are you using?
Windows 10 Enterprise 21H1 19043.964
Windows Feature Experience Pack 120.2212.3740.0

### What version of osquery are you using?
4.9.0

### What steps did you take to reproduce the issue?
Add queries to OSQuery config and register the logger, handling the data for logger with 'Category' and 'status'.

### What did you expect to see?
Receive the correct status data.

### What did you see instead?
Sometimes we go the empty data. We can find the 'status' from the request(ExtensionPluginRequest), and the value(->second) is 'true'. Then we can also find the 'log' item, but the log content is empty. And when the issue happens, there are several threads triggered for send out the log status:
`I0626 13:41:47.598803  5740 logger.h:118] osqueryd.exe status:'[{"s":0,"f":"query.cpp","i":102,"m":"Storing initial results for new scheduled query: logs_purge","h":"WIN10ETChangeMe","c":"Sat Jun 26 17:41:44 2021 UTC","u":1624729304}]'

E0626 13:41:47.598803  8308 logger.h:114] logStatus error json find in array:'[]'

I0626 13:41:47.598803  8308 logger.h:118] osqueryd.exe status:'[]'

E0626 13:41:47.614423  1000 logger.h:114] logStatus error json find in array:'[]'

I0626 13:41:47.614423  1000 logger.h:118] osqueryd.exe status:'[]'

E0626 13:41:47.614423  8464 logger.h:114] logStatus error json find in array:'[]'

I0626 13:41:47.614423  8464 logger.h:118] osqueryd.exe status:'[]'

E0626 13:41:47.614423  4944 logger.h:114] logStatus error json find in array:'[]'

I0626 13:41:47.614423  4944 logger.h:118] osqueryd.exe status:'[]'`

We did not see this before so it should be regression introduced in 4.9.0 and most probably related to this commit: https://github.com/osquery/osquery/commit/3541ef9877f80eb0330796cc9e6335d5a641d625#

and looks like https://github.com/osquery/osquery/blob/master/osquery/logger/logger.cpp#L513 will clean the log and then another thread reached soon will get the empty log.

**Comment by Smjert** [comment]
@YingFengOu Thank you for reporting this!

And sorry for causing this.. I would guess that the change that caused this behavior is this: https://github.com/osquery/osquery/commit/3541ef9877f80eb0330796cc9e6335d5a641d625#diff-503430993a8c1281a71e7285ad98be2ccad1fb1503d9801d0dffa2a19f5e0901R227

The comment states that it has to be processed in a dedicated thread (so async), but it was originally (incorrectly?) handled as synchronous, so the issue was not possible.

If I'm right though this doesn't causes missing logs, it "just" throws additional errors when new threads try to flush logs that have been already sent, right?

**Comment by Smjert** [comment]
@YingFengOu Would you be also able to provide the osquery configuration you're using?

**Comment by YingFengOu** [comment]
Hi @Smjert , Thanks for watching this.

From our side, we are not sure whether there's logs missing or might be some other error log. We register the logger and from the callback
`void ExtensionImpl::call(
    osquery::extensions::ExtensionResponse& _return,
    const std::string& registry, const std::string& item,
    const osquery::extensions::ExtensionPluginRequest& request)`
we found the 'registry' is 'logger' and found the 'status'  is 'true' in the 'request', but the 'log' value in the 'request' is empty.

So yes, it's mostly likely that it just throw an empty status log, but we couldn't prove it on our side.

As for the osquery configuration, it contains some of our product information, so I need more approval process to sharing it. The configuration contains about 30 queries, I think maybe some concurrent query could trigger such issue.

**Comment by Smjert** [comment]
> Hi @Smjert , Thanks for watching this.
> 
> From our side, we are not sure whether there's logs missing or might be some other error log. We register the logger and from the callback
> `void ExtensionImpl::call( osquery::extensions::ExtensionResponse& _return, const std::string& registry, const std::string& item, const osquery::extensions::ExtensionPluginRequest& request)`
> we found the 'registry' is 'logger' and found the 'status' is 'true' in the 'request', but the 'log' value in the 'request' is empty.
> 
> So yes, it's mostly likely that it just throw an empty status log, but we couldn't prove it on our side.
> 
> As for the osquery configuration, it contains some of our product information, so I need more approval process to sharing it. The configuration contains about 30 queries, I think maybe some concurrent query could trigger such issue.

I see, thank you for the clarifications. I already reproduced it on my side but I was also realizing that this might be an issue only with extensions, because I wasn't seeing that error downstream, in the core logging plugins, since they deserialized the JSON response in a way that discards it if there's no log inside.

Anyway I'll have a fix ready in a few.

**Comment by YingFengOu** [comment]
Thanks for the fixing!
