### ISSUE TITLE
TPM Information in a new Table in Schema

### ISSUE THREAD

**Issue by csmarin** [osquery/osquery#7187]
This has been previously raised by another user here: [https://github.com/osquery/osquery/issues/227](https://github.com/osquery/osquery/issues/227)

This information is needed, and although it can be indirectly inferred or implied by an already existing table "_bitlocker_info_", it could still be dependent on whether BitLocker is installed or not. Also information returned by bitlocker_info pertaining to TPM is partial, for example it doesn't give indication on the existence of the TPM chip, enabled or not. It would be nice to have TPM data in its own separate table, it could be handy for admins to know where to deploy digital certificates in a secured manner, etc.

**Comment by directionless** [comment]
Yes, I agree having a `tpm` table would be nice. There's some work towards that in https://github.com/osquery/osquery/pull/7107
