### ISSUE TITLE
Set up a self-hosted ARM Mac CI runner

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7222]
As it becomes possible to build osquery natively for Apple Silicon, we will need a new CI pipeline to run the builds on Apple Silicon hardware. Right now that is not an option offered by GitHub Actions and there is no timeline for it to be supported, but that will likely change in the near future.

In the August 3rd office hours, the consensus seemed to be that we will follow what we have done for AArch64 builds, which is a platform in a similar situation of being unsupported by a hosted GitHub Actions runner. We used a self-hosted runner, but because it could not be secured against misuse by anyone allowed to open a Pull Request, the AArch64 workflow only runs when a PR is merged to the `master` branch (and as a scheduled periodic run on said branch). Ref: https://github.com/osquery/osquery/blob/master/.github/workflows/build_aarch64.yml

The "self"-hosted runner will likely be on a cloud provider like MacStadium, ScaleWay or (if AWS introduces support) AWS EC2. Currently our AArch64 runner is AWS EC2.

~This task does not require us to completely port osquery to Apple Silicon native builds before setting up the CI. The CI can be building an x86 binary and running it under Rosetta until the port is complete.~ That no longer matters, we already completed the ability to build native Apple Silicon binaries.

**Comment by mike-myers-tob** [comment]
[As of July 28th 2022](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), all GitHub Actions hosted runners are still x86-64. We would still need a self-hosted runner for ARM Mac.

[We've been _building_ osquery as Universal binaries](https://github.com/osquery/osquery/blob/master/.github/workflows/hosted_runners.yml#L797) (x86 and ARM) but the ARM code cannot be tested without a runner.

**Comment by directionless** [comment]
This clearly isn't happening
