### ISSUE TITLE
Update CMake version used by the CI to 3.21.x

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7235]
We were originally pinning CMake to 3.17.5 because any version newer than that would have a bug with RPM packages generation.
Now CMake 3.21.x should contain a fix for that issue (https://github.com/osquery/osquery/issues/6755).

**Comment by mike-myers-tob** [comment]
Also a reminder to make changes to the build steps in the wiki for Linux and Windows. Because Homebrew installs version `3.21.1` as of today, no changes needed to the macOS steps. https://osquery.readthedocs.io/en/latest/development/building/

**Comment by mike-myers-tob** [comment]
It is done on `osquery/osquery` but still not done on `osquery/codesign` repo.

**Comment by mike-myers-tob** [comment]
Still just needs the change on the `osquery/codesign` repo, bumping to next month's milestone

**Comment by mike-myers-tob** [comment]
Ref: CMake minimum version required was updated [as part of the PR that added Apple Silicon support](https://github.com/osquery/osquery/blame/11d19323b7c7d138ac7e31999d466b1d8ed928e4/CMakeLists.txt#L8).

This is a housekeeping item, but does @sharvilshah or @directionless know if `osquery/codesign` could get this too so we can close this issue? Is it like a one-line change? I don't have access to make the PR

**Comment by mike-myers-tob** [comment]
Nevermind, looks a slight bit more involved. Closing this issue in favor of the redundant https://github.com/osquery/osquery/issues/7316
