### ISSUE TITLE
linux build installs to `/usr/local/`

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7237]
The linux build should install to `/opt/osquery`

**Comment by Smjert** [comment]
Is this when installing the RPM/DEB package or you mean when you call the `install` target?

**Comment by directionless** [comment]
> Is this when installing the RPM/DEB package or you mean when you call the `install` target?

It's what's in the `tar.gz`. I did not look at the rpm or deb

**Comment by sharvilshah** [comment]
Yes, this is pending for linux :)
Thanks for the detailed info @Smjert, always very much appreciated!

**Comment by thomas-merz** [comment]
@Smjert , could you please have a look at the linked issue in [osquery/osquery-packaging](https://github.com/osquery/osquery-packaging) which has been caused by this issue here? Thanks a lot 👍
