### ISSUE TITLE
Augeas does not parse json file

### ISSUE THREAD

**Issue by asterisk800** [osquery/osquery#7252]
# Bug report

### What operating system and version are you using?
version = 10.16
build = 20G80
platform = darwin

### What version of osquery are you using?
version = 4.5.1

### What steps did you take to reproduce the issue?
osqueryi --line "select * from augeas where path = '/tmp/test.json';"

### What did you expect to see?
[
    {
        "test": "test"
    }
]

### What did you see instead?
Empty result.

**Comment by asterisk800** [comment]
Since the lens file exist in /private/var/osquery/lenses/lenses/json.aug, I started osqueryi with the command below: 
osqueryi --augeas_lenses=/private/var/osquery/lenses/lenses

**Comment by directionless** [comment]
As I understand augeas, it doesn't support arbitrary file reading. Lenses declare what glob patterns for the files they read, and when loaded, all files are read into memory. 

I think the `json.aug` lens does not declare any files, instead it's there as a utility functions for other augeas lenses. It looks like it's used by the `openshift_quickstarts.aug` lens, or perhaps things people distribute outside osquery. 

You can get some sense of what files are known with `select distinct path  from augeas;`
