### ISSUE TITLE
local_timezone not honored with --utc=false on Linux

### ISSUE THREAD

**Issue by kaywoz** [osquery/osquery#7274]
### What operating system and version are you using?

` version = CentOS Linux release 8.4.2105
   build =
platform = rhel`

### What version of osquery are you using?
`version = 4.8.0`

### What steps did you take to reproduce the issue?

 ` select * from time;`

### What did you expect to see?

local time should show CEST

### What did you see instead?

local time and unix time are same, UTC.
![2](https://user-images.githubusercontent.com/64521603/130206256-c0cb762a-5fcc-48e5-8af3-a94faef859d6.PNG)

![1](https://user-images.githubusercontent.com/64521603/130206178-742d3506-1b96-4158-b836-1f5838ae70a3.PNG)

**Comment by theopolis** [comment]
My understanding is that `local_time` and `unix_time` will always stay the same since they are seconds since epoch. Perhaps we should consider removing `local_time`?

**Comment by Smjert** [comment]
> My understanding is that `local_time` and `unix_time` will always stay the same since they are seconds since epoch. Perhaps we should consider removing `local_time`?

Came to the same conclusion here: https://github.com/osquery/osquery/issues/6743
(But then forgot to act ^^')

**Comment by theopolis** [comment]
Ah, I was trying to find that conversation!

**Comment by kaywoz** [comment]
So --utc=false is not supposed to set the osqueryd to log in host local time? Is it even possible to force it to log in host local time, or will it always be in UTC?
