### ISSUE TITLE
Update Linux installation default paths in code and in documentation

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7277]
Beyond a small issue with the symlinks in the Linux packages which I'm fixing in the `osquery-packaging`, we still need to update the documentation and default paths inside the code that still point under `/usr`.

**Comment by Smjert** [comment]
Reopening since this wasn't (fully) fixed by the symlink PR.

**Comment by Smjert** [comment]
@sharvilshah  On this note, I think: https://github.com/osquery/osquery/blob/master/docs/wiki/deployment/process-auditing.md#automatically-granting-permissions-silent-installs has to be updated as well since it's still referring to the old way of installing osquery.

**Comment by sharvilshah** [comment]
@Smjert Yes, thanks for the reminder! I will get to the macOS doc updates

**Comment by mike-myers-tob** [comment]
> Still needs one more thing: documentation about codesigning the binary for your own use. @sharvilshah is working on this now.

Update: instead of encouraging people to re-wrap osquery, we're just going to update the PPPC example.
