### ISSUE TITLE
We should distribute a plain, signed, osqueryd for macOS

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7281]
One of the conversational points, is that while the fully featured macOS version now requires a app bundle, there are some vendors who ship a bare `osqueryd`. I'd like them to be able to keep shipping a properly osquery signed one. 

Obviously, they can work around it by signing their own. But as I'm seeing some other vendors erroneously claiming to ship stock osquery, I'd like to preserve our code signatures where we can.

We should endeavor to not confuse people with this. I think by not having it listed on the main downloads, but instead uploaded to github only. I'm imagine a plain signed macho binary. None of the extra files.

**Comment by mike-myers-tob** [comment]
PR is now merged
