### ISSUE TITLE
Key download for Debian Repo is not working -  keyserver receive failed: No name

### ISSUE THREAD

**Issue by docholiday** [osquery/osquery#7287]
# Bug report

### What operating system and version are you using?

Debian 9.13

### What version of osquery are you using?

Still trying to install

### What steps did you take to reproduce the issue?
Those described on the download page for an installation via repository:
export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY

### What did you expect to see?
The key being saved.

### What did you see instead?
This error message:
Executing: /tmp/apt-key-gpghome.raCJQN5sGB/gpg.1.sh --keyserver keys.openpgp.org --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
gpg: keyserver receive failed: No name

**Comment by directionless** [comment]
Thanks for checking!

This looks like a transient issue with that keyserver, not an error in the instructions.
