### ISSUE TITLE
Failed to get YARA rule url | Retrieving YARA Rules at Runtime 

### ISSUE THREAD

**Issue by mayoterry** [osquery/osquery#7308]
# Bug report

### What operating system and version are you using?

Windows 10 Enterprise

### What version of osquery are you using?

osqueryi.exe version 5.0.1

### What steps did you take to reproduce the issue?

Retrieving YARA Rules at Runtime ，Referer:  https://osquery.readthedocs.io/en/latest/deployment/yara/ https://github.com/osquery/osquery/pull/6607

But always fail , The error message is as follows

osquery> SELECT * FROM yara WHERE path LIKE "D:\code\%" and sigurl = "sig_url_1";
W0914 15:38:26.476879 33604 yara.cpp:249] Failed to get YARA rule url: sig_url_1

### What did you expect to see?

YARA Rules  successfully loaded at Runtime

**Comment by mike-myers-tob** [comment]
The problem might be in the YARA config, can you include yours here?

**Comment by mike-myers-tob** [comment]
Based on this line in the code https://github.com/osquery/osquery/blob/d2be385d71f401c85872f00d479df8f499164c5a/osquery/tables/yara/yara_utils.cpp#L387  I think there might be a mistake in the docs. Maybe each URL should be a JSON array (with square brackets).

```
 "signature_urls": {
      "sig_url_1": [ "https://192.168.152.103/test01.yara" ]
    },
```

**Comment by kswagler-rh** [comment]
I'm still having this problem on Linux (RHEL 8.6 OSQuery 5.5.1)

` 
"yara": {
        "signature_urls": { 
        "sig_url_1": [ "https://raw.githubusercontent.com/kswagler-rh/yara-rulez/main/yara/1.yara"    ]
  }

`


`
config.cpp:879] updateSource failed to parse config, of source: /etc/osquery/osquery.conf and content:
`

And switching to a sig file works

**Comment by msraju** [comment]
I am having same issue as well..

**Comment by msraju** [comment]
> The problem might be in the YARA config, can you include yours here?

Do you have any success ? @mike-myers-tob  ?
