### ISSUE TITLE
Add support for custom AWS Kinesis/Firehose endpoints

### ISSUE THREAD

**Issue by OlegOAndreev** [osquery/osquery#7309]
# Blueprint

Yandex.Cloud recently added a custom AWS Kinesis implementation: https://translate.google.com/translate?sl=ru&tl=en&u=https://cloud.yandex.ru/blog/posts/2021/08/data-streams-preview

We would like to add new endpoint configuration options so that osquery can support Kinesis API for Yandex.Cloud.

The proposed changes are pretty minimal:
1. Add `--aws_allow_unknown_region` flag to disable AWS region validation.
2. Add `--aws_firehose_endpoint` and `--aws_kinesis_endpoint` flags to set endpointOverride in `makeAWSClient`.

If you are ok with the proposed changes, we will create a PR.

**Comment by zwass** [comment]
This seems reasonable to me. There is generally some concern about adding additional configuration options, but it seems like a valid use case and I'm not sure how else we could achieve it.

**Comment by OlegOAndreev** [comment]
Oh, I absolutely share your concerns re:configuration options, unfortunately I do not see any other solution. The only thing we could do is skip the region validation automatically if custom endpoint is set.

**Comment by OlegOAndreev** [comment]
Opened https://github.com/osquery/osquery/pull/7317
