### ISSUE TITLE
Add osquery version to macOS app bundle Info.plist

### ISSUE THREAD

**Issue by weswhet** [osquery/osquery#7312]
# Feature request

### What new feature do you want?

Include the osquery version in the macOS App bundles info.plist

### How is this new feature useful?

Several macOS app distribution automation tools like munki can use the version number provided in an App Bundles macOS info.plist to do a quick and easy version comparison on whether or not an update needs to be installed. Currently, the Info.plist for osquery doesn't include version info.

### How can this be implemented?

During the macOS pkg build process, you could add the version in the `CFBundleShortVersionString` key along with the version value inside the info.plist. Example of what it would look like.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>osqueryd</string>
    <key>CFBundleIdentifier</key>
    <string>io.osquery.agent</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>osqueryd</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>5.0.2</string>
</dict>
</plist
```

Thanks!

**Comment by mike-myers-tob** [comment]
@Smjert @sharvilshah would this be relatively straightforward, or is this difficult in our CMake?
