### ISSUE TITLE
Exception while executing table shortcut_files: invalid string position

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#7380]
# Bug report

### What operating system and version are you using?

Exception originally encountered on Windows Server 2016.
Was able to reproduce the issue on Windows 10 21H1.

### What version of osquery are you using?

Exception originally encountered using osquery 4.8.0.
Was able to reproduce the issue using 5.0.1 as well.

### What steps did you take to reproduce the issue?

Create a copy of an existing lnk file, but only the first 70 bytes (e.g., I used OUTLOOK.lnk from `'C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs'`).
For instance, here's the version I used: 
[test_lnk.txt](https://github.com/osquery/osquery/files/7501114/test_lnk.txt)

Perform a query against the shortcut_files table that targets the truncated LNK copy, e.g.,:
```
osqueryi_501.exe --json "SELECT * FROM shortcut_files WHERE path LIKE 'C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\%';"
```

### What did you expect to see?

No exception generated, results for the rest of the valid lnks.

### What did you see instead?

Empty results and an exception error:
```
E1108 17:00:59.875947 23504 virtual_table.cpp:1006] Exception while executing table shortcut_files: invalid string position
[

]
Error: invalid string position
```

I believe the issue is an unaccounted for 10 byte gap in the parsing logic in [shortcut_files.cpp, `genShortcutFiles`](https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/shortcut_files.cpp#L209) and [shelllnk.cpp, `parseShortcutHeader`](https://github.com/osquery/osquery/blob/master/osquery/utils/windows/shelllnk.cpp#L59).

In order for parseShortcutHeader to succeed, the hex content of the file needs to be at least 132 characters (66 bytes).  However, if the hex-content is less than 152 characters (76 bytes), genShortcutFiles will do the following std::string::substr op, leading to an std::out_of_range exception:
```
    const int lnk_data = 152;
    std::string data_string = lnk_hex.substr(lnk_data);
```

It seems that any file that begins with the expected lnk GUID, and is in the range of [66, 76) bytes in size can trigger the exception.

**Comment by puffyCid** [comment]
Thanks for finding this bug and reporting it
I can take a look at it this week or weekend and try to fix it

**Comment by puffyCid** [comment]
I have fixed this issue.  Im checking other parts of the table to make sure this bug wont be triggered else where.
Im testing against other malformed/modified shortcut files, so far everything seems to be fixed.
Aiming to have a PR to fix this later this week.

**Comment by puffyCid** [comment]
Just a fyi @tferguson7337, I just opened a PR to fix this bug.
The table should log an info message and continue parsing any additional shortcut files
example of fix:
```
osquery> select * from shortcut_files where path = 'C:\Users\bob\Desktop\test_lnk.txt';
I1111 19:56:59.841959 14276 shortcut_files.cpp:216] enum osquery::ConversionError[0] (Invalid shortcut data size)
osquery> select * from shortcut_files where path like 'C:\Users\bob\Downloads\%' limit 1;
I1111 19:57:04.763382 14276 shelllnk.cpp:558] enum osquery::ConversionError[0] (Invalid shortcut data size)
I1111 19:57:04.767338 14276 shelllnk.cpp:132] enum osquery::ConversionError[0] (Invalid shortcut data size)
I1111 19:57:04.767338 14276 shelllnk.cpp:347] enum osquery::ConversionError[0] (Invalid shortcut data size)
I1111 19:57:04.767338 14276 shelllnk.cpp:558] enum osquery::ConversionError[0] (Invalid shortcut data size)
I1111 19:57:04.774370 14276 shelllnk.cpp:558] enum osquery::ConversionError[0] (Invalid shortcut data size)
           path = C:\Users\bob\Downloads\!SBECmd_Messages.txt.lnk
    target_path = This PC\{D3162B92-9365-467A-956B-92703ACA08AF}\ShellBagsExplorer\shells\!SBECmd_Messages.txt
target_modified = 1613263189
 target_created = 1613263186
target_accessed = 1613263189
    target_size = 1512
  relative_path = ..\..\..\..\..\Documents\ShellBagsExplorer\shells\!SBECmd_Messages.txt
     local_path = C:\Users\bob\Documents\ShellBagsExplorer\shells\!SBECmd_Messages.txt
   working_path = C:\Users\bob\Documents\ShellBagsExplorer\shells
      icon_path =
    common_path =
   command_args =
       hostname = desktop-eis938n
     share_name =
    device_type = Fixed storage media (harddisk)
  volume_serial = D49D126F
      mft_entry = 37488
   mft_sequence = 37
    description =
```
Let me know if you are expecting a different way to handle the bug or think there is a better implementation.
Thanks!

**Comment by tferguson7337** [comment]
Info or even warning level logging is fine with me.  So long as results for valid shortcut files are coming through and there are no error logs, I'm happy!

Thanks for the quick turnaround on this @puffyCid.
