### ISSUE TITLE
Tables that require arguments: documention mentions "dropper icon" but it's missing

### ISSUE THREAD

**Issue by jerkstorecaller** [osquery/osquery#7392]
At https://osquery.readthedocs.io/en/stable/introduction/sql/ , under "Tables With Arguments", it says: 
_"Several tables, file for example, represent concepts that require arguments. Consider SELECT * FROM file: you do not want this to trigger a complete walk of the mounted file systems. It is an ambiguous concept without some sort of argument or input parameter. **These tables, and their columns, are flagged by a dropper icon in the schema documentation** as requiring a column or as using a column to generate additional information."_

However, I don't see any dropper icon at https://osquery.io/schema/5.0.1/#device_partitions , the tables look identical to all the other tables. I tried both Firefox and Edge. Here's a screenshot:

![image](https://user-images.githubusercontent.com/58572326/143145955-99490fda-bf98-44eb-96bf-b813dd4f6735.png)

The only way to tell which argument you need to give in a WHERE clause, from what I can see, is to click the "Improve this Description on Github" link for that table, and look for "required=True" in the schema.

**Comment by michael-myers** [comment]
@directionless it looks like the schema website has a pushpin icon 📌 to indicate when "required=True" in a schema. Does that mean the issue is fixed? Mind if I open a small PR to change the wiki doc to refer to a pushpin icon instead of a dropper?
