### ISSUE TITLE
Deprecate antispyware column in windows_security_center

### ISSUE THREAD

**Issue by defensivedepth** [osquery/osquery#7399]
`WSC_SECURITY_PROVIDER::WSC_SECURITY_PROVIDER_ANTISPYWARE should be used only in operating systems prior to Windows 10, version 1607. As of Windows 10, version 1607, WSC continues to track the status for antivirus, but not for anti-spyware.`

Ran across that note here: https://docs.microsoft.com/en-us/windows/win32/api/wscapi/ne-wscapi-wsc_security_provider

The antispyware column in this table relies on that: https://osquery.io/schema/5.0.1/#windows_security_center

I have confirmed that on a Win10 v20H2, osquery still returns Good for this column.

This column needs to be deprecated & removed.

**Comment by iko1** [comment]
@defensivedepth, the program should fetch the antispyware status? although it returns constantly "Good' from Win10 1607

**Comment by iko1** [comment]
@mike-myers-tob, I think you can close this issue after the change was merged.
