### ISSUE TITLE
EXPLAIN never releases constraints and columns from VirtualTable contents

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#7400]
# Bug report

Looks like the call to [`xBestIndex`](https://github.com/osquery/osquery/blob/master/osquery/sql/virtual_table.cpp#L707) never releases the data set on `VirtualTable->contents`. It seems like this has been like this for a while, I assume no one has really noticed as it previously was not normal to run many `EXPLAIN` statements with a long living osquery process. However with https://github.com/osquery/osquery/pull/7158 we now run `EXPLAIN` on denylisted queries [here](https://github.com/osquery/osquery/blob/e8577ce7c359e2780d95c6ee26cd4e80ccba37a5/osquery/events/events.cpp#L35). I've begun noticing osquery collecting more memory than usual. Then after analyzing for a more traditional leak found that the allocations were still in scope. 

I think the fix for this may be quite simple - we can just add a call to [`addAffectedTable`](https://github.com/osquery/osquery/blob/master/osquery/sql/sqlite_util.cpp#L349) after the allocations in [`xBestIndex`](https://github.com/osquery/osquery/blob/master/osquery/sql/virtual_table.cpp#L707) something like:

```
  // Add the constraint set to the table's tracked constraints.
  pVtab->content->constraints[pIdxInfo->idxNum] = std::move(constraints);
  pVtab->content->colsUsed[pIdxInfo->idxNum] = std::move(colsUsed);
  pVtab->content->colsUsedBitsets[pIdxInfo->idxNum] = colsUsedBitset;
  pIdxInfo->estimatedCost = cost;

   pVtab->instance->addAffectedTable(pVtab->content);
```

Unfortunately not everywhere using `EXPLAIN` also calls [`clearAffectedTables`](https://github.com/osquery/osquery/blob/8f9a529c8aeedf2f90f933f83af179dafb19a644/osquery/sql/sqlite_util.cpp#L373). An example being the use of `QueryPlanner` in [`enforceEventsDenylist`](https://github.com/osquery/osquery/blob/e8577ce7c359e2780d95c6ee26cd4e80ccba37a5/osquery/events/events.cpp#L28). I am unsure  of the intention of QueryPlanner and if it should be trying to clear the data, it would be good to have some input on the correct solution for this.

### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 5.0.1   |
+---------+
```

### What steps did you take to reproduce the issue?

1. Run osquery as a shell
2. Run: `EXPLAIN select name from processes;` multiple times
3. Memory will begin increasing
4. If you place a break where [xBestIndex sets content](https://github.com/osquery/osquery/blob/8f9a529c8aeedf2f90f933f83af179dafb19a644/osquery/sql/virtual_table.cpp#L836) we can see values:

```
  pVtab->content->constraints[pIdxInfo->idxNum] = std::move(constraints);
  pVtab->content->colsUsed[pIdxInfo->idxNum] = std::move(colsUsed);
  pVtab->content->colsUsedBitsets[pIdxInfo->idxNum] = colsUsedBitset;
```

Increase with size with each index.

### What did you expect to see?

Memory is freed by emptying content after the execution of each explain statement.

**Comment by nickcollier** [comment]
I'm seeing the same leak in `SQLiteSQLPlugin::getQueryTables` which seems to be called once for each scheduled query every time the config is updated.

@Breakwell I think the fix you raised addressed both issues.
