### ISSUE TITLE
Query timings .. why is it inconsistent.

### ISSUE THREAD

**Issue by michaelvanderbeek** [osquery/osquery#7431]
Hi All,

I've just started to play with osqueryd Thinking it might be useful as a SAR replacement.
I am running 5.0.1 version. OS Centos 7.9
I have a simple config (for testing purposes, only 1 query)
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/var/log/osquery",
    "disable_logging": "false",
    "schedule_splay_percent": "10",
    "pidfile": "/var/osquery/osquery.pidfile",
    "events_expiry": "3600",
    "database_path": "/var/osquery/osquery.db",
    "verbose": "false",
    "worker_threads": "2",
    "disable_events": "false",
    "disable_audit": "true",
    "audit_allow_config": "true",
    "host_identifier": "hostname",
    "enable_syslog": "true",
    "audit_allow_sockets": "false",
    "schedule_default_interval": "3600"
  },
  "schedule": {
    "memory_info": {
        "query": "select * from memory_info;",
        "interval": 60,
        "removed": false
    }
  }
}

Now my problem is how inconsistent this 60s interval is.
For example:
Without DB (3 seconds slower) + with disable_auditd:false
/opt/osquery/bin/osqueryd --ephemeral --disable_database --disable_logging --verbose --flagfile /etc/osquery/osquery.flags --config_path /etc/osquery/osquery.conf
I0104 10:40:30.670468 18577 query.cpp:102] Storing initial results for new scheduled query: memory_info
I0104 10:40:30.670559 18577 scheduler.cpp:176] Found results for query: memory_info
I0104 10:41:33.679005 18577 scheduler.cpp:176] Found results for query: memory_info
I0104 10:42:36.686723 18577 scheduler.cpp:176] Found results for query: memory_info

With DB (2 seconds faster) + with disable_auditd:false
/opt/osquery/bin/osqueryd --ephemeral --disable_logging --verbose --flagfile /etc/osquery/osquery.flags --config_path /etc/osquery/osquery.conf
I0104 10:30:10.151365 18544 query.cpp:102] Storing initial results for new scheduled query: memory_info
I0104 10:30:10.151505 18544 scheduler.cpp:176] Found results for query: memory_info
I0104 10:31:08.160755 18544 scheduler.cpp:176] Found results for query: memory_info
I0104 10:32:06.167333 18544 scheduler.cpp:176] Found results for query: memory_info

Disable auditd query(+ with disable_auditd:true) + without db(4 seconds faster)
/opt/osquery/bin/osqueryd --ephemeral --disable_database --disable_logging --verbose --flagfile /etc/osquery/osquery.flags --config_path /etc/osquery/osquery.conf
I0104 10:47:44.693274 18590 query.cpp:102] Storing initial results for new scheduled query: memory_info
I0104 10:47:44.693389 18590 scheduler.cpp:176] Found results for query: memory_info
I0104 10:48:40.701272 18590 scheduler.cpp:176] Found results for query: memory_info
I0104 10:49:36.708547 18590 scheduler.cpp:176] Found results for query: memory_info

Can anyone tell me how to fix it so that the timing on interval is consistent?
Well its consistent.. +/- some number of seconds.

The more queries there are the longer between each run. Its consistent.

Regards,

Michael

**Comment by Smjert** [comment]
@michaelvanderbeek The `schedule_splay_percent` configuration is what controls that behavior. Since it's set by your config at 10%, then the 60s interval is offsetted by -/+ 6s.

**Comment by michaelvanderbeek** [comment]
I see.. it wasn't really clear what the schedule_splay_percent actually does.  All it states was that the it helps reduce load and collisions of scripts.

Thanks for the explanation!
