### ISSUE TITLE
Processes columns user_time and system_time values are incorrect on Apple Silicon

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7459]
# Bug report

### What operating system and version are you using?

macOS 11.6.2, Apple Silicon

### What version of osquery are you using?

osquery 5.2.1

### What steps did you take to reproduce the issue?

1. Open a terminal and two tabs
2. In the first tab run `while true; do done`
3. In the second tab launch osquery in shell mode and run the query `SELECT user_time, system_time FROM processes WHERE name = "zsh"` roughly every second.

### What did you expect to see?

The sum of user_time and system_time for one of the processes should clearly increase by about 1000 from the second query and on

### What did you see instead?

The times increase only by a value around 20 or so.

This seems to be caused by the API we use, `proc_pid_rusage` which doesn't return nanosecond times anymore in the `user_time` and `system_time` members of the `RUSAGE_INFO_V*` structure, but from my tests it seems a unit that has a value of something around 40ns.

The only talk about this "issue" I've found is here: https://stackoverflow.com/questions/66328149/the-cpu-time-obtained-by-proc-pid-rusage-does-not-meet-expectations-on-the-macos
which might suggest it's a bug in M1?

I've also tried to look at the implementation in the XNU source code but I couldn't see something immediately wrong.

I'm trying to use what chromium uses, which is another set of APIs (task_info, task_for_pid), which though require the binary to be code signed and there are some other requirements which is not yet clear to me.

**Comment by sharvilshah** [comment]
This might take some more digging -- iirc`task_for_pid` and similar mach task APIs now require entitlements (`task_for_pid-allow` and others)

**Comment by Smjert** [comment]
> This might take some more digging -- iirc`task_for_pid` and similar mach task APIs now require entitlements (`task_for_pid-allow` and others)
Ah! that's interesting. I haven't checked if we already somehow have them, but I was also noticing that we already are using `task_for_pid` in the `process_memory_map` table, but the processes I'm able to access with an official build and running as root are more than the osquery process alone, but much less than what I've running, even if those processes have been run by my user.

So basically if I run a non-root `osqueryi` instance and query that table, I can see the memory mappings for that process, but if I then run a new root instance and query the table, I can see some other processes (like a couple more really), but not the previous non-root `osqueryi` instance, which is a bit weird.

**Comment by Smjert** [comment]
By the way, using `task_for_pid` + `task_info` seems to retrieve the correct results (tested by retrieving osqueryd own times), and it's also what `ps` uses:
https://github.com/apple-oss-distributions/adv_cmds/blob/44d0e70decb9c49b9050ff97513c847424317482/ps/ps.c#L700
https://github.com/apple-oss-distributions/adv_cmds/blob/44d0e70decb9c49b9050ff97513c847424317482/ps/tasks.c#L88
https://github.com/apple-oss-distributions/adv_cmds/blob/44d0e70decb9c49b9050ff97513c847424317482/ps/print.c#L821-L835

**Comment by directionless** [comment]
Discussion today in office hours is that this might impact watchdog. Though the watchdog might be able to use the other API since it's a fork/child of the process.

**Comment by Smjert** [comment]
So I stumbled upon this: https://github.com/htop-dev/htop/issues/368 and https://github.com/htop-dev/htop/blob/c5e789db1bb304edee0b8602edf3edc686392cc0/darwin/PlatformHelpers.c#L89 and https://openradar.appspot.com/radar?id=5055988478509056.

The solution was sort of under my nose, because we were already using the `mach_timebase_info` API to get the needed conversion for mach ticks. I wasn't aware that also `user_time` and `system_time` coming from the proc_pid_rusage were in that format.
That API should return a numerator of 125 and a denominator of 3 which results in 41.666...7, which is close to the 40ns I was empirically seeing.
