### ISSUE TITLE
Note: The `cpuid` table is x86 only

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7462]
I think we expected to need to drop some tables with `m1` support, but I don't remember if the `cpuid` table was one. Is this intentional?

**Comment by alessandrogario** [comment]
> I think we expected to need to drop some tables with `m1` support, but I don't remember if the `cpuid` table was one. Is this intentional?

Yes this is intentional and is also missing from the Linux AArch64 port we used for Graviton; the cpuid instruction used in the implementation file is Intel-specific, and there is not a direct replacement.

**Comment by mike-myers-tob** [comment]
Let's make sure this is mentioned in the changelog, as an x86-specific table, with columns that directly return values from the `CPUID` assembly instruction. 

Optionally, do we want to create a new table that is cross-architecture and doesn't have an x86-specific schema? Could be a blueprint issue.

**Comment by directionless** [comment]
If this is an x86 specific instruction, I think it's reasonable to either drop the table, or to have it return no data on other architectures. I'm always torn between not having a table, which feels _correct_, and making it easier to work with osquery.

I suspect we should add an empty table, but I don't think it needs to be release blocking. 

I'm also not sure if it's the same, but I see that arm does have some CPUID registers
