### ISSUE TITLE
Deprecate the unreliable table lldp_neighbors

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7463]
The `lldp_neighbors` table is supposed to work on the macOS and Linux platform (albeit the website schema only lists Linux), but with osquery 5.2.1 it is now removed from the osquery build for macOS Apple Silicon.

The table works by using the lldpd library which acts as a client inside osquery which communicates to a daemon that runs on the system.
The problem is that the protocol is not backward or forward compatible, so a different lldpd daemon version, installed from the package manager, won't necessarily be able to communicate with the version osquery uses.

This breaks the expectation that osquery supports its tables on all the versions is runs on. Moreover, the version that osquery currently uses only works with CentOS 7.

**Comment by iko1** [comment]
@Smjert, What are you thoughts about fetching the LLDP neighbors through command line or DBus in order to keep this table and support multiple Linux distributions?

**Comment by Smjert** [comment]
@iko1 osquery executing a CLI should be definitely avoided. Not only because we have a policy of not creating new processes, but because CLIs do not have a consistent interface between versions, and when that breaks, you never have a compiler error to warn you.

There are also security implications, because it increases the attack surface.

As for DBus, what do you have in mind?
I think it's a matter of, where would it be supported? What it's required from the system? (Ideally nothing more than what there's in a default installation, although this table already had an exception because you had to install the lldpd daemon to get any data).

**Comment by iko1** [comment]
> @iko1 osquery executing a CLI should be definitely avoided. Not only because we have a policy of not creating new processes, but because CLIs do not have a consistent interface between versions, and when that breaks, you never have a compiler error to warn you.
> 
> There are also security implications because it increases the attack surface.
> 
> As for DBus, what do you have in mind? I think it's a matter of, where would it be supported? What it's required from the system? (Ideally nothing more than what there's in a default installation, although this table already had an exception because you had to install the lldpd daemon to get any data).

I'm taking back my suggestion about using DBus instead of linking statically to the lldpd library.
It won't be supported for wide range of distributions as well it doesn't work on the latest distributions.
