### ISSUE TITLE
Deprecate unmaintainable legacy table, smart_drive_info

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7464]
The `smart_drive_info` table is supposed to work on all platforms, but with osquery 5.2.1 it is now removed from the osquery build for macOS Apple Silicon.

The table works via a library that has been created on top of the upstream smartmontools repository. This library is created on top of a now 5 years old upstream code and is 4 years that is unmaintained.
To make it work, since smartmontools doesn't provide any library, the library requires modification/refactors to the upstream code which now would be totally outdated and a maintainance burden to port.
Finally the current implementation only supports the SATA protocol.

**Comment by directionless** [comment]
> Finally the current implementation only supports the SATA protocol.

seems the most compelling reason to me.

Is there a different library or standard that might expose this for more device types?

**Comment by iko1** [comment]
@Smjert, this table is so useful, it has crucial information regarding the health/maintenance information and etc. of hard disk drives SSDs and eMMC drives.
The upstream smartmontools repository is well-maintained and latest stable version was released last year.
The problem with smartmontools library is the lack of API(only command line is supported), so as you know, osquery is using old version(fork) with ad-hoc support of library compiling.
I suggest to rebase the osquery smartmontools repository with the upstream repository(I can take this task on myself), in order to keep this useful table.

**Comment by Smjert** [comment]
@iko1 Thanks for the interest.
Updating the custom library to use the latest version is not the only issue, the problem is that it requires continued maintenance and it shouldn't slow us down if we need to update it (due to CVEs for instance).

**Comment by iko1** [comment]
I've opened a PR with the deprecation of the library and the companion table. 
The smartmontools toolset and specifically smartctl collects unique information about the status of hard disk drives, but the fact that there is no public API to integrate it easily , and we don't want to maintain standalone wrapper outside the toolset upstream, made me understood that opening that deprecation PR is valuable to the project.

**Comment by directionless** [comment]
Have we requested a public API from the upstream? I wonder if they'd be willing to expose something

**Comment by iko1** [comment]
@directionless, Please check this [link ](https://www.smartmontools.org/ticket/501) please, this requirement asked before but nothing was happened
May I try to open the same issue again through the Github smartmontools [repository](https://github.com/smartmontools/smartmontools/issues)?

**Comment by anatol** [comment]
FYI A related project is https://github.com/anatol/smart.go which provides a nice low-level API to access the SMART information. The library is golang so I wonder if using golang-C bridge is fine for osquery.

**Comment by VincentSC** [comment]
> > Finally the current implementation only supports the SATA protocol.
> 
> seems the most compelling reason to me.

NVMe is supported. Not sure since when.

> but the fact that there is no public API to integrate it easily

Since this year, there is an actual effort on [making a library](https://github.com/smartmontools/smartmontools/issues/409).
