### ISSUE TITLE
osquery.io still shows 5.1.0 as the latest release not 5.2.2

### ISSUE THREAD

**Issue by erikng** [osquery/osquery#7483]
is 5.1.0 the latest release or 5.2.2?

**Comment by arubdesu** [comment]
To be a bit more explicit/descriptive about the behavior being observed, https://osquery.io/downloads redirects to [5.1.0](https://osquery.io/downloads/official/5.1.0), and the site is only displaying 5.1.0 as 'current'. Considering it just got discussed by @directionless that download/version improvements may be considered packaging issues (as per https://github.com/osquery/osquery-site/issues/227) this is probably the right place for the conversation.

https://github.com/osquery/osquery/releases/latest redirects/points at [5.2.2](https://github.com/osquery/osquery/releases/tag/5.2.2) and there are no 'prerelease' labels attached, so I'd assume it's safe to consider it the actual latest/fully released, and just chalk up a lag in addressing maintenance needs on the website. @erikng you'd like confirmation releases/latest in this repo should be considered authoritative?

**Comment by erikng** [comment]
Pretty much. I'd like to know what is the authority before deploying 5.2.2 to 60,000 devices.

**Comment by directionless** [comment]
5.2.2 is stable. I haven't updated the website yet. (It's a separate process than the github tagging. That they don't happen together is a human foible)

> Pretty much. I'd like to know what is the authority before deploying 5.2.2 to 60,000 devices.

Strongly recommend running your own test deploy to vet before rolling out to that many devices.

**Comment by erikng** [comment]
I mean of course. I just don't want to deploy _any_ pre-release to _any_ clients.

**Comment by directionless** [comment]
I updated the website. There may be caching delays
