### ISSUE TITLE
Column algorithm of table authorized_keys is empty

### ISSUE THREAD

**Issue by tokcum** [osquery/osquery#7544]
# Bug report

### What operating system and version are you using?

- Ubuntu 18.04.6 LTS
- Ubuntu 20.04.4 LTS
- Debian 11

### What version of osquery are you using?

- osquery 5.2.2

### What steps did you take to reproduce the issue?

When using `SELECT * from authorized_keys` to get a list of authorized_keys the algorithm column is not populated and stays empty.

### What did you expect to see?

Based on the documentation of the [osquery schema](https://www.osquery.io/schema/5.2.2/#authorized_keys), I expected to see the algorithm of the key.

So if the key looks like `ssh-ed25519 AAAACxxxxxxxxxxxxxxxx my.mail@local`, the algorithm should be `ssh-ed25519` or `ed25519`. Alternatively the schema docs should explain the prerequisites for this column.

### What did you see instead?

The algorithm column is not populated and stays empty.

**Comment by iko1** [comment]
The program doesn't parse correctly the line syntax within the 'authorized_keys' file. actually, the parsing code is very partial and there is no code that extracts the information into the table columns. I'm working on a fix.

**Comment by iko1** [comment]
This is an example of query output after my fix:
![image](https://user-images.githubusercontent.com/11705712/164042185-46c27c8c-27cf-427d-a124-d53035e640b5.png)

**Comment by tokcum** [comment]
Nice! Looks good.
