### ISSUE TITLE
Add CIDR functions

### ISSUE THREAD

**Issue by zwass** [osquery/osquery#7555]
# Feature request

Add functions for working with CIDR IP ranges.

### What new feature do you want?

Possible usage:

`SELECT in_cidr_range('10.0.0.0/26', '10.0.0.24')` would result in `1` (true).

### How is this new feature useful?

Allow detecting CIDR ranges beyond what is easily possible with `LIKE` queries. See https://osquery.slack.com/archives/C01DXJL16D8/p1649351841966129 for some discussion.

### How can this be implemented?

Implement like other custom SQL functions in osquery.

**Comment by iko1** [comment]
I'd like to know if a compatible function for IPv6 address should be added too, or one function should support both IP address types: IPv4 and IPv6?
