### ISSUE TITLE
Limit macOS UAL table rows number and provide sequential extraction

### ISSUE THREAD

**Issue by dabresua** [osquery/osquery#7591]
# Blueprint

## Introductory context

There is a PR #7259 that implements the parser for macOS Unified Access Logger. The problem is that the table can generate a large amount of data taking several seconds or even minutes. In those cases, the watchdog will probably kill it.

On the other hand, @puffyCid suggested on Slack that from a forensic point of view, it will require getting all the data at once for investigations. I understand that these kinds of research are exceptional, and the user can configure osquery to allow them.

Also, in the macOS Slack channel, there was some discussion and analysis about using the `LIMIT` clause. However, we concluded that is not feasible since it is applied after all the rows are generated, and there is no way to provide the table with the `LIMIT` clause in the context.

## Log aggregation platforms

Some log aggregation platforms use osquery as an endpoint to feed raw data into their servers. It is fundamental for those platforms to have all the data available.

If Osquery limits in some manner the number of rows provided, it will be very tricky to extract all the data from a machine.

That is why Osquery should provide a method to extract all the logs in sequential operations.

## How it works

The table uses an [OSLogEnumerator](https://developer.apple.com/documentation/oslog/oslogenumerator?language=objc) to access log entries. It initializes this enumerator using date constraints, etc.

The enumerator is iterated in a loop to get the [log entries](https://developer.apple.com/documentation/oslog/oslogentrylog?language=objc). Each iteration will read the log and serialize it into the table format. 

The process is expensive for the CPU and disk for accessing the stored logs. It also greatly impacts memory for accumulating all the log data on RAM.

### Adding a FLAG

The best way to limit the number of rows is to establish a FLAG that breaks the iterative process of getting the logs and serializing them. The FLAG can have a default value for most daemons. 

In the case of getting a lot of logs at once using the shell, the user can modify the FLAG value to allow it.

A better way will be using a `LIMIT` clause, but it seems is not supported.

- *Why we can't filter by timestamp instead as was suggested?*
Because it is not guaranteed that the number of rows returned complies with the CPU/disk/memory limits that we want to ensure.

### Keep track of returned rows

Aggregation tools require sending all logs. However, if we limit the number of rows returned, getting all the logs could be very tricky.

To provide support for getting all the logs generated on the system, Osquery will keep track of the last log sent by saving the timestamp (and additional info) into persistent memory (the database). By saving that, Osquery can configure the enumerator in a way it gets the next log so:

* Provides a method to extract all the logs sequentially.
* Skips all the extracted data saving lots of iterations: less CPU/disk/memory usage.

This method only applies to the query `select * from unified_log` considering that other queries that provide some kind of filter, are used for other purposes. I.e. when querying `select * from unified_log where pid > 100 and pid < 105` the optimization is not applied, nor the last timestamp is modified.

- *Why don't we use an evented-table instead?*
Evented tables require a PUB-SUB mechanism and to save all the data into RocksDB. Given the massive amount of data generated by UAL, it will lead to an intense usage of disk and CPU. Also, UAL already saves its info into files.

- *If it is not an evented-table, Will the data ever expire?*
It depends on UAL. I asked on the [macOS developer forum](https://developer.apple.com/forums/thread/705843)

### Use case example

An endpoint configures the maximum number of rows at **100**.

Also, sets a scheduled query `select * from unified_log` every **5 minutes**.

* case A: there are 80 logs every 5 minutes
All logs will be sent, and in the next round, logs will be sent starting from the next one that has been sent.
* case B: usually there are 80 logs every 5 minutes, but sometimes there are 120
When 120 logs are generated, only 100 will be sent. However, in the next round, another 100 will be sent (the 20 that couldn't be sent and the new 80)
* case C: there are 200 logs every 5 minutes
The table is not capable of sending all the logs, and Osquery should be reconfigured to allow such quantity.

## Documentation

Should provide documentation about how to use the flag and how to extract the data sequentially.

**Comment by dabresua** [comment]
We agreed to modify the behaviour at the [osquery office hours 2022-05-24](https://hackmd.io/7aYrhwjQSrmlMhp_3fyS9A).

First, the `select * from unified_log` hack feels weird because a non-expert user won't understand that behavior. The quorum was to add a sentinal value like `select * from unified_log where timestamp > 'LAST_TIMESTAMP'` or any other magic word.

Sencondly, a flag seems obscure, instead, a HIDDEN column for max_rows is preferable. Default value should be something between 100 and 1000 that guarantees stability. `select * from unified_log where max_rows = 123` will return up to 123 rows.

**Comment by dabresua** [comment]
I wasn't able to use the sentinal value of `'LAST_TIMESTAMP'`, it seems the sqlite engine is not prepared for changing the data type.
I'm now using `-1` which seems to work just fine.

**Comment by directionless** [comment]
Closed by #7598
