### ISSUE TITLE
fan_speed_sensors table not reporting accurate data

### ISSUE THREAD

**Issue by tdspoe** [osquery/osquery#7641]
# Bug report

### What operating system and version are you using?
macOS 10.15.7 (MBP i9) macOS 12.3.1 (M1 Pro)
version = 10.15.7
   build = 19H1922
platform = darwin

### What version of osquery are you using?

version = 5.3.0
### What steps did you take to reproduce the issue?
Discovered on 16" i9 MBP  (macOS 10.15.7) and confirmed on 14.1" M1 Pro (macOS 12.3.1)
### What did you expect to see? 
Something like:
osquery> SELECT * FROM fan_speed_sensors LIMIT 1;
fan = 0
name = Left side
actual = 2225
min = 2096
max = 5863
target = 2219
as documented here: https://www.kolide.com/blog/how-to-monitor-macos-hosts-with-osquery#basic-queries

### What did you see instead?
/usr/local/bin/osqueryi --line "select * from fan_speed_sensors desc;"  
   fan = 0
  name = 0
actual = -1
   min = -1
   max = -1
target = -1

   fan = 1
  name = 0
actual = -1
   min = -1
   max = -1
target = -1

**Comment by directionless** [comment]
I think this is a dup of #7627
