### ISSUE TITLE
Behavior of `--extensions_timeout` as applied to `--config_plugin` is inconsistent. 

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7653]
# Bug report

If one is using an extension provided `config_plugin`, obviously that extension must register before osquery reads the config. This presents some timing sensitivity. I believe the `extensions_timeout` flag is there to add some delay to osquery startup, to give extensions a change to register. 

**However** this only applies to osquery managed extensions. If there is nothing being loaded, then there is no timeout and osquery promptly exists.

I believe this is a bug, and that osquery should wait `extensions_timeout` for any extensions to register. (One might say that it should be a new configuration parameter. But this one already exists and fills this niche)

```shell
$ time osqueryd --disable_database --pidfile /tmp/osq.$RANDOM.pid --extensions_socket /tmp/osq.$RANDOM.sock --extensions_timeout=20 --config_plugin=does-not-exist  
E0624 14:38:56.797560 65406336 shutdown.cpp:79] Cannot activate does-not-exist config plugin: Unknown registry plugin: does-not-exist
E0624 14:38:59.794203 1843261440 shutdown.cpp:79] Worker returned exit status

real	0m3.242s
user	0m0.016s
sys	0m0.015s
```

And with an extension:
```shell
$ echo /usr/local/kolide-k2/bin/osquery-extension.ext > /tmp/al
$ time osqueryd --disable_database --pidfile /tmp/osq.$RANDOM.pid --extensions_socket /tmp/osq.$RANDOM.sock --extensions_timeout=20 --config_plugin=does-not-exist  --extensions_autoload /tmp/al 
[/usr/local/kolide-k2/bin/osquery-extension.ext --socket /tmp/osq.17423.sock --timeout 20 --interval 3]E0624 14:39:50.093936 62899584 shutdown.cpp:79] Cannot activate does-not-exist config plugin: Unknown registry plugin: does-not-exist
E0624 14:39:50.738528 1837412352 shutdown.cpp:79] Worker returned exit status

real	0m24.065s
user	0m0.065s
sys	0m0.044s
```

**Comment by Smjert** [comment]
@directionless We have the flag `extensions_require` for all extensions that need to be registered soon. It will still use `extensions_timeout` as the timeout, but it will work with non osquery managed extensions.

**Comment by directionless** [comment]
Ha. Of course, there's _another_ option lurking. Thank you!  I'm going to close this and test more heavily. I'll re-open if there's an issue.
