### ISSUE TITLE
Both `build` and `version` from `os_version` not as expected on Windows

### ISSUE THREAD

**Issue by arubdesu** [osquery/osquery#7663]
# Bug report

This is a follow-on of my noisiness about refinements to the os_version across multiple platforms that is related to #7657, but seems to have also been mentioned in #6082 if not other places I'm missing. 

From an end user perspective on Windows, this is what you'd see in the graphical interface provided by the Settings app:
<img width="602" alt="win build user expectation" src="https://user-images.githubusercontent.com/388808/176336215-a40f7b2e-15b9-4eb4-b85d-92317e2188b3.png">

### What operating system and version are you using?

osquery 5.2.3,
```osquery> select * from os_version;
version = 10.0.19044
build = 19044
platform = windows
```

### What steps did you take to reproduce the issue?
Same as above
### What did you expect to see?
Version matching the gui, corresponding to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\DisplayVersion`, 21H2
Build would be a period-separated concat of the `CurrentBuild` and `UBR` keys values from the same registry 'path' (I don't know what 'hives' are), 19044.1766
### What did you see instead?
The output above

I understand this diverges greatly from behavior in many revisions of osquery to date, so I can understand this being delayed to a major version bump, but I don't think it's intuitive/informative enough at present. In any case, I wanted to file the issue so the info is in more places than just the #windows channel in osquery slack.

**Comment by zwass** [comment]
Should be resolved by #8265
