### ISSUE TITLE
The windows registry is case insensitive

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7673]
I have recently learned that windows registry key names are case insensitive (See https://docs.microsoft.com/en-us/windows/win32/sysinfo/structure-of-the-registry).

I don't know what's possible, but I think sqlite support declaring default `COLLATE` settings for columns. It would be handy to add that one.

**Comment by iamharlie** [comment]
Tested this just to double check on my machine by trying to create a new key with the same name as another in different casing, and Windows said it already existed, so looks to be right 👍
