### ISSUE TITLE
Update macOS CI build job to use Monterey (macOS 12)

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7702]
Due to a scheduled brownout of Catalina Github Actions runners, we are temporarily removing the separate Catalina test job (PR: https://github.com/osquery/osquery/pull/7700), so that only Big Sur gets tested.

Ideally we would also update the Big Sur build job to Monterey and restore the test job on Big Sur, but to update to Monterey we need to test closely the full pipeline. This issue tracks this desire.

We would also need to update our ReadTheDocs documentation.

**Comment by mike-myers-tob** [comment]
Ref: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md

**Comment by Smjert** [comment]
I moved this to the next milestone, it wasn't my target to get it done this milestone, I don't think we should rush it and we should also re-generate all the library configs.

**Comment by mike-myers-tob** [comment]
- [ ] The Packaging job already uses Big Sur. It could use Monterey.
- [ ] Deprecate Catalina-based build and build from Big Sur
- [ ] Move the build job to Monterey
- [ ] Move the Test job to Big Sur
- [ ] Update the ReadTheDocs documentation about what CI is doing
