### ISSUE TITLE
suffering from err when running install

### ISSUE THREAD

**Issue by eastbook** [osquery/osquery#7724]
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
>   -DCPACK_GENERATOR=DEB \
>   -DOSQUERY_PACKAGE_VERSION=${OSQUERY_VERSION} \
>   -DOSQUERY_DATA_PATH=${DESTDIR} \
>   -DOSQUERY_SOURCE_DIRECTORY_LIST="/Users/bytedance/workspace/machinequery/osquery;/Users/bytedance/workspace/machinequery/osquery/build" \
>   ../../osquery-packaging
**CMake Error at CMakeLists.txt:45 (include):
  include could not find requested file:

    platform/macos/deb.cmake**

**Comment by eastbook** [comment]
it looks like it is not to allowed to generate deb pkg in macos?

**Comment by mike-myers-tob** [comment]
Right, if you need to build `.deb` packages, you currently have to build on Linux. They are also available from the releases page if you just need pre-built packages.
