### ISSUE TITLE
OSQuery failed to build with error MSB3491 on MSVC 

### ISSUE THREAD

**Issue by ChanyeolWang** [osquery/osquery#7748]
# Bug report

### What operating system and version are you using?
Windows: windows server 2019
VS: 2019

### What steps did you take to reproduce the issue?
1.git clone  https://github.com/osquery/osquery F:\gitP\facebook\osquery
2.cd F:\gitP\facebook\osquery\build
3.set PATH=C:\Python\Python27\;%PATH% 2>&1
4.set PATH=C:\Python\Python27\Scripts;%PATH% 2>&1
5.cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. 2>&1
6.set _CL_=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %_CL_%
7.cmake --build . --target osqueryd --config Release --verbose -- /maxcpucount 2>&1

### What did you expect to see?
build successfully.
### What did you see instead?
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB3491: Could not write lines to file "x64\Release\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h\osquery_.482695D9.tlog\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h.lastbuildstate". Path: x64\Release\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h\osquery_.482695D9.tlog\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h.lastbuildstate exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [F:\gitP\facebook\osquery\build\osquery\worker\ipc\osquery_worker_ipc_platformtablecontaineripc_ns_include_platform_table_container_ipc.h.vcxproj]
**log**
[build.log](https://github.com/osquery/osquery/files/9413471/build.log)

**Comment by mike-myers-tob** [comment]
Hello. This looks like the long filepaths problem on Windows, where you can workaround it by building from a directory closer to root. I build in `C:\Projects\osquery` without issues, see if that works for you. Alternatively you can change this limitation of Windows, as explained on the osquery wiki https://osquery.readthedocs.io/en/latest/development/building/#windows-10
