### ISSUE TITLE
in debug builds: file carve table broken after size updated

### ISSUE THREAD

**Issue by apinter-figma** [osquery/osquery#7756]
# Bug report

Hi there, when using a debug build there is a type assertion error on loading carve rows after the carver has updated the size column with the actual carve size since the update row function sets the size as a string. I have a fix working locally, but am submitting this and then will attach a PR (and do the CLA).

### What operating system and version are you using?

```
 version = 12.5.1
   build = 21G83
platform = darwin
```

### What version of osquery are you using?

```
version = 5.5.0-1-g41f4aba19
```

### What steps did you take to reproduce the issue?

I setup a local osquery agent with a locally running server in order to build out our file carving server implementation. After the first succesful carve I was no longer able to query the carves table and instead got the following assertion error. `Assertion failed: (data_.f.flags & kIntFlag), function GetInt, file document.h, line 1767..`

### What did you expect to see?

A successful result like 

```
osquery> select * from carves;
+------------+------------------------------------------------------------------+------+------------+-----------+--------------------------------------+--------------------------------------+-------+
| time       | sha256                                                           | size | path       | status    | carve_guid                           | request_id                           | carve |
+------------+------------------------------------------------------------------+------+------------+-----------+--------------------------------------+--------------------------------------+-------+
| 1661380470 | 4132ec7a31f82ed0dbf7d0b30c76b0403cdaec527fc35054e7094e9ba2e7d431 | 2048 | /etc/hosts | SUCCESS   | 573aeba7-c336-40d6-aecd-1c20ea98b256 | 7fc27abf-5506-4b26-8ac9-29681a3c2884 | 0     |
+------------+------------------------------------------------------------------+------+------------+-----------+--------------------------------------+--------------------------------------+-------+
```

### What did you see instead?

```
% osquery/osqueryi --flagfile ~/Desktop/osquery-dev/osquery.local.flags
Using a virtual database. Need help, type '.help'
osquery> select * from carves;
Assertion failed: (data_.f.flags & kIntFlag), function GetInt, file document.h, line 1767.
```

**Comment by mike-myers-tob** [comment]
Thanks @apinter-figma , although I have not tried to reproduce this myself yet, we look forward to seeing the PR you mentioned.

**Comment by apinter-figma** [comment]
@mike-myers-tob thanks, I've got a PR in draft and am just waiting on my legal dept to check out the CLA. Thanks!
