### ISSUE TITLE
we got huge volume of /api/v1/osquery/distributed/read  and  api/v1/osquery/log  flushing into fleet and crash it

### ISSUE THREAD

**Issue by eastbook** [osquery/osquery#7768]
i would like to know what are these two apis doing? And how to debug the root cause. currently, we have 20K hosts installed osquery with orbit but our LB of fleet received 2 million req from hosts with agent per hour, and most of them are /api/v1/osquery/distributed/read and api/v1/osquery/log

And why are these 2 APIs are POST?

**Comment by Smjert** [comment]
Hello @eastbook, for the FleetDM crashing part, I would also report this to them: https://github.com/fleetdm/fleet

That been said, the distributed API is for osquery to request queries that it has to run ad-hoc, "immediately", and there's also the relative `write` API endpoint which returns the results from those queries.

The other API should be for osquery to report logs to the fleet manager, through the TLS logger plugin.

The endpoints are configured by the flags
`--distributed_tls_read_endpoint`
`--distributed_tls_write_endpoint`
`--logger_tls_endpoint`

Both distributed and logger plugins have an interval that they use to get queries or push logs. They can be controlled by the following flags:
`--distributed_interval`, which by default (set by osquery, not orbit) is 60 seconds
`--logger_tls_period`, which by default is 4 seconds

I'm not entirely sure why the distributed read API is a POST, afaik the only information osquery sends is a node key for the fleet manager to identify the agent.

There's more information on the two features here: https://osquery.readthedocs.io/en/latest/deployment/remote/#distributed-queries, https://osquery.readthedocs.io/en/latest/deployment/remote/#remote-logging
and flags https://osquery.readthedocs.io/en/latest/installation/cli-flags/#distributed-query-service-flags, https://osquery.readthedocs.io/en/latest/installation/cli-flags/#remote-settings-flags-optional

I would suggest joining us on Slack if you have further questions, the FleetDM folks have their own channel too: https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw

**Comment by timmy-k** [comment]
@eastbook I work at Fleet, sorry it took me a second to notice this.

I talked to a member of our team and she suggested this:

> They could try tweaking the distributed_interval and logger_tls_period in agent options. Those control how often hosts check for queries and how often they send results to Fleet. Setting those to higher intervals will reduce the total number of requests sent to the server, but could also negatively impact live queries.

If you'd like to create a running dialogue with Fleeties that can help you with this our slack channel is the perfect place. You can join here— https://fleetdm.com/slack.

If you have any other questions LMK!
