### ISSUE TITLE
export LDFLAGS="-L/usr/local/opt/openssl@3/lib"   export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

### ISSUE THREAD

**Issue by MilkandGinn** [osquery/osquery#7772]
This has probably been asked a billion times, but I tried to search to see that it had not. I am trying to build to run on macOS, which has both openssl@1.1 and openssl@3 installed via home-brew. When installing openssl@3, it tells me that I may want to add the following to my build variables to tell the project files where the openssl data is located:

**export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"**

However, I cannot for the life of me figure out where it should go. I assume in ssl.h, but again, even if that's the correct file, where it should go in the file is beyond me.

**Comment by directionless** [comment]
osquery has a lot of third party dependancies and ships them as part of the source code. We do not support building against other libraries. There are some docs about how to build osquery at https://osquery.readthedocs.io/en/latest/development/building/
