### ISSUE TITLE
Fix the behavior of discovery queries on distributed queries

### ISSUE THREAD

**Issue by eastbook** [osquery/osquery#7793]
We cleaned up the orbit in our hosts of osquery and running them as system daemon service, but we discovered they still receive this from fleet by distributed/read api.

Oct 14 22:04:22 n121-038-121 osqueryd[563006]: I1014 22:04:22.862608 563137 tls.cpp:255] TLS/HTTPS POST request to URI: https://[fleet_endpoint]api/v1/osquery/distributed/read
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: {"node_key":"RnxiqtnNMV2ukNQlWrNtcy8m5f0DfvBP"}
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: {
Oct 14 22:04:22 n121-038-121 osqueryd[563006]:   "queries": {
Oct 14 22:04:22 n121-038-121 osqueryd[563006]:     "fleet_detail_query_orbit_info": "SELECT * FROM orbit_info"
Oct 14 22:04:22 n121-038-121 osqueryd[563006]:   },
Oct 14 22:04:22 n121-038-121 osqueryd[563006]:   "discovery": {
Oct 14 22:04:22 n121-038-121 osqueryd[563006]:     "fleet_detail_query_orbit_info": "SELECT 1 FROM osquery_registry WHERE active = true AND registry = 'table' AND name = 'orbit_info';"
Oct 14 22:04:22 n121-038-121 osqueryd[563006]:   }
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: }
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: I1014 22:04:22.874121 563137 distributed.cpp:131] Executing distributed query: fleet_detail_query_orbit_info: SELECT * FROM orbit_info
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: E1014 22:04:22.874183 563137 distributed.cpp:145] Error executing distributed query: fleet_detail_query_orbit_info: no such table: orbit_info
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: I1014 22:04:22.874310 563137 tls.cpp:255] TLS/HTTPS POST request to URI: https://[fleet_endpoint]/api/v1/osquery/distributed/write
Oct 14 22:04:22 n121-038-121 osqueryd[563006]: {"queries":{"fleet_detail_query_orbit_info":[]},"statuses":{"fleet_detail_query_orbit_info":1},"messages":{"fleet_detail_query_orbit_info":"no such table: orbit_info"},"node_key":"RnxiqtnNMV2ukNQlWrNtcy8m5f0DfvBP"}

i guess this is not supposed to happen?

**Comment by lucasmrod** [comment]
This is a bug in the "discovery" queries feature of distributed queries and should be fixed by #7655.

**Comment by zwass** [comment]
Fixed by #7655 :)
