### ISSUE TITLE
Firefox Addons 'native' field doesn't exist on Linux while it does on Mac OS

### ISSUE THREAD

**Issue by stanimirivanovde** [osquery/osquery#7827]
I am running a query that includes the 'native' column for firefox_addons. But on CentOS this query fails, while on Windows and Mac OS it succeeds. Looks like the native field was removed in this PR commit: <https://github.com/osquery/osquery/pull/7735>. I need to remove the field from my queries so they don't error out. The online documentation also clearly says that the `Native` field is supported:

```text
native | integer | 1 If the addon includes binary components else 0
```

The source code for the online documentation has been modified to remove the 'native' field but this hasn't been updated in the online documentation:

https://github.com/osquery/osquery/blob/master/specs/firefox_addons.table#L3

I think the website documentation needs to be regenerated.

**Comment by Smjert** [comment]
Hello @stanimirivanovde, the website is actually correct; right now the website shows the schema for 5.5.1 (this is the URL you will have https://osquery.io/schema/5.5.1/#firefox_addons), and the change has landed after it, so it's in 5.6.0, which is still not present on the website.

**Comment by stanimirivanovde** [comment]
I see, but how come 5.5.1 contains the changes then? On CentOS the column doesn't exist.

**Comment by Smjert** [comment]
> I see, but how come 5.5.1 contains the changes then? On CentOS the column doesn't exist.

Can you clarify what do you mean with "5.5.1 contains the changes"? Which changes?

What I'm saying is that 5.5.1 still has the `native` column, and that's correct, because the PR that removes it has landed after 5.5.1.

"On CentOS the column doesn't exist", the platform here doesn't matter, which version of osquery are we talking about?
Please run osquery with `--version` to see the version of the binary.

**Comment by stanimirivanovde** [comment]
You are right:

```text
osquery 5.6.0
using SQLite 3.39.2
```

I was looking at the official downloads page and didn't see a download for 5.6.0 which is what mislead me. I thought 5.5.1 is the latest version. How come 5.6.0 is not available on the downloads page?

**Comment by Smjert** [comment]
> I was looking at the official downloads page and didn't see a download for 5.6.0 which is what mislead me. I thought 5.5.1 is the latest version. How come 5.6.0 is not available on the downloads page but it is available in the CentOS repo?

There's no CentOS repo per-se, we generically prepare a single rpm and deb package which should work on all the distros that use those kinds of package systems.
The repo I think you're referring to is `https://pkg.osquery.io/rpm/osquery-s3-rpm.repo`; we have automation that uploads the build in the Github releases page and in the S3 bucket (which is what is backing up the package repository).

The website is separate and it's still updated semi-manually, so it happens later sometimes.

**Comment by Smjert** [comment]
> Thanks @Smjert, I still see the website is not updated with the latest version.

It has been updated now!

I'm closing this issue now; if there's something else about this issue you can reopen the issue, or you can join us on Slack and make your question there, using this invite: https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw
