### ISSUE TITLE
osquery `disk_encryption` table incorrectly states disk is not encrypted on linux

### ISSUE THREAD

**Issue by artemist-work** [osquery/osquery#7889]
# Bug report

### What operating system and version are you using?

```
+-------------------------------+-------+----------+
| version                       | build | platform |
+-------------------------------+-------+----------+
| 22.04.1 LTS (Jammy Jellyfish) |       | ubuntu   |
+-------------------------------+-------+----------+
```
### What version of osquery are you using?
```
+---------+
| version |
+---------+
| 5.6.0   |
+---------+
```

### What steps did you take to reproduce the issue?
Run `SELECT * FROM disk_encryption;` and `SELECT * FROM disk_encryption WHERE name="/dev/dm-1";` on a machine with LVM on LUKS full disk encryption
### What did you expect to see?
Both results state that `/dev/dm-1`, a logical volume stacked on top of an encrypted physical volume, is encrypted
### What did you see instead?
Only the query without the `WHERE` clause has a result that states that `/dev/dm-1` is encrypted.

**Comment by jean** [comment]
The `disk_encryption` table is empty on a machine with encrypted ZFS.

```
12:48 jean@jean-ThinkPad-X1:~$ zfs get -p encryption
NAME                                              PROPERTY    VALUE        SOURCE
bpool                                             encryption  off          default
bpool/BOOT                                        encryption  off          default
bpool/BOOT/ubuntu_ypu2r2                          encryption  off          default
rpool                                             encryption  aes-256-gcm  -
rpool/ROOT                                        encryption  aes-256-gcm  -
rpool/ROOT/ubuntu_ypu2r2                          encryption  aes-256-gcm  -
rpool/ROOT/ubuntu_ypu2r2/srv                      encryption  aes-256-gcm  -
rpool/ROOT/ubuntu_ypu2r2/usr                      encryption  aes-256-gcm  -
rpool/ROOT/ubuntu_ypu2r2/usr/local                encryption  aes-256-gcm  -
rpool/ROOT/ubuntu_ypu2r2/var                      encryption  aes-256-gcm  -
...
```

```
osquery> SELECT * FROM disk_encryption;
osquery> 
```

**Comment by directionless** [comment]
@artemist-work I wonder if this is related to #7382

I don't think I have a clear test case, but I think there's something not-right in how osquery detects lvm-on-luks

**Comment by directionless** [comment]
I suspect this was fixed by https://github.com/osquery/osquery/pull/8052 which will land in 5.10. Feel free to reopen or comment if not.
