### ISSUE TITLE
Support querying auto-update on Linux Mint

### ISSUE THREAD

**Issue by jean** [osquery/osquery#7893]
# Feature request

### What new feature do you want?

Please enable querying for auto-update on Linux Mint

### How is this new feature useful?

Compliance platforms such as Drata use osquery to check for e.g. disk encryption, auto-update, password policy, screensaver activation, etc.

### How can this be implemented?

This is configured using a systemd timer that can be queried:

```
12:56 jean@jean-ThinkPad:~$ systemctl list-timers "mintupdate*"
NEXT                        LEFT     LAST                        PASSED       UNIT                                ACTIVATES                            
Sat 2022-12-17 00:22:47 +07 11h left Fri 2022-12-16 10:48:42 +07 2h 16min ago mintupdate-automation-upgrade.timer mintupdate-automation-upgrade.service

1 timers listed.
```

**Comment by directionless** [comment]
I'm not sure what you're asking for. 

If it's the timer settings, perhaps the `systemd_units` table can expose them

My experience with linux update systems, is that there is a huge amount of variation and dearth of reasonable APIs for them. So this isn't something that osquery can reasonable expose. There may be extensions that can provide this access. 

I'm going to close this, but I think we'd consider an implementation if someone had a viable one.,

**Comment by directionless** [comment]
Osquery should be able to expose state about systemd units. Have you tried doing this with the `systemd_units` table?

If the complaint is that Drata doesn't know how to use osquery to check the state, that's an issue for Drata.

**Comment by jean** [comment]
OK, that sounds like the correct solution, I'll open a request with Drata. Thank you!
