### ISSUE TITLE
Install osquery without GUI prompt or internet?

### ISSUE THREAD

**Issue by hexclann** [osquery/osquery#7898]
# Question

Is it possible to install osquery without using any GUI setup prompt and without relying on package managers such as choco or scoop?

**Comment by Smjert** [comment]
Hello @hexclann I suppose this is a question for Windows. MSI installers are uploaded on Github in the releases page (https://github.com/osquery/osquery/releases) or later on the osquery.io site (https://osquery.io/downloads/official/5.6.0).
You can then install them in quiet mode with no UI with `msiexec /i <MSI> /quiet /qn`.
