### ISSUE TITLE
Add support for Windows on Arm

### ISSUE THREAD

**Issue by pbo-linaro** [osquery/osquery#7901]
# Blueprint

Hello everyone,

at [Linaro](https://www.linaro.org/), we have a [Windows on Arm](https://www.linaro.org/windows-on-arm/) team that is helping open source projects to support this new platform (WoA), either by building, testing, or submitting patches.

osquery was reported by one of our customer and we would be very happy to implement support for this platform :+1: . This will mainly allow to have better performance, and to support Windows 10 (only x86 code is emulated, while x86_64 is emulated too on Win11).

So far, I succeeded to build osquery, by adding necessary config files. The only problem found is with [aws-sdk](https://github.com/aws/aws-sdk-cpp) and [lacking support of atomics in C99 for MSVC](https://github.com/awslabs/aws-c-common/blob/4b4675c0670a0a55ddfd37cb9eda3712eba31fc4/include/aws/common/atomics_msvc.inl#L20). I solved it by disabling this dependency with ```cmake -DOSQUERY_BUILD_AWS=OFF```.

Would you be interested by a PR to implement this support?

For now, in CI, we would have to use cross compilation, as there is no github Windows on Arm runners available yet.
That implies that tests won't be run.
Even if there is no release for the platform, it would still be nice to ensure it's buildable from source on WoA.

By the way, congrats for your build system. It's one of the cleanest I met, and things are very explicit.

Thanks for your feedback,
Pierrick

**Comment by pbo-linaro** [comment]
Before starting a PR, we have our fork with WoA support [here](https://gitlab.com/Linaro/windowsonarm/forks/osquery/-/tree/woa).
You can check this [build log](https://gitlab.com/Linaro/windowsonarm/packages/osquery/-/jobs/3558053644), done using this [script](https://gitlab.com/Linaro/windowsonarm/packages/osquery/-/blob/master/recipe.sh).

**Comment by mike-myers-tob** [comment]
Closed by https://github.com/osquery/osquery/pull/7918
