### ISSUE TITLE
Suspected memory leak when using macOS `unified_log` table

### ISSUE THREAD

**Issue by slai** [osquery/osquery#7914]
# Bug report

Each query using the unified_log table on macOS causes the resident_size value to increase and it does not decrease. When running as a daemon, this causes the watchdog to eventually kick in and restart the worker.

### What operating system and version are you using?

```
❯ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 13.1
   build = 22C65
platform = darwin
```

### What version of osquery are you using?

```
❯ osqueryi --line "SELECT version from osquery_info;"
version = 5.7.0
```

### What steps did you take to reproduce the issue?

```sh
❯ sudo osqueryi
Using a virtual database. Need help, type '.help'
osquery> select pid,resident_size,total_size,cmdline from processes where cmdline = "osqueryi";
+-------+---------------+------------+----------+
| pid   | resident_size | total_size | cmdline  |
+-------+---------------+------------+----------+
| 59090 | 21774336      | 6161536    | osqueryi |
+-------+---------------+------------+----------+
osquery> select count(*) from unified_log where timestamp >= (select unix_time-300 from time);
+----------+
| count(*) |
+----------+
| 100      |
+----------+
osquery> select pid,resident_size,total_size,cmdline from processes where cmdline = "osqueryi";
+-------+---------------+------------+----------+
| pid   | resident_size | total_size | cmdline  |
+-------+---------------+------------+----------+
| 59090 | 613826560     | 129059584  | osqueryi |
+-------+---------------+------------+----------+
osquery> select count(*) from unified_log where timestamp >= (select unix_time-300 from time);
+----------+
| count(*) |
+----------+
| 100      |
+----------+
osquery> select pid,resident_size,total_size,cmdline from processes where cmdline = "osqueryi";
+-------+---------------+------------+----------+
| pid   | resident_size | total_size | cmdline  |
+-------+---------------+------------+----------+
| 59090 | 1108295680    | 207343488  | osqueryi |
+-------+---------------+------------+----------+
osquery> select count(*) from unified_log where timestamp >= (select unix_time-300 from time);
+----------+
| count(*) |
+----------+
| 100      |
+----------+
osquery> select pid,resident_size,total_size,cmdline from processes where cmdline = "osqueryi";
+-------+---------------+------------+----------+
| pid   | resident_size | total_size | cmdline  |
+-------+---------------+------------+----------+
| 59090 | 1604091904    | 288773184  | osqueryi |
+-------+---------------+------------+----------+

```

### What did you expect to see?

I expected the resident_size value to remain similar after each query execution, at roughly the value before the first query execution.

It should **not** increase by roughly the same amount after each execution of the same query.

### What did you see instead?

The resident_size value increased by roughly the same amount, 500MiB, every time the same query was executed.

I can also reproduce this by using `osqueryi` to connect to an `osqueryd` extension socket, running the same query as above (adding around 500MiB), then running the same query again (adding another 500MiB again), and observing the watchdog (with a memory limit of 800MiB) kick in and restart the worker.

**Comment by slai** [comment]
We've switched our queries back to using the built-in `unified_log` table and after running them for a few weeks, I can confirm that there is no longer a memory leak when repeatedly querying the `unified_log` table in 5.12.2. Thanks @Micah-Kolide for the fix!

**Comment by Micah-Kolide** [comment]
I'm glad that PR solved the issue for you! Happy I could assist.
