### ISSUE TITLE
New Batch of OpenSSL CVEs (Feb 2023)

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#7936]
Some new OpenSSL CVEs were recently announced/addressed - see here: https://www.openssl.org/news/secadv/20230207.txt

Seems like a bump to [OpenSSL 1.1.1t ](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1t) may be warranted.  Osquery appears to be using 1.1.1q (July 2022).

**Comment by Smjert** [comment]
Thanks for the heads up, seems NIST is still analyzing these, although I can see that functions reading certificates are affected, so osquery might be affected in some way.
A PR is up to update it.
