### ISSUE TITLE
 yara using osquery

### ISSUE THREAD

**Issue by baharuddinzulkifli** [osquery/osquery#7940]
Hi team,

I want ask about how to use yara table in osquery.
https://osquery.readthedocs.io/en/stable/deployment/yara/. based on this documentation it state that yara table can be used to perform on demand yara scan. can i get reference how to do it.

I currently have custom yara rule (malicious.yar) to detect some sample in my host. 
Does it possible to perform thru osquery?

Thanks

**Comment by Zaulao** [comment]
Hey @baharuddinzulkifli, the Fleet team has an example [here](https://fleetdm.com/tables/yara)

```sql
SELECT * FROM yara WHERE path like '/root/%%' AND sigrule IN ( 'rule eicar {
  strings:
  $s1 = "X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*" fullword ascii
  condition:
  all of them
}' ) AND matches='eicar';
```

**Comment by baharuddinzulkifli** [comment]
Thanks @Zaulao . Really appreciate your help
