### ISSUE TITLE
Update OpenSSL to version 3.0.x

### ISSUE THREAD

**Issue by Samuel-Roach** [osquery/osquery#7942]
# Feature request

### What new feature do you want?

OpenSSL should be updated to be using version 3.0.x. OpenSSL 1 is EOLed for [2023-09-11](https://www.openssl.org/policies/releasestrat.html), and as such security fixes will stop being provided for OpenSSL. Before this occurs osquery should take OpenSSL version 3.0.x to receive continued updates and patches. The current OpenSSL 3.0.x EOL is  2026-09-07.

### How is this new feature useful?

This would provide osquery with further OpenSSL functionality, along with continued bug fixes and security patches.

**Comment by mburns83** [comment]
Is there a plan to update OpenSSL before the 1.1.1 line is EOLed in September?

**Comment by mburns83** [comment]
I suspect this can be closed as duplicated by [#7987](https://github.com/osquery/osquery/issues/7987) which was resolved by [#8081](https://github.com/osquery/osquery/pull/8081).
