### ISSUE TITLE
Osquery to fetch DNS records

### ISSUE THREAD

**Issue by Niba-nazar** [osquery/osquery#7952]
Hi,
Is there any method to use osquery in getting DNS records

**Comment by michael-myers** [comment]
There is no table in osquery for listing the DNS queries that have been made by the host, but there is a table for showing the DNS resolvers configured on the host: `select * from dns_resolvers;`

Capturing all DNS requests requires a system-specific approach, and there was a canceled attempt at this just for macOS, around ten years ago ([here](https://github.com/osquery/osquery/pull/561)). There's an unmaintained open-source extension by [Trail of Bits](https://github.com/trailofbits/osquery-extensions/tree/master/network_monitor) for Linux only, and other vendors might offer paid extensions for this, but it's not a feature of osquery.
