### ISSUE TITLE
Update leveldb to version 1.23

### ISSUE THREAD

**Issue by nick-yangZ** [osquery/osquery#7979]
# Update leveldb to version 1.23

### What new feature do you want?

leveldb 1.23 could be accessed in https://github.com/google/leveldb/releases/tag/1.23. It is recommended to upgrade to the latest version

**Comment by Smjert** [comment]
Hello @nick-yangZ, osquery does not make use of `leveldb`. All the libraries we are making use of are listed here: https://github.com/osquery/osquery/blob/master/libraries/third_party_libraries_manifest.json

I suspect that if you used some CVE scanning utility it might have confused some files in RocksDB as leveldb?

**Comment by mike-myers-tob** [comment]
Closing this issue, since osquery is not built with `leveldb`
