### ISSUE TITLE
Migrate openssl from 1.1.1 to 3.x

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7987]
In September openssl 1.x will be deprecated and will not receive any further update; therefore osquery should migrate to a 3.x version of openssl by then.

https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/

The article also contains a link to the migration guide.

**Comment by mburns83** [comment]
Is there a plan to update OpenSSL before the 1.1.1 line is EOLed in September?
