### ISSUE TITLE
osqueryi returns error when executing query with quotes in interactive mode

### ISSUE THREAD

**Issue by lszcs90** [osquery/osquery#7998]
# Bug report

### What operating system and version are you using?

 version = 10.0.19045
   build = 19045
platform = windows

### What version of osquery are you using?

version = 5.8.1

### What steps did you take to reproduce the issue?

1. Execute a query with quotes in interactive mode: 
```
c:\osquery>osqueryi.exe
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> "SELECT * FROM time;"
    ...> ;
```

### What did you expect to see?
Query executed, result displayed.

### What did you see instead?
```
Error: near ""SELECT * FROM time;"": syntax error
```

**Comment by talk2sohail** [comment]
You do not need to put quotes when executing the query inside the shell.

Simply write the query at the prompt.
```

osquery> select * from time;
       weekday = Tuesday
          year = 2023
         month = 5
           day = 16
          hour = 18
       minutes = 51
       seconds = 49
      timezone = UTC
local_timezone = IST
     unix_time = 1684263109
     timestamp = Tue May 16 18:51:49 2023 UTC
      datetime = 2023-05-16T18:51:49Z
      iso_8601 = 2023-05-16T18:51:49Z
```

**Comment by lszcs90** [comment]
Hello, 

Yes, I know that it works well without quotes. 

(But...) Usually command lines apps accepts both forms. For this (the one in the previous sentence) and because the message is not user-friendly, I consider that it would be something that could be improved here. 

Thanks.

**Comment by Smjert** [comment]
@lszcs90 I think you might be confusing when passing an argument to a program via a shell, where the quotes are used to mark that what you're passing is to be taken all together as a single argument, vs a shell command.

When you start osqueryi you're executing a custom shell with its own rules (much like bash, zsh, etc), and in those shells `"ls /etc"` would not be the same as `ls /etc`.

As for improving the error message, the error you're seeing comes from `sqlite`, which is what is and should be parsing the SQL query, I'm not sure how ideal is to add some custom parsing on top just to validate that case.

**Comment by lszcs90** [comment]
Thank you @Smjert . 
This can be closed.
