### ISSUE TITLE
Update Windows on ARM to a patched version of openssl 1.1.1t 

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#8006]
Currently openssl 1.1.1t does not build correctly for Windows on ARM and so the PR adding this new platform is reverting it to openssl 1.1.1s (https://github.com/osquery/osquery/pull/7918).
It would be desirable instead to use 1.1.1t and patch it with the fix necessary taken from the unreleased openssl version 1.1.1u.
Patching can be done after the library archive is extracted by the ExternalProject module in CMake, using `PATCH_COMMAND`.
https://cmake.org/cmake/help/latest/module/ExternalProject.html

While we are also waiting for an openssl 1.1.1u to be released for other active CVEs and also we have a migration to openssl 3.x waiting, I think that this might be easy enough to implement before the next release of osquery, without waiting for openssl to release or the migration to happen.

**Comment by pbo-linaro** [comment]
Closed by #7918
