### ISSUE TITLE
 osqueryd result build-ups on macOS causing network traffic build-up

### ISSUE THREAD

**Issue by ghambissa-li** [osquery/osquery#8017]
# Bug report
On macOS clients, osqueryd accumulates results in the RockDB folder (/var/osquery/osquery.db) over time, which leads to high network traffic when sending them to FleetDM servers. The network traffic decreases temporarily when the RockDB folder is manually cleared and osqueryd is restarted but increases again as the results build up.

### What operating system and version are you using?

 version = 13.3.1
   build = 22E261
platform = darwin

### What version of osquery are you using?
version = 5.7.0

### What steps did you take to reproduce the issue?
1. Install osqueryd on a macOS fleet and connect it to a FleetDM server.
2. Run some queries and observe the network traffic and the size of the RockDB folder.
3. Purge the RockDB folder and restart osqueryd.
4. Repeat step 2 and compare the results.
### What did you expect to see?
Cached result data in the RockDB folder should be purged periodically and/or when the results are sent to the FleetDM server successfully. And the network traffic from osqueryd clients should be fairly consistent.

### What did you see instead?
Network traffic from osqueryd increases on the clients over time.

**Comment by asterisk800** [comment]
Hi @Smjert, suppose a network issue prevents the client from posting results to FleetDM. What happens to the messages? Do they keep accumulating indefinitely?

**Comment by ghambissa-li** [comment]
Hi @Smjert, suppose a network issue prevents the client from posting results to FleetDM. What happens to the messages? Do they keep accumulating indefinitely?

**Comment by Smjert** [comment]
> Hi @Smjert, suppose a network issue prevents the client from posting results to FleetDM. What happens to the messages? Do they keep accumulating indefinitely?

In that case the expected behavior is to keep those messages and resend them when the backend goes up again, so you don't lose them. That been said there's a threshold there too which you can control with `--buffered_log_max`, which by default is at 1 million.

**Comment by ghambissa-li** [comment]
Thank you for the info on the bufferd_log_max setting. Here are my setting for the CL flags: buffered_log_max at 1,000,000, logger_tls_max_lines at 1,024, and logger_tls_period at 10. I am doing an investigation on the load balancer limits and see if that is what is contributing to the issue. I have observed this error on many clients "Error sending results to logger: Request error: Exceeded max of 10." However, these clients do not have any issues enrolling in FleetDM. That led me to think the issue could be on the load balancer.

**Comment by ghambissa-li** [comment]
Hi @Smjert, I wanted to confirm if my understanding is correct. The buffered_log_maxflag determines the maximum number of logs that can be buffered before a new log is dropped. Additionally, the logger_tls_max_lines flag limits each log to 1024 lines. Assuming an average line length of 100 characters, each line would hold approximately 100 bytes of data. Therefore, 1024 lines would hold 102,400 bytes or 0.1024 MB of data. Based on this estimate, the buffer can hold up to 0.1024 MB * 1000000 = 102400 MB OR 102.4 GB.

**Comment by Smjert** [comment]
> Hi @Smjert, I wanted to confirm if my understanding is correct. The buffered_log_maxflag determines the maximum number of logs that can be buffered before a new log is dropped. Additionally, the logger_tls_max_lines flag limits each log to 1024 lines. Assuming an average line length of 100 characters, each line would hold approximately 100 bytes of data. Therefore, 1024 lines would hold 102,400 bytes or 0.1024 MB of data. Based on this estimate, the buffer can hold up to 0.1024 MB * 1000000 = 102400 MB OR 102.4 GB.

Hello @ghambissa-li sorry for the late response.
The `buffered_log_max` flag controls how many log can be buffered/saved in the RocksDB database before **old** logs start to get deleted; new logs will still be getting queued.
As mentioned previously `--logger_tls_max_lines` limits how many log lines are **sent** each `--logger_tls_period`, not the log lines that are present in the log.
