### ISSUE TITLE
select * from file not working as expected

### ISSUE THREAD

**Issue by sreenik250** [osquery/osquery#8060]
I am using OSQuery version 5.2.3 in Debian
I have installed Visual Studio code in -->>  /mnt/c/Users/myname/AppData/Local/Programs/Microsoft VS Code

When I give the query
 SELECT path, directory from  file where  path like '%Microsoft%';

It displays only 
+-----------------------------------------------------+----------------------------------------------------+
| path                                                | directory                                          |
+-----------------------------------------------------+----------------------------------------------------+
| /mnt/c/Program Files/Microsoft Analysis Services/   | /mnt/c/Program Files/Microsoft Analysis Services   |
| /mnt/c/Program Files/Microsoft SQL Server/          | /mnt/c/Program Files/Microsoft SQL Server          |
| /mnt/c/Program Files/Microsoft Update Health Tools/ | /mnt/c/Program Files/Microsoft Update Health Tools |
+-----------------------------------------------------+----------------------------------------------------+

I am expecting the above Visual Studio Code folder also

Please throw some light

**Comment by sreenik250** [comment]
Thank you very much for the response

Already tried all the below queries.  No data

❯ osqueryi
Using a virtual database. Need help, type '.help'
osquery> SELECT path, directory from file where path like '/mnt/c/Users/myname/AppData/Local/Programs/Microsoft%';
osquery> SELECT path, directory from file where path like '/mnt/c/Users/myname/AppData/Local/Programs/M%';
osquery> SELECT path, directory from file where path like '/mnt/c/Users/myname/AppData/Local/Programs/%';
osquery> SELECT path, directory from file where path = '/mnt/c/Users/myname/AppData/Local/Programs';

**Comment by directionless** [comment]
I don't think there's an osquery bug here.
