### ISSUE TITLE
OSQuery in a container?

### ISSUE THREAD

**Issue by aronchick** [osquery/osquery#8071]
### What new feature do you want?

I'd love to run OSQuery in a container on the machine - the idea is to query across a bunch of machines. It'd be ok if osqueryd was already on the machines, could I just mount that (or the data source) into the container so that I could make decisions about what to do inside the container based on what the host had available?

### How is this new feature useful?

Would let me decide to schedule things to the host (based on OS Query results) or let me run things inside the container based on the hardware profile.

### How can this be implemented?

TBD!

**Comment by directionless** [comment]
I'm not quite sure what you're asking. 

Osquery is something like an API translation layer. It queries various API, mostly OS level and presents the data via a sql interface. You can run osquery in a container, but it may not have access to the underlying host OS APIs.
