### ISSUE TITLE
For MacOS, the socket_events table has no value in the status field

### ISSUE THREAD

**Issue by an4oys942** [osquery/osquery#8073]
# Bug report

### What operating system and version are you using?

SELECT version, build, platform FROM os_version;
+---------+--------+----------+
| version | build  | platform |
+---------+--------+----------+
| 13.3    | 22E252 | darwin   |
+---------+--------+----------+

### What version of osquery are you using?

SELECT version from osquery_info;
+---------+
| version |
+---------+
| 5.8.2   |
+---------+

### What steps did you take to reproduce the issue?
I perform query
select action, pid, remote_address, success, status, time from socket_events;
![image](https://github.com/osquery/osquery/assets/59088530/3a321608-5cd4-4109-bfee-d3b75966d784)

My osquery.flags file:
```
# CONFIG CONTROL
--config_plugin=filesystem
--config_path=/var/osquery/osquery.conf
--pidfile=/var/osquery/osqueryd.pidfile
--database_path=/var/osquery/osquery.db
--disable_extensions=true

# BEAUTIFY EVENTS
--host_identifier=hostname
--utc=true

# PERFOMANCE & WATCHDOG
# watchdog level: -1=disabled | 0=normal 200M, 25% CPU (9 sec) | 1=restrictive 100M, 18% CPU (9 sec)
--enable_monitor=true
--disable_watchdog=false
--watchdog_level=1
--watchdog_delay=5
--worker_threads=4
# kill all other osquery processes on restart
--force

# EVENT BASED TABLES
# for socket events BSM
--disable_audit=false
--audit_allow_config
--audit_allow_sockets
--audit_persist=true
# for process events ES
--disable_endpointsecurity=false
# for FIM events
# for es_process_file_events table. Log everything. You need to add exceptions - it's not complicates.
#--disable_endpointsecurity_fim=false
# for file_events table. Log only what is specified in .conf files_path.
--enable_file_events=true

--disable_events=false
--events_optimize=true
--events_expiry=600
--events_max=50000

# LOGGING LOCAL
--logger_plugin=filesystem
--logger_path=/var/osquery/logs
--logger_rotate=true
--logger_rotate_size=45000000
--logger_rotate_max_files=1

#disable status events (not automatically rotated, --logger_rotate only for result logs)
--logger_min_status=3
--logger_min_stderr=3
```

### What did you expect to see?
status field values

### What did you see instead?
empty status field

**Comment by sharvilshah** [comment]
`status` column is only available for linux.
Perhaps we should move that to the extended schema in the table spec
