### ISSUE TITLE
Support aarch64 on Windows

### ISSUE THREAD

**Issue by chrisdutz** [osquery/osquery#8098]
# Feature request

### What new feature do you want?

I would like to be able to use cmake to compile on Windows systems (mostly VMs) that are running on Macs M1 or M2 chips.

### How is this new feature useful?

I maintain many OS projects and need to be able to check the builds of these on many operating systems. Having to grab my old Mac book to start a Windows VM in order to test Windows is slightly annoying ;-)

### How can this be implemented?

I don't think there is much we need to do.
When I installed the openjdk-20 on my system with chocolatey, it worked, however I noticed that the Java runtime invalidly reported to be x86_64 ... this caused cmake to download and build correctly on Windows aarch64 ... it produced executables that worked nicely on that system, but when trying to use the binaries compiled on that system on a x86_64 system, I got "wrong architecture" errors. 

When I updated the JDK to one that correctly reports the os.arch, the build started failing.

So I think it might be super easy to support building on aarch64 windows machines, as generally already should work and we're just giving up early here:
https://github.com/cmake-maven-project/cmake-maven-project/blob/7e7929d1330f53cb8d7c1768784ef1acc680a2f8/cmake-common/src/main/java/com/googlecode/cmakemavenproject/OperatingSystem.java#L74

**Comment by Smjert** [comment]
Hello @chrisdutz I'm slightly confused, did you meant to open this on the `cmake-maven-project` repository?

**Comment by chrisdutz** [comment]
Öööhm ... now I'm super confused too ... cause I am 100% sure I was on that repo, when I opened it ... don't even know what osquery does ;-)

Sorry for that ... either I'm in real need of a holiday or github is ;-)
