### ISSUE TITLE
It's possible for display serial numbers to be identical

### ISSUE THREAD

**Issue by mattlorimor** [osquery/osquery#8106]
This probably isn't worth an issue, but I wasn't even sure where to raise the "concern". PR https://github.com/osquery/osquery/pull/7946 added the ability to query connected display information on macOS and was merged a couple months ago.

I felt it was worth mentioning that, for a whole host of reasons, `_spdisplays_display-serial-number` _may_ not be unique. This is increasingly likely to happen if one purchases identical monitors at the same time, and the monitor manufacturer doesn't play nice in the EDID data stored on the monitor. I am a victim of this. I have two Samsung monitors that appear identical to my macOS installation, and, as a result, will non-deterministically flip-flop their logical positioning after actions like a reboot or wake from sleep.

Here is an example of `system_profiler` output on my macOS machine with two identical Samsung TU872 monitors plugged into it:

```json
"spdisplays_ndrvs" : [
        {
          "_name" : "LF32TU87",
          "_spdisplays_display-product-id" : "706b",
          "_spdisplays_display-serial-number" : "30414c38",
          "_spdisplays_display-vendor-id" : "4c2d",
          "_spdisplays_display-week" : "0",
          "_spdisplays_display-year" : "0",
          "_spdisplays_displayID" : "5",
          "_spdisplays_pixels" : "3840 x 2160",
          "_spdisplays_resolution" : "3840 x 2160 @ 60.00Hz",
          "spdisplays_main" : "spdisplays_yes",
          "spdisplays_mirror" : "spdisplays_off",
          "spdisplays_online" : "spdisplays_yes",
          "spdisplays_pixelresolution" : "spdisplays_2160p",
          "spdisplays_resolution" : "3840 x 2160 @ 60.00Hz",
          "spdisplays_rotation" : "spdisplays_supported"
        },
        {
          "_name" : "LF32TU87",
          "_spdisplays_display-product-id" : "706b",
          "_spdisplays_display-serial-number" : "30414c38",
          "_spdisplays_display-vendor-id" : "4c2d",
          "_spdisplays_display-week" : "0",
          "_spdisplays_display-year" : "0",
          "_spdisplays_displayID" : "2",
          "_spdisplays_pixels" : "3840 x 2160",
          "_spdisplays_resolution" : "3840 x 2160 @ 60.00Hz",
          "spdisplays_mirror" : "spdisplays_off",
          "spdisplays_online" : "spdisplays_yes",
          "spdisplays_pixelresolution" : "spdisplays_2160p",
          "spdisplays_resolution" : "3840 x 2160 @ 60.00Hz",
          "spdisplays_rotation" : "spdisplays_supported"
        }
      ]
```

I don't know exactly how this feeds into a security-related thing or a technical back-end concern, but I can think of a couple things:

* If the table used to store the data assumes the serial number will be unique, there would be a potential problem. I suspect this is not the case.
* If any decisions are made by anybody utilizing the displays table and, subsequently, the `serial_number` column, and they assume the value will be unique, they are making a bad assumption.
  * Think somebody writing some machine profiling heuristic that takes connected displays into account. It's not accurate to assume that all display serial numbers reported will be unique. Not really osquery's problem since you're just the data query engine/provider.
  
Tagging people that this would possibly be relevant to: @cacab (PR author), @directionless (PR reviewer and code owner of changed files), @n8felton (original requester of this feature), @terracatta (asked a relevant question about feature use case in the feature request).

Actually, @n8felton's use case example of "wanting to count monitors in our fleet" is a great example of where one could shoot themselves in the foot. You may write the query, dismiss identical serials as "inaccurate data", and just dedup on the field not knowing that the data is totally accurate and that you _do possibly have_ multiple physical monitors out there with identical serial numbers.

In fact, I'd go so far as to say this scenario of non-unique serials on physically-different-but-identical-model-number monitors is _more likely_ to happen in an enterprise scenario since monitors are often purchased in bulk and of the same make and model.

If there is a documentation section that has little blurbs about each field in the table, it might be worth calling out that there is no guarantee that the `serial_number` will be unique - something that may surprise people.

I feel like I've went on long enough, but if you want to read _way_ too much about the problem, hit up [this MacRumors thread](https://forums.macrumors.com/threads/external-displays-swapping-arrangement-not-remembered.2320211/page-13?post=32357866#post-32357866).

**Comment by directionless** [comment]
Thanks so much for noting this.

I'm not sure there's a good thing for us to do. Similar to this, hardware serial numbers may not be unique, and this can confuse people trying to inventory off of them. Osquery has generally taken the route of accurately presenting data, but interpreting it is sometimes hard.

I don't feel strongly about whether it belongs in docs anywhere. I think it would be reasonable to update the schema to note something like `The serial number of the display. (may not be unique)` if you wanted to put up a PR.
