### ISSUE TITLE
Unable to download osquery packages

### ISSUE THREAD

**Issue by moitrasayan007** [osquery/osquery#8129]
Unable to download osquery packages

```
This site can’t be reachedThe connection was reset.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_RESET
```

Please fix this issue ASAP.

**Comment by zwass** [comment]
Can you provide more information about the steps to reproduce this?

**Comment by directionless** [comment]
We cannot easily reproduce this. Can you say more about the problem you're having? Where are you downing from?

**Comment by moitrasayan007** [comment]
> We cannot easily reproduce this. Can you say more about the problem you're having? Where are you downing from?

from ubuntu instances, we are getting this error ```09/14/2023 00:06:14 root [ERROR]: E:The repository 'https://pkg.osquery.io/deb deb Release' no longer has a Release file.

**Comment by phibid** [comment]
Indeed, seems that the URL https://pkg.osquerypackages.com/deb is not public anymore ?

![image](https://github.com/osquery/osquery/assets/43341255/6cefa7c6-f6b5-4c42-bc00-48e264c87737)

**Comment by Smjert** [comment]
@phibid, more than that I believe there always have been limitations on listing the files/objects, you would have to use S3 REST API to get them.

In any case, if you try to access `https://pkg.osquery.io/deb/dists/deb/Release` or `https://pkg.osquerypackages.com/deb/dists/deb/Release`, you can see that the file can be downloaded.

Everything works for me on Ubuntu, how do you have the repository specified?
I have:
```
deb [arch=amd64 signed-by=/usr/share/keyrings/osquery.gpg] https://pkg.osquery.io/deb deb main
```

**Comment by phibid** [comment]
We are using aptly to sync this repo, how it stopped working since the beginning of September, not sure if some something changed:

```
# aptly mirror update xenial-osquery
Downloading https://pkg.osquery.io/deb/dists/deb/InRelease...
Following redirect to https://pkg.osquerypackages.com/deb/dists/deb/InRelease...
Error downloading https://pkg.osquery.io/deb/dists/deb/InRelease: https://pkg.osquery.io/deb/dists/deb/InRelease: Get "https://pkg.osquerypackages.com/deb/dists/deb/InRelease": Forbidden retrying...
Retrying 0 https://pkg.osquery.io/deb/dists/deb/InRelease...
Giving up on https://pkg.osquery.io/deb/dists/deb/InRelease...
Downloading https://pkg.osquery.io/deb/dists/deb/Release...
Following redirect to https://pkg.osquerypackages.com/deb/dists/deb/Release...
Error downloading https://pkg.osquery.io/deb/dists/deb/Release: https://pkg.osquery.io/deb/dists/deb/Release: Get "https://pkg.osquerypackages.com/deb/dists/deb/Release": Forbidden retrying...
Retrying 0 https://pkg.osquery.io/deb/dists/deb/Release...
Giving up on https://pkg.osquery.io/deb/dists/deb/Release...
ERROR: unable to update: https://pkg.osquery.io/deb/dists/deb/Release: Get "https://pkg.osquerypackages.com/deb/dists/deb/Release": Forbidden
```

**Comment by Smjert** [comment]
ok that's strange, at this point I'm wondering if there's something blocking the redirect, or it's an issue on where you are (geographically) trying to access that URL from.

If you just try to access the https://pkg.osquerypackages.com/deb/dists/deb/InRelease url from your browser, does it work/wants you to download the file?

**Comment by asmith-1** [comment]
hey I had this issue after troubleshooting it a bit looked like TLS was getting reset, 

checked network firewall (Palo alto) seems that was blocking under URL filtering suggest anyone else having issues with deb packages check proxies/ firewalls

**Comment by directionless** [comment]
Around the beginning of September, I did change how this works. It's changed a lot over time, but during August, `pkg.osquery.io` redirect things to a direct s3 bucket URL. This was changed to redirect to a Cloudflare R2 URL. You can see this in:
```
Downloading https://pkg.osquery.io/deb/dists/deb/InRelease...
Following redirect to https://pkg.osquerypackages.com/deb/dists/deb/InRelease...
```

I'm not sure why you're getting Forbidden. It seems to work for a large number of people. Does `wget https://pkg.osquerypackages.com/deb/dists/deb/InRelease` work?

> Indeed, seems that the URL https://pkg.osquerypackages.com/deb is not public anymore ?

I'm not sure this ever worked, buckets don't usually generate indexes.

**Comment by asmith-1** [comment]
> Around the beginning of September, I did change how this works. It's changed a lot over time, but during August, `pkg.osquery.io` redirect things to a direct s3 bucket URL. This was changed to redirect to a Cloudflare R2 URL. You can see this in:
> 
> ```
> Downloading https://pkg.osquery.io/deb/dists/deb/InRelease...
> Following redirect to https://pkg.osquerypackages.com/deb/dists/deb/InRelease...
> ```
> 
> I'm not sure why you're getting Forbidden. It seems to work for a large number of people. Does `wget https://pkg.osquerypackages.com/deb/dists/deb/InRelease` work?
> 
> > Indeed, seems that the URL https://pkg.osquerypackages.com/deb is not public anymore ?
> 
> I'm not sure this ever worked, buckets don't usually generate indexes.

probably this https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000PPImCAO

assuming the osquerypackages.com domain is fresh by that definition  (whosis showing as 30/08/2023) 

@moitrasayan007 are you behind a web proxy / firewall for this?

**Comment by phibid** [comment]
@asmith-1 Ok, that explains, I did not notice this redirect :-) We have added `pkg.osquerypackages.com` in our Squid, and it now works as expected

Thanks !

**Comment by directionless** [comment]
Glad it's sorted out
