### ISSUE TITLE
Settings in osquery.flags not showing in osquery_flags table however settings in osquery.flags.default show up

### ISSUE THREAD

**Issue by chrisdaun** [osquery/osquery#8137]
# Bug report

### What operating system and version are you using?

`version = CentOS Linux release 7.9.2009 (Core)
   build = 
platform = rhel`

### What version of osquery are you using?

`version = 5.9.1`
### What steps did you take to reproduce the issue?
`1. Add --logger_plugin=syslog in the /etc/osquery/osquery.flags file`
`2. Run sudo osqueryi --line "SELECT value from osquery_flags where name = 'logger_plugin';"`
### What did you expect to see?
`value = syslog`
### What did you see instead?
`value = filesystem`

**Comment by Smjert** [comment]
Hello @chrisdaun, so first of all the default path osquery searches in is `/etc/osquery/osquery.flags`, but that default for the `--flagfile` flag only matters apparently on Windows, when it's osquery that's installing a service. In all other cases the flags are read from `/etc/osquery/osquery.flags.default if no `--flagfile` flag is passed.

**Comment by chrisdaun** [comment]
@Smjert,
Thanks for the reply.
In my situation I do have a /etc/osquery/osquery.flags file with flags in it but this seems to be completely ignored even though the service is configured to look for that file via the --flagfile set at startup.

**Comment by Smjert** [comment]
Just to be sure, how are you verifying that the daemon launched via the service doesn't have the flags set correctly?

Keep in mind that `osqueryi` is not a shell that connects to the daemon, it's a separate osquery instance that starts as a shell instead of a daemon.

**Comment by chrisdaun** [comment]
> Just to be sure, how are you verifying that the daemon launched via the service doesn't have the flags set correctly?
> 
> Keep in mind that `osqueryi` is not a shell that connects to the daemon, it's a separate osquery instance that starts as a shell instead of a daemon.

@Smjert 
I was running the following command to validate: `sudo osqueryi "SELECT * FROM osquery_flags WHERE default_value <> value";`

I also tried launching the daemon as a service with the `--verbose` flag via command line but I do not see any indication in the `osqueryd` service output that indicates it has loaded any of the flags in my `/etc/osquery/osquery.flags` file
Maybe this is not a valid method to validate?
I am not seeing anything being logged to syslog, `--logger_plugin=filesystem,syslog` is in my `/etc/osquery/osquery.flags` file

**Comment by Smjert** [comment]
So, first of all, don't use `osqueryi` to validate the configuration for the daemon, as mentioned before they are two different processes and they don't communicate.
If you want to do a test that the `osquery.flags` file is parsed correctly with the shell, you have to pass the `--flagfile` flag when you start the shell, pointing it to the file, like in the daemon case.

For the daemon case, if you want to verify by querying the `osquery_flags` table, you have to add a scheduled query into your configuration file, and configure the logger with `--logger_plugin=filesystem,syslog`, just to be sure (if the syslog logger is not working for some reason).

**Comment by chrisdaun** [comment]
> @chrisdaun Actually I keep forgetting that we have a method to connect, although I would not suggest to use it in production; you can open an `osqueryi` shell and then `.connect /var/osquery/osquery.em` (that should be the default path to the extension socket if you haven't changed it), then the query will run on the daemon.

@Smjert thanks a million for this.
I was able to validate yesterday via the scheduled query you recommended but this `.connect` method is way cleaner and I was able to use it just now.
I did have to run `osqueryi` with `sudo` for the `.connect` to work ;)

**Comment by chrisdaun** [comment]
opening an osqueryi shell with sudo and then .connect /var/osquery/osquery.em got me what I needed.
