### ISSUE TITLE
When used with context, `block_devices` is missing information

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#8152]
## Problem

@Micah-Kolide and I noticed an issue with https://github.com/osquery/osquery/pull/8037 -- Basically, the parent traversal doesn't work across LVM setups. 

The old code would traverse everything, and somewhat by design, it would first traverse parents, and if it encounters LVM, it would populate the LVM things. Then the children would find their parents, and we'd have correct data. _But_ in this PR, what we query the child, and get incomplete information. As I understand it, this is because udev cannot traverse up, to find a parent relationship for LVM volumes. Because we cannot traverse up, the implementation in #8037 won't work, and should be reverted.

This can be seen via a simple:
```
osquery> SELECT * FROM block_devices WHERE name LIKE '/dev/dm-5';
+-----------+-----------+--------+-------+----------+------------+--------------------------------------+------+-------+
| name      | parent    | vendor | model | size     | block_size | uuid                                 | type | label |
+-----------+-----------+--------+-------+----------+------------+--------------------------------------+------+-------+
| /dev/dm-5 | /dev/dm-4 |        |       | 16777216 | 512        | 0f66e552-fb10-4363-9d1c-a0455ba9ab91 | ext4 |       |
+-----------+-----------+--------+-------+----------+------------+--------------------------------------+------+-------+

osquery> SELECT * FROM block_devices WHERE name = '/dev/dm-5';
+-----------+--------+--------+-------+----------+------------+--------------------------------------+------+-------+
| name      | parent | vendor | model | size     | block_size | uuid                                 | type | label |
+-----------+--------+--------+-------+----------+------------+--------------------------------------+------+-------+
| /dev/dm-5 |        |        |       | 16777216 | 512        | 0f66e552-fb10-4363-9d1c-a0455ba9ab91 | ext4 |       |
+-----------+--------+--------+-------+----------+------------+--------------------------------------+------+-------+
```

## Potential Solutions

Brainstorming, I don't know if there are simple solutions. If we cannot traverse up, we only have somewhat messy options:
- Find another library. Maybe partd would work. But that has other tradeoffs
- Attempt to tell if we're a child, and then trigger a `select *` style behavior
- Attempt to traverse by guessing minor numbers

**Comment by Micah-Kolide** [comment]
The underlaying udev methods for determining the child->parent relationship is by traversing the syspath:
```
micahsorenson@micah-linux-opensuse-test:~> ls -l /sys/class/block/
total 0
lrwxrwxrwx 1 root root 0 Oct  3 22:02 dm-0 -> ../../devices/virtual/block/dm-0
lrwxrwxrwx 1 root root 0 Oct  3 22:02 dm-1 -> ../../devices/virtual/block/dm-1
lrwxrwxrwx 1 root root 0 Oct  3 22:02 dm-2 -> ../../devices/virtual/block/dm-2
lrwxrwxrwx 1 root root 0 Oct  3 22:02 dm-3 -> ../../devices/virtual/block/dm-3
lrwxrwxrwx 1 root root 0 Oct  3 22:02 dm-4 -> ../../devices/virtual/block/dm-4
lrwxrwxrwx 1 root root 0 Oct  4 02:25 dm-5 -> ../../devices/virtual/block/dm-5
lrwxrwxrwx 1 root root 0 Oct  4 02:25 dm-6 -> ../../devices/virtual/block/dm-6
lrwxrwxrwx 1 root root 0 Oct  4 02:25 dm-7 -> ../../devices/virtual/block/dm-7
lrwxrwxrwx 1 root root 0 Oct  4 02:25 dm-8 -> ../../devices/virtual/block/dm-8
lrwxrwxrwx 1 root root 0 Oct  4 02:25 dm-9 -> ../../devices/virtual/block/dm-9
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sda -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sda1 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda/sda1
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sda2 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda/sda2
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sda3 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda/sda3
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdb -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:2/0:0:2:0/block/sdb
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdb1 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:2/0:0:2:0/block/sdb/sdb1
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdb2 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:2/0:0:2:0/block/sdb/sdb2
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdb3 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:2/0:0:2:0/block/sdb/sdb3
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdc -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:3/0:0:3:0/block/sdc
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdc1 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:3/0:0:3:0/block/sdc/sdc1
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdc2 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:3/0:0:3:0/block/sdc/sdc2
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdd -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdd
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdd1 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdd/sdd1
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdd2 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdd/sdd2
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdd3 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdd/sdd3
lrwxrwxrwx 1 root root 0 Oct  3 21:49 sdd4 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:4/0:0:4:0/block/sdd/sdd4
```

As you can see for LVM devices this type of traversal is useless.

We could use the device major:minor properties with some recursion to try and determine the parent node, but this doesn't feel great as there could be `n` nodes between the child and parent.

**Comment by Smjert** [comment]
Maybe it makes sense to look at how `lsblk` works: https://github.com/util-linux/util-linux/blob/master/misc-utils/lsblk.c#L1804

Not saying that it will be straightforward, given that it's string parsing (with its many formats...) vs a more stable API, but I think that would be the most complete way I think to find the relationship.

**Comment by Smjert** [comment]
Also on the traversing up issue, I understand that the intention is to start from an arbitrary point of the tree and go up, but I would expect queries to `disk_encryption` to be rare, not be in a JOIN, and if they are, then the result should be cached with SQL using MATERIALIZED.
So what I'm suggesting therefore is to always construct the full tree from top to bottom on each SQL query to `disk_encryption`, and then use that datastructure to find the data you need.
You can then optimize it if you really want so that if the user passes a single device they are interested in, you can interrupt the tree construction when you find that device (as long as obviously the constraint is something unique).

**Comment by directionless** [comment]
Fixed by https://github.com/osquery/osquery/pull/8037
