### ISSUE TITLE
OSQuery 5.10.2 - Status Log Field Types have changed

### ISSUE THREAD

**Issue by liamn** [osquery/osquery#8173]
# Bug report

Following updates to OSQuery 5.10.2 - we noticed type casting issues with our OSQuery implementation. 

Previously, in the Status Log, both UnixTimestamp and Severity were sent as strings. Following the update to OSQuery 5.10.2, these have been changed to integers. 

**Whilst this is a welcome change, it doesn't appear the breaking change is called out in the release notes - could this be updated? 🙏** 

PR that introduces this change is here: https://github.com/osquery/osquery/pull/8102

### What operating system and version are you using?

```
version = 14.0
build = 23A339
platform = darwin
```

### What version of osquery are you using?

`version = 5.10.2`

### What steps did you take to reproduce the issue?

Following the roll out of 5.10.2, errors were observed by our Go TLS server, which failed to unmarshal these logs. 

### What did you expect to see?

This should be called out as a possible breaking change in the release notes - not asking for this to be reverted - as this now matches the format of results logs - which makes sense 🙏 

### What did you see instead?

No mention of this as a breaking change in the release notes.

**Comment by Smjert** [comment]
Hello @liamn, many thanks for the reminder and sorry for the distruption, this fell through the cracks!

**Comment by sharvilshah** [comment]
Thanks @liamn!

**Comment by liamn** [comment]
Thanks all! Not a huge issue - wanted to make sure other folks didn't have the same issue! Thanks for adding the call out! 👍
