### ISSUE TITLE
 osquery and yara 

### ISSUE THREAD

**Issue by dimaivanov1234** [osquery/osquery#8188]
Hello!How to integrate osquery and yara on windows?

**Comment by Smjert** [comment]
Hello @dimaivanov1234, that is a pretty broad question, and in general I would ask/suggest to use [osquery Slack](https://join.slack.com/t/osquery/shared_invite/zt-1wi6cdgf7-zR2wt7FZ0ClHj6tEym6KFQ) for questions as this.

You might want to have a look at https://osquery.readthedocs.io/en/latest/deployment/yara/, and hit us on Slack if you have a followup question.
