### ISSUE TITLE
Update the secureboot table to support macs running Apple silicon 

### ISSUE THREAD

**Issue by Patagonia121** [osquery/osquery#8195]
### What new feature do you want?

We want to update the `secureboot` table to work for MacOS. The configuration can be seen in the system profiler output: 

`% system_profiler -json SPiBridgeDataType
{
  "SPiBridgeDataType" : [
    {
      ...,
      "ibridge_secure_boot" : "Full Security"
    }
  ]
}`

### How is this new feature useful?

The `secureboot` osquery table was updated in 5.8.1 to work with intel-based macOS and the T2 chips. This being a UEFI specific currently, we need to update the schema to add Apple silicon macs and return similar data. 

### How can this be implemented?

Ultimately would like to reference this doc: https://support.apple.com/guide/mac-help/change-security-settings-startup-disk-a-mac-mchl768f7291/mac

**Comment by zwass** [comment]
If `system_profiler` provides the necessary data, we can probably use the same approach as in the `connected_displays` table: https://github.com/osquery/osquery/blob/master/osquery/tables/system/darwin/connected_displays.mm#L29-L95
