### ISSUE TITLE
macOS build failure with Xcode 15: "no template named 'unary_function' in namespace 'std'"

### ISSUE THREAD

**Issue by zwass** [osquery/osquery#8196]
# Bug report

### What operating system and version are you using?

macOS 14.1.1

### What version of osquery are you using?

`master` (`904409ebd7aa72397870c1cb8b861b78369ba994`)

### What steps did you take to reproduce the issue?

Build osquery

### What did you expect to see?

Successful build

### What did you see instead?

```
In file included from /Users/zwass/dev/osquery/libraries/cmake/source/boost/src/libs/thread/src/pthread/thread.cpp:11:
In file included from /Users/zwass/dev/osquery/libraries/cmake/source/boost/src/libs/thread/include/boost/thread/thread_only.hpp:22:
In file included from /Users/zwass/dev/osquery/libraries/cmake/source/boost/src/libs/thread/include/boost/thread/detail/thread.hpp:41:
In file included from /Users/zwass/dev/osquery/libraries/cmake/source/boost/src/libs/container_hash/include/boost/functional/hash.hpp:6:
/Users/zwass/dev/osquery/libraries/cmake/source/boost/src/libs/container_hash/include/boost/container_hash/hash.hpp:131:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
1 error generated.
```

@Smjert says this issue only appears with Xcode 15. I will attempt downgrade to Xcode 14.

**Comment by Smjert** [comment]
A useful comment: https://github.com/facebook/react-native/issues/37748#issuecomment-1580334650

Means we can have a workaround for the build, enabling _LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION here: https://github.com/osquery/osquery/blob/904409ebd7aa72397870c1cb8b861b78369ba994/cmake/flags.cmake#L257

Long term we have to update boost to a version that doesn't use that anymore (though boost is a bit hard to update).

**Comment by Smjert** [comment]
I've also found: https://github.com/boostorg/container_hash/issues/22

Using `BOOST_NO_CXX98_FUNCTION_BASE` might be better/more specific.
