### ISSUE TITLE
Auto update Osquery on Windows

### ISSUE THREAD

**Issue by Anthony-76** [osquery/osquery#8198]
# Feature request

### What new feature do you want?

Is it possible on Windows OS to auto update Osquery to the new next Release? (install automatically the new release without destroy the osquery.flags file)

### How is this new feature useful?

The auto update avoid to download manually the new release then install
If I install the new release, I haave to recreate the osquery.flags file...

### How can this be implemented?

Thank you
Anthony

**Comment by zwass** [comment]
You could use fleetd - It's an open source portion of [Fleet](https://fleetdm.com). See the docs in https://fleetdm.com/docs/using-fleet/enroll-hosts about how to build packages. These docs are oriented around using it with Fleet, but it's not a requirement.

**Comment by Anthony-76** [comment]
Hi,

Thank you for your answer.

Best regards
Anthony

**Comment by Anthony-76** [comment]
Closed
