### ISSUE TITLE
Querying safari_extensions returns nothing

### ISSUE THREAD

**Issue by asthakra** [osquery/osquery#8210]
# Bug report

### What operating system and version are you using?

```
 version = 14.1.2
   build = 23B92
platform = darwin
```

### What version of osquery are you using?

`version = 5.10.2`

### What steps did you take to reproduce the issue?

1. Added extensions to safari and made sure they're enabled.
2. Enabled FDA to osqueryd 
2. Ran the  query `SELECT * FROM safari_extensions WHERE uid IN ( SELECT uid FROM users ) ;`

### What did you expect to see?

Expected to see a table with installed extensions. 

### What did you see instead?

Nothing.

### Additional Info 

Tried the query mentioned here : https://github.com/osquery/osquery/issues/6498#issuecomment-1224359149 - for this the installed extensions are displayed.

**Comment by zwass** [comment]
Does `SELECT * FROM users CROSS JOIN safari_extensions USING (uid)` work?

**Comment by asthakra** [comment]
> Does `SELECT * FROM users CROSS JOIN safari_extensions USING (uid)` work?

This too returns nothing.
