### ISSUE TITLE
There are changes in the build environment

### ISSUE THREAD

**Issue by Jondoe398** [osquery/osquery#8316]
When compiling under Windows, it was found that some parts of the Boost project have changed, as follows.
https://github.com/facebook/rocksdb/commit/d9e71fb2c53726d9c5ed73b4ec962a7ed6ef15ec
![微信截图_20240424182048](https://github.com/osquery/osquery/assets/104404517/41797ec2-0547-46ba-8e5f-012354728208)

**Comment by Smjert** [comment]
Hello @Jondoe398 can you please expand on what is being reported here?
osquery does not use the Boost build system, since it rewrites it to hardcode the configuration. We are also not using/compiling those sources.

**Comment by Jondoe398** [comment]
> Hello @Jondoe398 can you please expand on what is being reported here? osquery does not use the Boost build system, since it rewrites it to hardcode the configuration. We are also not using/compiling those sources.

Sorry, I misspoke about the project.   Due to network fluctuations, the automatic build failed to download the RocksDB project, and I tried to go to Git myself, encountering these problems.   I think it's because I chose the wrong version.

**Comment by Smjert** [comment]
> Sorry, I misspoke about the project. Due to network fluctuations, the automatic build failed to download the RocksDB project, and I tried to go to Git myself, encountering these problems. I think it's because I chose the wrong version.

Ah I see; I also realized I got stuck with the mention of Boost and so couldn't find those source files mentioned. But if it's RocksDB, then yeah those files we build, but we hardcode everything to a fixed RocksDB version, which you can find here: https://github.com/osquery/osquery/blob/master/libraries/third_party_libraries_manifest.json#L261 (remember to browse the repo at the osquery version you are using)

Glad you solved.
