### ISSUE TITLE
Multiple osquery services

### ISSUE THREAD

**Issue by wishperr** [osquery/osquery#8335]
Hello,

On windows 10/11, is there a way to simultaneously run two osquery daemon services that use different flagfiles.
I tried to --install two services with different names, install paths, flagfiles, socket names, config/db paths, but i was never able to get both of them running at the same time.

Thank you in advance!

**Comment by Smjert** [comment]
You additionally need to pass a different `--pidfile` path and --logging_path` (if using the `filesytem` plugin for logging too)

**Comment by wishperr** [comment]
Thank you for the information.

Unfortunately that has the same results.
Here is my scenario:

I have a standard osquery installation, without any custom configs. That installs and runs the osquery daemon service without any issues. Install location - `C:\Program Files\osquery`
Then i have a second folder with the osquery files in it, through which i install the service
`.\osqueryd-second.exe --install --flagfile "C:\Program Files\agent\osquery\osquery-windows.flags" --config_path="C:\Program Files\agent\osquery\osquery.conf" --database_path="C:\Program Files\agent\osquery\osqueryd\osquery.db" --pidfile="C:\Program Files\agent\osquery\osqueryd\osquery.pid" --extensions_socket="\\.\pipe\osquery-second.em" --logger_path="C:\Program Files\agent\osquery\osqueryd\logs" --verbose`

The flagfile that i use for the second service has the following content:
`--audit_allow_config=true
--audit_allow_sockets
--audit_persist=true
--disable_audit=false
--disable_logging
--disable_database
--enable_powershell_events_subscriber
--enable_windows_events_subscriber
--events_expiry=1
--events_max=500000
--watchdog_memory_limit=350
--watchdog_utilization_limit=130
--socket=\\.\pipe\osquery-second.em`

With the above command, the osquery-second daemon service is created, but it will not start while the original osquery service is running and vice versa.

**Comment by directionless** [comment]
Your second one is missing the `pidfile` argument, as Stefano suggested. 

Does it log anything about why it won't start?
