### ISSUE TITLE
Chemistry column always empty for MAC in battery table 

### ISSUE THREAD

**Issue by dvoota** [osquery/osquery#8372]
# Bug report
The chemistry column is always empty for MAC in the battery table

### What operating system and version are you using?
 version = 14.5
   build = 23F79
platform = darwin

### What version of osquery are you using?
version = 5.12.2

### What steps did you take to reproduce the issue?
select chemistry from battery;

### What did you expect to see?
The chemistry column should have the value

### What did you see instead?
Chemistry column is empty

**Comment by directionless** [comment]
Osquery works by querying various APIs for information. The `chemistry` information is not part of the macOS apis, and I do not know if there's a way we could find it.

It is only part of the windows APIs, thus it appears in the windows versions of the table
