### ISSUE TITLE
Collect accepted network connection events on macOS

### ISSUE THREAD

**Issue by bgirardeau-figma** [osquery/osquery#8379]
# Feature request

### What new feature do you want?

Collect accepted network connection events on macOS in the `socket_events` table. Currently actions collected are `bind`, `listen`, and `close`, but there is not visibility into when a bound socket accepts a new connection. The `process_open_sockets` table can show this information for long lived connections, but it won't capture short lived connections to a local server that disappear before a scheduled query runs.

### How is this new feature useful?
This feature would give visibility into connections to locally running servers, for example if a remote IP connects to a locally running development server or to track which local applications communicate with a device authorization application like Okta Verify.

### How can this be implemented?

Configure [this code](https://github.com/osquery/osquery/blob/e4ff72ee0b88e3101ad36cc6328d4634fab7f483/osquery/tables/events/darwin/socket_events.cpp#L72-L79) to listen for `AUE_ACCEPT` events and update [this function](https://github.com/osquery/osquery/blob/e4ff72ee0b88e3101ad36cc6328d4634fab7f483/osquery/tables/events/darwin/socket_events.cpp#L81) to process them correctly.

**Comment by zwass** [comment]
@bgirardeau-figma unfortunately I don't think that OpenBSM Audit provides the important information you are looking for here (remote address). Is this still useful for you if it provides local address only?

I got most of the way to implementing it (which was thankfully easier than expected) before noticing that the info is not provided. To double-check, I started a Python web server and used `sudo praudit -l -x /dev/auditpipe | grep python` (followed by `curl http://localhost:8000` to that server) to check out the events:

```
<record version="11" event="accept(2)" modifier="0" time="Thu Dec 19 06:56:06 2024" msec=" + 230 msec" ><argument arg-num="1" value="0x3" desc="fd" /><socket-inet type="2" port="58889" addr="127.0.0.1" /><subject audit-uid="zwass" uid="zwass" gid="staff" ruid="zwass" rgid="staff" pid="62392" sid="100004" tid="50331650 0.0.0.0" /><return errval="success" retval="6" /><identity signer-type="0" signing-id="org.python.python" signing-id-truncated="no" team-id="" team-id-truncated="no" cdhash="0x19342e1de42694aa0b6f8c3afd915ecdb2c15675" /></record>
<record version="11" event="recvfrom(2)" modifier="0" time="Thu Dec 19 06:56:06 2024" msec=" + 230 msec" ><argument arg-num="1" value="0x6" desc="fd" /><subject audit-uid="zwass" uid="zwass" gid="staff" ruid="zwass" rgid="staff" pid="62392" sid="100004" tid="50331650 0.0.0.0" /><return errval="success" retval="77" /><identity signer-type="0" signing-id="org.python.python" signing-id-truncated="no" team-id="" team-id-truncated="no" cdhash="0x19342e1de42694aa0b6f8c3afd915ecdb2c15675" /></record>
<record version="11" event="sendto(2)" modifier="0" time="Thu Dec 19 06:56:06 2024" msec=" + 230 msec" ><argument arg-num="1" value="0x6" desc="fd" /><subject audit-uid="zwass" uid="zwass" gid="staff" ruid="zwass" rgid="staff" pid="62392" sid="100004" tid="50331650 0.0.0.0" /><return errval="success" retval="17" /><identity signer-type="0" signing-id="org.python.python" signing-id-truncated="no" team-id="" team-id-truncated="no" cdhash="0x19342e1de42694aa0b6f8c3afd915ecdb2c15675" /></record>
... much more recvfrom and sendto ...
<record version="11" event="shutdown(2)" modifier="0" time="Thu Dec 19 06:56:06 2024" msec=" + 231 msec" ><argument arg-num="1" value="0x6" desc="fd" /><subject audit-uid="zwass" uid="zwass" gid="staff" ruid="zwass" rgid="staff" pid="62392" sid="100004" tid="50331650 0.0.0.0" /><return errval="success" retval="0" /><identity signer-type="0" signing-id="org.python.python" signing-id-truncated="no" team-id="" team-id-truncated="no" cdhash="0x19342e1de42694aa0b6f8c3afd915ecdb2c15675" /></record>
```

It does seem like you could at least use this to determine whether it's a remote connection as that would show a non-localhost address for the `accept` event (example when connecting from a VM on the local network):

```
<record version="11" event="accept(2)" modifier="0" time="Thu Dec 19 07:10:21 2024" msec=" + 256 msec" ><argument arg-num="1" value="0x3" desc="fd" /><socket-inet type="2" port="59411" addr="192.168.1.200" /><subject audit-uid="zwass" uid="zwass" gid="staff" ruid="zwass" rgid="staff" pid="62392" sid="100004" tid="50331650 0.0.0.0" /><return errval="success" retval="6" /><identity signer-type="0" signing-id="org.python.python" signing-id-truncated="no" team-id="" team-id-truncated="no" cdhash="0x19342e1de42694aa0b6f8c3afd915ecdb2c15675" /></record>
```

I am investigating whether it's possible to get the remote address through some other mechanism.

**Comment by zwass** [comment]
Actually it looks like I misinterpreted the networking from my VM. Requests from the VM appear to come from the localhost IP but when I make a request from a different machine on the same network I actually see that machine's IP!

**Comment by zwass** [comment]
Glad this is working because it doesn't seem that NetworkExtension supports what we want to do here (https://forums.developer.apple.com/forums/thread/751077)

Note that the values reported in the `port` field don't seem to match up with the local or remote ports. I checked pretty thoroughly by creating a server that accepts TCP connections, logs them, and lets them sit open. The logged remote port and the port seen on the remote machine via `lsof` match each other, but don't match the port in the Audit event.

I'm not sure if this is broken or has some as-yet-undetermined significance.

**Comment by bgirardeau-figma** [comment]
Interesting I'll try to submit feedback to Apple for adding this to NetworkExtension or Endpoint Security framework in future before OpenBSM audit is removed.

That's weird about the ports, I'm most interested in remote address but of course would be nice to understand the port field too.
