### ISSUE TITLE
Collect additional process IDs and process ID versions in macOS Endpoint Security tables

### ISSUE THREAD

**Issue by bgirardeau-figma** [osquery/osquery#8380]
# Feature request

### What new feature do you want?
Collect additional process ID fields and process ID versions for the `es_process_events` table in macOS:
* `session_id`
* `responsible_pid`
* `responsible_pidversion`
* `parent_pidversion`
* `pidversion`

Also update `es_process_file_events` with PID version fields where available for correlation.

### How is this new feature useful?

Responsible PID is helpful for understanding inheritance of TCC permissions. Session ID is useful to correlate commands and process groups across a session. See https://themittenmac.com/threat-hunting-pids-within-apples-es-api/ for more discussion of these. 

The PID version fields are useful to disambiguate PIDs from each other when they are reused, so that we can form an accurate process tree based on the es_process_events data. The PID version is contained in the audit token (more details [here](https://knight.sc/reverse%20engineering/2020/03/20/audit-tokens-explained.html))

### How can this be implemented?
Add logic to these files to extract the new fields where applicable:
* osquery/events/darwin/endpointsecurity.cpp
* osquery/events/darwin/endpointsecurity.h
* osquery/events/darwin/es_utils.cpp
* osquery/tables/events/darwin/es_process_events.cpp
* osquery/tables/events/darwin/es_process_file_events.cpp
* specs/darwin/es_process_events.table
* specs/darwin/es_process_file_events.table

PID versions are available from the audit tokens in [es_process_t](https://developer.apple.com/documentation/endpointsecurity/es_process_t) structure using `audit_token_to_pidversion` function

**Comment by zwass** [comment]
Here's the `audit_token_to_pidversion` @bgirardeau-figma refers to: https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX11.0.sdk/usr/include/bsm/libbsm.h#L1598-L1610

For the new columns, it seems to me that these are the sources:

| Column | Source |
| ------- | ------- |
| `session_id` | [`session_id`](https://developer.apple.com/documentation/endpointsecurity/es_process_t/3366185-session_id?language=objc) |
| `responsible_pid` | `audit_token_to_pid(`[`responsible_audit_token`](https://developer.apple.com/documentation/endpointsecurity/es_process_t/3684982-responsible_audit_token?language=objc)) |
| `responsible_pidversion` | `audit_token_to_pidversion(`[`responsible_audit_token`](https://developer.apple.com/documentation/endpointsecurity/es_process_t/3684982-responsible_audit_token?language=objc)) |
| `parent_pidversion` | `audit_token_to_pidversion(`[`ppid`](https://developer.apple.com/documentation/endpointsecurity/es_process_t/3228981-ppid?language=objc)) |
| `pidversion` | `audit_token_to_pidversion(`[`audit_token`](https://developer.apple.com/documentation/endpointsecurity/es_process_t/3228975-audit_token?language=objc)) |

Does that seem like what you intend @bgirardeau-figma?

**Comment by bgirardeau-figma** [comment]
Yes that looks right, thanks!
