### ISSUE TITLE
Segmentation faults in Fedora 38+ when querying `rpm_packages`

### ISSUE THREAD

**Issue by lucasmrod** [osquery/osquery#8384]
# Bug report

### What operating system and version are you using?

Reproduced in Fedora Workstation 38 and Fedora Workstation 40.
(I haven't tested older versions of Fedora, the bug might be there too).

### What version of osquery are you using?

v5.12.1, v5.12.2

### What steps did you take to reproduce the issue?

Run the following query as distributed query (can probably be reproduced as scheduled query too) on Fedora 38+ systems:
```sql
select 1 from rpm_packages rp, os_version ov where rp.name = "foo-fedora-playbooks" AND ov.name = "Fedora Linux";
``` 

### What did you expect to see?

osqueryd executes the query successfully.

### What did you see instead?

osqueryd crashes 60% of the time with a segmentation fault when running the above query. See [segfault.txt](https://github.com/user-attachments/files/16366794/segfault.txt).

### Discussions

- Slack thread with discussion: https://osquery.slack.com/archives/C08V7KTJB/p1720792822595459
- Original issue in Fleet: https://github.com/fleetdm/fleet/issues/20594.

### More information

- Since Fedora 33, the RPM database is a sqlite database (CentOS 7 and older systems use Berkeley DB). As stated by @Smjert in the Slack thread, it seems there's an issue with librpm registering sqlite3_log (also set by osquery) and causing issues with callbacks.
- osquery is currently using librpm 4.18.0, there are 4.18.1 and 4.18.2 releases available. Perhaps we should upgrade to 4.18.2 and test if it fixes the issue (I can see a `Don’t muck with per-process global sqlite configuration from the db backend`, see https://patchwork.yoctoproject.org/project/oe-core/patch/20230703065909.45555-1-anuj.mittal@intel.com/).
- There's also 4.19.0 available (Fedora 39 and 40 use RPM 4.19.0).

**Comment by lucasmrod** [comment]
@Smjert @directionless I can confirm this fixes the crash in Fedora 38 and 40. Thank you!

Does this warrant a 5.13.1? (given the segfaults/crashes in Fedora 33+ systems when querying `rpm_packages`)

**Comment by directionless** [comment]
> Does this warrant a 5.13.1? (given the segfaults/crashes in Fedora 33+ systems when querying `rpm_packages`)

I think it does. I was hoping we could get https://github.com/osquery/osquery/pull/8392 in, but maybe we should just cut a point release
