### ISSUE TITLE
alf table returns no results on macOS 15 Sequoia

### ISSUE THREAD

**Issue by ddribeiro** [osquery/osquery#8395]
# Bug report

### What operating system and version are you using?

```
osquery> SELECT version, build, platform FROM os_version;
+---------+----------+----------+
| version | build    | platform |
+---------+----------+----------+
| 15.0    | 24A5309e | darwin   |
+---------+----------+----------+
```
### What version of osquery are you using?

```
osquery> SELECT version from osquery_info;
+---------+
| version |
+---------+
| 5.12.1  |
+---------+
```

### What steps did you take to reproduce the issue?
I ran `SELECT * FROM alf;` on a host running macOS 15 beta 5.

### What did you expect to see?
I expected to see results that showed the status of the built-in macOS firewall

### What did you see instead?
My query returned no results.
It seems this is because the `alf` table for macOS [references](https://github.com/osquery/osquery/blob/12e588c9c927286d324bc9a5dd80b3ae434c6ffe/specs/darwin/alf.table#L14) `/Library/Preferences/com.apple.alf.plist`. This file does not appear to be present in macOS 15.

**Comment by directionless** [comment]
Unfortunately, yes. We thought it might be exposed in another plist (See #8371) but that plist wasn't actually updated, so we reverted that change (See #8378). 

The only way I know to get at this, is to exec `socketfilterfw`, and osquery does not exec. I'm not sure there's a route for this data.

**Comment by zwass** [comment]
Actually it looks like we could use a similar approach to what we use with [secureboot](https://github.com/osquery/osquery/commit/2bd7e8660881b2863811a04e34f8ff3d2d748a3d). The data seems to be available via `SPFirewallDataType`.

On macOS 14:

```
system_profiler SPFirewallDataType
Firewall:

    Firewall Settings:

      Mode: Limit incoming connections to specific services and applications
      Applications:
          com.amazon.Amazon-Chime: Allow all connections
          com.apple.controlcenter: Allow all connections
      Firewall Logging: Yes
      Stealth Mode: No
```

Also seems to work on macOS 15.
