### ISSUE TITLE
Compile error in StringView.h of aws-crt-cpp with c++20 or later

### ISSUE THREAD

**Issue by NEIL-smtg** [osquery/osquery#8417]
# Bug report
I work on MSVC compiler testing, and we regularly build popular open-source project including OSQuery, with development builds of MSVC in order to find and fix regressions before they ship and cause problems for you.

Recently, when I build OSQuery with /std:c++20 or later, an error was encountered in the aws-crt-cpp. I saw that the commit of aws-crt-cpp that used by OSQuery was 3 years ago. I have submitted an issue about this error at https://github.com/awslabs/aws-crt-cpp/issues/655 and recently they have committed a [fix ](https://github.com/awslabs/aws-crt-cpp/pull/659) for this issue. Any chance you guys can update the hash of aws-crt-cpp?

### What operating system and version are you using?
Windows 11

### What version of osquery are you using?
Latest commit

### What steps did you take to reproduce the issue?

1. Open X64 Native Tools Command Prompt for VS 2022
2. git clone https://github.com/osquery/osquery.git
3. mkdir osquery\build 
4. cd osquery\build
5. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set \_CL\_=/std:c++latest /Zc:strictStrings- /Zc:char8_t-
6.  cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 .. 2>&1
7. cmake --build . --target osqueryd --config Release --verbose -- /maxcpucount 2>&1

### What did you expect to see?
Build successful.

### What did you see instead?
```c++
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(856): error C3878: syntax error: unexpected token ',' following 'simple-type-specifier'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(856): note: missing one of: ( { ?
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(856): error C3878: syntax error: unexpected token ',' following 'simple-declaration'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(856): note: error recovery skipped: ','
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(856): error C2760: syntax error: '>' was unexpected here; expected 'declaration'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C3878: syntax error: unexpected token ',' following 'simple-type-specifier'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): note: missing one of: ( { ?
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C2760: syntax error: ',' was unexpected here; expected ';'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C3878: syntax error: unexpected token ',' following 'jump-statement'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): note: error recovery skipped: ','
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C2760: syntax error: '>>' was unexpected here; expected 'declaration'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C2760: syntax error: ')' was unexpected here; expected 'expression'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C2760: syntax error: ')' was unexpected here; expected ';'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): error C3878: syntax error: unexpected token ')' following 'expression-statement'
C:\gitP\facebook\osquery\libraries\cmake\source\aws-sdk-cpp\src\aws-crt-cpp\include\aws/crt/StringView.h(857): note: error recovery skipped: ')'
```

Note:
Full build log: [os.log](https://github.com/user-attachments/files/16902487/os.log)

**Comment by michael-myers** [comment]
@NEIL-smtg that's awesome that you've contributed a fix upstream in the AWS SDK.

This issue is to update the version of AWS SDK osquery builds with, which is possibly a duplicate of this issue:
https://github.com/osquery/osquery/issues/8407

**Comment by NEIL-smtg** [comment]
@michael-myers Alright, I will go ahead to close this since it's a duplicate issue.

**Comment by Smjert** [comment]
@NEIL-smtg thanks for the heads up though!
The AWS SDK is quite involved to update (since we have to hardcode its build system every time), so it might take "a moment" since it happens.

**Comment by NEIL-smtg** [comment]
@Smjert Totally understood. Thanks for the update!
