### ISSUE TITLE
Battery table reports incorrect data for MAC M1(Apple M1 Pro)

### ISSUE THREAD

**Issue by dvoota** [osquery/osquery#8429]
# Bug report
1) The Condition column is always empty.
2) We observed that battery health reports "Check Battery" sometimes

### What operating system and version are you using?

+---------+-------+----------+
| version | build | platform |
+---------+-------+----------+
| 14.6.1  | 23G93 | darwin   |
+---------+-------+----------+

### What version of osquery are you using?
osqueryi version 5.12.2

### What steps did you take to reproduce the issue?
select condition, health from battery;

### What did you expect to see?
1) The Condition column should not be empty.
2) Battery health should be Good or Fair or Poor

### What did you see instead?
1) The Condition column is always empty.
2) We observed that battery health reports "Check Battery" sometimes

**Comment by directionless** [comment]
This table reports the data as it's returned by Apple's API. A bunch of this changed with the m1 macs. Some discussion at https://github.com/osquery/osquery/issues/6800
