### ISSUE TITLE
lz4 build error on windows

### ISSUE THREAD

**Issue by morning-star-001** [osquery/osquery#8436]
###While i have been able to build for MacOS, It's been impossible building for windows x64, the error below always comes up no matter what is tried:

  [1/3864] Building C object libs/src/lz4/CMakeFiles/thirdparty_lz4.dir/src/lib/lz4hc.c.obj
  FAILED: libs/src/lz4/CMakeFiles/thirdparty_lz4.dir/src/lib/lz4hc.c.obj 
  C:\Strawberry\c\bin\gcc.exe -DNDEBUG -DNTDDI_VERSION=NTDDI_WIN7 -D_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING -D_WIN32_WINNT=_WIN32_WINNT_WIN7  -O2 -g -DNDEBUG /Gs /GS /Ot /guard:cf /bigobj /W0 -MD -MT libs/src/lz4/CMakeFiles/thirdparty_lz4.dir/src/lib/lz4hc.c.obj -MF libs\src\lz4\CMakeFiles\thirdparty_lz4.dir\src\lib\lz4hc.c.obj.d -o libs/src/lz4/CMakeFiles/thirdparty_lz4.dir/src/lib/lz4hc.c.obj -c C:/Users/user/Documents/osquery/libraries/cmake/source/lz4/src/lib/lz4hc.c
C:\Users\user\Documents\osquery\gcc.exe : warning : /Gs: linker input file unused because linking not done
C:\Users\user\Documents\osquery\gcc.exe : error : /Gs: linker input file not found: No such file or directory
C:\Users\user\Documents\osquery\gcc.exe : warning : /GS: linker input file unused because linking not done
C:\Users\user\Documents\osquery\gcc.exe : error : /GS: linker input file not found: No such file or directory
C:\Users\user\Documents\osquery\gcc.exe : warning : /Ot: linker input file unused because linking not done
C:\Users\user\Documents\osquery\gcc.exe : error : /Ot: linker input file not found: No such file or directory
C:\Users\user\Documents\osquery\gcc.exe : warning : /guard:cf: linker input file unused because linking not done
C:\Users\user\Documents\osquery\gcc.exe : error : /guard:cf: linker input file not found: No such file or directory
C:\Users\user\Documents\osquery\gcc.exe : warning : /bigobj: linker input file unused because linking not done
C:\Users\user\Documents\osquery\gcc.exe : error : /bigobj: linker input file not found: No such file or directory
C:\Users\user\Documents\osquery\gcc.exe : warning : /W0: linker input file unused because linking not done
C:\Users\user\Documents\osquery\gcc.exe : error : /W0: linker input file not found: No such file or directory

**Comment by michael-myers** [comment]
Do you think you might have encountered the path length limitation of Windows mentioned in the build instructions? https://osquery.readthedocs.io/en/latest/development/building/#windows-10

**Comment by Smjert** [comment]
@michael-myers @morning-star-001 The problem here is that it's trying to compile with gcc on Windows, which is not supposed to, which suggests something went wrong when configuring the project with CMake.
Are you sure you've followed the steps as written in the guide linked by @michael-myers?

If you still have issues, can you please provide the cmake command line you have used to configure and the complete output?

**Comment by morning-star-001** [comment]
Okay, I'll follow the guide, and revert
________________________________

**Comment by Smjert** [comment]
I'm going to close this issue; if you still have build problems, you can also hit us on Slack https://join.slack.com/t/osquery/shared_invite/zt-1wi6cdgf7-zR2wt7FZ0ClHj6tEym6KFQ
