### ISSUE TITLE
Question about interval execution queries and muti queries in same time

### ISSUE THREAD

**Issue by Anthony-76** [osquery/osquery#8474]
Hi,

In my Osquery configuration file, I execute multi queries with the same interval and others with differents intervals

Resultats are sent to my SIEM each 45 seconds. (with this parameter --logger_tls_period=45)

When a long query is executed (during 5 minutes), others are not executed (or stuck). 

Moreover, during this execution time of my long request, no result are sent to my SIEM.

I found no option on Osquery documentation allowing to execute in a same time multi query.

My question is: How to execute multi queries in a same time (long and short execution time query ) and sent the result each 45s ?

I hope that my question is clear....
Best regards
Anthony

**Comment by directionless** [comment]
Osquery's general goal is low impact, periodic, data collection. It is not designed to run queries on a precise schedule. 

Osquery uses a single thread for executing scheduled queries. They will be run one at a time. Additionally there are some underlying mechanisms to splay out execution time.

What kind of use case is pushing you to wanting tighter control here?

**Comment by Anthony-76** [comment]
Thank you for your answer. I understand now
